### ISSUE TITLE
preventing increment and decrements year drop down ?

### ISSUE THREAD

**Issue by kesavan49** [Hacker0x01/react-datepicker#1000]
Hi ,

Thanks for wonderful library.

is there any way to prevent increment and decrement year in drop down ?

Thanks in advance.

**Comment by tohjustin** [comment]
Hi @kesavan49, could you elaborate more on this? Which example on https://hacker0x01.github.io/react-datepicker/ are you currently referring to? =0

**Comment by kesavan49** [comment]
Hi tohujstin,

Thanks for response.

I am referring example24 (https://hacker0x01.github.io/react-datepicker/#example-24).

There is one requirement where i need to restrict user to not select more current year(Ex. 2017).

i dont know wheter i can touch this source code. But changed source and made build.

They changes are,

1. year_dropdown.jsx

`  renderDropdown = () => {
    const minYear = this.props.minDate ? this.props.minDate.year() : 1900
    const maxYear = this.props.maxDate ? this.props.maxDate.year() : 2100
    return (
    <WrappedYearDropdownOptions
        key="dropdown"
        ref="options"
        year={this.props.year}
        onChange={this.onChange}
        onCancel={this.toggleDropdown}
        scrollableYearDropdown={this.props.scrollableYearDropdown}
        yearDropdownItemNumber={this.props.yearDropdownItemNumber}
        **minYear={minYear}
        maxYear={maxYear**} />
    )
  }`

2. year_dropdown.jsx

`function generateYears (year, noOfYear) {
  var list = []
  for (var i = 0; i < noOfYear; i++) {
    list.push(year - i)
  }
  return list
}`

`  incrementYears = () => {
    if (this.state.maxYear && (this.state.maxYear <= this.state.yearsList[0])) {
      return
    } else {
      return this.shiftYears(1)
    }
  }`


its working as expected. But its done locally and i thought to share here and will helpful to others

**Comment by tohjustin** [comment]
Hmm the current API for specifying the range of the year dropdown feels a bit awkward & you way of specifying a `minYear` & `maxYear` seems to make more sense!

I'm not really sure whether the maintainer is currently interested in making break changes to our API but it would be great to submit a PR for this change =)

**Comment by kesavan49** [comment]
Hi tohjustin,

Thanks and let us see response from maintainer.

**Comment by mikeyc7m** [comment]
i'm also interested in a min & max.

**Comment by mikeyc7m** [comment]
hey wait, you can just use minDate and maxDate.

**Comment by kesavan49** [comment]
Yes I am using Min and Max Date.


const minYear = this.props.minDate ? this.props.minDate.year() : 1900 
const maxYear = this.props.maxDate ? this.props.maxDate.year() : 2100

**Comment by mikeyc7m** [comment]
yeah right. so set maxDate to date(2017,1,1,0,0,0) and this means the year picker won't go beyond 2017.

**Comment by kesavan49** [comment]
https://hacker0x01.github.io/react-datepicker/#example-24. check this example and from the year drop down i want to restrict. If you have solution please share with me.

Thanks

**Comment by mikeyc7m** [comment]
here's my code...
```
<DatePicker
	onChange={ this.moveToDate }
	selected={ this.props.selectedDate }
	dropdownMode="select"
	showMonthDropdown
	showYearDropdown
	maxDate={ moment().add(10,'years')}
	minDate={ moment().subtract(10,'years')}
/>
```
Here's a screenshot, see how it ends at 2027...
![image](https://user-images.githubusercontent.com/6045159/30087756-cfa71616-92e5-11e7-9322-887d0cd4fcdd.png)

**Comment by kesavan49** [comment]
@mikeyc7m thanks . but your solution is not working for me.

Please find the attachement
![datepicker](https://user-images.githubusercontent.com/11057888/30093993-a8925774-92e6-11e7-962a-a9291e51175f.PNG)
![ui](https://user-images.githubusercontent.com/11057888/30093995-a9c4c708-92e6-11e7-82c0-14288d5a8392.PNG)

**Comment by blakegilchrist** [comment]
Also experiencing an issue with Year dropdown when enabled via config setting. We have set maxDate with moment value of today that is honoured by the Month selector (won't let you go beyond current month) but the Year dropdown still shows 2018. 2019, 2020.. etc.

**Comment by DonikaV** [comment]
Same problem about Year Drop Down. How i can fix it ?

**Comment by mikeyc7m** [comment]
don't use the fancy styled year dropdown, use the <select> dropdown.
dropdownMode="select"

**Comment by kesavan49** [comment]
@mikeyc7m  thanks. But this is not valid answer to tell my clients

**Comment by mfmora** [comment]
The `select` dropdown (when using a min, max date) its not working in safari/ios for me. Does anyone have the same problem?

**Comment by DonikaV** [comment]
any news ?

**Comment by mohitkhurana1812** [comment]
I am getting years in year dropdown in descending order but i want it in ascending.Any suggestions??
