### ISSUE TITLE
React-DatePicker doesn't close when a React-Select is clicked

### ISSUE THREAD

**Issue by nothingrandom** [Hacker0x01/react-datepicker#1002]
If I've already got a react-datepicker element open, and click a react-select element on the same view, the select element opens, loses focus, and immediately switches focus back to the datepicker, closing the select element.

The behaviour I expected to see; when clicking a select element whilst a datepicker is already open, the datepicker should close, and the select box should open and get focus.

**Comment by rafeememon** [comment]
#730

**Comment by nothingrandom** [comment]
Thank you! I don't know why I didn't spot that when I did a search 😳 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
