### ISSUE TITLE
Dist files require external react-onclickoutside which is not available

### ISSUE THREAD

**Issue by Deraen** [Hacker0x01/react-datepicker#1003]
Hi,

As far as I can see, the files on [`dist/`](https://unpkg.com/react-datepicker@0.53.0/dist/) are supposed be usable in browser without webpack, if the dependencies (https://github.com/Hacker0x01/react-datepicker/blob/master/webpack.config.js#L22) are provider. However, react-onclickoutside doesn't provide browserified files: https://unpkg.com/react-onclickoutside@6.5.0/

Perhaps the webpack should be configured to bundle react-onclickoutside with dist files (i.e. removed from webpack externals), so the files would be usable?

Example setup here:
https://codepen.io/anon/pen/eEPgPp

Console shows an error:
```
react-datepicker.js:1033 Uncaught TypeError: (0 , _reactOnclickoutside2.default) is not a function
    at Object.module.exports (react-datepicker.js:1033)
    at __webpack_require__ (react-datepicker.js:30)
    at Object.module.exports (react-datepicker.js:598)
    at __webpack_require__ (react-datepicker.js:30)
    at Object.defineProperty.value (react-datepicker.js:65)
    at __webpack_require__ (react-datepicker.js:30)
    at Object.defineProperty.value (react-datepicker.js:50)
    at react-datepicker.js:53
    at webpackUniversalModuleDefinition (react-datepicker.js:9)
    at react-datepicker.js:10
```

**Comment by Deraen** [comment]
React-onclickoutside up-to 6.0 provides browser compatible JS file: https://unpkg.com/react-onclickoutside@6.0.0/index.js, but later versions only provide ES ja CJS modules.

**Comment by Deraen** [comment]
This can be solved by adding https://github.com/59naga/babel-plugin-add-module-exports

It will restore old Babel 5 behavior that exports the ES6 default property on `module.exports` and the global object.

**Comment by TechFounder** [comment]
HI, I'm running into a `Uncaught TypeError: (0 , _reactOnclickoutside2.default) is not a function` error. I'm using React 15.4.2 and React-datepicker 43+ ( I tried every version to the current and get the same error). What exactly should I do to fix this problem? Load `https://unpkg.com/react-onclickoutside@6.0.0/index.js` or `https://github.com/59naga/babel-plugin-add-module-exports` ?

Thanks

**Comment by TechFounder** [comment]
I fixed it by loading `https://unpkg.com/react-onclickoutside@6.0.0/index.js`. Thanks for the solution.

**Comment by marcopadillo** [comment]
It works fine in my project, until webpack rebuilds the bundle when a file is modified. I installed `babel-plugin-add-module-exports` and added `add-module-exports` to my .babelrc but I can still replicate the error.
