### ISSUE TITLE
TypeError while doing server-rendering with minified version

### ISSUE THREAD

**Issue by Kronuz** [Hacker0x01/react-datepicker#1005]
In the `dist` version of react-datepicker (minified) there is this:

```javascript
return je.Utils=("undefined"!=typeof window?window:t).PopperUtils
```
which results in `TypeError: Cannot read property 'PopperUtils' of undefined`

Perhaps (and it fixes the problem) the minified version should also have `global` there instead of `t`, like this:
```javascript
return je.Utils=("undefined"!=typeof window?window:global).PopperUtils
```

**Comment by Kronuz** [comment]
...must be popper's issue? webpack issue? ...??

**Comment by lordalaqua** [comment]
Were you able to solve this issue? I am also getting it when doing server rendering...

**Comment by Kronuz** [comment]
When using `dist/react-datepicker.min.js`, as it already comes packed and
minified, the `global` variable somehow gets lost, producing an error:
`TypeError: Cannot read property 'PopperUtils' of undefined`

To prevent this I'm directly using `lib/datepicker.js` instead.

You can either do `import DatePicker from 'react-datepicker/lib/datepicker'` or fork it and change `package.json`:

```diff
--- react-datepicker/package.json
+++ react-datepicker/package.json
@@ -5,7 +5,7 @@
   "version": "0.55.0",
   "license": "MIT",
   "homepage": "https://github.com/Hacker0x01/react-datepicker",
-  "main": "dist/react-datepicker.min.js",
+  "main": "lib/datepicker.js",
   "style": "dist/react-datepicker.min.css",
   "files": [
     "*.md",
```

**Comment by lordalaqua** [comment]
Thank you, I had changed the minified version as you first suggested, but importing directly from source is better.

Anyway, shouldn't the package mantainers take notice of this? Seeing as the issue is closed, I don't see this getting fixed, and it breaks server rendering for someone who isn't aware of importing directly.

**Comment by Kronuz** [comment]
Who knows.... I'll reopen to see if this could get fixed somehow.

To me, IMHO, I believe package maintainers should always provide `src` with ES6/ES7 modules right there, so users could use any packaging they want when they have to and import directly from sources (and it should be the default). I actually think providing minified `dist` files (or even `lib`) is more trouble than we'd want.

**Comment by lordalaqua** [comment]
Yeah, you are probably right, I wasn't even aware I was importing from the minified version by default, it can be confusing.
