### ISSUE TITLE
Submitting date value in moment format

### ISSUE THREAD

**Issue by kkashou** [Hacker0x01/react-datepicker#1006]
When I submit my form data to react data why does datepicker sends it as a moment object as oppose to string? 

```Javascript
<Field model='user.date' id='user.date' mapProps={{
                                selected: props => props.modelValue
                            }}>
                                <DatePicker
                                    dateFormat='MM-DD-YYYY'
                                    className={'form__textfield'}
                                    title={'Pick a date'}
                                    shouldCloseOnSelect={true}
                                    readOnly
                                    showMonthDropdown
                                    showYearDropdown
                                    dropdownMode='select'
                                    monthsShown={2}
                                />
                            </Field>
```

I am using react redux form hence why you see Field.

Thanks,

Kevin

**Comment by rafeememon** [comment]
This API of this component is to call `onChange` with a moment object, not a string, when the date changes.  If you want the raw string, use `onChangeRaw`.

**Comment by kkashou** [comment]
But problem is when i do console.log(e) on handleSubmit function, im not using onChange or onChangeRaw. How can I grab the string from the e

**Comment by rafeememon** [comment]
I don't know about redux-form, but you need to have it hook into `onChangeRaw`
