### ISSUE TITLE
Allow to hide the Calendar's title

### ISSUE THREAD

**Issue by lbelinsk** [Hacker0x01/react-datepicker#1008]
@martijnrusschen  I want to hear whether it will be ok to add a new boolean prop, something like `displayCalendarTitle` that will hide the header (August 2017 in this example):

![image](https://user-images.githubusercontent.com/18248989/29931279-7839a026-8e79-11e7-945c-81b8ab321de1.png)

Because it is a bit redundant to display it when you have a year and month dropdowns.

This is an example for what I am aiming for:

![image](https://user-images.githubusercontent.com/18248989/29931434-ef7af388-8e79-11e7-8cfc-004db7484f90.png)

![image](https://user-images.githubusercontent.com/18248989/29931450-f96c1e3a-8e79-11e7-815f-68aae6725cdc.png)

I am not sure, but maybe the title frame should be configurable?

Let me know what do you think, I will prepare a pr if it will be ok with you.

Thanks...

**Comment by lbelinsk** [comment]
@martijnrusschen is it ok to start working on that?

**Comment by martijnrusschen** [comment]
Sounds reasonable. Lets do it!

**Comment by aij** [comment]
Should that be an extra option? Do we ever need/want to show both?

Here's the scss we've been using in our apps:
```
// Styling for the mini-calendar
.react-datepicker {
  // [Omitted styling to change react-datepicker colors to match our app]
 
  .react-datepicker__current-month.react-datepicker__current-month--hasYearDropdown.react-datepicker__current-month--hasMonthDropdown {
    // Avoid showing the month and year a second time when it has month and year
    // dropdowns.
    display: none;
  }
}
```

@martijnrusschen Would it make sense to do something like that ^ by default? It seems like a better default, and if anyone actually needs the old behavior they can still get it with custom styling.

**Comment by martijnrusschen** [comment]
Yeah I think the new behaviour is better and should be the default. Lets roll with that!

**Comment by justame** [comment]
@aij The CSS solution looks good, but I think we can adjust it a little bit to something like that : 
```css
// Styling for the mini-calendar
.react-datepicker {
  // [Omitted styling to change react-datepicker colors to match our app]
  .react-datepicker__current-month.react-datepicker__current-month--hasYearDropdown,
  .react-datepicker__current-month.react-datepicker__current-month--hasMonthDropdown {
    // Avoid showing the month and year a second time when it has month and year
    // dropdowns.
    display: none;
  }
}

@martijnrusschen @aij, What I suggest is to hide the div if **one** of dropdown exists instead of both.
Below you can see an example of a use case that shows only one of the drop-down: 
![image](https://user-images.githubusercontent.com/286909/30556917-34ddf882-9cb5-11e7-8f7f-310f42344ccf.png)

**Comment by terolepisto** [comment]
Ok, where does that title come from?

I have two calendars in my app. The other says "February 2018" and the other says "Wednesday".

So how do I controll what data the title shows?

**Comment by iloveip** [comment]
Hello. Are there any updates on this? I would like to hide the calendar title and I tried to pass `dateFormatCalendar=""`, but I get an error:

`Uncaught TypeError: Cannot read property 'map' of null`

Which seems to be related to date-fns 'format()' function.

**Comment by aronmi** [comment]
> Hello. Are there any updates on this? I would like to hide the calendar title and I tried to pass `dateFormatCalendar=""`, but I get an error:
> 
> `Uncaught TypeError: Cannot read property 'map' of null`
> 
> Which seems to be related to date-fns `format()` function.

you can set it to " " , dateFormatCalendar=" " ;
just a space worked for me while "" did not.
