### ISSUE TITLE
Is it possible to have no date selected?

### ISSUE THREAD

**Issue by ashic** [Hacker0x01/react-datepicker#1009]
If I don't specify any limitations, the current date is selected. If I specify includeDates, the last date on the page is selected. Would be possible to have no date selected?

**Comment by rafeememon** [comment]
Pass `null` to the `selected` prop

**Comment by ashic** [comment]
Just tried it. It's still showing today / last day of includeDates in blue (using the default stylesheet).

**Comment by krini** [comment]
Did you solve this?

**Comment by Hillsie** [comment]
Trying to implement this option. Passing null to selected isn't working for me either.

**Comment by locdangle2552** [comment]
Hello. I have solved this issue.
Try this: 
**const [startDate, setStartDate] = useState(null);**

<DatePicker
    inline
    showTimeInput
    onChange={date => setStartDate(date)}
    **selected={startDate}
    disabledKeyboardNavigation**
/>

**Comment by ufukomer** [comment]
I think this issue should be reopened for the case where I want either keyboard navigation and null selected.

**Comment by ronenmagid** [comment]
this lack of basic feature makes this component unusable for modern projects.

**Comment by jonatanramhoj** [comment]
Seems like it would be more useful/logical if when passing `selected: null` also the class `react-datepicker__day--keyboard-selected` should not be applied? This must be a very easy fix?

**Comment by stefandeclerk** [comment]
What worked for me was to change `selected` to `""`  instead of null, so `selected={""}`

**Comment by wunaidage** [comment]
I found that the default highlighted today is caused by default enabled keyboard navigation. If you do not need keyboard navigation you can set `disabledKeyboardNavigation` then give selected `null`

**Comment by tdspl-Ajayjr** [comment]
> I found that the default highlighted today is caused by default enabled keyboard navigation. If you do not need keyboard navigation you can set `disabledKeyboardNavigation` then give selected `null`

I tried this but this is still showing current date as deafult

**Comment by maartenschumacher** [comment]
The current date is not selected, it's just styled with the same color as a selected date. To change or remove this styling you can target the `react-datepicker__day--today` selector

**Comment by mehdi-cse-bd** [comment]
> Pass `null` to the `selected` prop

Used it on usestate and worked perfectly for me. Thank you so much.
