### ISSUE TITLE
Support for React 0.13

### ISSUE THREAD

**Issue by ryan1234** [Hacker0x01/react-datepicker#101]
I'm using React 0.13 and this causes react-datepicker to show a warning about getDOMNode being deprecated. (https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html#new-features).

For lines like this in the code:

https://github.com/Hacker0x01/react-datepicker/blob/1d8177aff26042c10bfd25c46d4b4c5b0c98344c/src/date_input.jsx#L33

... what would your thoughts be about abstracting out getDOMNode and putting it behind a utility function that could be swap between getDOMNode and findDOMNode? The utility function would always return a node, so the client code would never know how it got the node, only that it got one.

In the build process you could specify the React version you want and the utility function would be wired to only include the support method for the appropriate version of React. 

Something like (pseudo code):

```{js}
if (__REACT_VERSION_0.12__) {
  return getDOMNode(component);
} 

if (__REACT_VERSION_0.13__) {
  return findDOMNode(component);
}
```
That's the current approach I use with webpack and environment variables to build different versions of components.

Or maybe just live with the warnings in dev. =)

**Comment by RSO** [comment]
Hey! Thanks for taking the time to write up this issue!

I like your approach, although I'm not sure if it wouldn't be a little too much for a small library like this one. 

I figure we could also just stop supporting 0.12 in the next version (I'm not sure if there are statistics as to how many people still use 0.12). Being that both react and this datepicker are still `0.` I figure we can still make breaking changes in small version bumps.

**Comment by ryan1234** [comment]
Sounds good. I'll just keep my eye out for the switch when it happens. Bummer they've introduced some breaking changes, but I suppose to be expected. =)
