### ISSUE TITLE
Not closing the calendar on selection of a date

### ISSUE THREAD

**Issue by frazboyz** [Hacker0x01/react-datepicker#1012]
The calendar is not hidden when a calendar date is selected. No errors or warnings are placed into the console. React Calendar V 0.53.0

```
<DatePicker
            className={"date-field" + (className ? " " + className : "") + (error ? " error" : "")}
            selected={date}
            onChange={(newValue) => onChange(identifier, newValue)}
            dateFormat="DD/MM/YYYY"
        />
```

**Comment by erikxcore** [comment]
Had the same issue, but in my case I had a <label> that was wrapping the date picker that caused this issue.

**Comment by ashic** [comment]
I have the same issue. Datepicker doesn't close if a date is selected.

**Comment by tourshi** [comment]
I can confirm, I am experiencing the same issue. If Datepicker is wrapped in a label tag it doesn't close on selecting a date.

**Comment by warmbowski** [comment]
I see this problem to. I have a component that wraps a Datepicker component in a label tag. The calendar stays open after selection. If I change the label to a div, it works properly.

**Comment by honzajerabek** [comment]
Same here, trying to use `<DatePicker />` as a label for a radio button

**Comment by honzajerabek** [comment]
adding `<label onClick={e => e.preventDefault()}><Datepicker .... /></label>` fixed this issue for me. In debugger I found that after select, `setOpen(false)` was called and DatePicker was closed but right after that it was reopened again (by label? 🤔)

**Comment by BananaBobby** [comment]
+1, I have a label that wraps datepicker component. I use to let user click on a button near the datepicker and open the datepicker as clicking on label triggers focus on the inner input.

**Comment by adam-horvath** [comment]
My solution is a mix of the above mentioned ones. A little bit hackish but worked for me.

`<label onClick={e => {
    if (window.calendar.state.open) {
        e.preventDefault();
    }
}}>
    <DatePicker
        ref={r => window.calendar = r}
        selected={this.props.filter.date}
        onChange={this.onDateChange}
        dropdownMode={'select'}
        isClearable={true}
        placeholderText={Constants.DATE_FILTER_PLACEHOLDER}
    />
    <div className="calendar-icon" style={{display : this.props.filter.date ? 'none' : 'block'}}/>
</label>`

**Comment by frizar** [comment]
Hello! Any news? This bug still doesn't fixed :(

**Comment by chetan-jain** [comment]
Facing same problem, putting datepicker inside label causing it to not close on date/time selection. Works fine when used outside of label.

**Comment by waheedsid** [comment]
Has anyone got a solution to this problem yet? my problem is I cant use this.calender or ref as mentioned in above solutions because my label is inside a stateless component.

**Comment by adam-horvath** [comment]
@waheedsid, I think my solution will work if you refactor your component to stateful.

**Comment by giorgosavgeris** [comment]
If the datepicker remains open because it is wrapped inside `label`,  you can call `preventDefault` on `onChange`.

```js
import React from 'react';
import DatePicker from 'react-datepicker';

class MyDatepicker extends React.Component {
  handleChange = (date, e) => {
    if (e && typeof e.preventDefault === 'function') {
      e.preventDefault();
    }

    const {onChange} = this.props;

    if (onChange) {
      onChange(date);
    }
  };

  render() {
    return (
      <DatePicker
          {...this.props}
         onChange={this.handleChange}
      />
    );
  }
}
...
```

**Comment by steve-taylor** [comment]
Rather than calling `preventDefault()` when the date picker is open, call it when the label content isn't clicked on directly. That way, you don't lose any of the functionality of labels.

```jsx
const labelContentRef = useRef(null)
const onClickLabel = useCallback(
    event => {
        if (event.nativeEvent.target !== labelContentRef.current) {
            event.preventDefault()
        }
    },
    []
)

return (
    <label onClick={onClickLabel}>
        <span ref={labelContentRef}>
            {label}
        </span>
        <DatePicker
            // props go here...
        />
    </label>
)
```

Note that, in my case, the `span` is styled to occupy the full width of the label, so clicking anywhere inside the label, except for the labelled element itself, passes focus to the focusable labelled element.

**Comment by ujjaldey** [comment]
> Rather than calling `preventDefault()` when the date picker is open, call it when the label content isn't clicked on directly. That way, you don't lose any of the functionality of labels.
> 
> ```js
> const labelContentRef = useRef(null)
> const onClickLabel = useCallback(
>     event => {
>         if (event.nativeEvent.target !== labelContentRef.current) {
>             event.preventDefault()
>         }
>     },
>     []
> )
> 
> return (
>     <label onClick={onClickLabel}>
>         <span ref={labelContentRef}>
>             {label}
>         </span>
>         <DatePicker
>             // props go here...
>         />
>     </label>
> )
> ```
> 
> Note that, in my case, the `span` is styled to occupy the full width of the label, so clicking anywhere inside the label, except for the labelled element itself, passes focus to the focusable labelled element.

Thanks for this! It worked like a charm!
