### ISSUE TITLE
How to display name of the day using date format?

### ISSUE THREAD

**Issue by jayendra-sharan** [Hacker0x01/react-datepicker#1014]
Hi,

I want to display the date in following format, e.g.
`Tue Sep 05, 2017`
What should I put as the dateformat?

For example, for 05/09/2017 I am keeping 'DD/MM/YYYY' and it is working fine.

**Comment by zek0faws** [comment]
Hi,

According to javascript's documentation, you can use 'dd MMM DD, YYYY' to display the date format you want.

**Comment by jayendra-sharan** [comment]
Thanks ✌️
