### ISSUE TITLE
preSelection and inline mode seems to bug

### ISSUE THREAD

**Issue by guillaumepotier** [Hacker0x01/react-datepicker#1015]
I faced a problem with `inline` datepicker and no value/date by default.

I use that code now:

```javascript
                      <DatePicker
                        inline
                        format='dddd MMMM Do'
                        minDate={moment()}
                        maxDate={moment().add(1, 'years')}
                        selected={this.props.task.dueDate ? moment.unix(this.props.task.dueDate) : moment()}
                        onChange={() => {}}
                        onSelect={date => this.handleChangeTaskDueDate(date)}
                      />
```
I need to display the today date when the picker is opened if no value yet. Since there is no `defaultDate` option, I use this kinda hack on `selected={this.props.task.dueDate ? moment.unix(this.props.task.dueDate) : moment()}`.

The problem is that it is impossible then to choose today since it is already selected, and not triggering a `onChange` event. I use `onSelect` to bypass that, and use noop for `onChange`.

Would it be possible then to have a `openOnDefaultDate` or so if no date is selected/empty value?

Or did I miss something?

**Comment by aij** [comment]
`selected` is an optional prop. Just pass `null` to indicate no date is selected, then when today is selected that will be a change.

**Comment by guillaumepotier** [comment]
@aij thanks for your answer, I tried it, but the calendar would be opened in jan 1970, despite my `minDate` and `maxDate`...

**Comment by aij** [comment]
@guillaumepotier That sounds like a bug then. It should be setting the default pre-selection to the current day, respecting `minDate` and `maxDate`.

Just checking, you're not somehow accidentally passing `selected={moment.unix(0)}` are you?

Anyway, PRs welcome if you want to take a stab at fixing it. I'm guessing somehow `preSelection` is not being initialized correctly in inline mode.

**Comment by guillaumepotier** [comment]
> Just checking, you're not somehow accidentally passing `selected={moment.unix(0)}` are you?
Nope, I test and if no value I give `moment()`

I'll update my issue title then, and would try to have a look for hopefully make a PR, but right now my workaround works fine I'll go a bit deeper in my project for now on :)

Best
