### ISSUE TITLE
Datepicker style doesn't work correctly, the picker items don't display in a grid

### ISSUE THREAD

**Issue by pro-soft-git** [Hacker0x01/react-datepicker#1016]
I'm using this datepicker and the functionality works perfectly well, however the datepicker itself is very high, and all the numbers are stacked on top of each other. The rest of the styles are correct, but the days just don't display correctly. This makes the datepicker really high and a huge part of it disappears at the top edge of the screen.

Also, I would like to show the datepicker below the date indicator when I click, instead of on top of the indicator.

The most important thing is the weird arrangement of the days though.

**Comment by zek0faws** [comment]
Could you provide a screenshot of what happens ?

**Comment by pro-soft-git** [comment]
Turns out it was some weird CSS being injected into the page, which removed the display property values of the datepicker. This issue has been closed...
