### ISSUE TITLE
popperClassName Not Passed Down

### ISSUE THREAD

**Issue by emilyrohrbough** [Hacker0x01/react-datepicker#1019]
The `popperClassName` is a prop offered on the datepicker component. However, looking at the popper component implementation, `popperClassName` is not defined and custom props are not spread on the rendered component. This is a misleading prop on the datepicker if including a custom class on the popper was not intended.

**Comment by ecrofeg** [comment]
Agreed, I've spent a lot of time trying to figure out what's going on, before I realised that `popperClassName` is completely ignored.

**Comment by adred** [comment]
I just experienced this. Hopefully fix is coming.
