### ISSUE TITLE
Inline portal version has no cancel function

### ISSUE THREAD

**Issue by ericluwj** [Hacker0x01/react-datepicker#1024]
It has not seem very user-friendly that the inline portal version requires another day to be selected in order for it to close.
Clicking on the originally selected date does not yield any response, nor does clicking outside the portal calendar.

**Comment by MUllman** [comment]
Agreed there is no way to clear the selected date when the DateTool is rendered inline. Its really frustrating

**Comment by ShaneGlee** [comment]
In case anyone is still looking.
You can bind to onClickOutside to toggle your open state.

```
<DatePicker
  withPortal
  inline
  onClickOutside={this.toggleCalendar} />
```
