### ISSUE TITLE
Disable input[type=text] manual edit

### ISSUE THREAD

**Issue by derkachdeveloper** [Hacker0x01/react-datepicker#1038]
How disable input[type=text] manual edit?
How provide functionality to disable manual editing to input?

![image](https://user-images.githubusercontent.com/6834477/30754760-ade015ca-9fcc-11e7-8de1-8d02822ffb94.png)

**Comment by tinhlv** [comment]
I have the same problem

**Comment by tinhlv** [comment]
help me

**Comment by RuslanYurchenko** [comment]
+1

**Comment by SilvioMessi** [comment]
Try to force the datepicke's value to be consistent with the date object stored in the component state. Something like this:
```
<DatePicker
    value={this.state.date.format('DD/MM/YYYY')}
    onChange={(inputValue) => {this.setState({date: inputValue});}}
/>
```

**Comment by ArcanisCz** [comment]
@SilvioMessi Manual edit will trigger `onChangeRaw`, not `onChange`.

**Comment by derkachdeveloper** [comment]
@tinhlv , i was make wrapper component and custom input and handle focus on it. on input focus - do blur.

**Comment by colinrcummings** [comment]
I pass a `readOnly` prop to the DatePicker component and the following css to make the background color white again:

```
.react-datepicker__input-container input[readonly] {
  background-color: white; 
}
```

**Comment by charmstead** [comment]
Try this. works for me

```
const CustomInput = (props) => {
    return (
        <input
            className={[classes.TransparentInput, "uk-input"].join(" ")}
            onClick={props.onClick}
            value={props.value}
            type="text"
            readOnly={true}
        />
    )
}
<DatePicker
  customInput={<CustomInput />}
  name={'from'}
  value={values['from']}
  onChange={e => setFieldValue('from', moment(e).format('L'))}
 />
```
