### ISSUE TITLE
Custom week day abbreviation

### ISSUE THREAD

**Issue by derkachdeveloper** [Hacker0x01/react-datepicker#1039]
How make custom week day abbreviation?

![image](https://user-images.githubusercontent.com/6834477/30754833-fb49ba78-9fcc-11e7-9060-a494444d74af.png)

**Comment by nits** [comment]
Did anyone find solution for this?

**Comment by nits** [comment]
alright. So i found out that this is not something relates to datepicker component.
Day abbreviation we can change using moment locale as follows:

moment.updateLocale('en', {
      weekdaysMin: ['S', 'M', 'T', 'W', 'T', 'F', 'S']
});

Source: https://momentjs.com/docs/#/i18n/
