### ISSUE TITLE
Uncaught TypeError: e.isDefaultPrevented is not a function

### ISSUE THREAD

**Issue by phun-ky** [Hacker0x01/react-datepicker#1041]
I'm getting this when I am typing into the datepicker field manually, instead of using the picker. What could be the issue here?

**Comment by phun-ky** [comment]
Anyone with a fix here?

**Comment by aij** [comment]
Works for me...

**Comment by lizter** [comment]
Hi, this is related to Internet Explorer.

![datepicker_exception](https://user-images.githubusercontent.com/920028/34994201-07930d46-fad3-11e7-85b2-842a94075a25.png)

Every time the datepicker is opened, this exception is thrown. This is annoying as it floods our logs.

I also noticed that reactdatepicker.com doesn't work at all in IE11. The page is grey, and the following errors are present in console:

![reactdatepicker_exceptions](https://user-images.githubusercontent.com/920028/34994301-548d2adc-fad3-11e7-958c-1d2739f47301.PNG)

**Comment by lizter** [comment]
@aij Is the information provided sufficient enough to investigate the issue for you?

**Comment by aij** [comment]
@lizter I don't know offhand what the issue is, and I have other things I need to work on now, but it's probably enough for someone to get started...

**Comment by rafeememon** [comment]
Possibly the same issue as https://github.com/Hacker0x01/react-datepicker/issues/1076

**Comment by lizter** [comment]
The DatePicker as a lib/component works in IE11, it’s just the exception
getting thrown on handleChange all the time.

tir. 23. jan. 2018 kl. 02:09 skrev Rafee Memon <notifications@github.com>:
