### ISSUE TITLE
Idea: Select Start/End on One Picker

### ISSUE THREAD

**Issue by hufftheweevil** [Hacker0x01/react-datepicker#1043]
First off, I love this project because it's focused more on functionality and less on style. Leaving the styling to the implementer of the component is the perfect way to go.

I'm wondering how hard it would be to add a feature that let a date range be selected within one calendar/picker. I'm imagining something where you might start with a calendar with nothing selected. The first two days clicked determines the range (could chosen as start->end or end->start). Then after that, you can click and drag the start/end dates to somewhere else. The picker would need to remain open during this time, and some sort of action button would need to be present to close the picker.

I realize it sounds like a lot of work. I may try to just implement something like this on my own, then share it. Just wondering if anyone else has any interest too.

**Comment by rafeememon** [comment]
This can already be done, although without dragging: you can set `startDate` and `endDate` from your `onChange` handler.  Determining whether the new date should be the start or end of the range can be done with simple logic.

**Comment by hufftheweevil** [comment]
Hmm, yeah I see what you mean. That logic part may not always be so logical, though. For example, if the current range starts on some Monday and ends on some Friday and then the user clicks on the Wednesday between those two, does he want to change the start to Wed or the end to Wed? I suppose I could use the children feature to add a toggle button within the picker, but I'm not sure if most people would understand that UI. I shall play around with it a bit. Obviously drag and drop would be clearer and easier to use.

**Comment by rafeememon** [comment]
I think determining how to handle clicking a day in the middle should be left to the consumer of the component; there's no obvious right answer, and I don't think one solution will make everyone happy. =)
