### ISSUE TITLE
Can't set locale

### ISSUE THREAD

**Issue by janhoeck** [Hacker0x01/react-datepicker#1044]
Hello,

I cannot set the locale to "de" to remove the AM and PM format. 
I tried this via the locale property and the moment global locale method.

**Comment by joshianuj** [comment]
Did you import 'moment/locale/de'?
and tried with locale='de'

**Comment by maxnowack** [comment]
I've got the same problem. I've imported 'moment/locale/de', but `locale="de"` has no effect …

**Comment by shadowwzw** [comment]
I have the same problem.

**Comment by etienne-bondot** [comment]
You need to call `moment.locale('<your_local>');` after importing locales.

**Comment by BartusZak** [comment]
Thanks for answer.
```
import 'moment/locale/pl';
...
locale="pl"
```

**Comment by pdpino** [comment]
The docs could say that importing the locale is needed. Also it could be specified in [this example](https://reactdatepicker.com/#example-16)
