### ISSUE TITLE
Weird responsive behavior with datepicker

### ISSUE THREAD

**Issue by hdpinto** [Hacker0x01/react-datepicker#1045]
![mobile-calendar](https://user-images.githubusercontent.com/1548970/31025979-a444cb00-a512-11e7-9380-cbcc8be4d136.png)

**Comment by hdpinto** [comment]
This actually very helpful, thank you @pfarnach!

Though, with the speech-bubble version it still shouldn't be going off-screen like that.

**Comment by Dineshdpb** [comment]
![Task](https://user-images.githubusercontent.com/63685426/147909343-b0074881-04e9-497b-856f-4327870f7656.png)
In my project it is still issue
