### ISSUE TITLE
Cannot read property 'numerator' of undefined

### ISSUE THREAD

**Issue by thilinaucsc** [Hacker0x01/react-datepicker#1049]
I develop web app with react I got error in there like below

`ERROR in ./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./node_modules/react-datepicker/dist/react-datepicker.css
Module build failed: 

        margin: 0;
        height: calc(195px + calc(1.7rem / 2));
      ^
Cannot read property 'numerator' of undefined
      in /home/thilina/Documents/office/Agent-Customer-Portal/node_modules/react-datepicker/dist/react-datepicker.css (line 167, column 8)
 @ ./node_modules/react-datepicker/dist/react-datepicker.css 4:14-105 18:2-22:4 19:20-111
 @ ./src/components/independentComponents/DivFormField.js
 @ ./src/components/independentComponents/FieldSet.js
 @ ./src/ui/Register/RegisterQuizUI.js
 @ ./src/ui/Register/RegisterUI.js
 @ ./src/controller/login/RegisterController.js
 @ ./src/container/LoginContainer.js
 @ ./src/App.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server ./src/App.js
webpack: Failed to compile.
`

I find error in 

 `height: calc(195px + calc(1.7rem / 2));`

can you update code to 

` height: calc(195px + (1.7rem / 2));`

**Comment by kodell** [comment]
Manually making your suggested change resolved this problem for me too. +1

**Comment by Raido0812** [comment]
not sure if this helps, 
setting strictMath option on less-loader to true fixed the issue for me.
