### ISSUE TITLE
React 16 Update

### ISSUE THREAD

**Issue by Shadowman4205** [Hacker0x01/react-datepicker#1053]
Hello, i get this warning,

warning "react-datepicker@0.55.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "react-datepicker@0.55.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".

will be any updates?

**Comment by aij** [comment]
Are there any problems besides the warning?

**Comment by Shadowman4205** [comment]
At first sight no i did not find any problem

**Comment by bjankord** [comment]
There is an open issue around react 16 support here: https://github.com/Hacker0x01/react-datepicker/issues/972

**Comment by aij** [comment]
Duplicate of #972
