### ISSUE TITLE
Today's date button does not work with utcOffset

### ISSUE THREAD

**Issue by marekadamek** [Hacker0x01/react-datepicker#1054]
Steps to reproduce:
1. Go to examples page: https://hacker0x01.github.io/react-datepicker/
2. Make sure today button is working in example "Today button"
3. Open date picker in example "TimeZone date"
4. Click today button

Result: nothing is set in the input
Expected result: today's date is set in the input (with respect to chosen utcOffset)

**Comment by prayerslayer** [comment]
Thanks for reporting, apparently there were two issues:

1) Set minDate and maxDate, but were not shown in code snippet. Depending on the date, "today" might have been an invalid date.
2) Moment.js apparently removed ambiguity when setting UTC offset. Previously every number <= 12 was counted as offset in hours, now you have to set it in minutes all the time: https://momentjs.com/docs/#/manipulating/utc-offset/

I'll open a PR to fix this in the next minutes.
