### ISSUE TITLE
Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by scrombie** [Hacker0x01/react-datepicker#1055]
Date Picker throws this error on first click, and subsequently on every on click outside the picker.
Any idea why?

React: v15.6.1
React-datepicker v0.55.0

**Comment by michaelwclark** [comment]
I'm having the same issues.

**Comment by scrombie** [comment]
@michaelwclark From what i gathered, It could be caused by different libraries using different versions of React. Or particularly, a library using a version higher than what you're using.

Not sure about this tho. I switched to a different library. Needed to move quick. But check it out and feel free to let me know if it was the cause.

**Comment by michaelwclark** [comment]
I just downgraded my datepicker. @scrombie

**Comment by czechdave** [comment]
Had the same issue, make sure your `react-dom` version is also `15.6.1`, that solved it for me, I had it different from the `react` version.

**Comment by eyanez1230** [comment]
Anyone still facing this issue on the latest release?

**Comment by jkahne** [comment]
I am.  I'm using:

"react": "^16.2.0",
"react-datepicker": "^0.64.0",
"react-dom": "^16.2.0",
