### ISSUE TITLE
TimeSelect not show?

### ISSUE THREAD

**Issue by permadiwibisono** [Hacker0x01/react-datepicker#1056]
Why TimeSelect not show? 
![gambar](https://user-images.githubusercontent.com/14840070/31212777-b52d1a08-a9cc-11e7-9893-20bf6b3bfb23.png)

**Comment by jessica-pixvana** [comment]
I have the same issue. Using v0.55.0. `showTimeSelect` breaks the datepicker and shows a poorly formatted list of times

<img width="267" alt="screen shot 2017-10-05 at 1 22 09 pm" src="https://user-images.githubusercontent.com/18540748/31250625-41096786-a9d0-11e7-861a-e416052c7f7c.png">

**Comment by martijnrusschen** [comment]
This looks like a CSS bug. Are you using the CSS provided by the component?

**Comment by jessica-pixvana** [comment]
Am I supposed to copy the file `react-datepicker/dist/react-datepicker.css` into my directory to use it?

**Comment by jessica-pixvana** [comment]
Currently I have` import 'react-datepicker/dist/react-datepicker.css';` at the top of my file

**Comment by nali** [comment]
@permadiwibisono I had the same issue on the 0.54 version, updating to 0.55 resolved it for me.

**Comment by permadiwibisono** [comment]
@nali i got it, but now there is bug in css, not show properly same problem with @jessica-pixvana 
![gambar](https://user-images.githubusercontent.com/14840070/31426977-d6d80ccc-ae8f-11e7-8427-09e1be2e85be.png)

And its my code:
![gambar](https://user-images.githubusercontent.com/14840070/31427014-fb543ab2-ae8f-11e7-9c50-e026b577b8ad.png)

**Comment by shadrech** [comment]
@permadiwibisono Whats your operating system and browser?

**Comment by permadiwibisono** [comment]
@shadrech I'm using Windows 10 and with Google Chrome.

**Comment by codepandy** [comment]
@shadrech the same issue,windows 7 and Chrome.
how to solve it?

**Comment by orx0r** [comment]
@shadrech I have the same issue on ubuntu and Chromium.
current versions react v15.5.4 react-datepicker v0.60.2 (on previous versions was the same issue)

1. https://github.com/Hacker0x01/react-datepicker/issues/1056#issuecomment-334628577
2. add some inline styles
```
.react-datepicker__time-container .react-datepicker__time .react-datepicker__time-box ul.react-datepicker__time-list {
    padding-left: 0;
    padding-right: 0;
}
```
it's solve display issues

**Comment by hugozap** [comment]
One thing I noticed is that the time list does not have margin set to 0, so it takes the browser defaults which results in issues: See a simple example here: https://codesandbox.io/s/l5oz7rvrzq

**Comment by jfajardo** [comment]
I have the same issue with react semantic ui
```
.react-datepicker {
    display: flex  !important;
}
```
