### ISSUE TITLE
Time format not taking locale

### ISSUE THREAD

**Issue by namezero** [Hacker0x01/react-datepicker#1057]
Time format is 'hh:mm A' hardcoded (time.js line 78)
also the header title : "Time" is hardcoded
this should be a default props so we can change it  or/and you have to get the format from the locale (i18n)
![image](https://user-images.githubusercontent.com/428343/31231818-3b05fe22-a9e8-11e7-812d-90755d11cf23.png)

**Comment by namezero** [comment]
also, when datepiker  dont fit screen, we have scroll bar, but impossible to scroll because when we want to scroll the datepicker hide. you should calculate and detect that the datepicker is out of screen and change it position 
![image](https://user-images.githubusercontent.com/428343/31273936-1fe699c2-aa91-11e7-9be8-8c0499adeeac.png)

**Comment by drinchev** [comment]
This has been implemented already : 

https://github.com/Hacker0x01/react-datepicker/pull/1035

**Comment by namezero** [comment]
What about the position on screen when it is on the edge?

**Comment by namezero** [comment]
![image](https://user-images.githubusercontent.com/428343/31376271-a4160a8c-ada4-11e7-92ea-9027b745f8b8.png)

**Comment by fredifr** [comment]
Basic locale settings are not honoured.

**Comment by fredifr** [comment]
![Screen Shot 2019-07-26 at 17 51 59](https://user-images.githubusercontent.com/19371927/61969060-81125a00-afd1-11e9-964e-621b165152af.png)

Look at the example in the main website
