### ISSUE TITLE
TimeSelect not working

### ISSUE THREAD

**Issue by fukaminmin** [Hacker0x01/react-datepicker#1058]
I user react-datepicker in my project.
I tried to show time picker but I can't.

It's my code.

package.json
```
"react-datepicker": "^0.54.0"
```

js
```
<DatePicker
  selected={this.state.disp_date}
  onChange={this.handleChange}
  showTimeSelect
  dateFormat="LLL"
/>
```
![scr 2017-10-07 12 54 24](https://user-images.githubusercontent.com/5743680/31304571-be182d5e-ab5e-11e7-9623-f936761ad663.jpg)

Please help me...

**Comment by codexpert** [comment]
Are you using React 16 ? #1060

**Comment by GautierT** [comment]
It's a feature of 0.55.0 : https://github.com/Hacker0x01/react-datepicker/releases

**Comment by fukaminmin** [comment]
@GautierT Thanks! When I upgrade react-date-picker for 0.55.0, that works fine!
