### ISSUE TITLE
Invalid changes to the input box are not reverted when the calendar is hidden

### ISSUE THREAD

**Issue by tobia** [Hacker0x01/react-datepicker#106]
If you try this:

1. Click on the text box, this should bring up the calendar
2. Clic again inside it, this will hide the calendar
3. Type some nonsense in the textbox
4. Click outside

This will leave the textbox with garbage inside it, while the state still contains the last valid date.

Correct behaviour would be either reverting the garbage, or disabling hiding the calendar altogether while the text box is focused (by adding className `ignore-react-onclickoutside` to the input element)

**Comment by RSO** [comment]
Interesting case. My thoughts originally were to not change the value of the input without the user actually doing so (e.g. click on a date or change the value). I think you convinced me, but I would like to get some more input from others before implementing.

**Comment by jenskanis** [comment]
I think disabling the calendar when the text box is focused makes the most sense to me. Reverting the input feels a bit too agressive towards the user.

**Comment by tobia** [comment]
I ended up adding `ignore-react-onclickoutside` to the input element, because from my tests I felt that gives the best user experience.

**Comment by martijnrusschen** [comment]
Should be fixed with #319.

**Comment by rafeememon** [comment]
@martijnrusschen, I don't think it was addressed actually.  Will make a separate fix

**Comment by martijnrusschen** [comment]
Ah, this one was mentioned in #319, but looks you're right.

**Comment by rafeememon** [comment]
Oops, yeah I think I misread this bug the first time around.
