### ISSUE TITLE
dropdown position change on month change

### ISSUE THREAD

**Issue by kenta88** [Hacker0x01/react-datepicker#1064]
The date picker's location is not stable and sometimes the same month is being displayed when the datepicker dropdown is positioned above the input.

![issue gif](https://media.giphy.com/media/26Ff0YIpSD4N7BQTS/giphy.gif)

**Comment by murdink** [comment]
the `fixedHeight` prop should meet your needs

**Comment by kenta88** [comment]
thank you very much!
