### ISSUE TITLE
Problem with datepicker on firefox with october month

### ISSUE THREAD

**Issue by kauehmoreno** [Hacker0x01/react-datepicker#1065]
Whenever October month is shown there is a bug which does not show all days, it can be seen it on mainpage of react-datepicker . [https://hacker0x01.github.io/react-datepicker/](url)

Both 2017 and 2018 are wrong on displaying all days as we can see on images attached
![screen shot 2017-10-10 at 13 03 40](https://user-images.githubusercontent.com/10923145/31397117-82770a5e-adbb-11e7-8872-0f06458fa2aa.png)

![screen shot 2017-10-10 at 13 01 13](https://user-images.githubusercontent.com/10923145/31397086-6b0668e2-adbb-11e7-82da-66a3217121a4.png)
 
This only happens on firefox so far.

**Comment by aij** [comment]
What version of Firefox are you using?

I just tried with Firefox 55.0.3, and it looks normal to me.

**Comment by kauehmoreno** [comment]
I've just check my version, and it's a little bit old.. I'm using 46.0.1 . I will update and check it out

**Comment by kauehmoreno** [comment]
I've just updated to 56.0.1 and still happening to me 
![screen shot 2017-10-10 at 13 28 28](https://user-images.githubusercontent.com/10923145/31398315-f1e24978-adbe-11e7-8003-8934141bd655.png)

**Comment by gabriel-card** [comment]
Hi, i'm having this issue in Firefox as well. Using 56.0.1.
Worth mentioning that in October, in Brazil (GMT-3) we have daylight saving time beginning. Maybe it's a problem with moment.js.

**Comment by rafeememon** [comment]
That seems like a good clue.  In the screenshot the calendar is displaying duplicate rows for the week of 8-14, probably due to incorrect day arithmetic around DST.

**Comment by aij** [comment]
@gabriel-card Can you check whether #1066 fixes it for you?

**Comment by gabriel-card** [comment]
@aij hi!
Just tested from master, didn't fix. Could it be moment.js's locale settings?
