### ISSUE TITLE
support for isomorphic React

### ISSUE THREAD

**Issue by lionng429** [Hacker0x01/react-datepicker#107]
when this date picker is rendered by server client, the system will return `document is not defined`

**Comment by RSO** [comment]
From what I understand Tether is causing this. I'm open to removing Tether as a dependency, if that's needed, but I don't think that I can find the time for this myself in the next couple of weeks.

**Comment by iam4x** [comment]
I may have a simple fix in head without dropping Tether for now, I need it too.

**Comment by martijnrusschen** [comment]
@iam4x Can you confirm this is fixed now?

**Comment by iam4x** [comment]
It's good for me!

**Comment by voronianski** [comment]
@iam4x @martijnrusschen what version are you using? I'm on `0.10.0` and still have tether complaints on server:

```
  var el = document.createElement('div');
           ^
ReferenceError: document is not defined
```
