### ISSUE TITLE
DatePicker does not work in IE 11

### ISSUE THREAD

**Issue by sarav1234** [Hacker0x01/react-datepicker#1076]
I have tried to open up your demo ( https://hacker0x01.github.io/react-datepicker/ ) using my IE 11 browser but it doesn't work and crashes. 
![datepicker_ieversion](https://user-images.githubusercontent.com/5393857/31625668-b8c4cc28-b25b-11e7-82a7-b240abd325fc.PNG)

In the dev tools, I see all sorts of errors relating to "bundle.js" as you can see below:

![datepicker_bundleerror](https://user-images.githubusercontent.com/5393857/31625615-856bb314-b25b-11e7-9045-4e7caa90c4c9.PNG)

**Comment by Grsmto** [comment]
You need to polyfill the `find` method as this is an ES6 one.

**Comment by rafeememon** [comment]
Even better, if this is the only thing preventing the picker from working in IE, we should remove the use of `.find` -- it can be trivially implemented with `.filter`.
