### ISSUE TITLE
Format calendar day names to display 3 characters instead of 2?

### ISSUE THREAD

**Issue by carmouche** [Hacker0x01/react-datepicker#1081]
Hi there!  I was wondering if there is any way to format the names of the days to use the 3 letter abbreviation instead of the 2 letter one?   I couldn't find anything to configure the format of that part. 

I'm referring to the row of day names that say MO TU, etc. I'd like to display MON, TUE, WED instead.

**Comment by carmouche** [comment]
Figured it out!  Looking through the code, I found a prop called `useWeekdaysShort` that does what I'm looking for.  The name is somewhat misleading though haha

`<DatePicker useWeekdaysShort={true} />`

**Comment by kambala3000** [comment]
@carmouche this isn't work for me :(

**Comment by AlanJereb** [comment]
@carmouche thank you! It worked as inteded.
Did you perhaps find a way to add class to the current date-name?

**Comment by targumon** [comment]
There's also `formatWeekDay`.
You provide it with a function that receives a full day name ('Sunday', 'Monday', etc.) and returns a ReactNode.

**Comment by mfrazier-quizlet** [comment]
> There's also `formatWeekDay`.
> You provide it with a function that receives a full day name ('Sunday', 'Monday', etc.) and returns a ReactNode.

@targumon Do you know if the `formatWeekDay` function always receives the English day names (Sunday, Monday, etc)? Or does the locale for the calendar affect the argument passed?

**Comment by targumon** [comment]
@mfrazier-quizlet no, `formatWeekDay` receives locale-dependent day names.
