### ISSUE TITLE
initial possible selection always starts with max date (even with selectsStart = true)

### ISSUE THREAD

**Issue by jblom** [Hacker0x01/react-datepicker#1084]
Hello,

probably I'm overlooking something, but I'm always getting my (starting) date picker to select the maximum year in the year dropdown (rather than the min date)

![schermafbeelding 2017-10-23 om 09 08 33](https://user-images.githubusercontent.com/917310/31876189-caff4ec4-b7d1-11e7-8419-45d9e1b2f87b.png)

This is my code (for my start & end date pickers):
```
<DatePicker
                                    disabled={this.props.disabled}
                                    selected={startDate}
                                    selectsStart={true}
                                    minDate={this.props.minDate}
                                    maxDate={this.props.maxDate}
                                    onChange={this.startDateChanged.bind(this)}
                                    showMonthDropdown={true}
                                    showYearDropdown={true}
                                    dropdownMode="select"
                                    className="form-control"
                                    placeholderText="Start date"/>


<DatePicker
                                    disabled={this.props.disabled}
                                    selected={endDate}
                                    selectsEnd={true}
                                    minDate={this.props.minDate}
                                    maxDate={this.props.maxDate}
                                    onChange={this.endDateChanged.bind(this)}
                                    showMonthDropdown={true}
                                    showYearDropdown={true}
                                    dropdownMode="select"
                                    className="form-control"
                                    placeholderText="End date"/>
```

Thanks (I hope I did not duplicate an issue; could not find this one)

**Comment by aij** [comment]
The default is to open to the current date, or the closest in the allowed range. You can use `openToDate` if you want more control over what date it opens to.

Your screenshot shows a date in the past. Have you checked whether it opens to maxDate when maxDate is in the future? If so, let us know, otherwise it looks like it's working as expected.

**Comment by jblom** [comment]
thanks for the quick reply and this works! I missed the openToDate property. Maybe (when scanning the list) I expected a different kind of property name (initialDate or something) for this.
