### ISSUE TITLE
onclickoutside issue on IE

### ISSUE THREAD

**Issue by tony1Centre** [Hacker0x01/react-datepicker#1102]
There is an issue (onclickoutside) in IE11,  and I've tried your page which is broke in IE as well.
https://hacker0x01.github.io/react-datepicker/

I've tried to down the version of the package to 56, 54, not working at all.

Thanks,
Tony

**Comment by bhldev** [comment]
The onclickoutside depends on Edge or other browsers and doesn't support IE https://github.com/Pomax/react-onclickoutside

The only workaround is to not use the onClickOutside handler and use say, blur and disregard the edge cases onClickOutside deals with... or use IE specific events https://stackoverflow.com/questions/3422754/problem-with-onblur-event-in-ie

Good luck

~B
