### ISSUE TITLE
how change to 24 - time format?

### ISSUE THREAD

**Issue by Greyewi** [Hacker0x01/react-datepicker#1103]
By default, datepicker has a 12-hour format, but in my country users used 24 time formats. How change time format to 24 ?

**Comment by yannickneemaa** [comment]
Hi,
You can use   `  timeFormat="HH:mm" `

**Comment by KirillYoYo** [comment]
How to chage time to 24 format in window with choise time?
![88](https://user-images.githubusercontent.com/26794095/32611999-e7c068da-c588-11e7-97a9-69324ee7a95e.png)
