### ISSUE TITLE
0.57.0 build seems to have older dependency for react-onclickOutside module

### ISSUE THREAD

**Issue by as-abhinav** [Hacker0x01/react-datepicker#1104]
It seems the latest build is having older dependency for react-onclickoutside module, which should be 6.6.2, but showing in bundled package.json as 6.0.0 and hence things are failing with latest react (16.0.0) bundling with webpack.

**Comment by martijnrusschen** [comment]
Can you try 0.58.0?

**Comment by as-abhinav** [comment]
Thanks a ton for super quick reply... Yes, it works now
