### ISSUE TITLE
TimeSelect not working with custom date format

### ISSUE THREAD

**Issue by mitsuruog** [Hacker0x01/react-datepicker#1105]
I tried to show time picker with custom date format(`YYYY/MM/DD`). but the time parts don't show.
I changed the date format to `LLL`. it works.

It's my code.

package.json

```
"react-datepicker": "^0.58.0",
```

js

```
<ReactDatePicker
    selected={selected}
    onChange={onChange}
    showMonthDropdown={true}
    dateFormat="YYYY/MM/DD"
    timeFormat="HH:mm"
    timeIntervals={15}
    showTimeSelect={true}
/>
```

![style guide](https://user-images.githubusercontent.com/1703219/32226946-42a4a44e-be8d-11e7-8626-1078d8135ee2.png)

Thanks.

**Comment by aij** [comment]
`YYYY/MM/DD` has no time parts. Add the time parts where you want them to appear in the `dateFormat`.

**Comment by mitsuruog** [comment]
ah, gotcha. thanks!!
