### ISSUE TITLE
Failing to update from version 0.57 to version 0.58

### ISSUE THREAD

**Issue by carpben** [Hacker0x01/react-datepicker#1106]
I'm trying to update to version 0.57 to version 0.58. 
My Package.json shows: 
 "react-datepicker": "^0.57.0"
when I type in the console 'npm outdated' it shows: 
 package: 'react-datepicker, current: 0.57, wanted: 0.57. 
Which to me doesn't make much sense. 
Nothing changes when I give the commands: 'npm update', or 'npm update -g react-datepicker'. 
This problem persists even now, 19 hours after version 0.58 was released on NPM. 
Looking for solutions. Thanks.

**Comment by rafeememon** [comment]
The caret dependency fixes the first non-zero number in the version.  You'll need to change your dependency to `^0.58.0`.
