### ISSUE TITLE
Escape button keeps the selected date 

### ISSUE THREAD

**Issue by mollynordh** [Hacker0x01/react-datepicker#1107]
Pressing the escape button when the calendar is open should perhaps not act as if the user actually has selected a date, but instead leave the date empty?

**Comment by aij** [comment]
It's not acting as if the user selected a date when I tried it. For me, pressing escape is cancelling the selection and keeping the previous value whether it was null or a date.

Can you reproduce the issue on the [demo site](https://hacker0x01.github.io/react-datepicker/), and provide steps to reproduce?
