### ISSUE TITLE
Clarification about onBlur 

### ISSUE THREAD

**Issue by firec0der** [Hacker0x01/react-datepicker#1110]
Hi there!

There is a mismatch between the code and examples.
There is a [date argument](https://github.com/Hacker0x01/react-datepicker/blob/master/docs-site/src/examples/on_blur_callbacks.jsx#L15), but the datepicker [returns an event](https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L229).

So, where is a mistake?

**Comment by crismethods** [comment]
@firec0der the second link is broken
