### ISSUE TITLE
How do you target the Popper styling?

### ISSUE THREAD

**Issue by LindAety** [Hacker0x01/react-datepicker#1112]
I can provide style to the <Input> element itself, which works as of now. However, the popper(when onFocus is triggered on the input element, supposedly), it kinda "hides" behind the rest of the content(I suppose, z-index could solve it?

However, seeing as I render the component as such:

```
                    <DatePicker
                        className={datePickerCSS}
                        dateFormat="DD.MM.YYYY"
                        selected={this.state.toDate}
                        onChange={this.handleToDateChange}
                    />
```

How would I style the Popper element that is nested inside your DatePicker component?

Thanks :)

**Comment by LindAety** [comment]
Just found that there's a `popperClassname` prop - that's the answer to my question ;) Closing!

**Comment by n3v3rd1e** [comment]
Its `popperClassName`  not `popperClassname`, just so someone would save time
