### ISSUE TITLE
How do I get access to the functionalities in Popper without styling?

### ISSUE THREAD

**Issue by cbll** [Hacker0x01/react-datepicker#1113]
I cannot import the CSS(it's a requirement I have from above), we use TypeStyle.

So basically I have to re-implement the styling in TypeStyle(and change it, of course to fit :) )

I can style the DatePicker component itself fine, but how do I access the Popper that trigger when selecting the Input element?

Basically, I get something like this now(I've added basic styling..):

![screen shot 2017-11-03 at 11 10 08](https://user-images.githubusercontent.com/9988107/32368955-bee13ecc-c087-11e7-9345-1c3fc09fa24f.png)

Is there a boilerplate of CSS to get a working Popper out? I mean, with the options to switch month etc, and see each date in correct rows/columns? I find it difficult to work out from it without the .css already implemented.

Here's some sample code I have so far:

```
        const popperCSS = style(
            {
                backgroundColor: "#fff",
                color: "grey",
                border: "1px solid rgba(209,197,195,0.6)",
                display: "inline-block",
                position: "relative",
                height: 225,
                width: 200,
            },
        );
```
```
                <DatePicker
                    placeholderText="dd.mm.yyyy"
                    popperPlacement={"left-start"}
                    className={datePickerCSS}
                    popperClassName={popperCSS}
                    dateFormat="DD.MM.YYYY"
                    selected={this.state.fromDate}
                    onChange={this.handleFromDateChange}
                />
```

Thanks in advance.

**Comment by aij** [comment]
Why can't you use CSS? Does TypeStyle somehow break the browser's support for CSS?

If you need help with TypeStyle, I don't think this is the right place.

If you're allowed to use `<style>` tags, `dist/react-datepicker.css` is all that should be needed.

If your intent is to re-implement all the existing CSS, you'll want to look at the source in `src/stylesheets/`, though keep in mind that would basically be a fork you'll have to maintain yourself.

**Comment by cbll** [comment]
I have no processor/loader for css.

I've looked at the scss source but it's a bit difficult to figure out how it would look in typestyle or just regular non-minified css.

**Comment by aij** [comment]
What browser doesn't support CSS these days? Some sort of react-native thing?

**Comment by aij** [comment]
Ok... And you are somehow able to load that CSS into the browser, right?

Is there some reason you're unable to load the react-datepicker CSS into the browser in the same way?

**Comment by cbll** [comment]
Yes, the reason is i'm on a major project and with the tech setup, it's not possible to just load pure css in the structure(to maintain consistency/development workflow).

Technical debt, and all that jazz :)
