### ISSUE TITLE
input doesn't have an id attribute

### ISSUE THREAD

**Issue by zhenximi** [Hacker0x01/react-datepicker#1124]
Can we have the `id` attribute on the input? for accessibility concern, it's suggested to have an `id` attribute on the input element.

**Comment by rafeememon** [comment]
`id` is a prop: https://github.com/Hacker0x01/react-datepicker/blob/master/docs/index.md

**Comment by harunkelesoglu** [comment]
But when i can not e.target.id or name when i try access changed input.How can i access to changing date input?
