### ISSUE TITLE
Example page does not work on IE11

### ISSUE THREAD

**Issue by marekadamek** [Hacker0x01/react-datepicker#1127]
Url: https://hacker0x01.github.io/react-datepicker/

What happened:
![image](https://user-images.githubusercontent.com/8816641/32490952-413d7a9a-c3b5-11e7-82ba-f41688801630.png)

![image](https://user-images.githubusercontent.com/8816641/32491000-5fa5fc00-c3b5-11e7-8b26-9c5f354d9212.png)

**Comment by rafeememon** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/1076
