### ISSUE TITLE
Add showYearDropdown range property

### ISSUE THREAD

**Issue by yankopetrov** [Hacker0x01/react-datepicker#1130]
Feature request!

Can you add range property for `showYearDropdown`? Something like `yearDropdownRange={[yearsBeforeThisYear, yearsAfterThisYear]}` for the range of year dropdown values. 

### UX problem
(I am using also `scrollableYearDropdown`)
- I have the case to pick date of birth and when try to select year, my birth year is not in the list
- Click on the years dropdown button add just one year to the list and because the list is scrollable, the button disappear 
- Scroll again to make the button visible
- Click again to add again one year
- Repeat till birth year. 

This is really bad user experience. The idea of the range is to have the possibility to say how mach years you want to have before and how much after current year when the year select is open. In my case i can say `yearDropdownRange={[100,0]}` so you already will have (almost)all possible birth years and clicking on button can be avoided. 

#### Update
`yearDropdownItemNumber` is something like range, but not flexible.

**Comment by GrzegorzBrdejMiquido** [comment]
Hi, I would like to see such feature too.
Also it would be good to parameterized number of years added to list when clicking on arrows.

**Comment by kriskross2893** [comment]
+1

**Comment by desmondgong** [comment]
The year dropdown is really a terrible user experience, can we make the arrows more flexible to switch the year list, rather than only 1 year per click.

**Comment by shmilyoo** [comment]
I'd like to see the feather , pass a range number to yearDropdownRange prop
