### ISSUE TITLE
onChangeRaw

### ISSUE THREAD

**Issue by kkashou** [Hacker0x01/react-datepicker#1133]
How can I serialize the data that comes in as "Moment" and I want the raw value instead?

**Comment by rafeememon** [comment]
Any number of ways -- `momentObject.valueOf()`, `momentObject.format`, etc.

**Comment by kkashou** [comment]
So I would need to loop through that object search for the value of "Moment" and then modify with what you mentioned above ?

**Comment by rafeememon** [comment]
You can use the moment.js docs to figure out what you need for your use case: https://momentjs.com/docs/
