### ISSUE TITLE
How to exclude time from the past (minTime), only if selected date is current date (minDate) ?

### ISSUE THREAD

**Issue by JustFly1984** [Hacker0x01/react-datepicker#1135]
I found how to exclude dates from the past with `minDate`,  I just pass `minDate={moment()}` 

If I set `minTime={moment().hours().minutes()}` it will exclude this time from all the dates.

I need to limit user to set time in past of current day.

I look for examples on the website, but could not find proper example.

PS. I Appreciate all the work you do for the community!

**Comment by manishbhatt94** [comment]
@martijnrusschen please have a look at this feature request!

**Comment by mathiasha** [comment]
I am looking for this feature too.
I want to set the minTime to be 6 hours in the future.

I tried this `minTime={moment().add(6, "hours")}`, but it didn't seem to do what I was expecting.

**Comment by aij** [comment]
Have you tried passing `minDate` based on the selected date?

**Comment by justinkahrs** [comment]
I'm coming across this as well. Any ideas how to manipulate the value of the time if the user didn't select one? It doesn't seem to care what the 'minTime' is, it will always default to 12:00am.

**Comment by mrchief** [comment]
This seems like a bug at this moment. Per the documentation, one needs to set both `minTime` and `maxTime`. But doing so disables all the time fields.

```
const now = moment().tz('America/New_York')
...
        <DatePicker
          isClearable
          minDate={now}
          minTime={now.hours(now.hour()).minutes(now.minutes())}
          maxTime={now.hours(23).minutes(45)}
          onChange={handleChange}
          placeholderText="Click to select a date"
          selected={input.value ? moment(input.value, 'America/New_York') : null}
          todayButton="Today"
          showTimeSelect
          timeFormat="HH:mm"
          timeIntervals={15}
          dateFormat={format}
        />

```
**Today's date**
![image](https://user-images.githubusercontent.com/781818/42387880-552d5e10-8176-11e8-9a74-eb7a0dfccb0a.png)

**Tomorrow's date**
![image](https://user-images.githubusercontent.com/781818/42387888-592e5e7e-8176-11e8-9aa7-c811d2ddbbba.png)

**Comment by mmcshinsky** [comment]
I would create a function that utilizes the `excludeTimes` parameter combined with your onChange event and/or selected parameter. If `selected` date === today's date then your `excludeTimes` will be an array of interval times you do not want displayed for this date. This function would have to run every time a date is selected on your onChange event and return null or and empty array when any other date other than the desired date is selected.

Note: This is untested but should in theory work. 😄

**Comment by GavinThomas1192** [comment]
+1 on this bug, same issue for me.

**Comment by fabiosangregorio** [comment]
+1

**Comment by charlesmarino1** [comment]
@fabiosangregorio The issue is that if you choose another date, the time is sticky. So if it's 1 pm, you can't see dates before 1 pm. Not only today but everyday. 

Still a bug

**Comment by fabiosangregorio** [comment]
@charlesmarino1 you can check if the selected date is the same of today, and if that is the case you can set the min/max time. I updated the previous comment with the code to do that.

**Comment by Valerika** [comment]
@fabiosangregorio Hi! This is not worked for me ((

**Comment by fabiosangregorio** [comment]
@Valerika here's a quick demo of it https://codepen.io/fabiosang/pen/PVyMJd?editors=0011

**Comment by Valerika** [comment]
@fabiosangregorio Thanks!!!!!!!!!!

**Comment by Valerika** [comment]
@fabiosangregorio  ((((
![image](https://user-images.githubusercontent.com/15037937/52881431-301e5000-316d-11e9-9528-5ba80c0231b5.png)

**Comment by Valerika** [comment]
![image](https://user-images.githubusercontent.com/15037937/52881502-68be2980-316d-11e9-97d9-0c7b8821b618.png)

**Comment by Valerika** [comment]
![image](https://user-images.githubusercontent.com/15037937/52883502-dbca9e80-3173-11e9-8347-6414a83ca3e2.png)

**Comment by Valerika** [comment]
@fabiosangregorio This is due to the version, I lowered the version to 1.4.1 and it works
Thanks!

**Comment by PaulRBerg** [comment]
Happy to announce that I sorted this out in #1718 🚀

### Min Date

<img width="883" alt="Screen Shot 2019-04-21 at 16 28 25" src="https://user-images.githubusercontent.com/8782666/56497353-12ff5800-64f5-11e9-9595-face89dcb05b.png">

### Max Date

<img width="889" alt="Screen Shot 2019-04-21 at 16 28 44" src="https://user-images.githubusercontent.com/8782666/56497362-17c40c00-64f5-11e9-99c6-c2ace9787c5e.png">

Read more details on the PR [page][pr-page].

[pr-page]: https://github.com/Hacker0x01/react-datepicker/pull/1718

**Comment by dlrandy** [comment]
Hi guys, for @JustFly1984 's question, i just encountered , any solution?

**Comment by JustFly1984** [comment]
@dlrandy Me and my team has made custom React datepicker with better accessibility support, written in typescript, supporting all main features of react-datepicker, and I’m planning to make it as npm package this month. Does anybody want to join as maintainer? I already have pretty much successful npm project @react-google-maps/api, so I’m retry sure in success of new datepicker. You can see an implementation in production at https://www.drivefromto.com

**Comment by farnell** [comment]
You can get this working now without this PR. 

This will exclude all times before now time, only future dates/times are selectable, requires moment js. 

```                                                
import moment from 'moment'
...

// set this in your state init call
this.state.minTime =  this.calculateMinTime(new Date()),


// add these two functions to your component
calculateMinTime = date => {
    let isToday = moment(date).isSame(moment(), 'day');
    if (isToday) {
        let nowAddTwoHours = moment(new Date()).add({hours: 1}).toDate();
        return nowAddTwoHours;
    }
    return moment().startOf('day').toDate(); // set to 12:00 am today
}

handleDateChange = date => {
    this.setState({
        closeDate: date,
        minTime: this.calculateMinTime(date),
    });
}

// DatePicker component in your render function.
<DatePicker
      onChange={this.handleDateChange}
      selected={this.state.closeDate}
      minDate={new Date()}
      minTime={this.state.minTime}
      maxTime={moment().endOf('day').toDate()} // set to 23:59 pm today
      timeIntervals={60}
      showTimeSelect
/>
```

enjoy :)

**Comment by trplfr** [comment]
Solution with date-fns:

```
import { endOfDay } from 'date-fns'

...

<DatePicker
  selected={selectedDate}
  minDate={new Date()}
  minTime={new Date()}
  maxTime={endOfDay(new Date())}
  showTimeSelect
  timeFormat='HH:mm'
  timeIntervals={15}
  dateFormat='HH:mm'
  onChange={handleDateChange}
/>
```

**Comment by trplfr** [comment]
date-fns solution:

calculateMinTime = date => isSameDay(date, new Date()) ? new Date() : startOfToday()

**Comment by trplfr** [comment]
date-fns solution:

```
import { isSameDay, startOfToday } from 'date-fns'

...

calculateMinTime = date => isSameDay(date, new Date()) ? new Date() : startOfToday()

state = {
  selectedDate: null,
  minTime: this.calculateMinTime(new Date())
}

...

handleDateChange = date => {
  this.setState({
    selectedDate: date,
    minTime: this.calculateMinTime(date)
  })
}

...

<DatePicker
  onChange={this.handleDateChange}
  selected={selectedDate}
  minDate={new Date()}
  minTime={minTime}
  maxTime={endOfDay(new Date())}
  timeIntervals={15}
  showTimeSelect
/>
```

**Comment by kbiswas100** [comment]
see it take UTC time , so if you use moment js then you can use this 
```
minTime={ moment().subtract('hour', 5).utc()}
maxTime={moment().utc()}

**Comment by vrinceanuv** [comment]
If anyone still looks for a solution for this, i came up with this:

`
handleDateChange = date => {
  this.setState({
    selectedDate: date,
    minTime: this.calculateMinTime(date)
  })
}

...

<DatePicker
  onChange={this.handleDateChange}
  selected={this.state.selectedDate}
  minDate={new Date()}
  {...(moment(minDate).isSame(moment(), 'day') && {
       minTime: new Date(moment(values?.start).add(5, 'm')),
       maxTime: new Date(moment().endOf('day')),
  })}
  timeIntervals={15}
  showTimeSelect
/>
`

Checks if the day is today, and if it is adds minTime and maxTime. Otherwise, it removes those props.

**Comment by Boopalanoptisol** [comment]
<DatePicker
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      timeInputLabel="Time:"
      dateFormat="MM/dd/yyyy h:mm aa"
      showTimeInput
    />
    
    For this how can we disable the past time for current date alone.

**Comment by artemlenkevich** [comment]
This solution works great:

const filterTime = (date) => {
    const isPastTime = new Date().getTime() > date.getTime();
    return !isPastTime;
  };

<DatePicker
selected={startDate}
onChange={(date) => setStartDate(date)}
timeInputLabel="Time:"
dateFormat="MM/dd/yyyy h:mm aa"
showTimeSelect
filterTime={filterTime}
/>

**Comment by GodAlmighty990** [comment]
@artemlenkevich This was a great solution, Helped me today. Thank you!

**Comment by truongthi-bic** [comment]
@artemlenkevich it's helpful. thank you

**Comment by clumsycompiler** [comment]
@artemlenkevich Thanks.

**Comment by tomnar** [comment]
@artemlenkevich Nice one! :)
