### ISSUE TITLE
How to chage time to 24 format in window with choise time?

### ISSUE THREAD

**Issue by KirillYoYo** [Hacker0x01/react-datepicker#1139]
Change to 24h format here:
![12344](https://user-images.githubusercontent.com/26794095/32711803-b2efbab6-c862-11e7-8b16-7e6c5bd3a266.png)

**Comment by kblodget** [comment]
This is assuming you have a property set up that sets when the user wants 12 hour versus 24 hour formats. 
``
  <DatePicker
      timeFormat={this.props.timeformat === '24' ? 'HH:mm' : 'hh:mm a'}
  </
``

**Comment by Manmathkulkarni** [comment]
Hi, 

Is this possible have 24 hour time format in input time in react date picker? So instead of AM PM, user can enter 24 hour time in the input box.

https://reactdatepicker.com/#example-input-time

Kindly help if anyone knows how can this be made to work.

Best regards,
Manmath
