### ISSUE TITLE
Styles are broken when used with time picker in Bootstrap's col

### ISSUE THREAD

**Issue by BorisTB** [Hacker0x01/react-datepicker#1141]
Datepicker alone looks ok, but when I want to use it with time picker, it's all broken when used in Bootstrap 4 column.

react-datepicker: 0.61.0
bootstrap: 4.0.0-beta.2

![screen shot 2017-11-14 at 11 33 40](https://user-images.githubusercontent.com/18208654/32775579-1d9609a6-c930-11e7-9e2c-a953c09a9872.png)

**Comment by JeffLoo-ong** [comment]
I have a similar issue were stuffing it into a bootstrap column causes loss of styling. 

react-datepicker: 0.61.0
bootstrap 4.0.0-alpha.6

Also running with Typescript if that matters.

**Comment by naishe** [comment]
I still have the same issue, when Col is small enough to not fit the Popper the time selector wrap at the bottom like the image shown.

    "bootstrap": "^4.1.3",
    "react-datepicker": "^1.8.0",

**Comment by pdanem** [comment]
A workaround that worked for me was to set the following in CSS:

```css
.react-datepicker-popper: {
    width: max-content;
}
```
