### ISSUE TITLE
Show db saved date value on datepicker field

### ISSUE THREAD

**Issue by DamPe88** [Hacker0x01/react-datepicker#1145]
Hi ,
I am trying this module and so far its seems ok.But when I try load already saved date in the datepicker field it wont show. 

Actually saved date format is 'YYYY-MM-DD' and current format is LL.

`<DatePicker id="deadline"
                                selected={this.state.deadline}
                                onChange={this.handleDeadlineChange}
                                dateFormat="LL"
                                scrollableYearDropdown
                                yearDropdownItemNumber={15}
                                showYearDropdown
                            />`

All the newly created dates are on new format which is LL, but when i try to load old date format, datepicker doesn't work.

Any idea?

**Comment by rafeememon** [comment]
You must pass a moment() object to the selected prop.  https://momentjs.com/docs/#/parsing/

**Comment by DamPe88** [comment]
Hi rafeememom,
It works. But can we have something like this?.
`selected={moment(data.meta.deadline) || moment()}`

if there is no data then show the current date.Something like that.

Thanks
