### ISSUE TITLE
Set a default value if the database value is empty

### ISSUE THREAD

**Issue by DamPe88** [Hacker0x01/react-datepicker#1147]
Connected to issue number : #1145

I have the datepicker component like this
`<DatePicker id="deadline" selected={moment(data.meta.deadline)} onChange={this.handleDeadlineChange} dateFormat="LL" scrollableYearDropdown yearDropdownItemNumber={15} showYearDropdown />`

If the `data.meta.deadline ` is empty cant we have something like below
`selected={moment(data.meta.deadline) || moment()}`

if there is no data then show the current date.

Thanks in advance.

**Comment by DamPe88** [comment]
Any help on this

**Comment by nicsptl** [comment]
I might be wrong, but its working for me, as I provide moment() on this.state.selected and if database return any value initialize with value in componentDidMount() with other initialization.  Or you can try following
this.state = {
selected: ((data.meta.deadline)
                ? moment(data.meta.deadline)
                : moment()
}
<Datepicker  selected={this.state.selected}/>
