### ISSUE TITLE
IE11 Popper unclickable

### ISSUE THREAD

**Issue by hanselsen** [Hacker0x01/react-datepicker#1148]
It seems that when you're using a customInput, the popper is not clickable in IE11. In Edge it works fine.
When I use the element selector of the devtools, it shows that the popper is part of the customInput. See attachment.

![devtools](https://user-images.githubusercontent.com/1150323/33064276-69251c98-cea5-11e7-9e5c-52a2d663958e.png)

**Comment by 1puneetbhatia** [comment]
Hi @hanselsen did you found the solution or any workaround for this?
