### ISSUE TITLE
Selecting time does not dismiss the calender but executes onChange event

### ISSUE THREAD

**Issue by shrutic** [Hacker0x01/react-datepicker#1149]
Selecting the date on the other hand dismisses the calender and executes onChange event. Can I get the following behavior instead?

AKA
When I select the date, I want calendar to remain open until user selects a time? 
When I select a time, I want the calendar to close and have the onChange event executed?

My goal is to have user select both date and time before dismissing the calendar and given that date renders on the right, it goes that user selects date first and then time 

<DatePicker
                        placeholderText = {text}
                        showTimeSelect={true}
                        onChange={this._onRowTapped.bind(this, null)}
                        timeFormat='HH:mm'
                        timeIntervals={30}
                        minDate={moment()}
                        popperPlacement='top-end'
                        popperModifiers={{
                            offset: {
                                enabled: true,
                                offset: '5px, 10px'
                            }
                        }}
                    />

**Comment by namezero** [comment]
+1

**Comment by tamouse** [comment]
The fix #1169 does keep the picker open until the time is selected, however, if fires `onChange` when the user selects a date *and* when the user selects a time. Can we have a single `onChange` event, please?
