### ISSUE TITLE
disabled props

### ISSUE THREAD

**Issue by WaveString** [Hacker0x01/react-datepicker#115]
Hello. Thanks for this nice component. But there was a need to disable INPUT under certain conditions.
It would be great if the components looks like:
  <DatePicker
        key="example5"
        disabled={true}
        selected={this.state.example5Selected}
        onChange={this.handleExample5Change}
        weekStart="0"
        placeholderText="I start on Sunday!"
 />
Thanks!

**Comment by Asgator** [comment]
+

**Comment by RSO** [comment]
Hi there! I can indeed see that a `disabled` property would make sense. Do you think that you have time to setup a PR? I personally don't think that I'll find the time for it anytime soon, so it would be awesome if someone else could step up to make it!

**Comment by skurger** [comment]
This issue can now be closed.

**Comment by RSO** [comment]
Thanks!

**Comment by skurger** [comment]
No problem!
