### ISSUE TITLE
openToDate & time

### ISSUE THREAD

**Issue by namezero** [Hacker0x01/react-datepicker#1150]
openToDate prop dont  scroll to the requested time when it render
![image](https://user-images.githubusercontent.com/428343/33180366-c5672442-d06c-11e7-8cd3-2448545ae4ef.png)

**Comment by alex-shamshurin** [comment]
Please give a code example. `openToDate` should only open the widget at the right page. It does not `select`

**Comment by micahalcorn** [comment]
@alex-shamshurin I assume that @namezero's expectation is that the timepicker's auto-scroll should prioritize `openToDate` over the current time. Based on my understanding of [the `componentDidMount` fallback](https://github.com/Hacker0x01/react-datepicker/blob/1306eb20cbdbb7cdea14e280d7a5939a0200ca73/src/time.jsx#L40), it currently falls back to the current time if no selection is passed. 

To be consistent with the `openToDate` behavior, the "open to time" functionality described here would need to also prioritize the time of the `openToDate` over the selection (but not result in a selection).
```
  componentDidMount () {
    // code to ensure selected time will always be in focus within time window when it first appears
    const multiplier = 60 / this.props.intervals
    const currH = (this.props.openToDate ? getHour(this.props.openToDate) : (this.props.selected) ? getHour(this.props.selected) : getHour(newDate()))
    this.list.scrollTop = 30 * (multiplier * currH)
  }
```

An alternative would be to only scroll to the "open to time" if a selection is not present:
```
  componentDidMount () {
    // code to ensure selected time will always be in focus within time window when it first appears
    const multiplier = 60 / this.props.intervals
    const currH = (this.props.selected) ? getHour(this.props.selected) : getHour(this.props.openToDate || newDate())
    this.list.scrollTop = 30 * (multiplier * currH)
  }
```

Would the maintainers be receptive to a pull request that includes one of these two changes? I have a user that is expecting this behavior. He is often using the datepicker in the early morning hours, but his selection always involves an evening time. It would be nice if we could save him some scrolling.

cc: @martijnrusschen

**Comment by micahalcorn** [comment]
Bump 😇
