### ISSUE TITLE
Does customInput pass time value?

### ISSUE THREAD

**Issue by jimyaghi** [Hacker0x01/react-datepicker#1151]
I'm using the customInput property to render the selected date in a read-only manner using moment's "fromNow" format method. However, it does not appear the time is sent through--only a date string. 

Would it not make sense to send over a Moment or Date object to the custom input component so one can format or manipulate the selection in any way they wish?

~jim

**Comment by magestican** [comment]
I need this feature as well :(

**Comment by AndreevskiAleksandar** [comment]
Any solution for this?

**Comment by vvdwivedi** [comment]
Did anyone reached to a solution on this?
