### ISSUE TITLE
Popper errors with latest react version

### ISSUE THREAD

**Issue by martinchristov** [Hacker0x01/react-datepicker#1153]
When ReactDatepicker is imported a warning shows up:

`Invalid argument supplied to oneOf, expected an instance of array Popper.js:256`

The date input shows up, but when it's clicked an error is thrown:

`Uncaught TypeError: _popper2.default is not a constructor
    at Popper._createPopper (Popper.js:173)
    at Popper._updatePopper (Popper.js:152)`

I am using react 16 and react-datepicker 0.61

**Comment by Rumpsteak** [comment]
I get the exact same issue.

react 16, react-datepicker 1.2.1

**Comment by danantal** [comment]
Any news on this?

**Comment by theruther4d** [comment]
Looks to me like for some reason the import of `placements` from `popper.js` is returning `undefined` instead of an array of placements. Will try to look into it and submit a PR in the next few days unless somebody has time sooner.
