### ISSUE TITLE
.createClass is not a function via unpkg

### ISSUE THREAD

**Issue by rmilejcz** [Hacker0x01/react-datepicker#1156]
Trying to use your package via unpkg, have tried both 0.40.0 and 0.61.0 and both give similar errors something.createClass is not a function.

I know it is not a dependency issue because I have React loaded via unpkg as well, and several other packages that depend on React and work without issue. I also have moment.js loaded before react-datepicker. I'm using the default unkpkg file listed in your package.json, react-datepicker.min.js

I really need a datepicker so any help with this is much appreciated. Thanks!

**Comment by robbiemilejczak** [comment]
duh this isn't compatible with React16, anyone who reads this just use React15 instead.

You can close.

**Comment by robbiemilejczak** [comment]
Nvm, still get error `module is undefined`. I have other packages via unpkg that use CommonJS and they work fine so not sure if this issue is with your config or with unpkg.
