### ISSUE TITLE
Year dropdown scroll defaults to max value

### ISSUE THREAD

**Issue by Bobvantpadje** [Hacker0x01/react-datepicker#1159]
I'm using the YearDropdown function on the datepicker but when I click it, the dropdown will always start at the top(max year). Is there a way to set the default value of the dropdown to the current year? 

**How it opens now**
![image](https://user-images.githubusercontent.com/22618775/33517165-7632b8fe-d77f-11e7-87cc-7171a90e7972.png)

**How I want it to open**
![image](https://user-images.githubusercontent.com/22618775/33517184-c0a82acc-d77f-11e7-8e0e-190c61a9dbf9.png)

**Comment by lmichailian** [comment]
@Bobvantpadje You resolved this ?

@Hacker0x01 any hint ?

**Comment by Bobvantpadje** [comment]
@lmichailian Nope.. I'm using another datepicker now

**Comment by acollier88** [comment]
@Bobvantpadje @lmichailian I used maxDate={moment()}

**Comment by ketysek** [comment]
Scroll position of the year picker is really not user friendly now ... 👎

**Comment by infinitbility** [comment]
Added Example of Scrollable Year dropdown

https://infinitbility.com/react-datepicker-scrollable-year-dropdown

**Comment by bhumi0901** [comment]
I'm also having same issue, i have set scrollableYearDropdown={true} but now the issue is it automatically scrolls up to the max value of year, it should scroll where the year is selected.

**Comment by ardibegolli** [comment]
same issue here

**Comment by javlund** [comment]
I had this issue as well. Turns out that it was due to me using `value` instead of `selected` for the value. Hope that helps someone.
