### ISSUE TITLE
Shifting datepicker after change height

### ISSUE THREAD

**Issue by Tsvetkovv** [Hacker0x01/react-datepicker#1160]
Steps to reproduce:
1. Open datepicker on top.
2. Switch to a month that has another week count than previous.
3. Return to previous

**Actual result:** trying to click on month selector is failed because of the datepicker shifts. Only second click let change month.
**Expected result:** the first click changes a month.

Seems like the datepicker updates position on the first click

The bug reproduces on the demo page:
![2017-12-04_19-15-59](https://user-images.githubusercontent.com/11594423/33560325-ddfb45dc-d928-11e7-8d99-20c72e25ea94.gif)

**Comment by rafeememon** [comment]
What version are you using?  This bug is a dupe (https://github.com/Hacker0x01/react-datepicker/issues/361) but comment on the other one if it's not resolved with the latest version.

**Comment by rafeememon** [comment]
Actually, I'm seeing this on the demo page too.  Re-opening

**Comment by jordenstuder** [comment]
Has there been any progress on this?
