### ISSUE TITLE
Add 'id' as prop

### ISSUE THREAD

**Issue by vrinceanuv** [Hacker0x01/react-datepicker#1165]
Would be nice to have a feature where you can pass the id as well to the calendar input, so in the case where you have a `<label for="abc">aaa</label>` it can focus on the date picker input.

**Comment by vtaits** [comment]
Maybe looks not beautiful, but works

```
<DatePicker customInput={<input type="text" id="abc" />} />
```

**Comment by vrinceanuv** [comment]
it is htmlFor, will have a look. Thanks
