### ISSUE TITLE
Calendar/popper shifts vertically when cycling through months

### ISSUE THREAD

**Issue by mhluska** [Hacker0x01/react-datepicker#1167]
A small UI issue: the calendar shifts vertically when I cycle through months because of the variable number of days/rows in a month. This makes it hard to keep clicking because I have to adjust my mouse.

This only happens when the popper is positioned to the top. It's fine when positioned to the bottom.

Is this a known issue and is there a workaround?

**Comment by rafeememon** [comment]
This is one of our favorites: https://github.com/Hacker0x01/react-datepicker/issues/361

**Comment by mhluska** [comment]
For those wondering, the solution was to use the `fixedHeight` prop`.
