### ISSUE TITLE
Possible to change blue of selected date and gray of placeholder?

### ISSUE THREAD

**Issue by flaurida** [Hacker0x01/react-datepicker#1172]
Hi React datepicker,
Is it possible to change the blue color of the selected date in the calendar? In addition, I would like to change the shade of gray for the placeholder text. I did not see the examples doing it, so was just wondering if it was possible. Thanks!

Sincerely,
Laura

**Comment by alex-shamshurin** [comment]
Yes, you can change it in css file, which is included.

**Comment by lejoss** [comment]
hi, thanks for the libray, i'm trying to change color of selected day, i notice the `react-datepicker.css` under /dist, and also sass files. i tried to copy the datepicker's stylesheet and add some changes, then i tried to import it in my code, but it's not working.

whats the process for changing the color of selected day? @flaurida @alex-shamshurin

**Comment by aij** [comment]
@lejoss Without knowing exactly what you did, it could be any number of things... It sounds like you're on the right track though. If you're including both the default style and your custom style, you may need to check on ordering or specificity. https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

If you need help learning CSS, there are plenty of resources throughout the web.
