### ISSUE TITLE
0.60.2 Release date?

### ISSUE THREAD

**Issue by lewisdiamond** [Hacker0x01/react-datepicker#1173]
I just want to know if 0.60.2 is going to be released shortly. Otherwise I'll have to release my clone to NPM as react-datepicker makes yarn fail when imported from github.

**Comment by martijnrusschen** [comment]
Which commit are you looking for? Does 0.61.0 fixes the issue for you?

**Comment by lewisdiamond** [comment]
Oh sorry I thought the next version was 0.60.2.
No 0.61.0 doesn't fix it, it's the very latest commit I'm looking for: f49251167b6f0fb9cb356736cf4dbac0247856f1

**Comment by martijnrusschen** [comment]
We'll get a new release out this week. Most likely today or tomorrow.

**Comment by lewisdiamond** [comment]
Thanks.
