### ISSUE TITLE
Unable to initialize custom input with empty date (selected = null)

### ISSUE THREAD

**Issue by yangtheng** [Hacker0x01/react-datepicker#1174]
I want to make two date drop downs with departing and returning date for flights. I want my system to identify that if returning date is empty it is assumed that the user is looking for a one way flight. However I am able to render the datepicker if I do not pass a moment date object to selected:

` <div style={{display: 'inline-block', width: '25%'}}>
<DatePicker customInput={<CustomDatePicker flight />} selected={this.state.departureDate} dateFormat={'DD MMM YYYY'} minDate={moment(this.props.dates[0])} maxDate={moment(this.props.dates[this.props.dates.length - 1])} onSelect={(e) => this.handleChange(e, 'departureDate')} />
          </div>
          <div style={{display: 'inline-block', width: '25%'}}>
            <DatePicker customInput={<CustomDatePicker flight />} selected={this.state.returnDate} dateFormat={'DD MMM YYYY'} minDate={moment(this.props.dates[0])} maxDate={moment(this.props.dates[this.props.dates.length - 1])} onSelect={(e) => this.handleChange(e, 'returnDate')} />
          </div>`

and state is initialized with: 

`     departureDate: moment(new Date(this.props.date)),
      returnDate: null,`

I have tried various values for return date including {} and '', both does not work in my case.

**Comment by aij** [comment]
It sounds like you need to debug your code. Passing `selected={null}` seems to be working fine on the examples page.

**Comment by yangtheng** [comment]
The example does not use a custom input. I have just tried removing the custom input from my own component and selected=null works. However, why does it not work with custom input?

Anyway, this is the component I am using for the customInput prop:
`class CustomDatePicker extends Component {
  render () {
    return (
      <span
        key='datePicker'
        onClick={this.props.onClick}>
        {this.props.value}
      </span>
    )
  }
}`

I was just following the example from https://hacker0x01.github.io/react-datepicker/ but with <span> instead because I do not want a button.

**Comment by yangtheng** [comment]
Okay, it works after I change it to a button and removed the borders and set background as transparent. Works fine for me for now (does not look like a button). It will be good if the custom input works reliably for a variety of elements.
