### ISSUE TITLE
Date range glitch when both datepickers are selected

### ISSUE THREAD

**Issue by sidewayskumara** [Hacker0x01/react-datepicker#1176]
Date range example - Focus flickers back and forth rapidly when both datepickers are selected (Shift + click). 

![daterange_glitch 11 42 59 am](https://user-images.githubusercontent.com/26181282/33973184-dc32ee82-e0c4-11e7-84a7-5449901e8344.gif)

**Comment by Tsvetkovv** [comment]
IE dies when it happening.
![image](https://user-images.githubusercontent.com/11594423/39251316-03aed00a-48b4-11e8-8dc2-1ff4a0833b45.png)

**Comment by rjanot** [comment]
the "hack" we have found is to use the ref of the first DatePicker and call `setOpen(false)` on it, before giving focus to the second DatePicker
