### ISSUE TITLE
maxDate issue

### ISSUE THREAD

**Issue by popmanhe** [Hacker0x01/react-datepicker#1178]
If there are two datepickers on the page and the second one has set maxDate, then two datepickers have the same value. If I remove the maxDate from the second datapicker, it works properly.
>   <div className="control-group form-elements">
                        <label className="control-label">Start Time (UTC)</label>
                        <div className="controls">
                            <DateTimePicker name="startTimestamp"
                                onChange={(date) => this.handleDateChange(date, 'startTimestamp')}
                                showTimeSelect
                                dateFormat="YYYY/MM/DD"
                                timeFormat="HH:mm"
                                timeIntervals={30}
                                minDate={moment()}
                                selected={this.state.startTimestamp}
                                placeholderText="When giveaway starts"
                            />
                        </div>
                    </div>
                    <div className="control-group form-elements">
                        <label className="control-label">End Time (UTC)</label>
                        <div className="controls">
                            <DateTimePicker name="endTimestamp"
                                onChange={(date) => this.handleDateChange(date, 'endTimestamp')}
                                selected={this.state.endTimestamp}
                                showTimeSelect
                                dateFormat="YYYY/MM/DD"
                                timeFormat="HH:mm"
                                timeIntervals={30}
                                minDate={this.state.startTimestamp}
                                maxDate={this.state.startTimestamp.add(1, "months")}
                                placeholderText="When giveaway ends"
                            />
                        </div>
                    </div>
![maxdate](https://user-images.githubusercontent.com/2193792/34030782-39789750-e123-11e7-93c2-2496cf975989.png)

**Comment by rafeememon** [comment]
`add` mutates the `moment` object.  You'll need to clone it before adding a month
