### ISSUE TITLE
Proposal to add custom function for check input value for emptiness

### ISSUE THREAD

**Issue by vtaits** [Hacker0x01/react-datepicker#1185]
I use `react-input-mask` as `customInput` component of datepicker. Empty value of input in my case is `'__.__.____'` but there is check only for empty string in `handleChange` method.

```
  handleChange = (event) => {
    if (this.props.onChangeRaw) {
      this.props.onChangeRaw(event)
      if (event.isDefaultPrevented()) {
        return
      }
    }
    this.setState({ inputValue: event.target.value })
    const date = parseDate(event.target.value, this.props)
    if (date || !event.target.value) {  // <-----------------------
      this.setSelected(date, event, true)
    }
  }
```

I propoes add `isRawEmpty` prop for check this, e.g.

```
  static propTypes = {
    isRawEmpty: PropTypes.func,
  }

  static get defaultProps () {
    return {
      ...
      isRawEmpty: (value) => !value,
    }
  }

  handleChange = (event) => {
    ...
    if (date || this.props.isRawEmpty(event.target.value)) {
    ...
  }
```

**Comment by aij** [comment]
That seems more like a placeholder than an actual value.

**Comment by aij** [comment]
Please let us know if the `placeholderText` prop does not suit your needs.

**Comment by vtaits** [comment]
No, it is not `placeholderText`, it is value from [react-input-mask](https://www.npmjs.com/package/react-input-mask). `react-datepicker` don't provides native mask therefore i need to use other libraries. Of course, i can create proxy-component for prevent calling `onChange` with placeholder-like value.

But there is 2nd issue: i need to reset value of datepicker for any invalid date in input, but now it resets only for empty value in input.

![reactdatepicker-value-reset](https://user-images.githubusercontent.com/4801414/37343216-e96986ca-26d7-11e8-95b4-4bf96d42ba39.gif)

**Comment by aij** [comment]
Hmm, it seems like making `react-input-mask` understand it's own empty value would be a cleaner solution. Is there a reason it can't present itself as empty when it is empty?

I don't know what you're trying to show by "2nd issue". It seems to work when I tried the demo site. Is it at all related to `react-input-mask`?

**Comment by vtaits** [comment]
No, "2nd issue" is not related to `react-input-mask`. I try showing next state:
- input value is "03/16/" (invalid);
- datepicker value is `Fri Mar 16 2018 ...` (doesn't match current input value).
