### ISSUE TITLE
Support dynamic props

### ISSUE THREAD

**Issue by at0g** [Hacker0x01/react-datepicker#120]
There's no way to set other props on the datepicker input element - it's a black box.

So if I wanted to add props such as onBlur, aria-*, className or anything else that is not explicitly added, they are simply ignored.

**Comment by martijnrusschen** [comment]
Do you still want to introduce dynamic props? Any way we can help you?

**Comment by mqklin** [comment]
@martijnrusschen, i want to prevent keypress typing, so i need a `onKeyPress` prop.

**Comment by rafeememon** [comment]
@mqklin does the `readOnly` prop work for your use case?

**Comment by mqklin** [comment]
I don't really remember... I chose another calendar

**Comment by rafeememon** [comment]
Closing this for the sake of getting to #inboxzero, as it looks like the issues mentioned here are addressed

**Comment by umakajan** [comment]
When using react-a11y, I get the following console log message: 

```
DateInput You have an unlabeled element or control. Add `aria-label` or `aria-labelledby` attribute, or put some text in the element.
```

Please let me know if this is resolved anywhere.
