### ISSUE TITLE
Year dropdown error in IE11 and Edge

### ISSUE THREAD

**Issue by mitaxe** [Hacker0x01/react-datepicker#1201]
### Actual behavior
Hi guys. When we open datepicker and then open year dropdown and then click outside we get this error:
`Unable to get property 'getInstance' of undefined or null reference`

![ie11](https://user-images.githubusercontent.com/17300379/34768793-971e97b0-f604-11e7-96f3-18c36e25ea22.png)

Error:
![image](https://user-images.githubusercontent.com/17300379/34768831-ae00582e-f604-11e7-8e11-610445303b51.png)

It is only reproduced in IE and Edge browsers

**Comment by robbporto** [comment]
Same here.

**Comment by smtaydemir** [comment]
+1
