### ISSUE TITLE
handleChange Target is undefined

### ISSUE THREAD

**Issue by kothaanu** [Hacker0x01/react-datepicker#1202]
### Expected behavior
Must be able to get target  in handlechange so I can set the state
### Actual behavior
on datepicker I am get target as undefined
### Steps to reprodcue
Render....Code... contains 2 datepickers and 1 text area

                            <DatePicker 
                                  selected={this.state.transactionDate}
                                  onChange={this.handleChange}
                            />
     
                            <DatePicker 
                                  selected={this.state.postDate}
                                  onChange={this.handleChange}
                            />
                       
                            <textarea type="text" name="loans"
                                  value={this.state.loans}
                                  onChange={this.handleChange}
                                  placeholder="loan numbers"
                                  className="form-control"
                                  tabIndex={3} />

Handle Change...

  handleChange({ target }) {
    console.log('PostDate: ' + target);
    //var errors = this.validate(target);
    this.setState({
      error: { loans: false, message: '' },
      isValid: '',
      [target.name]: target.value,
    });
  }

**Comment by rafeememon** [comment]
The callback is called with a date object, not an event.  See the example in the [readme](https://github.com/Hacker0x01/react-datepicker/blob/master/README.md#installation)

**Comment by SistemasSouza** [comment]
I have same problem, some solution to this it
