### ISSUE TITLE
Changing locale doesn't change locale text for inline datepicker

### ISSUE THREAD

**Issue by klis87** [Hacker0x01/react-datepicker#1203]
I have a following component:
```js
import React from 'react';
import VendorDatePicker from 'react-datepicker';
import { connect } from 'react-redux';

import { currentLanguageSelector } from 'stores/routes/selectors';

const mapStateToProps = state => ({
  currentLanguage: currentLanguageSelector(state),
});

const DatePicker = ({ currentLanguage, ...props }) => (
  <VendorDatePicker
    inline
    locale={currentLanguage}
    {...props}
  />
);

export default connect(mapStateToProps)(DatePicker);
```
### Expected behavior
When in redux `currentLanguage` is changed, new locale prop is passed to `DatePicker` and locale texts should be translated to a new language.

### Actual behavior
When in redux `currentLanguage` is changed, new locale prop is passed to `DatePicker` and locale texts is not translated to a new language. Only for example after DatePicker internal state like selected value is changed, text is translated.

### Steps to reproduce
Use `DatePicker` component in `inline` version and pass dynamic locale. After changing it, you will notice that datepicker text remains the same.

**Comment by etienne-bondot** [comment]
Did you try to import the moment locale as `import 'moment/locale/<your_locale>';` ?

**Comment by klis87** [comment]
Actually moment import all locales as the default, and I import only `en-gb` and `pl` by weboack config: `new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /en-gb|pl/),`

Locale is working fine, it is imported and translate everything correctly, the only problem is that `DatePicker` doesnt rerender when ONLY `locale` prop is changed - after any other prop like `selected` is changed, suddenly new locale is picked up. This issue is only for inline calendars.

**Comment by cheton** [comment]
Same to me with the following setup:
```jsx
<DatePicker
    inline
    locale={locale}
/>
```

If I change the `locale` prop, it won't update current translation unless I change the selected date with mouse click or update the "selected" prop.

**Comment by patfrat** [comment]
Same problem by my side, the locale text changes when choosing another date only !
It seems that the locale change is not listened by the DatePicker Component

**Comment by listatt** [comment]
Same issue

**Comment by Dean177** [comment]
A bit of a hack, but this is a quick fix:
```
<DatePicker
  inline={true}
  key={locale}
  locale={locale}
/>
```

**Comment by Sonamkhurana** [comment]
Has anyone resolved this issue?
