### ISSUE TITLE
Text and datepicker are very small

### ISSUE THREAD

**Issue by hoodsy** [Hacker0x01/react-datepicker#1210]
With no custom styling, the datepicker and all of it's text are extremely small, and essentially impossible to read.

![screen shot 2018-01-14 at 12 14 19 pm](https://user-images.githubusercontent.com/4467642/34918676-78425fca-f924-11e7-91fa-d42052fd8294.png)

**Comment by Gazler** [comment]
This is because react-datepicker uses `rem` for sizing and bootstrap sets the font-size of `html` to `10px`.

A quick fix is:

```css
html {
  font-size: 14px;
}
```

**Comment by yanniser** [comment]
well done @Gazler

**Comment by yanniser** [comment]
@hoodsy I think you should close this issue
