### ISSUE TITLE
Flickering issue when focusing on input at the top of the docs site

### ISSUE THREAD

**Issue by jennyscript-ridecell** [Hacker0x01/react-datepicker#1212]
### Expected behavior
Component becomes focused and accepts input

### Actual behavior
Screen flickers and scroll position changes rapidly. See video.

![datepicker-bug](https://user-images.githubusercontent.com/22223032/35011991-fe5e445e-fabc-11e7-8000-dbff8f7812c3.gif)

### Steps to reproduce
Load demo page https://reactdatepicker.com/ in Chrome (Tested on OSX Chrome 63.0.3239.132)
Before scrolling or clicking anywhere, click inside the input at the top of the page

Issue also exists on Safari

**Comment by renanlecaro** [comment]
Also happens on firefox on the demo site

**Comment by Hultner** [comment]
My team experience the same problem, I also found another issue about the same problem #1334 

I experienced it in all browsers I had available when testing.

**Comment by kyptin** [comment]
Has the fix been deployed to the https://reactdatepicker.com/ site yet? Because I'm still seeing the behavior in both Chrome and Firefox (but only if my devtools are closed).
