### ISSUE TITLE
react-datepicker__day--in-selecting-range not set on on disabled days in range

### ISSUE THREAD

**Issue by PeterKottas** [Hacker0x01/react-datepicker#1218]
### Expected behavior
Class 'react-datepicker__day--in-selecting-range' should be set on disabled days when doing a range selection.

### Actual behavior
It doesn't.

### Steps to reprodcue
Create 2 inputs in range, disable one date. It's not setting the class while selecting but the disabled day ends up with react-datepicker__day--in-range after you create range that contains it. 

I am not sure which one is preferable, but it should at least be consistent. 
For me it makes sense to add 'react-datepicker__day--in-selecting-range', it's basically just skipping that step because check for disable is higher in if hierarchy (I assume).

**Comment by bartzy** [comment]
@PeterKottas Did you find a solution for this?

**Comment by bartzy** [comment]
Fixed in https://github.com/Hacker0x01/react-datepicker/pull/3331
