### ISSUE TITLE
Can i force open calendar dropdown on clicking external button?

### ISSUE THREAD

**Issue by sambitroy** [Hacker0x01/react-datepicker#1223]
I need to open/close calendar dropdown on click of an external button. I am maintaining a local state flag "startOpenFlag" which is false by default. And in my <DatePicker> options i have startOpen={this.state.startOpenFlag}
On click of myButton i am setting this flag to true. But, calendar dropdown doesn't seem to open. 

Any help appreciated.

**Comment by maksimdegtyarev** [comment]
You can use `setOpen(bool)` method. Just set `ref` property to DatePicker component and call `setOpen`, for example:
```
toggle = () => {
    this.component.setOpen(this.focus);
    this.focus = !this.focus;
}
...
<DatePicker
  ref={(r) => {
    this.component = r;
  }}
  autoFocus
  selected={this.state.startDate}
  onChange={this.handleChange}
/>
<button type="button" onClick={() => this.toggle()}>toggle</button>
```

**Comment by sambitroy** [comment]
I added a custom input.
 customInput={<CustomInput inputProps={inputProps}/>}

class CustomInput extends React.Component {
	render () {
		return (
			<div onClick={this.props.onClick} className="tile-input-icon">
				<input type="text" value={this.props.value} name="inputName" placeholder="Select date" onChange={() => {return false;}} {...this.props.inputProps}/>
			</div>
		)
	}
}

This works like a charm! Thanks for your help though. :) Closing this issue.

**Comment by yasinsd2020** [comment]
i got simple solution ....default props of react datepcicker ...which is open props...using this u can  easly toggle ur calender ....

i created one useState  const [open ,setOpen]=useState(false);

const toggle =()=>{
setOpen(!open))

}

use this function in button 
  <button onClick={()=>toggle()}>click</button>

and in date picker we have to pass open props
  <DatePicker
                                open={copen}>
</DatePicker>
