### ISSUE TITLE
Datepicker component return undefined

### ISSUE THREAD

**Issue by bobysf12** [Hacker0x01/react-datepicker#1224]
### Expected behavior
Component rendered
### Actual behavior
`React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by nWidart** [comment]
any updates on this issue?

**Comment by bobysf12** [comment]
@nWidart I forgot what was the problem, but its blocking me. So I decided to use https://github.com/YouCanBookMe/react-datetime instead.
