### ISSUE TITLE
IE11 year dropdown is merged with the arrow down which is next to it

### ISSUE THREAD

**Issue by stasyaner** [Hacker0x01/react-datepicker#1226]
### Expected behavior
![datepicker1](https://user-images.githubusercontent.com/9165512/35336553-b8ce88cc-0110-11e8-85c1-092ce0be6c7c.PNG)

### Actual behavior
![datepicker2](https://user-images.githubusercontent.com/9165512/35336562-c02e555c-0110-11e8-922b-ad44cd3fa920.PNG)

### Steps to reprodcue
Init DatePicker and launch in IE11.
`<DatePicker  showYearDropdown  />`

**Comment by Sensetive64** [comment]
Have the same issue.

**Comment by kylethornton** [comment]
@stasyaner @Sensetive64 I was able to fix this by setting the following css

```
.react-datepicker__month-read-view--down-arrow,
.react-datepicker__month-year-read-view--down-arrow,
.react-datepicker__year-read-view--down-arrow {
  margin-left: -20px;
  left: 20px;
  top: 6px;
}
```

This works for IE11, chrome, safari (and mobile safari) now. IE doesn't seem to respect the margin-left but does respect left. so I set `left: 20px`, which looks right in IE but way too far right in Chrome so setting `margin-left: -20px` offsets that for all other browsers

**Comment by ashvinramana** [comment]
```
.react-datepicker__month-read-view--down-arrow,
.react-datepicker__month-year-read-view--down-arrow,
.react-datepicker__year-read-view--down-arrow {
	left: 20px;
	top: 6px;
}
.react-datepicker__month-dropdown-container span{
	margin-left: 20px;
}
```
Add this css in only Internet Explorer css file or Internet Explorer media query.
```
.react-datepicker__month-dropdown-container span{
	margin-left: 20px;
}
```
It will add margin between month and year.
Try this it work's for me.

**Comment by vijinpaulraj** [comment]
This is still an issue in IE.

![image](https://user-images.githubusercontent.com/14046103/124150370-6bddba00-da89-11eb-9a4a-667af94b2290.png)

**Comment by stasyaner** [comment]
> This is still an issue on IE.
> 
> ![image](https://user-images.githubusercontent.com/14046103/124150370-6bddba00-da89-11eb-9a4a-667af94b2290.png)

Realistically, IE is dead for everyone already.

**Comment by xmakina** [comment]
I'm also seeing this in Chrome after upgrading from 3.* to 4.*

![image](https://user-images.githubusercontent.com/1357791/146905958-c3308d56-667f-4658-a507-10f90e4af9a1.png)
