### ISSUE TITLE
Unexpected token in datepicker reactjs

### ISSUE THREAD

**Issue by chandnidobariya** [Hacker0x01/react-datepicker#1227]
./node_modules/react-datepicker/dist/react-datepicker.css Module parse failed: Unexpected token (1:0) You may need an appropriate loader to handle this file type.
| .react-datepicker-popper[data-placement^="bottom"]
| .react-datepicker__triangle, .react-datepicker-popper[data-placement^="top"]
| .react-datepicker__triangle, .react-datepicker__year-read-view--down-arrow,
 @ ./datepicker.jsx 21:0-53
 @ ./main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./main.js

**Comment by rafeememon** [comment]
The first line says it all -- you need to add a CSS loader to your webpack config.

**Comment by saramorsi** [comment]
I'm having this same issue and I have a CSS loader in my webpack config. What are some other possibilities that this might occur?
