### ISSUE TITLE
Not displaying date when this.state.date is changed

### ISSUE THREAD

**Issue by withakw** [Hacker0x01/react-datepicker#1228]
I have an application that has two datepicker fields for a start and an end of a date range. I have created a popup menu which allows the user to set some preset date range like the last 7 days last 30 days etc. This menu changes the value in the state held in the application and passed to DatePicker
### Expected behavior
After using DatePicker to type in a new date and then using the menu to change the state for the date used by DatePicker the new value should be displayed by DatePicker
### Actual behavior
The changed state date is not displayed. 
### Steps to reprodcue
Use the Component below. When it has started click in the date field and change the year to 12. Then click the button labelled "Set Date". The date displayed does not change but the display of this.state.date will show that it is set to 2018-01-01

import React from 'react'
import moment from 'moment'
import DatePicker from 'react-datepicker'
import 'react-datepicker/dist/react-datepicker.css'

export default class Test extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      date: moment("2018-01-25")
    }
    this.handleChange = this.handleChange.bind(this)
    this.setDate = this.setDate.bind(this)
  }

  handleChange(date) {
    // const formattedDate = moment(date).format('YYYY-MM-DD')
    this.setState({date: date})
  }

  setDate() {
    this.setState({date: moment("2018-01-01")})
  }

  render() {
    console.log(this.state)
    return (
      <div>
        <div>
          <label className="spark-input__field">
            <span className="spark-label spark-eta">{this.props.label}</span>
            <DatePicker
              dateFormat="DDMMMYY"
              selected={this.state.date}
              onChange={this.handleChange}
              showYearDropdown
              showMonthDropdown
            />
          </label>
        </div>
        <div>
          <button onClick={this.setDate}>
            Set Date
          </button>
        </div>
      </div>
    )
  }
}

**Comment by bhldev** [comment]
Hello,

You need to surround your JSX in ```code block markup``` so it will show up and not be escaped in the browser

That said there are several values to set like ```selected```, ```value```, ```format``` and so on, try different combinations until it works for you... one combination that works particularly well is ```selected``` with a customInput input box's value if you want to manage state on your own

~B

**Comment by HoiDam** [comment]
sad
