### ISSUE TITLE
Solved: Time picker not showing

### ISSUE THREAD

**Issue by dananw** [Hacker0x01/react-datepicker#1232]
### 1. check your module version
 your module react-datepicker version must be v.0.55.0, because time picker available on v.0.55.0 to the top, you can check it on package.json in your project

![image](https://user-images.githubusercontent.com/31610272/35435199-5a11cbd4-02bc-11e8-8bd3-ad3293a2a7d7.png)

*for upgrade you can type `npm install react-datepicker@1.0.4`

### 2. time picker display broken
![image](https://user-images.githubusercontent.com/31610272/35435393-236470ea-02bd-11e8-8edc-c9ef3d82b7c3.png)

*add this css to fix it
```
.react-datepicker__time-container .react-datepicker__time .react-datepicker__time-box ul.react-datepicker__time-list {
  padding-left: 0 !important;
  padding-right: 0 !important;
}
```

**Comment by rodriturnes** [comment]
Hi,

I tested both v0.55.0 and v.1.0.4 and I the time panel DOES NOT get rendered! It opens the usual calendar but the time component is not visible (not even on the elements).

Does someone addresses the same issue?

Thanks!

**Comment by rodriturnes** [comment]
I only get the "react-datepicker__month-container" rendered, but the "react-datepicker__time-container" does not.

Help, please!

**Comment by dananw** [comment]
can you check the elements on the calendar? like the picture below?

![image](https://user-images.githubusercontent.com/31610272/35606539-5a22f8c2-0682-11e8-9038-67e41c743724.png)

**Comment by dananw** [comment]
- have you restarted npm?

in package.json what version are you using for react-datepicker?
