### ISSUE TITLE
Visually broken calendars after upgrade

### ISSUE THREAD

**Issue by mir3z** [Hacker0x01/react-datepicker#1236]
After upgrading to the latest version all my calendars are broken. It turned out its due to changing `tether.io` to `popper.js`. It seems this is somehow related to the fact that popper puts calendar "inline", whereas tethers adds it to the body. Any advice on how to overcome this?

Calendar is inside scrollable absolute-positioned element. The calendar renders itself vertically (it shows 3 months) instead of horizontally and it looks like it can't flow outside scrollable panel.

**Comment by ManvendraSK** [comment]
Is there any progress on this part? I tried to use `popperContainer` prop, but don't know how to use it. all it says is to provide a function that returns, I think a React element. This is the code that does this https://github.com/Hacker0x01/react-datepicker/blob/9ddc73fb889f30cf4c7301ff95487ab5c16299c0/src/popper_component.jsx#L73

**Comment by msmfsd** [comment]
bump
