### ISSUE TITLE
Solved : the display is broken when inside bootstrap modal withPortal

### ISSUE THREAD

**Issue by dananw** [Hacker0x01/react-datepicker#1238]
### Solved : the display is broken when inside bootstrap modal withPortal
![image](https://user-images.githubusercontent.com/31610272/35512512-948a5fc4-0532-11e8-852f-5e38d6f7a00b.png)

* yellow box is modal
* Red box is datepicker

added this css to make it a center inside modal
`.react-datepicker__portal {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  width: 100% !important;
  height: auto !important;
  background: rgba(128, 128, 128, 0.7) !important;
}`

and results like this
![image](https://user-images.githubusercontent.com/31610272/35513168-c049f758-0534-11e8-9a19-cdc3a9bd4c16.png)

**Comment by ArtemBernatskyy** [comment]
@dananw Can you update title of the issue with something like this `Solved : the display is broken when inside bootstrap modal withPortal` .

It will help to find it easier. Thx.

**Comment by dananw** [comment]
@ArtemBernatskyy Thx for correction.
