### ISSUE TITLE
Uncontrolled Usage

### ISSUE THREAD

**Issue by jbrumwell** [Hacker0x01/react-datepicker#124]
What are your thoughts on allowing the datepicker to be used as an uncontrolled element, https://facebook.github.io/react/docs/forms.html#uncontrolled-components?

Would allow you to;

```
var moment = this.refs.datepicker.getValue();
```

Instead of listening on the event for changes.

**Comment by RSO** [comment]
Hmm, interesting approach. I guess I initially made it a controlled input to allow for masking/styling of the input while typing (`--/--/----`), but haven't gotten to implementing that yet. What's the reason for you to make the datepicker uncontrolled?

**Comment by jbrumwell** [comment]
This will just give it an option to be used in both controlled and uncontrolled. Our main requirement was to be able to get the value out of the datepicker and there was no link to the date input.

**Comment by RSO** [comment]
Thanks! I've merged the PR to master, will perform a release later today.

**Comment by jbrumwell** [comment]
Thanks Remon for your great component :+1:
