### ISSUE TITLE
Must create dist folder before running npm scripts

### ISSUE THREAD

**Issue by ksmith97** [Hacker0x01/react-datepicker#1242]
### Expected behavior
I should be able to run ```npm run css:prod``` from a fresh clone without errors.

### Actual behavior
The system cannot find the path specified.

### Steps to reprodcue
1. Clone repo into fresh location.
2. run ```npm run css:prod```

This is minor but annoying. I misinterpreted the error message to mean that something was wrong with my installation instead of that the script has a prerequisite of the dist folder existing.

**Comment by qpzm** [comment]
Did you run `npm install`(or `yarn install`) beforehand to install dependency?
