### ISSUE TITLE
I want to change the position of the calendar

### ISSUE THREAD

**Issue by m-morisaki** [Hacker0x01/react-datepicker#1246]
The calendar is hidden on the smartphone.
Can you adjust the position?

<img width="289" alt="2018-01-31 10 56 41" src="https://user-images.githubusercontent.com/32150594/35601269-7acaad8e-0675-11e8-82cd-12d302b61946.png">

**Comment by postal286** [comment]
Have the same issue. Want to move it left depends on input position. Someone know how to do that ?)

**Comment by m-morisaki** [comment]
I'm so grateful for that!

**Comment by benjaminkniaz** [comment]
Unfortunately, placement does not work for me, nor does it work in the official examples. I would expect placement to force the popper to appear on the bottom, etc.

**Comment by robhadfield** [comment]
Yep - as @benjaminkniaz says it doesn't `force` the position. if I say top-start I would expect to force that position even if it's near the screen edge.

**Comment by benjaminkniaz** [comment]
@robhadfield turns out you have to add a modifier to force the position. `flip` forces it not to flip even if the popper is going to be partially off-screen, and `preventOverflow` prevents it from covering the element you clicked, if again the popper detects the item will partially go off screen.

This is where I found the modifiers:
https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#modifiers..flip

```
<DatePicker
    selected={props.followup_complete_by_dt}
    onChange={props.handleDueDateChange}
    className="form-control"
    monthsShown={1}
    popperPlacement="bottom"
    popperModifiers={{
        flip: {
            behavior: ["bottom"] // don't allow it to flip to be above
        },
        preventOverflow: {
            enabled: false // tell it not to try to stay within the view (this prevents the popper from covering the element you clicked)
        },
        hide: {
            enabled: false // turn off since needs preventOverflow to be enabled
        }
    }}
/>
```

**Comment by robhadfield** [comment]
Thanks a lot @benjaminkniaz , I'll give that a go. I ended up reverting to a dialog which really ruins the flow.

**Comment by ryanlozon** [comment]
I'm still running into an issue where the popup appears off to the left. Any idea why it might be doing? 
![image](https://user-images.githubusercontent.com/31925763/47006878-38bb3700-d137-11e8-8488-ea44142081a3.png)
![image](https://user-images.githubusercontent.com/31925763/47006900-496bad00-d137-11e8-8833-bb7bc72c0259.png)

**Comment by robhadfield** [comment]
Here's the settings that work for me:

```
            <Picker
                showMonthDropdown
                showYearDropdown
                dropdownMode="select"
                dateFormat={ dateFormat }
                minDate={ isDate(minDate) ? moment(minDate) : null }
                maxDate={ isDate(maxDate) ? moment(maxDate) : null }
                placeholderText={ placeholder }
                selected={ date && isDate(date) ? moment(date) : initialDate }
                onChange={ onChange }
                disabled={ disabled }
                withPortal={ withPortal ? true : false }
                popperPlacement='bottom'
                popperModifiers={{
                    flip: {
                        behavior: ['bottom'] // don't allow it to flip to be above
                    },
                    preventOverflow: {
                        enabled: false // tell it not to try to stay within the view (this prevents the popper from covering the element you clicked)
                    },
                    hide: {
                        enabled: false // turn off since needs preventOverflow to be enabled
                    }
                }}
            />
```

**Comment by jacky-ew** [comment]
<img width="475" alt="Screenshot 2020-04-23 at 17 09 07" src="https://user-images.githubusercontent.com/56298610/80081154-24a29200-8585-11ea-9e8b-c24673262b35.png">
Hi any possible solution to this issue?
the datepicker is overlapped with the dates on calendar

**Comment by robhadfield** [comment]
@jacky-ew Looks like a z-index issue between the picker and Calendar, try dropping your calendar down to `z-index:1` ?

**Comment by jacky-ew** [comment]
Hi i think its better to set datepicker popper to have `z-index: 1`, but cannot find props in the lib

**Comment by jacky-ew** [comment]
managed to solved it by adding z-index in div container instead, thank you @robhadfield

**Comment by robhadfield** [comment]
Difficult to advise without seeing the live code but glad you got it working 👍

**Comment by rrankawat** [comment]
> Have the same issue. Want to move it left depends on input position. Someone know how to do that ?).
> 
> This params will help you: **'auto', 'auto-left', 'auto-right', 'bottom', 'bottom-end', 'bottom-start', 'left', 'left-end', 'left-start', 'right', 'right-end', 'right-start', 'top', 'top-end', 'top-start'**
> 
> Found params in src. You need to pass one of this values to **popperPlacement** props to the DatePicker component like that - `<DatePicker popperPlacement="bottom-end" />`.
> 
> Someone who knows how to contact with develop team tell them to update popperPlacement docs. It's not so clear to find this values. Thx.
Awesome Man!!!

**Comment by savtwo** [comment]
> Have the same issue. Want to move it left depends on input position. Someone know how to do that ?).
> 
> This params will help you: **'auto', 'auto-left', 'auto-right', 'bottom', 'bottom-end', 'bottom-start', 'left', 'left-end', 'left-start', 'right', 'right-end', 'right-start', 'top', 'top-end', 'top-start'**
> 
> Found params in src. You need to pass one of this values to **popperPlacement** props to the DatePicker component like that - `<DatePicker popperPlacement="bottom-end" />`.
> 
> Someone who knows how to contact with develop team tell them to update popperPlacement docs. It's not so clear to find this values. Thx.

Wanted to add a little more detail to this. The `react-datepicker` library uses `react-popper` found here: https://github.com/Hacker0x01/react-datepicker/blob/1605d79c175d5448d2e1ce63e71fc1202bc50a04/src/popper_component.jsx#L4

`react-popper` is the wrapper for the popper library and the docs for the options are found here: https://popper.js.org/docs/v2/constructors/#options.

**Comment by infinitbility** [comment]
Added examples to show datepicker at down side 

https://infinitbility.com/how-to-show-bottom-in-react-datepicker

**Comment by yannickNzali** [comment]
it works form me. The DatePicker's calendar is shown on top and is prevented to be shown bottom. I used the following code added to the <DatePicker> :
popperPlacement="top"
                                                                        popperModifiers={{
                                                                            flip: {
                                                                                behavior: ["bottom"] // don't allow it to flip to be above
                                                                            },
                                                                            preventOverflow: {
                                                                                enabled: false // tell it not to try to stay within the view (this prevents the popper from covering the element you clicked)
                                                                            },
                                                                            hide: {
                                                                                enabled: false // turn off since needs preventOverflow to be enabled
                                                                            }
                                                                        }}

**Comment by krystallopez** [comment]
> @robhadfield turns out you have to add a modifier to force the position. `flip` forces it not to flip even if the popper is going to be partially off-screen, and `preventOverflow` prevents it from covering the element you clicked, if again the popper detects the item will partially go off screen.
> 
> This is where I found the modifiers: https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#modifiers..flip
> 
> ```
> <DatePicker
>     selected={props.followup_complete_by_dt}
>     onChange={props.handleDueDateChange}
>     className="form-control"
>     monthsShown={1}
>     popperPlacement="bottom"
>     popperModifiers={{
>         flip: {
>             behavior: ["bottom"] // don't allow it to flip to be above
>         },
>         preventOverflow: {
>             enabled: false // tell it not to try to stay within the view (this prevents the popper from covering the element you clicked)
>         },
>         hide: {
>             enabled: false // turn off since needs preventOverflow to be enabled
>         }
>     }}
> />
> ```

I am also running into an issue with changing the position of the datepicker, however,  I tried this method as well and nothing changed. is there another dependency that needs to be installed into my application in order for the popper props to work?

**Comment by Linuhusainnk** [comment]
Any update on this issue? to force and show Date picker on bottom
