### ISSUE TITLE
Only Month/Year Picker

### ISSUE THREAD

**Issue by nmaves** [Hacker0x01/react-datepicker#1249]
Is there any implementation of this as just a month/year picker?  Our use case is to allow the user to select Jan 2018 - Jun 2018 without dates.

**Comment by xnog** [comment]
+1

**Comment by robinwkurtz** [comment]
Also interested in this!
Thanks for a great tool

**Comment by crorodriguezro** [comment]
I need this aswell.  I could work on this if it doesn't exist already.

**Comment by theinvensi** [comment]
+1 me too... wanted this feature

**Comment by LeoSolo** [comment]
+++++

**Comment by vctormb** [comment]
Any updates about this feature? I'm really interested too!

**Comment by ghenrique** [comment]
Hi! I'm really interested in this feature too. I need this in the project I'm working on and I'm having to search for another tool to cover this functionality.

**Comment by jeanfs** [comment]
Amazing idea, this would be really helpful! =)

**Comment by uxuioptum** [comment]
Hi! I'm really interested in this feature too.

**Comment by PauloRibeiro** [comment]
I'm interested in this feature too

**Comment by sensone** [comment]
me too

**Comment by 3mp3ri0r** [comment]
I need this feature

**Comment by CDimonaco** [comment]
I'm interested in this feature too :)

**Comment by gregorianisch** [comment]
Interested too :)

**Comment by dogrultan** [comment]
+1

**Comment by nomanalikhan** [comment]
+1

**Comment by ArthurSN57** [comment]
+1

**Comment by cleberpereiradasilva** [comment]
+1

**Comment by mobicity** [comment]
+1

**Comment by mobicity** [comment]
+1 @martijnrusschen @RSO

**Comment by SaifAsad** [comment]
Is there any updates on this ? this would be a really useful feature, it would also be awesome to be able to select 'year' only view, keen to help on this if required,

**Comment by almond-bongbong** [comment]
+1

**Comment by gautam-relayr** [comment]
Hello guys, I looked at this thread and it seems that there is a massive need of a month/year picker variation. So, I have started to work on something like this:

<img width="211" alt="Screen Shot 2019-03-15 at 1 22 21 PM" src="https://user-images.githubusercontent.com/32642691/54433851-24528900-472d-11e9-85a6-8ebf49cdaf76.png">

This is the 1st step towards month/year picker variation. I am planning to later extend it to Range month/year picker which is also needed. I have few ideas for the use cases but would like to hear from everyone else as well. It will help me to handle such use cases while I code for this.

Hoping for a positive response.

Cheers!!

**Comment by martijnrusschen** [comment]
Sounds like a great improvement! I could actually use this.

**Comment by htmlboss** [comment]
@gautam-relayr That's awesome news! I actually need the Range month/year so I'm looking forward to tracking your progress 😄

**Comment by goingpaper** [comment]
How about a purely year picker?

**Comment by fazzaMmsApis** [comment]
is there purely year picker in datePicker? or how to show year dropDown in monthYear Picker?

**Comment by cdpautsch** [comment]
> is there purely year picker in datePicker? or how to show year dropDown in monthYear Picker?

This could be useful to me as well. A dropdown is obviously one alternative, but I'm on a project now where they are looking for a year picker like this.

**Comment by philmetzger** [comment]
Also looking for this :)

**Comment by 1gory** [comment]
<DatePicker
    dateFormat="MM.yyyy"
    showMonthYearPicker
/>

**Comment by Ali-Ghali** [comment]
I would like to know if this feature was implemented already or not :), I need it

**Comment by andreareginato** [comment]
It seems it has been implemented.
Here a working example in the official documentation.

https://reactdatepicker.com/#example-month-picker

**Comment by goingpaper** [comment]
> It seems it has been implemented.
> Here a working example in the official documentation.
> 
> https://reactdatepicker.com/#example-month-picker

Purely year picker... not monthyear picker. All I would like is a drop down with a list of years to pick from. With that solution you can only increment/decrement the year, it's not feasible when you only want to pick the year.

**Comment by antoanelenkov** [comment]
+1 for year picker

**Comment by Cmion** [comment]
+1 for year picker

**Comment by jpcmf** [comment]
+1 for year picker

**Comment by muhfs94** [comment]
thanks for the month picker. now I'm also waiting for year picker +1

**Comment by eugenesaur** [comment]
+1 for year picker
and +1 for showYearDropdown in month picker as well

**Comment by alekseykarpenko** [comment]
+1

**Comment by senthiece42** [comment]
how to do mon-year calendar, show year dropdown?

**Comment by gautam-pahuja** [comment]
Hello guys, I hope everyone is doing well.

I see there is a massive demand of only pure year picker. I am building something like that, it looks like this:

![27bbb2868c36e497799fe917db28d2e8](https://user-images.githubusercontent.com/32642691/80979869-2e02e880-8e28-11ea-92c4-d3e8c24e6450.gif)

This is the 1st step towards year picker variation. I am planning to later extend it to click on the year in the header on a normal date picker which opens up this which I see is also highly required by the community. That might look something like this:

![date picker](https://user-images.githubusercontent.com/32642691/80980034-6e626680-8e28-11ea-96dc-f9ee333ec828.gif)

I have few ideas for the use cases but would like to hear from everyone else as well. It will help me to handle such use cases while I code for this.

Hoping for a positive response.

Cheers!!

**Comment by martijnrusschen** [comment]
Added a yearpicker thanks to #2130

**Comment by gautam-pahuja** [comment]
@martijnrusschen this issue can be closed too.

**Comment by denny7** [comment]
> Hello guys, I hope everyone is doing well.
> 
> I see there is a massive demand of only pure year picker. I am building something like that, it looks like this:
> 
> ![c2569d3411c7f727cb31b5337396cbb5](https://user-images.githubusercontent.com/32642691/80983162-8cca6100-8e2c-11ea-8350-210d915d5a69.gif)
> 
> This is the 1st step towards year picker variation. I am planning to later extend it to click on the year in the header on a normal date picker which opens up this which I see is also highly required by the community. That might look something like this:
> 
> ![date picker](https://user-images.githubusercontent.com/32642691/80980034-6e626680-8e28-11ea-96dc-f9ee333ec828.gif)
> 
> I have few ideas for the use cases but would like to hear from everyone else as well. It will help me to handle such use cases while I code for this.
> 
> Hoping for a positive response.
> 
> Cheers!!

This is exactly what I'm looking for. It will be very useful.

**Comment by nikitamundra** [comment]
Hey, This is exactly what I am searching for.
 I have one issue in this feature which is when I select year, That particular year comes at last position. i.e if I select year 2052 , then it changes the interval range also and 2052 becomes the last year in the visible year modal.  

Is there any solution so that the selected year does not comes at the last position ?
I am using latest version - 3.1.3

Here is screenshot for ref.
https://user-images.githubusercontent.com/49276226/90622781-3c3c0f80-e233-11ea-869e-52593629d704.png

**Comment by karthic-kailanware** [comment]
Waiting for this feature. still month and year together not working
