### ISSUE TITLE
date picker dont chage with change locale

### ISSUE THREAD

**Issue by zgolmohamadi** [Hacker0x01/react-datepicker#1250]
![capture](https://user-images.githubusercontent.com/35527928/35718809-689d2ab0-07fb-11e8-9a34-486c87fd5771.PNG)
hello
i set locale prop in datePicker and import 'moment/locale/fa' , but just font change to persian , and datepicker load en .

**it is my code:**
import React from 'react';
import moment from 'moment';
import 'moment/locale/fa';

import DatePicker from 'react-datepicker'; 
import 'react-datepicker/dist/react-datepicker.css';
 
export default class Calendar extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      startDate: moment()
    };
    this.handleChange = this.handleChange.bind(this);
  }
 
  handleChange(date) {
    this.setState({
      startDate: date
    });
  }
  render() {
      moment.updateLocale('fa',null)
    return <DatePicker
    inline
        selected={this.state.startDate}
        locale="fa"
        onChange={this.handleChange}
    />;
  }
}

**Thank you if you answer**

**Comment by bhldev** [comment]
Hello,

I got around this by passing in a "selected" value even if it is a custom moment, then using a custom input with a value of blank to show nothing

Create localized moment like this

```
moment().locale('fa')
```

~B
