### ISSUE TITLE
Always visible react-datepicker__day--in-selecting-range

### ISSUE THREAD

**Issue by vlafiser** [Hacker0x01/react-datepicker#1251]
Hello,

please is possible to have still visible `.react-datepicker__day--in-selecting-range` days instead of on hover only?

Thank you for help.

**Comment by mattgrannary** [comment]
I'm also dealing with this issue. The examples show all the days within the range as selected (dark blue) where as in my implementation the days in range are only highlighted (light blue) on hover. I'd like to always show the selected state for days within the range.
