### ISSUE TITLE
Z-index problem

### ISSUE THREAD

**Issue by dananw** [Hacker0x01/react-datepicker#1252]
### how to set z-index? 
![image](https://user-images.githubusercontent.com/31610272/35734838-0b7d17b4-0855-11e8-8963-03d8da057269.png)

**Comment by gothbarbie** [comment]
Add your own styling: 

```
.react-datepicker-popper {
  z-index: 3;
}
```

**Comment by MonkeyJumps** [comment]
This is not working for me. I have the following component configuration:

`           <DatePicker value={this.props.value} onChange={this.handleChange} //onChangeRaw={this.handleChangeRaw}
                        popperClassName="calendar-popout"
                        popperPlacement="top-end"
                        popperModifiers={{
                            offset: {
                                enabled: true,
                                offset: '5px, 10px'
                            },
                            preventOverflow: {
                                enabled: true,
                                escapeWithReference: false, // force popper to stay in viewport (even when input is scrolled out of view)
                                boundariesElement: 'viewport'
                            }
                        }}
                        isClearable={true}
                        customInput={<button type="button" className="btn btn-default" onClick={this.props.onClick}>
                            <img src='/Content/images/calendar.png' title='Run Lookup' />
                        </button>} />`



![image](https://user-images.githubusercontent.com/812636/36505980-152eb5f6-170a-11e8-8817-6e28dc98ae69.png)


I set the z-index as suggest above and every other i can think of but the popout still renders under other components.

**Comment by combizs** [comment]
Your style needs to be added in a stylesheet.

Also, it would help if you paste the code in a readable format, at least without comments if it's one-line.

**style.css**
```css
.react-datepicker-popper {
  z-index: 3;
}
```


**file.js**
```js
import React from 'react';
import DatePicker from 'react-datepicker';
import style.css

...

<DatePicker
  value={this.props.value}
  onChange={this.handleChange}
  popperClassName="calendar-popout"
  popperPlacement="top-end"
  popperModifiers={{
    offset: { enabled: true, offset: '5px, 10px' },
    preventOverflow: {
      enabled: true,
      escapeWithReference: false,
      boundariesElement: 'viewport'
    }
  }}
  isClearable={true}
  customInput={
    <button
      type="button"
      className="btn btn-default"
      onClick={this.props.onClick}>
      {' '}
      <img src="/Content/images/calendar.png" title="Run Lookup" />{' '}
    </button>
  }
/>

...

```

**Comment by andycamp** [comment]
I had this issue, and had to add !important to my style to get it to override the default z-index of 1
`.react-datepicker-popper { 
    z-index: 100 !important
}`

**Comment by prokhorenkovatv** [comment]
maybe it will help someone like me in future, but you can simply pass your own styles with exact z-index into **popperClassName** prop on DayPicker

**Comment by arfanroky-github** [comment]
it's not working in my case

**Comment by SirawichDev** [comment]
if z-index solution not working i suggest you to use ``` portalId ``` props instead
date-picker component just put      ```  portalId="what-ever-id" ```
and your problem will be fixed

**Comment by davidseek** [comment]
> ```js
> popperClassName="calendar-popout"
> ```

Only this worked for me

**Comment by davidseek** [comment]
> if z-index solution not working i suggest you to use `portalId` props instead date-picker component just put ` portalId="what-ever-id"` and your problem will be fixed

Only this worked for me:

```js
<DatePicker
      portalId="my-popper"
      ...
    />

# In index.html

<style>
#my-popper {
     z-index: 100 !important;
}
</style>
```

**Comment by SirawichDev** [comment]
nice <3 <3

**Comment by sanghmitras** [comment]
If nothing works, try this
<DatePicker 
...
popperModifiers={[
                  {
                    name: "zIndex",
                    enabled: true,
                    phase: "write",
                    fn: ({ state }) => {
                      if (state.styles.popper) {
                        state.styles.popper.zIndex = "2";
                      }
                    },
                  },
                ]}

/>

**Comment by anuraginvz** [comment]
in next js `global.css` it worked, 

```css
.react-datepicker-popper {
  z-index: 999 !important;
}
```
