### ISSUE TITLE
Need to change day name from [su mo tu we th fr sa] to [s m t w t f]

### ISSUE THREAD

**Issue by arulmozhimanikandan** [Hacker0x01/react-datepicker#1257]
### Expected behaviour
Expected date name : 
[s m t w t f]
### Actual behaviour
Actual date name:
[su mo tu we th fr sa]

I am unable to find API or attribute to change the date name formate.

Could you please help me the API or attribute reference?

Thank you very much.

**Comment by karlkras** [comment]
Wow, I just asked the same question, and this has been sitting here for 8 months? Well that's discouraging.

**Comment by arulmozhimanikandan** [comment]
Yes, it is been 8 months and I got released from project

**Comment by jinkyaw** [comment]
You can do that from css as :psuedo element as :first-letter

**Comment by hyana** [comment]
#2398 has a good solution for those who wonder
