### ISSUE TITLE
Allow editing the time directly from input field

### ISSUE THREAD

**Issue by alexandrubeu** [Hacker0x01/react-datepicker#1260]
### Expected behavior
Scenario: 
   I need a datetimepicker which have a 15 min time interval. I can select the time directly from UI interface and most of the time it's enough but sometimes I need to select a specific time (ex: 15:07). What I would like is to be able to change the time directly from input field. 
As a workaround I can set the `timeIntervals =  {1}` but then it's very annoying because you need to scroll down in UI in order to select a specifc time. 

### Actual behavior
Currently, if I try to modify the time directly from input field, the time will not be updated in the onChange handler. 

### Steps to reprodcue
```
 <DatePicker className='form-control'
                                    dateFormat='YYYY-MM-DD HH:mm'
                                    selected={window.start_date}
                                    disabledKeyboardNavigation
                                    onChange={(date) => this.dateChanged('start_date', date)}
                                    showTimeSelect
                                    timeFormat='HH:mm'
                                    timeIntervals={15}
```

1. Try to edit the time directly from input field

**Comment by tcollins** [comment]
Did you ever find a work around for this?  I'm thinking maybe onBlur can be used to update the date-time from the input, but I haven't tried it yet.

**Comment by tomtwttr** [comment]
I submitted this PR https://github.com/Hacker0x01/react-datepicker/pull/1289

**Comment by aij** [comment]
#1289 has been merged. Thanks @tomtwttr .

Protip for next time: If you write something like `Fixes #issuenumber` in your commit/PR, the corresponding issue will be closed when the fix gets merged.

**Comment by martijnrusschen** [comment]
Closing per #1289
