### ISSUE TITLE
Bundle size, moment library

### ISSUE THREAD

**Issue by kkseven07** [Hacker0x01/react-datepicker#1261]
This library uses 'moment' which is half of my bundle size. What can I do? Im new to react and know little about dependencies.

**Comment by star-collector** [comment]
If you use webpack to create your bundle, you can remove unused moment.js locales using context replacement plugin. This will decrease moment.js size by ~300KB.

Add something like this to your **_plugins_** option in **_webpack.config_**: 

`new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /ru/)`

**Comment by martijnrusschen** [comment]
Moment.js was removed in #1527, starting v2.0.0, this package doesn't use Moment anymore.
