### ISSUE TITLE
Support React 15 AND 16 ?

### ISSUE THREAD

**Issue by psimoneau22** [Hacker0x01/react-datepicker#1262]
In the documents it states that React 15.5 or newer is supported by tags above React-datepicker v.0.40.0 and above.  However, the peer-dependencies is set to strictly react 16+.   Installing 1.x.x gives warnings about incorrect peer-dependencies.   

Can we confirm that the datepicker supports 15 AND 16 and if so update peer dependencies to reflect that?

**Comment by aij** [comment]
Support for React 15 was dropped in #1047 .

No one is going to stop you from using React 15, but you'll be on your own since we decided not to spend resources supporting outdated versions of React.
