### ISSUE TITLE
required props usage

### ISSUE THREAD

**Issue by cumibulat** [Hacker0x01/react-datepicker#1268]
hi,

is the required props is for notifying user that he has to choose the date (mandatory) ?
I cannot get the required props works. I have clone and test it in the example code.

```
<DatePicker
  selected={this.state.startDate}
  onChange={this.handleChange}
  required={true}/>
```

If that's not the usage that intended to, is there any solution if i want to prompt a message when a user not choosing date / fill with wrong format date ?

thanks.

**Comment by aij** [comment]
The required prop will mark the input as required. See the https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input (the required attribute)

If you want to use it to prompt a message, you can use it to prompt a message, but when and how you do that is up to you. If you want to use it to apply styling, you can use it to apply styling.
