### ISSUE TITLE
how can i change the direction of the days from right to left?

### ISSUE THREAD

**Issue by avivdevalore** [Hacker0x01/react-datepicker#1271]
![image](https://user-images.githubusercontent.com/34057014/36158554-47a6b414-10e5-11e8-8cd1-5ee9f0a676e3.png)

I want to know if there is a way to make the days of the week and the date to start from the right side.
In Hebrew/Arabic you start from the right side. 
I thought the locale will fix it but it doesn't.
I've tried looking in the props but didn't see any relavent prop.

Thanks

**Comment by avivdevalore** [comment]
Thanks @sarahmarciano.
did you changed the direction to RTL?

if i add to the calendar 'direction: RTL' then it start from the right but then if i will change the locale back to English it will stay RTL and that is no good.

**Comment by sarahmarciano** [comment]
yes, indeed I've changed the direction to RTL,
what I can suggest you if you need your app to be flexible is to have two divs one with direction of rtl and one with direction of ltr and render the div depending on the locale direction
your code will look something like this: (I did not test this snippet of code but you got the idea...)

```
const rtlLocales = [
    'ae',	/* Avestan */
    'ar',   /* 'العربية', Arabic */
    'arc',  /* Aramaic */
    'bcc',  /* 'بلوچی مکرانی', Southern Balochi */
    'bqi',  /* 'بختياري', Bakthiari */
    'ckb',  /* 'Soranî / کوردی', Sorani */
    'dv',   /* Dhivehi */
    'fa',   /* 'فارسی', Persian */
    'glk',  /* 'گیلکی', Gilaki */
    'he',   /* 'עברית', Hebrew */
    'ku',   /* 'Kurdî / كوردی', Kurdish */
    'mzn',  /* 'مازِرونی', Mazanderani */
    'nqo',  /* N'Ko */
    'pnb',  /* 'پنجابی', Western Punjabi */
    'ps',   /* 'پښتو', Pashto, */
    'sd',   /* 'سنڌي', Sindhi */
    'ug',   /* 'Uyghurche / ئۇيغۇرچە', Uyghur */
    'ur',   /* 'اردو', Urdu */
    'yi'    /* 'ייִדיש', Yiddish */
];

function isLocaleRtl(locale) {
    return rtlLocales.indexOf(locale.split('-')[0]) !== -1;
}

render() {
        const { locale } = this.props;
        if (isLocaleRtl(locale)) {
            return (
                <div dir='rtl'>
                    <DatePicker
                        selected={date}
                        onChange={(date) => setEventDate(date)}
                        locale={locale}
                        minDate={moment()}
                    />
                </div>
            );
        }
        return (
            <DatePicker
                selected={date}
                onChange={(date) => setEventDate(date)}
                locale={locale}
                minDate={moment()}
            />
        );
    }


```

**Comment by efef10** [comment]
I have a problen with the keyboard arrows, when I press the left key, it acts as right. and vice versa...
does anyone got a solution?
Thanks!

**Comment by renana-kimaia** [comment]
Hi, I tried adding the <div dir='rtl'> to solve the direction of the arrows in an RTL lang. (right arrow to move to previous month, left to move to next month ) - but it didnt work.
Any suggestions...?
Thanks!

**Comment by only-mishmish** [comment]
Hi, I tried adding the <div dir='rtl'> to solve the direction of the arrows in an RTL lang. (right arrow to move to previous month, left to move to next month ) - but it didn't work.
Any suggestions...?
Thanks!

**Comment by ynonra** [comment]
it is possible with 2 simple css rules:

```
.react-datepicker__navigation--previous {
  left: unset !important;
  right: 2px;
  transform: rotateY(180deg);
}
.react-datepicker__navigation--next {
  right: unset !important;
  left: 2px;
  transform: rotateY(180deg);
}
```
