### ISSUE TITLE
Height of the datepicker popper grows on scroll and it disappears outside the screen. 

### ISSUE THREAD

**Issue by JustFly1984** [Hacker0x01/react-datepicker#1278]
I'm importing CSS modules from datepicker.
I have html `label` element wrapping react-datepicker with line-height set to 4rem
So as I understand, this line-height somehow inherited by all elements inside the datepicker popper, and the function which counts translate3d of going mad.

The only solution I found is override line-height. 
```
:global .react-datepicker-popper {
  line-height: 2rem;
}
```

If I set line-height to 2.4rem, it starts to grow again. Please fix default css and translate3d function.

Normal behavior:
<img width="582" alt="screenshot 2018-02-23 15 42 25" src="https://user-images.githubusercontent.com/2255993/36583332-390b665c-18b0-11e8-9e0e-dcec47dea323.png">

Incorrect behavior: 
<img width="659" alt="screenshot 2018-02-23 15 44 11" src="https://user-images.githubusercontent.com/2255993/36583367-6eff5ca0-18b0-11e8-824e-dcefd5f82ccd.png">

**Comment by JustFly1984** [comment]
I have no idea why but this happens only in Chrome Canary. I do not have same issue with standard chrome.

**Comment by farahamawi** [comment]
Hi Have you come up with a solution for this

**Comment by JustFly1984** [comment]
We have made our own implementation of datepicker whith typescript and accessibility support, so we could customise it for our projects.
