### ISSUE TITLE
Console report "Unable to preventDefault inside passive event listener invocation"

### ISSUE THREAD

**Issue by leomyth330** [Hacker0x01/react-datepicker#1279]
It's reported when I test on mobile with portal mode and click outside of calendar.
I tested with demo site and it has also same error.

**Comment by wramp** [comment]
Same issue here:

Getting console error on dev environment:
'Unable to preventDefault inside passive event listener invocation.'

When closing-of Portal version (clicking on black surrounding area)

<DatePicker  withPortal shouldCloseOnSelect={false}/>

Any ideas?

**Comment by Thrajnor** [comment]
Same bug here: 
![image](https://user-images.githubusercontent.com/27703720/46074663-8112b500-c188-11e8-9232-257a982bfc49.png)

any ideas ? Could someone fix it? I really like this date picker!

**Comment by porsich** [comment]
HI folks, I just add `autoFocus` flag, and it fixes bug for me

**Comment by matt-btc** [comment]
Is there a fix coming for this? Can reproduce the issue when using any of the mobile/touch device simulations in Chrome.

**Comment by SIARHEI-SMANTSAR** [comment]
This issue has been resolved for `react-onclickoutside`.
https://github.com/Pomax/react-onclickoutside#regulating-evtpreventdefault-and-evtstoppropagation

Need add `preventDefault={this.props.withPortal}` here https://github.com/Hacker0x01/react-datepicker/blob/1a3402ca4f15c0d21976b0ca5e6f886416cd2a24/src/index.jsx#L704
```
 <WrappedCalendar preventDefault={this.props.withPortal}  ... >
```

**Comment by ngozi-ekekwe-finleap** [comment]
I am still having this error on chrome

**Comment by X-Y** [comment]
Can still reproduce the problem. Why is it wontfix?

**Comment by meesta1990** [comment]
Hi, I've resolved. Check this:

https://github.com/Hacker0x01/react-datepicker/issues/2524#issuecomment-850292147
