### ISSUE TITLE
different excludetimes for specific days?

### ISSUE THREAD

**Issue by NanoMeko** [Hacker0x01/react-datepicker#1280]
Does `excludetimes` support different excluded moments depending on the day? 

For example on mondays, exclude different times than the excluded times for wednesday.

**Comment by NanoMeko** [comment]
fixed this issue by loading new exclude times specific to the day when the date is changed

**Comment by teosairus** [comment]
@NanoMeko can you share your solution?

**Comment by Jonofat** [comment]
@jamesattard, did you ever get this sorted? I am also trying to do the same thing.

**Comment by NanoMeko** [comment]
I think I found a solution that was counterintuitive but it was a long time
ago for a different employer. I’m sorry I can’t be of much help

**Comment by bogdansoare** [comment]
Check https://github.com/Hacker0x01/react-datepicker/issues/2412#issuecomment-719914433 for a solution

**Comment by akcalp** [comment]
Thank you so much for this

> Check [#2412 (comment)](https://github.com/Hacker0x01/react-datepicker/issues/2412#issuecomment-719914433) for a solution
