### ISSUE TITLE
Visible Start Date and End Date in Calendar

### ISSUE THREAD

**Issue by al3x-huang** [Hacker0x01/react-datepicker#1284]
I don't believe there is currently a way to obtain the start date and end date of the calendar right now. Since this computation is done on a new selected date, the result should be provided to the onChange handler. 

For a more concrete example, in this calendar view
<img width="224" alt="screen shot 2018-02-27 at 4 58 41 pm" src="https://user-images.githubusercontent.com/20210402/36757536-de404f34-1bdf-11e8-9af6-20ffb77d73bc.png">

January 30th and March 5th should be available to the onChange handler.

**Comment by rafeememon** [comment]
What is the use cases of needing to access January 30th and March 5th when February 27th is selectedm

**Comment by al3x-huang** [comment]
Applications might need to do an operation on each visible day. For example, if I were building a reservation system and choose to highlight days with empty reservations in green, it would be useful to have this list of visible dates so I can check availability on every day. This list of days will not change if the user selects a day within February but will change when any of the January or March days are clicked.

**Comment by rafeememon** [comment]
Why does the list of available days need to change at all?  You can pass in the entire list, not just the ones shown in the current view; if the list is large, you can trigger an API call with one of the various callbacks.

I don't think we should complicate the `onChange` API to support this.  The visible dates can be derived with a combination of moment.js functions from the selected date.

**Comment by al3x-huang** [comment]
You claim that you can pass in the entire list. How could I do this then? I couldn't find an example.
