### ISSUE TITLE
Time values CSS broken out of the box?

### ISSUE THREAD

**Issue by tomtwttr** [Hacker0x01/react-datepicker#1286]
### Expected behavior
Times to be visible

### Actual behavior
Times not visible

### Steps to reproduce

```
import 'react-datepicker/dist/react-datepicker.css';
//...
<DatePicker showTimeSelect />
```

![screen shot 2018-02-28 at 2 03 21 pm](https://user-images.githubusercontent.com/33262427/36815626-28fdf606-1c90-11e8-8073-f3f9f094a910.png)

**Comment by yangxiaoyao1983** [comment]
i meet the same issue.

**Comment by yangxiaoyao1983** [comment]
i modify it by follow:

**Comment by yangxiaoyao1983** [comment]
find the file react-datepicker.css
.react-datepicker__time-box {
  width: 120px;
  overflow-x: hidden;
  margin: 0 auto;
  text-align: center;
  margin-left: -58px;
}

**Comment by RickEyre** [comment]
+1

**Comment by christiantakle** [comment]
I use an css overwrite:
```css
.react-datepicker__time-list {
  padding: 0;
}
```

<img width="351" alt="screen shot 2018-03-21 at 12 38 44" src="https://user-images.githubusercontent.com/684866/37710255-00965408-2d05-11e8-9c64-bb5d4afe0d3d.png">

Depending on the project you may need to add more specificity to the selector.

**Comment by kaitmore** [comment]
+1 also experiencing this issue

**Comment by apbendi** [comment]
I'm having this issue as well. Good call on the override @christiantakle!

**Comment by davegravy** [comment]
+1 Same here

**Comment by beshanoe** [comment]
Same here, it happens because the datepicker actually requires some kind of reset.css and it's included in styles on the examples page, but is not mentioned in docs at all. The style should either be included in the selector or there should be additional line in docs

**Comment by davegravy** [comment]
@beshanoe I'm looking at the examples page ([aka the main site](https://reactdatepicker.com/)) and see no reference to styles or `reset.css`. Can you be more specific?

**Comment by beshanoe** [comment]
@davegravy sure, here https://github.com/Hacker0x01/react-datepicker/blob/master/docs-site/style.css starting from line 645 there's kinda reset styles, and specifically on 727 `padding: 0` is what makes examples work

**Comment by hraybould** [comment]
I'm still having this issue, I ended up:
1. Copying all the CSS to it's own file
2. Pre-pending a custom class to the selectors in that new file (since I was using SCSS, this just meant wrapping the existing CSS in the new class)

This meant that my Reset CSS file wasn't taking a higher specificity
