### ISSUE TITLE
input doesn't have styles

### ISSUE THREAD

**Issue by winlx** [Hacker0x01/react-datepicker#1287]
### Expected behavior
I wanna get styles for input like in docs:
![origin](https://user-images.githubusercontent.com/6899688/36843888-732328b0-1d61-11e8-94b9-c0d352238dc2.png)

### Actual behavior
But I get this:
![reality](https://user-images.githubusercontent.com/6899688/36843899-7df83df2-1d61-11e8-9e1f-9a80cbcb6e13.png)

Other styles work fine.

I do not understand what I'm doing wrong.

**Comment by hudsonpereira** [comment]
Is there a way to set `style={}` for `DatePicker` component?

**Comment by stevenkaspar** [comment]
You can use the `customInput` property to make this happen - at least it worked for my purposes

https://github.com/Hacker0x01/react-datepicker/blob/e052b4ad349c92670b63c0a19d69a6a5f1fb6396/src/index.jsx#L573

```
<DatePicker
  selected={this.state.starts_at}
  timeFormat="HH:mm"
  dateFormat="LLL"
  onChange={(day) => this.handleDateChange('starts_at', day)}
  customInput={<input style={INPUT_STYLE} />}
/>
```
