### ISSUE TITLE
day class name issue

### ISSUE THREAD

**Issue by yangxiaoyao1983** [Hacker0x01/react-datepicker#1293]
### Expected behavior
i want see red day names , but i see all the color of the day names are black!
### Actual behavior
i used the props
dayClassName={date => date.date() < Math.random() * 31 ? 'random' : undefined}

### Steps to reprodcue
100% occurs

**Comment by al3x-huang** [comment]
Same issue here. 

```
<DatePicker selected={this.state.date} onChange={this.updateDate} dayClassName={date => date.date() < Math.random() * 31 ? 'random' : undefined}/>
```

Is the code I used from the example.

**Comment by al3x-huang** [comment]
Ah, I did some digging around and realized that I was using an earlier version of `react-datepicker`. Using v0.5.0 solved my issue.

**Comment by bpsourav21** [comment]
For my case its working. What you need to do that define your random class like this.
.random{
    color: #f00 !important;
}

**Comment by bpsourav21** [comment]
It works for me. what you need to do just  define random class like this
.random{
    color: #f00 !important;
}
