### ISSUE TITLE
feature request: date range in one box

### ISSUE THREAD

**Issue by jaylucas** [Hacker0x01/react-datepicker#1296]
Hey, thanks for the great component.
I was wondering if it would be possible to combine date range boxes?

![screen shot 2018-03-05 at 4 57 55 pm](https://user-images.githubusercontent.com/1731967/37008615-d779876c-2097-11e8-86d3-d640abd5ec49.png)

I mean the fields on the right, like: last month, last week, etc..

**Comment by aij** [comment]
That should already be possible. It looks like you'll want your component to render two inline date pickers, and use them to select a range. See the [inline example](https://reactdatepicker.com/#example-34) and the [date range example](https://reactdatepicker.com/#example-20).

Let us know if for some reason those features do not work well together.

**Comment by jaylucas** [comment]
Sorry, I guess the image is misleading. If you look at the top right of the two boxes. It is a SINGLE input box. A better example:

<img width="639" alt="screen shot 2018-03-06 at 11 34 20 am" src="https://user-images.githubusercontent.com/1731967/37053951-6d0938be-2132-11e8-9d0e-b59ccbd0daae.png">

**Comment by aij** [comment]
Ok... Have you run into any problems in your attempt to create that single input? Have you tried rendering two ReactDatepicker instances as subcomponents for it?

**Comment by jaylucas** [comment]
I mean, I "could" create this with custom drop downs/css/text box, but it would be a nice feature to have out of the box. I see a lot of other react date pickers with this functionality.
