### ISSUE TITLE
Selected time doesn't scroll into view when popper is opened

### ISSUE THREAD

**Issue by wombat86** [Hacker0x01/react-datepicker#1297]
### Expected behavior
When opening calendar with time list **selected** time should be scrolled into view.

### Actual behavior
Selected time is not visible in the list view port and user has to scroll the list to find it.

### Steps to reprodcue
Having **selected** property set to particular date/time along with **showTimeSelect** property set to true and **timeIntervals** set to 1 (or 2, or 5 etc.) click on DatePicker to open the popper.

**Comment by wombat86** [comment]
After a short investigation I figured that [componentDidMount hook](https://github.com/Hacker0x01/react-datepicker/blob/2f9e54eed7bf9ec78a3211157e47d04faa45c71c/src/time.jsx#L39) of Time component has two possible problems that cause this issue:

- Hardcoded height of `li` items is used (30)
- The scrollTop position is calculated for the selected hour, not the actual selected `li`.

In my case the actual height of `li` is 25px. After manually hacking the code by replacing 25 with 30 the list started showing at the beginning of selected hour. E.g. if you select 12:45, the list shows 12:00. This is very inconvenient if you have intervals less than 30 minutes.

**Comment by carlostxm** [comment]
In our application we are experiencing the same problem, it's a little confusing when you don't know what is happening.

**Comment by wombat86** [comment]
I could prepare a PR but need some input from maintainers. There are few option of fixing this issue:

- fix calculation logic
- use [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) on selected element.

Either option has its pros and cons.

**Comment by S1rFrancis** [comment]
I have put together a quick PR using the scrollIntoView function that @wombat86 mentioned above. Would be great if you could let me know what you think of it.

**Comment by WesselKroos** [comment]
For now I'll use a 30 pixels height for my time picker. But we would like to change that to a greater value so that it complies with our designs. When can we expect this fix to be released?

**Comment by fabiosangregorio** [comment]
+1 on this fix
