### ISSUE TITLE
UTC offset lost on manual editing

### ISSUE THREAD

**Issue by tomtwttr** [Hacker0x01/react-datepicker#1298]
### Expected behavior
Inputing a selected moment with some utc offset without zone formatting should work

### Actual behavior
It will instead parse it as a local time.

**Comment by saward** [comment]
Did this get resolved?  I'm noticing this issue, or one very much like it, using 1.5.0.

**Comment by tomtwttr** [comment]
@saward I believe I worked around this such that the date picker is never aware it's using UTC or other. AKA I have UTC UI indication at a higher level and I adjust moments based on UTC offset minute.

**Comment by saward** [comment]
Alright, taking a similar approach seems to have simplified my fix quite a lot, thanks.  Should this issue still be open since it appears to be a fault still?

**Comment by tomtwttr** [comment]
@saward I'm unsure TBH. After digging around with this quite a bit it felt like moment lib was more to blame (at least half to blame) rather than date picker. If you feel this is important I recommend submitting a pull request or opening up a new issue referencing this one.
