### ISSUE TITLE
Can we change the area appearing this Date popup (Weather up or down) instead of default?

### ISSUE THREAD

**Issue by Erandakuruneru** [Hacker0x01/react-datepicker#1304]
**Can we change the area appearing this Date popup (Weather up or down) instead of default?**

Like this situation, the user can not click the date time picker.

once load the date time picker under the deader of the page, then this problem occurs.
![datetime](https://user-images.githubusercontent.com/10955492/37137324-45befb00-22cb-11e8-8a5d-dd379595112d.PNG)

**Comment by aij** [comment]
Yes. Use `popperPlacement`.
