### ISSUE TITLE
Feature: Support flow types

### ISSUE THREAD

**Issue by aij** [Hacker0x01/react-datepicker#1306]
We've started using [flow](https://flow.org/) at work and find the static type checking useful.

We're also using `babel-plugin-flow-react-proptypes`, which generates propTypes based on the flow types of a component, which means we don't need to worry about duplication and the resulting inconsistency.

The nice thing about flow is that it will check at compile time that the props (or function arguments) are being used consistently with their declared types. So, for example, it would flag places where we assume an optional prop is always defined. (react-datepicker has some such cases, especially for props with defaults)

There are two ways we could support flow:

1. By adding type declarations but keeping them separate from the code. This would benefit users of the library who use flow.
2. By adding flow types within the code. This would help users who use flow in addition to helping us catch bugs within the library itself. Less buggy code would also benefit users who don't use flow.

Of course, I would prefer option 2. :smiley: But I'd like to know there is buy-in before I spend too much time working on it. I can start on some of the smaller subcomponents if you'd like to get an idea of what it would look like.

cc @martijnrusschen @rafeememon

**Comment by martijnrusschen** [comment]
I don't have any experience with this, but if we can do this in a way that we can support this for people that have less experience with it (Linters? Tests?), it sounds like a nice addition. There's some historic context around this in #299 where TypeScript was suggested.

**Comment by aij** [comment]
@martijnrusschen Flow is a lot like a linter, in that it doesn't affect the runtime behavior at all, but it does require more annotations than eslint. They can be in comments, but it's prettier when they're not. Transpiling flow is as simple as removing the annotations, which we already seem to have babel configured to do.

The way we're using it at work, we have webpack configured to run flow, but it continues even if flow finds errors. (So you'll see the type errors but they don't get in the way of running the code.) On our CI server, we do reject changes that fail to typecheck, though initially we didn't.

Another advantage of Flow over TypeScript, is that React uses Flow, so our users are more likely to be familiar with it.

I added #1307 as a simple example.

**Comment by martijnrusschen** [comment]
Looks great, how do we make sure others are adding types as well when adding new functionality? Is there a way to enforce this somehow? It needs to be user-friendly and self-guiding to make sure people keep contributing.

Also, how do we migrate? It seems we can migrate piece by piece, but is there a way to measure progress?

**Comment by aij** [comment]
> Looks great, how do we make sure others are adding types as well when adding new functionality?

We could run flow from the build system so contributors would see flow errors right away, like with eslint. Another option would be to run it during testing, but it's often convenient to see type errors sooner rather than later.

> Also, how do we migrate? It seems we can migrate piece by piece, but is there a way to measure progress?

We can migrate piece by piece, and even adding flow checking into the build can be it's own piece. (Though probably one that is worth doing [relatively] sooner rather than later, to prevent the other pieces from bitrotting.)

For measuring progress, I see React is using [flow-coverage-report](https://www.npmjs.com/package/flow-coverage-report). I haven't used it yet, but it looks pretty straightforward.

**Comment by martijnrusschen** [comment]
> We could run flow from the build system so contributors would see flow errors right away, like with eslint. Another option would be to run it during testing, but it's often convenient to see type errors sooner rather than later.

Sounds like a good idea, I think it would be good add this in before we land the PR that's open. Thoughts? I found a few articles related to this but doesn't seem like there's a default way of doing this.

> For measuring progress, I see React is using flow-coverage-report. I haven't used it yet, but it looks pretty straightforward.

Looks interesting! But lets focus on adding the default checks to the CI first.

**Comment by martijnrusschen** [comment]
https://react.rocks/blog/post/flowtype-continuous-integration/

**Comment by kangax** [comment]
Found this issue when looking for flow-typed definitions for react-date-picker. Looks like there are none yet. I'll see if I can find some time for a PR to flow-typed repo.

**Comment by kangax** [comment]
Added in https://github.com/flow-typed/flow-typed/pull/3066
