### ISSUE TITLE
Field name

### ISSUE THREAD

**Issue by adelpuva** [Hacker0x01/react-datepicker#1308]
Hi,
when then names of fields are like this: _filed[0].from_ and _filed[0].to_, in the second calendar, range is not selected; while fields name are like this: **filed0from** and **filed0to**, the range works fine!

Here two snapshot of my case.

( _filed[0].from_ and _filed[0].to_)
![screen shot 2018-03-09 at 12 06 51](https://user-images.githubusercontent.com/1243844/37204875-d07482e8-2392-11e8-9411-8cdee7104ef8.png)

(**filed0from** and **filed0to**)
![screen shot 2018-03-09 at 12 06 08](https://user-images.githubusercontent.com/1243844/37204892-eb49dba4-2392-11e8-95a7-be71af298f07.png)

I use DatePicker inside a Field:
`<Field name={ fields.names[0] }
label={ fields.labels && fields.labels[0] }
component={ DatePicker }
additionalProps={ Object.assign(additionalProps, { 'selectsStart': true }) }
clearable />`

For me the "array" format of fields is a requirement! There's a way to solve the issue?
Any suggestion?

Thanks

**Comment by aij** [comment]
That looks more like a  problem in your code than in react-datepicker. The `name` prop is passed pretty much straight through to the `<input>`. You can check with React Devtools to be sure.

We can't debug your code of course (especially if you don't even provide it), but if you can narrow the issue down to a minimal reproduction we could take a look at that.

**Comment by adelpuva** [comment]
Maybe...

From React Devtools (Chrome/Mac OS):

**renderDatePicker** is the component (_stateless function_) that include DatePicker.

![screen shot 2018-03-09 at 15 55 04](https://user-images.githubusercontent.com/1243844/37213433-4d337ef0-23b2-11e8-942d-0e5cbf5444be.png)

This is more readable input content:
`{
	"input": {
		"name": "timetable[0].from",
		"onBlur": {},
		"onChange": {},
		"onDragStart": {},
		"onDrop": {},
		"onFocus": {},
		"value": "2018-02-25T22:00:00.000Z"
	}
}`

If the name of field is without square brackets and dot (_timetable0from_) the range selection works fine.

Thank you.

**Comment by aij** [comment]
You see that ellipsis (...) in your screenshot? That is where you should be looking to see whether the name is being passed through correctly. (Both on `<DatePicker ...>` and `<input ...>`)

I would guess the problem is in that `renderDatePicker` component. If you narrow down the code and it does turn out to be a problem in DatePicker, please do provide a minimal example showing the problem.

**Comment by adelpuva** [comment]
Here more info.

As you see the name of input is passed to DatePicker and input:
<img width="701" alt="screen shot 2018-03-14 at 11 17 31" src="https://user-images.githubusercontent.com/1243844/37396817-438c130a-277a-11e8-929d-20d44a53a112.png">

And here all props of DatePicker:
<img width="366" alt="screen shot 2018-03-14 at 11 23 20" src="https://user-images.githubusercontent.com/1243844/37396839-521b4cd8-277a-11e8-98b7-0609b5da7c67.png">

With the name **timetable[0].from** the range selection no works, If i use _timetable0from_ selection range works.

Where could my mistake be?

Thank you

**Comment by adelpuva** [comment]
Resolved! I do not pass startDate and endDate in the right way!
