### ISSUE TITLE
missing external div className

### ISSUE THREAD

**Issue by NicolaZaltron** [Hacker0x01/react-datepicker#1309]
The component creates an external div containing the "react-datepicker__wrapper" and "react-datepicker__popper"

![image](https://user-images.githubusercontent.com/9315502/37232093-d1d612d6-23ed-11e8-8b14-d73e3c4d87f1.png)

This external div doesn't have a className, and have been trying a lot to find a workaround to set it the display:inline property without a decent result.

Is it possible to add a class to it?

Thanks!

**Comment by rafeememon** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/932
