### ISSUE TITLE
Clarification about onBlur

### ISSUE THREAD

**Issue by danilvalov** [Hacker0x01/react-datepicker#1310]
(Reopening #1110)

There is a mismatch between the code and examples.
There is a [date argument](https://github.com/Hacker0x01/react-datepicker/blob/master/docs-site/src/examples/on_blur_callbacks.jsx#L15), but the datepicker returns an [event](https://github.com/Hacker0x01/react-datepicker/blob/master/src/index.jsx#L262).

And when we open the [example page](https://reactdatepicker.com/#example-24) and unfocus an input then we see an error in the console: `TypeError: date.format is not a function` because there is `event`, not `date`.

What do I need to fix in my PR to the repo: examples or `onBlur` arguments?

**Comment by iamandrewluca** [comment]
There is `onChange(date, event)` and `onChangeRaw(event)`  
Then it should be `onBlur(date, event)` and `onBlurRaw(event)`  
same for `onFocus` and `onFocusRaw` ?!
