### ISSUE TITLE
Change border color of the associated text box 

### ISSUE THREAD

**Issue by jcabrerazuniga** [Hacker0x01/react-datepicker#1314]
Is it possible to dynamically change the border color of the text box associated to the date picker calendar?
I wish I could change that color to tell the user 'this is a required field'. I tried

                    <DatePicker style={{borderColor='Red' }} .... /> 

but the border color associated to the DatePicker is always black

Thx

**Comment by FelipeLujan** [comment]
i need to do something like this too.
but also for the textbox background.

**Comment by xero88** [comment]
i need this feature too !
