### ISSUE TITLE
Using React-DatePicker with Redux and Stateless Components

### ISSUE THREAD

**Issue by tscrip** [Hacker0x01/react-datepicker#1315]
### Expected behavior
I would love to be able to do something like this: 
```
updateState(value) {
        this.props.updateValue(this.props.id, this.props.stateAttribute, value);    
    }

<DatePickerModule 
    selected={this.props.selected} 
    className="form-control" 
    containerClassName="form-control" 
    onSelect={this.updateState}
/>
```
Or do something like this:
```
<DatePickerModule 
    selected={this.props.selected} 
    className="form-control" 
    containerClassName="form-control" 
    onSelect={(event) => this.props.updateValue(this.props.id, this.props.stateAttribute, event.value)}
/>
```
It does not look like the event data is accessible via the onSelect this way. Would it be possible to create an `onSelectRaw` that would allow you to specifically get the value of the DatePicker?

**Comment by yanniser** [comment]
I currently use this datePicker with Redux , it works well.
In fact I throw the redux actions in the onChange handler and that's it.

`<DatePicker
            value={format(dateDeNaissance, 'DD/MM/YYYY')}
            onChange={this.handleCalendarChange}
            dateFormat="LLL"
   />

  public handleCalendarChange  = (value) => {
    this.setState({
      value: moment(value).toISOString(), // ISO String, ex: "2016-11-19T12:00:00.000Z"
    })
    this.props.dispatchChangeAction (value)
  }

`


Does that answer your question ?

**Comment by yanniser** [comment]
`wazza`
