### ISSUE TITLE
how to hide the calendar title, header

### ISSUE THREAD

**Issue by jwallet** [Hacker0x01/react-datepicker#1318]
### Expected behavior
to be able to hide the calendar month/year header when the header title is replaced by drop down lists, or to be able to set `dateFormatCalendar=""`, or a new prop `hideHeader`

### Actual behavior
no props or css class is available to hide the calendar header

it used to be a feature after they closed this issue #1008
[PR merged that added css Display None when drop down list were used](https://github.com/Hacker0x01/react-datepicker/pull/1026#issuecomment-330860422)

**Comment by aij** [comment]
#1008 wasn't closed yet. This seems like a duplicate, but please clarify if it is not.
