### ISSUE TITLE
Possibility to make calendar 'always open'

### ISSUE THREAD

**Issue by eldeni** [Hacker0x01/react-datepicker#1322]
This is not a bug, rather a suggestion. I am going to tweak it on my own though.
It would be helpful if the calendar can be **constantly shown** (with the flag). 

I am trying to put the two calendars on the same div (which is already a modal) and
let the user decide the date range with two calendars open until the closing action.

**Comment by CaitlinWeb** [comment]
Can you use the `inline` prop for your case? That shows the calendar, though without an input.

**Comment by haddyo** [comment]
Any Solution which can be arrived at the moment, which can help me out?

**Comment by astanimirov** [comment]
I have exactly the same request. It would be great if we can get such option!
