### ISSUE TITLE
`onInputKeyDown` should use utc offset

### ISSUE THREAD

**Issue by jakub-chatrny** [Hacker0x01/react-datepicker#1324]
### Expected behavior
`onInputKeyDown` should use consider utc offset using `newDateWithOffset()` [code](https://github.com/Hacker0x01/react-datepicker/blob/87a8cb4d399aee3139c2659e75410b5eff05040e/src/date_utils.js#L53)
instead of 
`moment(point)` [code](https://github.com/Hacker0x01/react-datepicker/blob/master/src/index.jsx#L402)
### Actual behavior
`onInputKeyDown` use only `moment(point)` instead of `moment(point)
    .utc()
    .utcOffset(utcOffset);`
that leads to inconsistency `onSelect` (when you select date in dropdown) consider date and `onInputKeyDown` does not.
### Steps to reproduce
In timezone +1 select date via datepicker dropdown (i.e. 20/3/2018). Change in input to 24/3/2018 and `23/3/2018 23:00` is returned.

**Comment by rafeememon** [comment]
PRs to fix this are welcome
