### ISSUE TITLE
Unable to set selected state from external component

### ISSUE THREAD

**Issue by sconno05** [Hacker0x01/react-datepicker#133]
I think there is an issue with the selected state value.  Specifically, a parent component can set the selected value by passing it as a prop, but if the parent were to change its value, the DatePicker component does not receive the update.  I have a separate "Clear" button on my page that should be able to clear the input.  I believe the root of the issue is the use of getInitialState() to set selected value from the prop:

```
getInitialState: function() {
    return {
      focus: false,
      selected: this.props.selected
    };
  },
```
The documentation states this as an antipattern: https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html

I believe the solution is to have a componentWillReceiveProps that can keep the selected state updated on changes, something like:

```
componentWillReceiveProps(newProps){
  this.setState({
    selected: newProps.selected
  });
}
```

What do you think? I'm happy to submit a pull request.

**Comment by cschuch** [comment]
:+1: I'm also having an issue with this, that fix would solve my problem as well.

**Comment by martijnrusschen** [comment]
Thanks, I'll take a look at #135 to make sure it works fine with our config too.

**Comment by sconno05** [comment]
Thanks Martijn.  Do you have an ETA for when you can merge this in?

**Comment by martijnrusschen** [comment]
Thanks, will release this today.

**Comment by dmatora** [comment]
Is this supposed to be working?
When I change date from another component (previous / next day buttons) date picker date is changed but not rendered until I click date picker
