### ISSUE TITLE
Request: inline styling of calendar

### ISSUE THREAD

**Issue by CaitlinWeb** [Hacker0x01/react-datepicker#1332]
For the project I'm working on we're allowing the customization of components such as font and border colors, etc. To do this we're currently using inline styles (also known as css-in-js, I believe).

Could we get props to pass different `style` props to the various parts of the calendar component? I can open a PR for this if it's acceptable.

**Comment by colmfah** [comment]
I would also like to be able to use inline style to change the border color. This won't work for react datepicker

`state= {
    borderColors:{
        startDetails: 'none',
    }
}

borderColor = (e, field) => {
    e.preventDefault()
    let borderColors = this.state.borderColors
    e.target.value === '' ? borderColors[field] = 'tomato' : borderColors[field] = '#00988f'
    this.setState({borderColors})
}



  <DatePicker
     className="datePicker"
     timeIntervals={15}
     selected={values.startDetails}
     onBlur = {event => this.borderColor(event, 'startDetails')}
     onChange={(event) => this.props.changeField(event, "startDetails")}
     showTimeSelect
     dateFormat="d MMM yyyy HH:mm"
     required
     placeholderText={'Date & Time Event Starts'}
     style={{borderColor: this.state.borderColors.startDetails}}
     />`
