### ISSUE TITLE
Demo page rapidly flashes

### ISSUE THREAD

**Issue by JacquiManzi** [Hacker0x01/react-datepicker#1334]
### Expected behavior
Demo page does not rapidly flash

### Actual behavior
Clicking on the datepicker input area causes the page to rapidly flash.

### Steps to reprodcue
Go to https://reactdatepicker.com/ and click on the date picker input, rapid flashing occurs.

Browser Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by martijnrusschen** [comment]
Just tested this on the latest Chrome and seems to work fine for me. Can you try this with a different browser and see if it might be related to your Chrome?

**Comment by martijnrusschen** [comment]
I'm using `Version 65.0.3325.181 (Official Build) (64-bit)`

**Comment by JacquiManzi** [comment]
Just had a co-worker re-produce this on Chrome, it didn't happen for him at first, but once he refreshed the page and tried again he got it to flash. I'll try Firefox.

**Comment by martijnrusschen** [comment]
Does it happen on any specific example, or isn't that relevant to reproduce the issue?

**Comment by mmcc** [comment]
^^ I am the above coworker, using Firefox 59.0.1. It seems to only happen on the _first_ click to the example in the hero. If I click elsewhere I can get the flashing to stop, and other examples (including that one) seem to work fine. If I refresh the page again and click the hero example, it triggers it again. Here's a quick recording: http://take.ms/Yj3sj

**Comment by martijnrusschen** [comment]
Hmm, interesting issue. Have you tried this with the latest Chrome as well? I haven't been able to reproduce the issue. I'm not sure if you have time to take a look, but if you can reproduce this on the local build, perhaps we can find out what's going wrong. 

(We (and many others) use this date picker in our production apps and it doesn't seem to be causing any issues for us)

**Comment by mmcc** [comment]
Yep, [also happens in the latest Chrome (65.0.3325.181)](http://take.ms/enEfl). My guess is the problem is just with the demo, not the library itself since it's really only one scenario that causes it. Unfortunately that scenario is also the most prominent example on the demo site, but I don't think this is a mission critical issue with the library itself.

**Comment by mmcc** [comment]
Ok digging in a little more we found some other interesting tidbits, but ultimately this seems like a focus issue. I noticed that if I open the page with my devtools open, the input field shows up without the dropdown open and clicking the input doesn't trigger the flashing insanity. Likewise, if I go to the page like before but click away from the input _first_ before clicking in the input field, the flashing doesn't occur. [Recordings of both scenarios](http://take.ms/ZO6CR).

**Comment by Hultner** [comment]
I have the same behaviour in all browsers I tested in. Listed below:

- Chrome, Version 66.0.3359.117 (Official Build) (64-bit)
- Safari, Version 11.1 (13605.1.33.1.4)

I also experience a similar issue but much slower flashing in
- Firefox Quantum 59.0.2 (64-bit)

In addition to this my team member @Levis92 also experience the same issue. It seems crucial that it's the first thing you click, in addition to that it sometimes doesn't happen (about 1 in 10).

**Comment by mtford90** [comment]
Flashing for me also on Chrome Version 66.0.3359.139 (Official Build) (64-bit), Mac OS X

**Comment by wramp** [comment]
Same for me, im using newest Chrome Version 66.0.3359.181 (Official Build) (64-bit), Win 10
