### ISSUE TITLE
With 2 months shown and inline calendar, the months shift when range selected spans the 2 months

### ISSUE THREAD

**Issue by sshilal1** [Hacker0x01/react-datepicker#1337]
I have an inline calendar with 2 months shown. Whenever a user selects a date range that spans the 2 months, if the range is not in the same month, the left month slides out of view. As seen in the gif below, In order to view the full range, a user must select the back arrow to see the range again.

![datepicker1](https://user-images.githubusercontent.com/15115953/38110725-90294006-336a-11e8-8994-8e698c95c3d8.gif)

Here is my code
```
<DatePicker
  inline
  selected={this.state.startDate}
  startDate={this.state.startDate}
  endDate={this.state.endDate}
  onChange={this.handleDateSelect}
  monthsShown={2}
  shouldCloseOnSelect={false}
/>
```

I feel as if there should be a prop to enable / disable this.

**Comment by aij** [comment]
I don't think the months were intended to shift when selecting a day. It seems like a buggy interaction between `monthsShown` and `inline`. (Normally, the date picker would close after selecting a date, so re-opening to the last selected date is fine/expected, but staying open and shifting is weird.)

**Comment by fooberichu150** [comment]
We're running into this issue as well.  I don't mind so much that it shifts the calendar as that when you're on a mobile device (I think it may just be iOS) the previous date placeholder on the 2nd month still shows highlighted until you "touch" somewhere else on your screen.  Getting this bug fixed would at least also prevent that associated display issue from showing up.

Before:
![screenshot_before_ios](https://user-images.githubusercontent.com/27869244/48450226-b1c3a380-e762-11e8-888f-e44458062af8.jpg)

After (December 13th being my selection):
![screenshot_after_ios](https://user-images.githubusercontent.com/27869244/48450238-c0aa5600-e762-11e8-8e22-f092b20940b4.jpg)

**Comment by martijnrusschen** [comment]
Should be fixed now

**Comment by smithaitufe** [comment]
Please I need to know how this was eventually resolved.

How do you know if it is the startDate that was selected or if the endDate that was selected?

**Comment by smeletis** [comment]
This is not fixed, why is this issue closed?

**Comment by eivindchr** [comment]
> This is not fixed, why is this issue closed?

I fixed this using shouldCloseOnSelect={false}

**Comment by BeKnowDo** [comment]
This is definitely not fixed... 2021 😆

**Comment by singladno** [comment]
> This is definitely not fixed... 2021 😆

Have you tried this?
`focusSelectedMonth={true}`

**Comment by NoelBaron** [comment]
> > This is definitely not fixed... 2021 😆
> 
> Have you tried this?
> `focusSelectedMonth={true}`

@BeKnowDo this is actually fixed with `focusSelectedMonth={false}`. See gif.
![MultiMonthFocus](https://user-images.githubusercontent.com/6867744/126314418-db4c4252-0c4b-4629-af74-6a995e7c183e.gif)

```
<DatePicker 
  focusSelectedMonth={false}
  startDate={startDate}
  endDate={endDate}
  monthsShown={2}
  selectsRange
  inline
  disabledKeyboardNavigation // <-- active-day bug is still open
  onChange={(e) => {  setDateRange(e) }}
/>
```

**Comment by honam867** [comment]
i try to fix by using focusSelectedMonth={true} on issue #2609, but it happend on this issue and don't know how to have a better way to fix both issue

**Comment by jphawk** [comment]
I have the same issue and none of the described fixes worked for me either :/

**Comment by cabrace** [comment]
Can confirm bug in 2022... The main thing that introduces it is : showPreviousMonths.
When this option is allowed, clicking any date for previous months forces calendar to constantly jump back,
without ever being able to select a date. When removed calendar selection date functions as normal.

```
 <DatePicker
      selected={null}
      onChange={onChange}
      startDate={startDate}
      endDate={endDate}
      selectsRange
      inline
       // showPreviousMonths //  <--- this causes dates to not be selected when monthsShown > 1
       monthsShown={3}
       maxDate={new Date()}
       wrapperClassName='date_picker_style'
  />
```

**Comment by sergeykurilov** [comment]
2023 this bug is still present.....

**Comment by unni4121987** [comment]
Is this fixed?

**Comment by sglogovic-moberg** [comment]
This bug makes the Multi-month date range unusable. Can you please fix this?

**Comment by brienpafford** [comment]
I got it to work by adding:
`selected={startDate}`

<img width="315" alt="Screenshot 2023-08-17 at 5 46 54 PM" src="https://github.com/Hacker0x01/react-datepicker/assets/10601340/fbce10fd-05aa-47c8-8724-8aac1a4d9e88">

**Comment by ultdevchar** [comment]
In my case, only ```selected={endDate}``` definition (without ```focusSelectedMonth```) works! 
If start date is assigned, your calendar might be opened shifted after the first selections.
