### ISSUE TITLE
Bad usability on multi month calendar

### ISSUE THREAD

**Issue by jkyro** [Hacker0x01/react-datepicker#1359]
When inline is set the month where the selected date is will always become the first month. If multiple months are visible this is very confusing when selecting a date from any other month than the first as the month containing the selected date will jump. 

This behavior cannot be worked around using e.g. openToDate since the selection event will override the openToDate prop.

Before selection:
![selection_018](https://user-images.githubusercontent.com/11060369/38926062-108dcab0-430a-11e8-984e-de56110ae43f.png)

After selection:
![selection_019](https://user-images.githubusercontent.com/11060369/38926072-17ca09d8-430a-11e8-995b-35dbbcca32b5.png)

**Comment by jkyro** [comment]
What I would expect after selection:
![selection_020](https://user-images.githubusercontent.com/11060369/38926114-4369c358-430a-11e8-89ac-c2c565c09efa.png)

**Comment by martijnrusschen** [comment]
Fixed
