### ISSUE TITLE
ref error

### ISSUE THREAD

**Issue by MR0B0T** [Hacker0x01/react-datepicker#136]
[Error] TypeError: null is not an object (evaluating 's.findDOMNode(this.refs.input).blur')

[Error] Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

**Comment by tonyhb** [comment]
You might want to look into parent vs owner refs:  https://gist.github.com/jimfb/0eb6e61f300a8c1b2ce7

Maybe you're making the calendar in a component which isn't owned by your parent component.

**Comment by martijnrusschen** [comment]
Can you show an example where this is happening?

**Comment by sjcrank** [comment]
I have a similar issue, here is an example:
[index.js | uploaded via ZenHub](https://files.zenhub.io/560bddf4d7a4f68e2d4f0bff)

**Comment by stevenleeg** [comment]
I'm having this issue as well (with a similar example as @sjcrank's). Any ideas as to what's going wrong?

**Comment by sjcrank** [comment]
I discovered the cause of my problem: I was including React.js in my index.html (not through browserify), but importing react-datepicker via browserify. Since react-datepicker has a react dependency, react was added in node_modules. Thus, I had 2 conflicting Reacts which causes this error message.

**Comment by stevenleeg** [comment]
op, I was doing the exact same thing. that's probably it then. thanks @sjcrank!

**Comment by shortstuffsushi** [comment]
Hi guys,

I'm seeing this issue as well, and don't really know enough about React to understand where I'm going wrong. I'm including the `DatePicker` inside another component, just inside its `render` block boiling down to effectively this --

```
return (
    <div id="input-box">
        <input id="field1" type="text" ></input>
        <DatePicker selected={this.state.date} onChange={this.onDateSelect} />
        <input id="field2" type="number"></input>
        <input id="field3" type="number"></input>
    </div>
);
```

 * I'm not including React or Moment externally, they're both browserify'd
 * I've used this.props.date, this.state.date, and an arbitrary local date var (I read passing props may be an issue)

Any idea?

**Comment by shortstuffsushi** [comment]
Hmm, I have no idea what's changed, but after uninstalling and reinstalling all of my modules (playing around w/ various date picker modules, decided to just dump the node_modules folder), it is now working.

**Comment by martijnrusschen** [comment]
Looks like this issue has been fixed. Let me know if there's any help needed.
