### ISSUE TITLE
Error in CSS

### ISSUE THREAD

**Issue by CamilaSolis** [Hacker0x01/react-datepicker#1362]
when adding
import 'react-datepicker/dist/react-datepicker.css'
 in my code I get the following

![captura de pantalla 2018-04-18 a la s 16 12 17](https://user-images.githubusercontent.com/20929448/38952944-9a3148b4-4323-11e8-9335-979409fbc450.png)

Help Please!!

**Comment by hakimelek** [comment]
Refer to custom CSS imports in using Next.js
👉 https://github.com/zeit/next.js#importing-css--sass--less--stylus-files
