### ISSUE TITLE
Month Container to small

### ISSUE THREAD

**Issue by rullymartanto** [Hacker0x01/react-datepicker#1363]
it is to small, how to make it bigger (Month Container) ?
![screenshot_2](https://user-images.githubusercontent.com/5577057/38975434-07a08a72-43d8-11e8-97f0-028557066fba.png)

Thanks

**Comment by redgetan** [comment]
i was able to make it larger by modifying the css styles. For example


```
.react-datepicker__day-name,
.react-datepicker__day,
.react-datepicker__time-name {
  width: 2.5rem;
  line-height: 2.5rem;
  font-size: 12px;
}

```

**Comment by AndyMeps** [comment]
I had to change the `font-size` associated with my `html, body` rule:

```css
html, body {
  font-size: 14px;
}
```

I assume this is because `react-datepicker` uses `rem` for font sizes.

**Comment by idoo** [comment]
doesn't work well for me with changes from https://github.com/Hacker0x01/react-datepicker/issues/1363#issuecomment-393509873 and https://github.com/Hacker0x01/react-datepicker/issues/1363#issuecomment-393826761
