### ISSUE TITLE
How to use react-datepicker from CDN only (with React from CDN only too)

### ISSUE THREAD

**Issue by Jaguar1** [Hacker0x01/react-datepicker#1364]
### Expected behavior
In case one uses React through CDN only (without npm installation) then is it possible to use 'react-datepicker' the same way?

### Actual behavior
When linking moment.min.js and react-datepicker.min.js through CDN:

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/1.4.1/react-datepicker.min.js"></script>

errors received for dependencies (I guess):

Uncaught TypeError: Cannot read property 'object' of undefined
    at react-datepicker.min.js:1
    at react-datepicker.min.js:1
    at react-datepicker.min.js:1

### Steps to reproduce
Please someone give a working example of 'react-datepicker' and React itself through CDN only.
If not supported this way please confirm.

**Comment by vladimir-poma** [comment]
I think to get CDN works it's needed to add other modules/stuff that are needed for React DatePicker defined in webpack.config.js, I was able to run CDN by adding the next libraries

    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prop-types/15.6.1/prop-types.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/react-onclickoutside@6.7.1/dist/react-onclickoutside.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/classnames/2.2.5/index.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react-popper/0.10.4/umd/react-popper.js"></script>
    
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/1.4.1/react-datepicker.js"></script>

**Comment by monkeysuffrage** [comment]
It doesn't seem to work. I'd love to get an update when it does though. In the meantime it's jQuery I guess.

**Comment by KajSzy** [comment]
Wish I could use single link or whole react-datepicker was packed into single file as UMD module

**Comment by lovato** [comment]
Hi. I installed with NPM and created an ln -s to the file.
Same problem.

Since .js file is also minified (both min.js and js are), it is hard to debug on Chrome.

**Comment by murphysunx** [comment]
> I think to get CDN works it's needed to add other modules/stuff that are needed for React DatePicker defined in webpack.config.js, I was able to run CDN by adding the next libraries
> 
> ```
> 
> <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prop-types/15.6.1/prop-types.min.js"></script>
> <script type="text/javascript" src="https://unpkg.com/react-onclickoutside@6.7.1/dist/react-onclickoutside.min.js"></script>
> <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/classnames/2.2.5/index.js"></script>
> <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>
> <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"></script>
> <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react-popper/0.10.4/umd/react-popper.js"></script>
> 
> 
> <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/1.4.1/react-datepicker.js"></script>
> ```

Hi, may I ask how can you use this component in your js file after importing via CDN?
