### ISSUE TITLE
Append popper to document.body

### ISSUE THREAD

**Issue by agzam** [Hacker0x01/react-datepicker#1366]
Is there a way to force popper to be appended to a different element, e.g.: document.body? It's causing problems when it's required to render datepicker within a fixed container 

![image](https://user-images.githubusercontent.com/1091022/39072187-9be7a7c6-449e-11e8-9d93-0525ff7e9b8d.png)

It's not issue with z-index. Lame workaround for this particular case would be to set main "left" container's overflow to visible, but then it become non-scrollable vertically. Not much of a workaround.

I think if popper was allowed to be attached to any element in DOM hierarchy, this wouldn't be an issue

**Comment by Sigura** [comment]
found solution: https://github.com/Hacker0x01/react-datepicker/pull/1074
sample: https://codesandbox.io/s/1ozy5ol5vl
