### ISSUE TITLE
Address "Unsafe lifecycle methods were found within a strict-mode tree" warnings

### ISSUE THREAD

**Issue by colinrcummings** [Hacker0x01/react-datepicker#1367]
Any plans to replace `componentWillReceiveProps` in the `DatePicker` and `Calendar` components as this lifecycle will be depracated in `react` v16.4? [react-lifecycles-compat](https://github.com/reactjs/react-lifecycles-compat) is another option.

**Comment by martijnrusschen** [comment]
Any help with this would be welcomed :)

**Comment by colinrcummings** [comment]
Sure thing; I'll work on a PR this week.

**Comment by aij** [comment]
To be clear, `componentWillMount`, `componentWillReceiveProps`, and `componentWillUpdate` are [already deprecated in 16.3](https://reactjs.org/blog/2018/03/29/react-v-16-3.html). They will continue to be supported until 17.0.

Deprecation *warnings* will be enabled during some future release -- not necessarily 16.4 AFAICT.

Anyway, we should plan to upgrade, but doing so will most likely involve dropping support for React <16.3.

**Comment by colinrcummings** [comment]
@aij, `react-datepicker` doesn't use `componentWillMount` or `componentWillUpdate`. There are two instances of `componentWillReceiveProps` (in [DatePicker](https://github.com/Hacker0x01/react-datepicker/blob/e052b4ad349c92670b63c0a19d69a6a5f1fb6396/src/index.jsx#L179) and [Calendar ](https://github.com/Hacker0x01/react-datepicker/blob/3b1efbe7dbac7dff0282f12a9925de622dcd2f46/src/calendar.jsx#L143)) that can probably be converted to `componentDidMount`, which won't break the API ([docs](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#migrating-from-legacy-lifecycles)).

**Comment by aij** [comment]
`componentDidMount` won't trigger on prop changes. Did you mean they could be converted to `componentDidUpdate`? It seems kind of weird to `setState` from `componentDidUpdate` but the [docs](https://reactjs.org/docs/react-component.html#componentdidupdate) don't say it's not allowed...

I guess I was assuming we would use the new `getDerivedStateFromProps`, but we might not have to.

**Comment by colinrcummings** [comment]
Yes, @aij, `componentDidUpdate`--sorry! I made a typo in my comment, which I've edited. I don't think we will need `getDerivedStateFromProps`. I'll let you know as soon as I have something.

**Comment by colinrcummings** [comment]
@aji, see [here](https://github.com/colinrcummings/react-datepicker/commit/4df29406d2d532014964135e221daf4d230d5df6). Everything was pretty straightforward--swapping the lifecycle names and changing `this.props` to `prevProps` and `nextProps` to `this.props` inside--with the exception of [this line](https://github.com/Hacker0x01/react-datepicker/blame/c8cc02330a90c70f837870741eff0cab9474b7a1/src/index.jsx#L177) in `DatePicker` from [this pull request](https://github.com/Hacker0x01/react-datepicker/pull/1303). Changing it to:

```
if (!this.state.focused) this.setState({ inputValue: null });
```

caused the following error: 

```
Uncaught (in promise) Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

Based on the example in [this issue](https://github.com/Hacker0x01/react-datepicker/issues/1295), which entails changing `DatePicker`'s `selected` prop, I reused the `hasPreSelectionChanged` check for the `inline` prop check along with the `focused` state check.

Let me know your thoughts...

**Comment by aij** [comment]
@colinrcummings Sounds good to me. Do you mind opening a PR with your
changes?

**Comment by colinrcummings** [comment]
@aji, I have two tests to fix first:

`DatePicker should update the preSelection state when a day is selected with mouse click`

This one is failing for me in `master`. Are you seeing this?

`TimePicker should allow for injected moment if input does not have focus`

This one relates to [this line](https://github.com/Hacker0x01/react-datepicker/blame/c8cc02330a90c70f837870741eff0cab9474b7a1/src/index.jsx#L177); I think adding a check to see if the `selected` prop changed should resolve it.

**Comment by colinrcummings** [comment]
@aji, see https://github.com/Hacker0x01/react-datepicker/pull/1374. I fixed the second test by adding the `hasSelectionChanged` check. The first one ran without issue during the CI run.
