### ISSUE TITLE
Accessibility: Keystrokes not functioning properly in input

### ISSUE THREAD

**Issue by greg-a-smith** [Hacker0x01/react-datepicker#1369]
### Expected behavior
When focus is in the `<input>`, the arrow keys should act the same as they do in other inputs.  The up arrow key should put the cursor before the first character.  The down arrow key should put the cursor after the last character.  The left and right arrow keys should move the cursor one character to the left or right, respectively.

On a similar note, the enter key should trigger any default form behavior (_e.g._ automatically submitting a form, etc.)

### Actual behavior
When focus is in the `<input>`, the arrow keys move the highlighted selection in the calendar.  Even if you use the escape key to close the calendar, it reappears once you start using arrow keys again.

With regards to the enter key, it will simply select the currently highlighted date.

### Steps to reproduce
Go to https://reactdatepicker.com and tab into the first DatePicker input.  Try using arrow keys to move the cursor within the `<input>` and edit the text.

### Suggested direction
In order for the input, the calendar and the time picker to all be properly accessible with keyboard navigation, they need to be decoupled and broken into separate components.  The browser focus actually needs to move from one control to the next so proper key handling can be achieved.  The overlay also likely needs to be linked to a trigger button rather than simply tied to input focus.  When showing an overlay to pick both date and time, it needs to include some form of OK/Cancel buttons since multiple selections can (and need to) be made.

We are interested in continuing to use `react-datepicker`, but we need to make these suggested changes in order to stay compliant.  Our team is willing to help work through these issues (this one plus #1370 and #1371) with multiple pull requests, if you are open to it.

**Comment by larsblumberg** [comment]
What a pity this story didn't get any attention, it's still broken

**Comment by this9is3me** [comment]
Still broken till now...

**Comment by deepak-biradar** [comment]
I want to access the time-picker dropdown using the keyboard up/down arrow. Can you please add support for this?
