### ISSUE TITLE
Trigger Callback on Month Change

### ISSUE THREAD

**Issue by carloquilala** [Hacker0x01/react-datepicker#1379]
### Expected behavior
Able to trigger action on month change

### Actual behavior
No callbacks on month change

### Steps to reprodcue
I'm using these properties

showMonthDropdown
dropdownMode="select"

Are there any ways on how can I trigger an api call after I change month from dropdown select menu?

I'm using these properties

showMonthDropdown
dropdownMode="select"

I want to achieve that whenever I change month, it'll trigger an api call

**Comment by calvinkurniawan** [comment]
hope this can solve your problem https://github.com/Hacker0x01/react-datepicker/pull/626
