### ISSUE TITLE
React Datepicker overwrites customInput's name property

### ISSUE THREAD

**Issue by yasserhussain1110** [Hacker0x01/react-datepicker#1380]
### Expected behavior
This is the code I use -

```jsx

import React from 'react'
import DatePicker from 'react-datepicker'
import {Icon} from 'semantic-ui-react'
import moment from 'moment'

<DatePicker
  customInput={<Icon name="calendar"/>}
  selected={moment()}
/>
```

I expect `Icon` component to have the name property. 

### Actual behavior
It gets overriden in the `renderDateInput` method. To workaround this problem I have to use the code like this - 

```jsx
<DatePicker
  name="calendar"
  customInput={<Icon />}
  selected={moment()}
/>
```

Date picker should not override properties of `customInputElement`.

**Comment by joetidee** [comment]
This is problematic is the name propType of `Icon` is required.
