### ISSUE TITLE
Time on custom input

### ISSUE THREAD

**Issue by lotusms** [Hacker0x01/react-datepicker#1381]
I have the custom input working great for date but not time. The calendar popper shows the time column but it doesn't pass to my textfield component. This is my code.

    class MyDate extends React.Component {
         constructor(props) {
              super(props);
              this.state = {
                  startdate: "",
              };
              this.handleStartDateChange = this.handleStartDateChange.bind(this);
          }

          handleStartDateChange(date) {
              this.setState({
                  startdate: date,
              });
          }
          render() {
               return (
                    <DatePicker
                           customInput={<StartDate />}
                           showTimeSelect
                           timeFormat="HH:mm"
                           isClearable
                           selected={this.state.startdate}
                           onChange={this.handleStartDateChange} />
               );
          }
     }

     class StartDate extends React.Component {
         render() {
             return (
                 <TextField
                     label="Start Date"
                     value={this.props.value}
                     onClick={this.props.onClick}
                     placeholder="DD/MM/YYYY"
                     InputLabelProps={{ shrink: true }}
                     style={{marginTop:0, marginBottom:35}}
                     fullWidth
                     margin="normal"/>
             );
         }
     }

     StartDate.propTypes = {
         onClick: PropTypes.func,
         value: PropTypes.string,
     };

My popper (needs styling I know)
![image](https://user-images.githubusercontent.com/6147772/39814881-1c7d1622-5364-11e8-847a-859d1e242356.png)

Once date and time are picked (notice, no time reflects in my textfield)
![image](https://user-images.githubusercontent.com/6147772/39814931-4e51d8b8-5364-11e8-92ad-2de1b2b70c2d.png)

Love this library by the way!

**Comment by sidsethupathi** [comment]
Have you tried setting the `dateFormat` property in `DatePicker`? 

https://reactdatepicker.com/#example-1

```
<DatePicker
  customInput={<StartDate />}
  showTimeSelect
  timeFormat="HH:mm"
  dateFormat="LLL"
  isClearable
  selected={this.state.startdate}
  onChange={this.handleStartDateChange} />
```

**Comment by lamasdev** [comment]
try: dateFormat="MM/DD/YYYY LT"
