### ISSUE TITLE
Map is undefined (IE)

### ISSUE THREAD

**Issue by quangas** [Hacker0x01/react-datepicker#1383]
Does anyone have this error on IE9/10? Map is undefined.

Day.propTypes = { day: _propTypes2.default.object.isRequired, dayClassName: _propTypes2.default.func, endDate: _propTypes2.default.object, highlightDates: _propTypes2.default.instanceOf(Map), inline: _propTypes2.default.bool, month: _propTypes2.default.number, onClick: _propTypes2.default.func, onMouseEnter: _propTypes2.default.func, preSelection: _propTypes2.default.object, selected: _propTypes2.default.object, selectingDate: _propTypes2.default.object, selectsEnd: _propTypes2.default.bool, selectsStart: _propTypes2.default.bool, startDate: _propTypes2.default.object, utcOffset: _propTypes2.default.number };

Error occurs with Map when calling _propTypes2.default.instanceOf(Map).

Version: "react-datepicker": "^1.1.0"

**Comment by rafeememon** [comment]
You'll need to use a polyfill to run React in IE9: https://reactjs.org/docs/javascript-environment-requirements.html
