### ISSUE TITLE
Empty string for initial value

### ISSUE THREAD

**Issue by gangstaJS** [Hacker0x01/react-datepicker#1388]
Hello. How I can render the datepicker with empty initial input value?

**Comment by EokLennon** [comment]
Use _null_, like this:

```
this.state = {
    ...
    Date: null,
    ...
}
<DatePicker
    selected={this.state.Date}
    onChange={/* Your change function */}
/>
```

**Comment by gangstaJS** [comment]
it will throw an error

**Comment by hisk** [comment]
@gangstaJS You can simply set the date inside your state as `undefined`.

```
this.state = {
    date: undefined
}

handleChange(value) {
    this.setState({ date: new Date(value) });
}

render() {
    return (
        <DatePicker selected={this.state.date} onChange={this.handleChange} placeholderText="My placeholder" />
    )
}

```

Hope it helped! 👍

**Comment by anitta-paul** [comment]
Either of setting initial state as 'null' and 'undefined' worked fine for me.

**Comment by PaulRBerg** [comment]
Using react 16.8.6 and react-datepicker 2.4.0 and I get an error when I assign `selected` to either "null", "undefined", "{}" or  "":

> Warning: Failed prop type: Invalid prop `selected` of type `Function` supplied to `DatePicker`, expected instance of `Date`.

Is there any workaround?

**Comment by neerajtomar98** [comment]
Can we set initial value for time input?

**Comment by imkane** [comment]
> Can we set initial value for time input, while using showTimeInput?
> while initialising with date as null and showTimeInput flag, the time shown in time input shows some random value probably the being added by the browser depending on the current timezone.
> Is there any way by which i can make this input 00:00 instead of default value taken by browser

Yes!!! This is exactly what we need too.

**Comment by neerajtomar98** [comment]
Hi guys,
I resolved this issue by wrapping the Datepicker in a div 
and defining an onclick handler called 'onClickDatePicker' on this div.
This can be called a customDatepicker and be used in other components.

function 'onClickDatePicker' will explicitly set the time to 0000 hours if it is default time(means when no datetime is already set)
it uses a state 'isDefaultTimeInput' to identify  whether default time was set or not.

code example:
  
  <div onClick={this.onClickDatePicker}>
    <DatePicker
        selected={this.props.selectedDatetime}
        onChange={this.onDatetimeChange}
        onSelect={this.props.handleSelectDatetime ? this.onSelectDatetime : () => { }}
        dateFormat={this.props.dateTimeFormat || "dd/MM/yyyy h:mm aa"}
        timeFormat="HH:mm"
        showTimeInput
        disabled={this.props.disabled}
        onClickOutside={this.handleOnClickOutside}
    />
</div>

 //function to set default time as 00:00 in time input.

 onClickDatePicker = () => {
  if (!this.props.selectedDatetime && this.state.isDefaultTimeInput == false) {
            let now = new Date();
            now.setHours(0, 0, 0, 0);
            let openDatetime = (new Date(now));
            this.setState({ isDefaultTimeInput: true });
            this.props.onDatetimeHandler(openDatetime, true);
        }
 }


//function to handle the case when user closes the datepicker without changing the time.
it updates the time back to null in case the isDefaultTimeInput was set true.
handleOnClickOutside = (event) => {
    if (this.state.isDefaultTimeInput) {
        this.setState({ isDefaultTimeInput: false });
        this.props.onDatetimeHandler(null, true);
    }
}


//function to set the selected datetime 
onDatetimeChange = (selectedDatetime) => {
    this.setState({ isDefaultTimeInput: false });
    this.props.onDatetimeHandler(selectedDatetime, false);
}

//function to handle change of date input on selecting any date.
onSelectDatetime = (selectedDatetime) => {
    this.setState({ isDefaultTimeInput: false });
    this.props.onDatetimeHandler(selectedDatetime, false);
}


this solution works fine for me in most cases. 
just one issue that if you are calling any api for updating the time on change /onSelect of the date then
there will be an extra call to set 00:00 time and back.But that too can be resolved with some checks.

Please let me know if it was helpful.

> Can we set initial value for time input, while using showTimeInput?
> while initialising with date as null and showTimeInput flag, the time shown in time input shows some random value probably the being added by the browser depending on the current timezone.
> Is there any way by which i can make this input 00:00 instead of default value taken by browser

Hi guys,
I resolved this issue by wrapping the Datepicker in a div 
and defining an onclick handler called 'onClickDatePicker' on this div.
This can be called a customDatepicker and be used in other components.

function 'onClickDatePicker' will explicitly set the time to 0000 hours if it is default time(means when no datetime is already set)
it uses a state 'isDefaultTimeInput' to identify  whether default time was set or not.

code example:
  
  <div onClick={this.onClickDatePicker}>
    <DatePicker
        selected={this.props.selectedDatetime}
        onChange={this.onDatetimeChange}
        onSelect={this.props.handleSelectDatetime ? this.onSelectDatetime : () => { }}
        dateFormat={this.props.dateTimeFormat || "dd/MM/yyyy h:mm aa"}
        timeFormat="HH:mm"
        showTimeInput
        disabled={this.props.disabled}
        onClickOutside={this.handleOnClickOutside}
    />
</div>

 //function to set default time as 00:00 in time input.

 onClickDatePicker = () => {
  if (!this.props.selectedDatetime && this.state.isDefaultTimeInput == false) {
            let now = new Date();
            now.setHours(0, 0, 0, 0);
            let openDatetime = (new Date(now));
            this.setState({ isDefaultTimeInput: true });
            this.props.onDatetimeHandler(openDatetime, true);
        }
 }


//function to handle the case when user closes the datepicker without changing the time.
it updates the time back to null in case the isDefaultTimeInput was set true.
handleOnClickOutside = (event) => {
    if (this.state.isDefaultTimeInput) {
        this.setState({ isDefaultTimeInput: false });
        this.props.onDatetimeHandler(null, true);
    }
}


//function to set the selected datetime 
onDatetimeChange = (selectedDatetime) => {
    this.setState({ isDefaultTimeInput: false });
    this.props.onDatetimeHandler(selectedDatetime, false);
}

//function to handle change of date input on selecting any date.
onSelectDatetime = (selectedDatetime) => {
    this.setState({ isDefaultTimeInput: false });
    this.props.onDatetimeHandler(selectedDatetime, false);
}


this solution works fine for me in most cases. 
just one issue that if you are calling any api for updating the time on change /onSelect of the date then
there will be an extra call to set 00:00 time and back.But that too can be resolved with some checks.

Please let me know if it was helpful.

**Comment by neerajtomar98** [comment]
Hi guys,
I resolved this issue by wrapping the Datepicker in a div 
and defining an onclick handler called 'onClickDatePicker' on this div.
This can be called a customDatepicker and be used in other components.

function 'onClickDatePicker' will explicitly set the time to 0000 hours if it is default time(means when no datetime is already set)
it uses a state 'isDefaultTimeInput' to identify  whether default time was set or not.

`<div onClick={this.onClickDatePicker}>
    <DatePicker
        selected={this.props.selectedDatetime}
        onChange={this.onDatetimeChange}
        onSelect={this.props.handleSelectDatetime ? this.onSelectDatetime : () => { }}
        dateFormat={this.props.dateTimeFormat || "dd/MM/yyyy h:mm aa"}
        timeFormat="HH:mm"
        showTimeInput
        disabled={this.props.disabled}
        onClickOutside={this.handleOnClickOutside}
    />
    </div>

 //function to set default time as 00:00 in time input.

 onClickDatePicker = () => {
  if (!this.props.selectedDatetime && this.state.isDefaultTimeInput == false) {
            let now = new Date();
            now.setHours(0, 0, 0, 0);
            let openDatetime = (new Date(now));
            this.setState({ isDefaultTimeInput: true });
            this.props.onDatetimeHandler(openDatetime, true);
        }
 }


//function to handle the case when user closes the datepicker without changing the time.
it updates the time back to null in case the isDefaultTimeInput was set true.
handleOnClickOutside = (event) => {
    if (this.state.isDefaultTimeInput) {
        this.setState({ isDefaultTimeInput: false });
        this.props.onDatetimeHandler(null, true);
    }
}


//function to set the selected datetime 
onDatetimeChange = (selectedDatetime) => {
    this.setState({ isDefaultTimeInput: false });
    this.props.onDatetimeHandler(selectedDatetime, false);
}

//function to handle change of date input on selecting any date.
onSelectDatetime = (selectedDatetime) => {
    this.setState({ isDefaultTimeInput: false });
    this.props.onDatetimeHandler(selectedDatetime, false);
}`
this solution works fine for me in most cases. 
just one issue that if you are calling any api for updating the time on change /onSelect of the date then
there will be an extra call to set 00:00 time and back.But that too can be resolved with some checks.

Please let me know if it was helpful.

**Comment by neerajtomar98** [comment]
> Can we set initial value for time input, while using showTimeInput?
> while initialising with date as null and showTimeInput flag, the time shown in time input shows some random value probably the being added by the browser depending on the current timezone.
> Is there any way by which i can make this input 00:00 instead of default value taken by browser

Hi guys,
I resolved this issue by wrapping the Datepicker in a div 
and defining an onclickHandler called 'onClickDatePicker' on this div.
This can be called a customDatepicker and be used in other components.

function '_onClickDatePicker_' will explicitly set the time to 0000 hours if it is default time(means when no datetime is already set)
it uses a state '_isDefaultTimeInput_' to identify  whether default time was set or not.

`<div onClick={this.onClickDatePicker}>
    <DatePicker
             selected={this.props.selectedDatetime}
             onChange={this.onDatetimeChange}
        onSelect={this.props.handleSelectDatetime ? this.onSelectDatetime : () => { }}
        dateFormat={this.props.dateTimeFormat || "dd/MM/yyyy h:mm aa"}
        timeFormat="HH:mm"
        showTimeInput
        disabled={this.props.disabled}
        onClickOutside={this.handleOnClickOutside}
    />
    </div>

 //function to set default time as 00:00 in time input.
 onClickDatePicker = () => {
  if (!this.props.selectedDatetime && this.state.isDefaultTimeInput == false) {
            let now = new Date();
            now.setHours(0, 0, 0, 0);
            let openDatetime = (new Date(now));
            this.setState({ isDefaultTimeInput: true });
            this.props.onDatetimeHandler(openDatetime, true);
        }
 }


//function to handle the case when user closes the datepicker without changing the time.
it updates the time back to null in case the isDefaultTimeInput was set true.
handleOnClickOutside = (event) => {
    if (this.state.isDefaultTimeInput) {
        this.setState({ isDefaultTimeInput: false });
        this.props.onDatetimeHandler(null, true);
    }
}


//function to set the selected datetime 
onDatetimeChange = (selectedDatetime) => {
    this.setState({ isDefaultTimeInput: false });
    this.props.onDatetimeHandler(selectedDatetime, false);
}

//function to handle change of date input on selecting any date.
onSelectDatetime = (selectedDatetime) => {
    this.setState({ isDefaultTimeInput: false });
    this.props.onDatetimeHandler(selectedDatetime, false);
}`
this solution works fine for me in most cases. 
just one issue that if you are calling any api for updating the time on change /onSelect of the date then
there will be an extra call to set 00:00 time and back.But that too can be resolved with some checks.

Please let me know if it was helpful.

**Comment by neerajtomar98** [comment]
> > Can we set initial value for time input, while using showTimeInput?
> > while initialising with date as null and showTimeInput flag, the time shown in time input shows some random value probably the being added by the browser depending on the current timezone.
> > Is there any way by which i can make this input 00:00 instead of default value taken by browser
> 
> Yes!!! This is exactly what we need too.

try the solution i have written in comments

**Comment by syedmahmad** [comment]
I am having the same issue.
