### ISSUE TITLE
"shouldCloseOnSelect" option is not working with datepicker when time picker enabled

### ISSUE THREAD

**Issue by vincentwongso** [Hacker0x01/react-datepicker#1394]
### Description
`shouldCloseOnSelect` option is not working with datepicker when time picker enabled.

### Expected behavior
Datepicker should not close when `shouldCloseOnSelect` is set to false.

### Actual behavior
Datepicker is closed once you select the time.

### Steps to reproduce
I have created codesandbox below to reproduce the issue.
https://codesandbox.io/s/2w4611793j

**Comment by jwrlee88** [comment]
Running into the same issue, anyone have any progress on this?

**Comment by ArthurBrito** [comment]
@jwrlee88 I am working on it.
I found that `this.setOpen(false) `is being called without checking `shouldCloseOnSelect`.
I added the verification, but I found another problem. After I click the time, the CSS (to show what time is currently selected) is not being applied.
When I have time I will check the problem with CSS and then make a PR.
