### ISSUE TITLE
Pass onClearClick to custom input component? 

### ISSUE THREAD

**Issue by ziweiwu** [Hacker0x01/react-datepicker#1397]
Is there a way to pass `onClearClick` function to the customInput component I am using? Because there is a clear button included in the `TextField`. 

I am trying like this, but it's not working.
```
<DatePicker>
 customInput={<TextField
      label={props.label}
      showClearButton = {props.isClearable}
      onClearButtonClick = {props.onClearClick}
      placeholderText={props.placeholderText}
    />}

</>

```

**Comment by sahaam** [comment]
Any update on this. This seems to be a bug. At least we can pass hideClearButton. There is also no way to call `onClearClick ` from component which is rendering Datepicker as `onClearClick ` is a private instance method.

**Comment by zargold** [comment]
Bump
