### ISSUE TITLE
Time padding is incorrect

### ISSUE THREAD

**Issue by daniyalhussain** [Hacker0x01/react-datepicker#1398]
### Expected behavior
![image](https://user-images.githubusercontent.com/5901712/41195524-1781e448-6c2f-11e8-9afd-836723bed49e.png)
It should look like this

### Actual behavior
![image](https://user-images.githubusercontent.com/5901712/41195530-3334d95c-6c2f-11e8-9eb9-283c0471bb45.png)
But it looks like this

### Steps to reprodcue
So i looked in to it and their is no padding:0 in it so he takes the default ul.

**Comment by imhazige** [comment]
I have the same issue.

**Comment by juhana** [comment]
A temporary fix is to add this CSS:

```
ul.react-datepicker__time-list {
    padding: 0;
}
```

**Comment by imhazige** [comment]
![screen shot 2018-06-21 at 06 52 10](https://user-images.githubusercontent.com/4122902/41688700-bcdb292e-751f-11e8-91a9-220d14aff863.gif)

**Comment by peterswallow** [comment]
It seems to be the `ul.react-datepicker__time-list element`, which inherits from the base 'user agent stylesheet' (in chrome at least) with this class:
`ul, menu, dir {
   padding-inline-start:40px;
}`
Guess we need to reset this to 0px, as mentioned above...
