### ISSUE TITLE
Timepicker 24-hour format in dropdown

### ISSUE THREAD

**Issue by ninjami-matti** [Hacker0x01/react-datepicker#1404]
Using `timeFormat="HH:mm"` changes the input field to the chosen format,

but in the dropdown the times are still in AM/PM format. I have gone through the docs multiple times but I do not see any other props to change the format than "timeFormat".

Example down below: 
**Input field** is in **24 hour format**,
**Dropdown** is in **12 hour format**

Code snippet: 
`<DatePicker showTimeSelect showTimeSelectOnly dateFormat="HH:mm" timeIntervals={30} onChange={ e => handleDateChange(e) } />`

<img width="213" alt="example" src="https://user-images.githubusercontent.com/30185460/41492188-0dfc1124-7106-11e8-8b37-876887de798a.png">

**Comment by ymor** [comment]
Your example shows that you used dateFormat, which formats the input.  You need to set the timeFormat to "HH:mm" to and this will format the dropdown.

**Comment by ninjami-matti** [comment]
I can't believe how I have missed that typo there! I have gone through the documentation and the code and somehow every time failed to see that I was using dateFormat prop. 

Thank you!

**Comment by nielsuit227** [comment]
> Your example shows that you used dateFormat, which formats the input. You need to set the timeFormat to "HH:mm" too and this will format the dropdown.

Thanks alot! I couldn't seem to find a list with possible formats, where did you gather your information?

**Comment by ymor** [comment]
> > Your example shows that you used dateFormat, which formats the input. You need to set the timeFormat to "HH:mm" too and this will format the dropdown.
> 
> Thanks alot! I couldn't seem to find a list with possible formats, where did you gather your information?

Back when I answered this question the library was using moment.js, but now its using date-fns so you can find the formats here: https://date-fns.org/v1.28.5/docs/format

**Comment by yash-aux** [comment]
when i change to the dateFormat to timeFormat working but when I select time showing me today's date how to fix it?
