### ISSUE TITLE
How do we disable certain days of the week?

### ISSUE THREAD

**Issue by pagesrichie** [Hacker0x01/react-datepicker#1409]
How do we disable certain days of the week?

Like for example, say I want to disable Monday and Tuesday.  (Not just weekends)

**Comment by Fer0x** [comment]
@pagesrichie https://reactdatepicker.com/#example-21

**Comment by ahmadzt** [comment]
You may use filterDate props. refer https://reactdatepicker.com/#example-filter-dates. also you need to use `date.getDay()` instead of `getDay(date)`

```
() => {
  const [startDate, setStartDate] = useState(null);
  const isWeekday = (date) => {
    const day = date.getDay();
    return day !== 0 && day !== 6;
  };

  return (
    <DatePicker
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      filterDate={isWeekday}
      placeholderText="Select a weekday"
    />
  );
};
```

**Comment by BrayanTheloveend** [comment]
thanks

**Comment by ashrafnazar** [comment]
Is there a way to exclude the days from appearing in the calendar, i.e. only display Mon-Fri?

**Comment by tetaplaun** [comment]
Same question here, how can we exclude them and also hide them from the calendar?
