### ISSUE TITLE
ERROR: Property 'timeCaption' does not exist on type '(IntrinsicAttributes & IntrinsicClassAttributes<ClassicComponent<ReactDatePickerProps, ComponentS

### ISSUE THREAD

**Issue by yang-wang-wips** [Hacker0x01/react-datepicker#1413]
### Expected behavior
                <DatePicker
                  name="datetime"
                  selected={data.datetime}
                  onChange={(date) => this.onDatePickerChange(date)}
                  locale="de-DE"
                  showTimeSelect
                  timeFormat="HH:mm"
                  timeIntervals={1}
                  dateFormat="DD.MM.YYYY HH:mm"
                  timeCaption="Time"
                  todayButton="Heute"
                />
### Actual behavior
ERROR in [at-loader] ./src/components/DataTable.tsx:520:19
    TS2339: Property 'timeCaption' does not exist on type '(IntrinsicAttributes & IntrinsicClassAttributes<ClassicComponent<ReactDatePickerProps, ComponentS...'.

**Comment by aurerua** [comment]
+1

**Comment by aurerua** [comment]
Same Problem here.

Adding `timeCaption: string` to the interface in `node_modules/@types/react-datepicker` makes it possible to use it but it is no real solution.

Are the type definitions available somewhere, so that a PR can be done?
