### ISSUE TITLE
Edit in <input /> directly does not trigger onChange?

### ISSUE THREAD

**Issue by yang-wang-wips** [Hacker0x01/react-datepicker#1414]
### Expected behavior
change the time in the input will trigger onChange.
### Actual behavior
I tried to type and change the time in the input, which didn't trigger onChange.

**Comment by yang-wang-wips** [comment]
I mean, I tried to type and change the time in <input />

**Comment by jslegers** [comment]
I experienced the same issue.
This is very annoying!

**Comment by bvanderdrift** [comment]
Did you make sure to put in the date in the correct format? This is currently working on my machine. onChange will not trigger if the format is incorrect or is an invalid date.

**Comment by jslegers** [comment]
> `onChange` will not trigger if the format is incorrect or is an invalid date.

I guess that's the problem, at least in my case.

I want to use the `onChange` to validate the input when user types something into the text field manually and reset the text field when validation fails.

Without the `onChange` getting fired, the text field pretty much accepts any input when the user types something into it and I have no idea of validating that input.

Is there perhaps another way to achieve this?

**Comment by bvanderdrift** [comment]
[There is a `onChangeRaw` property ](https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md). I guess you could use that to get any input that comes in and validate it yourself. I imagine it returns the normal event from the `input` element with the value in string format but did not verify that.

**Comment by jslegers** [comment]
The `onChangeRaw` event is triggered every time a single character is typed. 

This is ill-suited for date fields, because when typing eg. 05/05/2018 manually, you'll have an invalid date the first 9 times the event is triggered. You have a valid date only when the 10th and last character is typed. And there is no way of knowing from this event handler when the last character is typed.

The `onBlur` would be a better fit, as it is triggered only when leaving the field. 

I'm not sure what would be the right way to validate & format, though, when using `onBlur`.

**Comment by bvanderdrift** [comment]
I have created an issue (#1464) to discuss a callback to notify users of an invalid date being given. What I needed was reactively show a message as long as the given input is an invalid date. 

You can see at https://github.com/Hacker0x01/react-datepicker/blob/master/src/date_utils.js#L66 how this library validates dates. You could use the same implementation to do validation yourself. In a nutshell: it will only strictly accept issues that adhere to the `ISO-8610` standard. What I did personally is write a wrapper around the current `DatePicker` which exposes extra callbacks on which I can base whether the typed Date is valid or not.

**Comment by jslegers** [comment]
@bvanderdrift :

> You can see at https://github.com/Hacker0x01/react-datepicker/blob/master/src/date_utils.js#L66 how this library validates dates. You could use the same implementation to do validation yourself.

Doesn't have to implement your own validation behavior kind of defeat the purpose of using components like react-datepicker?

> it will only strictly accept issues that adhere to the `ISO-8610` standard.

Just... why?

It's so counter-intuitive to have to use a format that's different from the format used by the date-picker.

> What I did personally is write a wrapper around the current DatePicker which exposes extra callbacks 

I'm already doing that. 

Unfortunately, that's not really making things any easier.

> on which I can base whether the typed Date is valid or not.

In which handler should I put my validation code?

And how should I update the textbox's content if the validation fails?

This is what my `DateTimeFieldInput` module currently looks like : 

````tsx
**import * as moment from "moment";
import * as React from 'react';
import {default as ReactDatePicker} from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import {DateTimeField, DateTimeFieldValue, ServiceConfigurationField} from "../model/serviceconfig";

require("./_datetimefieldinput.scss");

const DATEFORMAT: { [precision: string]: string } = {
  year: "YYYY",
  month: "MM-YYYY",
  week: "DD-MM-YYYY",
  day: "DD-MM-YYYY",
  hour: "DD-MM-YYYY",
  minute: "DD-MM-YYYY"
};

const TIMEFORMAT: { [precision: string]: (boolean | string) } = {
  year: false,
  month: false,
  week: false,
  day: false,
  hour: "HH:mm",
  minute: "HH:mm"
};
const DEFAULT_FORMAT = "day";
const MINIMUM_TIME_INTERVAL = 15;

interface DateTimeFieldInputProps {
  field: DateTimeField;
  value: DateTimeFieldValue;
  onChange: (newValue: DateTimeFieldValue, sourceField: ServiceConfigurationField) => void;
}

export class DateTimeFieldInput extends React.Component<DateTimeFieldInputProps, {}> {

  shouldComponentUpdate(nextProps: DateTimeFieldInputProps, nextState: {}) {
    return this.props.onChange !== nextProps.onChange ||
           this.props.field !== nextProps.field ||
           this.props.value !== nextProps.value;
  }

  handleChange = (changedDate: moment.Moment) => {
    const {field, onChange} = this.props;
    if (changedDate) {
      //pass date back as a string, but make sure no date info is lost (use a ISO-8601 string)
      onChange(changedDate.format(), field);
    } else {
      onChange("", field);
    }
  }

  handleChangeRaw = (event: React.FocusEvent<HTMLInputElement>) => {
    const {field, onChange} = this.props;
    const newValue = moment((event.target as HTMLInputElement).value, this.getFormat(), 'en', true);
    if (newValue.isValid()) {
      onChange(newValue.format(), field);
    }
  }

  getPrecision() {
    return this.props.field.precision || DEFAULT_FORMAT;
  }

  getFormat() {
    const precision = this.getPrecision();
    const timeformat = TIMEFORMAT[precision];
    return timeformat ? DATEFORMAT[precision] + ", " + TIMEFORMAT[precision] : DATEFORMAT[precision];
  }

  render() {
    const {field, value} = this.props;
    const date = !value ? null : moment(value);
    const precision = this.getPrecision();
    const dateformat = DATEFORMAT[precision];
    const timeformat = TIMEFORMAT[precision];
    const timeinterval = precision === "minute" ? MINIMUM_TIME_INTERVAL : 60;

    const dateInput = {} as any;
    if (field.includeDates && field.includeDates.length) {
      dateInput.includeDates = field.includeDates.map(d => moment(d))
    } else if (field.range) {
      const {min, max} = field.range;
      dateInput.minDate = min ? moment(min) : null;
      dateInput.maxDate = max ? moment(max) : null;
    }

    return (
        <div className="datepicker-container">
          <ReactDatePicker selected={date}
                           onChange={this.handleChange}
                           onChangeRaw={this.handleChangeRaw}
                           value={date ? date.startOf(precision).format(this.getFormat()) : ""}
                           isClearable={true}
                           todayButton={"Today"}
                           showMonthDropdown={true}
                           showYearDropdown={true}
                           scrollableYearDropdown={true}
                           showTimeSelect={!!timeformat}
                           dateFormat={dateformat}
                           timeIntervals={timeinterval}
                           timeFormat={(timeformat || "") as string}
                           className="form-control"
                           placeholderText="Please pick a date"
                           id={field.id}
                           name={name}
                           {...dateInput}
          />
        </div>
    );
  }
}
````

I've spent hours tinkering with this, but I'm not getting anywhere close.
Everything I try seems to break more than it fixes...

**Comment by bvanderdrift** [comment]
> Doesn't have to implement your own validation behavior kind of defeat the purpose of using components like react-datepicker?
I feel that is always your own consideration. I personally do like the flexibility of the picker itself, and think it could be improved by some validation logic. If there is no need of visual validation (since internally it is validated) the component is still useful.

> It's so counter-intuitive to have to use a format that's different from the format used by the date-picker.
I have to correct myself on the `ISO-8610` thing I said. I now see that it will just accept a date with *trailing 0's* and in the localization of your choosing. So if it prints `08-08-2010` it will also accept input like that and not as `08/08/2010`, it will also not accept `8-8-2010`.

Regarding your code:
I don't fully get the functionality of this wrapper, are you parsing the `moment` value to a string? So that you only have to interact with the `ReactDatePicker` with strings? I think that it's fine to pass around the `moment` object through which you have way more flexibilty with the date. This way you keep as close as possible to the source of truth.

Also, I don't see the use of the `shouldComponentUpdate` call you're doing. Why don't you let the `ReactDatePicker` do that? In my exprience `shouldComponentUpdate` is causing bugs to appear, and I just normally trust the React logic to do that job properly.

I also have to admit I didn't take the time to completely root out your code but these are the first things that stand out to me. Also if you want to know when an input is not value you need to expose some kind of callback that notifies a parent. Currently you only trigger the callback when `isValid()` returns `true`, but do nothing when it returns `false`.

**Comment by jslegers** [comment]
> I have to correct myself on the `ISO-8610` thing I said. I now see that it will just accept a date with _trailing_ 0's and in the localization of your choosing. So if it prints `08-08-2010` it will also accept input like that and not as `08/08/2010`, it will also not accept `8-8-2010`.

I just verified that that is indeed the case.

Still pretty useless, though, without a way to guarantee that users enter dates in the correct format.

> I don't fully get the functionality of this wrapper, are you parsing the `moment` value to a string?

I'm working on an app where fields can be added, modified or removed based on configuration in a JSON file or service.

The configuration of a `DATETIME` field would look something like this : 

````json
{
  "type": "DATETIME",
  "id": "testdate",
  "precision" : "hour",
  "range" : {
    "min": "2018-03-19T07:22+02:00",
    "max": "2020-03-19T07:22+02:00"
  },
  "label": {
    "message": "A date field"
  },
  "help": {
    "message": "Shows you how to add a date field"
  }
}
````

The `DateTimeFieldInput` wrapper acts as an abstraction on top of `ReactDatePicker`, to add the proper properties based on the JSON config.

> Also, I don't see the use of the `shouldComponentUpdate` call you're doing. Why don't you let the `ReactDatePicker` do that? 

To be honest, I don't know either. That part of the code was written by a colleague of mine, who is sort of the React "expert" in our team. I'm still in the process of getting used to React and trying to wrap my head around some of its more esoteric behavior. And unfortunately, my colleague is on holiday this week.

> In my exprience `shouldComponentUpdate` is causing bugs to appear, and I just normally trust the React logic to do that job properly.

I guess I'll have to ask my colleague when he returns from holiday why he doesn't trust the React logic to do that job properly.

> Also if you want to know when an input is not value you need to expose some kind of callback that notifies a parent. Currently you only trigger the callback when `isValid()` returns `true`, but do nothing when it returns `false`.

So I should add something like an `onInvalidInput` callback to my `DateTimeFieldInput` component in the parent component & call that callback when `isValid()` returns `false`?

**Comment by bvanderdrift** [comment]
Ok, then I get why you do the manual converting!

> So I should add something like an `onInvalidInput` callback with validation logic to my `DateTimeFieldInput` component in the parent component & call that callback when `isValid()` returns false?

This is exactly what I have done and works nice. Ultimatly I wish this would be native functionality (to some extend) in the `react-datepicker`. I just made a very basic solution so there might be a better solution if someone puts in more brainpower, but for me this works now.

If you want to have it in the component itself always feel free to submit a PR to implement it.

**Comment by shuhei** [comment]
Here is my two cents. `onChangeRaw()` and manual validation with `moment(str, format).isValid()` work for me well. (You can ignore the `timeZone` if you don't care.)

```js
const DATE_FORMAT = "DD/MM/YYYY - HH:mm";

<DatePicker
  onChangeRaw={event => {
    // Read a value from the text field.
    // https://github.com/Hacker0x01/react-datepicker/issues/1414
    const date = moment(event.target.value, DATE_FORMAT).tz(timeZone);
    if (date.isValid()) {
      setValue(date);
    }
  }}
  dateFormat={DATE_FORMAT}
  {...otherProps}
/>
```

**Comment by SivaGanesh56** [comment]
@jslegers any breakthrough ?
