### ISSUE TITLE
Calendar focus after selecting date

### ISSUE THREAD

**Issue by charliearlie** [Hacker0x01/react-datepicker#1416]
### Expected behavior
The calendar should lose focus after the date has been selected. Or at least give the developer the option to remove focus

### Actual behavior
After a calendar selection is made the focus remains on the calendar. If you then switch to another browser tab and back again, the calendar pops up again because it has retained focus.

### Steps to reproduce
Steps are in actual behavior

Gif attached

![datepicker](https://user-images.githubusercontent.com/7570492/42280642-391b6d4a-7f99-11e8-9b01-24b0672e4031.gif)

**Comment by jothi-pyt** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/771 Please check out the response here.
