### ISSUE TITLE
Which prop should I used when I want to add icon inside the datepicker

### ISSUE THREAD

**Issue by iovoz** [Hacker0x01/react-datepicker#1422]
Which prop should I used when I want to add icon inside the datepicker? Just like the bootstrap, a small icon inside the input tag.

**Comment by qweluke** [comment]
@symbiane have you figured it out?

**Comment by jaspreetsingh2701** [comment]
How to use any custom Icon?

**Comment by billychan** [comment]
There is a `customInput` prop, you can use any custom input there, for example InputGroup with text or icon from Bootstrap.
