### ISSUE TITLE
Add Ability to open DatePicker from onKeyDown with developer specified buttons.

### ISSUE THREAD

**Issue by JakeLaCombe** [Hacker0x01/react-datepicker#1426]
### Expected behavior
We have the need for the datepicker to follow this design, which we currently use by creating a custom input, and passing onKeyDown to the calendar button.

<img width="174" alt="screen shot 2018-07-17 at 9 49 28 am" src="https://user-images.githubusercontent.com/2552573/42825140-fc01d0c6-89a6-11e8-84c1-88a50edb2c13.png">

It looks like to that in order to open the datepicker on keypress that the user needs to press ArrowUp or ArrowDown (https://github.com/Hacker0x01/react-datepicker/blob/master/src/index.jsx#L441). This doesn't work with accessibility needs, as that requires being able to toggle the datepicker with either the space or the enter key.

Our Proposal is to allow for customization of what buttons can be used to toggle the opening and closing of the datepicker. We can keep the default keys to what is existing so that the change is passive.

**Comment by yuderekyu** [comment]
Have any feedback on this proposal?
