### ISSUE TITLE
How to assign date to selected property when there are multiple DatePickers in a single page?

### ISSUE THREAD

**Issue by bharathitm** [Hacker0x01/react-datepicker#1431]
I have a page where I am creating multiple DatePickers dynamically depending on data returned from the database. The DatePickers are getting rendered correctly but I'm unable to change the dates. Even if I select a date, it does not change. How to handle this scenario?

**Comment by bhupesh-sf** [comment]
I am doing the similar thing but the issue I am facing is I select date on one it shows the same on all other DatePicker instances as well.

Any solution for that?
