### ISSUE TITLE
month dropdown's format should be configurable

### ISSUE THREAD

**Issue by herrherrmann** [Hacker0x01/react-datepicker#1436]
### Expected behavior
I want to use a custom format for the month dropdown (via `showMonthDropdown`), to e.g. include the year in it.

If I use `showMonthYearDropdown`, I'm forced to specify a `minDate` and `maxDate` (which I don't want to do).

Maybe there should be an independent prop for the month dropdown to achieve this (e.g. `dateFormatMonthDropdown="MM YYYY"`)? This way `useShortMonthInDropdown` could be deprecated and replaced with the more flexible dateFormatMonthDropdown.

### Actual behavior
No configurability of the month dropdown (except for the global `dateFormat` which seems to influence the month formatting somehow?).

### Related
#1183

**Comment by brendonco** [comment]
I agree, I'm also using ```showMonthYearDropdown``` and was force to specify ```minDate``` and ```maxDate```.  Is there a way to not specify  ```minDate``` and ```maxDate```?

**Comment by herrherrmann** [comment]
This is still an issue! ☝️

**Comment by herrherrmann** [comment]
This is still an issue! ☝️

**Comment by herrherrmann** [comment]
This is still an issue! ☝️
