### ISSUE TITLE
Datepicker does not open with readOnly=true

### ISSUE THREAD

**Issue by kevcodez** [Hacker0x01/react-datepicker#1443]
### Expected behavior

Datepicker opens, when a user clicks in the input.

### Actual behavior

Datepicker does not show up.

### Steps to reproduce

1. Use latest version of Chrome
2. Navigate to https://reactdatepicker.com/#example-25 > Read only datepicker
3. Click in the input

**Comment by symbiane** [comment]
<DatePicker
                            selected={this.state.activitySelectedDate}
                            onChange={this.handleActivityDateChange}
                            includeDates={dates}
                            showDisabledMonthNavigation
                            dateFormat="YYYY-MM-DD"
                            readOnly
                        />

**Comment by symbiane** [comment]
`<DatePicker
                            selected={this.state.activitySelectedDate}
                            onChange={this.handleActivityDateChange}
                            includeDates={dates}
                            showDisabledMonthNavigation
                            dateFormat="YYYY-MM-DD"
                            readOnly
                        />`

**Comment by flynorc** [comment]
experiencing the same problem here. After updating to 1.6.0 the readOnly attribute seems to be causing the datepicker to not open. There are no errors in console or any other errors, it just does not open.

tried `readOnly={true}` and `readOnly` none seem to work.
Removing the attribute makes it work again (but users are able to type into the field then)

**Comment by flynorc** [comment]
looking at some other issues, I found this one:
https://github.com/Hacker0x01/react-datepicker/issues/1418
it seems like that is the reason for the new behaviour.

**Comment by kevcodez** [comment]
Solved it by using `onKeyDown={e => e.preventDefault()}`

**Comment by flynorc** [comment]
did the same thing, and then also needed to add
`autoComplete="off"`
to prevent chrome from showing the previously selected options

**Comment by pniebrzydowski** [comment]
@kevcodez Unfortunately disabling keydown is problematic, as it removes all access to the keyboard which completely eliminates accessibility for the form. You can no longer tab away from the field, you can't use the keyboard to select the date, etc.

**Comment by flynorc** [comment]
anyone has an idea on how i could prevent the "soft keyboard" showing on android (and other mobile devices) when clicking on the input field that has the datepicker?

**Comment by charmstead** [comment]
Try this. works for me

```
const CustomInput = (props) => {
    return (
        <input
            className={[classes.TransparentInput, "uk-input"].join(" ")}
            onClick={props.onClick}
            value={props.value}
            type="text"
            readOnly={true}
        />
    )
}
<DatePicker
  customInput={<CustomInput />}
  name={'from'}
  value={values['from']}
  onChange={e => setFieldValue('from', moment(e).format('L'))}
 />
```

**Comment by vaanskii** [comment]
i found this now and i had same issue the easiest way i think its to add this

onKeyDown={(e) =>
  e.preventDefault();
 }}
autoComplete="off"
