### ISSUE TITLE
Calendar is traped inside the button menu

### ISSUE THREAD

**Issue by jesusaries** [Hacker0x01/react-datepicker#1451]
Hi im new in react and i have this problem, i made a custom button that when is clicked it should display the datepicker and well it does it, the problem is that it is trapped inside the menu of the button, and what i need is it to popout outside the menu (actually i need to close the menu when selected and just see the datepicker) 

any kind of help would be apreciated

![btn](https://user-images.githubusercontent.com/42280580/43976343-18b1b668-9c95-11e8-8ae8-dead9c437e5b.png)
![btn2](https://user-images.githubusercontent.com/42280580/43976348-1b0f8c46-9c95-11e8-9add-2c89dbae55ee.png)

as you can see my datepicker is inside a menu

this is my menu code
`      <Menu

        className="main-toolbar__menu"
        anchorEl={this.state.anchors.options_settings}
        open={Boolean(this.state.anchors.options_settings)}
        onClose={() => this.handleDropdownClose('options_settings')}
      >
        <MenuItem
          onClick={() => {
            this.toggleCalendar()     
          }}
        >
        <DatePicker
          customInput={<ExampleCustomInput />}
          selected={this.state.startDate}
          onChange={this.handleChange} 
        />
        </MenuItem>
        <MenuItem
          onClick={() => {
            this.handleModal('addNotificationModal', true)
            this.handleDropdownClose('options_settings')
          }}
        >
          <span>Notification Preferences</span>
        </MenuItem>
      </Menu>`

**Comment by evangow** [comment]
You might want to check out the "Inline portal version" in the docs

https://reactdatepicker.com/

**Comment by smithaitufe** [comment]
In my case, when the button is clicked, it does not show the datepicker. Rather it shows an input control which must be clicked to launch the Datepicker. Please what is the expected behaviour? 
The sample in the doc works fine. So what is wrong?

```js
<div className="field">
          <div className="control">
            <button 
            className="button is-outline"
            onClick={this.toggleCalendar}>{this.state.birthDate ? this.state.birthDate.format("DD-MM-YYYY") : "Birth Date"}</button>
            {this.state.isDatePickerOpen && (<DatePicker
            selected={this.state.birthDate}
            onChange={this.handleChange}
            withPortal/>)}
          </div>
        </div>
// handlers
handleChange = date => {
    this.setState({birthDate: date})
    this.toggleCalendar()
  }
  toggleCalendar = (e) => {
    e && e.preventDefault()
    this.setState({isDatePickerOpen: !this.state.isDatePickerOpen})
  }
```
