### ISSUE TITLE
Inline Portal won't close on 'escape'

### ISSUE THREAD

**Issue by evangow** [Hacker0x01/react-datepicker#1453]
Great library! This has been extremely helpful to me! 🙂

### Expected behavior
On the Inline Portal version (needed in order to provide a custom input with portal)
- hit 'escape' => portal should close
- hit arrow keys => date selected should change

### Actual behavior
- hit 'escape' => nothing happens
- hit arrow keys => nothing happens

### Steps to reproduce
You can see this under the Inline Portal version in the example from the documentation
https://reactdatepicker.com/

I tried to handle the key presses myself, but if you add the `onKeyDown` prop with a function when you set the `inline` prop, the function passed to `onKeyDown` will not be called.

**Comment by ryanleland** [comment]
Direct link https://reactdatepicker.com/#example-30

**Comment by mtford90** [comment]
Also - can't click the backdrop to escape with inline/portal either.
