### ISSUE TITLE
1.6.0  Input Click problem

### ISSUE THREAD

**Issue by uurcankaya** [Hacker0x01/react-datepicker#1455]
### Expected behavior
Datepicker does not pop upon input click, works on 1.5.0

### Steps to reproduce

`<DatePicker
         customInput={TimepickerInput}
         minDate={moment.tz()}
         selected={this.state.scheduledAt}
         onChange={(e) =>this.setScheduleTime(e)}
         showTimeSelect
         timeIntervals={5}
         dateFormat="LLL"
         isClearable={false}
         placeholderText="Click to select a date"
         preventOpenOnFocus
         readOnly
         todayButton={`${tmz}`}
          />`

**Comment by jacekk** [comment]
You have `readOnly` property which changed behavior in https://github.com/Hacker0x01/react-datepicker/pull/1419 . Don't ask me why it works like that right now ;) Or ... **does not work** ... to be more exact :/

**Comment by bcullman** [comment]
If you want your users to *only* use the calendar control and not the input field, you need to use an alternate method for blocking text input - read-only has a defined meaning, per W3C - it specifies the value can not be edited by the user. see

https://www.w3.org/TR/html401/interact/forms.html#adef-readonly
