### ISSUE TITLE
Module not found: Can't resolve 'moment' in '/Users/xxx/react/project_name/node_modules/react-datepicker/es'

### ISSUE THREAD

**Issue by rsouthpaw** [Hacker0x01/react-datepicker#1457]
I installed the momentjs using "npm i react-moment --save"
My moments js is installed in node_modules/react-moment
Should I import
import moment from 'react-moment';
or 
import moment from 'moment'; (this is given in example)
Although both are not working, I get the same error!

### Expected behavior
Should be able to import react correctly

### Actual behavior
Gives module not found error

### Steps to reproduce
Installed datepicker using npm
installed momentjs using npm
Still getting this error

**Comment by a-x-** [comment]
Did you restarted your builder watch mode?

**Comment by martijnrusschen** [comment]
Moment.js was removed in #1527, starting v2.0.0, this package doesn't use Moment anymore.
