### ISSUE TITLE
Disabled prop not working correctly

### ISSUE THREAD

**Issue by skurger** [Hacker0x01/react-datepicker#146]
It seems that the disabled property is not working as it was when I submitted my pull request.  The input should have the disabled HTML property and not allow the input to have focus.  This is no longer the case.

**Comment by martijnrusschen** [comment]
Yep, this is a bug. Looks like the disabled isn't propagated to the input itself. Could probably be fixed by adding a `disabled={this.props.disabled}` in the `date_input.jsx` file around line 80.

**Comment by skurger** [comment]
I can fix this later today.  That property was removed from the input sometime after my branch was merged.

**Comment by martijnrusschen** [comment]
Sorry about that! Thanks for fixing though!
