### ISSUE TITLE
Suggested: onInvalidDate callback

### ISSUE THREAD

**Issue by bvanderdrift** [Hacker0x01/react-datepicker#1464]
Currently when someone inserts a date string which is not `ISO-8610` formatted the DatePicker will not trigger `onChange`. Currently when one wants to check if the user types in input but it is not valid, that person has to use `onChangeRaw` to check and validate themselves.

A possible use case could be to give feedback to the user that the date string is invalid. One can input an invalid date could happen during an autofill of a form where the application performing the autofill is in a different locale as the DatePicker.

The current solution is duplicate work for users of this library as well as bug-sensitive if this library will ever change its way of validating a date.

Therefore I would suggest something along the lines of an `onInvalidDate` callback. This callback could even provide what is wrong in the given string using `moment#parsingFlags` or `moment#invalidAt`. See the [moment documentation](http://momentjs.com/docs/#/parsing/is-valid/).

This way users can gracefully handle the case when the user manually inputs a date in the wrong format or invalide date.

**Comment by jslegers** [comment]
> Currently when someone inserts a date string which is not `ISO-8610` formatted the DatePicker will not trigger `onChange`. 

`ISO-8610`? That doesn't make sense.

If the date in the textfield is formatted like `MM/DD/YYYY`, the text field should by default accept dates formatted as `MM/DD/YYYY`.
If the date in the textfield is formatted like `DD-MM-YYYY`, the text field should by default accept dates formatted as `DD-MM-YYYY`.

It's totally counter-intuitive to have to input a date in `ISO-8610` if dates selected by the picker are displayed as `MM/DD/YYYY`.
