### ISSUE TITLE
Documentation is lacking

### ISSUE THREAD

**Issue by xehpuk** [Hacker0x01/react-datepicker#1468]
The component "documentation" lists the available props. Since most of them are missing a description, it's a bit of trial and error to use them correctly.

**Comment by a-x-** [comment]
+

I wanna props api doc.
examples are not cover all the cases

e.g. isOpen doc is missed

**Comment by rendall** [comment]
I would like the documentation to answer the question: how does one get a blank field to start?

**Comment by karlkras** [comment]
I would like documentation that would address a huge number of nebulous usage challenges. Using this github repo for technical questions is mostly unhelpful and getting very little notice from any existing knowledgeable devs.

**Comment by vamshi9666** [comment]
it is super hard to predict the arguments and use them without docs. i really appreciate to have written documentation

**Comment by martijnrusschen** [comment]
https://reactdatepicker.com/ contains a lot of examples, is this what you're looking for?

**Comment by xehpuk** [comment]
@martijnrusschen To me, it's not.

**Comment by martijnrusschen** [comment]
Can you be a little bit more descriptive about what you would like to see?

**Comment by xehpuk** [comment]
I'd like to see a description of every prop in the [docs folder](../tree/master/docs).
I can't exactly remember what I needed when I created the issue.
The examples only describe how to achieve specific scenarios. The list is obviously not exhaustive.
Most of the props are not used in the examples. `adjustDateOnChange`, `clearButtonTitle`, `customInputRef` …

**Comment by a-x-** [comment]
WAT?
