### ISSUE TITLE
ReadOnly props is not working

### ISSUE THREAD

**Issue by ali-master** [Hacker0x01/react-datepicker#1469]
### Expected behavior
I added readOnly props to datePicker component but when I using this props, then the component is not working but if I remove it, it's working.
NOTE: This problem was not available before.
### Actual behavior
I should be work with datePicker while it has readOnly props.

**Comment by pniebrzydowski** [comment]
My solution was to utilize the `customInput` property and create a new component which will ignore any change to the value if the entry is not a valid moment object. This way if the user inputs anything in the keyboard, the change will be rejected, but if the input accepts a selection in the datepicker, it will be passed through as a moment object and update the value accordingly.

Code for the component:
```
import React from 'react';
import PropTypes from 'prop-types';
import moment from 'moment';

class DateOnlyInput extends React.Component {
    constructor(props) {
        super(props);
        this.checkIfDate = this.checkIfDate.bind(this);
    }

    checkIfDate(date) {
        if (!moment.isMoment(date)) return;
        this.props.onChange(date);
    }

    render() {
        const props = {...this.props};
        delete props.onChange;
        return (
            <input type="text" onChange={this.checkIfDate} {...props} />
        );
    }
}

DateOnlyInput.propTypes = {
    onChange: PropTypes.func,
};

export default DateOnlyInput;
```

Then I just input this into the `customInput` in my `DatePicker` component, and the component works properly again without using the `readOnly` property. 
```
<DatePicker
    ...
    customInput={<DateOnlyInput />}
/>
```

I still see this as more or less a hack and a bunch of additional unnecessary code, and that this is exactly how it should function (and has in the past) when `readOnly` is true, but at least it seems to function as needed, and all keyboard functionality is retained. Hopefully the previous "fix" for read-only will be reverted.

**Comment by pniebrzydowski** [comment]
For some reason this was changed in https://github.com/Hacker0x01/react-datepicker/pull/1419

Here's the solution I came up with: https://github.com/Hacker0x01/react-datepicker/issues/1443#issuecomment-416531351

**Comment by whatisaphone** [comment]
The change in #1419 broke us as well. I'm also in favor of reverting it. Until then, here is our workaround:

```js
const ForceReadOnlyInput = React.forwardRef((props, ref) => (
  <input {...props} ref={ref} readOnly={true} />
));

<ReactDatePicker
  customInput={<ForceReadOnlyInput />}
/>
```
