### ISSUE TITLE
DatePicker automatically regains focus when clicking on a react-select component

### ISSUE THREAD

**Issue by shiftsave** [Hacker0x01/react-datepicker#1471]
I can't quite figure out what the issue is, but hide on click outside seems to bug out when I click on a [react-select](https://github.com/JedWatson/react-select) component. Clicking any other element works as expected.

![selectionbug](https://user-images.githubusercontent.com/1121873/44752844-4d416280-aaea-11e8-80c3-f2bf75952c45.gif)

**Comment by rafeememon** [comment]
#730

**Comment by shiftsave** [comment]
thanks!

**Comment by samthomson** [comment]
@rafeememon if this issue is solved please mention in what release so others coming to the problem know which version to upgrade to :+1:
