### ISSUE TITLE
Inconsistent date produced when selecting with mouse click versus keyboard selection

### ISSUE THREAD

**Issue by Android3000** [Hacker0x01/react-datepicker#1484]
### Expected behavior
Clicking a date, and selecting the date with the keyboard arrow keys + enter should yield the same date object.

### Actual behavior
When clicking a date, the yielded date object has the time component set to **midnight**.

When selecting a date with keyboard navigation + the enter key, the yielded date object has the time component set to **current time**.

### Steps to reproduce
https://codesandbox.io/s/vmy1v65m60

Select a date via mouse click, and then via keyboard selection + enter key and notice the output of the date.

**Comment by coreylight** [comment]
This is still an issue today. Reproduced with current code on the doc website.

https://user-images.githubusercontent.com/1470090/103685652-354c3a00-4f53-11eb-83cb-a51e06fe8198.mp4
