### ISSUE TITLE
Error when trying to use arrow keys for navigation

### ISSUE THREAD

**Issue by himynameisdave** [Hacker0x01/react-datepicker#1485]
### Expected behavior

I expect to be able to use the arrow keys (specifically left & right) to highlight a new "selected" date when the datepicker is open (like in the examples).

### Actual behavior

I get an error when trying to use the arrow keys when the input field is in focus.

### Steps to reproduce

Here is the code I am using which produces the error, along with a little gif of the error happening:

```jsx
import React from 'react';
import DatePicker from 'react-datepicker';
import moment from 'moment';


const MyComponent = (props) => (
    <DatePicker
        className="calendar-input__datepicker js-test-calendar-input"
        dateFormat="MMM D, YYYY"
        onChange={props.onDateChange}
        selected={this.props.date ? moment(props.date) : null}
        placeholderText={props.placeholder}
        minDate={props.minDate}
        maxDate={props.maxDate}
    />
);

MyComponent.defaultProps = {
    date: null,
    minDate: null,
    maxDate: null,
};

export default MyComponent;
```

![react-datepicker](https://user-images.githubusercontent.com/4298089/45457711-2c117200-b6a5-11e8-96e2-0bfbf6674576.gif)

[This is the line of source code from which the error originates](https://github.com/Hacker0x01/react-datepicker/blob/db6f040131c04409c9407df148775fa6a414edf7/src/date_utils.js#L285).

---

Wondering if maybe I am just missing a prop or if it's a real bug? Any insight/ideas would be greatly appreciated by me and my team. For the time being, we have applied the `disabledKeyboardNavigation` prop, which gets around the issue, however now we lose keyboard navigation, which kinda sucks.

**Comment by joeflynn** [comment]
I'm experiencing the same error on keyboard navigation. If I remove `minDate` and `maxDate`, the error disappears and keyboard navigation starts working again. I feel like the two are probably related since @himynameisdave is also passing those props.
