### ISSUE TITLE
Any way to add scrollbar for time picker?

### ISSUE THREAD

**Issue by GreenDavidA** [Hacker0x01/react-datepicker#1488]
Is there any way to add a scrollbar for the time picker? Currently, only a few hours are shown in the date picker, and the only way that other times can seemingly be entered is via the keyboard. Am I missing a setting?

**Comment by roryza** [comment]
If you have a mouse with a scroll wheel or are using a touch device you should be able to scroll.
To get a scroll bar you can try adding styles like this on the page. There's probably a way to pass down a style or a class somehow, but this works well enough for me.
`.react-datepicker__time-container .react-datepicker__time .react-datepicker__time-box ul.react-datepicker__time-list {
    overflow-y: visible;
}`

**Comment by GreenDavidA** [comment]
That did it. Thank you!
