### ISSUE TITLE
Popper not displaying correctly

### ISSUE THREAD

**Issue by Gwith** [Hacker0x01/react-datepicker#1489]
When using Datepicker with time only (showTimeSelect, showTimeSelectOnly) I'm getting unexpected results:

                <DatePicker
                  selected={this.props.startDate}
                  onChange={this.props.handleChange}
                  withPortal
                  showTimeSelect
                  showTimeSelectOnly
                  timeIntervals={15}
                  dateFormat="LT"
                  timeCaption="Time"
                />

### Expected behavior
[Here](https://i.imgur.com/1C5sk0e.png) is a screenshot of what the Component should look like when rendered to the DOM. 

### Actual behavior
[This](https://i.imgur.com/lydgvp3.png) is the result when used. As you can see the popper is being cutoff some how.

### Steps to reproduce
If it matters I have this component embedded into a table, an example is shown below:

       <table>
      <thead>
        <tr>
          <td>header</td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <DatePicker
              selected={this.props.startDate}
              onChange={this.props.handleChange}
              showTimeSelect
              showTimeSelectOnly
              timeIntervals={15}
              dateFormat="LT"
              timeCaption="Time"
            />
          </td>
        </tr>
      </tbody>
    </table>

What might be the issue that is causing the popper window to not display correctly?

**Comment by JacoGasp** [comment]
A workaround is to add to `index.css` the following
```
.react-datepicker__time-container .react-datepicker__time .react-datepicker__time-box ul.react-datepicker__time-list {
    padding: 0px
}
```
