### ISSUE TITLE
Can react-datepicker adapt to dayjs?

### ISSUE THREAD

**Issue by taoweicn** [Hacker0x01/react-datepicker#1490]
react-datepicker's peer dependency momentjs is so big, even bigger than react-datepicker itself.
Can you consider adapting [dayjs](https://github.com/iamkun/dayjs), it's 2KB size and alternative to Moment.js with the same API.

**Comment by ahmadalfy** [comment]
Even better I think [date-fns](https://date-fns.org/)

**Comment by logeshwaran1998** [comment]
Hi, Can we use dayjs in react-date picker?  

If Yes. Please suggest the solution here. Thanks

**Comment by thinhbg2812-2** [comment]
lol, literally if u cant use date-fns, dont use this =))
