### ISSUE TITLE
Custom labels to days

### ISSUE THREAD

**Issue by b7hamilton** [Hacker0x01/react-datepicker#1492]
I'd like to be able to add custom labels to the days underneath the number. For example 'Available', 'Unavailable' based on whether the day is disabled or not.

I am happy to make this change and submit a pull request, please advise if this is ok?
This would just be an optional prob for the availableLabel and another for disabledLabel so will not conflict with anything else at the moment

**Comment by saunders1989** [comment]
https://github.com/Hacker0x01/react-datepicker/pull/1356 is a much better approach

**Comment by b7hamilton** [comment]
This is perfect - thanks!
