### ISSUE TITLE
Question: Is input user customizable?

### ISSUE THREAD

**Issue by karlkras** [Hacker0x01/react-datepicker#1496]
Before forking and hacking on this myself, I have a requirement for the input to contain a calendar icon along with the normal entry input, so basically a span that tacks on a small icon to the right of the input.
Any current available hook to accomplish this?

**Comment by aij** [comment]
See the `customInput` prop...

We're using a button with a small calendar icon to the right of the input, rendered outside react-datepicker. Eg: https://wcca.wicourts.gov/advanced.html We're only using `customInput` for the sake of `aria-describedby`.

**Comment by kkras3** [comment]
Huh... well that's an approach I hadn't considered. Thanks aij.

**Comment by kkras3** [comment]
@aij How are you triggering the calendar to pop when you click on the added button?

**Comment by WesselKroos** [comment]
@kkras3 There is a customInput={<CustomInput/>} property you can set with your custom input component. In there you can add multiple elements, so in my case I just focus on the input on the click event of a button that is within that component. That'll open the datepicker automatically.

**Comment by karlkras** [comment]
Thanks, yep, found a solution by hunting around the issue items.
