### ISSUE TITLE
Changing day headings?

### ISSUE THREAD

**Issue by kkras3** [Hacker0x01/react-datepicker#1497]
The default markers for the week days is:
`Su Mo Tu We Th Fr Sa`

Is there any way these can be modified ? Say week day name prop that could take, e.g.,:
`dayNames={ sun: 'S', mon: 'M', tue: 'T', wed: 'W', th: 'T', fr: 'F', sa: 'S' }`
?

**Comment by kkras3** [comment]
Figured out how to do this via moment configuration.

**Comment by Sustenance** [comment]
@kkras3 Could you give an example of how you solved this via configuration?

**Comment by Sustenance** [comment]
Figured out a way to do it with version `2.8.0`. Looks like there is an undocumented prop that you can pass in like so:
```javascript
<DatePicker
  selected={selectedDate}
  onChange={setSelectedDate}
  formatWeekDay={(dayOfWeekLabel) => dayOfWeekLabel.substring(0, 3)}
  {...props}
/>
```
Which results in this:
![Screen Shot 2019-08-06 at 2 29 51 PM](https://user-images.githubusercontent.com/4147842/62566319-b3844880-b856-11e9-8a68-33d6af2e8eb9.png)
