### ISSUE TITLE
Showing only current month dates? Ignore any leading/trailing days?

### ISSUE THREAD

**Issue by karlkras** [Hacker0x01/react-datepicker#1498]
Current implementation would seem to include a "full month" of days, so if the current month doesn't take up a full 31 days, the remaining days are filled in with prior and/or next month days. I'd prefer to exclude these filler days and simply leave them blank.
Is there some way to achieve this?

**Comment by alphanumericone** [comment]
Did you find a way to do this?

**Comment by karlkras** [comment]
Yes I did... there's a class for the dates that aren't in the month (react-datepicker__day--outside-month), that I overwrote to basically hide these elements.
