### ISSUE TITLE
date didn't change when input field out of scope/screen

### ISSUE THREAD

**Issue by SajagTiwari** [Hacker0x01/react-datepicker#1499]
### Expected behavior
date input field should update when the user clicks on any date digit in the popup.

### Actual behavior
date input field is not updating when the input field is outside of the visual area and the only popup is visible.

### Steps to reproduce
First, open the calendar popup then use mouse scroll to scroll the input field outside of the visible area and ensure that only calendar popup is visible. now click on any date digit. input filed will not update with the new date.

**Comment by klov** [comment]
Did  you   updated your state in function onChange ?
