### ISSUE TITLE
restrict keyboard  in date picker

### ISSUE THREAD

**Issue by sonusandeep** [Hacker0x01/react-datepicker#1503]
Hi,  have been using react date picker in my projects. but in the text box, we are able to enter any characters which should not be the case and we need to write the validations for it, i am just curious to know is there any key attribute to restrict keyboard

**Comment by karlkras** [comment]
well, there is the onKeyDown callback, from which you can theoretically explicitly control what is entered into the "value" prop, which dictates what shows up in the input.
However, I tried this but abandoned the attempt as I found that the datepicker will unexpectedly add its own stuff to this value before it calls the callback making it unpredictable and pretty much useless.
YMMV, and you might have better success at making this work so don't let me deter you. Personally I'd like to hear from someone who actually makes this work properly.

**Comment by WesselKroos** [comment]
You can use the customInput={<CustomInputComponent/>} and handle the onKeyDown, onKeyUp, etc events yourself to get full control over the characters that can be put into it.

**Comment by YahyaAhmad** [comment]
You can also use onChangeRaw: ` onChangeRaw={(event) => { event.preventDefault(); }}`
