### ISSUE TITLE
A basic working example of a Custom Input implentation?

### ISSUE THREAD

**Issue by karlkras** [Hacker0x01/react-datepicker#1508]
### Expected behavior
An example showing interaction of a picker controlled via a custom input implementation.
### Actual behavior
Existing example in code base is hard to decipher and is using a button, not an input text control for demonstration.
### Steps to reproduce
[Look at it... ](https://github.com/Hacker0x01/react-datepicker/blob/master/docs-site/src/examples/custom_input.jsx)I'm not new at this and I can't figure it out.

**Comment by WesselKroos** [comment]
I have to agree that the current examples do a poor job at describing how you can make your own input components. But I can give you one of my own examples instead. Hopefully that can shed some light on questions you might have:

`import React, { Component } from 'react'
import DatePicker from 'react-datepicker'

class CustomInputExample extends Component {
  render() {
    const inputProps = this.props;
    return <input
      {...inputProps} 
    />
  }
}

class DatePickerExample extends Component {
  render() {
    return <DatePicker 
      CustomInput={CustomInputExample}
    />
  }
}`

**Comment by kkras3** [comment]
Well, yeah, but that is nothing more than the standard input.
Not sure what this does for me over overriding styles of the built in input.

**Comment by wilarz89** [comment]
I also had a hard time figuring it out , then I saw the examples :
https://reactdatepicker.com/#example-43
And what it does is turn the input into a button.
