### ISSUE TITLE
Formik Validation

### ISSUE THREAD

**Issue by Randore** [Hacker0x01/react-datepicker#1514]
### Expected behavior
using `<DatePicker />` as a child component inside Formik should validate the date field.
### Actual behavior
The wrapped div structure generated around Date-picker wrapper is not accessible in Formik
### Steps to reproduce
create a DatePicker component and import it into HOC Formik and try validation

along with DatePicker and Formik, I am using react-bootstrap ^3.xx

**Comment by ahmadalfy** [comment]
I am using Formik like the following and the validations are working as expected

```
class MyDatePicker extends React.Component {
  constructor(props) {
    super(props);
    this.handleChange = this.handleChange.bind(this);
    this.handleBlur = this.handleBlur.bind(this);
  }
  handleChange = value => {
    this.props.onChange(this.props.id, value);
  };

  handleBlur = () => {
    this.props.onBlur(this.props.id, true);
  };

  render() {
    return (
      <DatePicker
        autoComplete="off"
        id={this.props.id}
        maxDate={this.props.maxDate || null}
        selected={
          typeof this.props.value === 'string'
            ? moment(this.props.value)
            : this.props.value
        }
        onBlur={this.handleBlur}
        dateFormat="DD/MM/YYYY"
        onChange={this.handleChange}
        showYearDropdown
        dateFormatCalendar="MMMM"
        scrollableYearDropdown
        disabled={this.props.disabled}
        yearDropdownItemNumber={15}
      />
    );
  }
}
```

**Comment by idoo** [comment]
@ahmadalfy do you have any ideas how to validate it on field level?

**Comment by ahmadalfy** [comment]
@idoo do you mean using Formik or without it?

**Comment by idoo** [comment]
@ahmadalfy I mean that one https://jaredpalmer.com/formik/docs/guides/validation#field-level-validation

**Comment by ahmadalfy** [comment]
No I always use the `validationSchema` option and the `validate` function is triggered automatically after blur and change.

**Comment by idoo** [comment]
so, would be nice to have such attribute somehow, or combine that datepicker with formik fields

**Comment by tureey** [comment]
> I am using Formik like the following and the validations are working as expected
> 
> ```
> class MyDatePicker extends React.Component {
>   constructor(props) {
>     super(props);
>     this.handleChange = this.handleChange.bind(this);
>     this.handleBlur = this.handleBlur.bind(this);
>   }
>   handleChange = value => {
>     this.props.onChange(this.props.id, value);
>   };
> 
>   handleBlur = () => {
>     this.props.onBlur(this.props.id, true);
>   };
> 
>   render() {
>     return (
>       <DatePicker
>         autoComplete="off"
>         id={this.props.id}
>         maxDate={this.props.maxDate || null}
>         selected={
>           typeof this.props.value === 'string'
>             ? moment(this.props.value)
>             : this.props.value
>         }
>         onBlur={this.handleBlur}
>         dateFormat="DD/MM/YYYY"
>         onChange={this.handleChange}
>         showYearDropdown
>         dateFormatCalendar="MMMM"
>         scrollableYearDropdown
>         disabled={this.props.disabled}
>         yearDropdownItemNumber={15}
>       />
>     );
>   }
> }
> ```

Since you are using `Arrow functions` you don't need to use `.bind()` in the `constructor`. So, You could omit all the constructor and binding thing

**Comment by tureey** [comment]
BTW, I'm trying the same thing and it's not working for me :(

**Comment by mjangir** [comment]
> > I am using Formik like the following and the validations are working as expected
> > ```
> > class MyDatePicker extends React.Component {
> >   constructor(props) {
> >     super(props);
> >     this.handleChange = this.handleChange.bind(this);
> >     this.handleBlur = this.handleBlur.bind(this);
> >   }
> >   handleChange = value => {
> >     this.props.onChange(this.props.id, value);
> >   };
> > 
> >   handleBlur = () => {
> >     this.props.onBlur(this.props.id, true);
> >   };
> > 
> >   render() {
> >     return (
> >       <DatePicker
> >         autoComplete="off"
> >         id={this.props.id}
> >         maxDate={this.props.maxDate || null}
> >         selected={
> >           typeof this.props.value === 'string'
> >             ? moment(this.props.value)
> >             : this.props.value
> >         }
> >         onBlur={this.handleBlur}
> >         dateFormat="DD/MM/YYYY"
> >         onChange={this.handleChange}
> >         showYearDropdown
> >         dateFormatCalendar="MMMM"
> >         scrollableYearDropdown
> >         disabled={this.props.disabled}
> >         yearDropdownItemNumber={15}
> >       />
> >     );
> >   }
> > }
> > ```
> 
> Since you are using `Arrow functions` @ahmadalfy you don't need to use `.bind()` in the `constructor`. So, You could omit all the constructor and binding thing

I try to avoid arrow functions in class properties though :)

**Comment by tureey** [comment]
Why is that? @mjangir 

> > > I am using Formik like the following and the validations are working as expected
> > > ```
> > > class MyDatePicker extends React.Component {
> > >   constructor(props) {
> > >     super(props);
> > >     this.handleChange = this.handleChange.bind(this);
> > >     this.handleBlur = this.handleBlur.bind(this);
> > >   }
> > >   handleChange = value => {
> > >     this.props.onChange(this.props.id, value);
> > >   };
> > > 
> > >   handleBlur = () => {
> > >     this.props.onBlur(this.props.id, true);
> > >   };
> > > 
> > >   render() {
> > >     return (
> > >       <DatePicker
> > >         autoComplete="off"
> > >         id={this.props.id}
> > >         maxDate={this.props.maxDate || null}
> > >         selected={
> > >           typeof this.props.value === 'string'
> > >             ? moment(this.props.value)
> > >             : this.props.value
> > >         }
> > >         onBlur={this.handleBlur}
> > >         dateFormat="DD/MM/YYYY"
> > >         onChange={this.handleChange}
> > >         showYearDropdown
> > >         dateFormatCalendar="MMMM"
> > >         scrollableYearDropdown
> > >         disabled={this.props.disabled}
> > >         yearDropdownItemNumber={15}
> > >       />
> > >     );
> > >   }
> > > }
> > > ```
> > 
> > 
> > Since you are using `Arrow functions` @ahmadalfy you don't need to use `.bind()` in the `constructor`. So, You could omit all the constructor and binding thing
> 
> I try to avoid arrow functions in class properties though :)

**Comment by iamelme** [comment]
> I am using Formik like the following and the validations are working as expected
> 
> ```
> class MyDatePicker extends React.Component {
>   constructor(props) {
>     super(props);
>     this.handleChange = this.handleChange.bind(this);
>     this.handleBlur = this.handleBlur.bind(this);
>   }
>   handleChange = value => {
>     this.props.onChange(this.props.id, value);
>   };
> 
>   handleBlur = () => {
>     this.props.onBlur(this.props.id, true);
>   };
> 
>   render() {
>     return (
>       <DatePicker
>         autoComplete="off"
>         id={this.props.id}
>         maxDate={this.props.maxDate || null}
>         selected={
>           typeof this.props.value === 'string'
>             ? moment(this.props.value)
>             : this.props.value
>         }
>         onBlur={this.handleBlur}
>         dateFormat="DD/MM/YYYY"
>         onChange={this.handleChange}
>         showYearDropdown
>         dateFormatCalendar="MMMM"
>         scrollableYearDropdown
>         disabled={this.props.disabled}
>         yearDropdownItemNumber={15}
>       />
>     );
>   }
> }
> ```

This one solve's my problem, thank you @ahmadalfy

**Comment by mjangir** [comment]
> Why is that? @mjangir
> 
> > > > I am using Formik like the following and the validations are working as expected
> > > > ```
> > > > class MyDatePicker extends React.Component {
> > > >   constructor(props) {
> > > >     super(props);
> > > >     this.handleChange = this.handleChange.bind(this);
> > > >     this.handleBlur = this.handleBlur.bind(this);
> > > >   }
> > > >   handleChange = value => {
> > > >     this.props.onChange(this.props.id, value);
> > > >   };
> > > > 
> > > >   handleBlur = () => {
> > > >     this.props.onBlur(this.props.id, true);
> > > >   };
> > > > 
> > > >   render() {
> > > >     return (
> > > >       <DatePicker
> > > >         autoComplete="off"
> > > >         id={this.props.id}
> > > >         maxDate={this.props.maxDate || null}
> > > >         selected={
> > > >           typeof this.props.value === 'string'
> > > >             ? moment(this.props.value)
> > > >             : this.props.value
> > > >         }
> > > >         onBlur={this.handleBlur}
> > > >         dateFormat="DD/MM/YYYY"
> > > >         onChange={this.handleChange}
> > > >         showYearDropdown
> > > >         dateFormatCalendar="MMMM"
> > > >         scrollableYearDropdown
> > > >         disabled={this.props.disabled}
> > > >         yearDropdownItemNumber={15}
> > > >       />
> > > >     );
> > > >   }
> > > > }
> > > > ```
> > > 
> > > 
> > > Since you are using `Arrow functions` @ahmadalfy you don't need to use `.bind()` in the `constructor`. So, You could omit all the constructor and binding thing
> > 
> > 
> > I try to avoid arrow functions in class properties though :)

https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1
