### ISSUE TITLE
Datepicker popup doesn't disappear

### ISSUE THREAD

**Issue by nryumin** [Hacker0x01/react-datepicker#1516]
### Steps to reproduce
1. Goto https://reactdatepicker.com Second example (Select time)
2. Click on text field
3. Select date
4. Select time

### Expected behavior
Datepicker popup disappears after time select

### Actual behavior
Datepicker popup disappears and appears back in a moment. Only way to close it is to click somewhere outside

Caught in chrome and safari (os x high sierra)

**Comment by jantaylor** [comment]
Tried to replicate this. It disappears like expected for me. If I don't click outside the input and switch tabs then come back, it pops open.

Latest chrome v69x, OS X Mojave.

**Comment by nryumin** [comment]
Just tried on my android tablet (galaxy tab A chrome). Same bug

**Comment by adamwhiles** [comment]
I see the same issue as well. Select a date, the calendar popup stays in view until you click somewhere outside of the popup

**Comment by Sajam** [comment]
+1

**Comment by Sajam** [comment]
Possible workaround (minimal effort example):
```
<DatePicker
    ref="timePicker"
    onChange={value => {
        this.refs.timePicker.cancelFocusInput();
    } />
```

I'm not 100% sure what are (and if there are any) drawbacks of using `cancelFocusInput` directly, but seems to be OK for me.

**Comment by lorenzos** [comment]
Any news on this? Looks like @Sajam's workaround doesn't work anymore.
