### ISSUE TITLE
Exception for onClickOutside(calendar) when upgrading react from 16.4 to 16.5

### ISSUE THREAD

**Issue by mpantel** [Hacker0x01/react-datepicker#1517]
### Expected behavior
for version 1.6.0
select the date as usual when upgrading from react 16.4 to 16.5
### Actual behavior
it throws an exception for onClickOutside(calendar):

The above error occurred in the <OnClickOutside(t)> component:
    in OnClickOutside(t)
    in div
    in e
    in div
    in e
    in t
    in t
    in div
    in DatePickerInput
    in App
    in React::TopLevelRailsComponent

### Steps to reproduce
upgrade react 16.4 to 16.5

**Comment by sittmannkatia** [comment]
Can confirm, had the same issue. When I updated to the latest react version (`16.6.3`) it works fine.

**Comment by diego-betto** [comment]
same here

**Comment by hamzahamidi** [comment]
Same error here with 
```
    "react-datepicker": {
      "version": "1.4.1",

```
