### ISSUE TITLE
react-datepicker doesn't work on react 16.4

### ISSUE THREAD

**Issue by OHaidukova** [Hacker0x01/react-datepicker#1519]
Datepicker 1.6.0 doesn't work on react 16.4

errors:
react-datepicker@1.6.0 requires a peer of react@^16.0.0 but none is installed.
react-datepicker@1.6.0 requires a peer of react-dom@^16.0.0
react-onclickoutside@6.7.1 requires a peer of react@^15.5.x || ^16.x but none is installed.
react-onclickoutside@6.7.1 requires a peer of react-dom@^15.5.x || ^16.x but none is installed.
react-popper@0.9.5 requires a peer of react@0.14.x || ^15.0.0 || ^16.0.0 but none is installed.
 react-popper@0.9.5 requires a peer of react-dom@0.14.x || ^15.0.0 || ^16.0.0 but none is installed.

package.json
    "react": "^16.4.2",
    "react-dom": "^16.4.2",

**Comment by Ky6uk** [comment]
@OHaidukova this isn't looking at `react-datepicker`'s issue. It looks you have no installed peer dependencies of `react` and `react-dom` at all.

**Comment by Ky6uk** [comment]
@OHaidukova those packages may not been installed still. Try to run `npm install react react-dom`.

**Comment by OHaidukova** [comment]
React and React-dom installed, like react-select. They work but Datepicker doesn't work.
I try to use Datepicker in gulp and webpack, it has the same result (but different errors).
Do you have a working project with React 16.4 and Datepicker?

**Comment by Ky6uk** [comment]
What do you mean "doesn't work"? It's working fine for latest react in my project.
