### ISSUE TITLE
Clear button not showing at start when you initially add value to the calendar

### ISSUE THREAD

**Issue by billyperalta89** [Hacker0x01/react-datepicker#1530]
### Expected behavior
Upon load of my Calendar Components, I was expecting for the clear "x" button to appear when you initially add value from a props

```
<DatePicker
        name={this.props.name}
        selected={this.state.InitialDates}
        value={
          moment(this.props.value.substring(0, 10)).format("MM/DD/YYYY")
        }
        dateFormatCalendar="MM/DD/YYYY"
        className={
          "fill-control-input " + (this.props.readOnly ? "readonly" : "")
        }
        readOnly={this.props.readOnly}
        showMonthDropdown
        useShortMonthInDropdown
        isClearable={true}
      />
```

### Actual behavior

but unfortunately it doesnt detect the value in the DatePicker component and the clear button doesnt appear yet until you chosen a new date

### Steps to reproduce

1.) Add value to the components using props
2.) Upon load of the component it seems the button is not added even there is a value in the input

<button type="button" class="react-datepicker__close-icon" tabindex="-1"></button>

**Comment by YahyaAhmad** [comment]
You should use `selected` instead, I think it doesn't watch the `value` prop.
