### ISSUE TITLE
Custom Input Props Not Getting Passed Through

### ISSUE THREAD

**Issue by zachgibson** [Hacker0x01/react-datepicker#1535]
### Expected behavior
Passing `customInput={<input type="text" placeholder="gucci"/>}` should render an input with the placeholder.
### Actual behavior
This renders an input with no placeholder.
### Steps to reproduce
[CodeSandbox](https://codesandbox.io/s/q9xmo77o1q).

**Comment by rebirthtobi** [comment]
@zachgibson datepicker has a props called `placeholderText`. this is what is used, not the placeholder on the input

**Comment by zachgibson** [comment]
@rebirthtobi Let me expound.

I’m trying to pass a custom `Input` component that has props like `css` coming from emotion. These props are not getting passed through for some reason.

**Comment by zachgibson** [comment]
My code looks like:

```jsx
customInput={(
    <Input
        name="requestedDate"
        value={props.value}
        placeholder="Date"
        onClick={props.onClick}
        css={{ marginTop: 16, width: '100%', '@media(max-width: 700px)': { fontSize: 16 } }}
        readOnly
        autoComplete={false}
    />
)}
```

**Comment by rebirthtobi** [comment]
@zachgibson i now understand, but check through you can use class to manipulate as you like

**Comment by cention-sany** [comment]
@zachgibson may be this can help https://github.com/Hacker0x01/react-datepicker/issues/1469#issuecomment-417756933 because what happen to my case is the `readOnly` props is not pass through into `customInput`'s component. What I did is instead of pass with `readOnly` props I use another props name `notClickable` then inside customInput's component `notClickable` is treated as `readOnly`. May be you want to try use another name for those props that not passed through.

**Comment by alphanumericone** [comment]
I also use a custom input, but I do not pass the placeholder prop to my custom input (although it supports that) but provide the placeholder to the DatePicker placeholderText prop.

**Comment by zachgibson** [comment]
I used placeholder as an example, but other props like `css` didn’t work either.

**Solved** this by making my input a component with all the props I needed.

```jsx
<DatePicker
    customInput={<DatePickerInput value={props.value} onClick={props.onClick} />}
/>
```

```jsx
const DatePickerInput = ({ value, onClick }) => (
    <Input
        name="requestedDate"
        value={value}
        placeholder="Date"
        onClick={onClick}
        css={{ cursor: 'pointer' }}
        autoComplete={false}
        readonly="true"
    />
);
```

**Comment by zachgibson** [comment]
This does work, however it breaks opening the datepicker on input focus.

**Comment by zachgibson** [comment]
So I found out a composed component is the issue. If you try to make an `Input` component then make a `DatepickerInput` component by composing it from `Input` it won’t show the picker on focus.

So I’m going to just make a *root* `DatepickerInput` component with all the props I need. Not the most flexible solution, but it solves my requirements as of now.

**Comment by GLObus303** [comment]
@zachgibson what about

```
 <DatePicker
          inputRef={(node) => {
            if (node) {
              node.setAttribute('value', props.value);
              // whatever else you need 
            }
          }}
          ```

that worked for me.
