### ISSUE TITLE
No validation for date range

### ISSUE THREAD

**Issue by lingfeidiewu** [Hacker0x01/react-datepicker#1537]
### Expected behavior
The max date should prevent people choose a date later than it, no matter by selecting from the calendar or input from keyboard.
### Actual behavior
Now if I set max date as 11/14/2018, I cannot select a later date from calendar. However, I can input a date like 11/15/2018 from keyboard.
### Steps to reproduce
https://reactdatepicker.com/#example-11

**Comment by rootedy-ffit** [comment]
+1

**Comment by toanqc** [comment]
+1
