### ISSUE TITLE
How to get actual date selected in the dropdown area after Redux Form Reset?

### ISSUE THREAD

**Issue by maxdonetsk** [Hacker0x01/react-datepicker#1538]
### Expected behavior
During the reset of Redux Form which contains DatePicker, I want the selected date in the dropdown area be set to initial value.

### Actual behavior
When I'm trying to reset a Redux Form which contains DatePicker, this happened:
1. Redux form values set to initial in its store (including the value of DatePicker).
2. Selected date in the dropdown area of DatePicker can't be reset.

### Steps to reproduce
I have this code:
```
export const renderDatePicker = ({ id, value, props, intl }) => {
  const parseDate = date => (date ? date.format('YYYY-MM-DD') : null);

  return (
    <Field
      parse={parseDate}
      id={id}
      name={id}
      component={renderDatePickerComponent}
      value={value}
      intl={intl}
      {...props}
    />
  );
};

export class renderDatePickerComponent extends React.Component {
  state = {
    date: this.props.input.value ? moment(this.props.input.value) : null,
  };

  onChange = date => {
    this.setState({ date });
    this.props.input.onChange(date);
  };

  onChangeRaw = event => {
    const { value, onChange } = this.props.input;
    let date = moment(event.target.value);
    if (!date.isValid()) {
      date = moment(value);
    }
    this.setState({ date });
    onChange(date);
  };

  render() {
    const {
      input: { value },
      id,
      meta: { error, warning },
    } = this.props;
    const { date } = this.state;
    return (
      <React.Fragment>
        {renderHints({ error, warning })}
        <DatePicker
          value={moment(value).format('L')}
          selected={date}
          onChange={this.onChange}
          onChangeRaw={this.onChangeRaw}
          name={id}
          id={id}
        />
      </React.Fragment>
    );
  }
}
```
1. Check the initial date in DatePicker:

![image](https://user-images.githubusercontent.com/8349136/48475541-bab98100-e805-11e8-8e8f-cfecf61cc0f1.png)

2. Then change the date:

![image](https://user-images.githubusercontent.com/8349136/48475575-cd33ba80-e805-11e8-841b-df04c3da113a.png)

3. Reset the Redux Form.
4. Check DatePicker's input and dropdown area. Value in the input is correct, but selected date is wrong.

![image](https://user-images.githubusercontent.com/8349136/48475695-03713a00-e806-11e8-97ce-cad60467a5e9.png)

**Comment by iloveip** [comment]
Hi there,

I have the same problem. Did you manage to solve it?
