### ISSUE TITLE
Ability to select a time range

### ISSUE THREAD

**Issue by DominicTobias** [Hacker0x01/react-datepicker#1542]
Hi,

This seems like the most versatile calendar picker, but I could not see in the examples if it's possible to select a time range, only a date range. Is that correct? Thanks

**Comment by shmilyoo** [comment]
+1   
```
 minDate={new Date(new Date().setHours(0, 0, 0, 0))}
 maxDate={new Date(new Date().setHours(12, 0, 0, 0))}
```
the property above is of no effect. I want user can only select time betten 00:00 and 12:00.

**Comment by aliberkhsl** [comment]
```
minTime={new Date().setHours(0,0,0)}
maxTime={new Date().setHours(12,0,0)}
```

It should be ok.

**Comment by Nemec163** [comment]
> minTime={new Date().setHours(0,0,0)}
> maxTime={new Date().setHours(12,0,0)}

![screenshot_5](https://user-images.githubusercontent.com/31842607/53810899-71866c00-3f71-11e9-96bf-eb17770c85c8.png)

It's working, but: 

Warning: Failed prop type: Invalid prop `minTime` of type `Number` supplied to `DatePicker`, expected instance of `Date`.
