### ISSUE TITLE
Locale error when using date-fns

### ISSUE THREAD

**Issue by cbh6** [Hacker0x01/react-datepicker#1546]
I'm trying to load `es` locale from date-fns and it throws an error, maybe this is related to date-fns itself. 
It also happens with locales that are different than 'en-GB'

### Expected behavior
Load different locale than en-GB

### Actual behavior
It crashes with this message:
`RangeError: locale must contain localize property
    at format (modules.js?hash=6c38037b3206d378e63fb830a74ef56e49e3a6a4:8675)
    at formatDate (modules.js?hash=6c38037b3206d378e63fb830a74ef56e49e3a6a4:12089)
    at safeDateFormat (modules.js?hash=6c38037b3206d378e63fb830a74ef56e49e3a6a4:12`
### Steps to reproduce
import es locale and load it to DatePicker component

Can anyone try it out ?
Thanks in advance

**Comment by Darrken** [comment]
Which version of date-fns are you using? To take advantage of the latest date-fns localization file features (and to better match the previous moment localization), the alpha version was used in react-datepicker, so you may need to try a new version of date-fns: `npm install date-fns@next`

**Comment by cbh6** [comment]
Thanks a lot for your answer.
I was using date-fns v1.29.0. Switched to alpha and it worked like a charm !

:dancer:

**Comment by cbh6** [comment]
Yes, that was for trying some features :smile: 

Finally grabbed needed locale files and it also worked withouth having to use alpha version

**Comment by LidiaRamirez** [comment]
How could you change from lowercase to the first letter to upper case and the rest to lowercase?

**Comment by cbh6** [comment]
Hi Lidia, cannot understand. What do you mean? Can you provide an example (code, pic or something)?

**Comment by LidiaRamirez** [comment]
![image](https://user-images.githubusercontent.com/32305550/50603278-00024280-0e88-11e9-92f0-825a6b2b80af.png)
![image](https://user-images.githubusercontent.com/32305550/50603302-101a2200-0e88-11e9-8b84-1c6fd0181fc9.png)

**Comment by LidiaRamirez** [comment]
The months and days are in lowercase according to code, as it is with camelCase

**Comment by 1S3L** [comment]
Hi. how do i switch to alpha

**Comment by cbh6** [comment]
@1S3L to install a certain version of date-fns you can use `npm install date-fns@2.0.0-alpha.27 --save` for example, but as @Darrken said, is preferable to only grab the files you need from that version.

**Comment by KumailP** [comment]
![image](https://user-images.githubusercontent.com/22764971/55503451-204cc380-5668-11e9-9dbc-029c5f64d6c7.png)

Hi, I'm getting this when I'm trying to use the alpha version. I'm not using DD or + token + anywhere.

**Comment by cbh6** [comment]
Thats maybe related with date-fns itself. If you need some localization files from date-fns I think its better to grab and use them locally rather than installing alpha version.

**Comment by KumailP** [comment]
That worked! Thanks!

Just a follow-up. How do I integrate it with my React app that's deployed on Firebase? Because when I deploy it on Firebase it would install fresh packages.

**Comment by cbh6** [comment]
I think that doesn't matter. I mean, if you have some localization files locally and import them instead of node_modules/date-fns ones, it doesn't matter if your deploy install fresh packages. No ?

**Comment by LosEagle** [comment]
I don't think switching to alpha version of that package is a good enough solution to justify closing this issue. I bet I'm not alone in not wanting to use unstable software on production.

**Comment by lxcusp** [comment]
> Which version of date-fns are you using? To take advantage of the latest date-fns localization file features (and to better match the previous moment localization), the alpha version was used in react-datepicker, so you may need to try a new version of date-fns: `npm install date-fns@next`
> 
> Another option if you don't want to go alpha is just grab the latest date localization files and use those independently: https://github.com/date-fns/date-fns/tree/master/src/locale

Hello, May I asked how to use them independently? 
Thanks! :)
