### ISSUE TITLE
Replace Moment with date-fns

### ISSUE THREAD

**Issue by aghoneim92** [Hacker0x01/react-datepicker#1550]
The problem with Moment is that it has a big size in bundles. Date-fns was created to mitigate that problem by allowing better tree shaking. Suggestion: replace moment with date-fns.

**Comment by martijnrusschen** [comment]
Moment was removed in v2.0.0. This should resolve your concerns,

**Comment by aghoneim92** [comment]
Thank you :-)!

**Comment by Firanolfind** [comment]
In our project, we use Moment.js extensively. Changing Moment.js to Date-fns in react-datepicker only adds up to the application footprint. Is it possible to make it a drop-in dependency, so we could use new version of this great component and keep Moment.js without replacing it with date-fns, or adding another dependency and making overall application bundle even bigger than before?

**Comment by martijnrusschen** [comment]
I'm happy to support that path if you can help to get there. Ideally, the datepicker would support multiple date engines so you can use the date engine that works best with the rest of your app.
