### ISSUE TITLE
2.X.X @types

### ISSUE THREAD

**Issue by chrisgbaker** [Hacker0x01/react-datepicker#1556]
Hello!
Excited to see that `react-datepicker` has dropped Moment.js in lieu of native `Date`s. Has anybody put together a release of the typescript types that remove `moment` as well?

Thanks!

**Comment by jakeboone02** [comment]
I took a stab at typing v2:  DefinitelyTyped/DefinitelyTyped#30867

I'm fairly new to TypeScript so any feedback would be appreciated.

**Comment by jakeboone02** [comment]
The PR mentioned above was merged so this issue can be closed.
