### ISSUE TITLE
Problem with tabbing navigation

### ISSUE THREAD

**Issue by bmcneely** [Hacker0x01/react-datepicker#156]
If you open the demo and press Tab to move focus from one DatePicker to another, the calendar of the original DatePicker stays open. I think that by default it should hide the same way it would when you click outside of the calendar.

**Comment by gsheppard** [comment]
Is there any update regarding this?

**Comment by creativej** [comment]
What's the status of this issue? It's such a basic form UX, would love to see tab working.

**Comment by martijnrusschen** [comment]
No update yet. It would be awesome if someone could help here with providing a pull request.
