### ISSUE TITLE
Picking a time without picking a date ignores the day of the minDate

### ISSUE THREAD

**Issue by CyrilBos** [Hacker0x01/react-datepicker#1560]
### Expected behavior
The resulting date should be the day of minDate, which time part is modified to the selected time.

### Actual behavior
The resulting date is today, which time part is modified to the selected time. This looks buggy since the minDate day shows being selected in blue in the date part of the picker.

### Steps to reproduce
    <ReactDatePicker
        selected={this.state.value}
        onChange={(value: Date) => this.setState({ value }, () => this.invokeOnChange())}
        minDate={new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)}
        showTimeSelect
        dateFormat={dateFormat}
        timeFormat="HH:mm"
    />
I fixed it temporarily by changing the value in the onChange callback (if `value < props.minDate`).

**Comment by mightym** [comment]
Same issue the other way around. If you've set `minTime` to `8:00` and you just select a date the time will be `00:00`

**Comment by bobsoppe** [comment]
Can this one be reopened? This bug is still happening

**Comment by hassan-nxtwave** [comment]
I am getting the same issue still.
