### ISSUE TITLE
Dates are compared with (their) time

### ISSUE THREAD

**Issue by jRichardeau** [Hacker0x01/react-datepicker#1561]
### Expected behavior
When using Date Range (_selectsStart_, _selectsEnd_) option, the _startDate_ and _endDate_ props should determine the range of the period.
### Actual behavior
If the _startDate_ and _endDate_ props of the DatePicker are not initialized with hours/minutes/seconds/milliseconds to 0 the dates are not included in the period when hovering the calendar.
### Steps to reproduce
Initialize _startDate_ and _endDate_ with non "0 time" date

```
const startDate = new Date();
const endDate = addDays(new Date(), 1);

<ReactDatePicker
   selected={ startDate }
   selectsStart
   startDate={ startDate }
   endDate={ endDate }
/>

<ReactDatePicker
   selected={ endDate }
   selectsEnd
   startDate={ startDate }
   endDate={ endDate }
/>
```
In this example, this is the start picker with start date Nov 27 and end date Nov 28, the Nov 27 should be "in-range" but is not :

![image](https://user-images.githubusercontent.com/4921182/49092379-e7bb5a00-f22f-11e8-99f7-3b1fdee8f978.png)

If I set hours/minutes/seconds/milliseconds to 0 for startDate it works as it should

**Comment by pmacmillan** [comment]
It appears to be a regression in removing moment.

https://github.com/Hacker0x01/react-datepicker/commit/f0d4c560c3f5722366c553bbbca3748cd03688fe#diff-eae406df76db9079672d27cd79e9079eL280

The old code rounded up/down whereas the new code just uses the day (which is probably at hour 0 and would not include any time after midnight).

A workaround would be for the consumer of date picker to round dates to the start/end of days (which is probably not ideal).

workaround example: https://codesandbox.io/s/oo23r64r4q  (notice the startOfDay/endOfDay usage).
