### ISSUE TITLE
Uncaught RangeError: Invalid interval

### ISSUE THREAD

**Issue by willbee28** [Hacker0x01/react-datepicker#1563]
### Expected behavior
Nothing. I should be able to error handle on my own. 
### Actual behavior
When a start date is chosen after the end date, an error pops up and my application crashes.
### Steps to reproduce
Use the date range version of react-datepicker and choose an endDate that is before the startDate. In the demo on your site, I am not allowed to select an End Date before the Start Date, like physically cannot. Wonder why my result is different.

**Comment by jRichardeau** [comment]
I think the component doesn't do it natively and lets you implement your own behavior.
You have to manage this in the _onChange_ callbacks : for instance block the date change or change the start/end depending of what is the value.
For my part I made the start and end have the same value if the period is invalid and I think in the demo it is the first option that is implemented.

**Comment by willbee28** [comment]
Does it show how that is implemented? Also not to be an asset, but I think
that's kinda dumb, that should be on the user of the library. I like that
there is validation but I think it should be a choice and not in the form
of a application-crashing bug.

**Comment by jkeam** [comment]
Opened a PR against this (https://github.com/Hacker0x01/react-datepicker/pull/1577).  Comments welcome!

**Comment by willbee28** [comment]
Also, this is most likely beyond this ticket, but I submitted another
addressing that if you begin to type 20 for the year or 19 for the 20th
century, the other date updates automatically to 2020 of 2019 for 20th
century. Weird that it doesn't wait for the user to finish typing I think.

**Comment by sugarfree1** [comment]
It is fixed now. Could you release it, please?
