### ISSUE TITLE
What is going on with dateFormat?

### ISSUE THREAD

**Issue by seanpascoe** [Hacker0x01/react-datepicker#1564]
### Expected behavior
set dateFormat to "YYYY-MM-DD", get "2018-11-28"
### Actual behavior
set dateFormat to "YYYY-MM-DD", get "2018-10-301"
### Steps to reproduce

I looked through the documentation thoroughly and could not find anything on formatting the date for display. I would expect the syntax would be similar to date-fns or moment but it doesn't seem to be the case. The examples on the website are minimal with no explanation. I looked through the source and while I see the format function from date-fns being used, trying to trace exactly what it is doing with locale is a mess.

**Comment by makalkin** [comment]
Hey @seanpascoe, I thought I had same issues then I noticed that `react-datepicker` is using `date-fns` above `2.0.0` and they changed [formatting rules](https://date-fns.org/v2.0.0-alpha.25/docs/format) quite a bit, so In your case `DD` refers _to day of the year_ Hope this helps you, or anyone who comes across.

**Comment by seanpascoe** [comment]
Ahh, thanks @makalkin! Yup, I was looking at the [latest formatting documentation](https://date-fns.org/v1.29.0/docs/format), which at this time is v1.29.0.
