### ISSUE TITLE
Suggested change of PropType for button label 

### ISSUE THREAD

**Issue by ismyrnow** [Hacker0x01/react-datepicker#1568]
### Expected behavior
Using JSX or a React component as a prop value for `previousMonthButtonLabel` or `nextMonthButtonLabel` should not show a PropType warning.

### Actual behavior
The PropType is defined as "string", which causes a warning in the console.

### Steps to reproduce
```jsx
<DatePicker previousMonthButtonLabel={<MyComponent />} />
```

---

The use case for this is to render an Icon for the button label, instead of text. We are doing this already, and it works, but we want to avoid the console warnings.

I am happy to open a PR for this. I suggest changing the PropType to `PropTypes.node` or `PropTypes.oneOf(PropTypes.string, PropTypes.node)`, since the prop value is just being rendered as a child of the button. I would like to get validation from an author or maintainer before opening the PR, to ensure this is a reasonable change and could be merged.

**Comment by orestis** [comment]
I just had the same issue. I completely agree, using a node works just fine but you do get warnings in the console.

**Comment by orestis** [comment]
Leave open please?
