### ISSUE TITLE
Default locale not being picked up

### ISSUE THREAD

**Issue by Amwam** [Hacker0x01/react-datepicker#1571]
### Expected behaviour
Using `setDefaultLocale` to en-GB, I would expect the default locale to be the the en-GB format (day/month/year)

### Actual behaviour
Display in the en-US format (month/day/year)

### Steps to reproduce
Minimal app:
```jsx
import React, { Component } from "react";
import ReactDOM from "react-dom";
import Datepicker, { registerLocale, setDefaultLocale } from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { enGB } from "date-fns/esm/locale";

registerLocale("en-GB", enGB);
setDefaultLocale("en-GB");

class App extends Component {
  render() {
    return <Datepicker selected={new Date("2018-12-30")} />;
  }
}

ReactDOM.render(<App />, document.querySelector("body"));

```

Package.json
```json
{
  "name": "react-datepicker-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.6.3",
    "react-datepicker": "^2.0.0",
    "react-dom": "^16.6.3",
    "react-scripts": "2.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

Screenshot:
![screenshot 2018-12-05 at 13 11 33](https://user-images.githubusercontent.com/879073/49515614-51baab80-f88f-11e8-9bc6-76f224b14032.png)

Printing `getDefaultLocale()` in the render also correctly prints `en-GB`.

**Comment by tombiddulph** [comment]
For whatever reason the `dateFormat` prop is still set as `MM/dd/yyyy` when the locale is set to `en-GB`.
https://github.com/Hacker0x01/react-datepicker/blob/93d4694c50cb894edb3884f802537feeec4c4c66/src/index.jsx#L85 

Setting the [`dateFormat`](https://github.com/Hacker0x01/react-datepicker/blob/93d4694c50cb894edb3884f802537feeec4c4c66/src/index.jsx#L85)  prop to `dd/MM/yyyy` resolves the issue with or without the locale set to `en-GB`

```
class App extends Component {
  render() {
    return <Datepicker 
                   dateFormat="dd/MM/yyyy"
                   selected={new Date("2018-12-30")} />;
  }
}

```

**Comment by MickMonaghan** [comment]
This is a significant issue. Changing the `locale` should by itself be enough to change the presented format. Looks like this applies for all locales - not just `en-GB`. One should not have to set the `dateFormat` manually.
The locale data imported from `date-fns` looks like it should be adequate - here's the `en-GB` data: https://github.com/date-fns/date-fns/blob/master/src/locale/en-GB/_lib/formatLong/index.js#L7

**Comment by nemile** [comment]
I ran into this issue while updating to v2 and refactoring my props as `react-datepicker` switched from `momentjs` to `date-fns`. The locale is actually taken into account: if you use a format with the long name of the weekday like `"Wednesday"` and another locale like `"fr"`, it will be translated to `"Mercredi"`. It's just that changing the locale isn't enough to use the localized formats.

The default `dateFormat` prop is hardcoded to `"MM/dd/yyyy"`. You have to specify the localized dateFormat as follows to make it change with the locale:
```javascript
<DatePicker dateFormat="P" selected={new Date("2018-12-30")}/>
```

Since `react-datepicker` has been using date-fns instead of `momentjs`, you can now check the available localized formats here: https://date-fns.org/v2.0.0-beta.5/docs/format
They are different than the `momentjs` ones (https://momentjs.com/docs/#/displaying/format/).

It might be good to explain all that in the localization section of the readme though.

I don't know if specifying a locale should force the format all the time, it might be more confusing than now. But maybe it would be less confusing if the default behaviour (when no dateFormat prop is passed and a locale is set globally or with a prop) was to use the localized formats.

**Comment by lowellstewart** [comment]
This annoyed me as well.  Since I'm working on a project where I don't know the exact locale up front (it's dynamic, depending on user choices), I'm getting around it like this:
```js
  const locale = require('date-fns/locale/' + getDefaultLocale()).default
  const dateFormat = locale.formatLong.date({ width: 'short' })
```
Sure smells funny though.

**Comment by Amwam** [comment]
This is still an issue. I've created a codesandbox with the latest version to demonstrate the issue:

https://codesandbox.io/s/react-datepicker-default-location-issue-xtkv0?file=/src/App.js

**Comment by nemile** [comment]
> This is still an issue. I've created a codesandbox with the latest version to demonstrate the issue:
> 
> https://codesandbox.io/s/react-datepicker-default-location-issue-xtkv0?file=/src/App.js

@Amwam I'm not a contributor here, but I'm not sure this is an issue, you can check my explanation using the difference between translating weekdays names VS using a localized format as an example: https://github.com/Hacker0x01/react-datepicker/issues/1571#issuecomment-522674630

**Comment by Amwam** [comment]
@nemile Sure you can override the format at the component level, but the README suggests that localisation can be set globaly (https://github.com/Hacker0x01/react-datepicker#localization). 

I believe with v1 this is also how the formatting worked with moment, and being able to set the default, without specifying on each component.

**Comment by nemile** [comment]
> @nemile Sure you can override the format at the component level, but the README suggests that localisation can be set globaly (https://github.com/Hacker0x01/react-datepicker#localization).
> 
> I believe with v1 this is also how the formatting worked with moment, and being able to set the default, without specifying on each component.

Indeed the README is misleading or misses information on that matter, as I also suggested on my comment above.

**Comment by Alweezy** [comment]
> It seems to work by registering the locale object instead of the locale string:
> 
> ```js
> import es from 'date-fns/locale/es';
> import { registerLocale, setDefaultLocale } from "react-datepicker";
> 
> registerLocale('es', es)
> setDefaultLocale(es)
> ```

Seems like everyone is demonstrating this using `es` while particularly the problem is `en-GB`.

**Comment by adamsadiq7** [comment]
> > It seems to work by registering the locale object instead of the locale string:
> > ```js
> > import es from 'date-fns/locale/es';
> > import { registerLocale, setDefaultLocale } from "react-datepicker";
> > 
> > registerLocale('es', es)
> > setDefaultLocale(es)
> > ```
> 
> Seems like everyone is demonstrating this using `es` while particularly the problem is `en-GB`.

For en-GB, this worked for me:

```js
import gb from 'date-fns/locale/en-GB';
import { registerLocale, setDefaultLocale } from "react-datepicker";

registerLocale('en-GB', gb);
setDefaultLocale(gb);
```
