### ISSUE TITLE
Date Range: Beginning to type year out changes year instantly and results in start/end error

### ISSUE THREAD

**Issue by willbee28** [Hacker0x01/react-datepicker#1576]
### Expected behavior
Allow the user to type the full year (either 2 or 4 numbers) and then click off or hit enter to submit
### Actual behavior
The year changes with every number typed. This results in the "end date before start date" error when an end date of 2008 for example, is partially typed resulting in the date being set to 2002 because of the leading 2, while the start is still 2018.
### Steps to reproduce
Type 1999 in the start date of the date range on your demo website. The end date will switch to 2019.

**Comment by NunoCardoso** [comment]
I have kind of the same problem, when I type 01, it already is formatting a date.
I want to allow the user to type in the date, OR click on a button to open the datepicker. That part is easy to implement with a CustomInput, my problem is that onChange is always triggered

**Comment by willbee28** [comment]
That is really unfortunate. It should be triggered on hitting enter or
clicking off. Don't know if this would interfere with other features
though. No problems that I can think of.
