### ISSUE TITLE
Datepicker closes on month navigation when an `onBlur` prop is provided

### ISSUE THREAD

**Issue by ntdb** [Hacker0x01/react-datepicker#158]
The GIF shows the problem:
![broken_datepicker](https://cloud.githubusercontent.com/assets/2095463/9183210/b608bf30-3f62-11e5-9135-ce9be5ad95b0.gif)

[This is the specific usage.](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/a3bea63fd6307336702b28cbe2c3aed1420b7d1a/app/assets/javascripts/components/common/text_input.cjsx#L35-L48)

My short-term fix for this has been to downgrade to 0.9.0, introducing different bugs. :) I first noticed this a couple of releases ago and tried to find the problem with no success, I suspect the problem is specific to my implementation.

Any ideas? Thanks!

**Comment by ntdb** [comment]
Naturally, I found some answers after logging an issue. :) I've traced it back to #129. I'm using a custom onBlur callback which causes [this code](https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L61-L64) to run, closing the calendar. My first thought is to simply add

```js
this.setState({
  virtualFocus: true
});
```

to the `increaseMonth` and `decreaseMonth` functions... but `handleBlur` gets called after them and resets `virtualFocus` to false.

**Comment by martijnrusschen** [comment]
Is this still happening. We made some changes around the virtualFocus element. Curious if this solved your issues too.

**Comment by ntdb** [comment]
Ping @thenickcox: if you get the chance, please update this library to latest and report back. Thanks. :)

**Comment by ntdb** [comment]
I'm experiencing this out of the box with 0.15.2 and React 0.14.2... but without an onBlur this time. I'll try to track it down.

**Comment by bjpbakker** [comment]
This bug also shows up in the onBlur example: https://hacker0x01.github.io/react-datepicker/#example-9

**Comment by ntdb** [comment]
Working on tracking this down. The problem seems to be with [this code](https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L67-L76). Is there a case where `virtualFocus` is set back to `true` during that 200ms timeout?

**Comment by ntdb** [comment]
Ping @at0g. Any thoughts on what's happening here? [The original implementation of `handleBlur`, for reference](https://github.com/Hacker0x01/react-datepicker/commit/99643b9da343c223a4fcd9610505aa5d349c8a1f#diff-f662ae56197d5c888897a02b982f0ad3).

It appears that `onBlur` is fired by the input when clicking on the popover (tested in FF, Safari, Chrome). This seems like a pretty fundamental problem... months are changeable if `onBlur` is set to a non-function. Unfortunately, that means that tabbing out of an input does not close the popover (observable in [the examples](https://hacker0x01.github.io/react-datepicker)); this is particularly problematic on mobile.
