### ISSUE TITLE
Allow to set when time picker starts

### ISSUE THREAD

**Issue by jamesattard** [Hacker0x01/react-datepicker#1582]
### Expected behavior
Allow to set the timepicker to start at a specified time. This will be useful if you have a 1hr interval to display only times like: 8:30AM, 9:30AM, 10:30AM, etc..

### Actual behavior
At the moment there is no option to set the time. Even if you set the minTime to, for example, 8:30AM, while the interval is set to one hour, the timepicker will start at 9AM. 

In other words, by default it shows on the hour, ex. 8:00AM, 9:00AM, etc. This is not flexible if you want to display timeslots that are not necessarily on the hour.

### Steps to reproduce
```
            <FixDatePickerTimer>
              <DatePicker
                inline
                onChange={this.handleChange}
                showTimeSelect
                timeFormat="HH:mm"
                timeIntervals={60}
                timeCaption="time"
                minTime={moment()
                  .hours(8)
                  .minutes(30)}
                maxTime={moment()
                  .hours(17)
                  .minutes(30)}
              />
```

![reactpicker](https://user-images.githubusercontent.com/3464559/50021085-3e6ab700-ffd8-11e8-9502-dbdff0895532.PNG)

**Comment by saltire** [comment]
A shame this was closed; it's a valid issue.

**Comment by moeatsy** [comment]
yep, still actual

**Comment by KamilPesek** [comment]
This could work similar to "openToDate={new Date("1993/09/28")}".

**Comment by abeonweb** [comment]
This is still an issue. Can't find a workaround.
