### ISSUE TITLE
problem in Year select dropdown

### ISSUE THREAD

**Issue by SajagTiwari** [Hacker0x01/react-datepicker#1586]
### Steps to reproduce:- open the Year select dropdown, change the year with the keyboard with value 1500. the value is changed in the input field but not in the year drop-down(it only shows till 1900)
![image](https://user-images.githubusercontent.com/13046829/50204489-1211ba80-038b-11e9-8131-a3e034e9fade.png)
![snapshot](https://user-images.githubusercontent.com/13046829/50204535-34a3d380-038b-11e9-8796-d085bc4f3afd.JPG)

**Comment by SajagTiwari** [comment]
if we remove dropdownMode="select" then its working fine.

**Comment by nassihmahmoud** [comment]
![image](https://github.com/Hacker0x01/react-datepicker/assets/7226382/6e48155b-47f1-49dc-be74-c328a1aa02e4)
