### ISSUE TITLE
Time selection does not fire onSelect event

### ISSUE THREAD

**Issue by haizz** [Hacker0x01/react-datepicker#1590]
### Expected behavior

Time selection fires onSelect event.

### Actual behavior

Time selection does not fire onSelect event.

### Steps to reproduce

Trivial

**Comment by yshap** [comment]
Hey, could someone give me information on this issue? I have the same problemю Why does on Select event do not fire with time selection?

**Comment by haizz** [comment]
up

**Comment by GilbertMizrahi** [comment]
I have the same problem

**Comment by alihusic** [comment]
I just faced the same problem, please use onChange prop, since onSelect is probably an internal call.

**Comment by haizz** [comment]
onChange fires up on keyboard entry events as well, but I need specifically to capture an event of user choosing time with time selector to close the selector and save the edit. 
Also, "closeOnSelect" closes on date selection not allowing to choose time.
"onSelect" is not an internal call, it is explicitly mentioned in the second example on README page.
