### ISSUE TITLE
Parsed date is off by one for ISO date input

### ISSUE THREAD

**Issue by rosslh** [Hacker0x01/react-datepicker#1592]
### Expected behavior

Input `2018-08-28` should be parsed as `08/28/2018`

### Actual behavior

Input `2018-08-28` is parsed as `08/27/2018`

### Steps to reproduce

Type a date in `YYYY-MM-DD` format into the first datepicker on [the examples website](https://reactdatepicker.com/)

Browser: Firefox 64.0

**Comment by kwayebopp** [comment]
This issue is still persisting. Furthermore, converting the DatePicker value into an ISO string returns a date one day ahead of the expected date. What might be causing this?

**Comment by wmertens** [comment]
Hypothesis: This is most likely caused by time zone. The YYYY-MM-DD is parsed as midnight in the UTC timezone and then converted to a local date format with the local time zone. If you're ahead of UTC, this will move the time part to the previous day.

**Comment by DylanCStack** [comment]
@kwayebopp @rosslh I'm not too knowledgable on dates or the datepicker, but I had a similar issue where the date I typed in was rendered as one day in the past from the desired date.

I had to add the timezone offset to the value that I was passing in to the datepicker as the selected date. Something like this:
```
	render() {

		let value = this.props.value; // a Date object

		value.setTime(value.getTime() + value.getTimezoneOffset() * 60000); // include the timezone

		return (
			<DatePicker
				selected={value}
				onChange={this.handleChange}
				onSelect={this.handleChange}/>
		);
	}
```
