### ISSUE TITLE
Datepicker with Custom Input. When click on tab button, popup is not disappear(onBlur doesn't close popup).

### ISSUE THREAD

**Issue by frontendbro** [Hacker0x01/react-datepicker#1595]
### Expected behavior
Datepicker popup disappears after onBlur event.

### Actual behavior
Datepicker popup is not disappears.

### Steps to reproduce
1. Goto https://reactdatepicker.com -> Custom input
2. Click on button
3. Click TAB button

**Comment by gialdeyn** [comment]
+1
You can open popup with onFocus, but still can't close it. So if you have several inputs and go with TAB through them — you will get all popups opened.

**Comment by toanqc** [comment]
+1 any workaround for this issue?

**Comment by toanqc** [comment]
I found the workaround solution by using the onKeyDown on the custom input and check the tab key event

onKeyDown = event => {
    // Close the calendar when user using 'Tab' key to tab off the custom input
    if (event.which === 9) this.calendar.current.setOpen(false, true);
};

**Comment by Megamouse** [comment]
A workaround is not a fix.
Please reopen
