### ISSUE TITLE
Is there any feature like customizing clearable button?

### ISSUE THREAD

**Issue by bodguy** [Hacker0x01/react-datepicker#1597]
### Expected behavior
feature like styling clearable (x) button or props like onClearClick to fully customizing my own button.

### Actual behavior
I can't find any customizable options.

**Comment by returnzer0** [comment]
Did you find out if such an option exists @bodguy ?

**Comment by bodguy** [comment]
@returnzer0 nope, I customize datepicker component to use such a feature.

**Comment by returnzer0** [comment]
@bodguy do you mind sharing how you went about it? Trying to do the same thing but I don't know how. Did you use the onChange listener?
