### ISSUE TITLE
Problem with date picker Year selector not working on Firefox

### ISSUE THREAD

**Issue by pareshmutha** [Hacker0x01/react-datepicker#1599]
### Expected behavior
Year Drop down must work on Firefox.
### Actual behavior
Year Drop down not working on Firefox.
### Steps to reproduce
Run the datepicker example on latest firefox.

![firefox](https://user-images.githubusercontent.com/5389741/50889279-a10b7300-141d-11e9-8716-f6cd7a10b0e0.PNG)

**Comment by pareshmutha** [comment]
Issue was with momentjs

**Comment by YajashJhamb** [comment]
@pareshmutha Can you please explain what was the issue and  how you solved it with momentJs

**Comment by pareshmutha** [comment]
@YajashJhamb ,

I have used 
minDate = moment('1970-01-02');
Above code solved my problem.
As Firefox doesn't support some Date functions, so we have to use moment (version - 2.22.2)

Please try and let me know if it works.
