### ISSUE TITLE
onFocus doesn't fire when focusing on all parts of the datepicker

### ISSUE THREAD

**Issue by togakangaroo** [Hacker0x01/react-datepicker#1601]
### Expected behavior
When focus shifts to the next/prev month arrows I would expect onFocus since what I'm interested in is knowing that focus is on the control itself

### Actual behavior
Focus events seem to only fire when focusing on the date buttons

### Steps to reproduce

```
<DatePicker selected={null} inline
  onFocus={e => console.log(`focused`)} />
```

observe that focus does not fire consistently as you click around the datepicker

A workaround for me was to wrap it in a `<div>` and use refs to wire up to `focusin` and `focusout` events

**Comment by togakangaroo** [comment]
I disagree with this being closed. It is still a bug. I see it got labeled as wontfix which means it should at least get an explanation and documentation, right?

**Comment by remmel** [comment]
This is an important event. Too bad it cannot be fixed.
