### ISSUE TITLE
Invariant Violation: View config not found for name input

### ISSUE THREAD

**Issue by huynguyen2903** [Hacker0x01/react-datepicker#1604]
### Expected behavior
Invariant Violation: View config not found for name input
I got this error. Please help me solved it. Thanks!
### Steps to reproduce
![image](https://user-images.githubusercontent.com/40721082/51233944-e855ae80-199d-11e9-8334-6823382d8761.png)

**Comment by jiangli1984** [comment]
I have the same issue...any solution?

**Comment by jiangli1984** [comment]
> ### Expected behavior
> Invariant Violation: View config not found for name input
> I got this error. Please help me solved it. Thanks!
> 
> ### Steps to reproduce
> ![image](https://user-images.githubusercontent.com/40721082/51233944-e855ae80-199d-11e9-8334-6823382d8761.png)

it does not support on RN...just got it..
