### ISSUE TITLE
'yyyy' vs 'YYYY'

### ISSUE THREAD

**Issue by ArtemBernatskyy** [Hacker0x01/react-datepicker#1609]
### Expected behavior

I'm using Moment.js and react-datepicker.  
Also I use `YYYY-MM-DD` for both packages.

For the same date Moment.js gives me `2019-02-08`  
react-datepicker gives me `2019-02-39`  

    <DatePicker
      selected={this.state.tempDate}
      showTimeSelect={false}
      className="form-control"
      dateFormat="YYYY-MM-DD"
      placeholderText="Add date to exclude"
      onChange={date => this.setTempDate(date)}
    />

**Comment by mvenaas** [comment]
Moment.js was removed as part of v2.0. 
I am also experiencing problems with react-datepicker showing a days corresponding "number" in a year rather than the date. Have you found a solution yet?

**Comment by ArtemBernatskyy** [comment]
@mvenaas nope (

**Comment by mvenaas** [comment]
I downgraded from v2.0 to v1.8 and continued with Moment.js while in search for a better solution.

**Comment by markokosir** [comment]
@ArtemBernatskyy  @mvenaas since there is no more Moment.js dependency you should use date format in your case like so `dateFormat={'yyyy-MM-dd'}`

**Comment by ArtemBernatskyy** [comment]
@markokosir the problem is in inconsistency.

Date is the same but `dateFormat` differs from `moment.js` - which is very bad.

**Comment by benbcai** [comment]
I'm switching from moment to date-fns and encountered the same issue. Take a look at https://blog.date-fns.org/post/unicode-tokens-in-date-fns-v2-sreatyki91jg.

**Comment by xxyuk** [comment]
Day.Js is a nice alternative to me, supper small and the same date format. May be we could consider using it as a replacement of date-ins

⏰ Day.js 2KB immutable date library alternative to Moment.js with the same modern API

https://github.com/iamkun/dayjs
