### ISSUE TITLE
Calendar does not hide when pressing Enter in IE

### ISSUE THREAD

**Issue by sconno05** [Hacker0x01/react-datepicker#161]
Steps to reproduce:

1 Go to example page: https://hacker0x01.github.io/react-datepicker/
2. In the first example (Default), enter a new value into the input field and press enter
3. The calendar does not close, but it will close in Chrome/Firefox

Tested in IE9, IE10, IE11 - all have the same behavior

**Comment by tomhirschfeld** [comment]
+1 here, having the issue in IE.

**Comment by benmliang** [comment]
+1, on IE 11, The calendar doesn't close, flash back and forth.

**Comment by gweinert** [comment]
+1 here. On IE 11, 10, 9. I also see the calendar flash back and forth.

**Comment by fabricior** [comment]
+1

**Comment by rcoy-v** [comment]
I added a new [issue](#309) for the recent flashing issue in IE, as this thread is for a separate bug.

**Comment by martijnrusschen** [comment]
Should be fixed with #319.

**Comment by rafeememon** [comment]
Yup, just verified
