### ISSUE TITLE
how to change default locale to locale ru

### ISSUE THREAD

**Issue by 3a6aBHo** [Hacker0x01/react-datepicker#1616]
### Expected behavior
in Date picker month names like [Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август, Сентябрь,Октябрь,Ноябрь,Декабрь]
how can i localize month and weeks to RUS
### Actual behavior
in actual, date picker months in eng.
### Steps to reproduce
import DatePicker,{registerLocale,setDefaultLocale} from "react-datepicker"
import "react-datepicker/dist/react-datepicker.css"
import { ru } from "date-fns/locale/ru/index.js";
registerLocale('ru',ru);
setDefaultLocale('ru');

return(
     <DatePicker
                                locale={ru}
                                formatWeekDay={ru}
                                onSelect={this.handleChange}
                                dateFormat="YYYY-MM-DD"
                                shouldCloseOnSelect={true}
                                showYearDropdown={true}
                                scrollableYearDropdown={true}
                                yearDropdownItemNumber={101}
                            />
)

![azzaa](https://user-images.githubusercontent.com/12620709/51737371-9c4dec80-20b6-11e9-896e-1b09285ef7ab.PNG)

**Comment by golubvladimir** [comment]
package.json

`"date-fns": "^2.0.0-alpha.23",`

component.js

```
import ru from 'date-fns/locale/ru';
...
<DatePicker
  locale={ru}
>
```

**Comment by zelucena** [comment]
`import ptBR from 'date-fns/locale/pt-BR';
...
registerLocale('pt-BR', ptBR);
`

Thanks, it worked just as fine to me
