### ISSUE TITLE
Wrong default time if specified range

### ISSUE THREAD

**Issue by keery** [Hacker0x01/react-datepicker#1625]
Hi all 🖖

I'm confronted to a problem, I've date picker with specified range of time, between 11 to 16.
But by default when I choose a date without time, the returned value is "DD/MM/YYYY 00:00".
In fact, to a different point of view this be normal, but "00:00" it's not included in my time range and the user can leaves the date picker without choosing a time and in this case he will have a wrong time. 

```` jsx
<DatePicker
    selected={this.state.startDate}
    name={name}
    onChange={this.onDateChange}
    dateFormat={dateFormat}
    autoComplete="off"
    required={required}
    showTimeSelect
    minTime={moment().hour(10)}
    maxTime={moment().hour(16)}
/>

**Comment by adamthewan** [comment]
You have to do 
`  minTime={moment().hour(10).toDate()}
    maxTime={moment().hour(16).toDate()}`
