### ISSUE TITLE
dateFormat="DD/MM/YYYY" doesnt work

### ISSUE THREAD

**Issue by jjjss94** [Hacker0x01/react-datepicker#1628]
When i have on 2019-02-01: 
  <DatePicker
                    className="form-control"
                    selected={new Date()}
                    dateFormat="DD/MM/YYYY"
                  />

i get:
![captura](https://user-images.githubusercontent.com/47239689/52109705-b7f94b80-25fe-11e9-8e28-008930451677.PNG)

**Comment by Valerika** [comment]
use dd/MM/YYYY

**Comment by jjjss94** [comment]
Wow!! Youre my savior today! Its works thx

**Comment by Trym-H** [comment]
> use dd/MM/YYYY

I had to use "dd/MM/yyyy" or else the console would yell at me.

**Comment by pravin-gnanaolivu** [comment]
Try to edit the day its not changing defaults to the previous value
