### ISSUE TITLE
Picking a date is not added to the input box when input box is not in view

### ISSUE THREAD

**Issue by beatfreaker** [Hacker0x01/react-datepicker#1631]
### Expected behavior
- when selecting date when the textbox is not in view, the date should get selected and the selected value should be populated in textbox.

### Actual behavior
- when selecting date when the textbox is not in view, the date is not getting selected and the scroll jumps to textbox without populating selected date.

![ezgif com-optimize](https://user-images.githubusercontent.com/4180238/52264096-d8a30780-2956-11e9-8960-b547c3a86a04.gif)

### Steps to reproduce
- Go to https://reactdatepicker.com/
- Zoom the webpage
- Now selected the textbox to show calander
- Scroll so that input box is not in the view but you still able to select some date
- Select the date.
- Check above attached GIF

**Comment by beatfreaker** [comment]
Tried debugging the click event and found below details
- when it is working properly, below is the path captured by `react-dom`, and we can see the origin click event is from the day.
![image](https://user-images.githubusercontent.com/4180238/52465071-46dc0a00-2ba3-11e9-98ea-5c1ce004b638.png)

- when it is not working, below is the path captured by react-dom, and here the origin of click event is from month div and not from day div.
![image](https://user-images.githubusercontent.com/4180238/52465016-18f6c580-2ba3-11e9-82bd-d3ba59e32fcf.png)

got these path details from below function of `react-dom`
```js
/**
 * Simulates the traversal of a two-phase, capture/bubble event dispatch.
 */
function traverseTwoPhase(inst, fn, arg) {}
```
and call stack is as below
![image](https://user-images.githubusercontent.com/4180238/52465226-dda8c680-2ba3-11e9-8ee8-fb351dccc444.png)

**Comment by Gauri-P** [comment]
I am also facing exact same issue. Is there any solution to this?
