### ISSUE TITLE
Is there a changelog anywhere?

### ISSUE THREAD

**Issue by Dakkers** [Hacker0x01/react-datepicker#1639]
### Expected behavior
N/A
### Actual behavior
N/A
### Steps to reproduce
N/A

Really, I'd just like to know what changes in each version before upgrading to a potentially broken version.

**Comment by flppv** [comment]
You can check this https://github.com/Hacker0x01/react-datepicker/releases

(As for me it's broken now, don't upgrade yet)

**Comment by Dakkers** [comment]
For 2.1.0, there isn't any description, and the commit representing the change is just a version bump. 😭

**Comment by martijnrusschen** [comment]
I guess I forgot to add, but you can simply check out the commits done between 2.0 and 2.1.
