### ISSUE TITLE
Virtual keyboard on mobile phone pops up

### ISSUE THREAD

**Issue by c0debreaker** [Hacker0x01/react-datepicker#1640]
When I visit my app on desktop, everything is great! However, when I open it from my phone and I click the input field of react-datepicker, my phone thinks I'd like to enter data.

So I tried the prop `readOnly` but unfortunately, it disables the calendar. When I click the input, nothing happens.

Any workaround to this? Maybe instead of `<input`>, it should be `<button>`?

**Comment by samhstein** [comment]
same issue here, button or read only custom input would probably work, but it would be nice to have an option to hide the keyboard.

**Comment by allenaveen** [comment]
I am also getting the same issue. Any solution on this?

**Comment by rista86** [comment]
Having same problem and still no fix on this. Tried fix from [other topic](https://github.com/Hacker0x01/react-datepicker/issues/1480#issuecomment-445163098) but that didn't worked for me.

**Comment by c0debreaker** [comment]
Folks, I switched to `material-ui-pickers`. I love it! No issues on their DatePicker.

**Comment by jakks-team** [comment]
Workaround by @tinuts works very well.
Thank you.

BUT, this is a workaround. Can't they just provide a props for this?

**Comment by Dan2D** [comment]
Simple Fix by setting onFocus={(e) => e.target.readOnly = true} to the DatePicker Component

**Comment by charlesoma** [comment]
Thanks @Dan2D, fix worked for me too

**Comment by sudokzt** [comment]
Thanks @Dan2D , your solution helped me.

**Comment by vipulchakravarthy** [comment]
Thanks @tinuts it works

**Comment by Dujota** [comment]
Updated answer for anyone who is struggling with this problem, specifically with IOS, Safari or Iphones and does not want to create a custom input. 

```
  const handleFocus = (e: ReactClickEvent<HTMLInputElement>) => {
    const { target } = e;

    if (target) {
      target.readOnly = true;  // -------> this for all others
      target.blur(); //  ------> this for ios iphone
    }
  };
```
