### ISSUE TITLE
react-datepicker does not  'registerLocale'.

### ISSUE THREAD

**Issue by shmulikamin** [Hacker0x01/react-datepicker#1643]
I'm trying to do an IMPORT to registerLocale  like this. 

import { registerLocale } from 'react-datepicker';
And that's the result:
'react-datepicker' does not contain an export named 'registerLocale'.

**Comment by evaldosantos** [comment]
I have faced the same problem @shmulikamin. I figure out that it's a named export.

import DatePicker, { registerLocale } from "react-datepicker";

You can check it here: https://github.com/Hacker0x01/react-datepicker/blob/master/docs-site/src/examples/locale.jsx

**Comment by shmulikamin** [comment]
Thanks
But I tried it already, and I still get the same message

**Comment by evaldosantos** [comment]
ah sorry, my bad, I thought you were trying to import it directly like:
import registerLocale  from "react-datepicker";

**Comment by AbhishekGowda28** [comment]
Check the version you are using, if you using previous versions update to the latest one.

I faced the same problem with older versions, updating to newer version fixed the issue.

**Comment by Rutulpatel7077** [comment]
I have same issue. How do I solve it ?

`import DatePicker, { registerLocale } from 'react-datepicker';`

![image](https://user-images.githubusercontent.com/22271244/58727906-a01ab400-83b3-11e9-805b-15c6d04af821.png)

**Comment by jkepps** [comment]
I am also seeing this issue in my production build, but not in my dev environment... my production build is using the minified build and giving me this error. any suggestions?

**Comment by simonatoluca** [comment]
> I am also seeing this issue in my production build, but not in my dev environment... my production build is using the minified build and giving me this error. any suggestions?
> 
> version 2.9.6

Hi guys. I found this solution that works for me

`import DatePicker, { registerLocale } from "react-datepicker/dist/es"`
