### ISSUE TITLE
utcOffset property no longer exists

### ISSUE THREAD

**Issue by koss-lebedev** [Hacker0x01/react-datepicker#1647]
It seems that after this library was refactored to use `date-fns` instead of `moment.js`, the property `utcOffset` referred in the documentation [here](https://github.com/Hacker0x01/react-datepicker/blob/f0d4c560c3f5722366c553bbbca3748cd03688fe/docs/datepicker.md) no longer exists. What is the proper way to set timezone offset for this component now?

Thanks!

**Comment by loopdtw** [comment]
would also like to know this as well!

**Comment by glitterk** [comment]
+1. Want to know if you have a plan to fix this.

**Comment by bugeats** [comment]
AFAIK `date-fns` does not have the time zone / offset support that `moment.js` does.

**Comment by AmberWilliams** [comment]
This is still a huge problem otherwise the dates are offset by a day depending on timezones

**Comment by RafaPolit** [comment]
Having this problem as well.  I have to double convert values by hand.  This issue is here since around March, any info on updates?  Thank you.

**Comment by kortik425** [comment]
this is still an issue afaik?

**Comment by michaelmesser** [comment]
What is the solution to this issue?

**Comment by Yueran-Yu** [comment]
No one think about the solution so far?

**Comment by keeeeith** [comment]
Still an issue.

**Comment by evankazadaiev** [comment]
Still an issue

**Comment by hanzenok** [comment]
Still an issue

**Comment by ayushjainmm** [comment]
Still an issues

**Comment by sheldonmaschmeyer** [comment]
Using `date-fns-tz` package I believe I have been able to workaround the issue but, should not need to.
Switching from `moment` to `date-fns` is a good choice. Using `date-fns-tz`, this feature could likely be re-implemented.

**Comment by tannermann** [comment]
This is still an issue and should be re-opened.

**Comment by AndySmrt** [comment]
Still an issue

**Comment by aliemdadi** [comment]
Any updates on this?
The utcOffset prop was not valid in version 7.3.0, but now in 7.4.0, it is a valid prop. However, it still doesn’t seem to work.
