### ISSUE TITLE
dateFormat doesn't work correctly

### ISSUE THREAD

**Issue by flppv** [Hacker0x01/react-datepicker#1649]
### Expected behavior
Before update I was using this dateFormat: `dateFormat="M/D/YYYY"` and it was showing date like: **2/28/2019** for 28 Feb 2019
### Actual behavior
After update it shows **2/58/2019**

I saw [this issue](https://github.com/Hacker0x01/react-datepicker/issues/1628) which shows date in non-broken format at least, but what should I do if I don't need leading zeros? 

Please add correct formats support

**Comment by flppv** [comment]
Oh, I just found that it works fine with "M/d/YYYY"

**Comment by activebiz** [comment]
@flppv how did you found the format?

**Comment by flppv** [comment]
@activebiz I just tried until it worked as expected
