### ISSUE TITLE
Select date don't work when I have a other input field behind the calendar

### ISSUE THREAD

**Issue by Xifeat** [Hacker0x01/react-datepicker#1651]
### Expected behavior
Date picker work perfectly with keyboard,
If I use the mouse, it's not working in my red area (screen my screenshot)

### Actual behavior
See the screen below : 
The bleu area works, the date is set well, probably because behind I have the toolbar instead of an input
but if I click on the red part, the value is not set and it focus my draftJs editor behind.

<a href="https://ibb.co/9YW7tDs"><img src="https://i.ibb.co/12Tk6g8/weird.png" alt="weird" border="0"></a>

How can I handle this ?

**Comment by seungmin3577** [comment]
I have the same problem.
