### ISSUE TITLE
The `id` attribute doesn't get passed down to provided `customInput` 

### ISSUE THREAD

**Issue by ankurkaushal360** [Hacker0x01/react-datepicker#1653]
### Expected Behaviour
The `id` attribute gets passed down to the provided `customInput`.

### Actual Behaviour
The `id` attribute isn't showing up in the underlying `input` element provided via the `customInput` prop. 

### Steps to reproduce
Here's a very simple example reproduced in [codesandbox](https://codesandbox.io/s/o9wmqwmy5).

Also, here's a screenshot of the same:

![image](https://user-images.githubusercontent.com/31927177/53663942-18e36600-3c35-11e9-8320-caf493e0672b.png)

![image](https://user-images.githubusercontent.com/31927177/53663957-27ca1880-3c35-11e9-8b1e-61f53ab1e7e4.png)

**Comment by alobban** [comment]
Has this issue been resolved? I am looking to pass the `id` attribute as well down to the input field.

**Comment by vahidd** [comment]
It's because `id` and some other props of `<CustomInput />` are being overridden. 
https://github.com/Hacker0x01/react-datepicker/blob/5fd5cb4fb9b0e82e30d072a36d441faf30738425/src/index.jsx#L903
So you should pass `id` to `<DatePicker />`:
```javascript
<ReactDatePicker
    customInput={<CustomInput maxLength={10} />}
    openToDate={new Date()}
    id="dummy-id"
/>
```
