### ISSUE TITLE
Day of date in input wrong

### ISSUE THREAD

**Issue by stepseazy** [Hacker0x01/react-datepicker#1654]
### Expected behavior
Display date of dateTime object
### Actual behavior
displays number larger than number of days in the month. when March 14 2019 is chosen, it shows 2019/03/73 16:00
### Steps to reproduce
```
const DateInput = ({
  input,
  width,
  placeholder,
  meta: { touched, error },
  ...rest
}) => {
  return (
    <Form.Field error={touched && !!error} width={width}>
      <DatePicker
        {...rest}
        placeholderText={placeholder}
        selected={input.value ? input.value : null}
        onChange={input.onChange}
      />
      {touched && error && (
        <Label basic color="red">
          {error}
        </Label>
      )}
    </Form.Field>
  );
};
```

```
              <Field
                name="date"
                type="text"
                component={DateInput}
                dateFormat="YYYY-MM-DD HH:mm"
                timeFormat="HH:mm"
                showTimeSelect
                placeholder="Date and Time of Event"
              />
```

**Comment by stepseazy** [comment]
![capture](https://user-images.githubusercontent.com/16912092/53673600-6237b380-3c3d-11e9-864a-02464e3bc0b6.JPG)

**Comment by benbcai** [comment]
@stepseazy Try changing your `dateFormat` to `yyyy-MM-dd HH:mm` and see if that fixes your issue. See https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md#popular-mistakes

**Comment by stepseazy** [comment]
Did the trick. Thanks a bunch, great library
