### ISSUE TITLE
Can't select the most recent available date of the date range using the arrow keys.

### ISSUE THREAD

**Issue by owad** [Hacker0x01/react-datepicker#1662]
### Expected behavior
If my date range is 2019-03-01 - 2019-03-13, I should be able to go all the way to the 2019-03-13 using arrows.

### Actual behavior
I'm getting stopped on the 2019-03-**12** and I have to use a mouse to select 2019-03-13.

### Steps to reproduce
Go to https://reactdatepicker.com/#example-13 (Specific Date Range example), click the input field and try selecting the last date (03/18/2019) with **arrow keys only**. 

### A note ###
In my case it is actually the other way around. I can't select the very first date (2019-03-01).

**Comment by AnthonyCrowcroft** [comment]
I am also experiencing this bug and am noticing it on both ends when there are boundaries set on the available dates able to be picked
