### ISSUE TITLE
Return an event just as any input. 

### ISSUE THREAD

**Issue by josuevalrob** [Hacker0x01/react-datepicker#1664]
I am making a form, with multiple fields, all my fields send a prop to the parent component, just like this: 
**ChildComponent**
```
function NameInput (props) {  
  return (
    <React.Fragment>
      <label htmlFor="username">Nombre de Usuario</label>
      <input
        className="form-control"
        id="username"
        name="username"
        type="text"
        placeholder="Enter username"
        value={props.data}
        onChange={props.handleChange}
        />    
    </React.Fragment>
  )
};
```
The on change method, in the parent element, call action and add the new property to my state, with redux, and all the crazy things... 

**ParentComponent**
  ```
handleChange = event => {
    const {name, value} = event.target
    this.props.addField({...this.props.user, [name] : value})
  }
```

It works fine with any type of field, like names, email, etc etc... But this workflow doesn't work with react-DatePicker, this is my current approach: 

```
function birthInput(props) {  
  return (
  <React.Fragment>
    <label htmlFor="username">Año de nacimiento</label>
    <DatePicker 
      name="nacimiento" 
      selected={props.data} 
      onChange={props.handleChange} />
  </React.Fragment>
  )
};
```

But, checking out what I get in my on change method, and found a simple date: 
_Wed Mar 20 2019 16:00:39 GMT+0100 (hora estándar de Europa central)_

### Expected behaviour
Return the event from the input field. 

### Actual behavior
a dateObject

### Steps to reproduce
Follow the example.

**Comment by goldfarbdev** [comment]
I've been scouring the internet for the same answer.  I want to access the Event object and not the Date object or access both.  I especially need this because I'm dynamically adding multiple field instances which creates an updated array for each add, so I NEED the index number as well as the name value to update the array in the state.

Thank you!

**Comment by goldfarbdev** [comment]
@josuevalrob I found a solution that helps.  

Use the onFocus method to access the input.

getName(e) {
        return this.setState({currentName: e.target.getAttribute('name')});
}

validate(e) {
       const inputName = this.state.currentName;

}
render() {
`<Datepicker 
    name="the name"
    onFocus={this.getName.bind(this)}
    onChange={this.validate.bind(this)}
/>`
}

**Comment by josuevalrob** [comment]
It works, in fact, if I check the event onFocus, I got all that I need, but I want to separate the logic from my birthday component. Is there a way to avoid managing states in the component?. **I don't want to create a class component at this level**, so I tried this: 

```
const NacimientoInput = (props) => {  
  return (
  <React.Fragment>
    <label htmlFor="username">Año de nacimiento</label>    
    <DatePicker
        selected={!props.data ? new Date() : props.data} 
        name = "nacimiento"
        onFocus={props.handleChange}
        className={`form-control ${ props.style }`}
        showYearDropdown
        dateFormatCalendar="MMMM"
        scrollableYearDropdown
        yearDropdownItemNumber={50}
      />
  </React.Fragment>
  )
};
```

In my _handleChange_ method, in the parent component, I got the `event.target`, with all the toys, the name and the value. But, something goes wrong with the date picker:

> Warning: Failed prop type: Invalid prop `selected` of type `String` supplied to `DatePicker`, expected instance of `Date`.

> Warning: Failed prop type: Invalid prop `selected` of type `String` supplied to `Calendar`, expected instance of `Date`

> Warning: Failed prop type: Invalid prop `date` of type `String` supplied to `YearDropdown`, expected instance of `Date`

> Warning: Failed prop type: Invalid prop `selected` of type `String` supplied to `Month`, expected instance of `Date`.

The date from the state didnt update: 

```
    identificacion: {
      email: '',
      username: '',
      password: '',
      sexo: '',
      nacimiento: 'Invalid Date',
      nif: ''
    }
```

I will check my actions and my reducer to get any clue. 

thanks anyway.

**Comment by josuevalrob** [comment]
At the end, I did this on my `handleEvent `from the Form. 

```
handleChange = event => {
    if(event instanceof Date ){ //This conditional sucks!
      this.props.addField({...this.props.user['identificacion'], ['nacimiento'] : event})
    } else { //the rest of inputs changes... 
```

**Comment by linkerx** [comment]
@josuevalrob las one is a good solution if you only have one date, i want to dynamically add from several datepickers, and its imposible without event target.
Solution: one handler for every datepicker

**Comment by josuevalrob** [comment]
> @josuevalrob las one is a good solution if you only have one date, i want to dynamically add from several datepickers, and its imposible without event target.
> Solution: one handler for every datepicker

I will need to da that later, can you share your code? thanks!

**Comment by josuevalrob** [comment]
> @josuevalrob las one is a good solution if you only have one date, i want to dynamically add from several datepickers, and its imposible without event target.
> Solution: one handler for every datepicker

Yo dont need one handler for every datapicker, just send a second param when you call the handleChange function, something like this: 

`handleChange = {(e) => {this.handleChange(e, 'inicio')}}`

and consume it like this: 

```
handleChange = (event, txt) => {
		let rdSocial = [...this.props.estudios]
		if(event instanceof Date ){
			rdSocial[id][txt] = event
			this.props.addEstudioField(rdSocial)
		} else {
			....
```

**Comment by shimulcse22** [comment]
hei @josuevalrob 
Can you help me out. um  facing the same problem,
um using hook for localstate and dynamically rendering some DatePicker input.
i need event.target how can i get.
Thanks in advanced

**Comment by lodab111** [comment]
I came across this issue of not being able to get the data i needed from the event of the input.  I am creating each input dynamically and I am reading the name of the event.target to decide where to update my state.  I found that I was able to hack it a bit and just create an object to mock the data I needed from the event.target object. 

`DatePicker = (fieldData) => {
return (
  <DatePicker 
  selected={fieldData.Value}  
  isClearable
  className="DatePickerTextArea"
  onChange={(value, event) => {
	event.target = {type:"text", value:value, name:fieldData.Name}
	fieldData.ChangeHandler(event)
  }}
   />
);
}`

**Comment by hedge-talha** [comment]
> @josuevalrob I found a solution that helps.
> 
> Use the onFocus method to access the input.
> 
> getName(e) { return this.setState({currentName: e.target.getAttribute('name')}); }
> 
> validate(e) { const inputName = this.state.currentName;
> 
> } render() { `<Datepicker name="the name" onFocus={this.getName.bind(this)} onChange={this.validate.bind(this)} />` }

Still there is no value in the event.target object. How do i get value
