### ISSUE TITLE
Inline calendar shifts months when a date is selected

### ISSUE THREAD

**Issue by cmangia47** [Hacker0x01/react-datepicker#1665]
### Expected behavior
We are displaying an inline calendar that spans 12 months from Jan through Dec for a particular year. Our application is meant to allow a user to toggle the state of a business process for a specific date. When a user clicks on a date we update the background color to indicate its is now "active". I expect the calendar to remain static meaning the same full year calendar will be displayed regardless of how many dates are clicked on by the user.

### Actual behavior
If you click any date, the display seems to jump by that many number of months ahead or back depending on how many months away from January you click.

### Steps to reproduce
So to explain in more detail, suppose we are displaying an inline calendar for Jan through Dec 2019. If I click any date in January, after the updates execute and the component is rendered, I still see a calendar from Jan 2019 - Dec 2019. If I click a date in February 2019 the calendar shifts back one month to display Dec 2018 through Nov 2019. If I click a date in March 2019, the shift is 2 months back (Oct 2018 - Oct 2019). If you now click any day in Dec 2018, the calendar shifts one month in the other direction. You can repeat this until you are once again viewing Jan 2019 - Dec 2019. I have confirmed the values for startDate and openToDate are 2019-01-01 and monthsShown = 12. Are these not the values that determine the calendar dates which are visible?

**Comment by cmangia47** [comment]
Sorry forgot the mention we are using version 2.2.0

**Comment by shettyashwitha** [comment]
+1

**Comment by Helpermedia** [comment]
With "inlineFocusSelectedMonth={true}" the jumping does not occur. Which seems strange, I would expect the opposite (see: https://github.com/Hacker0x01/react-datepicker/pull/1541).

However "inlineFocusSelectedMonth={true}" works for me now and prevents the jumping.

**Comment by cmangia47** [comment]
Thank you! We will try this

**Comment by cmangia47** [comment]
Adding property "inlineFocusSelectedMonth={true}" seems to stop the calendar from jumping to month selected when using the the inline calendar
