### ISSUE TITLE
Strange behaviour when dateFormat includes date and time

### ISSUE THREAD

**Issue by mxsmirnoff** [Hacker0x01/react-datepicker#1667]
I made input with `dateFormat` that includes date and time formats and try to enter date without time.
### Expected behavior
Clear input or format with date part of `dateFormat`
### Actual behavior
In cases when `dateFormat="dd/MM/yyyy HH:mm:ss"` (with slashes) it clears input when dd > 12 and swap date and month when dd < 12.
In cases when `dateFormat="dd.MM.yyyy HH:mm:ss"` (with dots) it always clears input
![Mar-18-2019 17-54-30](https://user-images.githubusercontent.com/33573380/54539335-009a7780-49a7-11e9-8aa4-257a8b015fd4.gif)
### Steps to reproduce
react-datepicker v2.0.0
```
import DatePicker from 'react-datepicker';
...
<DatePicker
  id={code}
  selected={value}
  onChange={(date) => { this.setState({ value: date }); }}
  showTimeSelect
  timeFormat="HH:mm"
  dateFormat="dd/MM/yyyy HH:mm:ss"
/>
```

**Comment by patrickalbani** [comment]
You can use onChangeRaw

```    
<DatePicker
   dateFormat="dd/MM/yyyy"                
   locale={ptBr}
   maxDate={new Date(`01/01/2036`)}
   minDate={new Date()}
   name="expirationDateTime"
   selected={values.expirationDateTime ? values.expirationDateTime : undefined}
   shouldCloseOnSelect={false}
   onChangeRaw={onChangeRaw}
/>```

```
const onChangeRaw = ({ setFieldValue }) => ({ target: { value } }) => {
  if (value) {
    return setFieldValue(`expirationDateTime`, new Date(value));
  }
  return setFieldValue(`expirationDateTime`, value);
};
```
