### ISSUE TITLE
Uncaught TypeError: e.format is not a function

### ISSUE THREAD

**Issue by akohout** [Hacker0x01/react-datepicker#167]
I start your component with

```
<DateInput
          ref="date"
          className={classNames}
          dateFormat="DD.MM.YYYY"
          dateFormatCalendar="DD.MM.YYYY"
          locale="de"
          placeholderText={placeholder} />
```

But as soon as I add the selected property with a value, I get the error ```Uncaught TypeError: e.format is not a function```.  The console points to this line that causes the error:

```
safeDateFormat:function(e){return e?e.format(this.props.dateFormat):null}
```

For values, I used a simple string in my expected format (e.g. 01.01.1990), and I also tried Javascript Date objects. Doesn't change anything.

**Comment by akohout** [comment]
Ah I see, when I use a Moment object, it works. Maybe this should go anywhere in the documentation :)

**Comment by martijnrusschen** [comment]
Agreed. Documentation sucks. We'll get some better documentation soon!

**Comment by mordra** [comment]
+1, wasted too much time on this...

**Comment by cnardi-git** [comment]
Solution does not work for me.  I tried setting the date value in state to null, but now I can't select a date without getting the error:  TypeError: t.format is not a function

Also, the popover won't close.

this.state = {
   startDate: null
};

<DatePicker selected={this.state.startDate} />

Overall, I would say this implementation is not worthy of 250+ stars... can't even have a 'blank' input field which prevents it from working.

**Comment by KeitIG** [comment]
same problem as @cnardi-git
