### ISSUE TITLE
modifying size of the date-picker input box

### ISSUE THREAD

**Issue by Phoenixton** [Hacker0x01/react-datepicker#1672]
### Naming conventions

Might be a bit trivial, but is it intended for us to have to do 
`.react-datepicker__input-container input {
    width: {whatever}px;
}` 
in order to modify the size of the input box? 
I feel that input-**container** working as a wrapper of sorts for the actual box is kind of counter-intuitive, naming wise? It took me some time to understand why 
`.react-datepicker__input-container{
     width: {whatever}px;
}` 
wasn't working. I couldn't find any documentation on the subject.

**Comment by leolynn** [comment]
I've added a `className` to my datepicker and specified the height in my index.css

**Comment by SamYan** [comment]
try:

`.react-datepicker__input-container {
    display: block;
}

.react-datepicker-wrapper {
    width: 100%;
}`
