### ISSUE TITLE
Error when using setHours and setMinutes

### ISSUE THREAD

**Issue by GilbertMizrahi** [Hacker0x01/react-datepicker#1682]
I have this:

`<DatePicker
          selected={this.state.startDate}
          onChange={this.handleChange}
          showTimeSelect
          minDate={new Date()}
          minTime={setHours(setMinutes(new Date(), 0), 7)}
          maxTime={setHours(setMinutes(new Date(), 0), 17)}
          filterDate={this.isWeekday}
          timeFormat="HH:mm"
          timeIntervals={30}
          dateFormat="d MMMM, yyyy h:mm aa"
          timeCaption="Hora"
          locale="es"
        />
`

But  setHours and setMinutes throw an error. I am missing something?
Also, with filterDate I want to allow only to select a weekday. Does anyone have the function for isWeekday?

**Comment by no1lov3sme** [comment]
Hi, you need `date-fns` module for that, take a look at [this example](https://github.com/Hacker0x01/react-datepicker/blob/master/docs-site/src/examples/inject_times.jsx).

**Comment by suprabhasupi** [comment]
@no1lov3sme The URL which you shared it's throwing 404.

**Comment by no1lov3sme** [comment]
> @no1lov3sme The URL which you shared it's throwing 404.

```
import setSeconds from "date-fns/setSeconds";
import setMinutes from "date-fns/setMinutes";
```

[Source](https://github.com/Hacker0x01/react-datepicker/blob/de392f68bb08f63676edbbb0f28f17f0595c44a7/src/date_utils.js)
