### ISSUE TITLE
Add label for accessibility - aria props

### ISSUE THREAD

**Issue by developdeez** [Hacker0x01/react-datepicker#1684]
### Expected behavior
Would like to set Aria label on the input
### Actual behavior
cant
### Steps to reproduce
n/a

**Comment by cdsmith-umn** [comment]
I'm also looking to be able to pass in aria-* properties and cannot.

**Comment by tu4mo** [comment]
I used `customInput` as a workaround.

**Comment by miltonpinedakg** [comment]
Would like to set Aria label on the input

**Comment by PsiKai** [comment]
I would like to set aria-label on the datepicker input.

**Comment by mattfrancis888** [comment]
> I used `customInput` as a workaround.

Hi,

How were you able to use customInptu as a workaround for aria-label? I can't seem to wrap my head around it

**Comment by DeveshChauhan** [comment]
```
<label id="label-id">Datepicker</label>
<Datepicker
...
ariaLabelledBy="label-id"
 />
```

use ariaLabelledBy = "id-of-label", I hope this works.
