### ISSUE TITLE
DateFormat Documentation

### ISSUE THREAD

**Issue by activebiz** [Hacker0x01/react-datepicker#1689]
Ever since release of version 2 and removal of momentjs the formats which were used in moment js no longer works here. Which is fine but could we please put some documentation around what date formats are currently supported?

Thanks

**Comment by benbcai** [comment]
@activebiz Version 2 removed momentjs and now uses date-fns. The format in date-fns uses unicode tokens. Take a look at this documentation. https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md

**Comment by erwstout** [comment]
I agree this should be added to the docs somewhere as well. I had to search issues to find this. It's also worth noting that the doc URL posted in @benbcai's answer is for v2 alpha, where as just navigating to the docs organically gives you the stable docs which have some key differences, such as `do` vs `Do` for Day of the Month.

**Comment by Dror-Bar** [comment]
Most libraries have Documentation or API link on the main page, but not this one.
This is the prop you are looking for:

dateFormat='dd/MM/yyyy'

**Comment by HasanMothaffar-OSG** [comment]
I can't find any place on the website that documents how to use `dateFormat` and its possible values. Can we re-open the issue?
