### ISSUE TITLE
Cannot initialize a datepicker with a date

### ISSUE THREAD

**Issue by JustHereForTheBugReport** [Hacker0x01/react-datepicker#169]
In datepicker.jsx line 151:

date={this.state.selected}

Should probably be:

date={this.props.date}

Otherwise it's not possible to specify an initial date.

**Comment by JustHereForTheBugReport** [comment]
Alternatively, if default dates should be specified as such, which is apparent to me now: <DatePicker selected={moment()} /> I think this should be mentioned in the readme.

**Comment by antonholmquist** [comment]
+1

**Comment by cglantschnig** [comment]
thanks I was looking for that.
A little "How to start"-section would be nice in the readme

**Comment by SpencerCDixon** [comment]
+1 needs more documentation on getting started for sure

**Comment by martijnrusschen** [comment]
Documentation has been updated a while ago. Let me know if you need anything else.
