### ISSUE TITLE
onChangeRaw

### ISSUE THREAD

**Issue by dani-t** [Hacker0x01/react-datepicker#1690]
### Expected behavior
On change row should execute my provided function.
### Actual behavior
Looks like `onChangeRaw` is never invoked.
Later edit: it seems that the function is executed when you type into the field but not when you select the value from the datepicker
### Steps to reproduce
```
<DatePicker
  onChangeRaw={event => console.log("blah")}
/>
```

**Comment by godzsa** [comment]
Is it possible to make this work without having to write in the field?

I need to access the original react event to integrate this to a legacy application.
