### ISSUE TITLE
Non-minified version is missing from build?

### ISSUE THREAD

**Issue by jutunen** [Hacker0x01/react-datepicker#1693]
After I run npm install, the development and production versions of react-datepicker.js in dist directory are identical, both being minified.

Also in CDN both are minified and identical:

https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/2.3.0/react-datepicker.js
https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/2.3.0/react-datepicker.min.js

**Comment by kelp404** [comment]
`react-datepicker.js` and `react-datepicker.min.js` are the same thing.
