### ISSUE TITLE
Allow for monthsShown to be either next or previous to selected, or to default before maxDate.

### ISSUE THREAD

**Issue by BramKaashoek** [Hacker0x01/react-datepicker#1697]
### Expected behavior
When I use `monthsShown={2}` and `maxDate={today}`, I would like to be shown current month and previous month

### Actual behavior
Current month and next month are shown.

![image](https://user-images.githubusercontent.com/28596210/55631527-8cd6d800-57b8-11e9-8514-60af96422ebc.png)

**Comment by timkindberg** [comment]
I'd rather just have it be based on what integer is passed to `monthsShown`. We'd need to add support for negative integer and 0 becomes the 'current' month. By default it would include 0-n where n is the number provided, but you could also provide an array tuple (array of two integers) to explicitly define exactly which month range to show.

Some examples
- `monthsShown={0}` - default, show the current month
- `monthsShown={1}` - show the current month and next month
- `monthsShown={-1}` - show the current month and previous month
- `monthsShown={[1,2]}` - show the next month and the month after that
- `monthsShown={[-2,-1]}` - show two months ago and the previous month
- `monthsShown={[-1,1]}` - show previous, current and next month

Just an idea!!

**Comment by mrwomsk** [comment]
any news? :(

**Comment by siva-osv** [comment]
when using this flag with monthsShown and selectsRange, on Date select I am going to the previous month. is there any feasible solution

**Comment by Vladyslav-Hrytsenko** [comment]
@siva-osv did you come up with a solution? I've faced this issue and can't figure out how to fix it.

**Comment by Sakshi-Zeni** [comment]
Hi, @siva-osv Were you able to find a solution to this?

**Comment by annadrg** [comment]
@Sakshi-Zeni using both `showPreviousMonths` and `focusSelectedMonth` worked for me

**Comment by sgtkuncoro** [comment]
facing same issue here 😢
