### ISSUE TITLE
onClickDay date off issue

### ISSUE THREAD

**Issue by manjitha-teshara** [Hacker0x01/react-datepicker#1698]
![issues](https://user-images.githubusercontent.com/36306276/55680128-05fa3a80-5933-11e9-9f20-3e377c9a43f7.png)
if i click 29 i get previous date 28 .all calendar date click work same as.how can fix this trouble.

**Comment by niwsa** [comment]
If it helps...
Are you mutating the selectedDate in state by calling set*Date/Hours/Years...*  somewhere in your code ? I had faced the same issue and removed the mutation by cloning the state https://stackoverflow.com/a/1090817/3939061

**Comment by gbersac** [comment]
I have the same issue. I think this is a timezone issue. The date the user click on using the UI is then converted to a javascript date.

**Comment by RAJARMR** [comment]
![image](https://user-images.githubusercontent.com/25096109/60341355-d73caf00-99cb-11e9-8c30-276947c1b332.png)
when I select a date it shows correct and it allows to enter any number of date and month. How can I fix to not allow typing
