### ISSUE TITLE
how to set local language,more detail example.

### ISSUE THREAD

**Issue by mayuelei66** [Hacker0x01/react-datepicker#170]
Hi, I find there is't a example show how to set local language, I'm a little confused.And I also find I can't use delete key to delete the date.Version 0.11.5

**Comment by mayuelei66** [comment]
<DatePicker placeholderText="开始时间"
                                                className="form-control"
                                                selected={this.state.startDate}
                                                onChange={this.handleStartDate}
                                                locale="zh-CN"
                                        />
it doesn't show Chinese version. So is there a detail example?

**Comment by sergeynechaev** [comment]
It seems that moment() locale overrides the DatePicker settings. I've got correct month names only after setting:
moment.locale('ru');
before the <DatePicker ... />

Also for correct weekday names I have to explicit set right names as props:
<DatePicker key={1} dateFormat="YYYY-MM-DD" 
                                 locale="ru" 
                                 weekdays={['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб']} />

**Comment by strivek** [comment]
you should download` zh-cn.js` from `moment.js` and   reuqire it  ,  then  set 
```javascript
moment.locale('zh-cn');
``` 
and set  DatePicker locale
```javascript
 getDefaultProps: function getDefaultProps() {
	    return {
	      weekdays: ["周一", "周二", "周三", "周四", "周五", "周六", "周日"],
	      locale: "zh-cn",
	      dateFormatCalendar: "MMMM YYYY",
	      moment: moment,
	      onChange: function onChange() {},
	      disabled: false,
	      onFocus: function onFocus() {}
	    };
	  },
```
in react-datepicker.js

**Comment by martijnrusschen** [comment]
Looks like the fix.

**Comment by martingg88** [comment]
seems like doesn't work. any idea how to resolve this issue?
