### ISSUE TITLE
Clearing the Time entry throws error

### ISSUE THREAD

**Issue by brandon8088** [Hacker0x01/react-datepicker#1701]
### Steps to reproduce

Calendar using InputTime option

Can reproduce on demo site reactdatepicker.com:
visit https://reactdatepicker.com/#example-51  (Input Time)
Open browser console
Open the Calendar
Clear the time entry (click the x)

Dev mode console message:
Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

version 2.3.0
react version 16.8.6

**Comment by gautam-relayr** [comment]
Hi @brandon8088 This issue is already tracked here(https://github.com/Hacker0x01/react-datepicker/issues/1670). Please close this one.

The fix is merge but not released yet. Please wait for the next release.
@martijnrusschen When are we planning to release the next version?

**Comment by brandon8088** [comment]
Thanks @gautam-relayr  - closing
