### ISSUE TITLE
Month picker doesn't shows current active month in calendar

### ISSUE THREAD

**Issue by pvieira91** [Hacker0x01/react-datepicker#1705]
### Expected behavior
Whenever a month is picked from the month picker it should show that month highlighted in the calendar. 

### Actual behavior
The recently added month picker (great feature btw!) has a minor issue. It doesn't add any classes or inline css to highlight the active month in the calendar. In the image below the month May should be highlighted - in the standard day picker it shows in blue and with --selected class.
<img width="206" alt="Screen Shot 2019-04-11 at 3 29 30 PM" src="https://user-images.githubusercontent.com/3017887/55965532-af606980-5c6e-11e9-9c00-d4b4ee15159f.png">

### Steps to reproduce
Go to month picker example https://reactdatepicker.com/#example-53
Select one month and then check if it appears active in the calendar.

**Comment by gautam-relayr** [comment]
@pvieira91 This is fixed in the master branch but we are waiting for the release yet. Please wait for the next release.

**Comment by gnanbu** [comment]
when it will be available ?

**Comment by gautam-pahuja** [comment]
Have you checked it(https://reactdatepicker.com/#example-55). I can see it working.

**Comment by gnanbu** [comment]
yes its working . thanks .

**Comment by gautam-pahuja** [comment]
Can you please close the issue then

**Comment by shipra-vishnoi** [comment]
which version of react-datepicker I have to use, as I am doing the same but month picker is still not displaying.

**Comment by shipra-vishnoi** [comment]
> yes its working . thanks .

which version of react-datepicker I have to use, as I am doing the same but month picker is still not displaying.

**Comment by shipra-vishnoi** [comment]
> Have you checked it(https://reactdatepicker.com/#example-55). I can see it working.

which version of react-datepicker I have to use, as I am doing the same but month picker is still not displaying.
