### ISSUE TITLE
Styling is broken 

### ISSUE THREAD

**Issue by kalenpw** [Hacker0x01/react-datepicker#1707]
### Expected behavior
Date picker to appear as preview

### Actual behavior
No formatting dates appear in a straight line up page

### Steps to reproduce
I created a new project via npx create-react-app and only instead react-datepicker and was able to reproduce this issue.

Also happens in an existing project.

Both version 2.3.0

Screenshots:

The first screenshot is when added to an existing project with Bulma imported. The second has nothing but react-datepicker.
In second screenshot that little 4 you see on the right side is what appears when the date picker is selected.

Both tested on current Firefox and current Chromium.

![2019-04-11_155503383419](https://user-images.githubusercontent.com/13550971/56006672-16901500-5c93-11e9-97c8-dc88331afb56.png)

![2019-04-11_155503378319](https://user-images.githubusercontent.com/13550971/56006647-fceecd80-5c92-11e9-8fc0-370e5b5ce900.png)

**Comment by ceciliaschiebel** [comment]
were you able to fix it?

**Comment by kalenpw** [comment]
Yes, I didn't realize the css was kept separate, but now I understand why.

**Comment by Bhushankumar-pawar** [comment]
I am also getting the same view but I am unable to resolve. I am using datepicker with babel-plugin-react-css-modules. imported CSS from node modules dist folder still styling is not getting applied. 
Created ticket [#1809](https://github.com/Hacker0x01/react-datepicker/issues/1806) .
Please let me know you also having the same config.

**Comment by refayathaque** [comment]
In the README it says

`import 'react-datepicker/dist/react-datepicker-cssmodules.css';`

when it should be:

`import "react-datepicker/dist/react-datepicker.css";`

Thanks for pointing this out @kalenpw !

**Comment by sairabunny** [comment]
Hi! Is this .css above also applies to "Select Time Only" react-datepicker. I can't get the same view as one in here.. https://reactdatepicker.com/

**Comment by sgtkuncoro** [comment]
> Hi! Is this .css above also applies to "Select Time Only" react-datepicker. I can't get the same view as one in here.. https://reactdatepicker.com/

hi @imnobunny I think it's because you use both of `todayButton` and `showTimeSelect`,  I fix that issue by hiding `todayButton` LOL. I think `react-datepicker` doesn't support yet if we use `todayButton` and `showTimeSelect` at the same place
