### ISSUE TITLE
Add a note to README about dateFormat/timeFormat option that localizes the format per the locale.

### ISSUE THREAD

**Issue by Rhoulhac** [Hacker0x01/react-datepicker#1709]
Update the [Localization](https://github.com/Hacker0x01/react-datepicker#localization) section of the README to include a note that passing _P_ as the `dateFormat` localizes the displayed date in the input for you without any extra work. 

ex:
``` js
<DatePicker 
    dateFormat="P"
    locale={this.state.locale}
/>
```
This behavior came for free (no need to pass date format) with `moment` as long as you passed a locale. So I think it is worthwhile to highlight it in the README. It would have saved me a few hours of searching which eventually lead me to [this closed issue](https://github.com/Hacker0x01/react-datepicker/issues/1580) which pointed out the solution.

Same goes for `timeFormat`.

**Comment by Aid19801** [comment]
Is there actually a list of dateFormat examples? Desp trying to get it in British / DD/MM/YYYY format but struggling...

**Comment by Aid19801** [comment]
Ignore me - just worked out that the format has to be `dd/MM/YYYY` case sensitive.
my component, in case it helps someone else

```

    const [ startDate, setStartDate ] = useState(new Date());
    const [ endDate, setEndDate ] = useState(new Date());
...
...
<div className="from-and-to-container">
                        <DatePicker
                            selected={startDate}
                            onChange={setStartDate}
                            dateFormat="dd/MM/YYYY"
                        />
                        <DatePicker
                            selected={endDate}
                            onChange={setEndDate}
                            dateFormat="dd/MM/YYYY"
                        />
                    </div>
```

**Comment by georgesunnyt** [comment]
@Rhoulhac thanks for posting this man. It hasn't been included readme yet. Passing just "P" saved me all the trouble. You saved me a lot of time. I have huge respect for people like you out there who post solutions. I will try to be the same and post solutions for other people too. Peace
