### ISSUE TITLE
Textbox is not user-editable

### ISSUE THREAD

**Issue by JustHereForTheBugReport** [Hacker0x01/react-datepicker#171]
When placing the cursor into the textbox and attempting to delete a character or enter a new character the value is always rejected. This makes it impossible to manually enter a date and contradicts the demos.

See date_input.jsx line 70 ( value={this.safeDateFormat( this.props.date )} ) and compare to the corresponding line in the demos (value: this.state.value).

This bug precludes me using this library in production so hope it can be fixed.

This bug was introduced in commit ef9ece6

**Comment by lindslev** [comment]
:point_up_2:

**Comment by JustHereForTheBugReport** [comment]
As stated in the original post, currently the datepicker doesn't accept user input from the keyboard. I've submitted a pull request which contains a fix for this issue.

Some notes on the behavior of this fix:
* If the user enters an invalid date the onChange method will be invoked with a null value.
* If the DatePicker is assigned a null value it will continue to show the last displayed value.

Consumers of this fix will need to review their usage of DatePicker as this behavior is slightly different from the current behavior.

**Comment by bmcneely** [comment]
@JustHereForTheBugReport You say that "If the DatePicker is assigned a null value it will continue to show the last displayed value." How does that play out if the user wants to clear the input field?

**Comment by JustHereForTheBugReport** [comment]
@bmcneely The user would need to highlight their input and backspace it themselves. There is no way to programatically clear the date input display value with the pull request I have submitted. This is because the aforementioned commit breaks key functionality that would make this possible. If your use case requires programatically clearing the date input display value I would suggest checking out and testing commit 397a8e which was made prior to the changes that led me to raise this issue.

**Comment by marr** [comment]
Fwiw, I created a hacker1 theme for a similar date-picker repo here github.com/zippyui/react-date-picker.
It allows for programmatically using an input, and has a cleaner implementation, imo.

**Comment by jnarowski** [comment]
What's the status on this pull request. I'd also like the input to be editable by users, since sometimes they are changing the year and that requires a lot of clicking otherwise.

**Comment by andyparisi** [comment]
Also this. Can we get some movement on this PR? Otherwise i'll be forced to switch libraries.

**Comment by martijnrusschen** [comment]
Happy to merge it once the questions has been answered.

**Comment by andyparisi** [comment]
Thanks for the quick reply. I'll be keeping an eye out on the thread.

**Comment by dave-handy** [comment]
What questions still need to be answered?

**Comment by jnarowski** [comment]
+1

**Comment by martijnrusschen** [comment]
Fixed by #171
