### ISSUE TITLE
Current month is not shown in custom header with multiple months inline

### ISSUE THREAD

**Issue by Helpermedia** [Hacker0x01/react-datepicker#1721]
### Expected behavior
Multiple months (monthsShown={3}) have a current month title in the header. 
With renderCustomHeader a custom header can be made, current month is not an option to add. I would expect it would be still visible.

### Actual behavior
Current month is not longer shown when renderCustomHeader is used.

### Steps to reproduce
Implement renderCustomHeader with multiple months inline. Current month is not shown.

**Comment by brojd** [comment]
any update on this?

**Comment by Zertz** [comment]
Looking at the code, it seems like [this behavior is intentional](https://github.com/Hacker0x01/react-datepicker/blob/99d45b9e884ae89a1a0f9b43f1eb3c74d62dbf7a/src/calendar.jsx#L673).

I've started working on #2520 to fix this.
