### ISSUE TITLE
adding a dateFormat "dd-MM-yyyy" prevents user from changing date in customInput

### ISSUE THREAD

**Issue by forkerino** [Hacker0x01/react-datepicker#1722]
### Expected behavior
We have an input field with a button next to it which opens the Datepicker. We would like the user to be able to just enter a date by pressing the numbers on their keyboard when in the input field. We use a "dd-MM-yyyy" dateFormat, because that's how dates look here. 

### Actual behavior
The date cannot be altered by keyboard. When the user selects the whole field and presses a number, it immediately changes after that first number is entered into a date in 2001 and no other numbers entered are registered.

### Steps to reproduce
```jsx
<Datepicker
    customInput={
        <CustomInput
            value={
                initialValues.start_date
            }
        />
    }
    showWeekNumbers
    id="id_start_date"
    name="start_date"
    dateFormat="dd-MM-yyyy"
    locale={nl}
    onChange={handleChange}
/>
```
where CustomInput renders:
```jsx
<p className="input-group">
    <input
        type="text"
        className="form-control"
        data-testid="id_start_date"
        onClick={onClick}
        value={value}
        onChange={onChange}
    />
    <span className="input-group-btn">
        <button type="button" className="btn btn-default" onClick={onClick}>
            <i className="glyphicon glyphicon-calendar" />
        </button>
    </span>
</p>
```

**Comment by willensoll** [comment]
+1

**Comment by trandaniel** [comment]
+1

**Comment by ivanosevitch** [comment]
I had a similar issue with react-datepicker 2.9.6: entering `01` in a `customInput` would autocomplete to a full date (like `01/01/2019`).

I managed to solve this issue by passing down a `onFocus` props to the `customInput`, as explained in https://github.com/Hacker0x01/react-datepicker/issues/1915#issuecomment-564933671
