### ISSUE TITLE
Inline with Input

### ISSUE THREAD

**Issue by abhikp** [Hacker0x01/react-datepicker#1724]
### Expected behavior

Is there a way to have an inline date picker *with* an input. Seems like this isn't possible.

An example of what I'd expect to be able to accomplish:

<img width="306" alt="Screen Shot 2019-05-01 at 4 18 37 PM" src="https://user-images.githubusercontent.com/336114/57049448-fb2e7f00-6c2c-11e9-9ef8-a4f7d3fb7323.png">

**Comment by abhikp** [comment]
This could also be possible with an option to only have a text parsing input

**Comment by abhikp** [comment]
I was able to solve this by using two DatePicker components, one with `inline=true` and another with `popperClassName` equal to a class that had `display: none`

**Comment by aditigoel23** [comment]
Is there a better way to achieve this through props instead of adding multiple pickers?

**Comment by soorajbala** [comment]
just add a prop open={true}

**Comment by ArtemBernatskyy** [comment]
It could help someone

![image](https://user-images.githubusercontent.com/13070119/100106506-493f4f00-2e71-11eb-8ed1-8df597855a39.png)


```
const someComponent = (props) => {
  const [startDate, setStartDate] = useState(new Date("2019/08/08"));
  const [endDate, setEndDate] = useState(new Date("2020/02/08"));

  const onChange = dates => {
    const [start, end] = dates;
    setStartDate(start);
    setEndDate(end);
  };

  return (
    <div className="popup-window">
      <div>
        <DatePicker
          selected={startDate}
          onChange={(date) => setStartDate(date)}
          popperClassName="d-none"
          dateFormat="d MMM yyyy"
          placeholderText="Select from date"
        />
        <DatePicker
          selected={endDate}
          onChange={(date) => setEndDate(date)}
          popperClassName="d-none"
          dateFormat="d MMM yyyy"
          placeholderText="Select to date"
        />
        <DatePicker
          selected={startDate}
          onChange={onChange}
          startDate={startDate}
          endDate={endDate}
          disabledKeyboardNavigation
          selectsRange
          monthsShown={2}
          inline
        />
      </div>
    </div>
  );
};
```
