### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by overtureweb** [Hacker0x01/react-datepicker#1727]
### Expected behavior
In the example for Exclude Dates, the excludeDates attribute is written as 
`excludeDates={[new Date(), subDays(new Date(), 1)]` When I include this line in my code it should exclude the current date and the previous date.

### Actual behavior
When I attempt to use this in my component I receive an error that subDays is not defined

**Comment by MoAli2016** [comment]
subDays is defined in date-fns library and you can find it in ./es/index.js. You have to import it like this
`import subDays from "date-fns/subDays";` into your code but you have to have "npm install date-fns"
