### ISSUE TITLE
Disable Next if exclude is set

### ISSUE THREAD

**Issue by mydudechris** [Hacker0x01/react-datepicker#173]
Would it be possible to disable the Prev/Next buttons if the exclude values are set? For example, I'm setting up two inputs, a from and to date. The to date is set to today and the user shouldn't be able to go beyond today. Rather than simply setting the future dates to a light color, I'd rather just disable moving forward altogether. Is that something we can request as a feature? Thanks!

**Comment by mydudechris** [comment]
Bump

**Comment by mydudechris** [comment]
Bump

**Comment by rafeememon** [comment]
I don't think this can be implemented as stated -- excluded values are necessarily finite, so going far into the past/future can get to valid dates.  I can see this working with `includeDates` instead.

**Comment by rafeememon** [comment]
Closing in favor of #413
