### ISSUE TITLE
renderDayContents not passing date

### ISSUE THREAD

**Issue by zslabs** [Hacker0x01/react-datepicker#1739]
### Expected behavior

As part of https://github.com/Hacker0x01/react-datepicker/pull/1637 I believe the `date` property was supposed to be sent along with the function.

### Actual behavior

Only the first, `day` property is actually provided. There are no other parameters available.

### Steps to reproduce

```js
<DatePicker
  renderDayContents={(day, date) => console.log(day, date)}
/>
```

Only `day` will be available.

**Comment by zslabs** [comment]
Was using older version 💩

**Comment by kuriel-trivu** [comment]
How to know if rendered day is selected for range dates?
