### ISSUE TITLE
A locale object was not found for the provided string ["sl"].

### ISSUE THREAD

**Issue by Shooshte** [Hacker0x01/react-datepicker#1740]
### Expected behavior
Slovene translations should load from the `date-fns` locales.

### Actual behavior
Datepicker defaults to English because locales are not found.

### Steps to reproduce
Using `"react-datepicker": "^2.5.0"`

```
import React from 'react';
import DatePicker from 'react-datepicker';
import moment from 'moment';

export default ({ value, name, onChange }) => (
  <DatePicker
    dateFormat="dd.MM.yyyy"
    selected={value ? value : moment()}
    onChange={date => onChange(name, moment(date).valueOf())}
    locale="sl"
  />
);
```

---

It seems that the alpha version of date-fns is used with react-datepicker that does not support all the available languages? The language locale is there in the `date-fns` repo but I don't think it is ready for the alpha version yet?

Could you use a version of `date-fns` without the alpha or beta tag? That way most languages already available in `date-fns` would be supported.

**Comment by JozefBiros** [comment]
I have same problem with locales. DatePicker use beta version of date-fns which doesn't support all locales yet. I did make pull request for my locale on date-fns, but that project looks dead to me. Code wasn't updated at least 5 months and about 50 pull request is waitign for  review.

**Comment by martinbjeldbak** [comment]
Did you solve this issue @Shooshte @JozefBiros? I had a similar error and realised that I needed to import & register the locales I wanted to use within react-datepicker, directly from date-fns. See for example https://reactdatepicker.com/#example-17 and https://github.com/Hacker0x01/react-datepicker/issues/1815#issuecomment-513215416. This made the error message go away for me and allowed setting locale. Hope this helps!

**Comment by Shooshte** [comment]
@martinbjeldbak This did not solve my issue - unfortunately the version of date-fns used with react-datepicker is in a beta and does not have slovene locales supported yet.

**Comment by ArthurSN57** [comment]
+1

**Comment by TiagoFuelber** [comment]
+1

**Comment by Delfio** [comment]
+1 :(

**Comment by Rafael-Ramblas** [comment]
+1 on this.
I've read the solution mentioned, but this means that i have to install date-fns in my project and import every single location that i plan to use?

**Comment by vedranstipancic** [comment]
For me this solution is not an option.
I use moment over most of my app and if i register date-fns locales it breaks the moment locales
