### ISSUE TITLE
missing titles (LLLL)

### ISSUE THREAD

**Issue by aseroj** [Hacker0x01/react-datepicker#1741]
Everything works ok when using the plugin in local, but the way we need the plugin to function is to use it in my private self hosted library and then it gets called inside my react app and that's when the abnormal behavior starts.

<img width="594" alt="Screen Shot 2019-05-14 at 8 48 09 PM" src="https://user-images.githubusercontent.com/6689309/57777899-fccf6b00-7733-11e9-8cab-7d980feac8e5.png">

again, during local usage everything functions as expected, after deployment this is what happens. we didn't temper the plugin in any way.

"react": "**16.8.1**"
"react-datepicker": "**2.5.0**"

**Comment by jimdebeer** [comment]
I have exactly the same problem
![image](https://user-images.githubusercontent.com/5682524/58088849-ce361200-7bc3-11e9-8410-d7ebe564e72d.png)

"react": "16.8.0"
"react-datepicker": "^2.5.0"

**Comment by aseroj** [comment]
we solved the issue by updating `date-fns` library from `1.30.1` to the latest `2.0.0`

```
-    "date-fns": "^1.30.1",
+    "date-fns": "^2.0.0-alpha.27"
```
