### ISSUE TITLE
./node_modules/react-popper/lib/esm/Popper.js Module not found: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in 'mypath\node_modules\react-popper\lib\esm'

### ISSUE THREAD

**Issue by leslie555** [Hacker0x01/react-datepicker#1744]

**Comment by mancontr** [comment]
I get a different error that seems to be related, after updating to Babel 7.4 and core-js 3.
```
ERROR in ./node_modules/babel-runtime/core-js/object/assign.js
    Module not found: Error: Can't resolve 'core-js/library/fn/object/assign' in '/home/.../node_modules/babel-runtime/core-js/object'
     @ ./node_modules/babel-runtime/core-js/object/assign.js 2:13-56
     @ ./node_modules/babel-runtime/helpers/extends.js
     @ ./node_modules/react-popper/lib/esm/Popper.js
     @ ./node_modules/react-popper/lib/esm/index.js
     @ ./node_modules/react-datepicker/es/index.js
...
```
It seems to be related to react-popper using `babel-runtime` which uses `core-js` 2, while we're using `@babel/runtime` and `core-js` 3.
Is there any way to make it work on this situation?

**Comment by burtontanner** [comment]
@leslie555 I got the same error as you and updating react-scripts worked for me. 
`yarn remove react-scripts`
`yarn add react-scripts`
If you have a proxy setup in local development, you will probably need to convert to using a `setupProxy.js` file.
