### ISSUE TITLE
Change locale doesn't work on datepicker custom input

### ISSUE THREAD

**Issue by leorigon** [Hacker0x01/react-datepicker#1745]
### Expected behavior
Allow use of other date and hour format e.g (dd/MM/yyyy : HH:mm) through locale 'pt-br'. This problem affect inputs on our application. 

### Actual behavior
The format(date/hour) continue uses the default format. And shows the warn on console:
`A locale object was not found for the provided string ["pt-br"].`
### Steps to reproduce
The code is some like this: 

```
  import DatePicker from 'react-datepicker'
  import 'react-datepicker/dist/react-datepicker.css'
  import 'moment/locale/pt-br'

    <DatePicker
        { ...props }
        locale='pt-br'
     />
```
I have try fix it with different forms in last days, but the behaviour does not change.

**Comment by Satyam** [comment]
Try adding the `dateFormat="PP"` or any of the various P format string options from https://date-fns.org/v2.0.0-beta.2/docs/format:

```jsx
<DatePicker
     { ...props }
     locale='pt-br'
     dateFormat="PP"
/>
```
