### ISSUE TITLE
Is there a way to detect click on the currently selected day?

### ISSUE THREAD

**Issue by acobster** [Hacker0x01/react-datepicker#1746]
Thank you for your work on this awesome component!

### The problem I'm trying to solve

I have a date range picker similar to the [Date Range example](https://reactdatepicker.com/#example-24), but that only exposes one `input` to the user and shows/hides the start/end pickers depending on which date the user has just selected. For example:

1. User clicks the input to select a new date range
2. User picks a new start date
3. In the `onChange` handler, my component recognizes that the user has selected a start date, and rerenders the `DatePicker` with the appropriate `selectsEnd` prop etc. for selecting the  end date instead
4. User picks an end date
5. My component recognizes both dates have been selected, and finally closes the picker

The problem is that there's no way for the user to select a date range with the same start date, but a different end date.

### Expected behavior

I would expect when clicking on the current day that some kind of click event would fire, so I can check whether the user is being prompted to select a start date, and render the end date picker accordingly.

I also tried setting `shouldCloseOnSelect` to `false` for the start date picker, but this didn't work either because clicking on the already selected date doesn't register as a selection.

### Actual behavior

When I add `onClick` or `onDayClick` handler props to the `DatePicker`, they seem to be short-circuited by clicking on the currently selected day. I haven't found any way to discern that the user has taken any action at all.

### Steps to reproduce

I can probably create a demo repo soon (I'm actually using ClojureScript/Reagent so translating back into vanilla React is more than I have time for right now) but I'm hoping this is a detailed enough explanation in the meantime that you can point me in the right direction. Thanks again.

**Comment by smithaitufe** [comment]
@acobster Did you manage to figure a solution to this issue?
