### ISSUE TITLE
includeTimes doesn't work as expected

### ISSUE THREAD

**Issue by lorenzosjb** [Hacker0x01/react-datepicker#1750]
### Expected behavior

If you add a date to an array to includeTimes it should appear only once.

### Actual behavior

When you add a date to an array to the includeTimes option, it appears on all days.

`<DatePicker
  selected={this.state.startDate}
  onChange={this.handleChange}
  showTimeSelect
  includeTimes={[setHours(setMinutes(new Date(), 0), 17), setHours(setMinutes(new Date(), 30), 18), setHours(setMinutes(new Date(), 30), 19), setHours(setMinutes(new Date(), 30), 17)]}
  dateFormat="MMMM d, yyyy h:mm aa"
/>`

**Comment by samazadi** [comment]
@lorenzosjb did you find a work around for this? I'm experiencing the same issue.
