### ISSUE TITLE
throw out RangeError('Invalid time value') 

### ISSUE THREAD

**Issue by gamesover** [Hacker0x01/react-datepicker#1752]
### Expected behavior
Hello, I want to use the component to select date, but it keeps throwing out `Invalid time value` error. No idea why. 
### Actual behavior
The below is where error was throw out.
```
  if (!isValid(originalDate)) {
    throw new RangeError('Invalid time value');
  } // Convert the date in system timezone to the same date in UTC+00:00 timezone.
  // This ensures that when UTC functions will be implemented, locales will be compatible with them.
  // See an issue about UTC functions: https://github.com/date-fns/date-fns/issues/376
```
### Steps to reproduce
```javascript
<DatePicker
      selected={this.state.date}
      onChange={(value:any)=> {
     // value here is javascript date object
      this.setState({date: moment(value)})
       }}
  />
```
I tested the above simple case, it throws the same error. Really confused.

**Comment by gamesover** [comment]
I found the issue, I am using `react-datepicker` 2.5.0 + typescript + "@types/react-datepicker": "^1.1.7". After upgrade "@types/react-datepicker": "^2.3.0". Problem solved

**Comment by abepark01** [comment]
I am also getting the same issue with `react-datepicker@2.5.0`

Any luck?

**Comment by gamesover** [comment]
`react-datepicker` before version 2, it use `moment` for date type
after version 2, it use js date type

please pay attention whether the version of `react-datepicker` is consist with the version of `@types/react-datepicker`. Typescript shall give you warning.

It is very likely you pass `moment` date to `react-datepicker@2.5.0`, which use js date type now.

**Comment by abepark01** [comment]
@gamesover Thanks for the heads up.
I was also passing in a moment object into the `selected` prop.
```es6
const selected = moment(isoDateStr).toDate()
```

**Comment by allysson-esparta** [comment]
> @gamesover Thanks for the heads up.
> I was also passing in a moment object into the `selected` prop.
> 
> ```js
> const selected = moment(isoDateStr).toDate()
> ```

It`s worf for me

**Comment by jschimmoeller** [comment]
hey heads up i am using 2.9.6 with js Date object and i am getting this error also; so something inside library

**Comment by stinachen** [comment]
> hey heads up i am using 2.9.6 with js Date object and i am getting this error also; so something inside library

I'm also seeing the same thing when I try to initialize `selected` with `new Date()`. It works if I leave it un-initialized.

**Comment by KevinGrant12** [comment]
Also using 2.9.6 and getting the same error.

**Comment by KevinGrant12** [comment]
Also using 2.9.6 and getting the same error.
Consdering nobody cares about this error, I'll just go use the other datepicker. Thanks for the awesome support!

**Comment by switch900** [comment]
Try Date.Parse.   Below is sample of working code t

const handleChange = date => {
        setChildInfo({ ...childInfo, birthDate: date })
 }; 

 <DatePicker
selected={Date.parse(childInfo.birthDate)}
onChange={handleChange}
 />

**Comment by AlexanderArce** [comment]
Same issue but only happening on Safari, which is weird. 
In Firefox and Chrome is working as expected.

```
selected={event.start ? new Date(event.start) : null}
```

**Comment by nuposyatina** [comment]
I have same issue only in Safari. I think it happens because Safari doesn't support `<input type='time'>`
When we delete the colon, date cannot be parsed.
I added this code in onChange listener:
`if (!(dateIn instanceof Date && !isNaN(dateIn))) return;`
Instead of an error, the previous date is selected until the user enters a new date.
It helps me, so I hope it helps you too.

**Comment by hanzlahabib** [comment]
i am facing same issue with simple datepicker 
i am initializing date with new Date()

**Comment by silverspectro** [comment]
problems seems to be the langage of the date.
On Firefox, changing the langage in the Preferences from English to French cause the problem to appear. Having Firefox in English makes the problem disappear.
I suspect the datepicker to try to interprete with the engish format by default, and then on click it uses the langage of the JS Date object which is the the one of the browser by default. If it is the same it works, else not.

**Comment by Assdi** [comment]
> Same issue but only happening on Safari, which is weird.
> In Firefox and Chrome is working as expected.
> 
> ```
> selected={event.start ? new Date(event.start) : null}
> ```
> 
> Edit: Adding `.replace(/-/g, '/')` to `event.start` seems to solve the problem for me.

works for me 👍

**Comment by abhinav2331** [comment]
I also faced same issue in my application.
But I got the solution by reduce my version to react-datepicker": "2.3.0"

Please use this version and fix you issues.

**Comment by udielenberg** [comment]
I fixed it by changing wherever I had to pass `null` with `undefined` instead

**Comment by timrobinson33** [comment]
I had the same problem when binding the date picker to a field in an object that had been parsed from a fetch() call, something like this (in typescript):
```
class Person: {
  name: string;
  birthDate: Date;
}
var result = await fetch(...);
var person : Person = await result.json();
this.setState(person);
```
I added this line just above the setState
```
person.birthDate = new Date(person.birthDate.valueOf());
```
to clone the Date object, and hey presto it started working.
using 2.14.1 (latest at time of writing)

**Comment by Drewlove** [comment]
This worked for me! Thank you.

**Comment by suraj-omni** [comment]
> > @gamesover Thanks for the heads up.
> > I was also passing in a moment object into the `selected` prop.
> > ```js
> > const selected = moment(isoDateStr).toDate()
> > ```
> 
> It`s worf for me

worked

**Comment by mrabaev48** [comment]
I am also getting the same issue with react-datepicker@3.0.0
Any updates?

**Comment by abigray** [comment]
I resolved this by wrapping my string date into a Date object.  This got rid of the error:

 const [date, setDate] = useState(null);

 async function onLoad() {
      setDate(new Date(myLoadedDate));
}

 <DatePicker
            selected={date}
            onChange={date => setDate(date)}
            showTimeSelect
            timeFormat="hh:mm aa"
            timeIntervals={15}
            timeCaption="Time"
            dateFormat="MMMM d, yyyy h:mm aa"
  />

**Comment by CoDigo93** [comment]
> I resolved this by wrapping my string date into a Date object. This got rid of the error:
> 
> ```
> const [date, setDate] = useState(null);
> 
>  async function onLoad() {
>       setDate(new Date(myLoadedDate));
> }
> 
>  <DatePicker
>             selected={date}
>             onChange={date => setDate(date)}
>             showTimeSelect
>             timeFormat="hh:mm aa"
>             timeIntervals={15}
>             timeCaption="Time"
>             dateFormat="MMMM d, yyyy h:mm aa"
>   />
> ```

where did this 'myLoadedDate' come from?is it a client-side request or did you get from the database?

**Comment by jerrycaffe** [comment]
` <DatePicker
  
    selected={startDate}
    dateFormat="MMMM d, yyyy h:mm aa"
    onChange={handleDateTime}
  />`
experiencing the same error, spent 4 hours on it

**Comment by timrobinson33** [comment]
Make sure the selected date you pass in (i.e. startDate value) is a JavaScript Date object, not a string

> ` <DatePicker
> 
> ```
> selected={startDate}
> dateFormat="MMMM d, yyyy h:mm aa"
> onChange={handleDateTime}
> ```
> 
> />`
> experiencing the same error, spent 4 hours on it

**Comment by chiweip** [comment]
moment().toDate() somehow does not work. But JS's Date.parse() works:
`Date.parse(moment(dateString, 'MM/DD/YYYY').toISOString())`

**Comment by robertfobrien** [comment]
I have the same issue even on react-datepicker@^3.3.0. Getting this error
![Screen Shot 2021-01-11 at 2 54 50 PM](https://user-images.githubusercontent.com/20687631/104231439-f7e92000-541c-11eb-857f-7a760cdc2368.png)

**Comment by afucher** [comment]
Same issue here, but it works in several computers just in my Mac it throws the error.
Versions:
```
"typescript": "^4.2.3",
"react-datepicker": "^3.4.1",
"@types/react-datepicker": "^3.1.7",
```

<img width="1033" alt="Captura de Tela 2021-03-14 às 17 11 01" src="https://user-images.githubusercontent.com/3756185/111082666-5186cd00-84e8-11eb-84ba-2f95749cafb9.png">

**Comment by CharieBlastX7** [comment]
The selected prop takes directly the date object, hence we have to convert any date string to a date object. it can be done by passing `selected={new Date(dateInAnyString)}` and it should work

**Comment by curious-33** [comment]
This one is worked for me. Thanks guys😊

> const selected = moment(isoDateStr).toDate()

**Comment by stepan-slyvka** [comment]
Have the same problem. Version 4.8. How to solve?

**Comment by timrobinson33** [comment]
> Have the same problem. Version 4.8. How to solve?

see other comments above - make sure you are passing in a Date object, not a string

**Comment by stepan-slyvka** [comment]
> > Have the same problem. Version 4.8. How to solve?
> 
> see other comments above - make sure you are passing in a Date object, not a string

It doesn't work.

Code below.

`const [startDate, setStartDate] = useState(orderDate || date);`

`const orderDate = new Date(props.orderDate);`

`<DatePicker
                    dateFormat="MM-dd-yyyy"
                    className={classes["order-date-input"]}
                    selected={orderDate}
                    onChange={(val) => setStartDate(val)}
                  />`

**Comment by timrobinson33** [comment]
I can't really understand your code sample - you seem to have 4 separate date variables `startDate`, `orderDate`, `props.orderDate`, and `date`; `orderDate` is used before it's defined; and the one you're passing as `selected` isn't the same one you're setting into the state.

Here's a simple example using react-datepicker 4.8.0
```
import ReactDatePicker from 'react-datepicker'
import { useState } from 'react'
function App() {
  const [startDate, setStartDate] = useState(new Date("2022-05-17"))
  return (
    <div>
      <ReactDatePicker dateFormat="MM-dd-yyyy" selected={startDate} onChange={(val) => setStartDate(val)} />
      <p>current value is {startDate.toString()}</p>
    </div>
  )
}
export default App;
```

**Comment by stepan-slyvka** [comment]
> I can't really understand your code sample - you seem to have 4 separate date variables `startDate`, `orderDate`, `props.orderDate`, and `date`; `orderDate` is used before it's defined; and the one you're passing as `selected` isn't the same one you're setting into the state.
> 
> Here's a simple example using react-datepicker 4.8.0
> 
> ```
> import ReactDatePicker from 'react-datepicker'
> import { useState } from 'react'
> function App() {
>   const [startDate, setStartDate] = useState(new Date("2022-05-17"))
>   return (
>     <div>
>       <ReactDatePicker dateFormat="MM-dd-yyyy" selected={startDate} onChange={(val) => setStartDate(val)} />
>       <p>current value is {startDate.toString()}</p>
>     </div>
>   )
> }
> export default App;
> ```

I understand how to use react-datepicker, but the problem is - I'm trying to pass it in date format, but it somehow doesn't do that. You can watch my repository called test-project for more info(I've got so much date states, because i have addInvoice and editInvoice) - https://github.com/stepan-slyvka/test-project

**Comment by timrobinson33** [comment]
> I understand how to use react-datepicker, but the problem is - I'm trying to pass it in date format, but it somehow doesn't do that. You can watch my repository called test-project for more info(I've got so much date states, because i have addInvoice and editInvoice) - https://github.com/stepan-slyvka/test-project

You can see I'm passing in date format in my example and it works OK. if your form is complicated I'd suggest you make a test copy and delete everything except the date picker until you've got only the minimum code that replicates the problem. Then if it is a problem with the date picker itself (Which I doubt) you can post the minimum sample here.

**Comment by stepan-slyvka** [comment]
> > I understand how to use react-datepicker, but the problem is - I'm trying to pass it in date format, but it somehow doesn't do that. You can watch my repository called test-project for more info(I've got so much date states, because i have addInvoice and editInvoice) - https://github.com/stepan-slyvka/test-project
> 
> You can see I'm passing in date format in my example and it works OK. if your form is complicated I'd suggest you make a test copy and delete everything except the date picker until you've got only the minimum code that replicates the problem. Then if it is a problem with the date picker itself (Which I doubt) you can post the minimum sample here.

Okay, thank you.
