### ISSUE TITLE
How can I show the string "Today" if the selected date and current date are same?

### ISSUE THREAD

**Issue by harikrishnanp** [Hacker0x01/react-datepicker#1753]
### Expected behavior
If the selected date and current date are the same it should show the string "Today" instead date.
![Screen Shot 2019-05-28 at 11 35 27 AM](https://user-images.githubusercontent.com/3635614/58454741-077afe80-813d-11e9-9c2c-9b791c123200.png)

### Actual behavior
It shows the date even if the selected date and current date are the same.  
### Steps to reproduce
1) Select current date from date picker.

**Comment by bakaa99** [comment]
you can manually set the value using the value prop if you want to show "Today" on today's date.
