### ISSUE TITLE
Add ability to create/pass data-attributes to all elements for E2E testing

### ISSUE THREAD

**Issue by rodoabad** [Hacker0x01/react-datepicker#1757]
### Expected behavior

Ability to pass in or auto generate data-testids for data picker so it's easier to do E2E testing i.e. selecting dates, etc.

### Actual behavior

Not able to pass in custom data attributes to each element.

**Comment by ConorLindsay94** [comment]
You can get round this issue by using a custom input.

`customInput={<input data-testid="some-test-id" type="text" />}`
