### ISSUE TITLE
Allow using the year dropdown with the month picker

### ISSUE THREAD

**Issue by gesabehrends** [Hacker0x01/react-datepicker#1762]
### Expected behavior
In a month picker (showMonthYearPicker) it should be possible to show a year dropdown (showYearDropdown).
### Actual behavior
In a month picker even with `showYearDropdown=true` no year dropdown is rendered.

**Comment by 144mdgross** [comment]
I am seeing similar behavior. 
The select box for the year drop down appears, but it's empty. 
I am at v2.7.0. 
The example site shows the year and month drop downs working at the same time for v2.7.0 but that doesn't seem to be the case.
