### ISSUE TITLE
Error on date selection

### ISSUE THREAD

**Issue by quangas** [Hacker0x01/react-datepicker#1770]
Each time I click on the DatePicker it throws the following error:

`Uncaught RangeError: Use `yyyy` instead of `YYYY` for formating years; see: https://git.io/fxCyr at throwProtectedError` ...

`The above error occurred in the <Month> component: in Month (created by Calendar)`

What's up with this? There are no date formatters or anything on the page.

```
<DatePicker
 selected={this.state.date}
 onChange={this.handleDate.bind(this)}
 className="form-control" />
```

React 16.8.6
Datepicker 2.6.0

**Comment by PanDymitr** [comment]
I has already been [fixed](https://github.com/Hacker0x01/react-datepicker/commit/53ea064165d9cc07e19051b55d3510b60a6ea378#diff-5b4063a3ef5bdfe9d5e50b18c4c5b795). I believe that version should be upgraded to 2.6.1

**Comment by quangas** [comment]
Thanks.

Have to downgrade to v2.1.0 before this fix is pushed to NPM.
