### ISSUE TITLE
Custom dateFormat/selected value

### ISSUE THREAD

**Issue by philmetzger** [Hacker0x01/react-datepicker#1778]
### Expected behavior
I would like to display a custom selected value such as: "June 20, 2019 (30 days from now)"
![image](https://user-images.githubusercontent.com/4325631/59104073-d9619f80-8930-11e9-83bd-d52719c7aaa4.png)

I have also tried this which does not seem to use the customInput:

```
const CustomInput = ({ onClick, value }) => {
    return <Input placeholder="MMMM d, yyyy" onClick={onClick} value={`${value} (30 days from now)`} />;
};

const DeadlineSelector = () => {
    const startDate = new Date();
    const endDate = new Date();
    endDate.setDate(endDate.getDate() + 30);

    const options = {
        dateFormat: 'MMMM d, yyyy',
        minDate: startDate,
        maxDate: endDate,
    };

    return (
        <DatePickerFormField
            customInput={<CustomInput />}
            label="Deadline for your job post"
            name="endDate"
            placeholderText="MMMM d, yyyy"
            {...options}
        >
            <DatePicker {...options} />
        </DatePickerFormField>
    );
};

DeadlineSelector.propTypes = {
    initialValues: T.object,
};

export default DeadlineSelector;
```

### Actual behavior
Using a dateFormat like displays the date as: MMMM d, yyyy (30 days from now)

July 7, 2019 (30 7PM201923 fro28 no28)

![image](https://user-images.githubusercontent.com/4325631/59104151-0dd55b80-8931-11e9-9f2f-5359608295da.png)

**Comment by philmetzger** [comment]
Solved using customInput

**Comment by enzoferey** [comment]
People landing here (as it's the closest issue I have found), you can wrap characters inside `'` to skip them during formatting as written in the [`date-fns` docs](https://date-fns.org/v2.9.0/docs/format).
