### ISSUE TITLE
Use moment.weekdaysMin() for weekdays

### ISSUE THREAD

**Issue by jesenko** [Hacker0x01/react-datepicker#178]
Considering that `moment` is used for formatting of date-related stuff in datepicker (e.g. `month+year` in calendar header), why is it not used to obtain weekdays?

I am currently setting it as

    const weekdays = moment.weekdaysMin()
    <Datepicker weekdays={weekdays} />

I assume this would be sensible default - also taking into account `locale` property of `<Datepicker />`?

Current implementation also overrides moment locale setting with `weekdays` as set in `Datepicker` (https://github.com/Hacker0x01/react-datepicker/blob/master/src/calendar.jsx#L59), which can be rather surprising for the user of the component.

**Comment by RSO** [comment]
SGTM. Not sure if I can find the time to work on this, so a PR would be much appreciated.

**Comment by rafeememon** [comment]
Fixed by #277
