### ISSUE TITLE
Time format for time input

### ISSUE THREAD

**Issue by gmltA** [Hacker0x01/react-datepicker#1785]
Hi there,

If I'm getting everything right, there is currently no way to customize time input's (`showTimeInput`) format (currently it is `HH:mm aa`). Are there any plans to implement this feature?

**Comment by gautam-pahuja** [comment]
Hi @gmltA 
It looks like a pretty simple change, you want to submit a PR for that?
😄

**Comment by gmltA** [comment]
Hello @gautam-pahuja,

Yep, I guess I can.

**Comment by gautam-pahuja** [comment]
Awesome. Let me know if you face any issue.

Thanks.

**Comment by wilbertaristo** [comment]
hello is this feature available now? been wanting to change the inputTime format here...

**Comment by CastleDev** [comment]
Does this mean that the showTimeInput field is getting the format automatically? Could be why we are getting some mixed results with some users experiencing AM/PM where we expect 24 hour format (Majority is getting 24 hour format).

**Comment by mmarchuk-jama** [comment]
+1, I'm also running into this issue. I would like to be able to allow 24 hour time format for the time input, but there doesn't seem to be any way to do that.
Things I've tried so far:
- Setting my computer's locale 
- Adding the `locale="en-GB"` prop
- Adding `timeFormat="HH:mm"` prop

It seems like the "time select" respects the time format and shows 24 hour options, but the time input remains in the `hh:mm a` format instead of `HH:mm`

**Comment by plushyday** [comment]
same issue

**Comment by CastleDev** [comment]
I found the reason to why we cannot force the time input format.

The input field is of type time which only follow system locale. Meaning whatever locale we set with date-fns or timeFormat will not change this.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by oshabaeva** [comment]
Any update on this? Maybe should not use type time?

**Comment by g-akshay** [comment]
Any updates?

**Comment by Rubenvdveen** [comment]
This should just use the already existing `timeFormat` prop in my opinion. Please implement this.

**Comment by christensenmichael0** [comment]
This is an enhancement i'd also like to see. Stuck using the time select at the moment.

**Comment by Kal1na-w** [comment]
Any updates?

**Comment by kallebornemark** [comment]
Need this!

**Comment by SergTanchenko** [comment]
need this too

**Comment by fggreen** [comment]
need

**Comment by oduvanka** [comment]
need

**Comment by robheerdink** [comment]
any plans to fix this?

**Comment by neacsugeorge** [comment]
Need this too

**Comment by jerrylee007** [comment]
need this too.

**Comment by Fleurig** [comment]
Need this too

**Comment by NikolozR** [comment]
Need this

**Comment by NikolozR** [comment]
timeFormat set to "HH:mm" works for me.
