### ISSUE TITLE
MinDate, MaxDate is not working in Month Range Picker

### ISSUE THREAD

**Issue by caothuphu2013** [Hacker0x01/react-datepicker#1791]
I have a month range component below:
<DatePicker
            className="react-datepicker-wrapper"
            selected={this.state.startDate}
            startDate={this.state.startDate}
            endDate={this.state.endDate}
            maxDate={this.state.endDate}
            showMonthYearPicker
            onChange={(date) => onChange(date, 'startDate')}
          />
I found that maxDate is not working in only month range mode.
Please to help me resolve this issue.

**Comment by gautam-pahuja** [comment]
Hi @caothuphu2013 It should ideally work, there was another issue like this which was resolved:
https://github.com/Hacker0x01/react-datepicker/issues/1685

Can you please create a JSFiddle of your use case and share it with us?

Thanks

**Comment by bakaa99** [comment]
I can confirm, it is still not working for month picker

**Comment by gautam-pahuja** [comment]
@bakaa99 Can you please share a codepen or JSFiddle of what you are doing.

**Comment by bakaa99** [comment]
I don't know how to include libraries in there. This is component i am using all across my app. It works fine as when using as a datepicker, when i use it for months , the min and max does not work
```
<DatePicker
            id={id}
            autoComplete="off"
            dateFormat={showMonthYearPicker ? "yyyy/MM" : "yyyy/MM/dd"}
            showMonthYearPicker={showMonthYearPicker || false}
            placeholderText={placeholder}
            disabled={disabled}
            className={`${error && 'is-invalid'} form-control border-right-0`}
            openToDate={openToDate}
            defaultValue={value}
            value={value}
            minDate={minDate ? minDate : new Date()}
            maxDate={maxDate ? maxDate : null}
            readOnly={readOnly}
            required={validationRules.isRequired}
            // shouldCloseOnSelect={true}
            onSelect={(value) => handleChange(value, id)}
            onChange={(value) => handleChange(value, id)} />
```

**Comment by gautam-pahuja** [comment]
Can you check this:
https://codesandbox.io/embed/peaceful-water-0kzlf

**Comment by gautam-pahuja** [comment]
Check this: https://codesandbox.io/s/peaceful-water-0kzlf

**Comment by bakaa99** [comment]
i does work when both minDate and maxDate are defined,not when only minDate is defined.I don't want maxDate, only minDate

**Comment by gautam-pahuja** [comment]
@bakaa99 I updated the same sandbox to your use case and that's working as well, can you check?

**Comment by bakaa99** [comment]
@gautam-pahuja it'll not work if you change the month, i tried and it wasn't working for me.

**Comment by bakaa99** [comment]
@gautam-pahuja were you able to reproduce the issue? do you need any more info from my side?

**Comment by gautam-pahuja** [comment]
Yes, please. A GIF of what you are trying to do would be nice.

**Comment by bakaa99** [comment]
@gautam-pahuja , my requirement is very simple . I should be able to set minDate without a maxDate. I want to set the current month as minimum, so that user should not be able to select any previous month.

**Comment by caothuphu2013** [comment]
Finally, This issue has not been resolved

**Comment by caothuphu2013** [comment]
I fixed this issue. You can see by: https://github.com/Hacker0x01/react-datepicker/pull/1805

**Comment by Mukulagarwal1980** [comment]
After lots to r&d I found the solution for set minDate and maxDate properly for DatePicker component. 

It accept only "**yyyy-MM-dd hh:mm:ss**" format and also it is must be java script '**Date**' object. moment type is not supported for minDate and maxDate. 

eg. 
maxDate = {moment(this.props.maxDate).toDate()}
minDate= {moment(this.props.minDate).toDate()}
or
maxDate = {new Date("2020-05-25")}
minDate = {new Date("2010-05-25")}

These are 100% succeed formats. I am using it.
I hope it will help some one to fix their issue. You don't need to write any validation any more for selected value. Handle it on UI layer of your product. :)

**Comment by DominikPro** [comment]
If someone needs to set the date min for today, you can do it this way

`const DatePickerInput = () => {
	const [startDate, setStartDate] = useState(new Date());
	return (
		<DatePicker
			showWeekNumbers
			selected={startDate}
			onChange={(date) => setStartDate(date)}
                        locale="en-gb"
                        minDate = {new Date(startDate)}
                        placeholderText="Weeks start on Monday"

		/>
	);
};`

**Comment by Xenotech81** [comment]
I just ran into the same issue when using Luxon.DateTime as input to the picker.
Solution: Always use [toJSDate()](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toJSDate) when providing values to the picker, and transform its returns back to DateTime with [fromJSDate](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromJSDate). Easy.
