### ISSUE TITLE
Consider renaming the repo to be consistent with the bower name

### ISSUE THREAD

**Issue by martijnrusschen** [Hacker0x01/react-datepicker#18]
The bower name (and also Rails assets name) is react-date-picker (react-datepicker was already used). It would be better to have consistent naming between this repo and our names we're using for our component.

**Comment by hahahana** [comment]
Have you guys thought anymore about this? It's especially confusing given react-date-picker is something different on React Components.

**Comment by RSO** [comment]
Haven't really thought about it, no. We're open for suggestions! I agree that it's confusing, so let's do some brainstorming:

- react-datey
- react-date-input
- react-date-selector

What do you think?

**Comment by martijnrusschen** [comment]
Not a priority right now
