### ISSUE TITLE
Time Input crashes when removing ':'

### ISSUE THREAD

**Issue by bartpeeters** [Hacker0x01/react-datepicker#1809]
Version: 2.7.0
### Steps to reproduce
1. Use 'showTimeInput'.
2. Use a browser which makes `<input type="time" />` act like a normal input (Safari)
3. Remove the ':' between hours and minutes in the time input.
Result: App crashes with a 'RangerError: Invalid time value'

**Comment by gautam-pahuja** [comment]
Safari is not mentioned in the list of compatible browsers. Have you checked this in other browsers?
It works for me in firefox and chrome lastest versions.

If it is only in safari, then I would suggest you to close it.

**Comment by pmendozav** [comment]
https://github.com/Hacker0x01/react-datepicker/pull/1841 can fix it

**Comment by christiankaindl** [comment]
I am also having this issue in Safari. In the meantime, I changed my Datepicker to use `showTimeSelect` instead of `showTimeInput`: https://reactdatepicker.com/#example-select-time

**Comment by micheleberetta98** [comment]
This is still happening in version 2.10.1

**Comment by info-bit** [comment]
A custom time input component may solve this issue without changing default behaviour. Here a PR https://github.com/Hacker0x01/react-datepicker/pull/2034! We already use this edited version of react-datepicker in production.
