### ISSUE TITLE
After deployed to azure its showing following format

### ISSUE THREAD

**Issue by chetanhande** [Hacker0x01/react-datepicker#1811]
[###](

- url
![DatePickerIssue](https://user-images.githubusercontent.com/4488763/60583341-4a696b00-9da8-11e9-9103-3a232e01e18d.png)

) Expected behavior

**Comment by chetanhande** [comment]
Please help me on this

**Comment by dvaJi** [comment]
I fixed it updating the date-fns dependency in my package.json:
```
"dependencies": {
   ....
    "date-fns": "2.0.0-beta.2",
   ....
}
```
