### ISSUE TITLE
withPortal is not a true React Portal, and setting it ignores popperContainer

### ISSUE THREAD

**Issue by jeffcstock** [Hacker0x01/react-datepicker#1813]
Setting `withPortal` to `true` doesn't work how you expect, because it still renders inside the component hierarchy. ie. it's not a "true" portal outside the DOM structure.

**Example: On mobile, the `withPortal` prop doesn't append the calendar to the DOM, so it's not a "true" portal:**

![image](https://user-images.githubusercontent.com/13420097/60682616-d337e380-9e48-11e9-9b52-903465f37da8.png)

I've tried to fix this by forcing the calendar to be appended to the DOM, so I've provided a wrapper for the calendar to get ported to a div outside the body (see https://github.com/Hacker0x01/react-datepicker/pull/1074) and https://github.com/Hacker0x01/react-datepicker/pull/1074#issuecomment-428957422).

![image](https://user-images.githubusercontent.com/13420097/60683164-3b87c480-9e4b-11e9-81f8-d5c5c45fcd94.png)

However, when `withPortal` is set to `true`, it ignores any popperContainer you have provided.
**This is a problem because it can be affected by other elements that naturally appear first in the CSS stacking context:**

![Image from iOS](https://user-images.githubusercontent.com/13420097/60682482-56a50500-9e48-11e9-9d42-af443cb6def6.png)

Does anybody know of a way that we can use "withPortal" and still have a popper Container provided?

### Expected behavior
Setting `withPortal` to true will not ignore the `popperContainer` that you have set

### Actual behavior
Setting `withPortal` to true ignores the `popperContainer` that you have set

### Steps to reproduce
1. Create a Datepicker with a popperContainer set to append the calendar to the dom (see https://github.com/Hacker0x01/react-datepicker/pull/1074#issuecomment-428957422).
2. set `withPortal` to true.

Observe that it will not append the calendar to the DOM anymore.

**Comment by activenode** [comment]
What's the status of this?

**Comment by mttetc** [comment]
Why is this closed? This issue is not fixed!
Basically that library is not usable if you are using it in a container with overflow: hidden

Please, fix it

**Comment by bryanmylee** [comment]
React DatePicker 6.2.0 still adds the portal element in the wrong position within the DOM tree.

Instead of properly rendering the portal at the end of the DOM, it inserts a random element next to the trigger which causes my layout to act weird, and causes the position of the popup to be incorrect when used with other tools using portals like Radix.
