### ISSUE TITLE
Uncaught RangeError: locale must contain localize property

### ISSUE THREAD

**Issue by jepz** [Hacker0x01/react-datepicker#1815]
### Expected behavior
Expect that when adding locale="sv" to <DatePicker /> it should show Swedish.

### Actual behavior
Crashes app and gives error message: Uncaught RangeError: locale must contain localize property....

### Steps to reproduce
Packeges: date-fns 2.0.0-beta.2 (yarn add date-fns@next), react-datepicker 2.5.0.
I use registerLocale('sv', sv);

**Comment by SaschaDeWaal** [comment]
I have exactly the same problem, but with the dutch language (nl).

`import nl from 'date-fns/locale/nl';registerLocale('nl', nl);`

**Comment by TimoWestland** [comment]
Same here, doesn't matter which locale you choose. Also the error message is very confusing IMO.

**Comment by pepijnolivier** [comment]
@TimoWestland Thanks a bunch! 

Seems like things got updated and we're now using `"date-fns": "^2.1.0"` on `"react-datepicker": "^2.9.6"`.

Also, for the next guy, you'll also need to:
`import { registerLocale } from 'react-datepicker';`

**Comment by awthwathje** [comment]
In my case I had `cypress` installed in the same project, which depends on a very specific version of `date-fns` (`date-fns@1.30.1`).

Just installing the latest `date-fns` (`yarn add date-fns`) as a project's first-party dependency gave the latest version a precedence and `react-datepicker` was able to pick it up.

**Comment by danielo515** [comment]
So, why is this closed? I just installed react-datepicker today and I'm getting this error. I don't have any version of date-fns installed, only the one that cames as dependency with react datepicker:

```
➜  npm ls date-fns
spring@1.0.0 /Users/...spring
└─┬ react-datepicker@3.1.3
  └── date-fns@2.15.0 

```
So unless this library declares as dependency the wrong library I don't know what else it can be.

**Comment by simokhalil** [comment]
Faced the same problem today with v3 and figured out that you have to register the locale before importing DatePicker, so doing it in the parent component works.

In the parent component
```
import fr from 'date-fns/locale/fr';
import { registerLocale } from 'react-datepicker';

registerLocale('fr', fr);
```

And in the desired (child) component:
```
import DatePicker from 'react-datepicker';

<DatePicker
  locale="fr"
/>
```

**Comment by gain620** [comment]
> Faced the same problem today with v3 and figured out that you have to register the locale before importing DatePicker, so doing it in the parent component works.
> 
> In the parent component
> 
> ```
> import fr from 'date-fns/locale/fr';
> import { registerLocale } from 'react-datepicker';
> 
> registerLocale('fr', fr);
> ```
> 
> And in the desired (child) component:
> 
> ```
> import DatePicker from 'react-datepicker';
> 
> <DatePicker
>   locale="fr"
> />
> ```

This helped me solve the problem!
Thank you @simokhalil

**Comment by dwome** [comment]
> In my case I had `cypress` installed in the same project, which depends on a very specific version of `date-fns` (`date-fns@1.30.1`).
> 
> Just installing the latest `date-fns` as project's first-party dependency (`yarn add date-fns`) gave the latest version a precedence and `react-datepicker` was able to pick it up.

Also solved it for my case. Installing it as a standalone dep solved the issue,

**Comment by marcomald** [comment]
import {es} from 'date-fns/esm/locale'

<DatePicker locale={es} />
