### ISSUE TITLE
CustomInput css not working

### ISSUE THREAD

**Issue by robertobatts** [Hacker0x01/react-datepicker#1816]
I have a component like this:

```javascript
export class MonthPicker extends Component() {
  render() {
    return (
      <DatePicker customInput={this.getNotWorkingCustomInput()} />
      <DatePicker customInput={this.getWorkingCustomInput()} />
      )
  }

  getNotWorkingCustomInput() {
    return (
      <button className="input-datepicker-button">{this.getButtonLabel()}</button>
    )
  }


  getWorkingCustomInput() {
    return (
      <div>
        <button className="input-datepicker-button">{this.getButtonLabel()}</button>
      </div>
    )
  }
}
```

In the first case the css is not working. Can you solve it?

**Comment by tata81** [comment]
@robertobatts A live demo in code sandbox would be better, and please do mention which version of packages you are using.

**Comment by mkultra-z** [comment]
Should be `customInput` not `customerInput` 🤔

**Comment by robertobatts** [comment]
> Should be `customInput` not `customerInput` 🤔
I wrote it wrong here, I corrected it.

Here is the code on codesandbox:
https://codesandbox.io/embed/tender-resonance-m8cb0

**Comment by tata81** [comment]
@robertobatts Working solution, https://codesandbox.io/s/datepicker-issue-52jse

**Comment by robertobatts** [comment]
Yeah, I already know that solution. I just wanted to let you know that it doesn't work if you don't wrap it into a div. In general, it doesn't take the style of the parent div
