### ISSUE TITLE
onBlur not called when showMonthDropdown, dropdownMode="select" and change month

### ISSUE THREAD

**Issue by Yzchen1994** [Hacker0x01/react-datepicker#1817]
### Expected behavior
```
<DatePicker
showMonthDropdown
showYearDropdown
onBlur={this.onBlurHandler}
dropdownMode="select"
/>
```
When the user change the month or year and selects a date, it should call onBlurHandler. 

### Actual behavior
onBlurHandler is not called when the user changes month or year selection and then select a date.
onBlurHandler is called when the user just pick a date without touching month picker or year picker. 

### Steps to reproduce

1. Click the datepicker input box
2. Change the month picker
3. Pick a date
4. Observe if the onBlurHandler is called.

**Comment by maverickdude** [comment]
I'm facing the same issue.

**Comment by jspencer** [comment]
I filed this as #1652 but this report is more clearly described
