### ISSUE TITLE
Clear button does not work in Firefox

### ISSUE THREAD

**Issue by weebl2000** [Hacker0x01/react-datepicker#182]
When trying to clear a datepicker in Firefox by clicking the clear button, nothing happens.

**Comment by weebl2000** [comment]
It might be a CSS problem.

**Comment by martijnrusschen** [comment]
This was changed in https://github.com/Hacker0x01/react-datepicker/pull/165, @ntdb do you have any idea why this isn't working in Firefox?

**Comment by ntdb** [comment]
@martijnrusschen I don't but it looks like you figured it out! Something to do with `button` vs `a`?
