### ISSUE TITLE
openToDate does not show correct time on input

### ISSUE THREAD

**Issue by hlarcher** [Hacker0x01/react-datepicker#1820]
### Expected behavior
When using openToDate prop the time input should show the time for that date.

### Actual behavior
time input shows always 01:00

### Steps to reproduce
```jsx
<DatePicker
    openToDate={new Date().getTime()}
    selected={timestampEnd}
    onChange={this.onTimestampEndChange}
    minDate={timestampStart}
    showTimeInput
    timeInputLabel="Hora:"
    dateFormat={PICKER_DATE_FORMAT}
    timeFormat={TIME_FORMAT}
    className="action-date"
    locale="pt"
    disabled={this.timestampEndReadOnly()}
/>
```

**Comment by gautam-pahuja** [comment]
I think `showTimeInput ` doesn't respect `openToDate` attribute right now. The fix is simple. Do you want to go ahead and open a PR? 😃

**Comment by hlarcher** [comment]
I don't have a a fix for this that is ready for a PR and unfortunately I don't have time at the moment to go through it, just thought someone knew of a workaround for now.

When I have time if noone else has fixed this I'll give it a go.

**Comment by gautam-pahuja** [comment]
ok, no problem, Why don't you set the timestamp in `selected` every time you try to open the calendar. I think It will behave as it behaves for `openToDate` in normal scenarios.
Have you tried it?

**Comment by hlarcher** [comment]
Yea, I was trying to avoid inserting a timestamp for the user but maybe that coupled with isClearable={true} might work in this case, thanks!
