### ISSUE TITLE
TypeError: filterDate is not a function

### ISSUE THREAD

**Issue by AcidRaZor** [Hacker0x01/react-datepicker#1823]
Following example #24 

```
> <DatePicker
> selected={this.state.date}
> onChange={this.handleChange}
> filterDate={this.isWeekday}
> placeholderText="Select a weekday" />
```

I get TypeError: filterDate is not a function

/edit

Documentation is seriously lacking. Been an issue since at least 2017

isWeekday = date => {
    const day = date.getDay();
    return day !== 0 && day !== 6 && date !== today;
  };

**Comment by AcidRaZor** [comment]
After having to dig through issues on github since documentation is aweful, I found this:

```
isWeekday = (date) => {
    const day = date.day()
    return day !== 0 && day !== 6
  }
```

However, TypeError: date.day is not a function

Other than the calendar popping up and showing default formatted date (not the one you specified at all) and closing when you select something, is this actually useful to anyone?

**Comment by wenbochang** [comment]
thanks for finding this

**Comment by ybakhshi** [comment]
@AcidRaZor did you find a solution for this issue. i am also encountering it in my app.
const DatePicker = ({input, label, meta}) => {
    const className = `form-control form-control-lg ${meta.error && meta.visited ? 'is-invalid': ''}`;
    //filter weekend dates
    const isWeekday = (date) => {
        const day = getDay(date);
        return day !== 0 && day !== 6;
    };
    return (
            <div className= "form-group">
                <label htmlFor={input.name}>{label}</label>               
                <ReactDatePciker  
                    selected={input.value || null}
                    dateFormat="dd/MM/yyyy"
                    onChange ={input.onChange}
                    filterDate={(date) =>isWeekday(date)}
                    //onChange={date => setStartDate(date)}
                    minDate={new Date()}
                    // maxDate={addMonths(new Date(), 5)}
                    showDisabledMonthNavigation
                    className ={className}
                    placeholderText ="dd/mm/yyyy"
                    isClearable
                    name ={input.name}
                    locale ={input.fi}
                    autoComplete ="off"
                    
                />
                <div className ="text-danger small message error">
                    {meta.touched || meta.visited ? meta.error : ''}
                </div>
            </div>  
    );
    
    
};


i am using it in cobination with redux-form

**Comment by AcidRaZor** [comment]
@ybakhshi Sorry for the late reply. The solution is in my original post; I reformatted it so that it's more obvious

**Comment by josegerardo-sanc** [comment]
const isWeekday = (date) => {
    
        const myFecha = new Date(date);
        const day = myFecha.getDay();
        return day !== 0 && day !== 6;
    };

<DatePicker
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      filterDate={(date) => isWeekday(date)}
  />
