### ISSUE TITLE
DatePicker Opens to Incorrect Month

### ISSUE THREAD

**Issue by Kent-H** [Hacker0x01/react-datepicker#1824]
### Expected behavior
When the datepicker is opened, it should display the selected date's month.

### Actual behavior
When the datepicker is opened, it displays the wrong month.  (Appears to always be selected date's month`-1`. (If July 2019 is selected, June 2019 will be opened, etc.)

## Details
Discovered in 2.3.0 & still present after updating to 2.8.0

Using `openToDate` === `selected` doesn't have any effect.
openToDate appears to be broken in the same way (off by `-1` month)

Workaround:
```openToDate={new Date(this.state.date.getFullYear(), this.state.date.getMonth() + 1)}```

**Comment by AcidRaZor** [comment]
That is because getMonth is 0 - 11.  January is 0, February is 1, and so on

This is how JavaScript's Date object works, and might confuse people if the documentation from how the native object works compared to this plugin.

**Comment by Kent-H** [comment]
What is the expected behaviour of `openToDate={new Date()}`?

I would expect the datepicker to open to the current month, but it opens to the previous month.

Are you saying that this plugin uses 0-11 while the builtin `Date` type uses 1-12?

Even with the workaround
(`openToDate={new Date(this.state.date.getFullYear(), this.state.date.getMonth() + 1)}`)
I'm seeing inconsistent behaviour. 
Sometimes it's the correct month, sometimes it's not.  (This isn't even consistent with the same `Date`, it often opens with the incorrect month (+/-1) if the datepicker is closed & re-opened, seemingly at random.)
