### ISSUE TITLE
React DatePicker display's blank Page

### ISSUE THREAD

**Issue by Ravi-debug** [Hacker0x01/react-datepicker#1826]
Hi, 
I have created date picker using react-datepicker. When I click on calendar it is showing a blank page. I tried date picker using react-date-picker, material-ui also. It shows the same result.

**Comment by spatrick195** [comment]
Hi, did you fix this?

**Comment by eltonmarques96** [comment]
Same issue

**Comment by tylercaceres** [comment]
I have this issue too, nothing is showing in the calendar.

**Comment by estherlaus** [comment]
Same issue still, DatePicker refreshed a blank page after clicking it. Any resolution?

**Comment by multiman95** [comment]
I think this is caused by Dark Mode on iOS 13+

Am using Expo CLI so i change "userInterfaceStyle": "dark" inside  app.json file.

Doing this changed my DateTimePicker to dark allowing me to see the Date.

if set to light you will have to disable Dark mode on iOS 13+

This has been my temp fix
