### ISSUE TITLE
Pressing enter inside the input closes the popper but focuses the body  - This means form can't submit

### ISSUE THREAD

**Issue by owlyowl** [Hacker0x01/react-datepicker#1827]
### Expected behavior
Hitting enter on the input field either retains focus on the input the calendar control is on or submits the form

### Actual behavior
Hitting enter returns focus to the document body or blocks form submission with a suspected event.preventDefault() which means standard form submission behaviour doesn't work

### Steps to reproduce
https://codepen.io/anon/pen/ZgbGJr

1. Open chrome debug console and add  a live expression for the active element: https://developers.google.com/web/tools/chrome-devtools/console/live-expressions

2. Either select a date from the popper or type in the input and hit ENTER

3. Notice the focus is then set on the body of the document rather than the input in some cases focus is lost to the body, in others enter just doesn't fire submit depending on input and form context

This has the unfortunate side-effect of not allowing enter to submit the form the control is in because focus is no longer inside the form.

If you hit enter in the input field it submits or hit the button it submits

**Comment by Vages** [comment]
I was just about to report this. Is there any way to mark this as not stale?
