### ISSUE TITLE
How to add a calendar icon 

### ISSUE THREAD

**Issue by sridhar-v9** [Hacker0x01/react-datepicker#1830]
I want to add a calendar icon to this component and the calendar should open when ever the user clicks on the calendar icon.

Please do the needfull or suggest/show the right way.. thanks in advance

**Comment by sridhar-v9** [comment]
Iam able to achieve this with customInput and its working fine

**Comment by nanafan93** [comment]
I want to do this same thing. Are you able to help ?

**Comment by DuudeXX8** [comment]
They just close issue without any help 😡😡😡
