### ISSUE TITLE
change dateformat  

### ISSUE THREAD

**Issue by psdwizard** [Hacker0x01/react-datepicker#1839]
### Expected behavior
show the Date Format (Full) like 'august 1, 2019'
### Actual behavior
it only show this format 09/1/19

**Comment by Pardeep94** [comment]
@psdwizard Do you find the solution to do this?

**Comment by psdwizard** [comment]
-- Please reply above this line --


Hi Hacker0x01/react-Datepicker,

 Thanks for the email! 

 We’re working on your request, and we’ll get back to you as soon
as possible (Monday-Friday 9am-10pm Philippine time). 

 Thanks again, 
 Team Fullstack HQ

 P.S. We’ve got our best developers on it :)
