### ISSUE TITLE
 this._date.locale is not a function

### ISSUE THREAD

**Issue by SpencerCDixon** [Hacker0x01/react-datepicker#184]
I finally realized I need to use a moment() for the initial date to work but now whenever I try to change the date I get `this._date.locale is not a function`

Pretty new to JS so sorry if there is a simple answer but I can't seem to figure out what to do

**Comment by SpencerCDixon** [comment]
Wow cant believe I missed this:
`import moment from 'moment';` fixed my problem

**Comment by mskeving** [comment]
Hey - I'm getting this same problem and I'm not sure how to fix it. Would you mind elaborating a bit more on how you fixed it?

I'm rendering the datepicker with selected=moment(), but when I click on the input box to get the calendar to popup, I get this error.

**Comment by SpencerCDixon** [comment]
can you paste a gist with the code? I can compare it to what I got working

**Comment by martijnrusschen** [comment]
Hi guys, I'm working on an improved version of the documentation. Take a look at https://github.com/Hacker0x01/react-datepicker/pull/189 to see if that makes it more clear. Comments are welcome!

**Comment by SpencerCDixon** [comment]
Looks like a great improvement! +1

**Comment by mskeving** [comment]
Thanks for the clarification. I think I have everything set up correctly, though I'm still getting that error 'this._date.locale is not a function.'

this is what my code looks like using coffeescript:

```
React = require('react')
moment = require('moment')
DatePicker = React.createFactory(require('react-datepicker'))

module.exports = React.createClass
    handleChange: (date) =>
        @setState startDate: date

    getInitialState: ->
        startDate: moment()

    render: ->
        DatePicker
            selected: @state.startDate
            onChange: @handleChange
```

I have also attached a screenshot of what my browser is displaying. You can see from the console that I do have moment available. The errors come up when I click on the date picker. I imagine I'm just missing something silly...

![screenshot 2015-09-28 10 21 16](https://cloud.githubusercontent.com/assets/1342734/10143030/e21f1bee-65ca-11e5-90e8-acdd8e219e39.png)
