### ISSUE TITLE
Keyboard up/down arrow input no longer work after screen scroll with mouse

### ISSUE THREAD

**Issue by Joshua-rose** [Hacker0x01/react-datepicker#1840]
### Expected behavior
Arrow up and down to scroll by week as before scroll.
### Actual behavior
After scroll using scroll wheel, up and down default to using Chrome's auto-fill.
### Steps to reproduce
Fill the date field so that Chrome's auto-fill is populated
Click or select the date field. After the popup has shown, scroll up or down on the page. Attempt to use up or down arrow.

**Comment by goxr3plus** [comment]
mmmm

**Comment by goxr3plus** [comment]
Any updates on this?

**Comment by Joshua-rose** [comment]
This may be a solution.
https://stackoverflow.com/questions/59426792/stop-chrome-autocomplete-dropdown-taking-focus
using `autocomplete="off"`
