### ISSUE TITLE
Choose only specific days on calendar, e.g., Fridays?

### ISSUE THREAD

**Issue by gravitymedianet** [Hacker0x01/react-datepicker#1843]
Is there a way to make only Fridays selectable (or any other day of week passed)?

**Comment by preetampvp** [comment]
` const filterDatePickerDates = date => {
    var day = date.getDay();
    if (calendarView === Constants.CalendarWeekly) {
      return day === 1;
    }
    return day;
  };`

Setting `filterDate` prop

`          
<DatePicker
      selected={selectedDate}
      locale="en-GB"
      highlightDates={highlightedDates}
      filterDate={date => filterDatePickerDates(date)}
      onSelect={date => setDate(date)}
      inline></DatePicker>
`
