### ISSUE TITLE
CRITICAL ERROR FOR REACT

### ISSUE THREAD

**Issue by ivanafanasyev** [Hacker0x01/react-datepicker#1846]
### Steps to reproduce

You function into es/index and lib/index have MM-YYYY - it's incorrect for react. Always will be error when onChange, with use yyyy intead of YYYY. dateFormat works only for showing

**Comment by askesis** [comment]
@CaptainIvan hey, I don't understand what is happening with YYYY and yyyy, but I have the problem `use the yyyy instead YYYY`, but yyyy is doesn't work

I suppose, there was an error with the YYYY format and @martijnrusschen fixed it in #1767 
But now I have the opposite error

**Comment by Irrelon** [comment]
The version of date-fns less than 2 uses YYYY, from version 2 it uses yyyy
