### ISSUE TITLE
Custom header does not work with month picker

### ISSUE THREAD

**Issue by tu4mo** [Hacker0x01/react-datepicker#1847]
### Expected behavior

Custom header should be rendered when showMonthYearPicker is enabled. renderCustomHeader should provide functions for month picker header.

### Actual behavior

Custom header is not rendered when showMonthYearPicker is enabled.

### Steps to reproduce

Use renderCustomHeader with showMonthYearPicker.

**Comment by arsmth** [comment]
I may have a fix in [this commit](https://github.com/sturents/react-datepicker/commit/48b030907f28024286b126520f452bb1bc852840)

Not sure why renderCustomHeader was ignored if showMonthYearPicker. Can anyone shed some light?

**Comment by enagy27** [comment]
It looks like this isn't just a feature request, but a bug, because the header does not render navigation buttons if there is a custom header 😞

**Comment by tu4mo** [comment]
That's not a bug, that's is the feature. There are functions passed for the navigation buttons, so you can implement them yourself.

**Comment by tu4mo** [comment]
@arsmth Are you planning to submit that PR? If not, I can give it a shot. It would be a breaking change though.

**Comment by arsmth** [comment]
@tu4mo Go for it, I’m on holiday for a few weeks. Have you thought about the +/- year functions?

**Comment by mohammedabualsoud** [comment]
Any updates on this ?
