### ISSUE TITLE
When `selected` isn't specified, I see a warning in the console.

### ISSUE THREAD

**Issue by cowboy** [Hacker0x01/react-datepicker#186]
Many of the examples on https://hacker0x01.github.io/react-datepicker/ don't have a `selected` property. When clicking them (and in my own code) I see this warning in the console:

> Warning: Failed propType: Required prop `selected` was not specified in `Calendar`. Check the render method of `DatePicker`.

Is this warning really necessary? Can it be removed?

**Comment by cowboy** [comment]
(Or is there a way to prevent the warning from displaying?)

**Comment by martijnrusschen** [comment]
This is caused because selected is a required prop in calendar.jsx. This looks like a leftover after we've added more functionality like placeholders. I'll go ahead and remove this to get rid of those warnings.
