### ISSUE TITLE
Datepicker is missing first three weeks

### ISSUE THREAD

**Issue by zyion** [Hacker0x01/react-datepicker#1866]
**Describe the bug**
The Datepicker is missing the first three weeks of the month.

**To Reproduce**
1. Changed timezone to: America Los_Angeles Standard Time
2. Go to https://reactdatepicker.com/

**Expected behavior**
The full month should be displayed in the Datepicker

- iOS
- Chrome
- Version 76.0.3809.100 (Official Build) (64-bit)

![Screen Shot 2019-08-23 at 11 53 45 am](https://user-images.githubusercontent.com/8841642/63561342-75ea1580-c50e-11e9-85d5-8486cf0a6e73.png)

![Screen Shot 2019-08-23 at 10 12 50 am](https://user-images.githubusercontent.com/8841642/63561315-594ddd80-c50e-11e9-8fa0-634c9ec354f8.png)

**Comment by Volodymyr-Bairamov** [comment]
Same issue when using Time Shift Extension for Chrome and setting -5h timezone
