### ISSUE TITLE
When 'select' prop is not provided (because I want a blank picker), picking anything causes instant breakage

### ISSUE THREAD

**Issue by unphased** [Hacker0x01/react-datepicker#187]
[Here](https://github.com/Hacker0x01/react-datepicker/blob/master/dist/react-datepicker.js#L494):

```
if (nextProps.selected !== this.props.selected) {
    this.setState({
        date: new DateUtil(nextProps.selected).clone()
    });
}
```

Once selected and the widget gets re-rendered by parent, we have nextProps.selected being `null`. At this point the code explodes because `new DateUtil(null)` cannot have `clone` called on it...

**Comment by arnars** [comment]
Or if `this.state.date: null` I get the following error:
`Warning: Failed propType: Required prop `selected` was not specified in `Calendar`. Check the render method of `DatePicker`.`

This is when trying not to show date by default, but actually show the placeholderText.

**Comment by williamcoates** [comment]
If anyone else bumps into this issue, seems like a workaround is to initially set `selected` to empty string.

**Comment by cnardi-git** [comment]
^ This does not work for me. I set the initial state of the date to null, and called it on the selected prop, just in the example above, but when I select a date from the calendar I get this repeated console error:

Uncaught TypeError: t.format is not a function

This prevents the calendar popover from closing.  However, the date value is set into the components state.

**Comment by jeannei** [comment]
@williamcoates solution worked for me. 

I was getting the error "Cannot read property 'clone' of undefined." I set the initial state to  <code>{date: null} </code>, and set the prop <code>selected={this.state.date}</code> and in the <code>onChange</code> callback updated date <code>   this.setState({date: date}) </code>

**Comment by martijnrusschen** [comment]
Just tried to reproduce this issue with the following code:
```
export default React.createClass({
  displayName: "Default",

  getInitialState() {
    return {
      startDate: null
    };
  },

  handleChange(date) {
    this.setState({
      startDate: date
    });
  },

  render() {
    return <div className="row">
      <pre className="column example__code">
        <code className="jsx">
          {"<DatePicker"}<br />
              {"selected={this.state.startDate}"}<br />
              {"onChange={this.handleChange} />"}
        </code>
      </pre>
      <div className="column">
        <DatePicker
          selected={this.state.startDate}
          onChange={this.handleChange} />
      </div>
    </div>;
  }
});
```

This example works fine for me and doesn't show an initial selected date. This allows me to select a date that will be saved in the state as `startDate`. I guess this is the best way to solve this issue.

Furthermore, I just discovered that the `<DatePicker placeholder="hi />` doesn't need a selected too :)

**Comment by rafeememon** [comment]
I don't think this is an issue anymore now that `DateUtil` has been removed.
