### ISSUE TITLE
[Demo Site] A locale object was not found for the provided string ["en-GB"].

### ISSUE THREAD

**Issue by Joshua-rose** [Hacker0x01/react-datepicker#1871]
**Describe the bug**
The locale example on the demo site is not working correctly. It is using my locale (en-US) instead of the stated locale (en-GB). It is also produces an error. Error reproduced below

**To Reproduce**

1. Go to 'https://reactdatepicker.com/#example-locale'
2. Open Dev Tools, (I am using chrome in this instance. However issue is also present in FireFox)
3. Click on the date field
4. View console.

> Scroll up or down to reproduce the.  

> See error in Additional Context

**Expected behavior**
Expected date popup with correct local (en-GB in this instance).

**Screenshots**
![image](https://user-images.githubusercontent.com/49696165/63693257-96052780-c7e1-11e9-85b3-dfed61871a9a.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome, Firefox
- Version 76.0.3809.100, 68.0.2 respectivly

**Additional context**
Error procuced from console
```
backend.js:6 A locale object was not found for the provided string ["en-GB"].
r @ backend.js:6
we @ index.js:403
(anonymous) @ index.js:552
(anonymous) @ index.js:2459
(anonymous) @ index.js:2445
(anonymous) @ index.js:2442
(anonymous) @ index.js:2654
(anonymous) @ index.js:2708
value @ index.js:2836
yi @ react-dom.production.min.js:3880
mi @ react-dom.production.min.js:3871
Jo @ react-dom.production.min.js:6116
Wo @ react-dom.production.min.js:5101
Ho @ react-dom.production.min.js:4958
Fo @ react-dom.production.min.js:4817
(anonymous) @ react-dom.production.min.js:2543
a.unstable_runWithPriority @ scheduler.production.min.js:338
cr @ react-dom.production.min.js:2513
Rr @ react-dom.production.min.js:2538
hr @ react-dom.production.min.js:2528
Ie @ react-dom.production.min.js:6706
Bn @ react-dom.production.min.js:1817
Ln @ react-dom.production.min.js:1790
```

**Comment by Joshua-rose** [comment]
Closed with #1872

**Comment by Snazzie** [comment]
Yep, this is silly.

**Comment by Snazzie** [comment]
This isnt fixed, even on your demo site with "en-GB" your input is still "en-US". i also get this console warning with "en-US" as locale.

**Comment by owainharris** [comment]
Same issue - not fixed.

**Comment by jimsheen** [comment]
Bump

**Comment by wviveiro** [comment]
From his commit on issue #1872 I checked he did 2 things:

1. Import the locale from date-fns to the code

```javascript
import enGB from "date-fns/locale/en-GB";
```

2. Register the locale using react-datepicker function when component is mounted

```javascript
registerLocale('gn-GB', enGB);
```

So, in order to make it work in my code, I did the following:


```javascript

import React, { useEffect } from "react";
import DatePicker, { registerLocale } from "react-datepicker";
import enGB from "date-fns/locale/en-GB";


// REACT HOOK
const MyDatePicker = () => {
    useEffect(() => {
        registerLocale("en-GB", enGB);
    }, []);

    return (
        <DatePicker
            locale={'en-GB'}
        />
    );
};

// React Component
class MyDatePickerComponent extends React.Component {
    componentDidMount() {
        registerLocale("en-GB", enGB);
    }
    render() {
        return (
            <DatePicker
                locale={'en-GB'}
            />
        );
    }
}

```

**Comment by LaurenceRSkoropinski** [comment]
For me adding  `dateFormat="P"` to get correct Format for GB, see https://date-fns.org/v2.21.2/docs/format
```
<DatePicker
      selected={startDate}
      onChange={date => setStartDate(date)}
      locale="en-GB"
      placeholderText="Weeks start on Monday"
          dateFormat="P"
    />
```

**Comment by janmisek1** [comment]
Still not fixed.  `registerLocale` solve the problem for future renders, but the first render is always with console warning.

**Comment by D-Thrane** [comment]
Still a problem

**Comment by jorgemustafa** [comment]
Still a problem with pt-BR too

**Comment by asafcraftio** [comment]
If the issue is changing the start date of the week.
there is a [prop at the bottom of the list](https://reactdatepicker.com/#example-calendar-start-day) that can be used (without any need to use `date-fns` at all, in this example Monday is the first day of the week:
```
<DatePicker
  calendarStartDay={1}
/>

**Comment by lukaskvapil** [comment]
For anyone why the localisation is not working in the input field, there are actually separate 2 things going on here:

- one is format of the calendar popup - that is determined by the `locale` property which needs to register the relevant locale using the `registerLocale` function, as done #1872. It is also mentioned in the [README](https://github.com/Hacker0x01/react-datepicker#localization)
- however, what appears in the input field is determined by the `dateFormat` property which accepts [date-fns formatting](https://date-fns.org/v2.21.2/docs/format). To have the localised version, you can use the `dateFormat="P"`, which then uses formatting according to provided `locale`.

For fully localized datepicker, both are needed:

```
import React, { useEffect } from "react";
import DatePicker, { registerLocale } from "react-datepicker";
import enGB from "date-fns/locale/en-GB";

const MyDatePicker = () => {
    useEffect(() => {
        registerLocale("en-GB", enGB);
    }, []);

    return (
        <DatePicker
            locale={'en-GB'}
            dateFormat="P"
        />
    );
};
```

**Comment by nicolak** [comment]
Same problem. Any update?

**Comment by davidnormo** [comment]
My workaround for this is:

```tsx
import DatePicker, { registerLocale } from "react-datepicker";
import { useLayoutEffect, useState } from "react";
import enGB from "date-fns/locale/en-GB";

const MyDatePicker = () => {
  const [locale, setLocale] = useState<string | undefined>(undefined);

  useLayoutEffect(() => {
    // register all locales and set the desired one in this effect... 
    registerLocale("en-GB", enGB);
    setLocale("en-GB");
  }, []);

  return (
    <DatePicker locale={locale} />
  );
};
```

It would be nice to be able to call `registerLocale` in the module scope ahead of it being rendered...
