### ISSUE TITLE
hide calendar

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [Hacker0x01/react-datepicker#1875]
Is there anyway to not use calendar? i can't find it in documentation.

I really like the way this component implements and it options, unlike default `date` input, this component look consistent in every browser but calendar popup is not suitable for mobile browser so I want to use this component as a [datetime-loca](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)l input polyfill.

**Comment by ao-alexi** [comment]
does adding open={false} prop solve your problem? try it
