### ISSUE TITLE
FindDomNode warning with react strict mode

### ISSUE THREAD

**Issue by jRichardeau** [Hacker0x01/react-datepicker#1890]
This is not really a bug but when using react in strict mode a warning appears linked to OutsideClickHandler : 

`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of r which is inside StrictMode. Instead, add a ref directly to the element you want to reference.`

**To Reproduce**
Run react in strict mode and use `calendarContainer` prop

**Expected behavior**
I think this can be solved with this https://github.com/Pomax/react-onclickoutside/pull/319

Thank you

**Comment by belonog** [comment]
Have the same issue when using `custom Input` prop.

**Comment by gyenabubakar** [comment]
Hello! Is this fixed? I'm facing a similar issue in a Next,js project.

**Comment by siddacool** [comment]
I get the same issue when using showMonthDropdown and showYearDropdown

**Comment by Shaker-Hamdi** [comment]
Any updates on this?

**Comment by ievgen-klymenko-uvoteam** [comment]
same, using showYearDropdown with react-hook-form
