### ISSUE TITLE
Placeholder doesn't show up if selected prop == null

### ISSUE THREAD

**Issue by conradjonp** [Hacker0x01/react-datepicker#1903]
**Describe the bug**
Placeholder doesn't show up if selected prop is equal to null. Instead it's displaying "invalid date"

**To Reproduce**
```
<DatePicker
    customInput={<WebDateDisplay lang={lang}/>}
    dateFormat={"yyyy-MM-dd"}
    maxDate={moment(maxDate).toDate()}
    placeholderText={placeholder}
    selected={dateValue == null ? null : moment(dateValue).toDate()}
    showYearDropdown
    scrollableYearDropdown
    yearDropdownItemNumber={100}
    onChange={this.props.onChange}/>
```

**Expected behavior**
expected behaviour should show the placeholder text obviously....

**Comment by VBGH** [comment]
Hello,

In order for that to work, you have to pass the placeholder to customInput:
<DatePicker
    customInput={<WebDateDisplay lang={lang}  placeholderText={placeholder}/>}
....
/>
===>
WebDateDisplay= props =>{
<input placehorlder={props.placeholderText} />
}

Hope this works for you!

**Comment by henkkasoft** [comment]
You should use placeholderText in DatePicker like @VBGH said, but the props  passed to the WebDateDisplay is props.placeholder

(small typing error there also placehorlder=placeholder)
