### ISSUE TITLE
v2.9.4+ Requires React 16

### ISSUE THREAD

**Issue by LucasUnplugged** [Hacker0x01/react-datepicker#1912]
**Describe the bug**
Starting with v2.9.4, `react-datepicker` requires React 16. This is because commit #1898 makes a change to calendar.jsx, which includes a call to `React.createRef`, which is only a method in v16 of React.

If you could update the **Compatibility** section of the readme.md file, that'd be great. Alternatively, if you'd like to maintain compatibility with React 15, you may be able to do so by finding an alternative to using `React.createRef`.

**Comment by martijnrusschen** [comment]
I agree with this. This has been an oversight on our end, as we didn't check backward compatibility before releasing this change.

**Comment by macpham** [comment]
No problem, thanks for this repo!
