### ISSUE TITLE
customInput component with input child cannot be typed in

### ISSUE THREAD

**Issue by benuleau** [Hacker0x01/react-datepicker#1915]
When creating a date picker with a custom input component, typing into the input field auto-formats to the incorrect date. For example, if the following date is in the input field: 01/01/2019, backspacing twice will automatically change the date to 01/01/2020. Backspacing 3 more times changes the date to 01/01/2002. 

This is my code that is experiencing the issue:

```js
const MyForm = () => (
  <DateInput />
);

const DateInput = () => {
  const [test, setTest] = useState(new Date());
  return (
    <DatePicker selected={test} onChange={date => setTest(date)} customInput={<CustomInput />
  );
}

const CustomInput = ({value, onClick, onChange}) => (
  <input value={value} onClick={onClick} onChange={onChange} />
);
```

Oddly enough, when using the standard date picker (without the custom input), everything works as expected. 

Below is a gif of what happens when backspacing in the date picker with a custom input component
![react-datepicker-issue](https://user-images.githubusercontent.com/14222900/64983939-a9ab2780-d88f-11e9-9798-187464adb6d2.gif)

**Comment by VLaD0S** [comment]
@benuleau under the hood datepicker uses customInput = <input type="text" /> || other
 Also, you don't need to pass down all the event handlers.
`<DateInput customInput={(<input type="text")}>`

**Comment by antiold** [comment]
@benuleau this works, I guess some other prop is required (like `onKeyDown` (?), to lazy to debug)
```js
const CustomInput = props => <input {...props} />
````

**Comment by ivanosevitch** [comment]
@antiold @benuleau you actually have to additionally  pass down `onFocus` to the CustomInput to avoid this issue.
The following code doesn't reproduce the bug:

```
const DateInput = () => {
  const [test, setTest] = useState(new Date());
  return (
    <DatePicker selected={test} onChange={date => setTest(date)} customInput={<CustomInput />
  );
}

const CustomInput = ({value, onClick, onChange}) => (
  <input value={value} onFocus={onFocus} onChange={onChange} />
);
```

This is not intuitive, it ought to be somewhere in the documentation.

_Using react-datepicker 2.10.1_

**Comment by benuleau** [comment]
@antiold @ivanosevitch thank you, you're correct. Passing the rest of the properties from `DatePicker` solves my issue. [Link to a working version of the picker](https://codesandbox.io/s/serene-browser-gq3sj)

**Comment by L5eoneill** [comment]
Wow. When I tried this in custom input, the focus seemed to flicker back and forth from input to calendar at a crazy rate. Completely not working.
