### ISSUE TITLE
Dynamic minDate wrong date if only time is selected

### ISSUE THREAD

**Issue by augnustin** [Hacker0x01/react-datepicker#1917]
**Describe the bug**

The selected date doesn't match what was pre-selected.

**To Reproduce**

1. 2 `Datepicker`s, with `showTimeSelect` attribute, and the second one having a `minDate={valueOfTheFirstOne}` 
2. Select a datetime with the first one
3. Select only a time with the second one
4. The selected date is today's date instead of the pre-selected one which was the minDate

**Expected behavior**

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1970156/65031480-9fe1fc80-d941-11e9-94f3-4eeb1e8adaa6.gif)

**Desktop:**

- OS: Linux
- Browser: Chrome
- Version: 76

Hope it helps

**Comment by developdeez** [comment]
Same issue
