### ISSUE TITLE
Disable keyboard appearing on mobiles

### ISSUE THREAD

**Issue by YasiruDev** [Hacker0x01/react-datepicker#1921]
I tried many suggestions on internet to prevent keyboard appearing  on mobile.but those are not solve my problem.

```
<DatePicker  onChange={this.bidHandleChangeStart} 
value={this.state.startDate} name="startDate" maxDate={new Date()}  customInput={<CustomInput />} />

const CustomInput = React.forwardRef((props,ref) => {
    return (
        <input
            readOnly={true}
        />
    )
})
```
How to disable keayboad on mobiles?

**Comment by solankirohan** [comment]
I am also facing the same issue...any solution to this issue?

**Comment by cicconewk** [comment]
This issue has been pointed out in previous threads, you should check them out. You might find a solution there.
