### ISSUE TITLE
Missing utcOffset in DatePicker even if it is still documented in datepicker.md

### ISSUE THREAD

**Issue by ultralabed** [Hacker0x01/react-datepicker#1922]
**Describe the bug**

I was hoping that I can tweak the `today's timezone` in DatePicker by using `utcOffset` which was stated in  [`datepicker.md`](https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md). However, `utcOffset` is removed from the source code in this from [version 0.58](https://github.com/Hacker0x01/react-datepicker/compare/v0.58.0...master#diff-24813adcea9b58ff52aaad101420ab71L33).

**To Reproduce**
Assume `browser timezone` is `UTC+00:00`

1. Pass in `utcOffset` as a prop like below
```
      <DatePicker
        ...
        utcOffset={480}
      />
```
2. Click and open the DatePicker in browser
3. Seeing `today` with timezone of `UTC+00:00`

**Expected behavior**
I expect to see `today` with timezone of `UTC +08:00`

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome 
- Version: 77.0.3865.90 64 bits

**Additional context**
 I really hope `utcOffset` is still supported. However, If it is not supported any more, I think the document needs to be updated accordingly.

**Comment by Yueran-Yu** [comment]
Anyone can help with the UTC problem?
