### ISSUE TITLE
Add a YearPicker

### ISSUE THREAD

**Issue by boubaks** [Hacker0x01/react-datepicker#1927]
It would be perfect to have also a year picker !

**Comment by comphonia** [comment]
right! imagine clicking a previous month button 200+ times to find your birthday ![](https://i.imgur.com/MJu2FgV.jpg)

**Comment by FREEZX** [comment]
> right! imagine clicking a previous month button 200+ times to find your birthday ![](https://camo.githubusercontent.com/65942f61f0d5863ab11fcc54c2bf690fffcf0996/68747470733a2f2f692e696d6775722e636f6d2f4d4a75324667562e6a7067)

Seems like your use case is covered with this:
https://reactdatepicker.com/#example-year-dropdown

**Comment by boubaks** [comment]
No, I wasnt looking for a select of a year inside the calendar.
But more just like the Month Picker but for years (https://reactdatepicker.com/#example-month-picker)

**Comment by FREEZX** [comment]
> No, I wasnt looking for a select of a year inside the calendar.
> But more just like the Month Picker but for years (https://reactdatepicker.com/#example-month-picker)

Makes sense. I was referring to "Selecting your birthday" as being solved.

In your case, perhaps simply making a dropdown of years to select could solve your issue, or a number input field with min and max values?
What would you expect from an implementation in this library?

**Comment by boubaks** [comment]
I'm using this component with date format selected by the user.

The user could choose between MM/DD/YYYY, MM/YYYY and YYYY format.
It should be normal to him to have a datePicker organised differently for each format.

About the select, it's the solution i'm using now even I don't think it's the best solution ;)

**Comment by ematipico** [comment]
This feature is interesting and needed

**Comment by sauldelgado** [comment]
Adding an option `showYearPicker` in the same fashion as the existing `showMonthYearPicker` would definitely be a useful feature.

**Comment by gautam-pahuja** [comment]
Added a yearpicker https://github.com/Hacker0x01/react-datepicker/pull/2130

@martijnrusschen this issue can be closed too.
