### ISSUE TITLE
Bug in style

### ISSUE THREAD

**Issue by Wellers0n** [Hacker0x01/react-datepicker#1932]
I am with this bug on the style.

How resolve it ?

![image](https://user-images.githubusercontent.com/39449389/66426377-14abd200-e9e8-11e9-84d5-ae586514ad91.png)

**Comment by xoche** [comment]
You can make the container a little bigger using the class: 

.react-datepicker-popper {
    width: 320px;
}

The width is just an example, use a size that better fits you

**Comment by Wellers0n** [comment]
in styled component how would be it ?

**Comment by xoche** [comment]
Probably you have something like this:

```
... // Rest of the code
render(){
    <SDatePicker className={this.props.className} /*More props*/ />
}
```

Where the SDatePicker is styled like this:
```
const SDatePicker = styled(DatePicker)`
    & .react-datepicker-popper {
        width: 320px;
    }
`;

```

**Comment by Wellers0n** [comment]
nice
