### ISSUE TITLE
Minified React error #290 when clicking month or year dropdown

### ISSUE THREAD

**Issue by mmarchuk-jama** [Hacker0x01/react-datepicker#1939]
**Describe the bug**
When using any of the month or year dropdowns with `showMonthDropdown`, `showMonthYearDropdown`, etc... I get a minified react error. The component is replaced with the error text. This is present in the live examples found on the reactdatepicker website [here](https://reactdatepicker.com/#example-month-dropdown). 
I used the examples from the live page, locally, and don't get the error. However, my browser tab becomes unresponsive and I'm forced to kill my browser and restart it.

**To Reproduce**
1. Go to https://reactdatepicker.com/#example-month-dropdown
2. Click the datepicker input
3. Click the month or year dropdown
4. See error rendered instead of datepicker

**Expected behavior**
A month or year picker should pop up

**Screenshots**
![Screenshot_10_15_19__8_55_AM](https://user-images.githubusercontent.com/46354960/66848247-955b5880-ef29-11e9-82bf-219a46f6b796.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave 10.14.6
- Browser: Chrome, Safari, Firefox
- Version: Latest

**Comment by manuelfink** [comment]
Having the same error.

Full error trace:

react-dom.production.min.js:4260 Error: Minified React error #290; visit https://reactjs.org/docs/error-decoder.html?invariant=290&args[]=options for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Qr (react-dom.production.min.js:2938)
    at u (react-dom.production.min.js:3007)
    at f (react-dom.production.min.js:3071)
    at h (react-dom.production.min.js:3112)
    at react-dom.production.min.js:3222
    at gi (react-dom.production.min.js:3794)
    at Jo (react-dom.production.min.js:6135)
    at Wo (react-dom.production.min.js:5101)
    at Ho (react-dom.production.min.js:4958)
    at Fo (react-dom.production.min.js:4817)

**Comment by martijnrusschen** [comment]
This should be fixed with #2132 merged. We will release a new version shortly.

**Comment by mmarchuk-jama** [comment]
Thank you @martijnrusschen!
