### ISSUE TITLE
Calendar covers the input when there is 6 weeks in a month

### ISSUE THREAD

**Issue by nanopx** [Hacker0x01/react-datepicker#1940]
**Describe the bug**
Calendar covers the input when there is 6 weeks in a month.
Reproduces only when the picker is displayed at the top of the input.

**To Reproduce**

1. Go to https://reactdatepicker.com/
2. Resize browser height until the datepicker is displayed at the top of the input
3. Go to `June 2019` in the picker
4. See the picker covering the input

**Expected behavior**
Do not cover the input

**Screenshots**
![](https://i.gyazo.com/4fe767b57d060c2da520971bfd3c7746.png)

**Desktop (please complete the following information):**

- Mac OS
- Chrome
- 77.0.3865.90

**Smartphone (please complete the following information):**

Didn't check 🙇

**Comment by charlesrajesh** [comment]
I am also having this problem. Can someone help? 
my react date picker version is pretty old (0.55.0). I want to know the reason behind this different behavior.

**Comment by shijinkrishna** [comment]
Hi @nanopx Where you able to find a solution for this? Setting popper properties like below moves the popper up, but if I do so, it shows away from the input when there are only 5 fields.

```
popperModifiers={{
	offset: {
		enabled: true,
		offset: "0px, 38px"
	},
	preventOverflow: {
		enabled: true,
		escapeWithReference: false, // force popper to stay in viewport (even when input is scrolled out of view)
		 boundariesElement: 'viewport'
	}
 }} 
```
