### ISSUE TITLE
Using `showTimeInput` with a null `selected` value shows incorrect time

### ISSUE THREAD

**Issue by MattCrouch** [Hacker0x01/react-datepicker#1941]
**Describe the bug**
We are trying to initialise an empty datepicker that uses the time input box as well.

When we do this, the date field itself is empty, but the time field is initialised as `01:00`.

It appears to be linked to the timezone the user is in. We're in the UK here (UTC+1).

**To Reproduce**

```jsx
() => (
  <DatePicker
    selected={null}
    showTimeInput
  />
);
```

1. Create datepicker with time input
2. Click on field
3. See the time reads `01:00`

**Expected behavior**
The time should read `00:00`

**Screenshots**
<img width="264" alt="Screenshot 2019-10-16 at 10 46 09" src="https://user-images.githubusercontent.com/1612120/66908443-015dbf80-f003-11e9-9692-13d8d26f3879.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: 77

but also occurs on Firefox 69 and Edge 18

**Comment by MinhTuong12101996** [comment]
how css showTimeinput ?
