### ISSUE TITLE
React Datepicker with format mm/yyyy css is breaking, Instead of grid, it is coming as list

### ISSUE THREAD

**Issue by kumaraswamyDR** [Hacker0x01/react-datepicker#1943]
<img width="116" alt="Screenshot 2019-10-18 at 2 28 49 PM" src="https://user-images.githubusercontent.com/15646892/67080857-ad460d00-f1b3-11e9-9a5e-c1ecd780b604.png">

Thanks for help

**Comment by dskusuma** [comment]
Hi I have the same issue. Any solution for this?

**Comment by dskusuma** [comment]
I tried to import the scss and now it's working fine. Have you tried?
```
import 'react-datepicker/src/stylesheets/datepicker.scss'
```
