### ISSUE TITLE
datepicker is not giving time when i do not initialize the picker with 'new Date()'

### ISSUE THREAD

**Issue by ravi26** [Hacker0x01/react-datepicker#1946]
**Describe the bug**
   Datepicker is not giving time when i do not initialize the picker with 'new Date()'. There are cases when one do not want the datepicker to be initialized. 
**To Reproduce**
1. Do not initialize Datepicker with new Date();
2. You will only see date now. No time

**Expected behavior**
Even if we do not initialize datepicker component with new Date(), it should still show time date with current time
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by atul-kumar-singh** [comment]
Facing same issue.
