### ISSUE TITLE
locale property doesn't work with "pt-BR" locale

### ISSUE THREAD

**Issue by Cligor** [Hacker0x01/react-datepicker#1949]
**Describe the bug**
I'm using locale pt-BR but component still in english (labels and formats)

**Screenshots**
![image](https://user-images.githubusercontent.com/22886741/67515280-b8e27980-f674-11e9-9273-43c3a76dbee4.png)

![image](https://user-images.githubusercontent.com/22886741/67515329-d1eb2a80-f674-11e9-8f9f-c034aafaa4ff.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Opera
- Version: 63.0.3368.107

- OS: Windows 10
- Browser: Firefox
- Version: 69.0.3

- OS: Windows 10
- Browser: Chrome
- Version: 77.0.3865.120

**Comment by ShiiRochi** [comment]
The same thing, but with 'ru' locale

**Comment by ShiiRochi** [comment]
@Cligor, I made it work for 'ru' locale by installing date-fns as a dependency (maybe it is unnecessary as soon as date-fns is dep of react-datepicker) and importing of the desired local and passing it as locale prop into Datepicker component. 
```
import ru from 'date-fns/locale/ru';

<Datepicker
    selected={value}
    onChange={date => onValueChange(date)}
    showTimeSelect
    showTimeSelectOnly
    timeIntervals={10}
    timeCaption="Time"
    locale={ru}
    dateFormat="hh:mm aa"
/>
```

**Comment by lucaswx2** [comment]
@Cligor use 'ptBR' instead of 'pt-BR'

`
import ReactDatePicker, { registerLocale} from 'react-datepicker';
import ptBR from 'date-fns/locale/pt-BR';
registerLocale('ptBR', ptBR);

  <ReactDatePicker
        dateFormat="dd/mm/yyyy"
        locale="ptBR"
      />

`

**Comment by lucaswx2** [comment]
@Cligor use 'ptBR' instead of 'pt-BR'

```
import ReactDatePicker,{registerLocale} from 'react-datepicker';
import ptBR from 'date-fns/locale/pt-BR';
registerLocale('ptBR', ptBR);

 <ReactDatePicker
        name='date'
        selected={selected}
        locale="ptBR"

      />

```

**Comment by Cligor** [comment]
> @Cligor, I made it work for 'ru' locale by installing date-fns as a dependency (maybe it is unnecessary as soon as date-fns is dep of react-datepicker) and importing of the desired local and passing it as locale prop into Datepicker component.
> 
> ```
> import ru from 'date-fns/locale/ru';
> 
> <Datepicker
>     selected={value}
>     onChange={date => onValueChange(date)}
>     showTimeSelect
>     showTimeSelectOnly
>     timeIntervals={10}
>     timeCaption="Time"
>     locale={ru}
>     dateFormat="hh:mm aa"
> />
> ```

It worked for me. Thanks guys!

**Comment by Cligor** [comment]
@ShiiRochi @lucaswx2 Both solutions work. Thanks guys!
