### ISSUE TITLE
Can not use showPopperArrow

### ISSUE THREAD

**Issue by johnparkTopQuad** [Hacker0x01/react-datepicker#1952]
**Describe the bug**
I have upgraded to 2.9.6 because I would like to use the showPopperArrow prop to remove the arrow. After upgrading I noticed that it wasnt working when using the prop as shown in the examples on the demo page. The docs state 'Below are examples which also can be edited directly via the editor on the left side and will be rendered on the right.' and the example works on the site but not locally. 

I looked at the jsx on github and saw the conditional rendering the showPopperArrow code uses :
   
   ```
{showPopperArrow && (
         <div className="react-datepicker__triangle" {...arrowProps} />
       )}
```
however in my node_modules folder. When searching for 'triangle' in the code I find

`return e.createElement("div",{className:r},e.createElement("div",ie({className:"react-datepicker__triangle"},a)),n)}`

which doesnt seem to show any conditional rendering and only ever renders the triangle no matter what value the prop is given. 

I believe the issue is either that the showPopperArrow code did not make it into the latest release as intended or the docs are just showing examples for something that isnt released yet. 

**To Reproduce**

Add showPopperArrow={false} prop to DatePicker component in render
Observe that the arrow still shows.
Observe differences in code on github vs code in node_modules.

**Expected behavior**
Arrow should not render when prop is set to false

**Comment by jlmitch** [comment]
When will this be resolved?  This is an issue for our team as well.
