### ISSUE TITLE
Conflict with locale

### ISSUE THREAD

**Issue by liamhubers** [Hacker0x01/react-datepicker#196]
When I use locale in for DatePicker the Moment.js I use elsewhere in my application will return wrong results. Before I click on the DatePicker ```new Moment().week()``` will return 40 but after I opened the DatePicker ```new Moment().week()``` will return 39.

I've narrowed this down to ```week: {
        dow: this.props.weekStart
      },``` in the ```initializeMomentLocale``` function in the Calendar component. For the time being I've disabled this but I hope someone has a solution for this problem or just remove it becaus my code seems to be running fine without it.

**Comment by liamhubers** [comment]
Fixed the issue, had to use moment.isoWeek() instead of moment.week() and now the weeknumbers are consistent before and after using the datepicker.

**Comment by martijnrusschen** [comment]
Thanks for clarifying!
