### ISSUE TITLE
Add a YearPicker (only year)

### ISSUE THREAD

**Issue by aakhan89** [Hacker0x01/react-datepicker#1962]
**It would be perfect to have also a pure year picker ! please have a look screen shot**
I have tried `showYearPicker ` but can not achieve desired result, Please help

![image](https://user-images.githubusercontent.com/38126236/68276753-83378a80-008f-11ea-89fa-65331bd93d84.png)

**Comment by LuisRizo** [comment]
I have had to start searching for other libraries because this feature is not yet implemented. I'd love for this to see the light soon 👍

**Comment by martijnrusschen** [comment]
Added a yearpicker thanks to #2130
