### ISSUE TITLE
Incorrect behavior after update to 2.10.0

### ISSUE THREAD

**Issue by sergeu90** [Hacker0x01/react-datepicker#1969]
**Describe the bug**
import 'react-datepicker/dist/react-datepicker.css'; not included in the build.

**Comment by edgarjs** [comment]
I can confirm that the CSS breaks on 2.10.0.


v2.9.6:
<img width="565" alt="v2 9 6" src="https://user-images.githubusercontent.com/12443/69195100-7cc5fb80-0af0-11ea-80e3-a29b16149f7e.png">

v2.10.0:
<img width="243" alt="v2 10 0" src="https://user-images.githubusercontent.com/12443/69195112-83ed0980-0af0-11ea-8788-87d8f483f8a0.png">

**Comment by focux** [comment]
I'm also experiencing the same issue.

**Comment by samkuehn** [comment]
I was having the same issue - 2.10.1  fixed it for me.
87d22648598430d9f373638bc1d399a58fb08e28

**Comment by martijnrusschen** [comment]
This should be fixed now. Sorry for the inconvenience.

**Comment by Enase** [comment]
it works now, thanks!
