### ISSUE TITLE
Update @types/react-datepicker to the latest version

### ISSUE THREAD

**Issue by dicrescenzoa** [Hacker0x01/react-datepicker#1971]
**Is your feature request related to a problem? Please describe.**
the latest @types/react-datepicker is the 2.9.4
https://www.npmjs.com/package/@types/react-datepicker

**Describe the solution you'd like**
Update the @types definition to the 2.10.0 version

Thank you

**Comment by WtheFourth** [comment]
I added `showQuarterYearPicker` to it today, as we had a need to use that in our React-TypeScript project. I'll go through and add the other missing items in the coming days.

**Comment by dicrescenzoa** [comment]
Thank you very much @WtheFourth

**Comment by dicrescenzoa** [comment]
Since this updated I'll close the issue!! Thank you!

https://www.npmjs.com/package/@types/react-datepicker

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-datepicker/index.d.ts
