### ISSUE TITLE
Year picker only

### ISSUE THREAD

**Issue by tsogi** [Hacker0x01/react-datepicker#1972]
I was checking and it seems the package doesn't provide a pure year picker without months/days etc.

Does this feature has no value or is there any other reason it wasn't implemented so far?

I think it should look roughly like this:
![image](https://user-images.githubusercontent.com/8704592/68881043-d495e880-0725-11ea-85cf-26565476eeb6.png)

**Comment by Versifiction** [comment]
I'm looking exactly for this, I just need the user to pick a year without a month or a day..

**Comment by chupee120** [comment]
Hi, I'm also looking for the same.

**Comment by Daniyal857** [comment]
I also need this feature.

**Comment by martijnrusschen** [comment]
Added a yearpicker thanks to #2130
