### ISSUE TITLE
production build breaking due to react-datepicker/dist/react-datepicker.css:1

### ISSUE THREAD

**Issue by izaakf** [Hacker0x01/react-datepicker#1977]
**Describe the bug**
production build failing due to the following:

```
.react-datepicker-popper[data-placement^="bottom"] .react-datepicker__triangle, .react-datepicker-popper[data-placement^="top"] .react-datepicker__triangle, .react-datepicker__year-read-view--down-arrow, ^  SyntaxError: Unexpected token '.'
```

**To Reproduce**

1. npm build
2. npm run start:prod from https://github.com/cullenjett/react-ssr-boilerplate

**Expected behavior**
build to succeed

**Desktop (please complete the following information):**

- OS: manjaro linux
- Browser chrome/firefox
- Version v2.10.1

**Additional context**

**Comment by sommesh** [comment]
Getting the same error.
Any workaround?
