### ISSUE TITLE
Date picker breaks on Mozilla firefox 70.0.1 macOS

### ISSUE THREAD

**Issue by RonaldFaizaan** [Hacker0x01/react-datepicker#1981]
**Browser:** Mozilla firefox version: 70.0.1
**OS:** macOS 10.13.6 
- Date is not selected
- Calendar incorrect

![react-date-picker-firefox-issue](https://user-images.githubusercontent.com/32439095/70296187-1ef30e00-1796-11ea-8df7-13de5fb3cf06.gif)

**Comment by mustafawm** [comment]
Working fine on my end (same browser/OS). View the console to see what errors are being thrown (if any).

**Comment by RonaldFaizaan** [comment]
I upgraded my Firefox version to 71.0. I can still reproduce this
![image](https://user-images.githubusercontent.com/32439095/70418536-96bc8380-1a89-11ea-8117-f5519506b57b.png)
Also I don't see any console errors but warnings

**Comment by SrikarVasta** [comment]
This could be one of the extensions that you're using. 😄

**Comment by RonaldFaizaan** [comment]
Closing this issue, this was due to an add on that I installed "Change Timezone(Time Shift)"
