### ISSUE TITLE
Is it possible to add a class name to the time picker popper? 

### ISSUE THREAD

**Issue by paufar** [Hacker0x01/react-datepicker#1983]
Is it possible to have the same functionality provided for the date picker (show below) for the time picker popper?
`<DatePicker  calendarClassName="custom-class-name" />`

  tried using the popperClassName attribute on the DatePicker component but that adds the class to the .react-datepicker-popper div. Instead I need to add a class to the .react-datepicker .react-datepicker--time-only div so that I can style the actual panel as this is the DIV that holds all the styles 
![image](https://user-images.githubusercontent.com/36677885/70547306-f477cb00-1b70-11ea-940f-92a2725eb7a5.png)

**Comment by rongzinho** [comment]
Have you tried adding `!important` after the values?
e.g. `.custom-class-name: {
  color: #000 !important;
}`
