### ISSUE TITLE
React crashes when publishing to azure

### ISSUE THREAD

**Issue by MichaMican** [Hacker0x01/react-datepicker#1985]
**Describe the bug**
Even though the package works locally, after you deploy it to azure React crashes completely:
https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]=
When you remove only the DatePicker from the code the website starts working again.

**To Reproduce**

1. Create dotnet react single page app (i used 3.1)
2. Create App service in azure
3. Deploy the app to the App service

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome or Firefox or Microsoft Edge

**Comment by CassieKoelsch** [comment]
I'm having the exact same issue.  It looks like there is a dependency of react-dev-utils that is trying to create a WebSocket over https.
