### ISSUE TITLE
Custom header is not working with month select

### ISSUE THREAD

**Issue by iloveip** [Hacker0x01/react-datepicker#1986]
**Describe the bug**
Custom header is not working with month select. I just copy/pasted the code from the [example](https://reactdatepicker.com/#example-custom-header) with month select only and the app crashes when I open the datepicker.

**To Reproduce**
Please see this [codesandbox](https://codesandbox.io/s/react-datepicker-clear-solved-p2m8y?fontsize=14&hidenavigation=1&theme=dark) and click on Start or End date.

**Expected behavior**
A datepicker would open when I click on it.

**Screenshots**
Here is the screenshot of the error.
<img width="1392" alt="Снимок экрана 2019-12-18 в 1 38 07" src="https://user-images.githubusercontent.com/4873895/71040188-253e9e00-2137-11ea-93ab-1ff1c1832ec8.png">

**Desktop (please complete the following information):**

- macOS Mojave
- Chrome
- Version 79.0.3945.79 

**Additional context**
Datepicker is used with `react-final-form`

**Comment by iloveip** [comment]
This still doesn't work.

**Comment by fatihyildizhan** [comment]
I have the same problem.

`const years = range(1990, getYear(new Date()) + 1, 1);`

@martijnrusschen Do you have any suggestions? Thank you for your time

**Comment by oduvanka** [comment]
@iloveip , @fatihyildizhan 
Because getMonth is not defined. You need to:
import getMonth from "date-fns/getMonth";
or getMonth(date) replace with [date.getMonth()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth)
