### ISSUE TITLE
Word "Time" in component not translated

### ISSUE THREAD

**Issue by KJoWu** [Hacker0x01/react-datepicker#1989]
Can we get the inline text "Time" translated when switching between locales? 

<img width="313" alt="Screen Shot 2019-12-19 at 10 51 57 AM" src="https://user-images.githubusercontent.com/5553403/71197016-ebac8680-224d-11ea-8a48-a22eca27faa8.png">

I noticed the official Doc also runs into this issue.

**Comment by ducanh2110** [comment]
need help for this

**Comment by pisacode** [comment]
You can use `timeCaption` props to change this text

**Comment by KJoWu** [comment]
Works on my end. Thanks!
