### ISSUE TITLE
Milliseconds are not 0 when selecting time before date

### ISSUE THREAD

**Issue by Atema** [Hacker0x01/react-datepicker#1991]
When using the datepicker to select a date and time, the number of milliseconds in the resulting date object is not 0 when the a time is clicked in the picker, but not a date.

Editing an example to log changes to the console:
```
() => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker
      selected={startDate}
      onChange={date => {setStartDate(date); console.log(new Date(date).toISOString())}}
      showTimeSelect
      dateFormat="MMMM d, yyyy h:mm aa"
    />
  );
};
```

logs results like
```
2019-12-20T18:00:00.133Z
```

I'm using Vivaldi 2.9.1705.41 on Windows, with the react-datepicker version on the website.

**Comment by marcoacm** [comment]
@atema did you fix this issue? I am having the same problem.

**Comment by thunguy** [comment]
Here's the workaround
```javascript
import { setMilliseconds } from 'date-fns'

// and then, in your component
onChange={(value) => setFieldValue("start", setMilliseconds(value, 0))}
```
