### ISSUE TITLE
Module not found: Error: Can't resolve 'es-abstract/helpers/callBind'

### ISSUE THREAD

**Issue by eran-or** [Hacker0x01/react-datepicker#1995]
Error:
ERROR in ./node_modules/regexp.prototype.flags/index.js
Module not found: Error: Can't resolve 'es-abstract/helpers/callBind' in 'C:\Repositories\agng-frontend\node_modules\regexp.prototype.flags'
 @ ./node_modules/regexp.prototype.flags/index.js 4:15-54
 @ ./node_modules/deep-equal/index.js
 @ ./node_modules/react-popper/lib/esm/Popper.js
 @ ./node_modules/react-popper/lib/esm/index.js
 @ ./node_modules/react-datepicker/dist/react-datepicker.min.js

this error happens after npm update 

package.json:

"dependencies": {
				"@babel/polyfill": "^7.4.4",
				"axios": "^0.19.0",
				"babel-jest": "^24.8.0",
				"babel-runtime": "^6.26.0",
				"date-fns": "^2.0.0-beta.4",
				"devextreme": "^19.1.5",
				"devextreme-react": "^19.1.5",
				"immer": "^3.2.0",
				"informed": "^2.11.9",
				"jest": "^24.8.0",
				"moment": "^2.24.0",
				"normalize.css": "^8.0.1",
				"normalizr": "^3.4.1",
				"qs": "^6.7.0",
				"react": "^16.11.0",
				"react-color": "^2.17.3",
				"react-datepicker": "^2.8.0",
				"react-dom": "npm:@hot-loader/react-dom@^16.11.0",
				"react-form": "^3.5.7",
				"react-grid-layout": "^0.16.6",
				"react-html-parser": "^2.0.2",
				"react-intl": "^3.1.8",
				"react-loader": "^2.4.5",
				"react-redux": "^7.1.1",
				"react-redux-utils": "^0.1.15",
				"react-router": "^5.1.2",
				"react-router-dom": "^5.1.2",
				"react-select": "^3.0.4",
				"react-table": "^6.10.0",
				"react-test-renderer": "^16.9.0",
				"readable-stream": "^2.0.2",
				"redux": "^4.0.4",
				"redux-api-middleware": "^3.0.1",
				"redux-logger": "^3.0.6",
				"redux-thunk": "^2.3.0",
				"regenerator-runtime": "^0.13.3",
				"reselect": "^4.0.0",
				"semantic-ui-loader": "^2.3.1",
				"store2": "^2.10.0",
				"striptags": "^3.1.1",
				"styled-components": "^4.3.2",
				"uuid": "^3.3.2",
				"yargs": "^14.0.0"
		},
		"devDependencies": {
				"@babel/cli": "^7.5.5",
				"@babel/core": "^7.5.5",
				"@babel/plugin-proposal-class-properties": "^7.5.5",
				"@babel/plugin-proposal-decorators": "^7.4.4",
				"@babel/plugin-proposal-export-namespace-from": "^7.5.2",
				"@babel/plugin-proposal-function-sent": "^7.5.0",
				"@babel/plugin-proposal-json-strings": "^7.2.0",
				"@babel/plugin-proposal-numeric-separator": "^7.2.0",
				"@babel/plugin-proposal-throw-expressions": "^7.2.0",
				"@babel/plugin-syntax-dynamic-import": "^7.2.0",
				"@babel/plugin-syntax-import-meta": "^7.2.0",
				"@babel/plugin-transform-modules-commonjs": "^7.5.0",
				"@babel/plugin-transform-runtime": "^7.5.5",
				"@babel/plugin-transform-spread": "^7.2.2",
				"@babel/preset-env": "^7.5.5",
				"@babel/preset-flow": "^7.0.0",
				"@babel/preset-react": "^7.0.0",
				"@babel/register": "^7.5.5",
				"@babel/runtime": "^7.5.5",
				"@babel/runtime-corejs3": "^7.5.5",
				"@hot-loader/react-dom": "^16.9.0-4.12.11",
				"babel-core": "^6.26.3",
				"babel-eslint": "^10.0.2",
				"babel-loader": "^8.0.6",
				"babel-plugin-react-html-attrs": "^2.1.0",
				"babel-plugin-react-intl": "^4.1.12",
				"babel-plugin-styled-components": "^1.10.6",
				"babel-plugin-transform-async-to-generator": "^6.24.1",
				"babel-plugin-transform-decorators-legacy": "^1.3.5",
				"babel-plugin-transform-object-assign": "^6.22.0",
				"babel-plugin-transform-object-rest-spread": "^6.26.0",
				"babel-plugin-transform-runtime": "^6.23.0",
				"babel-preset-env": "^1.7.0",
				"babel-preset-jest": "^24.6.0",
				"babel-preset-react": "^6.24.1",
				"babel-preset-stage-0": "6.24.1",
				"base-href-webpack-plugin": "^2.0.0",
				"body-parser": "^1.19.0",
				"clean-webpack-plugin": "^3.0.0",
				"copy-webpack-plugin": "^5.0.4",
				"copyfiles": "^2.1.1",
				"cpy-cli": "^2.0.0",
				"css-loader": "^3.2.0",
				"dotenv": "^8.0.0",
				"eslint-plugin-react-hooks": "^2.0.1",
				"express": "^4.17.1",
				"file-loader": "^4.2.0",
				"html-loader": "^0.5.5",
				"html-webpack-plugin": "^3.2.0",
				"imagemin-webpack-plugin": "^2.4.2",
				"mini-css-extract-plugin": "^0.8.0",
				"morgan": "^1.9.1",
				"nodemon": "^1.19.1",
				"npm-run-all": "^4.1.5",
				"path": "^0.12.7",
				"react-hot-loader": "^4.12.11",
				"react-scripts": "^3.1.1",
				"redux-devtools-extension": "^2.13.8",
				"resolve-url-loader": "^3.1.0",
				"style-loader": "^1.0.0",
				"stylus": "^0.54.5",
				"stylus-loader": "^3.0.2",
				"url-loader": "^2.1.0",
				"watch": "^1.0.2",
				"webpack": "^4.39.2",
				"webpack-cli": "^3.3.6",
				"webpack-dev-server": "^3.10.1",
				"webpack-merge": "^4.2.1",
				"webpack-node-externals": "^1.7.2"
		},

**Comment by radh2uk** [comment]
Had a very similar problem today for no apparent reason. So ran npm install es-abstract and working now.
