### ISSUE TITLE
Uncaught ReferenceError: ReactDOM is not defined

### ISSUE THREAD

**Issue by cubbuk** [Hacker0x01/react-datepicker#200]
I am using last version of react v 0.14. I tried to use react-datepicker in my project but I got the following error when I click on date picker.
`Uncaught ReferenceError: ReactDOM is not defined`

Also the datepicker's style does not look proper. What could be done to solve this problem?
Thanks

**Comment by martijnrusschen** [comment]
Yes this is an error introduced in #198. I released a few minor versions to get this working, but it looks like we're still depending on `React.` things in https://github.com/Pomax/react-onclickoutside. We need to figure out what's wrong here, but I have no time left anymore for today. Would be awesome if you had some time today to look into this.

**Comment by martijnrusschen** [comment]
This has been fixed in the latest release.
