### ISSUE TITLE
Range Error when removing colon from Time Input in IE

### ISSUE THREAD

**Issue by TheStantonator** [Hacker0x01/react-datepicker#2012]
In browsers that don't support the input="time" control such as IE and Safari, the user is presented with a textbox instead that they can edit. If they change this textbox to remove the colon, the control will be replaced with a "RangeError: Invalid time value" with no other option that to refresh the page.

1. Go to https://reactdatepicker.com/#example-input-time in internet explorer
2. In the textbox, change the value to remove the colon
3. See error

I propose that instead of throwing an error, the control checks that the inputted value is valid before it tries to convert it

**Comment by Stantonator93** [comment]
I'm not sure if there's already a fix or workaround for this but I thought I'd bring it up

**Comment by info-bit** [comment]
This idea can solve this issue without affecting current behaviour https://github.com/Hacker0x01/react-datepicker/pull/2034!
