### ISSUE TITLE
Time input should allow an optional seconds field

### ISSUE THREAD

**Issue by TheStantonator** [Hacker0x01/react-datepicker#2013]
The time input currently only allows hours and minutes, so I suggest adding the seconds in as an option based on a prop.

**Comment by mgummelt** [comment]
I'll add that this is impossible to workaround even with a custom time input, because the calling code only extracts the hours and minutes, not seconds.

**Comment by chriscareycode** [comment]
Submitted a PR to add support for seconds https://github.com/Hacker0x01/react-datepicker/pull/3214
