### ISSUE TITLE
Moment.js => date-fn lib regression for date completion

### ISSUE THREAD

**Issue by bfeister** [Hacker0x01/react-datepicker#2015]
**Describe the bug**
Upon entering `9/1` for example (or any other date that includes only a single slash, omitting the year), the datepicker yields `9/1/2001` rather than defaulting to the current year. 

The reason for this is that the Date object (which is the `date-fns` library more closely adheres to compared to moment.js) expects year as the first argument in a new date, e.g. `new Date(<year>, <month>, <day>)` and since year is absent from the string `9/1` we need to capture this input style `mm/dd` from users with regex and add the current year. 

I believe moment.js is smarter about handling an input like `9/10` and thus this regressed during the update to remove moment.js.

I can gladly submit a PR for this, but I have some concern that this library is less active, I see alot of newly reported bugs. Please confirm that my efforts would be welcome and considered.

**To Reproduce**

1. View the demo https://codesandbox.io/s/epic-glade-shjg4
2. Do as shown in the GIF below
3. Type `9/1` in the input field
4. Hit ENTER on keyboard

**Expected behavior**
Should yield `9/1/<current year>`.

**Screenshots**
![Screen_Recording_2020-01-15_at_7 44 07_PM](https://user-images.githubusercontent.com/47546998/72488907-a2f5d800-37cf-11ea-976d-dceba92c6e28.gif)

**Comment by wekeepofficial** [comment]
I have the same issue, what did you end up doing? Any other date library you would recommend?

**Comment by sharathprabhal** [comment]
@bfeister I'm having the same issue as well. Did you find a workaround for this?
