### ISSUE TITLE
Pressing ESC closes parent modal form?

### ISSUE THREAD

**Issue by cmtmc** [Hacker0x01/react-datepicker#2019]
Hello,

I put datepicker onto react-responsive-modal - and ESC on opened datepicker closes not only the datepicker but also modal - which is wrong. I do see in docs on keyboard support "Enter & Esc calls preventDefault", and I see it in sources - but modal is closed. Please advise what I'm doing wrong. Thanks!

Test.jsx:

```
import React, { Component } from "react";
import Modal from "react-responsive-modal";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import "./Test.css";

class Test extends Component {
  constructor(props) {
    super(props);

    this.state = { isOpen: false, startDate: new Date(), endDate: new Date() };
  }

  onClick = () => {
    this.setState({ isOpen: !this.state.open });
  };

  onClose = () => {
    this.setState({ isOpen: false });
  };

  changeStartDate = date => {
    this.setState({
      startDate: date
    });
  };

  changeEndDate = date => {
    this.setState({
      endDate: date
    });
  };

  render() {
    return (
      <>
        <button onClick={this.onClick}>Press me</button>
        <Modal
          open={this.state.isOpen}
          onClose={this.onClose}
          classNames={{ modal: "modal-class" }}
          center={true}
          onEscKeyDown={this.onEscKeyDown}
        >
          <input type="text"></input>
          <DatePicker
            selected={this.state.startDate}
            onChange={this.changeStartDate}
          />
          <DatePicker
            selected={this.state.endDate}
            onChange={this.changeEndDate}
          />
        </Modal>
      </>
    );
  }
}

export default Test;

```

Test.css:

```
.modal-class {
  border-radius: 5px;
  padding: 20px;
  width: 600px;
  height: 400px;
}

```

**Comment by ArneMis** [comment]
Does someone found a solution to fix this issue?

**Comment by cmtmc** [comment]
> Does someone found a solution to fix this issue?

As a hack in modal's onClose I do the following check:

  onClose = (event: any) => {
    if (
      event.target.id !== 'idStartDate' &&
      event.target.id !== 'idEndDate'
    ) {
      this.setState({ isOpened: false });
    }
  };

But this is very dirty actually.

**Comment by csaden** [comment]
I think `event. stopPropagation()` needs to be added.

https://github.com/Hacker0x01/react-datepicker/blob/f8fc33c8669dc5b26921a14528154cce948be9dc/src/index.jsx#L645-L647

https://github.com/Hacker0x01/react-datepicker/blob/f8fc33c8669dc5b26921a14528154cce948be9dc/src/index.jsx#L667-L669
