### ISSUE TITLE
Date string in input field is not formatted according to locale prop

### ISSUE THREAD

**Issue by AndrewPrifer** [Hacker0x01/react-datepicker#2021]
**Describe the bug**
I think it would make sense for the format of the date string shown in the input to reflect the provided locale when no format string is provided. Currently it always defaults to `mm/dd/yyyy` in absence of a format string, which I think is incorrect behavior when a locale is set. E.g. for the below screenshot, the format should be `dd-mm-yyyy` with the locale prop set to `nl`. (The locale _is_ properly registered, as you can see in my screenshot, the text in the popup shows 'januari' in Dutch.)

**To Reproduce**

Select a date.

**Expected behavior**
The date picker shows the date string in the format provided by the supplied `date-fns` object.

**Screenshots**
<img width="299" alt="Screen Shot 2020-01-19 at 23 29 46" src="https://user-images.githubusercontent.com/2991360/72689625-96e18180-3b13-11ea-8c91-202b47b39572.png">

Update: I think this issue could be solved if react-datepicker simply used `P` as the default format string instead of `mm/dd/yyyy` . This would still display the American format by default, except when a locale is provided.

**Comment by andrewpeterprifer** [comment]
Found a tolerably awkward workaround for in the meantime, in case anyone else is looking for a solution:

```js
import { enUS, nl } from 'date-fns/locale';

const locales = {
  'en-US': enUS,
  'nl-NL': nl,
};

for (const [key, value] of Object.entries(locales)) {
  registerLocale(key, value);
}

// ...

<DatePicker
  locale={locale}
  dateFormat={locales[locale].formatLong?.date({ width: 'short' })}
/>
```

**Comment by anadutova** [comment]
@AndrewPrifer you can use `dateFormat="P"` prop to get the same effect.
Related docs:
https://date-fns.org/v2.9.0/docs/format

Nonetheless, I agree: no reason it should default to the american format _at all_.

**Comment by AndrewPrifer** [comment]
@anadutova thank you! That makes things much simpler. Then I think the obvious solution would be for react-datepicker to simply use "P" as the default format string and not the American one. It wouldn't even be much of a breaking change since date-fns defaults to `en-US` so people who don't specify a locale wouldn't even notice it, and those who do probably want to format their date in their provided locale anyway.
