### ISSUE TITLE
Calendar displays the dates in US format, but with EU column headings

### ISSUE THREAD

**Issue by jenskanis** [Hacker0x01/react-datepicker#203]
From a customer on our platform:

> Just wanted to let you know that your calendar
 displays the dates in US format, but with EU column headings. Ex: Sun, Oct 11th shows as Mon, Oct 11th. See screenshot. 
> <img width="215" alt="screen shot 2015-10-11 at 4 28 22 pm" src="https://cloud.githubusercontent.com/assets/1345437/10424292/680d9bb4-70ce-11e5-94dd-f2b5fc434011.png">

**Comment by rafeememon** [comment]
Probably the same issue as #160

**Comment by rafeememon** [comment]
Most likely fixed by #277
