### ISSUE TITLE
Is there any way to set custom initial time while using showTimeInput ?

### ISSUE THREAD

**Issue by hiteshr882** [Hacker0x01/react-datepicker#2030]
I am trying to set a custom initial time in the highlighted area. 
<img width="397" alt="t____Workflow____Flowster" src="https://user-images.githubusercontent.com/19893229/73199178-5a88d380-415a-11ea-860d-750629bb675b.png">

**Comment by imkane** [comment]
Yes, we need to know how to do this too :+1:

**Comment by cchoiniere** [comment]
You have to create a custom string using todays date and then add your default time in. Use that string to create a new Date(). Would create the new Date() then remove the current time and replace it with your custom time. You'd have to write a function to handle the formatting.

Basically you end up with something like this `const defaultTime = new Date('Jan 01 2020 09:00:00')`
