### ISSUE TITLE
Can we have a week picker ?

### ISSUE THREAD

**Issue by goxr3plus** [Hacker0x01/react-datepicker#2033]
I see month picker , year picker but no week picker :) .

**Comment by goxr3plus** [comment]
@martijnrusschen Hey boss , can it be done boss ? Please boss ?

**Comment by pepijnolivier** [comment]
I'd also need this

**Comment by AlexeyCanyon** [comment]
I'd also need this + 1

**Comment by khalidk7** [comment]
Yes I'm also looking for an option to "select an entire week" (as opposed to selecting individual day), similar to an implementation like this whereby the entire week (in the normal monthly view) is highlighted:

https://react-day-picker.js.org/examples/selected-week/

Is there a way to implement this using the current latest react-datepicker or does this require a new feature enhancement in the code base?
 
Thanks in advance!

**Comment by TiesWestendorp** [comment]
@martijnrusschen This would be very nice to have! :)

**Comment by TiesWestendorp** [comment]
I have a PR in the works that fixes this issue. :)

**Comment by johnnyxbell** [comment]
Also needing this...

**Comment by berolomsa** [comment]
would be nice to have weekpicker too :)

**Comment by arun-Kumar-N** [comment]
Yes we need week picker :(

**Comment by thomasio101** [comment]
I second this, I'd really appreciate having a week picker!

**Comment by stebogit** [comment]
Yep, would work for me as well

**Comment by Hitunen** [comment]
Ditto

**Comment by calag4n** [comment]
It would be great !

**Comment by targhs** [comment]
I need this too

**Comment by andrescevp** [comment]
I can not wait to get that PR merged (https://github.com/Hacker0x01/react-datepicker/pull/4288)

**Comment by martijnrusschen** [comment]
Fixed by https://github.com/Hacker0x01/react-datepicker/pull/4288
