### ISSUE TITLE
dates typed in the 'YYYY-MM-DD' format result in a subtraction of 1 day

### ISSUE THREAD

**Issue by mbungeroth** [Hacker0x01/react-datepicker#2035]
**Describe the bug**
If you type 1970-07-26 into the datepicker, you will end up with July 25th, 1970. This is most likely caused by the date-fns "parse" function that is imported and used, but this renders react-datepicker 100% unusable in any sort of production setting where dates matter, so you may want to replace that parser with your own rather than rely on them to fix it in a timely manner.

**To Reproduce**
1. In the text box, type 1970-07-26
2. Hit return/enter
3. Look at your unfortunate result

**Expected behavior**
The date you enter to be the date you get.

**Desktop (please complete the following information):**

- OS: Mac OS X catalina
- Browser: Brave, Firefox, Chrome, Safari

**Additional context**
This **only** occurs when typing dates in the YYYY-MM-DD format and with hyphens as your delimiter. doing YYYY/MM/DD will not replicate this. Nor, oddly, will YY-MM-DD, nor MM-DD-YYYY, nor anything similar.

**Comment by ruanopme** [comment]
Same when typing dates in DD/MM/YYYY
