### ISSUE TITLE
Text Field - change style

### ISSUE THREAD

**Issue by FilipMasar** [Hacker0x01/react-datepicker#2036]
Hi, I would like to change text field css. Could this be somehow simply done ?
Concretely change width and font-size. Thanks

**Comment by chrisandrewca** [comment]
Hi Filip, see these threads.

https://stackoverflow.com/questions/51710700/react-datepicker-input-width-will-not-adjust-to-100
https://stackoverflow.com/questions/50391206/custom-input-field-on-datepicker

**Comment by FilipMasar** [comment]
Thanks
