### ISSUE TITLE
Use of 'yyyy' instead of 'YYYY' breaking the component

### ISSUE THREAD

**Issue by vitorboccio** [Hacker0x01/react-datepicker#2037]
**Describe the bug**
As soon as a date is set to the component it breaks, throwning the error 

> Use of 'yyyy' instead of 'YYYY' for formatting years

**To Reproduce**
```
this.state = {
    startDate: new Date(),
}
<Datepicker
              id="input-start-date"
              selected={startDate}
              onChange={e => this.handleStartDate(e)}
              dateFormat="d MMM, YYYY h:mm aa"
/>

```

**Additional context**
I've seen people were having a similar issue, but as I've updated it and the problem still happening to me I decided to open this issue.

"react-datepicker": "^2.11.0",
"date-fns": "^2.9.0",

**Comment by vitorboccio** [comment]
I've downgraded to the version 2.3 and It's working. Reopening in case anyone has the same problem and find a solution for the problem.

**Comment by gauthamdaze** [comment]
> I've downgraded to the version 2.3 and It's working. Reopening in case anyone has the same problem and find a solution for the problem.

how did intergrate the css for react datepicker??
