### ISSUE TITLE
Date format is different than value submitted

### ISSUE THREAD

**Issue by Bluefitdev** [Hacker0x01/react-datepicker#2038]
my current date format is following mysql format

```

    handleDateChange = date => {
        this.setState({
            due: date,
        });
    };

        <DatePicker
            selected={this.state.due}
            onChange={this.handleDateChange}
            showTimeSelect
            timeFormat="HH:mm"
            timeIntervals={15}
            timeCaption="time"
            dateFormat="yyyy-MM-dd HH:mm:ss"
        />
```

the value that is sent through the post request is: 2020-02-05T06:15:30.038Z

However the value showing on the input is correctly showing as 2020-02-05 17:30:00

What should I do to get the correct format as value in my state?

Thanks

**Comment by EduardoZepeda** [comment]
I think I'm having the same problem
