### ISSUE TITLE
error on 0.14.2

### ISSUE THREAD

**Issue by thiagoc7** [Hacker0x01/react-datepicker#204]
Hi, I'm having this error:

<img width="1265" alt="screen shot 2015-10-12 at 11 04 00 am" src="https://cloud.githubusercontent.com/assets/6671184/10429725/0849b354-70d1-11e5-9acb-4acecd0622fe.png">

Thanks!

**Comment by mwanji** [comment]
I have a similar error since moving to React 0.14

**Comment by martijnrusschen** [comment]
Yup, looks like the dependencies aren't ready for 0.14 yet. I need to figure out what's going wrong but not sure when I have time to investigate this.

**Comment by SpaceMacGyver** [comment]
The issue appears to be present on the examples page as well:

![image](https://cloud.githubusercontent.com/assets/2105094/10454617/9090face-717b-11e5-8270-a7e00b806432.png)

Currently, the examples do not work (clicking on date inputs does not cause the datepicker component to appear).

**Comment by martijnrusschen** [comment]
Yes this is an issue with the latests version of the datepicker. You can use version 0.13.0.

**Comment by trueter** [comment]
Does 0.13.0 work with React 0.14 though?

**Comment by thiagoc7** [comment]
you may have same issues with webpack when using two versions of react...
https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375

2015-10-16 14:59 GMT-03:00 Torsten Rü <notifications@github.com>:

**Comment by martijnrusschen** [comment]
That might be it! I'll try that in our example app.

**Comment by KeitIG** [comment]
hi ! 

Any news on this ?

**Comment by KeitIG** [comment]
Looks like the classic problem with react 0.14, refs node are now only accessible by `this.refs.reference` and not `ReactDOM.findDOMNode(this.refs.reference)`.

Are you open to a PR @martijnrusschen or do you think you can fix that soon ?

**Comment by martijnrusschen** [comment]
Please submit a PR

**Comment by martijnrusschen** [comment]
Version 0.14.5 should fix this issue.

**Comment by KeitIG** [comment]
Working well. Thanks !
