### ISSUE TITLE
ERROR in ./~/react-datepicker/dist/react-datepicker.css Module build failed: SyntaxError: Unexpected token (1:0

### ISSUE THREAD

**Issue by gauthamdaze** [Hacker0x01/react-datepicker#2041]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sommesh** [comment]
Any solutions?

**Comment by SivaGanesh56** [comment]
+1

**Comment by rufatZZ** [comment]
Any solution? Still happens
