### ISSUE TITLE
Module Missing: Module not found: Can't resolve 'highlight.js/lib/highlight' 

### ISSUE THREAD

**Issue by ShraddhaGeek** [Hacker0x01/react-datepicker#2042]
I cloned the repo from here https://github.com/Hacker0x01/react-datepicker

Follow the instruction for the setup [Link](https://github.com/Hacker0x01/react-datepicker/blob/master/CONTRIBUTING.md)

Getting error **Module not found: Can't resolve 'highlight.js/lib/highlight'**

**Comment by oscarcarlstrom** [comment]
I have the same problem
