### ISSUE TITLE
Property 'customTimeInput' does not exist on type ReactDatePickerProps

### ISSUE THREAD

**Issue by Aashreetha** [Hacker0x01/react-datepicker#2046]
I am trying to use the customTimeInput prop added in (#2034 ) in my react app, but I am seeing this error.

`Property 'customTimeInput' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactDatePicker> & Readonly<ReactDatePickerProps> & Readonly<{ children?: ReactNode; }>'. error. `

I am using typescript version : 3.5.3
Is there anything someone can help ?

**Comment by g-akshay** [comment]
It seems the custom time component is not taken into consideration as well... behaving as if its a redundant prop.

**Comment by g-akshay** [comment]
Bumping up the version to `2.12.1` fixed the problem.

**Comment by Aashreetha** [comment]
Seems like version upgrade to `2.12.1` didn't solve my problem. Updating the @types/react-datepicker is still at 2.11.0 and it doesn't have the `customTimeInput` prop

**Comment by pdziwoki** [comment]
Any fix incoming?

**Comment by MartinYounghoonKim** [comment]
I have same issue.
