### ISSUE TITLE
Input is parsed by mm/dd/yyyy format regardless of locale

### ISSUE THREAD

**Issue by anadutova** [Hacker0x01/react-datepicker#2050]
**Describe the bug**
An ambiguous date input (e.g. `10.02.1996.`) is parsed by mm/dd/yyyy (or American) format regardless of locale or dateFormat. More specifically, when locale is set to `de` or `en-GB` and dateFormat to `P`.

**To Reproduce**

1. Set `locale="de"`
2. Set `dateFormat="P"`
3. Type in the date `10.02.1996.`

**Expected behavior**
The popper should show February 10th as selected.

**Screenshots**
The screenshot illustrates that the locale was correctly set to German, but the input is parsed as it if were month-day-year.
![datepicker-fail](https://user-images.githubusercontent.com/9092664/74257860-b6746000-4cf5-11ea-9381-28d30720eb49.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 2.11.0

**Additional context**

**Comment by enolive** [comment]
have you registered the locale?
had the same problem (using 2.13.0, though), before I read the docs a little bit better and added following line:

```typescript
import {registerLocale} from 'react-datepicker';
import {de} from 'date-fns/locale';

registerLocale('de', de);
```

**Comment by anadutova** [comment]
@enolive I believe I have. If I hadn't registered it, could it display the current month as "Oktober", with a K?

**Comment by capa89k** [comment]
I had the same issue, not sure this is the default way or we are missing something.

Anyway as a "workaround" you can define the date format using the dateFormat prop. Of course this is static, but you could define your own string format in your locale file just like any other translation. The use the proper format string to make it "dynamic".

`<DatePicker
	customInput={<CustomDatePicker disabled={this.props.isFetching} />}
	selected={this.props.date.toDate()}
	onChange={this.handleDayChange}
	todayButton={"Today"}
	disabled={this.props.isFetching}
	minDate={range.minDate}
	maxDate={range.maxDate}
	locale={this.props.locale}
	dateFormat="dd/MM/yyyy"
	fixedHeight={true}
	showDisabledMonthNavigation={true}
	className="form-control"
/>`

You can then use `dateFormat={i18n.t("date_format")}` or something like that.
