### ISSUE TITLE
Can you prevent the calendar from opening?

### ISSUE THREAD

**Issue by ahiyalala** [Hacker0x01/react-datepicker#2052]
Is there an option to prevent the calendar from popping up? The component is great with all its cool options but we encountered a use case that we just want to have the date input as a text field.

**Comment by mikeyyyzhao** [comment]
there's a prop you acn pass in disabled

```
<DatePicker
      selected={startDate}
      onChange={date => setStartDate(date)}
      disabledKeyboardNavigation
      placeholderText="This has disabled keyboard navigation"
    />
```

**Comment by srezarn** [comment]
hi @ahiyalala 
set  preventOpenOnFocus  to true

  <DatePicker 
                selected={this.state.startDate}
                onChange={this.setStartDate}               
                preventOpenOnFocus = {true}
                placeholderText="This has disabled keyboard navigation"
                dateFormat="yyyy/MM/dd"
            />
