### ISSUE TITLE
Include dates with a large array of dates results in 1FPS on scrolling and opening

### ISSUE THREAD

**Issue by Busteren** [Hacker0x01/react-datepicker#2053]
**Describe the bug**
When the prop `includeDates` has a large array of dates (typically say 1500) the datepicker takes a lot of time to compute on updates. On opening, it normally takes 0.5s to 1s to open and when scrolling it is very laggy. Typically between 1-4 FPS on these actions. Is there a way to optimise this (cache), so it doesn't have to redo the calculations every time the component updates?

**To Reproduce**
Create a date-picker with more than 1500 dates in the `includeDates` prop.

**Expected behaviour**
Fast and smooth opening/closing and scrolling with the component.

**Screenshots**
Performance tab in google chrome on opening the date-picker:
<img width="870" alt="Screenshot 2020-02-13 at 13 28 35" src="https://user-images.githubusercontent.com/15114362/74441020-03c40f00-4e67-11ea-92bf-a97bcd57e189.png">
<img width="160" alt="Screenshot 2020-02-13 at 13 28 43" src="https://user-images.githubusercontent.com/15114362/74441026-06266900-4e67-11ea-9862-01509fdd8349.png">
<img width="698" alt="Screenshot 2020-02-13 at 13 31 23" src="https://user-images.githubusercontent.com/15114362/74441031-0888c300-4e67-11ea-86a8-318e5819d785.png">

**Desktop:**

- OS: [MacOS Mohave]
- Browser [chrome, firefox]
- Version [chrome 80.0.3987.87 (Official Build) (64-bit), firefox 72.0.2 (64-bit)]

Is it possible to cache the output of the `includeDates`? The array never changes, so I don't necessarily see why it should do a lot of computation to check the array each time (maybe memorize the output if the same input)?

**Edit**
This also happens when hovering over any of the dates or any interaction that I have encountered.

**Edit 2**
Was `includeDates` which caused this, not `includeTimes` as first mentioned in issue

**Edit 3**
With an array of 1500 dates, when opening the date picker, for each date the function isDayDisabled is called 45 times. Finding a way of avoiding to call isDayDisabled so many times should improve rendering times.

**Comment by jalovatt** [comment]
For what it's worth, I'm having the same issue when passing `includeTimes` an array of just under 300 items.

**Comment by Busteren** [comment]
I have pinned down the issue somewhat. The lookup to check if a date is in include times is quite expensive (not sure if this is possible to avoid unless using some sort of dictionary or anything with a O(1) lookup). But one of the main culprits is that that the this is done 4-5 times in a render for each day and on hover and mouseover in `day.jsx`. Working on a solution to either memoize the result or use the `getDerivedStateFromProps` lifecycle (normally would use memoize, but might be worth using for performance). 

300 items in `includeTimes` does sound like a lot though? Could you use `injectTimes` or Specific Time Range to do something smart?

**Comment by jalovatt** [comment]
> 300 items in `includeTimes` does sound like a lot though? Could you use `injectTimes` or Specific Time Range to do something smart?

The data I'm working with is taken every five minutes, so 288 per day, and any given day will have maybe a dozen missing entries. I'm starting from an array of the entries that are available, but I'll look at adding the inverse to our API so I can use `excludeTimes` instead.

**Comment by Busteren** [comment]
Ah I see, so using `timeIntervals` and then `excludeTimes` to remove the ones not needed?

**Comment by jalovatt** [comment]
Exactly.

I've just tried it and the performance is unchanged, which makes sense as I can imagine `includeTimes` and `excludeTimes` are very similar internally if not using the same code.

**Comment by Busteren** [comment]
Added memoization, still performance issues. For some reason, the different components are rendered multiple times. The Month component is rendered 4 times on opening of the Calendar, hence a 4 * 30 + rendering of Day. Seems very buggy, so might look into an alternative.

**Comment by martenwallewein** [comment]
I experienced the same problem for excludeDates with around 3000 items. Any progress here?

**Comment by Busteren** [comment]
Due to unforeseen circumstances, I haven't had time to work on it. Still, something that would be nice to fix. The memorization does help a bit, but still issues with rendering. So not much progress tbh.
