### ISSUE TITLE
Open + Close programmatically

### ISSUE THREAD

**Issue by mnsr** [Hacker0x01/react-datepicker#2055]
For my use case, this seems perfect, but i can't seem to find a way to open and close the calendar programmatically.

I'm using range for a pick-up and drop-off scenario with time. onSelect (whether it's date or time), i'd like it to close the pick-up calendar, and open the drop-off calendar.

Is this possible?

**Comment by mikeyyyzhao** [comment]
this might be a hack but it's working for me. I added a ref to the component and when I need to open/close the popper, I call this.refs.datePicker.state.open = false;

**Comment by wwladislavv** [comment]
I've used customInput prop with ref, worked like a charm

**Comment by mnsr** [comment]
I actually figured it out. I'll post a quick overview of what i've used in case someone needs this in the future.

```javascript
  const startRef = useRef<DatePicker>();
  const endRef = useRef<DatePicker>();

  const onStartChange = () => {
    // used the following line as i'm using time as well, but it's not obvious that 
    // you need to click it to close the pickup calendar
    startRef.current.setOpen(false); 
    endRef.current.setOpen(true);    
  }

  return (
    <>
      <DatePicker ref={startRef} onChange={onStartChange} ... />
      <DatePicker ref={endRef} ... />
    </>
  );
```

**Comment by sanjarcode** [comment]
This should be added in the examples, it's a really important use case.

**Comment by friederjanmoerman** [comment]
You can use this example to build it more customizable:
```
() => {
  const [startDate, setStartDate] = useState(new Date());
  const [isOpen, setIsOpen] = useState(false);
  const handleChange = (e) => {
    setIsOpen(!isOpen);
    setStartDate(e);
  };
  const handleClick = (e) => {
    e.preventDefault();
    setIsOpen(!isOpen);
  };
  return (
    <>
      <button className="example-custom-input" onClick={handleClick}>
        {format(startDate, "dd-MM-yyyy")}
      </button>
      {isOpen && (
        <DatePicker selected={startDate} onChange={handleChange} inline />
      )}
    </>
  );
};
```

**Comment by Junaid300** [comment]
How would i know, is calendar open or close previously using ref ? 
If i do `  const isOpen = datePickerRef.current.state.open;` it says `Property 'open' does not exist on type 'Readonly<{}> with typescript`

**Comment by friederjanmoerman** [comment]
> How would i know, is calendar open or close previously using ref ? If i do ` const isOpen = datePickerRef.current.state.open;` it says `Property 'open' does not exist on type 'Readonly<{}> with typescript`

In my example above, set the state of setIsOpen to false or true as in this example:
`const handleClick = (e) => {
    e.preventDefault();
    setIsOpen(!isOpen);
  };`
  
  If unfamiliar with handling states: https://react.dev/learn/state-a-components-memory

**Comment by friederjanmoerman** [comment]
> How would i know, is calendar open or close previously using ref ? If i do ` const isOpen = datePickerRef.current.state.open;` it says `Property 'open' does not exist on type 'Readonly<{}> with typescript`

setOpen seems to be the state in that example which is a boolean, true or false. You can check out more about states here: https://react.dev/learn/state-a-components-memory

**Comment by Junaid300** [comment]
> setOpen seems to be the state in that example which is a boolean, true or false. You can check out more about states here: https://react.dev/learn/state-a-components-memory

I agree setOpen seems to be  state although i am asking about `ref object`. I tried to access ref object of `read-datepicker` we have state object inside `ref.current` when i try to access any element of the `state object inside ref.current` it says  `Property 'open' does not exist on type 'Readonly<{}> with typescript` .

**Comment by zeevnoiman** [comment]
> How would i know, is calendar open or close previously using ref ? If i do ` const isOpen = datePickerRef.current.state.open;` it says `Property 'open' does not exist on type 'Readonly<{}> with typescript`

You can use `const isOpen = datePickerRef.current.isCalendarOpen();`
