### ISSUE TITLE
wrong initial time with timezone.

### ISSUE THREAD

**Issue by erikkubica** [Hacker0x01/react-datepicker#2057]
**Describe the bug**
If I set the input DateTime to 2020-02-17T15:32:00+01:00 which means the DatePicker should show 16:32 as the time in the input, instead it show 15:32.

Also when I manually select 16:32 it shows 16:32 but it returns 16:32+01:00 instead of 15:32+01:00

**To Reproduce**
const date = Date("2020-02-17T15:32:00+01:00")
<DatePicker
    selected={date}
    onChange={date => {
        console.log(date);
    }}
    showTimeSelect
    timeFormat="HH:mm"
    timeIntervals={30}
    dateFormat="dd. MMMM yyyy, HH:mm"
    locale={"sk"}
/>

Now the input will show 15:32 (not 16:32), if you change the time to for example 17:30 it will return 17:30+01:00 instead of 16:30+01:00 (which is for some weird reason ok because PHP modifies the date to 16:30+01:00), so technically the problem is that display time that is displayed on the initial render is wrong.

**Comment by MaxChu23** [comment]
I'm having the same issue.
Also there's nothing about timezones in the official documentation and in the repository.

**Comment by ACoolmanBigHealth** [comment]
Hm. I also am having the same issue
