### ISSUE TITLE
Add tabIndex to the list of properties

### ISSUE THREAD

**Issue by mydudechris** [Hacker0x01/react-datepicker#206]
Would it be possible to add a tabindex attr to the list of configurable props?

**Comment by mydudechris** [comment]
I tried adding tabIndex to the list of props in the react-datepicker.jsx input render call to no avail. Couldn't get the property to show up anywhere.

**Comment by martijnrusschen** [comment]
I'll take a look next week. Let me know if you have found anything in the mean time.

**Comment by martijnrusschen** [comment]
So, to be clear. You want a tabIndex value on the input field?
