### ISSUE TITLE
Any possibility to use clean internationalization without importing date-fns locales?

### ISSUE THREAD

**Issue by kevinlandsberg** [Hacker0x01/react-datepicker#2074]
I am using react-datepicker inside my project. I have no problems with date-fns is a dependency by react-datepicker. But without setting the locale attribute for the datepicker component, i cannot have a clear internationalization of the datepicker, e.g. i cannot set the starting day of the week programatically without delivering a locale. Is there any possibility to use clean internationalization without date-fns? I would really be happy about e.g. setting the start of the week programatically or tofetch locales from an API or something...
We use luxon for date stuff thats why we do not need to import another library for dates again.

**Comment by martintyler** [comment]
Same here.. I am just upgrading from an old moment based version of react-datepicker and trying to get my weeks to start on a Monday again.

Also migrating to Luxon, after trying date-fns, which I liked, but need more control over UTC and Local times
