### ISSUE TITLE
Make date picker full screen in mobile or small screen resolution

### ISSUE THREAD

**Issue by topex-psy** [Hacker0x01/react-datepicker#2075]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when in mobile/small screen, date picker is truncated and not correctly displayed.

**Describe the solution you'd like**
Make date picker fill the screen.

**Describe alternatives you've considered**
Or show popup dialog to select date.

**Additional context**
![WhatsApp Image 2020-02-24 at 9 40 23 AM](https://user-images.githubusercontent.com/14989865/75508525-0bfb7d00-5a17-11ea-8b4d-10eccf19fadc.jpeg)

**Comment by RaudByorn** [comment]
All you need is "withPortal" attribute
<DatePicker
      selected={startDate}
      onChange={date => setStartDate(date)}
      withPortal
    />

**Comment by maurusrv** [comment]
Hi @RaudByorn, i've tried your solution and it works on ios devices. but it doesn't seem to work in android?

**Comment by RaudByorn** [comment]
Hi @maurusrv, I've checked it just now on Android and it works fine. Try it here https://reactdatepicker.com/ on example with "withPortal" attribute.

**Comment by maurusrv** [comment]
Yes. my mistake. it is indeed working. thanks for the reply anyway @RaudByorn!

**Comment by softshape** [comment]
Portal is not helping much on devices. It's not 100% fullscreen, and it won't disable text input so a keyboard covers the calendar.  


![image](https://user-images.githubusercontent.com/107505/87537993-1e2c3e00-c6ce-11ea-9cc0-0bbf13429f51.png)

**Comment by RaudByorn** [comment]
@softshape here is solution #942
