### ISSUE TITLE
Multiple instances of React

### ISSUE THREAD

**Issue by tquetano-r7** [Hacker0x01/react-datepicker#208]
I tried loading the latest version and I am getting an error along these lines:

Warning: React can't find the root component node for data-reactid value `.1.2`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.

I am still using React 0.13.3, so not sure if that contrubites, however its not just me ... that error was taken from the devtools when loading your own demo page. I've tried several versions of react-datepicker, and the most recent version where I do not get this error is 0.13.0.

**Comment by martijnrusschen** [comment]
Yes this is an issue with the latests version of the datepicker. You can use version 0.13.0.

**Comment by martijnrusschen** [comment]
Version 0.14.5 should fix this issue.
