### ISSUE TITLE
date picker does not close

### ISSUE THREAD

**Issue by Utsav170** [Hacker0x01/react-datepicker#2084]
**Describe the bug**
The datepicker does not close if clicked on other input fields

**To Reproduce**

Steps:
1) Click on datepicker.
2) After the datepicker is opened, click inside other fields like  textarea or inputs.

**Expected behavior**
The datepicker should close

**Actual Result**
The datepicker does not close

**Screenshots**
After clicking on text area the cursor is blinking but the datepicker is not closed.
![image](https://user-images.githubusercontent.com/38745363/76510563-ef7d2d00-6479-11ea-87da-f61e7f6c860a.png)

**Desktop (please complete the following information):**

- Browser [e.g. internet explorer]
- Version [e.g. IE11]

**Comment by ivan133** [comment]
For me, it happens because I set focus 

>  setTimeout(() => this._datepickerRef.focus());

When I removed it for Ie it works ok
