### ISSUE TITLE
Scroll months on touch devices

### ISSUE THREAD

**Issue by evgenygil** [Hacker0x01/react-datepicker#2087]
Hi, can I realize such functionality with datepicker, scroll months by swipe on phone?
Like this
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23053513/76858307-313a1900-6868-11ea-8e4c-9ca7690c9d3b.gif)
Or, may be from left to right (not from top to bottom)

**Comment by deadly8** [comment]
is it possible to do that with react datepicker or no?

**Comment by MatanB-Inmanage** [comment]
I have the same issue
