### ISSUE TITLE
year/month dropdown crashes

### ISSUE THREAD

**Issue by jwallet** [Hacker0x01/react-datepicker#2088]
**Describe the bug**
https://reactdatepicker.com/#example-year-dropdown
https://reactdatepicker.com/#example-month-dropdown

```
Error: Minified React error #290; visit https://reactjs.org/docs/error-decoder.html?invariant=290&args[]=options for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```

**To Reproduce**

1. open dropdown

**Desktop (please complete the following information):**

- OS: windows
- Browser firefox 74

**Comment by martijnrusschen** [comment]
This should be fixed with #2132 merged. We will release a new version shortly.
