### ISSUE TITLE
onMonthChange not firing

### ISSUE THREAD

**Issue by eugenesaur** [Hacker0x01/react-datepicker#2091]
**Describe the bug**
onMonthChange not firing by clicking on "day--outside-month" 

**To Reproduce**

1. Configure inline datepicker ( in my case: monthsShown={3} )
2. Click on the outside month date
3. Month has changed, but "onMonthChange" did not fired

**Expected behavior**
Main: fire onMonthChange

Other: 
1st case: Don't change month at all. 
2nd case: want to show the dates, but with prevented onClick event (not just hide)
3rd case: onOutsideDayClick event

4th case: Add hooks! =)

**Desktop (please complete the following information):**

- OS: macOs Catalina 10.15.3
- Browser: chrome
- Version: 80.0.3987.149

**Comment by eugenesaur** [comment]
One of the solutions (_prevent onClick_):

```
.react-datepicker__day--outside-month {
    pointer-events: none;
}
```

**Comment by DJ-Eckam** [comment]
This is a real bug. When you change the month using month controls, the 'onMonthChange' event fires.
But when you cause the month to advance by either clicking on a date outside the main displayed month (like March 1 when you're looking at February), or by using an arrow key to navigate to the next or previous date, the event does not fire. Seems like it should. I would like to know when the displayed month changes so I can fetch new data for it.
