### ISSUE TITLE
Error: Minified React error #290 in docs site

### ISSUE THREAD

**Issue by syncatallah** [Hacker0x01/react-datepicker#2093]
**Describe the bug**
It's in the docs site examples of `Month dropdown` and `Year dropdown`. Trying to select month or year respectively raises an error: 
<pre>Error: Minified React error #290; visit https://reactjs.org/docs/error-decoder.html?invariant=290&amp;args[]=options for the full message or use the non-minified dev environment for full errors and additional helpful warnings. </pre>

**To Reproduce**

1. Go to [reactdatepicker.com/](https://reactdatepicker.com/)
2. In Example [Month dropdown](https://reactdatepicker.com/#example-year-dropdown) or [Year dropdown](https://reactdatepicker.com/#example-month-dropdown)
3. Try to select month or year.
4. See error wrapped in `pre` tag with `Error: Minified React error #290; visit https://reactjs.org/docs/error-decoder.html?invariant=290&amp;args[]=options for the full message or use the non-minified dev environment for full errors and additional helpful warnings`

**Expected behavior**
I can select normally in the demo, but I can't because of this error.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 19.10 (Eoan Ermine) 
- Chrome 
- Version 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
I don't think this happens in the package itself because I tried it in a current working example. and it works, just in the site docs from the live preview.

I am investigating the issue and see if I'm able to help. but, just in case, here is a non critical bug.

**Comment by martijnrusschen** [comment]
This should be fixed with #2132 merged. We will release a new version shortly.
