### ISSUE TITLE
Date reset when Time is select

### ISSUE THREAD

**Issue by dboutin84** [Hacker0x01/react-datepicker#2102]
When i select date and after select time, the date reset a current day

"react": "^15.4.2",
"react-datepicker": "1.6.x",

<DatePicker
     className="form-control"
     onChange={this.handleUpdateDatepickerStart}
     showTimeSelect
     timeFormat="HH:mm"
     timeIntervals={30}
     timeCaption="time"
     dateFormat="MMMM d, yyyy h:mm"
     value={pubDateStart}
/>

![Screenshot from 2020-03-26 15-11-55](https://user-images.githubusercontent.com/42750910/77687242-7d760f00-6f74-11ea-9eed-3820f034654f.png)
![Screenshot from 2020-03-26 15-12-32](https://user-images.githubusercontent.com/42750910/77687264-823ac300-6f74-11ea-9783-c6dbbe1b6af3.png)

**Comment by aethelz** [comment]
Same issue, time change in showTimeSelect+showTimeSelectOnly field resets date to today (Also confirmed in version 3.1.3)

**Comment by aethelz** [comment]
I made a minimal reproducible case: https://stackblitz.com/edit/react-7u9dx3
Everything breaks if you erase last digit
![Peek 2020-08-10 14-59](https://user-images.githubusercontent.com/10677343/89780461-297e5800-db1a-11ea-9064-82edd5c4c378.gif)

**Comment by aure-staffbase** [comment]
Similar to https://github.com/Hacker0x01/react-datepicker/issues/2319

Has anyone found a fix/solution/workaround?

**Comment by aure-staffbase** [comment]
As a partial workaround, for cases where a dropdown is also available, https://github.com/Hacker0x01/react-datepicker/issues/942 provides information on how to block users to manually enter text.

**Comment by januarsmad** [comment]
> Similar to #2319
> 
> Has anyone found a fix/solution/workaround?

passing the props "selected" will retain the value after use select the date
```
<DatePicker
  selected={ new Date(value || '')  }
  placeholderText='01/01/2022 08:30'
  autoComplete='off'
  showTimeSelect={ showTimeSelect }
  timeFormat='HH:mm'
  value={ value }
  onChange={ handleChange }
  className={ inputClassName }
/>
```
