### ISSUE TITLE
customInput does not support functional components

### ISSUE THREAD

**Issue by rachelruderman** [Hacker0x01/react-datepicker#2104]
**Describe the bug**
When using a functional component for the custom input, as shown in the docs, the following error appears in the console:

<img width="505" alt="Screen Shot 2020-03-30 at 2 56 36 PM" src="https://user-images.githubusercontent.com/26726429/77965925-efad6300-7296-11ea-8383-eb769b2b9464.png">

**Expected behavior**
There should be no error in the console

**Comment by developius** [comment]
Whilst the docs are misleading (and jump around randomly?), I fixed this by doing what that error suggests - using `forwardRef` (truncated for simplicity):

```jsx
export default class MonthDatePicker extends React.Component {
  render() {
    return (
      <DatePicker customInput={<DatePickerTrigger/>} />
    );
  }
}

const DatePickerTrigger = forwardRef((props, ref) => {
  return (
    <button onClick={props.onClick}>
      {props.value}
    </button>
  );
});
```

**Comment by rachelruderman** [comment]
@developius good point!!! Thank you :))) closing the issue

**Comment by developius** [comment]
It’s definitely worth updating the docs though. I’ll find some time and put a PR together
