### ISSUE TITLE
showMonthYearPicker not working in version@2.14.1

### ISSUE THREAD

**Issue by taruntrivedi** [Hacker0x01/react-datepicker#2107]

**Comment by quazZzar** [comment]
Hello,
is there anyone working on this? 
The tab is crashing because of this, everything freezes... this is very important to be solved.

**Comment by taruntrivedi** [comment]
I had revert back to version 2.13 for it to be working

**Comment by quazZzar** [comment]
@taruntrivedi is it functionally acceptable? I mean isn't it crashing or something?

**Comment by taruntrivedi** [comment]
`<DatePicker
                  selected={this.state.startDate}
                  onChange={date => this.setStartDate(date)}
                  dateFormat="MMMM yyyy"
                  showMonthYearPicker
                />`

2.13 is wotking finew forme

**Comment by quazZzar** [comment]
Thank you @taruntrivedi ! Much appreciated!
