### ISSUE TITLE
Allow custom times

### ISSUE THREAD

**Issue by cisox** [Hacker0x01/react-datepicker#2108]
I'm using the react-datepicker in time only mode and I'd like to insert a `Start of Day` and `End of Day` time to the start and end of the list of times. I don't currently see a way to do that.

There's a `renderDayContents` function but that only applies to the days on the calendar view. It would be nice to have a feature such as `renderTimeContents` or perhaps a method that accepts a date and allows you to return a custom format such as `formatTime` which would fall back to the default date-fns `format` method already being used.

**Comment by ardamutlu** [comment]
also should be `renderMonthsContents`

**Comment by mikeyyyzhao** [comment]
@cisox Did you find a solution to this? I'm trying to add duration to the list of times from a set time. I tried @ardamutlu 's suggestion of renderMonthsContents but the method is not getting called (Not sure if it's an actual method, this thread is the only place this method is ever mentioned)
