### ISSUE TITLE
reactdatepicker.com broken scroll/focus behavior (unusable)

### ISSUE THREAD

**Issue by scottc-netflix** [Hacker0x01/react-datepicker#2109]
**Describe the bug**
On reactdatepicker.com, the date picker at the very top, under the title of the page, has permanent focus and prevents me from using the page. 

**To Reproduce**

Example 1:
1. Click on one of the example links
2. URL updates but page remains scrolled to the very top

Example 2:
1. Scroll down a few screens to an example.
2. Interact with any of the example datepickers.
3. Click away from the datepicker example so it loses focus.
4. Scroll the page up or down with scroll wheel or touchpad.
5. Result: Page immediately snaps to the very top datepicker under the title

**Desktop (please complete the following information):**
OS: Mac OS Mojave 10.14.6
Chrome 80

**Comment by TheKalpit** [comment]
Same issue for me on Firefox v74; Mac OS Catalina 10.15.3

**Comment by LanhKhoc** [comment]
Same issue for me on Chrome v81, Ubuntu 18.04.
It is very annoying.
