### ISSUE TITLE
Day component is slow to render

### ISSUE THREAD

**Issue by mattcolman** [Hacker0x01/react-datepicker#2114]
**Describe the bug**
We have noticed that it can take up to 10 seconds on old iphones to open up react-datepicker. On further investigation it appears that the Day component is slow to render and could be optimized.

**To Reproduce**

1. Use chrome devtools performance tab to record opening up react-datepicker
2. Notice that `isSameDay` function gets called multiple times for each Day component

**Expected behavior**
React datepicker should render without any noticeable lag on any device

**Screenshots**
<img width="1438" alt="2020-04-15 20-50-50" src="https://user-images.githubusercontent.com/1013215/79329837-d1648a00-7f5b-11ea-8574-2eca68a8dfc5.png">
Notice the multiple calls to `isSameDay`

**Desktop (please complete the following information):**

- OS: MacOS
- Browser chrome
- Version 80.0.3987.163

**Smartphone (please complete the following information):**

**Additional context**
It appears that `isSameDay` is quite expensive. I'm sure you don't have to call it twice per Day component. Instead create a day map per month and pass through props to Day like `isSelected` and `isToday`

**Comment by MagnusPladsen** [comment]
This is still a problem... It uses about 2-3 seconds to change the month.

**Comment by WillTaylor22** [comment]
This still seems to be an issue?
