### ISSUE TITLE
Calendar stays open when tabbing backwards

### ISSUE THREAD

**Issue by selbekk** [Hacker0x01/react-datepicker#2115]
**Describe the bug**
If you have opened the datepicker calendar, and tab backwards (shift+tab), the calendar stays open. 

**To Reproduce**
Here is a reproduction with explanation: https://codesandbox.io/s/react-datepicker-repro-cw2pi?file=/src/App.js

**Expected behavior**
It should close the calendar

**Additional context**
I guess this happens because react-datepicker doesn't track where the focus is correctly. Perhaps a change to the setBlur function could fix it?

**Comment by brunormferreira** [comment]
Same problem on current project here... nice point!

**Comment by openseah** [comment]
Any update for this bug?

**Comment by jhogervorst** [comment]
Same issue here…
