### ISSUE TITLE
Page scroll to bottom after used inline option

### ISSUE THREAD

**Issue by bhavin-nakrani** [Hacker0x01/react-datepicker#2117]
**Describe the bug**
I used "inline" option to show datepicker directly in div. When I refresh page, my page is directly show footer section instead of header.

**To Reproduce**

React: 16.12.0
react-datepicker: 2.11.0

1. Implement code and mention "inline" option.
2. Page refresh and it will auto scroll to datepicker section or scroll to bottom of page.
3. If I remove "inline" then it works perfectly.

**Expected behavior**
HTML page should display top section instead of bottom section

**Code**
```
render() {
      return (
            <DatePicker
              selected={this.state.startDate}
              onChange={this.handleChange}
              locale="de"              
              id={this.state.id}  
              inline              
            />                    
      );
    }
```

**Desktop (please complete the following information):**

- OS: [Ubuntu]
- Browser [chrome, firefox]

**Comment by sudo-sj** [comment]
Adding `{+disabledKeyboardNavigation+}` and removing `{-selected-}` props helped me. ”Issue” is day receiving focus when component mounts and that causes scroll in some cases / browsers.

**Comment by binnyFriedman** [comment]
Same thing here, I noticed that it only happens on ios devices but on  browsers:[safari, chrome].

**Comment by 1jmj** [comment]
still an issue, on safari, chrome & edge
