### ISSUE TITLE
Calendar overlapped with datepicker

### ISSUE THREAD

**Issue by jacky-ew** [Hacker0x01/react-datepicker#2119]
**Describe the bug**
Calendar component covers the datepicker dropdown.

**To Reproduce**

1. declare a datepicker on top of a calendar component
2. calendar covers datepicker

**Expected behavior**
datepickers render on top of every component

**Screenshots**
<img width="475" alt="Screenshot 2020-04-23 at 17 09 07" src="https://user-images.githubusercontent.com/56298610/80082140-84e60380-8586-11ea-86c2-cddb1dfbbb2d.png">

**Desktop (please complete the following information):**

- OS: macOs
- Browser Chrome
- Version chrome v81

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jacky-ew** [comment]
component used: react-big-calendar

**Comment by ChrisWU012** [comment]
@jacky-ew Have you solved the problem? I'm facing the same problem.
