### ISSUE TITLE
Accessibility :: Date Picker : Previous and Next Month Buttons Are Read as "Next Month" With Voiceover Enabled

### ISSUE THREAD

**Issue by amorun2** [Hacker0x01/react-datepicker#2120]
**Describe the bug**
When a user has speak-over enabled, the previous and next month's buttons both read as "Next Month". The next month button should read "Next Month" when in focus.

**To Reproduce**
Open any date picker with speak-over enabled, and bring focus to the Next month button. Speak-over will read "Previous Month".

**Expected behavior**
The next month button should read "Next Month" when in focus.

**Desktop:**
All devices and all browsers

**Screenshot**
<img width="915" alt="Screen Shot 2020-04-24 at 8 46 06 AM" src="https://user-images.githubusercontent.com/26802846/80220053-e8b11080-8608-11ea-8972-e7641a79fd26.png">

**Comment by ben-caplan** [comment]
Im on it! I'll hopefully have a PR up shortly 😄

**Comment by ben-caplan** [comment]
Great news, looks like this bug was already fixed! Upgrading the version of RDP fixes this issue, so this can be closed.

**Comment by amorun2** [comment]
Closing this issue, as it has been fixed
