### ISSUE TITLE
Force user to select both date and time

### ISSUE THREAD

**Issue by thamanchand** [Hacker0x01/react-datepicker#2123]
Is there a way to force user to select time upon date selection or make both date and time mandatory on datetimepicker? If time is not selected how can i show message? I went through documentation but couldn't find right info. 

Help me out!

<img width="528" alt="Screen Shot 2020-04-28 at 11 06 30" src="https://user-images.githubusercontent.com/1145027/80450181-ae18e200-8940-11ea-9622-b53b9b7158e6.png">

**Comment by evansjohnson** [comment]
Also having this issue.  In my case I have a minDate/maxDate and minTime/maxTime set and only selecting date or only selecting time causes the value to be out of range.  Looking for similar issues, may open a new one specific to not enforcing the min/max ranges.

**Comment by saltire** [comment]
Also mentioned in #1917. Reproducible on https://reactdatepicker.com if you edit the "Specific date range" example to add `showTimeSelect` and set `minDate={addDays(new Date(), 2)}`. 

Interestingly, the keyboard navigation defaults to the first valid day (👍), but if you don't actually click that day and just click a time, the result defaults to today (👎).

**Comment by sebastianpatten** [comment]
Yea I need this as well
