### ISSUE TITLE
Year Dropdown Demo broken on webpage

### ISSUE THREAD

**Issue by tayloraucoin** [Hacker0x01/react-datepicker#2129]
-> https://reactdatepicker.com/ 

![Screen Shot 2020-05-03 at 8 06 37 PM](https://user-images.githubusercontent.com/10913613/80933708-bd04f780-8d79-11ea-8335-5f0047fe69f5.png)

**Comment by martijnrusschen** [comment]
This should be fixed with #2132 merged. We will release a new version shortly.
