### ISSUE TITLE
Does the lib support multiple date selections?

### ISSUE THREAD

**Issue by jacky-ew** [Hacker0x01/react-datepicker#2131]
**Is your feature request related to a problem? Please describe.**
Requires to select multiple dates from the calendar, non-continuous 

**Describe the solution you'd like**
accept an array of dates in `selected` props

**Describe alternatives you've considered**
using another library but it will not be standardised in application

**Additional context**

**Comment by madeleineostoja** [comment]
Would be great if this could be reopened, and if it's not going to be implemented at least a solid answer to that
