### ISSUE TITLE
onChange can't be fired if use calendarContainer with createPortal

### ISSUE THREAD

**Issue by huangc8606** [Hacker0x01/react-datepicker#2138]
**Describe the bug**
onChange event can't be fired if create calendar via react portal, I want to avoid calendar being clipped by small size parent container.

**To Reproduce**

```
const [startDate, setStartDate] = useState(new Date());
return (<DatePicker
          selected={startDate}
          calendarContainer={({ children }) => {
            return ReactDOM.createPortal(children, document.body);
          }}
          onChange={date => setStartDate(date)} />)
```

**Expected behavior**
Should trigger onChange event when select date in calendar popup appended into body.

**Desktop (please complete the following information):**
- Browser: Chrome
- react-datepicker version: 2.15.0

**Comment by mjchang** [comment]
Encountered the same thing. Seems clicking on the calendar actually triggers the close calendar function so the onChange is not called.

I found a solution though - create portal in popperContainer instead
```
const [startDate, setStartDate] = useState(new Date());
return (<DatePicker
          selected={startDate}
          portalContainer={({ children }) => {
            return ReactDOM.createPortal(children, document.body);
          }}
          onChange={date => setStartDate(date)} />)
```

**Comment by huangc8606** [comment]
Thanks for the reply, it solves the issue.
