### ISSUE TITLE
Accessibility: Dates unreachable via keyboard when `inline` set to `true`

### ISSUE THREAD

**Issue by miina** [Hacker0x01/react-datepicker#2141]
**Describe the bug**
When the calendar is displayed inline (`inline` set to `true`), the calendar dates seem to be unreachable via keyboard. E.g. tabbing to the date and using arrow keys to navigate doesn't seem to work.

**To Reproduce**

This can also be seen on the examples website.

1. Go to https://reactdatepicker.com/#example-inline-version (Inline version example)
2. Click on one of the month arrows to visibly have the focus there
3. Click tab to go into dates
4. See the focus going out of the calendar

**Expected behavior**
Dates should be accessible via keyboard independent of the calendar having `inline` set to true.

**Screenshots**
Tabbing here:
![tabbing](https://user-images.githubusercontent.com/3294597/81727399-35aa3900-9489-11ea-9f0a-c3b044aff375.gif)

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome

**Comment by miina** [comment]
Trying to use the calendar inline [in a plugin](https://github.com/google/web-stories-wp/pull/1743/files#diff-506f36fac1a9c8ae575f0854723a283eR44-R49), however, the keyboard accessibility doesn't seem to work in case of `inline`.
.
Assuming it's a bug since it doesn't work on the demo website either, however, it would be good to know if it needs a special configuration instead.

**Comment by arsnyder16** [comment]
@miina I am seeing the same behavior with inline. For me when i navigate with arrows through the days it seems to actually be moving but the class is not getting applied to the element that will show the styling that it is keyboard selected. There is a specific check for inline that will always return false for keyboard selected 

![image](https://user-images.githubusercontent.com/6554919/82330839-530f6380-99b1-11ea-8bbf-4ce41f682c8c.png)

I am not sure of the history of why that is there.
