### ISSUE TITLE
Uncaught RangeError: Invalid time value

### ISSUE THREAD

**Issue by doverradio** [Hacker0x01/react-datepicker#2143]
**Describe the bug**
After loading react-datepicker example into my next.js frontend, tho it renders, if I click any date, it crashes the page and throws the error: Uncaught RangeError: Invalid time value

**To Reproduce**

```
const [date, setDate] = useState(new Date());

    const handleDateChange = date => {
        setDate({ date: date });
    };
<DatePicker className="form-control"
    // value={date}
    selected={date}
    onChange={handleDateChange}
    />

```
**Expected behavior**
Needs to work!  I need to be able to pick a date and not have the page crash.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows/Ubuntu
- Browser: Chrome

**Comment by barrychapman** [comment]
Also having this same problem

**Comment by varunshukla** [comment]
I am facing a similar issue. Has anyone found the solution?

**Comment by nacimgoura** [comment]
This problem is still present, please resolve

**Comment by Desintegrator** [comment]
same

**Comment by ngoduchung2B** [comment]
same :((

**Comment by techiekarthick** [comment]
I'm also facing a similar issue.. anyone found the solution ? **RangeError: Invalid time value**
![image](https://user-images.githubusercontent.com/55398402/166192614-e150e09c-f4c7-48af-8fd2-26ed5e2dee47.png)

**Comment by musicalmacdonald** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/1812#issuecomment-508827336
