### ISSUE TITLE
renderDayContent gets invoked repeatedly which causes browser to go out of memory and kills the page

### ISSUE THREAD

**Issue by Vgurnani** [Hacker0x01/react-datepicker#2145]
**Describe the bug**
renderDayContent call again and when we go on the calendar and do hover on any date and scroll.

**Comment by Vgurnani** [comment]
It keeps on calling renderDayContent function even when someone scrolls outside calendar same issue is happening on your demo link as well.
See the image attached below
![Screenshot 2020-05-26 at 5 36 23 PM](https://user-images.githubusercontent.com/32096089/82898795-7f118280-9f77-11ea-989c-8f6baf3373c2.png)
@jgelens @martijnrusschen @rafeememon @RSO @iam4x

**Comment by RSO** [comment]
I don’t appreciate you mentioning me on a repository that I last committed to multiple years ago while working for a company that I don’t work for anymore. Next time please take into consideration that most contributors manage projects like this voluntarily. If you’ve discovered a bug you should feel free to submit a Pull Request or fork the repository!

**Comment by locdangle2552** [comment]
I have the same issue. Can anyone resolve this issue?
