### ISSUE TITLE
DatePicker includes time style not working?

### ISSUE THREAD

**Issue by imnobunny** [Hacker0x01/react-datepicker#2148]
I can't get the same view of **react-datepicker includes times** as one in here (https://reactdatepicker.com/). Even though I have this  style imported "react-datepicker/dist/react-datepicker.css  inside my component.

**Screenshots**
Datepicker inside my web app.
![image](https://user-images.githubusercontent.com/32007478/81962966-0fca9300-9647-11ea-8cee-f517824c8ce8.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome

Thanks,

**Comment by SivaGanesh56** [comment]
+1

**Comment by imnobunny** [comment]
Closing this issue now..
