### ISSUE TITLE
Year Picker min/max dates.

### ISSUE THREAD

**Issue by essedger** [Hacker0x01/react-datepicker#2154]
**Describe the bug**
minDate and maxDate doesn't work correctly. 

**To Reproduce**
add to <DatePicker/>
showYearPicker
dateFormat="yyyy"
minDate={startDate}
maxDate={endDate}

**Expected behavior**
For example dates:
const [startDate, setStartDate] = useState(new Date("2001/02/08"));
const [endDate, setEndDate] = useState(new Date("2015/04/08"));

Picker shows 3 pages and doesn't disable values over the period.
Also it duplicats 2001 and 2012 years. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12384438/82347748-b07ed100-9a00-11ea-878e-9a2bcdfed260.png)
![image](https://user-images.githubusercontent.com/12384438/82347793-bc6a9300-9a00-11ea-9964-1269370f12c8.png)
![image](https://user-images.githubusercontent.com/12384438/82347813-c391a100-9a00-11ea-84b0-775193d5c811.png)

- OS: Windows 10
- Browser [chrome, safari, etc]
- Version [2.15.0]

**Comment by Marc19** [comment]
Yeah, I am facing the same problem. Is there at least a way to give a className for out of range dates?

**Comment by martijnrusschen** [comment]
Fixed by https://github.com/Hacker0x01/react-datepicker/pull/2186

**Comment by Marc19** [comment]
How can I get this fix? I am trying 'npm update' but there is no update.
