### ISSUE TITLE
Time selection does not fire onSelect event

### ISSUE THREAD

**Issue by haizz** [Hacker0x01/react-datepicker#2156]
Original issue #1590 was closed by bot without any resolution.

Expected behavior

Time selection fires onSelect event. closeOnSelect closes the picker after time selection.

Actual behavior

Time selection does not fire onSelect event. closeOnSelect closes the picker just after date selection not allowing users to select time.

Steps to reproduce

Trivial

**Comment by tannermann** [comment]
It is unfortunate that these issues are being closed automatically without resolution one after another.
