### ISSUE TITLE
onChangeRaw and onChange triggered at same time

### ISSUE THREAD

**Issue by thesnowgoose** [Hacker0x01/react-datepicker#2161]
**Describe the bug**
When I start typing a date Ex. `06/22/2020` both onChange and onChangeRaw are triggered at same time.

**To Reproduce**
The problem seems **to be only when I type the first digit**

When typing `06/22/2020`:
1. onChangeRaw is triggered with `event.target.value` equal to 0
2. onChange is triggered with date equal to `Jan 01 2000 00:00:00`
3. If I keep typing, only onChangeRaw its triggered for the rest of the values set

**Expected behavior**
onChange is not triggered at all when typing data

**Screenshots**
Here is what it logs when typing
![image](https://user-images.githubusercontent.com/17257307/83056117-12979180-a012-11ea-86c7-8a97ea1e59bc.png)

**Desktop (please complete the following information):**

- OS: macOX
- Browser: chrome
- Version 2.11.0

**Comment by dennisat** [comment]
This is a serious bug!

**Comment by frali14** [comment]
Three years later I'm having the same problem, is it possible to fix this please?

**Comment by Kucerenko171** [comment]
@frali14 Try to add `e.preventDefault()`

e.g.
`onChangeRaw={(e) => {
e.preventDefault()
//other code...
}`

**Comment by Abdeladim101Basraoui** [comment]
@thesnowgoose actually this helped me to make the user insert number values only instead of characters
