### ISSUE TITLE
Selected value first in the box

### ISSUE THREAD

**Issue by AndrewOkonar** [Hacker0x01/react-datepicker#2166]
I'm using "year picker" for input where the user should select the next data for future events.

```
      {jobStartsAtFormat === 'specific_date' && <S.DatePickerOptional
        selected={job.startsAt && moment(job.startsAt).toDate()}
        onSelect={handleDate('startsAt')}
        showYearPicker
        dateFormat="yyyy"
        customInput={<InputRef
          name="startsAt"
          label="Eintrittsdatum"
          error={errors.startsAt}
          placeholder="Gibt es eine Eintrittsdatum?" /> } />}
```

![image.png](https://images.zenhubusercontent.com/596cb2bd61b4ca3b0a74a9a9/fc69cef4-364d-41f5-8257-ab30be01d632)

And as you see selected year always the last in the box. is it possible to make always first in the box and show future years?

**Comment by martijnrusschen** [comment]
Fixed by https://github.com/Hacker0x01/react-datepicker/pull/2186
