### ISSUE TITLE
Initial value from the beginning and not from the end?

### ISSUE THREAD

**Issue by AndrewOkonar** [Hacker0x01/react-datepicker#2167]
User wants to set/edit a new date for the deadline. And the user should choose future date while editing this field. but as you see all selected value from "showYearPicker" stared from the end (screenshot 1). is it possible make selected value always first in the container? (screenshot 2)

1)
![image](https://user-images.githubusercontent.com/23657360/83421613-0efc7400-a431-11ea-8281-6154aca09bf5.png)

2)
![image](https://user-images.githubusercontent.com/23657360/83422277-f50f6100-a431-11ea-9bba-745d29a5e1ea.png)

**Comment by martijnrusschen** [comment]
Fixed by https://github.com/Hacker0x01/react-datepicker/pull/2186
