### ISSUE TITLE
When turning over months, several dates are highlighted.

### ISSUE THREAD

**Issue by ouldanov** [Hacker0x01/react-datepicker#2178]
When a date is selected which when turning over month present in the current and next, it will be highlighted in both.

1. Select date in the end of month.
2. Turn over next month.
3. It can be seen that several dates are highlighted.
The same thing when select date in start of month and turning over on the previous month.

![rd-ssue](https://user-images.githubusercontent.com/38261337/84011533-efa89e00-a97e-11ea-8c18-7ef0e5c1bb15.gif)

**Comment by 3bOONAL** [comment]
It doesn't look like a bug. As I understood 30 June on gif it's selected date and it's equal the date in input, but 30 Jule it's a date which displays selected date after increasing by the month. You can see it by the color of the days. 30 June(current date) is darker than 30 July(current date + month). Light highlight may be seen if you try to manipulate by keyboard arrows.  If it inappropriate behavior you can try rewrite styles for it(class react-datepicker__day--keyboard-selected responsible for this)

**Comment by 3bOONAL** [comment]
> When a date is selected which when turning over month present in the current and next, it will be highlighted in both.

It doesn't look like a bug. As I understood 30 June on gif it's selected date and it's equal the date in input, but 30 Jule it's a date which displays selected date after increasing by the month. You can see it by the color of the days. 30 June(current date) is darker than 30 July(current date + month). Light highlight may be seen if you try to manipulate by keyboard arrows. If it inappropriate behavior you can try rewrite styles for it(class react-datepicker__day--keyboard-selected responsible for this)

**Comment by ouldanov** [comment]
Okay, sorry.
I did not notice that they are of different colors, did not expect such behavior, I will rewrite the class you wrote about.
