### ISSUE TITLE
Prevent Datepicker From Changing Input Value onBlur

### ISSUE THREAD

**Issue by kcunanan** [Hacker0x01/react-datepicker#2180]
Is it possible to prevent the datepicker component from altering the datepicker component on bad input? i.e. if someone enters something like `ffffff` or `39/20/2020` I'd prefer to manually handle that and alert that the input is invalid rather than immediately changing it for the user.

**Comment by SonyaKaramchandani** [comment]
I believe you can just do:
`onChangeRaw={e => e.preventDefault()}` 

and that should prevent it from being altered!
