### ISSUE TITLE
RangeError: Invalid time value, when clearing the input field

### ISSUE THREAD

**Issue by NemanjaTck** [Hacker0x01/react-datepicker#2181]
Clearing the input field and then clicking somewhere outside the datepicker breaks the application with the following error
- RangeError: Invalid time value

**To Reproduce**
1. Clear the input field of the datepicker
2. Click somewhere outside of the field 

**Expected behavior**
Accepting null/undefined values or reseting to the previous value

**Screenshots**
![image](https://user-images.githubusercontent.com/3010324/84475382-bfb60f00-ac8c-11ea-9e15-2b70469a8155.png)

**Comment by seangibbens** [comment]
Issue occurs when clearing via the keyboard, and also clearing via the `isClearable` button.

**Comment by SeokhwanWon** [comment]
me too

**Comment by chrifmarwen** [comment]
We have encountred the same issue and landed here,

but after some experimentation, our problem cames from setting an invalid value passed to the "selected" props
(invalid moment date with toDate())

**Comment by pellea** [comment]
Why is this close? The issue is still there in the latest version.

**Comment by MaxLeiter** [comment]
I agree, I'm also running into this.

**Comment by Desintegrator** [comment]
same
