### ISSUE TITLE
Today footer

### ISSUE THREAD

**Issue by noyessie** [Hacker0x01/react-datepicker#2185]
Please, there is a way to add a today footer to datepicker ?

something like `Today: 12 august 2018`.

I tried to use `todayButton` but i don't have access to the current date inside the element.

Thank you.

**Comment by fkropfhamer** [comment]
You can just set a child component:
`() => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker selected={startDate} onChange={date => setStartDate(date)}>
      <div >Today: 12 august 2018</div>
    </DatePicker>
  );
};`
