### ISSUE TITLE
Wrong date selected with time picker when minDate is provided

### ISSUE THREAD

**Issue by amrithakrishnan** [Hacker0x01/react-datepicker#2194]
**Describe the bug**
When a `minDate` different from the current date is provided to a date+time picker and you select a time, the resulting data has the current date with the time you select.

**To Reproduce**
Here's the component code from the following sandbox example:
```
<DatePicker
          onChange={val => {
            this.setState({ date: new Date(val).toISOString() });
          }}
          showTimeSelect
          dateFormat="dd/MM/yyyy HH:mm"
          timeFormat="HH:mm"
          timeIntervals={1}
          timeCaption="Time"
          name="schedule"
          selected={this.state.date ? new Date(this.state.date) : null}
          placeholderText="Click to select"
          autoComplete="off"
          minDate={new Date("12-12-2020")}
        />
```

Here's the example:
1. Go to [CodeSandbox example](https://codesandbox.io/s/react-datepicker-example-hjooj).
2. Click on the date field.
3. Click on some time.

**Expected behavior**
The resulting date+time should be the highlighted date selected by default instead of the current date.

**Screenshots**
![bug](https://user-images.githubusercontent.com/10302887/85444866-631df280-b5b0-11ea-94f8-a76d9bc7d89f.gif)

**Comment by amrithakrishnan** [comment]
For anyone else facing this issue, I was able to solve it by passing `openToDate` prop with the same value as that of `minDate`.

```
<DatePicker
    onChange={val => {
      this.setState({ date: new Date(val).toISOString() });
    }}
    showTimeSelect
    dateFormat="dd/MM/yyyy HH:mm"
    timeFormat="HH:mm"
    timeIntervals={1}
    timeCaption="Time"
    name="schedule"
    selected={this.state.date ? new Date(this.state.date) : null}
    placeholderText="Click to select"
    autoComplete="off"
    minDate={new Date("12-12-2020")}
    openToDate={new Date("12-12-2020")}
/>
```

**Comment by RacketyWater7** [comment]
This didn't work for me :(

**Comment by RacketyWater7** [comment]
I want to remove the default today's date selected in my datepicker (selectsRange). Because when I have provided a minDate, and if that minDate is after the today's date, the datepicker still selects today's date as a from-date in range.
