### ISSUE TITLE
DatePicker allows dates to be entered that subsequently trigger a RangeError

### ISSUE THREAD

**Issue by alyssa-glean** [Hacker0x01/react-datepicker#2195]
**Describe the bug**
The component allows dates to be entered with years greater than 9999 (both by manually typing and by navigating using the calendar). However, passing a saved value this large to the `selected` prop causes the component to blow up with a `RangeError`.

**To Reproduce**

1. Add a simple date picker:

```
<ReactDatePicker
    minDate={new Date()}
    selected={date}
  />
```

2. Select a date after `31 Dec 9999`, e.g. 01/01/10000. The `ReactDatePicker` accepts this value.
3. Do something that causes that same value to be passed to a new `ReactDatePicker` as its `selected` prop (in our case, it's saved to the DB so we can achieve this by just refreshing the page).
4. The `ReactDatePicker` blows up with the following (minified) exception:

```
RangeError: Invalid time value
    at format (index.js:371)
    at Me (react-datepicker.min.js:1)
    at r.renderDateInput (react-datepicker.min.js:1)
    at r.value (react-datepicker.min.js:1)
```

**Expected behavior**
The picker should not allow values to be entered which won't be accepted as valid later. Entering a date that's too large should not update the value, in the same way that typing nonsense does.

**Relevant versions:**

- OS: Linux (Ubuntu 18)
- Browser Chrome 80
- `react-datepicker` version `2.13.0`

**Additional context**
It's possible to work around the issue by setting the `maxDate` prop, e.g. `maxDate={new Date('December 31, 9999 00:00:00')}`

**Comment by xargr** [comment]
@alexburlton-sonocent what type is date variable in selected ? should be type date eg. selected={new Date()}

**Comment by alexburlton-sonocent** [comment]
Yep, the type is `Date`

**Comment by stephent** [comment]
Possibly related: setting `dateFormat` to something like 'eee PP' (trying to get short days - why, oh why, isn't that one of date-fns 'P' format styles?), and then typing 'Wed Jan' in to the picker field results in this:

'Exception has occurred: RangeError: The format string mustn't contain `eee` and `MMM` at the same time

This appears to be an error thrown in the parse function date-fns, but it appears not be caught by DatePicker.

**Comment by lal12** [comment]
This issue shouldn't go stale... It is a significant bug and easy to reproduce!
