### ISSUE TITLE
When installing package, get error: /node_modules/react-datepicker/dist/react-datepicker.min.js Module not found: Error: Can't resolve 'date-fns/subDays' in 'D:\code\OrckestraCommerce.Application.OMS\node_modules\react-datepicker\dist'

### ISSUE THREAD

**Issue by TONYFECTEAU** [Hacker0x01/react-datepicker#2196]
I am evaluating whether this date time picker is good for our use.  We need a date and time picker that works well in Chrome and IE11.

I did a:  npm install react-datepicker
As soon as I add: import "react-datepicker/dist/react-datepicker.css";

**The below errors occur:**
/node_modules/react-datepicker/dist/react-datepicker.min.js
Module not found: Error: Can't resolve 'date-fns/subDays' in 'D:\code\OrckestraCommerce.Application.OMS\node_modules\react-datepicker\dist'

**Entries in my packages.lock:**
    "_react-datepicker_": {
      "version": "3.0.0",
      "requires": {
        "classnames": "^2.2.6",
        "_date-fns_": "^2.0.1",
        "prop-types": "^15.7.2",
        "react-onclickoutside": "^6.9.0",
        "react-popper": "^1.3.4"
      }
    },

    "_date-fns_": {
      "version": "2.14.0",
    },

**Environment info:**
Dev machine is Windows10
I tried with Chrome and IE11, and the same errors occur.

**Comment by csk1827** [comment]
same here

**Comment by TONYFECTEAU** [comment]
I resolved my issue... we had a strange alias setup that mapped date-fns as a v1 release, and an alias created called date-fns-2, that was linked to date-fns.  I removed the need for the old date-fns, and removed the alias, and all was working for me.
