### ISSUE TITLE
 2 dates getting selected after month changed

### ISSUE THREAD

**Issue by RoshanGirhe** [Hacker0x01/react-datepicker#2203]
2 dates showing selected after month changed

**To Reproduce**
1. Select date which in last row and it will come in next month starting.
2. click on next arrow which change month.
It will show selected date from last month as well as in current month.

**Expected behavior**
It should not show selected date in every month this functionality should optional.

**Screenshots**
![datepicker](https://user-images.githubusercontent.com/42737573/86019365-220c5f00-ba44-11ea-80fc-cdb96f7db03c.PNG)

**Desktop (please complete the following information):**

- OS: [e.g. windows]

**Additional context**
Using latest version.
"react-datepicker": "^3.0.0",

**Comment by nguyen-darianhuy** [comment]
Looks like this bug was introduced in version 2.15.0
