### ISSUE TITLE
Selected day repeat to all months

### ISSUE THREAD

**Issue by dcmunhoz** [Hacker0x01/react-datepicker#2205]
**Describe the bug**
After set 'selected' prop, the calendar highlight all subsequent equals days

**To Reproduce**
```` Node
            <DatePicker 
                placeholderText="Selecione uma data"
                dateFormat="dd/MM/yyyy"
                className="custom-date-picker"
                minDate={new Date()}
                onChange={onChange}
                selected={startDate}
            />
````
**Screenshots**
![Captura de Tela 2020-06-29 às 21 18 43](https://user-images.githubusercontent.com/23061616/86068908-dad79b80-ba4e-11ea-9e1a-569f085da40e.png)

**Versions**
react-datepicker: "^3.0.0"

**Comment by xargr** [comment]
I have the same, any update @dcmunhoz ?

**Comment by nguyen-darianhuy** [comment]
Looks like this bug was introduced in version 2.15.0

**Comment by denis-n** [comment]
Still present.

Version 3.1.3.

**Comment by damonbauer** [comment]
Same issue here: #2376
