### ISSUE TITLE
2 dates selected when changing date until closed

### ISSUE THREAD

**Issue by gadzet** [Hacker0x01/react-datepicker#2206]
**Describe the bug**
When changing date by setting it's state, the datepicker does not unselect the previous date, so both previous and new date are selected.

**To Reproduce**

Click on the today button to set state as provided in example. 
You will see that both dates are selected

I am also experiencing the same issue as described #2203, not sure if its related

```
const Datepicker = React.forwardRef(function Datepicker(props, ref) {
    const {
        children,
        className = '',
        ...other
    } = props;
    const [startDate, setStartDate] = useState(new Date());

    return (
        <div>
        <DatePicker
            selected={startDate}
            onChange={date => setStartDate(date)}
            locale={nb}
            
        >
            <div>
                <button  onClick={() => setStartDate(new Date())}>Today</button>
            </div>
        </DatePicker>

        </div>
    )
});

export default Datepicker;
```

**Comment by pio87** [comment]
For a walkaround use this prop, seems that keyboard navigation stays on.
`disabledKeyboardNavigation={true}`
