### ISSUE TITLE
Possibility to remove the inline height on time container

### ISSUE THREAD

**Issue by thibaultauvray** [Hacker0x01/react-datepicker#2207]
**Is your feature request related to a problem? Please describe.**
I have a problem with the inline CSS height that is set on the time container. My issue seems to be related to #2056.  

Even if I set `display: none` on every disabled time: the inline-height is still set to 360px here. 
![image](https://user-images.githubusercontent.com/5720128/86142078-15930f80-baf3-11ea-9e02-4b180f130111.png)

And i don't know why a height is set in inline. It annoying for responsive reason.

**Describe the solution you'd like**
having possibility not to put a inline height here.

**Additional context**
![image](https://user-images.githubusercontent.com/5720128/86142963-1f694280-baf4-11ea-984d-78088053d89c.png)

**Comment by austinlxx** [comment]
I had this same issue with the TimePicker inline height exceeding the DatePicker's height.

```
<ul class="react-datepicker__time-list" style="height: 274px;">...</ul>
```
![image](https://user-images.githubusercontent.com/9122618/105085235-51b89e00-5a4c-11eb-9991-1cebe186f74b.png)

A workaround for me was to use `!important` within the class `ul.react-datepicker__time-list`.
```
'ul.react-datepicker__time-list': {
    height: '234px !important'
},
```

![image](https://user-images.githubusercontent.com/9122618/105085480-a9570980-5a4c-11eb-9180-39cad6c0c368.png)
