### ISSUE TITLE
the popper is going inside the popup.

### ISSUE THREAD

**Issue by athuldom** [Hacker0x01/react-datepicker#2211]
I have some fields inside a popup where datepicker is used. but inside the popup the popper of the datepicker is going inside the scroll rather than showing above the popup. I'm working on a reactjs project. How can i acheive it ? 

![popup-Datepicker_issue](https://user-images.githubusercontent.com/67672807/86579214-9db56100-bf9a-11ea-99bf-8f0740e4845f.PNG)

**Expected behavior**
the popper must be shown above the popup

**Desktop (please complete the following information):**

- OS: windows
- Browser: chrome,firefox
- Version: latest

**Comment by MathisBicheyre** [comment]
I'm interested, I have kind of the same issue. 
Tried 
`.react-datepicker-popper {
  overflow: visible;
  z-index: 2147483647;
}`
But it doesnt work. I guess the next thing is to use portals but I have no idea how to display the component in the right position

**Comment by athuldom** [comment]
How to use the portals for this issue? any idea? i have not used it before

**Comment by rikkertkoppes** [comment]
Simple answer: use `portalId` property to point to a container where you want your picker to be. If an element with that id does not exist, it is created at the end of the page

I am also running into this problem but it gets a little more complicated. My datepicker was in a `dialog` element, and the portal automatically created at the end of the document. As a result, it is behind the dialog. z-index does not work here, as the dialog is in its own top-layer (see https://fullscreen.spec.whatwg.org/#top-layer and https://stackoverflow.com/questions/41815069/is-it-possible-to-position-a-div-on-top-of-a-dialog-tag-that-is-not-its-parent)

I am trying to use a custom `calendarContainer` that wraps the date picker in a `dialog` element as well. No success yet

**Comment by DerHerrGammler** [comment]
+1
