### ISSUE TITLE
Unable to associate the text input with a label

### ISSUE THREAD

**Issue by theSmaw** [Hacker0x01/react-datepicker#225]
It is not currently possible to provide a label for the text input created by react-datepicker, as an id attribute cannot be added to the input.

**Comment by martijnrusschen** [comment]
Should be fixed now!

**Comment by theSmaw** [comment]
Super, thanks!

**Comment by guigs** [comment]
Seems this is not working anymore since id is assigned to hidden input field and not to the visible one.
