### ISSUE TITLE
showPreviousMonths plus maxDate makes last month inaccessible

### ISSUE THREAD

**Issue by winstonwolff** [Hacker0x01/react-datepicker#2257]
**Describe the bug**

Here's the modified code:
```
() => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker
      selected={startDate}
      onChange={date => setStartDate(date)}
      monthsShown={2}
      maxDate={new Date()}
      showPreviousMonths
    />
  );
};
```
**To Reproduce**

- modify your Multiple Months example, adding a `maxDate={new Date()}` and `showPreviousMonths` attributes. See example below.
- Open the date picker and pick a day in the current month, let's say July.
- Open the date picker again. Notice it opens to June, not July.
- Also there is no right arrow, so I cannot get back to July.
**Expected behavior**
- I expected that I would be able to access July, and see the date I had picked.

**Screenshots**

![previous-months-bug](https://user-images.githubusercontent.com/281580/87076840-24568200-c1d7-11ea-83ba-0be2e24e16c7.gif)

I have included an animated GIF showing the interaction.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Safari
- Version: 3.0.0 (release 159)

**Additional context**
- If I remove the `showPreviousMonths` attribute, it works fine. So it may be an interaction between them.

**Comment by johnayeni** [comment]
I currently facing this issue, has there been a solution added to the library for it?

**Comment by Antoshkiv** [comment]
I got the sam problem.
