### ISSUE TITLE
Locales can't be set

### ISSUE THREAD

**Issue by RipDevil** [Hacker0x01/react-datepicker#2258]
_Hello and thank you for the quite convenient package that I'd love using if we somehow fix this bug (or my simple misunderstanding)._ 

On your webpage with examples there are some ones about LOCALES. As you have live coding on your page I tried to change a locale in the Locale block and it led to warnings in the console. The same thing I am having on my project. What's wrong am I doing? 

I've installed **date-fns** of course but it doesn't help. I've tried to import locales from the package and to register them but it has not helped.

To reproduce this issue:
- put the DatePicker react component into any simple form;
- try to use locales.

I am using Chrome Version 83.0.4103.116 (Official Build) (64-bit).

_Sorry if this question is a bit dull or something._

**Comment by alex-pol** [comment]
Try to pass the locale directly to the component
For example:
`
import en from 'date-fns/locale/en-GB';
import de from 'date-fns/locale/de';
const dateLocales = {
  en,
  de,
};
const locale = 'de';
<DatePicker
   ...
   locale={dateLocales[locale]}
   ...
/>
`

**Comment by RipDevil** [comment]
@alex-pol 
Pitifully, this doesn't work. Maybe did I miss something here?

**"dependencies": {**
    "@babel/preset-react": "^7.10.4",
    "axios": "^0.19.2",
    "bootstrap-sass": "^3.3.6",
    "date-fns": "^2.14.0",
    "jquery": "^3.5.1",
    "js-file-download": "^0.4.12",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-autocomplete": "^1.8.1",
    "react-bootstrap": "^1.0.1",
    "react-datepicker": "^3.0.0",
    "react-dom": "^16.13.1",
    "react-dropzone": "^4.2.1",
    "react-html-parser": "^2.0.2",
    "react-redux": "^7.2.0",
    "react-redux-toastr": "^7.6.5",
    "react-select": "^3.1.0",
    "react-split": "^2.0.7",
    "react-virtualized-select": "^3.1.3",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0",
    "resolve-url-loader": "^3.1.0"
**}**

**Comment by RipDevil** [comment]
_Phew!_

After some time I've finnaly returned to this issue. 

At first glance I thought that the errror was with the React Bootstrap package that I used. I tried this and that, and a help from @alex-pol , but nothing worked out.

After that I went to the npm react-datepicker webpage of this package and found an information that wasn't presented on the webpage. Maybe this info is kind of obvious for someone but it helped me.

To solve this issue we have to import the **registerLocale** function else from the react-datepicker. And use it with a locale from the **date-fns** package.

An example:
```
import DatePicker, { registerLocale } from "react-datepicker";
registerLocale('de', de)
```
...and somewhere in code
```
<Form.Control
as={DatePicker}
locale="de"
 />
```
And it works!

_If you have any questions you can look above and see installed packages, maybe you have the same issue and the same packages stack, or you can PM._
