### ISSUE TITLE
renderCustomHeader only applies to first month when using Multiple months

### ISSUE THREAD

**Issue by pn13b** [Hacker0x01/react-datepicker#2264]
If you try to use Custom Headers (the renderCustomHeader prop) when using Multiple Months (monthsShown) the custom header only applies to the first month when using Multiple Months, the second displayed month does not even show a header. There does not seem to be any way to target the second month.

![Screen Shot 2020-07-14 at 12 38 00 PM](https://user-images.githubusercontent.com/10716432/87454795-7a119c80-c5d2-11ea-8039-03deba141327.png)

**Comment by nathpaiva** [comment]
This issue it about this point: https://github.com/Hacker0x01/react-datepicker/blob/master/src/calendar.jsx#L666

They have an if, to check the index of calendar, and render just for the first.

I thought open a `PR` to change this line and add a new `prop`, to verify if I want to render a custom `header` for all calendars or not.

In the project I'm working on, I added a custom header and create a function to resolve the current month.
