### ISSUE TITLE
time is changing while we use react-datepicker

### ISSUE THREAD

**Issue by bipindubey-technoark** [Hacker0x01/react-datepicker#2266]
i have selected 12:00 Pm in datepicker and i also console log it .... it shows Thu Jul 09 2020 12:00:00 GMT+0530 (India Standard Time) which is right time.
but when i click on save then it sends wrong time (2020-07-09T06:30:00.454Z).
It should send (2020-07-09T012:00:00.454Z)----Expected Behaviour
i dont know what is the issue and how to fixx this

I need to pass exact same time which user has  selected .

**Comment by mschefer** [comment]
2020-07-09T06:30:00.454Z is in UTC. This is the same time as Thu Jul 09 2020 12:00:00 GMT+0530. I don't know how you send the data but there seems to be a conversion to UTC somewhere.

**Comment by bipindubey-technoark** [comment]
no i have not converted dates anywhere but javascript deals with local time so if i had selected 12:00Pm then it send 6:30am  i think so.

**Comment by talovicnedim** [comment]
Have you found a solution? I think I came across the same thing and I'd like to save some time.

I select a date, convert it to UTC with moment.js, but after I select a new date then time goes -1. And -1 again and again. Weird.

@mschefer @bipindubey-technoark
