### ISSUE TITLE
default value for dateFormatCalendar is not suitable for japanese locale

### ISSUE THREAD

**Issue by arnauddem** [Hacker0x01/react-datepicker#2268]
Default value for dateFormatCalendar is 'LLLL yyyy'  (ie June 2020), if used with japanese locale it produce the text '7月 2020' whereas expected text is '2020年 7月'.  It's strange specially when uses dateFormat="P".

**To Reproduce**

0. set locale to 'ja'
1. Use :
```
 <DatePicker
        onChange={(r: any) => ()}
        dateFormat="P"
        minDate={new Date()}
        fixedHeight
      />
```
2. calendar input shows '2020/07/16' which is localized
3. open calendar, the top date is '7月 2020'  which is not localized

**Expected behavior**
top date should '2020年 7月.

**Screenshots**
![image](https://user-images.githubusercontent.com/52075241/87683397-517bd500-c781-11ea-85b0-006c30d1a1a8.png)

** workaround **
use dateFormatCalendar="yyyy年 LLLL" for 'ja' locale only
it shows:
![image](https://user-images.githubusercontent.com/52075241/87683625-9869ca80-c781-11ea-8f0e-d82779d0d572.png)

however I expect react-datepicker to convert 'LLLL yyyy' default value to the right one in current locale.

**Desktop (please complete the following information):**
- Browser Chrome Version 83.0.4103.116 in Win10

**Comment by arnauddem** [comment]
This issue is still opened and require attention and fix, thanks to silly robot to not move it to stale state.

**Comment by joos0701** [comment]
<DatePicker 
dateFormatCalendar={"yyyy年 LLLL"}
/>

**Comment by MBehtemam** [comment]
I have a same problem I created a Sandbox for this problem , 
[Sandbox Sample](https://codesandbox.io/s/wonderful-browser-bj2zp?file=/src/App.js)

**Comment by arnauddem** [comment]
This issue is still opened and require attention and fix, thanks to silly robot to not move it to stale state ! ;-).

**Comment by PurpleMonkey729** [comment]
> Default value for dateFormatCalendar is 'LLLL yyyy' (ie June 2020), if used with japanese locale it produce the text '7月 2020' whereas expected text is '2020年 7月'. It's strange specially when uses dateFormat="P".
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 0. set locale to 'ja'
> 1. Use :
> 
> ```
>  <DatePicker
>         onChange={(r: any) => ()}
>         dateFormat="P"
>         minDate={new Date()}
>         fixedHeight
>       />
> ```
> 
> 2. calendar input shows '2020/07/16' which is localized
> 3. open calendar, the top date is '7月 2020'  which is not localized
> 
> **Expected behavior** top date should '2020年 7月.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![image](https://user-images.githubusercontent.com/52075241/87683397-517bd500-c781-11ea-85b0-006c30d1a1a8.png)
> 
> ** workaround ** use dateFormatCalendar="yyyy年 LLLL" for 'ja' locale only it shows: ![image](https://user-images.githubusercontent.com/52075241/87683625-9869ca80-c781-11ea-8f0e-d82779d0d572.png)
> 
> however I expect react-datepicker to convert 'LLLL yyyy' default value to the right one in current locale.
> 
> **Desktop (please complete the following information):**
> 
> * Browser Chrome Version 83.0.4103.116 in Win10

You are right.
I am favor of it.
Thanks.

**Comment by yuki0410-dev** [comment]
In date-fns, the format to return the year and date is not facilitated.
On the other hand, the browser standard toLocaleDateString seems useful.

If dateFormatCalendar is unspecified, we believe we can easily obtain the desired string by modifying the library to format using toLocaleDateString.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
```js
date.toLocaleDateString(local, {
    year: "numeric",
    month: "long",
}
```

There are two concerns with toLocaleDateString: the local props currently passed to the datepicker do not necessarily match the local strings supported by toLocaleDateString. DateTimeFormat API does not work with all browsers that support this library.

https://caniuse.com/date-tolocaledatestring
https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat
