### ISSUE TITLE
Update "date-fns" dependency to the latest version

### ISSUE THREAD

**Issue by vinnichenko** [Hacker0x01/react-datepicker#2269]
**Is your feature request related to a problem? Please describe.**
I use the react-datepicker in one big multilingual project. We've found that the current version of the react-datepicker (3.1.3) does not have Hindi and Kazakh languages. That is probably because you use an old version of the "date-fns" library as a devDependency (2.0.1). The latest version (2.14.0) of "date-fns" library has those two locales.

**Describe the solution you'd like**
Update please the "date-fns" library to the version 2.14.0
Let me know if it's feasible.

Thank you in advance,
Artem

**Comment by martijnrusschen** [comment]
Feel free to submit a PR for this, happy to review it.

**Comment by vinnichenko** [comment]
Can't push to a feature branch => permissions denied.

**Comment by martijnrusschen** [comment]
You'll need to fork the repository first before pushing to a branch. Once you've made your changes, you can open a PR to this repo.

**Comment by martijnrusschen** [comment]
Btw, this lib isn' a devDependency but a peerDependency. This means, you can specify the wanted version yourself as long as it's above "2.0.1".

**Comment by vinnichenko** [comment]
Thanks, I see it's already here: https://github.com/Hacker0x01/react-datepicker/pull/2271
