### ISSUE TITLE
react-datepicker 0.14.0 and up will not support below React 13

### ISSUE THREAD

**Issue by mhubenthal** [Hacker0x01/react-datepicker#227]
The package.json needs to be updated to depend on React 0.13.0 and up for react-datepicker 0.14.0 and up. react-datepicker 0.14.0 and up uses "findDOMNode" which is introduced in React 0.13.0 and up.

**Comment by martijnrusschen** [comment]
The package already requires 0.14 or higher. What do we need to change?

**Comment by mhubenthal** [comment]
@martijnrusschen sorry, I should have been more specific...we're trying to use an older version of react-datepicker (we haven't made the jump to React 0.14.0 yet). Older versions of react-datepicker specify ```"react": ">=0.12 <0.14"```, but I think they should specify ```"react": ">=0.13 <0.14"```.

**Comment by martijnrusschen** [comment]
Correct. React 0.14 includes some breaking changes. I think the best solution for now would be checking out on an old commit before the change to React 0.14. (see https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html)

**Comment by mhubenthal** [comment]
@martijnrusschen thanks for the help. React-datepicker v0.6.2 is the most recent version that will work with pre 0.13.0 React, FYI.

**Comment by martijnrusschen** [comment]
Okay, I'll add that info to the Readme
