### ISSUE TITLE
onChange with dont receive array of dates

### ISSUE THREAD

**Issue by randalmaia** [Hacker0x01/react-datepicker#2292]
**Describe the bug**
When I do time range with one datepicker, the event onChange not prepared to receive an array of dates (start and end).

**To Reproduce**

1 Create a datepicker for time range with one datepicker like this 
<img width="610" alt="Screen Shot 2020-07-24 at 19 06 57" src="https://user-images.githubusercontent.com/2751058/88439209-f1b8a600-cde0-11ea-9783-8a3e3f4f3329.png">

2. get the error 
<img width="1009" alt="Screen Shot 2020-07-24 at 19 08 09" src="https://user-images.githubusercontent.com/2751058/88439247-0b59ed80-cde1-11ea-9d95-d2fdf3f9ff51.png">

**Expected behavior**
onChange parameter type enable to get an Array
<img width="664" alt="Screen Shot 2020-07-24 at 19 08 44" src="https://user-images.githubusercontent.com/2751058/88439295-2f1d3380-cde1-11ea-9958-2cd362c1a8c5.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser Chrome

**Comment by psoaresbj** [comment]
Which version are you using @randalmaia?

**Comment by williamcosta** [comment]
@psoaresbj we are using version `3.1.3`

**Comment by Maadtin** [comment]
Im having the same problem aswell And I was working with version 2.13.0, upgraded to 3.1.3 and still the same problem, its not receiving an array of dates but just a single date.

**Comment by whitexgate** [comment]
use the function toString() then split():
`onChange={(date) => {
   const arrayDate = date.toString().split(" ");
   console.log(arrayDate);
}`
**arrayDate**: this is an array of strings contains your date selected.

**Comment by anastasia-son** [comment]
How is this completed? I have the same issue

**Comment by yesk13** [comment]
@anastasia-son don't know if this is still applicable to you now. Check for typo in your props `<DatePicker selectsRange />` if you use `selectRange` you will not get an array of `Date` when calling handler in the `onChange`. I have nodejs version 12.22.12 with `react-datepicker` at version `4.25.0` and it is working fine for me.
