### ISSUE TITLE
If we want to exclude a specific range of dates for suppose between july 25 and july 30. How can we do that

### ISSUE THREAD

**Issue by abhinavthipparapu** [Hacker0x01/react-datepicker#2299]
If we want to exclude a specific range of dates for suppose between july 25 and july 30. How can we do that

**Comment by smeletis** [comment]
> If we want to exclude a specific range of dates for suppose between july 25 and july 30. How can we do that

You can use `excludeDates={[ . . . ]}` and inside the array you can generate those dates with something like date-fns.
