### ISSUE TITLE
Can't close popup programmatically

### ISSUE THREAD

**Issue by smeletis** [Hacker0x01/react-datepicker#2305]
**Describe the bug**
User can't close popup programmatically

**To Reproduce**

1. Click on any picker (a popup will show)
2. Assuming there is a cancel button, what code should that button run?

onBlur is called when the user clicks outside, but my goal is to close it programmatically. Thanks in advance!

**Comment by smeletis** [comment]
`onBlur` is called when the user clicks outside, but my goal is to close it programmatically. Thanks in advance!

**Comment by kzotoff** [comment]
First way: use refs (remember that refs are not available before picker is rendered first!)
```
datepickerRef = React.createRef();

onCloseButton = () => {
  this.datepickerRef.current.setOpen(false);
}

render() {
    return <DatePicker ref={this.datepickerRef} />;
}
```

Second way: use `open` prop (this fails sometime in `true` state):
```
render() {
    return <DatePicker open={this.state.shouldShowDatepicker} />;
}
```

**Comment by smeletis** [comment]
Thanks @kzotoff it is working as expected! I used the ref way since IMO it's a better approach to my problem.

**Comment by ningo-agilityio** [comment]
@kzotoff: 
Hi,
The open/close programmatically worked for me. But after closing by `setOpen`, the selected value was reset too.
How to prevent this unexpected reset action?

**Comment by kzotoff** [comment]
@ningo-agilityio: 
Have no idea ) If you need to remember that value I think that's a good idea to store it by yourself and restore when opening datepicker, and don't rely on component which is technically a blackbox.

**Comment by ningo-agilityio** [comment]
@kzotoff: Ok, let me check around. Thanks for your answer ^^
