### ISSUE TITLE
MonthPicker component doesn't translate months with locale

### ISSUE THREAD

**Issue by karolinakuzniewicz** [Hacker0x01/react-datepicker#2311]
**Describe the bug**
MonthPicker displays only names in English even if the locale passed as a props is different.

**To Reproduce**
Pass locale props (e.g "de") to the MonthPicker component.

**Expected behavior**
Month names are translated.

**Comment by sibstark** [comment]
The same issue. I imported globally import "date-fns/locale/ru" locale but datepicker still showing only eng months names.
