### ISSUE TITLE
Add Time picker support | ability to disable date picker and keep time only

### ISSUE THREAD

**Issue by jessypouliot98** [Hacker0x01/react-datepicker#2315]
**Is your feature request related to a problem? Please describe.**
I feel like a date/datetime picker should support a time picker.

**Describe the solution you'd like**
It would be nice to have another prop like showTimeSelect but for dates. "showDateSelect" with a default value to true. That way we could keep the same base input with same style for date, datetime and time.

**Additional context**
I am building a full custom react inputs for an open source framework/cms I am building and I want to support date, datetime and time.

**Comment by Patrick-Ullrich** [comment]
You should be able to achieve this using:

        showTimeSelect={true}
        showTimeSelectOnly={true}
