### ISSUE TITLE
calendarContainer Styling. 

### ISSUE THREAD

**Issue by 1pauling** [Hacker0x01/react-datepicker#2318]
**Describe the bug**
Calendar styles don't show up. Probably because I have issues importing 'react-datepicker/dist/react-datepicker.css';
But I get this error when i try importing the .css file. 

../node_modules/react-datepicker/dist/react-datepicker.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .react-datepicker-popper[data-placement^="bottom"] .react-datepicker__triangle, .react-datepicker-popper[data-placement^="top"] .react-datepicker__triangle, .react-datepicker__year-read-view--down-arrow,
| .react-datepicker__month-read-view--down-arrow,
| .react-datepicker__month-year-read-view--down-arrow {

**To Reproduce**

**Expected behavior**
According to all documentation and examples for this react-datepicker library. it seems very straight forward for one to plug and use this react component. 

**Screenshots**
![Screen Shot 2020-08-11 at 16 28 59](https://user-images.githubusercontent.com/18016963/89945919-1ccc3380-dbf0-11ea-99ae-cb021a81d847.png)

**Desktop (please complete the following information):**
- OS: iOS 10.13.6
- Browser: Chrome

**Additional context**
Does anyone have in depth examples/tutorial on how to custom style react-datepicker component?

**Comment by samechikson** [comment]
Looks like you need to add the `css-loader` and `style-loader` to webpack so that it can import CSS. [See here](https://webpack.js.org/loaders/css-loader/).
