### ISSUE TITLE
Time Only Picker does not keep Date on manual typing input

### ISSUE THREAD

**Issue by Patrick-Ullrich** [Hacker0x01/react-datepicker#2319]
**Describe the bug**
When using a Time Only Picker (https://reactdatepicker.com/ -> Select Time Only), the date sets to todays date once a user types into the input. 

**To Reproduce**

1. Go to https://codesandbox.io/s/react-datepicker-forked-xcmon
You will see that the date is set to tomorrow.

2. Click into the Time picker, but instead of selecting a time, start typing a valid time.
3. See that the date has been reset to todays date

**Expected behavior**
Just like when we select a time, the date should be maintained

**Screenshots**
Before: 
![image](https://user-images.githubusercontent.com/6193042/89953572-92ce9b80-dbec-11ea-8b24-00d65da86a8b.png)

After: 
![image](https://user-images.githubusercontent.com/6193042/89953584-995d1300-dbec-11ea-80d2-6a6a20ed74cc.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome 
- Version 84.0.4147.105

**Comment by aure-staffbase** [comment]
I have the same issue. @Patrick-Ullrich have you maybe found a solution/workaround?

**Comment by aure-staffbase** [comment]
As a partial workaround, for cases where a dropdown is also available, #942 provides information on how to block users from manually entering text.
