### ISSUE TITLE
Calendar gets closed when start date is selected

### ISSUE THREAD

**Issue by sumeyradavran** [Hacker0x01/react-datepicker#2333]
When using Date range for one datepicker, as soon as start date is selected, calendar gets closed.

"react": "^16.13.1",
"react-datepicker": "^3.1.3"

Is there a way to prevent this?

**Comment by prolific** [comment]
I am facing the same issue. I am using the example from the docs with the heading "[Date range for one datepicker](https://reactdatepicker.com/#example-date-range-for-one-datepicker)"

In the above example, Just remove the property inline and the issue can be reproduced. Here is the final code snippet:

```
() => {
  const [startDate, setStartDate] = useState(new Date());
  const [endDate, setEndDate] = useState(null);
  const onChange = dates => {
    const [start, end] = dates;
    setStartDate(start);
    setEndDate(end);
  };
  return (
    <DatePicker
      selected={startDate}
      onChange={onChange}
      startDate={startDate}
      endDate={endDate}
      selectsRange
    />
  );
};
```

**Problems:**

- Calendar closes automatically before allowing to select an end date. `shouldCloseOnSelect` property can be used here to resolve this but then the user has to manually close the calendar by clicking outside it. Ideally the calendar should be closed once both start and end dates are selected.
- After selecting both start and end dates, Input is not displaying them in UI. Only the start date is being displayed. 

Please let me know if any further information is needed.

**Comment by otech47** [comment]
Same issue

**Comment by ybinstock** [comment]
Same issue

**Comment by jackleblack-kpt** [comment]
Same issue

**Comment by taylorc93** [comment]
I managed to get this working by using some conditional logic with the `shouldCloseOnSelect` prop:

```js
() => {
  const [startDate, setStartDate] = useState(new Date());
  const [endDate, setEndDate] = useState(null);
  const onChange = dates => {
    const [start, end] = dates;
    setStartDate(start);
    setEndDate(end);
  };
  return (
    <DatePicker
      selected={startDate}
      onChange={onChange}
      shouldCloseOnSelect={startDate && !endDate}
      startDate={startDate}
      endDate={endDate}
      selectsRange
    />
  );
};
```

**Comment by TempD** [comment]
> I managed to get this working by using some conditional logic with the `shouldCloseOnSelect` prop:
> 
> ```js
> () => {
>   const [startDate, setStartDate] = useState(new Date());
>   const [endDate, setEndDate] = useState(null);
>   const onChange = dates => {
>     const [start, end] = dates;
>     setStartDate(start);
>     setEndDate(end);
>   };
>   return (
>     <DatePicker
>       selected={startDate}
>       onChange={onChange}
>       shouldCloseOnSelect={startDate && !endDate}
>       startDate={startDate}
>       endDate={endDate}
>       selectsRange
>     />
>   );
> };
> ```

This is the way to get the expected behavior with date ranges. This seems like a very common use case, would it be possible to add this as the example instead? I find the example on the website to be a bit misleading.

**Comment by SCasarotto** [comment]
`shouldCloseOnSelect` didn't fully work in my testing. If you select a date and then select a date before that one, the date picker will close. After realizing this, I instead went with manually controlling the closing using a `ref`. 

Programmatically closing: https://github.com/Hacker0x01/react-datepicker/issues/2055 and `shouldCloseOnSelect={false}` did the trick. 

Hope it might help others.
