### ISSUE TITLE
How can I 'invert' the direction of the months arrows while using an RTL language

### ISSUE THREAD

**Issue by only-mishmish** [Hacker0x01/react-datepicker#2336]
Hi,

I looked at 
https://github.com/Hacker0x01/react-datepicker/issues/1271
 And tried to add 

`<div dir='rtl'>`

 as described there, but it didn't work.

Is there another way to invert the behaviour of the arrows -
left --> go to next month
right --> go to previous month

many thanks!

**Comment by yohainnn** [comment]
i'm also struggling with this. seems like the dudes who developed this thing don't know the answer

**Comment by renana-kimaia** [comment]
Have you tried this: `<div dir='rtl'>` ?

**Comment by yohainnn** [comment]
like that? 
```
<div dir='rtl'>
    <DatePicker
        selected={startDate}
        onChange={date => setStartDate(date)}
        popperClassName={classes.datePopper}
        popperPlacement="bottom-center"
        dayClassName={() => classes.calendarDay}
        weekDayClassName={() => classes.weekDay}
        calendarClassName={classes.datePicker}
        customInput={<DateInput />}
        maxDate={new Date()}
        locale='he'
    />
</div>
```
not working

**Comment by bartzy** [comment]
@only-mishmish Did you manage to fix this?

**Comment by only-mishmish** [comment]
> @only-mishmish Did you manage to fix this?

Unfortunately not...
You may try to change the package code, I haven't tried.
