### ISSUE TITLE
Css / Styling not working

### ISSUE THREAD

**Issue by SimonGribert** [Hacker0x01/react-datepicker#2339]
**Describe the bug**
The styling seams to be missing, and when i click the input, all the dates just stack on top of the input. 

**To Reproduce**

1. npm install react-datepicker
2. import react-datepicker
3. Use default example from https://reactdatepicker.com/
4. Styling gone

**Expected behavior**
I expect the styling / css to work as default. 

**Screenshots**
![image](https://user-images.githubusercontent.com/69861148/90533547-f9b5fc80-e178-11ea-8501-0d357bc536c0.png)

**Desktop (please complete the following information):**

- OS: [mcOS Catalina 10.15.6]
- Browser [Chrome]
- Version [^3.1.3]

**Comment by coldapache** [comment]
Experiencing the same behavior.

**Comment by tamj0rd2** [comment]
This helped me: https://github.com/Hacker0x01/react-datepicker/issues/1707

https://github.com/Hacker0x01/react-datepicker/#installation

```typescript
import "react-datepicker/dist/react-datepicker.css";
```

**Comment by umedsondoniyor** [comment]
> This helped me: #1707
> 
> ```ts
> import "react-datepicker/dist/react-datepicker.css";
> ```
> 
> https://github.com/Hacker0x01/react-datepicker/#installation

Still css not working :(

**Comment by emmanuelay** [comment]
Im experiencing the same issue. I have added the import of the css-file according to the installation-procedure.
This is the error I get:

```
./node_modules/react-datepicker/dist/react-datepicker.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-datepicker/dist/react-datepicker.css)
BrowserslistError: Unknown browser query `ios_saf undefined`. Maybe you are using old Browserslist or made typo in query.
    at Array.reduce (<anonymous>)
    at Array.some (<anonymous>)
    at Array.filter (<anonymous>)
```

**Comment by emmanuelay** [comment]
> > This helped me: #1707
> > ```ts
> > import "react-datepicker/dist/react-datepicker.css";
> > ```
> > 
> > 
> > https://github.com/Hacker0x01/react-datepicker/#installation
> 
> Still css not working :(

I had the same issue. Im guessing you ran the npm install procedure, included the css & import in your jsx and then just saved to see changes?

Try restarting the npm script, everything worked as expected for me.
