### ISSUE TITLE
New release of react-onclickoutside breaks datepicker

### ISSUE THREAD

**Issue by tquetano-r7** [Hacker0x01/react-datepicker#234]
react-onclickoutside just released 4.2.0 sometime earlier today, and it appears to be a bug there (the error is "root is not defined", and since react-datepicker relies on compatible versions of 4.0.1, you may want to do something like >=4.0.1 <4.2.0 until the bug there is fixed.

**Comment by uniphil** [comment]
This was just fixed in 4.3.0: https://github.com/Pomax/react-onclickoutside/issues/51

Should we switch the dependency back to a `^` range on `4`, or another range that still specifically excludes `4.2.0`?

**Comment by martijnrusschen** [comment]
SGTM

**Comment by uniphil** [comment]
Cool, revert in a PR at #236

**Comment by martijnrusschen** [comment]
merged

**Comment by uniphil** [comment]
thanks!

**Comment by martijnrusschen** [comment]
Merged a PR to updates this plugin to the latest version. Didn't see any problems here anymore.(https://github.com/Hacker0x01/react-datepicker/commit/1f88061db37c4a5050199b6d5a5bba850be19e8c)
