### ISSUE TITLE
react-datepicker__day--selecting-range-end not set on date range with only one datepicker

### ISSUE THREAD

**Issue by mihaibogdan** [Hacker0x01/react-datepicker#2349]
**Describe the bug**
It seems dat css class react-datepicker__day--selecting-range-end it's not set correctly on the "Date range for one datepicker"

**To Reproduce**

1. Go to a range calendar with one date picker
2. Select start date
3. Hover on a second date
4. react-datepicker__day--selecting-range-end class is not applied.

**Screenshots**

![image](https://user-images.githubusercontent.com/6225068/90878440-30288d00-e3ae-11ea-961f-f30c87efebe7.png)

- OS: macOS Catalina
- Browser Chrome
- Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by markpalantoni** [comment]
Still a problem and here's a hacky solution: use a ref in `renderDayContents` component to set the parent class correctly.

NOTE: This code is just an idea to get started it doesn't have all the required logic and props.

```<ReactDatePicker
  onDayMouseEnter={date => {
    setRangeSelectionEndDate(date);
  }}
  renderDayContents={() => {
    return <CalendarDay isRangeSelectionEndDate={isRangeSelectionEndDate} dayOfMonth={dayOfMonth} />;
  }}
  selectsRange
/>;

const CalendarDay = ({ dayOfMonth, isRangeSelectionEndDate }) => {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const element = ref.current;

    if (!element) return;

    const datePickerElement = element.parentElement;

    if (!datePickerElement) return;

    if (isRangeSelectionEndDate) {
      datePickerElement.classList.add('react-datepicker__day--selecting-range-end');
    } else {
      datePickerElement.classList.remove('react-datepicker__day--selecting-range-end');
    }
  }, [isRangeSelectionEndDate]);

  return <div>{dayOfMonth}</div>;
};
```
