### ISSUE TITLE
For the dateFormat = mm/yyyy calendar (month year) can you enable year dropdown

### ISSUE THREAD

**Issue by LJ-837194** [Hacker0x01/react-datepicker#2365]
**Is your feature request related to a problem? Please describe.**
The month and year calendar does not have an dropdown option for the year. User has to click 10 times to bo back 10 year back in the calendar widget.

**Describe the solution you'd like**
The year dropdown feature is present for the dd/mm/yyyy calendar. A similar implementation for the month- year calendar as well. It will be great feature to be added.

**Comment by Svish** [comment]
@LJ-837194 Does the `showYearDropdown` prop work for this? Looking at the documentation to consider using this library, and had your issue in the back of my mind, since we also need a month-year-picker.

https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md
