### ISSUE TITLE
Accessibility issue of time picker 

### ISSUE THREAD

**Issue by devangpatel21** [Hacker0x01/react-datepicker#2367]
**Describe the bug**
cannot choose a time with tab click I don't have tab index = 0

**To Reproduce**

1. Select date picker with time 
2. open picker through the keyboard and go to time picker to choose the time 
3. Won't be able to pick time through the keyboard

**Expected behavior**
time should also able to be picked  through the keyboard

**Comment by kennygrubb** [comment]
Yes this is an issue for me as well. Thanks

**Comment by lpelypenko** [comment]
Trying to fix this issue in https://github.com/Hacker0x01/react-datepicker/pull/2566. 
Please vote for my fix, hopefully, it will help to release it faster.
