### ISSUE TITLE
Z index issue with Material theme

### ISSUE THREAD

**Issue by shaheeralimm** [Hacker0x01/react-datepicker#2369]
**Z Index**
When using with the Material table some parts of the picker hidden inside the Material table. Please check the screen shot for reference.

[https://material-ui.com/customization/z-index/](url)

![image](https://user-images.githubusercontent.com/30893632/91853273-969b8e00-ec7f-11ea-9674-ba6d5868281c.png)

**Comment by aymansaafan** [comment]
Try adding css class to the material-ui component with the property **z-index: 0;**
