### ISSUE TITLE
consider removing the carat from your dependencies

### ISSUE THREAD

**Issue by shackbarth** [Hacker0x01/react-datepicker#237]
At the moment this package is breaking my Babel6/Browserify build, because of a bug in 
https://github.com/Pomax/react-onclickoutside
which has been fixed in github but which nevertheless won't be available until Pamax publishes 4.4.0 to npm. 

I'd prefer not to worry about Pomax's npm publishing schedule. If you'd locked your dependency with `--save-exact` or the like, your package -- and by extension my build -- would be more stable.

I know everyone loves semver, but still...

**Comment by ntdb** [comment]
+1

**Comment by martijnrusschen** [comment]
Pinned the version again. Should resolve the issue

**Comment by shackbarth** [comment]
Great, thanks! But please consider not readopting the carat as soon as `react-onclickoutside` is fixed on npm. There's nothing I like better than knowing that my build is going to work tomorrow as well as it works today if I don't mess anything up.

**Comment by martijnrusschen** [comment]
Same here, I'll make sure this double checked next time. Looks like react-onclickoutside upgraded to babel6 and might cause some issues here.
