### ISSUE TITLE
Thai Year

### ISSUE THREAD

**Issue by goodlythink** [Hacker0x01/react-datepicker#2372]
Thai Year

**Comment by dominicgan** [comment]
Setting the locale in this component does not convert the year representation from Gregorian (2020) to Buddhist year (2563) when setting the component to Thai locale (th)

**Current**
![image](https://user-images.githubusercontent.com/7966311/94050284-a171ba80-fe08-11ea-8aa5-3eaad9d43a21.png)

**Expected**
![image](https://user-images.githubusercontent.com/7966311/94050339-b3ebf400-fe08-11ea-9717-050195095f3e.png)

Some context from wikipedia: https://en.wikipedia.org/wiki/Thai_calendar

**Comment by goodlythink** [comment]
please example code in codesanbox

**Comment by sirisakc** [comment]
> Setting the locale in this component does not convert the year representation from Gregorian (2020) to Buddhist year (2563) when setting the component to Thai locale (th)
> 
> **Current**
> ![image](https://user-images.githubusercontent.com/7966311/94050284-a171ba80-fe08-11ea-8aa5-3eaad9d43a21.png)
> 
> **Expected**
> ![image](https://user-images.githubusercontent.com/7966311/94050339-b3ebf400-fe08-11ea-9717-050195095f3e.png)
> 
> Some context from wikipedia: https://en.wikipedia.org/wiki/Thai_calendar

Please example code how to do  Buddhist year (2563).
