### ISSUE TITLE
locale issue?

### ISSUE THREAD

**Issue by qw110946** [Hacker0x01/react-datepicker#2374]
![EBC7A0C9-3A2E-4897-BBBE-9F1BFFC50464](https://user-images.githubusercontent.com/26341956/92227463-e6c15d00-eed8-11ea-977e-34994a518737.png)

**Comment by jaymdq** [comment]
Having the same problem

**Comment by MickMonaghan** [comment]
Duplicated by #2502 , #2503

**Comment by capsule5** [comment]
> Duplicated by #2502 , #2503

so where is it discussed?

**Comment by qw110946** [comment]
Resolved
`<DatePicker timeCaption="string"/>`
