### ISSUE TITLE
Today's day is highlighted for every motnth

### ISSUE THREAD

**Issue by ao-alex** [Hacker0x01/react-datepicker#2376]
**Describe the bug**
Todays date is highlighted on every month
**To Reproduce**
1. Go to  the demo page
2.  Open any calendar, and change months notice that today's date is highlighted on every month

**Expected behavior**
Should only highlight only current date.  

**Screenshots**
<img width="289" alt="Screen Shot 2020-09-04 at 18 51 33" src="https://user-images.githubusercontent.com/55664544/92252747-b7621e80-eedf-11ea-924b-8619a16b05e9.png">
<img width="256" alt="Screen Shot 2020-09-04 at 18 52 26" src="https://user-images.githubusercontent.com/55664544/92252808-ccd74880-eedf-11ea-9b7d-fae44f840de3.png">

**Comment by mariusGundersen** [comment]
I have the same problem, it's annoying as it looks like changing the month changes the value, but it does not. It's the same when using the `showYearDropdown` and `showMonthDropdown`; picking a year or month from the dropdowns does not update the value, but changes the calendar view and higlights todays date.

**Comment by damonbauer** [comment]
This has something to do with [`isKeyboardSelected`](https://github.com/Hacker0x01/react-datepicker/blob/d2d7135ee3c7b239bccc49ec49440850c1cf5d7c/src/day.jsx#L81) in `Day.jsx`.

On date pickers that have a `value` set, the issue occurs (for instance: [Default](https://reactdatepicker.com/#example-default)).
On date pickers that do not have a `value` set, the issue **does not** occur (for instance: [Date Range with disabled navigation shown](https://reactdatepicker.com/#example-date-range-with-disabled-navigation-shown))

**Comment by dennisat** [comment]
Same here... any progress?

**Comment by dennisat** [comment]
Debugging this I realized that this is not actually a bug.
The colour of the selected date on other months is different. That's the colour of the **keyboard** selection.

Of course, it looks like a bug... ideally this color should be completely different, or shouldn't be not a solid colour.

A quick fix is to `disabledKeyboardNavigation` if you don't interested in keyboard date selection.

**Comment by hwkiem** [comment]
IS this resolved?

**Comment by JohnDDuncanIII** [comment]
per-https://github.com/Hacker0x01/react-datepicker/issues/2872#issue-853667583, I was able to fix this in my range datepicker by manually passing `disabledKeyboardNavigation`/`minDate={null}`

https://user-images.githubusercontent.com/9257785/158491032-b78f959d-6956-4a80-aa56-09d685787c46.mov

first example in vid is the default `minDate` (i.e., not passing the prop down at all)
second example is `minDate={null}` behavior

**Comment by isaac-wahba** [comment]
Hello guys 

Any solution for the month case? 
I am facing the same issue with the MM/yyyy, and I tried the following: 

1. Solving it with css.
2. disabledKeyboardNavigation

But it is not solved yet.  I still see the selected month in each year.

Any recommendations? @JohnDDuncanIII  @damonbauer  @mariusGundersen @ao-alex

**Comment by khnbzkrt** [comment]
Worked sass code for me. 


```sass
&--selected,
  &--keyboard-selected {

    color: black;
    background-color: inherit !important;

    @at-root #{&} {
      &.react-datepicker__day--today {
        color: #fff;
	background: $color-secondary-400 !important;
    }

  }
}
```
