### ISSUE TITLE
need a filterTime feature

### ISSUE THREAD

**Issue by Riba-Kit** [Hacker0x01/react-datepicker#2378]
Hi! In my project I need to filter times in time-picker select-list. It would be nice if I can use filterTime just as filterDate.

**Comment by alanunesouza** [comment]
I also have the same problem ... I need to set the time range per day and I had to look for another alternative.

**Comment by Jonofat** [comment]
> I also have the same problem ... I need to set the time range per day and I had to look for another alternative.

Did you find something else? I want to be able to choose different time options for weekdays and different time options for weekends.

**Comment by ArchanaSharma95** [comment]
I am having same issue, I want to disable the past time using "filterTime" prop. Please suggest if you find any other solution.

**Comment by saltire** [comment]
Hey folks, there is a filterTime property now, merged from PR #2420.

https://reactdatepicker.com/#example-filter-times

**Comment by ymh357** [comment]
I copied exactly the same code from the example, but it not works as expected. Date larger than today still applies the filter.

`const filterPassedTime = time => {
    const currentDate = new Date();
    const selectedDate = new Date(time);

    return currentDate.getTime() < selectedDate.getTime();
  } `

I want only the time before today to be disabled, not after today. Could you please have a look?

**Comment by Riba-Kit** [comment]
> > I also have the same problem ... I need to set the time range per day and I had to look for another alternative.
> 
> Did you find something else? I want to be able to choose different time options for weekdays and different time options for weekends.

I was generated full list of times instead of filtering) but I see that something was merged

**Comment by Riba-Kit** [comment]
> Hey folks, there is a filterTime property now, merged from PR #2420.
> 
> https://reactdatepicker.com/#example-filter-times

Thanks a lot! how can I close this issue?

**Comment by ishvar-kanajariya** [comment]
> I copied exactly the same code from the example, but it not works as expected. Date larger than today still applies the filter.
> 
> `const filterPassedTime = time => {
> const currentDate = new Date();
> const selectedDate = new Date(time);
> 
> ```
> return currentDate.getTime() < selectedDate.getTime();
> ```
> 
> } `
> 
> I want only the time before today to be disabled, not after today. Could you please have a look?

Try this one!
  filterPassedTime = (time: any) =>{
    const currentDate = new Date(time);
    const selectedDate = this.state.selectedDate; 
    if (selectedDate.getDate() === new Date().getDate()) {
      return currentDate.getTime() > selectedDate.getTime();
    }
    return currentDate.getTime() < selectedDate.getTime();
  }
