### ISSUE TITLE
Uncaught Error: Cannot find module '[object Object]' after reinstalling package

### ISSUE THREAD

**Issue by angelinacc** [Hacker0x01/react-datepicker#238]
So I removed react-datepicker package to reinstall it again today. However, I am now getting this error:

Uncaught Error: Cannot find module '[object Object]'

and also noticed that moment is missing from node_modules under this package, not exactly sure why and wanted some insight. It was working before until I removed it.

This is my dependencies in my package.json:
    "react": "0.14.2",
    "react-dom": "0.14.2",
    "react-datepicker": "0.15.2",
    "moment": "2.10.6"

**Comment by kirev** [comment]
you need to add this "react-onclickoutside":"4.1.1" it's seems the component has another version that is the problem 

"react": "0.14.2",
"react-dom": "0.14.2",
"react-datepicker": "0.15.2",
"moment": "2.10.6",
"react-onclickoutside":"4.1.1"

let me know

**Comment by martijnrusschen** [comment]
I downgraded react-onclickoutside to make sure it doesn't fail anymore.

**Comment by angelinacc** [comment]
Looks like the issue is resolved, thanks guys.
