### ISSUE TITLE
Is there a way to close a calendar by clicking the DatePicker again?

### ISSUE THREAD

**Issue by ygnoh** [Hacker0x01/react-datepicker#2381]
Hi all, I'm using 1.5.0.

By clicking DatePicker, a calendar is open. However when I click it again, it looks like that doesn't close.
Only the way to close the calendar is clicking outside of DatePicker or a date in the calendar.
Am I right? Is there a way to close a calendar by clicking the DatePicker again?

**Comment by AlanJereb** [comment]
I have solved the same problem by adding a boolean toggle in the state and using a customInput component. 

In customInput component I check:
![slika](https://user-images.githubusercontent.com/24469472/92564134-fa721800-f278-11ea-9764-97f19b021941.png)
