### ISSUE TITLE
When picking the second date, the DatePicker scrolls back to the first date selection

### ISSUE THREAD

**Issue by lorenzosjb** [Hacker0x01/react-datepicker#2388]
Hi, I have an inline that doesn't close DatePicker that selects a range of dates. When pressing the second date, the component automatically returns to the first date selected. 

Is there a way to avoid this behavior and when selecting the second date?

<DatePicker
        minDate={addDays(new Date(), 2)}
        openToDate={addDays(new Date(), 2)}
        showPopperArrow={false}
        onChange={(date): void => {
          onDateChange(date);
        }}
        monthsShown={1}
        placeholderText="dates"
        value={customValue}
        inline={true}
        shouldCloseOnSelect={false}
      />

Thanks.

**Comment by diasqazaqbro** [comment]
@lorenzosjb Have you fixed it? I have been struggling with same kind of issue.

**Comment by lorenzosjb** [comment]
> @lorenzosjb Have you fixed it? I have been struggling with same kind of issue.

No, I havent found the fix.
