### ISSUE TITLE
How to use multiple date pickers in a table

### ISSUE THREAD

**Issue by richardcao27** [Hacker0x01/react-datepicker#2390]
I am trying to render a data picker for each row of my table as shown. Each row has a published date. I want to be able to update the publish date for each row.
<img width="881" alt="Screen Shot 2020-09-14 at 5 24 18 PM" src="https://user-images.githubusercontent.com/54082143/93150874-28a78b80-f6af-11ea-9efc-c9b4374fb616.png">

However I get the issue that the updated date are not rendered when selected (shows the same old date on the screen).

Here's my code:
<img width="683" alt="Screen Shot 2020-09-14 at 5 25 12 PM" src="https://user-images.githubusercontent.com/54082143/93150941-4e349500-f6af-11ea-8c04-bc1fd6fa9f5c.png">

Is this the right approach to rendering multiple data pickers?

Thanks

**Comment by AlanJereb** [comment]
How does your handleDateChange work?

**Comment by ch3tan03** [comment]
any update on this?
