### ISSUE TITLE
openToDate does not select the time

### ISSUE THREAD

**Issue by iweber-coder** [Hacker0x01/react-datepicker#2391]
**Describe the bug**
Hi!

I would like the DatePicker to open with current date and current time + 1 hour (rounded to the nearest half an hour, since the timeIntervals are 30 minutes). E.g. if now is 09/15/2020 2:43PM, I would like it to open on 09/15/2020 3:30PM.
I did not find a way to do it. I was hoping openToDate could be used for that, but it does not set the time, only the date. And there is no openToTime prop.
What would be the easiest way to achieve that?

**To Reproduce**
`const defaultDate = addHours(new Date(), 1);`
`defaultDate.setMilliseconds(Math.round(defaultDate.getMilliseconds() / 1000) * 1000);`
`defaultDate.setSeconds(Math.round(defaultDate.getSeconds() / 60) * 60);`
`defaultDate.setMinutes(Math.round(defaultDate.getMinutes() / 30) * 30);`

`                      <DatePicker
                            showTimeSelect={true}
                            timeFormat="HH:mm"
                            timeCaption="Time"
                            openToDate={defaultDate}
                        />`

**Expected behavior**
Either to have openToTime prop or openToDate should set the time as well, if it is enabled.

**Desktop (please complete the following information):**

- macOS
- Chrome
- Version 85.0.4183.102

**Comment by siddarth-compass** [comment]
Yes we too need a fix for the same
