### ISSUE TITLE
showMonthYearPicker doesn't hightlight current month

### ISSUE THREAD

**Issue by Upskxkit** [Hacker0x01/react-datepicker#2392]
**Describe the bug**
when you set showMonthYearPicker to select month, it doesn't mark current month. If compare with date 
![image](https://user-images.githubusercontent.com/19734355/93347449-c335d500-f83d-11ea-93fa-d7c6c9b1fba3.png)
![image](https://user-images.githubusercontent.com/19734355/93347569-e6f91b00-f83d-11ea-9ff2-a639b998eec9.png)

how to handle such situation? or can you fix it?

**Comment by malutka** [comment]
Class _.react-datepicker__month-text--today_ is missing - can we add this class somehow, or we need to wait for fix?

**Comment by malutka** [comment]
what about this issue? Are you going to fix it?
