### ISSUE TITLE
Keep The Picker Open Always

### ISSUE THREAD

**Issue by ellismarte** [Hacker0x01/react-datepicker#2393]
Would be nice if you could pass a prop to keep the picker open always, is this already a thing?

**Comment by AlanJereb** [comment]
You are lucky! It already is a thing.

Just use prop
`inline={true}`
or even shorter
`inline` - as it defaults to true.

**Comment by brojd** [comment]
Is there a way to not hide input when using `inline={true}`? So to have both calendar and input at the same time?

**Comment by brojd** [comment]
Ok, I can see we can use `open` prop

**Comment by ricardo-rp** [comment]
@brojd Did it work by just passing both `inline` and `open` as `true`? I cannot get it to be open by default and stay open, even by doing that.

**Comment by ricardo-rp** [comment]
Just to clarify, passing `open={true}` and not passing inline allows to have both the input and calendar visible at the same time.
