### ISSUE TITLE
get the actual date user entered along with date objects...

### ISSUE THREAD

**Issue by yaswanthmaddula-sureify** [Hacker0x01/react-datepicker#2394]
**Is your feature request related to a problem? Please describe.**
**Use case** : Make a network call after user completely enters the date. 
**Problem and Request** : Currently through onChange event, we can get the date object. A date object is automatically derived even though the user didn't enter the date completely. But in my use case here , I need to make a network call once the user enters the complete date.. 

**Describe the solution you'd like**
It would have been better if I get what the user actually entered , so that I can check the input length and confirm that the user completely entered the date and then make a network call. There is event for `onSelect` but that `event.target.value` gives me`undefined`

**Describe alternatives you've considered**
Currently I didn't find any good alternative. If I use rawInputChange for the same, it conflicts with the calender input.

**Comment by rsshilli** [comment]
I found a workaround. The original event is passed in as the second argument (most of the time).
```
  <DatePicker onChange={this.handleChange} ... />

...

  handleChange(parsedDate, event) {
    console.log("Parsed JS Date object:", parsedDate);
    console.log("Text typed in by user:", event.target.value);
  }
```
