### ISSUE TITLE
Calendar not closing on selection of a date

### ISSUE THREAD

**Issue by ItzaMi** [Hacker0x01/react-datepicker#2395]
I've seen this [issue](https://github.com/Hacker0x01/react-datepicker/issues/1012#) but it doesn't seem to offer any solution to my problem.

Recently I picked up a project that uses `react-datepicker` and there's an issue where the calendar just isn't closing on selection of a date. Here's a gif showcasing that
![reactdatepicker](https://user-images.githubusercontent.com/30603437/93449507-bca26e80-f8cc-11ea-8ff4-44d3878d3829.gif)

My DatePicker component is here
```
const DatePicker: FC<Props> = ({
  label,
  icon,
  date,
  onChange,
  minDate,
  maxDate,
  selectsStart,
  selectsEnd,
}) => {
  const dateObj = useMemo(() => (date ? date.toDate() : null), [date])
  const minDateObj = useMemo(() => (minDate ? minDate.toDate() : null), [
    minDate,
  ])
  const maxDateObj = useMemo(() => (maxDate ? maxDate.toDate() : null), [
    maxDate,
  ])

  return (
    <div className={css.host}>
      <div className={css.label}>{label}</div>
      <label className={`${css.wrapper}`}>
        {icon}
        <ReactDatePicker
          selected={dateObj}
          className={css.input}
          calendarClassName={css.calendar}
          showTimeSelect
          dateFormat="dd/MM/yyyy h:mm aa"
          onChange={(newDate: Date, e) => {
            if (newDate) {
              const momentDate = moment(newDate)
              onChange(momentDate)
            }
          }}
          startDate={minDateObj}
          endDate={maxDateObj}
          minDate={minDateObj}
          maxDate={maxDateObj}
          selectsStart={selectsStart}
          selectsEnd={selectsEnd}
          showPopperArrow={false}
          popperModifiers={{
            offset: {
              enabled: true,
              offset: '-28px, 4px',
            },
          }}
          renderCustomHeader={customHeader}
        />
      </label>
    </div>
  )
}
```

And it's being used here
```
<div
      className={css.host}
      onKeyUp={(evt) => {
        if (evt.keyCode === 13) {
          onSearch({ startDate, endDate, text })
        }
      }}
    >
      <DatePicker
        id="startDate"
        label="Start date"
        icon={<DateStartIcon width={16} height={16} />}
        date={startDate}
        maxDate={endDate}
        onChange={(newDate: Moment) => {
          setStartDate(newDate)
        }}
        selectsStart
      />
</div>
```

Inside my `ReactDatePicker` I tried to set the `onChange` like so
```
onChange={(newDate: Date, e) => {
    if (newDate) {
        if (e && typeof e.preventDefault === 'function') {
            e.preventDefault();
        }
        const momentDate = moment(newDate)
        onChange(momentDate)
    }
}}
```

I'm not sure what else I can do here so any help would be great!

**Comment by tx-paola** [comment]
same issue

**Comment by notAro14** [comment]
Same issue. But I found out that it is happening when the component is **enclosed in the label component**

### This does not work
```jsx
<label>
  Text label
  <Datepicker />
</label>
```

### This works
```jsx
<label>Text label</label>
<Datepicker />
```

I don't know why exactly it is working like that

**Comment by xyzzyxyzzy0077** [comment]
This issue needs to be addressed. Date picker should belong to a label in a form

**Comment by ujjaldey** [comment]
> Same issue. But I found out that it is happening when the component is **enclosed in the label component**
> 
> ### This does not work
> ```js
> <label>
>   Text label
>   <Datepicker />
> </label>
> ```
> 
> ### This works
> ```js
> <label>Text label</label>
> <Datepicker />
> ```
> 
> I don't know why exactly it is working like that
> 
> ### EDIT
> This [solution](https://github.com/Hacker0x01/react-datepicker/issues/1012#issuecomment-735342311) worked for me. Even if the Datepicker is wrapped inside label

@notAro14 - Thanks! This worked!!
