### ISSUE TITLE
customInput property is not working anymore

### ISSUE THREAD

**Issue by PsykoSoldi3r** [Hacker0x01/react-datepicker#2397]
**Describe the bug**c
customInput property is not working anymore and is resulting into the following error: ```undefined is not an object (evaluating 'c.props.className)```

**To Reproduce**
react-datepicker: v3.1.3
Here is a simple snippet that can be used to reproduce with Typescript (4.0.2)
```typescript
            <ReactDatePicker
                selected={ new Date() }
                onChange={date => this.onChangeDate(date)}
                customInput={ ({ value, onClick }) => ( <input value={ value } onClick={ onClick } /> ) }
            />
```

**Expected behavior**
The custom input field working as defined in the customInput property.

**Screenshots**
<img width="619" alt="image" src="https://user-images.githubusercontent.com/2241262/93607838-25bbdc00-f9ca-11ea-9d5b-cab5309c7edc.png">

**Desktop (please complete the following information):**
- OS: macOS 10.15.6
- Browse: Safari, Google Chrome
- Version: 14.0, 85.0.4183.102

**Comment by pedro-lb** [comment]
Same error here

**Comment by Psvensso** [comment]
Got it to work with some **workaround**s for now, thought i'd just share them.


First it requires an instantiated component. 
``` 
const CustomComp = ({ value, onClick }) => ( <input value={ value } onClick={ onClick } /> );
<ReactDatePicker
                selected={ new Date() }
                onChange={date => this.onChangeDate(date)}
                customInput={<CustomComp  />}
            />
```

This gave me some ref errors in the console so wrapped mine in a forwardRef as well. 
```

const CustomComp = forwardRef(({ value, onClick }, ref) => ( <input ref={ref} value={ value } onClick={ onClick } /> ));
<ReactDatePicker
                selected={ new Date() }
                onChange={date => this.onChangeDate(date)}
                customInput={<CustomComp  />}
            />
```

I got another component so just threw together this from your code so its probably not compiling but you get the idea. 

I think the customInput requires a overhaul so its more robust as well.

**Comment by tlehtimaki** [comment]
Is the error perhaps originating from this https://github.com/Hacker0x01/react-datepicker/blob/master/src/index.jsx#L924?

**Comment by mmarshad** [comment]
I'm having the same issue, can't edit the value from custom input field. soon you start typing, after first character the focus goes to body
