### ISSUE TITLE
Custom day names

### ISSUE THREAD

**Issue by retrofox** [Hacker0x01/react-datepicker#2398]
**Describe the solution you'd like**
I'd like to be able to set the shape of the day names in the header. Although it's possible to change the day names using a locale, it isn't possible (AFAIK) to change the format in the names, something like the following:

![image](https://user-images.githubusercontent.com/77539/93610274-3d339e80-f9a3-11ea-9fdd-1fb09d9f0eff.png)

**Comment by keeko20** [comment]
try this:

<DatePicker
        formatWeekDay={(day) => day.slice(0, 3)}
 />
