### ISSUE TITLE
Enter invalid date "423432/324324/324324" and press enter still the date picker picks some invalid date

### ISSUE THREAD

**Issue by shivanagowda** [Hacker0x01/react-datepicker#2399]
If I enter invalid date which some random numbers like "423432/324324/324324" and press enter still the date picker auto selects some date.

**To Reproduce**
1.Go to https://reactdatepicker.com/ 
2.enter some random numbers on date picker input ex: '"423432/324324/324324"
3. Date picker auto selects date to 01/01/42343 

**Expected behavior**
It should clear the invalid date

**Screenshots**
![invalidenter](https://user-images.githubusercontent.com/1989081/93666688-d21ac280-fa9d-11ea-946d-ccb6e36f5a9e.JPG)
![autoselecteddate](https://user-images.githubusercontent.com/1989081/93666693-d810a380-fa9d-11ea-966d-f19b8cb0e75b.JPG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AlanJereb** [comment]
Test the input with the date-fns solution (which is integrated in react-datepicker)
`isValid(input);`
[https://date-fns.org/v1.9.0/docs/isValid](url)

If you you get "false" returned, substitute input with an empty string.

**Comment by lamhungypl** [comment]
> Test the input with the date-fns solution (which is integrated in react-datepicker)
> `isValid(input);`
> [https://date-fns.org/v1.9.0/docs/isValid](url)
> 
> If you you get "false" returned, substitute input with an empty string.

How to test input when losing focus.
I use `strictParsing`, date picker force to last valid value if input get weird value

**Comment by AlanJereb** [comment]
> 
> How to test input when losing focus.
> I use `strictParsing`, date picker force to last valid value if input get weird value

I believe returning the previous valid value is the right way to go if you lost focus. 
However, if you want to return an empty input field when losing focus, I would suggest doing the isValid(input) check on blur.

**Comment by lamhungypl** [comment]
@AlanJereb  In that invalid case, I wanna show an error message and force ether typing with valid input format or delete all character.
`onBlur` not prevent Datepicker falling to the previous value
