### ISSUE TITLE
Provided id is not rendered on the input element

### ISSUE THREAD

**Issue by xabikos** [Hacker0x01/react-datepicker#240]
When using the datepicker I am passing an id and after diving into the code it should rendered in the underlying input component something that is not happening. 
[Here](http://1drv.ms/1kReSzS) is a simple example that demonstrates that. The code is simple and I can't see why this happening.

**Comment by tiffting** [comment]
I'm having a problem with this, too. This bug prevents me from associating a `<label>` with the datepicker for a11y.

**Comment by martijnrusschen** [comment]
Are you sure? I just tried to reproduce this, but it worked fine for me:

```
        <DatePicker
          selected={this.state.startDate}
          onChange={this.handleChange}
          id=1 />
```

**Comment by martijnrusschen** [comment]
Could you try to latest version (0.16.0), this should resolve your issue.

**Comment by tiffting** [comment]
We could not successfully upgrade to 0.16.0, so this isn't a solution right now. Our project fails to find react-datepicker when we try to upgrade.

**Comment by martijnrusschen** [comment]
Please try 0.16.1. 0.16.0 contained some errors.

**Comment by xabikos** [comment]
I just upgraded to 0.16.1 and I can see the id is populated correctly. Thanks a lot @martijnrusschen

**Comment by martijnrusschen** [comment]
Awesome!

**Comment by tiffting** [comment]
Same here. Thanks, @martijnrusschen!
