### ISSUE TITLE
Leave the date management library selection on the user's side

### ISSUE THREAD

**Issue by fresk-nc** [Hacker0x01/react-datepicker#2402]
**Is your feature request related to a problem? Please describe.**
I have several projects that use different libraries to manage dates, but react-datepicker forces me to use date-fns.

**Describe the solution you'd like**
What about a solution like material-ui-pickers - https://material-ui-pickers.dev/getting-started/installation#peer-library
They are providing interfaces for moment, date-fns, luxon and dayjs.

**Comment by raynor85** [comment]
Shut up bot, this issue is a must have and cannot be ignored by you or anyone else!

**Comment by L-U-C-K-Y** [comment]
Strongly agree that this would be a huge win!

**Comment by rhengeveld** [comment]
From what I could find, `moment` was tossed out in favour of `date-fns` with #382 and #1527 halfway 2020. 

Since this issue has been open since end 2020, this means there is no interest whatsoever in making the change to [date-io](https://github.com/dmtrKovalenko/date-io)?

**Comment by gracefullight** [comment]
I hope we can choose another the date library to mange time.

**Comment by bradlocking** [comment]
Agreed that it should be down to the project to decide which date management system any date picker should operate with. Could be a bottleneck for projects that are already using a date tool other than date-fns and are hesitant to include date-fns in their bundle too.

**Comment by mohsensaremi** [comment]
Strongly agree that this would be a huge win!
