### ISSUE TITLE
monthClassName prop does not work

### ISSUE THREAD

**Issue by rago4** [Hacker0x01/react-datepicker#2407]
**Describe the bug**
Maybe I'm missing some context but it seems like `monthClassName` prop doesn't work 🤔

**To Reproduce**

1. Go to https://codesandbox.io/s/competent-rain-9rk2s
2. Check the date picker and console

**Expected behavior**
Date picker should apply `current-month` class to the element representing current month. Also, console should log `{ isSameMonth: true/false }` values

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.3
- Browser: chrome
- Version: 85.0.4183.102 (Official Build) (64-bit)

BTW Thank you for this lib and your hard work 🙇‍♂️

**Comment by ogaston** [comment]
Hi @rago4, You're right.

It seems that this property is not being currently used inside the Month component.

I could fix that.
