### ISSUE TITLE
Time Format?

### ISSUE THREAD

**Issue by tcagkansokmen** [Hacker0x01/react-datepicker#2408]
Hi there,

Is there any time format there?
It only gives 12 hours format with AM/PM.
I need 24 hours format without am/pm.

**Comment by AlanJereb** [comment]
As mentioned in the documentation.
Using this property, you can format time:
```timeFormat="HH:mm"```

**Comment by kasugaicrow** [comment]
@AlanJereb it does not actually work, I mean if you type `16` it's auto changed to `04`. This option adds the zero so instead of `4` you'll indeed have `04`

**Comment by AlanJereb** [comment]
> 
> 
> @AlanJereb it does not actually work, I mean if you type `16` it's auto changed to `04`. This option adds the zero so instead of `4` you'll indeed have `04`

Before pressing thumbs down, please verify. Below is the screenshot directly from their example website that shows it working...
![slika](https://user-images.githubusercontent.com/24469472/95304578-21763680-0885-11eb-8168-0831de7ebaa5.png)

**Comment by kasugaicrow** [comment]
That's a sort of workaround which only works in Firefox, check it in Chrome, it does not work

**Comment by AlanJereb** [comment]
> 
> 
> That's a sort of workaround which only works in Firefox, check it in Chrome, it does not work because this option in the docs does not actually correct this beheviour

I see, you are correct. I have not noticed this, as I have implemented a custom time input component, which parses time using a custom logic.
![slika](https://user-images.githubusercontent.com/24469472/95310654-f2fc5980-088c-11eb-8ae8-766596261d46.png)

**Comment by kasugaicrow** [comment]
Oh, you have opted for the custom implementation, cool. Hope they will add this option since other people #2424 are requesting it
