### ISSUE TITLE
How to deselect day and refresh calendar programatically when the date changes

### ISSUE THREAD

**Issue by kevinmamaqi** [Hacker0x01/react-datepicker#2411]
**Describe the bug**
I have inserted a button into the calendar dropdown, below it. It sets the date to Today, but although the date changes, the calendar doesn't view update/refresh, as seen in the following video: https://streamable.com/wegzhy

**To Reproduce**
Create a button or function to programatically change the date when the calendar is open. Change it.

**Expected behavior**
1. The selected day, should be the only one visible.
2. The month/year... etc should bring to the selected day.

**Screenshots**
https://streamable.com/wegzhy

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome Latest

**Comment by nthurnau** [comment]
I am seeing and dealing with this same issue, minus the use of a "Today" button - has any progress been made on this?

**Comment by soulchainer** [comment]
I'm also experiencing the same. When you update the date of one calendar from outside the component, it doesn't updates properly, till you, as example, trigger a `onBlur` event.

Firefox Developer last version, Arch Linux, so this is OS/browser independent.

**Comment by yshapo** [comment]
Also experienced a similar issue. Basic code example:

```
() => {
  const [startDate, setStartDate] = useState(new Date("12-01-2020"));
  
  setTimeout(() => {
     setStartDate(new Date());
  }, 1500);
  
  return (
    <DatePicker
      selected={startDate}
      onChange={date => setStartDate(date)}
      inline
    />
  );
};
```

This can be worked around by setting _startDate_ to null or undefined prior to setting it to a valid date. Ex:

setTimeout(() => {
     setStartDate();
     setStartDate(new Date());
  }, 1500);

**Comment by mansi-mms** [comment]
Hi! Has anyone found a workaround for this issue?
I have an inline date picker and custom buttons added. 
`       <button onClick={getThisWeekRange}>
              {t('thisWeek')}
            </button>`
`  const getThisWeekRange = () => {
    setStartDate(startOfWeek(currentDay, []));
    setEndDate(endOfToday());
  }`
If a previous month is opened and I click this button, the range is set correctly, but I still see that month. 
I want to refresh the date picker in order to see the month of 'this week'
![image](https://user-images.githubusercontent.com/85544335/144896333-11289e11-b01b-4191-a792-4af4f9048806.png)

**Comment by sagarCS** [comment]
update key prop for complete refresh of calender is not working for me as it takes away the focus from the custom input field,
Any update or solution you guys have found please share
