### ISSUE TITLE
How to show different times on different days

### ISSUE THREAD

**Issue by Jonofat** [Hacker0x01/react-datepicker#2412]
Please could anyone assist with this, I am desperate. I want to show different times for weekdays and weekends.

I am trying something like this as a start but this disables times for any day instead of specific days

```
  const isSunday = (date) => {
    const day = getDay(date);
    return day !== 0;
  };

  let excluded = [
    {
      time: "12",
      date: "28/09/2020",
    },
    {
      time: "13",
      date: "03/10/2020",
    },
  ];


    <DatePickerField
      filterDate={isSunday}
      minTime={new Date(new Date().setHours(8, 0, 0))}
      maxTime={new Date(new Date().setHours(17, 0, 0))}
      excludeTimes={excluded.map((exclude, index) => {
        return setHours(
          setMinutes(new Date(), 0),
          parseInt(exclude.time)
        );
      })}
      timeIntervals={60}
      maxDate={addDays(new Date(), 3)}
      dateFormat="d/M/Y HH:mm"
      timeFormat="HH:mm"
      name="time-to-contact"
      label="Required Date *"
    />
```

**Comment by bogdansoare** [comment]
I solved this using the `onSelect` callback that gets triggered when selecting a day. 
In that callback I set the exclude times for that specific day.
You can check out the solution here https://codesandbox.io/s/react-datepicker-different-excludetimes-for-specific-days-6i7y6?file=/src/App.js

**Comment by Jonofat** [comment]
Nice one! Do you perhaps know how to only show certain times, like working hours though? This always starts at midnight which makes the time list really long. For example, it should only show 8am to 5pm and not have anything before or after those times ie: not visible at all.

**Comment by akcalp** [comment]
> I solved this using the `onSelect` callback that gets triggered when selecting a day.
> In that callback I set the exclude times for that specific day.
> You can check out the solution here https://codesandbox.io/s/react-datepicker-different-excludetimes-for-specific-days-6i7y6?file=/src/App.js

Thank you so much for this. I have a question though. Do you know how can I exclude time and date if I have a dynamic array of Dates? For example, I want to exclude March 5th at 9:00 am and March 6th at 19:00 pm but I don't want to hardcode this as I am having a dynamic array of dates
