### ISSUE TITLE
Can you make 24-hour time selection available for the showTimeInput option?

### ISSUE THREAD

**Issue by CBreakr** [Hacker0x01/react-datepicker#2424]
When using the showTimeInput option to allow for picking the particular time by hour+minute, the only option available when clicking the clock icon seems to be time in the AM/PM format. Changing the timeFormat option doesn't appear to do anything and I didn't see anything in the documentation to suggest another option to use for this purpose.

I would like to be able to select 24-hour time in this way rather than having to rely on the showTimeSelect option.

**Comment by dbollinger** [comment]
Seems like fate that the issue number for this one is 2424 😅

**Comment by CBreakr** [comment]
Some serendipity for the issue, but I guess not for the solution. Thanks!
