### ISSUE TITLE
Locale doesn't work in navigation

### ISSUE THREAD

**Issue by ygnoh** [Hacker0x01/react-datepicker#2428]
**Describe the bug**
Navigations always have labels in English even if I apply specific locale to.

**To Reproduce**

1. Go to example (https://reactdatepicker.com/)
2. And choose **Locale without global variables** section.
3. Using browser debugging tool, inspect the navigation html elements.

**Expected behavior**
Labels should be shown in given language(locale).

**Screenshots**
![image](https://user-images.githubusercontent.com/13075245/95072968-0a312f00-0747-11eb-98f6-67e1ab3c965c.png)

It shows its label in English(`Next Month`), not in given language(`fi`).

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Browser [e.g. chrome, safari] chrome latest
- Version [e.g. 22] 3.2.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Svish** [comment]
Locale doesn't localize any texts, it just deals with date/time formatting. To translate all the texts, you need to set these props:

```js
const LocalizationProps = {
  chooseDayAriaLabelPrefix: 'Velg',
  ariaLabelClose: 'Lukk',
  weekAriaLabelPrefix: 'Uke',
  nextMonthButtonLabel: 'Neste måned',
  previousMonthButtonLabel: 'Forrige måned',
  nextYearButtonLabel: 'Neste år',
  previousYearButtonLabel: 'Forrige år',
  weekLabel: 'Uke',
};

<ReactDatepicker selected={date} onChange={setDate} {...LocalizationProps} />
```

Really wish all of these could be gathered into one single prop though. It would make it much easier to "discover", and make it clearer that you should supply all of these at once. Although there might be a few labels you won't use, it rarely makes sense with a partially translated datepicker.

**Comment by Svish** [comment]
There does seem to be a bug though: The `aria-label` of the navigation buttons doesn't get the translated text.

![image](https://user-images.githubusercontent.com/142162/95099605-60df3e80-0730-11eb-9600-f966ebf4b88f.png)

**Comment by ygnoh** [comment]
@Svish Thanks for your answer! I think it's more reasonable to provide translated labels as well.
