### ISSUE TITLE
Memory leak when a select element is used inside a custom header

### ISSUE THREAD

**Issue by omniphx** [Hacker0x01/react-datepicker#2431]
**Describe the bug**
Appears to be a memory leak anytime a `<select>` element exists inside custom header with multiple select options. This hurts performance and can cause new date selections to not register.

**To Reproduce**

1. Go to https://reactdatepicker.com/#example-custom-header
2. Open Chrome devtools > Memory
3. Select Allocation instrumentation on timeline and click "Take snapshot"
4. Select any date
7. Select a new date
8. Continue selecting additional dates for more examples
9. Will see memory leaks after every time the calendar window closes and reopens

* Can also reproduce by selecting outside calendar window or triggering an onblur event instead of picking a date
* Good idea to remove any React devtool extensions since they can also cause memory leaks

For a more concise example:
```
() => (
  <DatePicker
    renderCustomHeader={() => (
      <select>
        {[1, 2, 3].map((option, index) => (
          <option key={index}>{option}</option>
        ))}
      </select>
    )}
  />
);
```

**Expected behavior**
No memory leaks

**Screenshots**
![2020-10-06_17-16-54](https://user-images.githubusercontent.com/3722405/95261969-55a41580-07f9-11eb-83d9-78070a42d6be.png)

**Desktop (please complete the following information):**

- OS: iOS 10.15.7
- Browser: Chrome
- Version: 85.0.4183.121
- React version: 16.13.1

**Additional context**
What's weird is this only seems to be an issue if there are multiple options. A list of other elements such as `<div>` works fine with no memory issues whatsoever.

**Comment by imyjimmy** [comment]
Can confirm I'm seeing the same issue:
<img width="1594" alt="Screen Shot 2020-10-06 at 3 07 21 PM" src="https://user-images.githubusercontent.com/489440/95266691-862f8380-07e8-11eb-867d-10ac02dbd82b.png">
