### ISSUE TITLE
Datepicker slow in Safari after added includeDates array

### ISSUE THREAD

**Issue by ahmed-sharief5** [Hacker0x01/react-datepicker#2435]
**Describe the bug**
Datepicker is popups very slowly when includeDates array is added with around 300 elements in Safari browser.
Performance is lagging due to the above issue. Please resolve this issue as soon as possible

**Comment by lassekuu** [comment]
It's not only on Safari. I have similar performance issue with Firefox.

**Comment by EduardoLopes** [comment]
Same problem here

**Comment by Ramosok** [comment]
I have this problem (
