### ISSUE TITLE
Seperate Icon to open picker

### ISSUE THREAD

**Issue by TomPeak** [Hacker0x01/react-datepicker#2441]
On Mobile I have the problem that the keyboard that opens onFocus gets over the picker. Is there a property for open it by button? -> so no keyboard for input field.

thx,
Tom

**Comment by ParksDMSI** [comment]
You can pass in your own component to the customInput prop

**Comment by TomPeak** [comment]
Thx thats cool! Is it possible to deactivate the CalendarPopUp so that i switch between "inline" by state and textinput without the daygrid?

**Comment by ParksDMSI** [comment]
I think you could accomplish this yourself by making another component that is just an input and have a parent component display wither the inline or the daypicker based upon state

**Comment by TomPeak** [comment]
There was the problem that the date was not the right format and it crashes. So when you edit the onChange … I will have a new try… but I guess I have to do may setDate on my own. … .isValid()

Thx!
