### ISSUE TITLE
function filterTime is not binded to date

### ISSUE THREAD

**Issue by mroforolhc** [Hacker0x01/react-datepicker#2449]
I wanted to filter time that has already passed but noticed that component Time render values based on current date.
I expected Time will render values based on selected date.

**Example filter** (Changing the date will not change anything):
```
const filterTime = (time) => {
    const currentDate = new Date();
    const selectedDate = new Date(time);

    return currentDate.getTime() < selectedDate.getTime();
};
```

**Comment by jcsunran** [comment]
I use the latest code, it still has this issue,   time value is  always current date.
