### ISSUE TITLE
npm start is not a valid script

### ISSUE THREAD

**Issue by arahansen** [Hacker0x01/react-datepicker#245]
The readme mentions using `npm start` to run an example application. But this is not a valid script command within the project directory.

`npm start` is available for the gh-pages branch. But not for the master branch. Can the start command be added to the master branch? If not, then maybe the readme should be updated to clarify usage of `npm start`?

**Comment by martijnrusschen** [comment]
We've updated the docs. This should be more clear now. (btw, `npm start` is a valid command now)
