### ISSUE TITLE
Date management library agnostic via "date-io"

### ISSUE THREAD

**Issue by hazem3500** [Hacker0x01/react-datepicker#2455]
**Is your feature request related to a problem? Please describe.**
If a project already depends on another date management library like moment or luxon it would be better if they didn't have to depend on another date management library when using react-datepicker (date-fns), and having react-datepicker tied to a date management library makes it hard to support other calendar systems such as Jalali and Hijri.

**Describe the solution you'd like**
We can make react-datepicker depend on [date-io](https://github.com/dmtrKovalenko/date-io) which offers an abstraction over the common date management libraries, that way a project can utilize the date management library that they are already using, also now we'll be able to support other calendar systems by just switching the date management library.

**Additional context**
this is how [material-ui-picker](https://material-ui-pickers.dev/getting-started/installation) handles it.

**Comment by vutran** [comment]
Not entirely sure if `date-io` is the best option here but I do agree with not coupling this library to `date-fns`.

However, this seems related to #2402
