### ISSUE TITLE
selected date appears selected across all months

### ISSUE THREAD

**Issue by wlblanchette** [Hacker0x01/react-datepicker#2456]
**Describe the bug**
When using the datepicker to drive a date range with `selectsRange` prop, the selected day of the month appears to be selected across all months. 

**To Reproduce**
1. Go to https://reactdatepicker.com/#example-date-range-for-one-datepicker
2. click a day 
3. then click to scroll left or right through months. You'll see the day remains selected.

**Expected behavior**
Would expect that only the specific day that the user selected is highlighted in the UI.

**Screenshots**
<img width="238" alt="Screen Shot 2020-10-15 at 3 45 12 PM" src="https://user-images.githubusercontent.com/14362937/96178521-87099900-0efd-11eb-9306-ac7b98e90fde.png">

<img width="224" alt="Screen Shot 2020-10-15 at 3 45 25 PM" src="https://user-images.githubusercontent.com/14362937/96178480-7527f600-0efd-11eb-80d7-72a71b24d848.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser chrome
- Version 85

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ktonini** [comment]
Came across this same issue.  Looks like it's caused by keyboard navigation.  Passing this prop in worked for me-

**Comment by nthurnau** [comment]
I wouldn't recommend disabling keyboard navigation because it might interfere with accessibility. @wlblanchette You can solve the issue with CSS - give your react-datepicker a custom classname and then target the styles like this:
```
.react-datepicker__day--keyboard-selected {
      background-color: transparent;
      border-radius: unset;
      outline: unset;
      color: #000;

      &:focus {
        box-shadow: unset;
      }
    }
```

**Comment by Hillsie** [comment]
@ktonini Solution worked for my use case. https://github.com/Hacker0x01/react-datepicker/issues/2456#issuecomment-716547497

**Comment by ashmoop** [comment]
@nthurnau - The css solution removes the css for the actual selected date, so its not quite what I need. Disabling the keyboard navigation was the only way I could get the calendar to match the requirements I need. It would be nice to have the accessibility working, though.
