### ISSUE TITLE
customInput remounts on every render

### ISSUE THREAD

**Issue by JavRok** [Hacker0x01/react-datepicker#2479]
Hi, I think there's a performance issue when using _customInput_ option with react-datepicker. The provided custom input gets created/mounted on every render of the parent. 
 
The problem can be seen in this sandbox: 
[![Edit React Hook Form - Controller (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-controller-forked-coxoj?fontsize=14&hidenavigation=1&theme=dark)
Here I was testing it together with react-hook-form, but I commented the integration to prove the problem is on the datepicker. I followed the example here -> https://reactdatepicker.com/#example-custom-input. 

I added local state (open) to force parent rendering, and _useEffect_ to log the element remounting. 

This may not seem like a big problem, but this is a simple example. On my project I'm using a heavier custom element and the performance hit is pretty obvious. 

I don't know if the solution is fixable here or I'm gonna have to use some kind of hook/memoization. Any clues? 

Thanks and keep up the good work !

- OS: Ubuntu on WLS
- Browser Chrome
- Version 86

**Comment by JavRok** [comment]
Oh, and seems **_forwardRef_** is also necessary, as commented by @Psvensso on this other issue https://github.com/Hacker0x01/react-datepicker/issues/2397#issuecomment-707048538

**Comment by davidfrtala** [comment]
Same here. This is even more visible when you pass `onChange` handler, and try to manually type the date. You will lose focus on each render.

In my case, adding `useMemo` hook solve the issue

```tsx
const CustomInput = React.useMemo(
  () => forwardRef((props, ref) => <input {...props} ref={ref} />),
  [],
);
```

**Comment by jlei523** [comment]
> Same here. This is even more visible when you pass `onChange` handler, and try to manually type the date. You will lose focus on each render.
> 
> In my case, adding `useMemo` hook solve the issue
> 
> ```tsx
> const CustomInput = React.useMemo(
>   () => forwardRef((props, ref) => <input {...props} ref={ref} />),
>   [],
> );
> ```

Could you post a full example of this? Thanks!

**Comment by ShivamJoker** [comment]
If anyone is looking for full example here it is with custom tailwind component
```tsx
const DatePicker = ({
  value,
  onChange,
  label,
  showError,
  placeholder,
}: IDatePicker): JSX.Element => {
  const ref = createRef<HTMLInputElement>();

  const CustomInput = useMemo(
    () =>
      forwardRef<HTMLInputElement, unknown>(({ ...rest }) => (
        <div className={styles['outline-container']}>
          {label && <label>{label}</label>}
          <input
            ref={ref}
            {...rest}
            className={!value && showError ? 'input-error' : ''}
            type="text"
            autoComplete="bday"
          />
          <Icon
            className={`absolute text-gray-500 right-4 ${
              label ? '' : '-translate-y-1/2'
            } top-1/2 transform stroke-current`}
            name="calendar"
          />
        </div>
      )),
    []
  );

  return (
    <ReactDatePicker
      customInput={<CustomInput ref={ref} />}
      selected={value}
      locale={ru}
      dateFormat="dd.MM.yyyy"
      portalId="root"
      onChange={onChange}
      placeholderText={placeholder}
    />
  );
};
```

**Comment by RobSchilderr** [comment]
> If anyone is looking for full example here it is with custom tailwind component
> 
> ```tsx
> const DatePicker = ({
>   value,
>   onChange,
>   label,
>   showError,
>   placeholder,
> }: IDatePicker): JSX.Element => {
>   const ref = createRef<HTMLInputElement>();
> 
>   const CustomInput = useMemo(
>     () =>
>       forwardRef<HTMLInputElement, unknown>(({ ...rest }) => (
>         <div className={styles['outline-container']}>
>           {label && <label>{label}</label>}
>           <input
>             ref={ref}
>             {...rest}
>             className={!value && showError ? 'input-error' : ''}
>             type="text"
>             autoComplete="bday"
>           />
>           <Icon
>             className={`absolute text-gray-500 right-4 ${
>               label ? '' : '-translate-y-1/2'
>             } top-1/2 transform stroke-current`}
>             name="calendar"
>           />
>         </div>
>       )),
>     []
>   );
> 
>   return (
>     <ReactDatePicker
>       customInput={<CustomInput ref={ref} />}
>       selected={value}
>       locale={ru}
>       dateFormat="dd.MM.yyyy"
>       portalId="root"
>       onChange={onChange}
>       placeholderText={placeholder}
>     />
>   );
> };
> ```

Cheers! Did you also manage to make this component responsive on phones when including time?
