### ISSUE TITLE
ShowYearPicker does not appear like a sample page

### ISSUE THREAD

**Issue by JayKim-Dev** [Hacker0x01/react-datepicker#2496]
When using showYearPicker, it is different from the sample on https://reactdatepicker.com
How can I mark three years in a line?

```
import React, { useState } from "react";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

function DatePick() {
  const [startDate, setStartDate] = useState(new Date());
  return <DatePicker selected={startDate} onChange={(date) => setStartDate(date)} showYearPicker dateFormat="yyyy" />;
}

export default DatePick;
```

![image](https://user-images.githubusercontent.com/48009636/97147709-45a2a480-17ad-11eb-9e65-4c6d2451ce99.png)

**Comment by SivaGanesh56** [comment]
add your own css. add with around 210px to react-datepicker-wrapper class

**Comment by Eotex** [comment]
What version of react-datepicker is this?

**Comment by Eotex** [comment]
Mine isn't selected default
