### ISSUE TITLE
Using a Function component as a customInput shows error

### ISSUE THREAD

**Issue by xdumaine** [Hacker0x01/react-datepicker#2497]
**Describe the bug**

When using a react Function Component (`FC`) as the `customInput` to a `DatePicker` causes react to log an error `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

**To Reproduce**

1. Create a function component
2. Render a DatePicker with that function component as the `customInput` value
3. View console

**Expected behavior**
No Errors are shown. 

**Observed behavior**
Using the function component as a custom input seems to work fine, but the react error is shown. It's possible some different behavior would be broken.

**Comment by sashamorozov** [comment]
@xdumaine I faced the same error and found the solution in this comment https://github.com/Hacker0x01/react-datepicker/issues/2397#issuecomment-707048538

**Comment by YanaLugina** [comment]
I fixed this bug like this:
// when create custom input added ref in function params
`    const ExampleCustomInput = React.forwardRef(({ value, onClick }, ref) => (
        <button ref={ref} className={style.timeInput} onClick={onClick}>
            <span>c</span>
            {value}
        </button>
    ));
    const ref = React.createRef();`

// in DatePicker i passed ref
`
<DatePicker
                selected={startTime}
                ...
                locale={ru}
                timeCaption='Время'
                dateFormat='HH:mm'
                customInput={<ExampleCustomInput ref={ref} />}
                onChange={(data) => {
                    setStartTime(data);
                }}
            />`

**Comment by robations** [comment]
Does the documentation need to change?

https://reactdatepicker.com/#example-custom-input
https://github.com/Hacker0x01/react-datepicker/blob/master/docs-site/src/examples/customInput.js#L1

I can make a PR if this contribution is appropriate.

**Comment by YanaLugina** [comment]
> Does the documentation need to change?
> 
> https://reactdatepicker.com/#example-custom-input
> https://github.com/Hacker0x01/react-datepicker/blob/master/docs-site/src/examples/customInput.js#L1
> 
> I can make a PR if this contribution is appropriate.

Yes, please!

**Comment by robations** [comment]
@xdumaine `forwardRef()` has been added to the docs so you might be able to close this issue?
