### ISSUE TITLE
still running into bug with inline calendar: selection showing twice

### ISSUE THREAD

**Issue by archywillhe** [Hacker0x01/react-datepicker#2514]
**Describe the bug**
selection is showing twice

**To Reproduce**
easily reproduced by creating an inline table, and letting `selected={date}` to be set by some outside function. 

i.e.  this problem still persists: #2284

**Expected behavior**
expecting the bug to be fixed by https://github.com/Hacker0x01/react-datepicker/pull/2436 

- OS: macOS
- Browser: Chrome

currently on react-datepicker 3.3.0 (latest as of writing)

**Comment by archywillhe** [comment]
so this problem still persists: https://github.com/Hacker0x01/react-datepicker/issues/2284

**Comment by archywillhe** [comment]
right now i'm forcing table to refresh 

```
  useEffect(() => {
    // this is a hot fix to a bug with inline calendar
    // https://github.com/Hacker0x01/react-datepicker/pull/2436
    // https://github.com/Hacker0x01/react-datepicker/issues/2514

    setTempHide(true)
    setTimeout(function () {
      setTempHide(false)
    }, 0)
  }, [date])
```

**Comment by dusanbass** [comment]
Hi @archywillhe, I'm having the same issue,
thanks for posting solution, but I don't know how to use it. What is 
```
setTempHide(true)
    setTimeout(function () {
      setTempHide(false)
    }, 0)
```

**Comment by riccardobellini** [comment]
Having the same problem, when changing "selected" prop programmatically selection is showing both on old and new date.
At first, I thought about destroying and recreating the component with the updated date, but I found a simpler and suitable workaround by just adding prop "disabledKeyboardNavigation" to date picker, since in my application I don't plan to need that feature. However, it would be nice if it could be solved.

**Comment by thepuzzlemaster** [comment]
Although not a long-term solution, a cleaner fix is to just hide the `keyboard-selected` state, unless it's actually focused. You can do this just with CSS.

```
.react-datepicker .react-datepicker__day.react-datepicker__day--keyboard-selected {
      background-color: $white;
      color: inherit;

      &:focus {
        background-color: #2a87d0;
        color: #fff;
      }
    }
