### ISSUE TITLE
Click through overlay in portal version

### ISSUE THREAD

**Issue by meandersen** [Hacker0x01/react-datepicker#2524]
Getting the bug where you can click through the overlay in portal version.
You can on mobile devices (including Chrome device simulation), click through the overlay at the portal version and activate other input fields, links or buttons.

**Gets console error**
`Unable to preventDefault inside passive event listener invocation.`

Have seen same issue here https://github.com/Hacker0x01/react-datepicker/issues/1279 but is labeled with **wontfix**. 

**To Reproduce**
on mobil deviceses

1. Go to https://reactdatepicker.com/#example-portal-version
2. Click on the 'portal version' input.
3. Click on the darkened overlay, over the same input field or an other
4. The portal closes but the other input gets activated
5. See error in console
`Unable to preventDefault inside passive event listener invocation.`

**Expected behavior**
The portal close, nothing else gets activated.

**Comment by meesta1990** [comment]
after spending 2 hours I finally figured out how to fix this.

react-datepicker uses react-onclickoutside and I investigate how it sets the outsideclick. Basically it adds an eventListener on touchstart in the document. So my idea was override this function.

All you need is add this prop to the datePicker:

`onCalendarOpen={handleCalendarOpen}`

then the function is:

```
const handleCalendarOpen = () => {
      document.addEventListener('touchstart', (event: TouchEvent) => {
          event.stopPropagation();
      }, true);
 };
```

**Comment by Wulfram8** [comment]
Same issue, is there any other solution?

**Comment by bladerunner2020** [comment]
This is a workaround (it works only if calendar has days, otherwise you need to change class name):

```js
  const handleTouchStart = (e) => e.stopPropagation();
  const handleCalendarOpen = () => {
    document.addEventListener('touchstart', handleTouchStart, true);
    const [element] = document.getElementsByClassName('react-datepicker__day') || [];
    if (element) element.focus();
  };
  const handleCalendarClose = () => document.removeEventListener('touchstart', handleTouchStart);
```

**Comment by Szorcu** [comment]
@meesta1990 and @bladerunner2020 worked for me with a small adjustment. Notice that `handleTouchStart` function is wrapped in `useCallback` to prevent redefining it on re-renders which would result in the listener not being removed on calendar close, which can lead to unwanted issues.

```ts
const handleTouchStart = useCallback(
  (e: TouchEvent) => e.stopPropagation(),
  []
)

const handleCalendarOpen = () => {
  document.addEventListener("touchstart", handleTouchStart, true)
}

const handleCalendarClose = () => {
  document.removeEventListener("touchstart", handleTouchStart, true)
}
```
