### ISSUE TITLE
Locale doesnt work

### ISSUE THREAD

**Issue by sibstark** [Hacker0x01/react-datepicker#2532]
Hello! I found that locale translations are not pulled from date-fns/locale. Here is my example
1. I imported "date-fns/locale/ru"
2. Used https://reactdatepicker.com/#example-locale as reference

See in https://codesandbox.io/s/condescending-kepler-gxg3o

**Expected**
Datepicker are translated in Russian

**Current** 
Got A locale object was not found for the provided string ["ru"]; error

**Comment by daniel-seoane** [comment]
You have to register the locale, like it says [here](https://github.com/Hacker0x01/react-datepicker#localization)

Check it out: [https://codesandbox.io/s/happy-christian-387xi](https://codesandbox.io/s/happy-christian-387xi)
