### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by SadPandaBear** [Hacker0x01/react-datepicker#2536]
**Describe the bug**
I'm importing the component in a NX monorepo. Its deps are losing reference to global.

**Expected behavior**
This should not happen

**Screenshots**
```
Uncaught ReferenceError: global is not defined
    at Object.../../../node_modules/has-symbols/index.js (vendor.js:20388)
    at __webpack_require__ (bootstrap:79)
    at Object.../../../node_modules/es-abstract/GetIntrinsic.js (vendor.js:14490)
    at __webpack_require__ (bootstrap:79)
    at Object.../../../node_modules/es-abstract/helpers/callBind.js (vendor.js:14744)
    at __webpack_require__ (bootstrap:79)
    at Object.../../../node_modules/object-is/index.js (vendor.js:47563)
    at __webpack_require__ (bootstrap:79)
    at Object.../../../node_modules/deep-equal/index.js (vendor.js:14185)
    at __webpack_require__ (bootstrap:79)
```

**Workaround**
Add the following In the `index.html`: 

```
<script>
  if (global === undefined) {
    var global = window;
  }
</script>
```

**Comment by dan-overton** [comment]
I've hit the same issue in an nx monorepo. Simply installed, imported and used.

**Comment by michelpm1** [comment]
> **Describe the bug**
> I'm importing the component in a NX monorepo. Its deps are losing reference to global.
> 
> **Expected behavior**
> This should not happen
> 
> **Screenshots**
> 
> ```
> Uncaught ReferenceError: global is not defined
>     at Object.../../../node_modules/has-symbols/index.js (vendor.js:20388)
>     at __webpack_require__ (bootstrap:79)
>     at Object.../../../node_modules/es-abstract/GetIntrinsic.js (vendor.js:14490)
>     at __webpack_require__ (bootstrap:79)
>     at Object.../../../node_modules/es-abstract/helpers/callBind.js (vendor.js:14744)
>     at __webpack_require__ (bootstrap:79)
>     at Object.../../../node_modules/object-is/index.js (vendor.js:47563)
>     at __webpack_require__ (bootstrap:79)
>     at Object.../../../node_modules/deep-equal/index.js (vendor.js:14185)
>     at __webpack_require__ (bootstrap:79)
> ```
> 
> **Workaround**
> Add the following In the `index.html`:
> 
> ```
> <script>
>   if (global === undefined) {
>     var global = window;
>   }
> </script>
> ```

Worked same situation for a electron app

**Comment by Nightbr** [comment]
Same error, with Nx monorepo (bundle with webpack).

Adding
