### ISSUE TITLE
showTimeSelect and todayButton bug

### ISSUE THREAD

**Issue by Mikowhy-owl** [Hacker0x01/react-datepicker#2543]
**Describe the bug**
When both props are passed into the picker the styles look weird.

**To Reproduce**

Just go to a main page https://reactdatepicker.com/, go to "Today button" example and add showTimeSelect prop.

**Expected behavior**
It should just add today button on the bottom and do not destroy whole calendar style.

**Screenshots**
![image](https://user-images.githubusercontent.com/24779051/99548821-55cb2f80-29b9-11eb-878a-002471ffa436.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave 10.14.6
- Browser: Chrome
- Version: 86.0.4240.198 (Official Build) (x86_64)

**Comment by sebastienbarre** [comment]
Still kinda broken as of 2024:

<img width="899" alt="image" src="https://github.com/user-attachments/assets/97ee3130-3ef0-4656-8886-085cb0d0aa07">

Note all the corners...
