### ISSUE TITLE
Option to make the popper top of all DOM elements.

### ISSUE THREAD

**Issue by athuldom** [Hacker0x01/react-datepicker#2545]
**Is your feature request related to a problem? Please describe.**
When using inside a custum popup or material ui table the popper of the datepicker is going under the view. It should be displayed above the table or popup. Changing the z-index didn't work.

**Describe the solution you'd like**
There should be an option to make the popup overlapping or above all DOM elements. it is going inside the table not displayed above.
![u275](https://user-images.githubusercontent.com/67672807/99620175-fae21880-2a4a-11eb-8727-f491306de3e0.PNG)

**Describe alternatives you've considered**
making the position to fixed and dynamically changing the top and left properties may work perfect.

**Additional context**

**Comment by simjes** [comment]
You can create a [React portal](https://reactjs.org/docs/portals.html) for it outside the normal DOM flow, take a look at `Portal by id` [example](https://reactdatepicker.com/). It should then work as you suggest, and you can change the z-index if you need it to be infront of a modal.

**Comment by athuldom** [comment]
thank you, it got worked in two step:
step 1 - **import createPortal**
`import {createPortal} from `'react-dom';`
step 2 - add this props to the datePicker:-
`popperContainer={({children}) => createPortal(children,document.body)}`

simple, it got worked in my case. Hope someone may get helpful
