### ISSUE TITLE
0.16.0 npm package missing dist files

### ISSUE THREAD

**Issue by strawbrary** [Hacker0x01/react-datepicker#255]
0.16.0 of this package on npm is missing the `dist` folder which is breaking the package. It looks like f99587e added `dist` to the `.gitignore` file, and since there is no `.npmignore` file, everything in `.gitignore` is also being ignored on npm.

**Comment by martijnrusschen** [comment]
@RSO This is exactly what you were wondering about today. Looks like we need an `.npmignore`.

**Comment by strawbrary** [comment]
Oh I just saw a `.npmignore` was added in efc1587 but I guess it doesn't work if it's not in the project root.

**Comment by martijnrusschen** [comment]
Yeah looks like it, I moved it to the root now. Hopefully this fixes the issue.

**Comment by martijnrusschen** [comment]
I'll release a patch version to fix this issue.

**Comment by strawbrary** [comment]
Thanks.

Btw there is an npm package called [pkgfiles](https://www.npmjs.com/package/pkgfiles) which will show you a preview of what files will be published. Can be useful for getting some insight into npm's behavior.

**Comment by RSO** [comment]
Hehe, that's what we get for making changes like this on a Friday afternoon. Sorry @strawbrary!

**Comment by RSO** [comment]
And thanks for reporting!

**Comment by strawbrary** [comment]
No worries, it's happened to the best of us. :) Thanks for the quick turnaround on the fix.

**Comment by martijnrusschen** [comment]
Released 0.16.1 with the fix (https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.16.1)

**Comment by strawbrary** [comment]
Looks good :+1:

**Comment by martijnrusschen** [comment]
Awesome!
