### ISSUE TITLE
Can I configure datepicker to accept MM/DD, then append YYYY?

### ISSUE THREAD

**Issue by michaels23** [Hacker0x01/react-datepicker#2550]
Out users have asked if they can simply type in MM/DD, then have YYYY defaulted to the current year. Can datepicker be configured to do that somehow?

**Comment by OptimusPi** [comment]
Upvote

**Comment by OptimusPi** [comment]
Actually, it accepts MM/DD, but not MMDD, example: If I type "1124" instead of Nov. 24th, (current year), it actually says December 31, year 1123...

**Comment by jmpeterson18460** [comment]
Upvote
