### ISSUE TITLE
Adding the `showMonthYearDropdown` prop on the datepicker causes the app to hang/become-unresponsive.

### ISSUE THREAD

**Issue by ParrotStone** [Hacker0x01/react-datepicker#2553]
**Describe the bug**
When I add the `showMonthYearDropdown` prop shown [here](https://reactdatepicker.com/#example-monthyear-dropdown) on the `DatePicker` component, it kinda crashes/hangs the whole app, I'd have to restart the app or open it again in another tab.

**To Reproduce, go to [this codesandbox](https://codesandbox.io/s/determined-meitner-fprnj?file=/src/App.js)**

**Expected behavior**
The dropdown of both months & years to appear without the hassle and the app crashes/hangs.

**Desktop (please complete the following information):**

- OS: [Linux]
- Browser [Chromium, Firefox]

**Additional context**
This error is consistent regardless of `React` version, I tried it with `React` 16.13 & 17.0

**Comment by hufftheweevil** [comment]
I'm experiencing the same thing. Using `React 16.13.1` and Chrome 88 here.

**Comment by TkDodo** [comment]
I have the same issue. Just to clarify, as this is missing from the original bug description:

The DatePicker renders fine, and you can also select dates fine in the above sandbox. The app begins to "freeze" as soon as you want to _open_ the `montYearDropdown`. There is no error in the console or anything.

**Comment by OmkarRajam** [comment]
If you go to https://reactdatepicker.com/#example-monthyear-dropdown and then try to open `montYearDropdown`, it also does not open. The date picker crashes with error as follows (same error appears in console) - 
```
Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message 
or use the non-minified dev environment for full errors and additional helpful warnings.
```
As per the link of the error decoder, the full text of the error is:
```
Unable to find node on an unmounted component.
```

**Comment by vantsymbalenko** [comment]
The same issue with month year dropdown.  
React v16.13.1;
react-datepicker 3.7.0;
Browser: chrome 89.0.4389.90 (Official Build) (x86_64), 
OS: macOS Catalina v10.15.6;
Any updates of this bug?

**Comment by StanBorovko** [comment]
I have the similar issue: I added datepicker with minDate and maxDate values and in this case datepicker works fine. when I remove props minDate and maxDate the app crashes when I try to open month selector

"react": "17.0.2",
"react-datepicker": "^3.8.0",
browser: chrome 92.0.4515.107
os: win10 home 19041.1110

**Comment by Donorlin** [comment]
Any news about this, please? 
The same thing happened to me, react 16.14.0 and latest datepicker 4.6.0.
Everything hangs out, I cant help with posting anything useful sorry.

**Comment by ParrotStone** [comment]
Any chance of this issue getting fixed. Been opened for nearly two years now...

**Comment by garethterrace** [comment]
I managed to fix this hang by specifying the ``dateFormatCalendar`, `minDate` and `maxDate` props. My theory is the dropdown needs the min/max dates to give the dropdown its range and not specifying them causes it to infinite loop.


```
 dateFormatCalendar={"MMM yyyy"}
 minDate={dayjs().subtract(7, 'month').toDate()}
 maxDate={dayjs().add(7, 'month').toDate()}
```
