### ISSUE TITLE
Add a close button in header react datepicker

### ISSUE THREAD

**Issue by yasirali179** [Hacker0x01/react-datepicker#2557]
I have added a close button in the datepicker's header by using "renderCustomHeader". Now I don't know how datepicker will close when I click that header button. Is there any call function which closes react datepicker?

**Comment by alinadirkhanloo** [comment]
see this:

**Comment by alinadirkhanloo** [comment]
see this:
https://github.com/Hacker0x01/react-datepicker/issues/730#issuecomment-289418619
