### ISSUE TITLE
DatePicker doesn't complete date input if calendar is not rendered

### ISSUE THREAD

**Issue by khanilov** [Hacker0x01/react-datepicker#2562]
**Describe the bug**
DatePicker doesn't correct/complete date string in input, if open property is `false`.

**To Reproduce**

1. Pass `open={false}` prop to `DatePicker`
2. Start typing your date, but not complete it.
3. Leave the input.
4. Your input string stays as is, instead of complete to closest valid date.

**Expected behavior**
`DatePicker` should behave similar to when `open={true}` or `open={undefined}` and correct/complete user input.

**Screenshots**
With calendar:
![open=true](https://user-images.githubusercontent.com/52448226/100632591-121fe080-333e-11eb-9b08-78e96b2f4d2a.gif)
Without calendar:
![open=false](https://user-images.githubusercontent.com/52448226/100632636-219f2980-333e-11eb-8842-557db8848127.gif)

**Desktop (please complete the following information):**

- OS: any
- Browser any
- Version any

**Smartphone (please complete the following information):**

- Device: any
- OS: any
- Browser any
- Version any

**Additional context**
In my use case I need to use `DatePicker` without calendar. I've not found any prop to disable/hide calendar except of `open`. But when I'm using it I'm losing all the cool features with visual date correctness/complete (only in state layer).

**Comment by SivaGanesh56** [comment]
@khanilov any solution or workaround you found  ?
