### ISSUE TITLE
Styling Range

### ISSUE THREAD

**Issue by maybecrimson** [Hacker0x01/react-datepicker#2589]
Hello.
I am in need of style the range in the calendar: a continuous background colour from start to end with border radius at the start/end of the row if is the case.
Thank you.

**Comment by enaluz** [comment]
Did you ever figure this one out? @maybecrimson

**Comment by siddharthshankarpaul** [comment]
+1

**Comment by maybecrimson** [comment]
No news about this topic 😭

**Comment by m-suchorski** [comment]
+1, a class for the end of selection range is missing.

**Comment by nc-mdh** [comment]
You can use the range classes to style the range. Obviously each day is a single element, so I had the same problem with radius and background-color on start and end day of range. However I was able to solve it using radial-gradient: 

`  .react-datepicker__day--range-end {
    background: radial-gradient(circle 16.5px, rgb(1, 160, 80) 94%, rgb(1, 160, 80, 0.1));
    color: #fff;
    border-top-right-radius: 100%;
    border-bottom-right-radius: 100%;
  }`

![image](https://user-images.githubusercontent.com/42059387/187882323-f10f0928-d4b9-4bd5-8d36-ac87c8e6b35f.png)
