### ISSUE TITLE
is there any option to use inline styling ?

### ISSUE THREAD

**Issue by sudhakarsn15** [Hacker0x01/react-datepicker#2600]
I'm trying to customize input using inline styling. but i'm unable to set width to 100% 
Plz some one let me know is there is any solution to set width to 100%

``
![image](https://user-images.githubusercontent.com/35915646/102213233-7032f300-3efc-11eb-8ea2-39c108a47a09.png)

**Comment by randy-aguirre** [comment]
You might use React.createRef() to connect the styling of a given element with the datepicker. Here a short snippet

```
const ref = React.createRef();

const CustomInput = forwardRef(({ value, onClick }, ref) => (
    <Button variant="outline-secondary" onClick={onClick} ref={ref} block>{value}</Button>
));

<DatePicker dateFormat="dd/MM/yyyy" selected={date} onChange={date => setDate(date)} customInput={<CustomInput ref={ref}/>}/>

```
The key part is is connecting DatePicker with CustomInput in customInput={<CustomInput ref={ref}/>}. The button component comes from React Bootstrap in my example. Also you might considere use styled-components.
