### ISSUE TITLE
Close Date picker only after selecting both dates.

### ISSUE THREAD

**Issue by rajat-arora084** [Hacker0x01/react-datepicker#2603]
Hi, 
Is there a way to close DatePicker only after the user selects both dates (start & end date)
Currently, if i use shouldCloseOnSelect={false}, the datepicker remains open, but i want to close it after selecting 2nd date.

**Comment by JuSenpai** [comment]
Try `shouldCloseOnSelect={startDate && !endDate}`.

**Comment by rajat-arora084** [comment]
> Try `shouldCloseOnSelect={startDate && !endDate}`.

It worked. Thanks. :)

**Comment by rajat-arora084** [comment]
7

> > Try `shouldCloseOnSelect={startDate && !endDate}`.
> 
> It worked. Thanks. :)
