### ISSUE TITLE
When monthsShown > 1, selecting a range that spans multiple months causes the calendar to shift

### ISSUE THREAD

**Issue by developithecus** [Hacker0x01/react-datepicker#2609]
**Describe the bug**
When I pass the prop `monthsShown={2}` (or any other > 1), selecting a range that spans multiple months (e.g. December 21st - January 3rd), causes the calendar to shift one month back.

**To Reproduce**

1. Open https://codesandbox.io/s/3re17
2. Open the calendar and notice current month and next month being displayed.
3. Select a range spanning over multiple months (e.g. December 21 - January 3)
4. Open the calendar again and notice that the calendar view shifted and the current month is now on the right side.

**Expected behavior**
The calendar should not shift, so if I have `monthsShown = n`, a range spanning `n` months should be completely visible.

**Screenshots**
![captured](https://user-images.githubusercontent.com/22986246/103204991-34872880-4901-11eb-8aca-e2b458a73251.gif)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge (Chromium), essentially Chrome
- Version: 87.0.664.66

**Additional context**
The bug does not reproduce if the initial value of the datepicker is a range spanning multiple months (as you can see in the sandbox provided).

I already found a similar issue https://github.com/Hacker0x01/react-datepicker/issues/1337, however it did not specify a solution for the presented bug.

**Comment by sebqq** [comment]
+1

**Comment by sebqq** [comment]
Somehow I was able to fix this problem by removing `selected` prop, so I only use `startDate` and `endDate` props now...

**Comment by Vladyslav-Hrytsenko** [comment]
any updates?

**Comment by nick-khoroshkov** [comment]
I solved this problem with: focusSelectedMonth={true}
