### ISSUE TITLE
When entering a date via keyboard in the YYYY-MM-DD format, the selected date is one day prior

### ISSUE THREAD

**Issue by chrisharrington** [Hacker0x01/react-datepicker#2613]
**Describe the bug**
When entering a date via keyboard in the YYYY-MM-DD format, the selected date is one day prior. For example, entering "2020-12-28" selects December 27th, 2020.

**To Reproduce**

1. Click on the date picker's input field.
2. Input "2020-12-28" and hit enter.

**Expected behavior**
The selected date should be December 28th, 2020. Instead, December 27th is selected.

**Screenshots**
![datepicker](https://user-images.githubusercontent.com/453848/103418587-97b8cb00-4b4c-11eb-9dba-ff5b4b7f24fb.gif)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: Chromium 87.0.4280.101.

**Comment by bravis85** [comment]
For me this happened if I set this.state.date = null; and value={this.state.date}, but not if I set it to new Date(); etc.

**Comment by gunner13** [comment]
The same issue for me. YYYY/MM/DD works well. Any updates on this?

**Comment by akamud** [comment]
This is happening to me in the DD/MM/YYYY format too. I see this issue was marked as stale, but it's definitely not fixed 7.3.0.
