### ISSUE TITLE
Month and MonthYear Dropdowns crash

### ISSUE THREAD

**Issue by fcolacilli** [Hacker0x01/react-datepicker#2629]
**Describe the bug**
Both dropdowns return _Minified React error 188_ when clicked.

`
Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
`

**To Reproduce**

1. Click on dropdown toggle

**Desktop:**

- OS: Ubuntu 18
- Browser Chrome 87

https://user-images.githubusercontent.com/65421430/103656825-d8975200-4f47-11eb-810b-d0752b7862a8.mp4

**Comment by shashank1010** [comment]
Year, Month and MonthYear dropdowns crash in the scroll mode, which is the default mode.
I cloned the repo and I get the following error 
> Error: Unable to find node on an unmounted component.

I tried fixing it, but I need to be able to add breakpoints to fix it.
With the doc-site, I cannot fix it as I cannot add breakpoints. Maybe I'm not building it correctly for development.

**Comment by shashank1010** [comment]
It seems to be an issue from react-onoutsideclick
If i replace
`var WrappedMonthYearDropdownOptions = onClickOutside(MonthYearDropdownOptions);`
with 
`var WrappedMonthYearDropdownOptions = MonthYearDropdownOptions;`

It works.
