### ISSUE TITLE
Is there a way to apply "data-xxx" attributes?

### ISSUE THREAD

**Issue by HaloHaloZenon** [Hacker0x01/react-datepicker#2631]
Question in the title

**Comment by chrisgrabinski** [comment]
This might be too late for you but maybe it will help someone else.

To add custom props (for example data-testid) to your date picker input you can [use a custom input](https://reactdatepicker.com/#example-custom-input) as described in the documentation and then pass the desired props down to it.

```
function CustomDatePicker({ dataTestId }) {
  const [startDate, setStartDate] = useState(new Date());
  const ExampleCustomInput = forwardRef(
    ({ value, onClick }, ref) => (
      <input type="text" onClick={onClick} ref={ref} value={value} data-testid={dataTestId} />
    ),
  );
  return (
    <DatePicker
      selected={startDate}
      onChange={date => setStartDate(date)}
      customInput={<ExampleCustomInput />}
    />
  );
}
```

**Comment by chrisgrabinski** [comment]
This might be too late for you but maybe it will help someone else.

To add custom props (for example `data-testid`) to your date picker input you can use a custom input as described in the documentation and then pass the desired props down to it.


```
const CustomInput = React.forwardRef((datePickerProps, ref) => (
  <Input type="text" ref={ref} {...datePickerProps} />
));

function CustomDatePicker({ dataTestId }) {
  const [startDate, setStartDate] = useState(new Date());
  
  return (
    <DatePicker
      selected={startDate}
      onChange={date => setStartDate(date)}
      customInput={<CustomInput data-testid={dataTestId} />}
    />
  );
}
```

**Comment by pdevito3** [comment]
this seems like a dup to #2009 and is an issue for me as well. 

i'd like to add the `data-private` attribute to my input to support obfuscation in LogRocket, but the attribute can't be added. 

for example:

```tsx
<ReactDatePicker data-private={isSensitive ? true : undefined} />
```

needing to supply a custom input seems like an odd and convoluted workaround. @martijnrusschen any thoughts on this? wouldn't expect this to be a big lift and seems pretty limiting
