### ISSUE TITLE
Two separate date ranges in the same calendar

### ISSUE THREAD

**Issue by icelic** [Hacker0x01/react-datepicker#2636]
Is it possible to select 2 separate date ranges in the same calendar?

I need to display 2 sperate selected date ranges that are being compared one against other.

For example something like this:

![image](https://user-images.githubusercontent.com/22912976/104035668-b6fdcb00-51d2-11eb-912c-d7b20c2ddb07.png)

Is it possible to do it with this library?

**Comment by rajat-arora084** [comment]
I just checked the Library functions & we can use onSelect to select the same date again.
Hence, Closing the issue.
Thanks React community! :)

**Comment by icelic** [comment]
I am not sure I understood your solution, in the end I went with another library because I needed some multi range specific features..

**Comment by khoand0407** [comment]
anyone has answer for this question?
