### ISSUE TITLE
PopperJS modifiers error

### ISSUE THREAD

**Issue by Hrach-H** [Hacker0x01/react-datepicker#2656]
I am getting the following error when setting popper 'preventOverflow' modifier: 
`PopperJS: an invalid property has been provided to the "undefined" modifier, valid properties are "name", "enabled", "phase", "fn", "effect", "requires", "options"; but "preventOverflow" was provided.`

I guess it's connected to the version update?

**Comment by martijnrusschen** [comment]
I accidently released a breaking change yesterday. Will be releasing a new version today that reverts the change.

**Comment by Svarozic** [comment]
> I accidently released a breaking change yesterday. Will be releasing a new version today that reverts the change.

may I ask, if and when do you plan to release it again, but with Popper v2 again ?
