### ISSUE TITLE
Support for passing option to date-fns (useAdditionalWeekYearTokens)

### ISSUE THREAD

**Issue by rafchy** [Hacker0x01/react-datepicker#2661]
Hello,

Starting with date-fnsv2, `format` and `parse` use [Unicode tokens](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table). More information can be found  [on date-fns docs](https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md)

The problem we are facing is that we can't use `dateFormat="ww/YYYY"`. As a workaround, we replace YYYY with YYY.

Currently, react-datepicker does not support passing an option for allowing useAdditionalWeekYearTokens. If we were able to pass this additional option to date-fns the problem would not exist.

I've created a codesandbox showing the problem, to reproduce uncomment line 17.

[link](https://codesandbox.io/s/priceless-sammet-ouhge?file=/src/App.js)

**Comment by piyushkathayat** [comment]
@martijnrusschen

**Comment by mykolap** [comment]
See 
https://unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table
Year in “Week of Year” based calendars in which the year transition occurs on a week boundary; may differ from calendar year ‘y’ near a year transition. This numeric year designation is used in conjunction with pattern character ‘w’ in the ISO year-week calendar as defined by ISO 8601, but can be used in non-Gregorian based calendar systems where week date processing is desired. The field length is interpreted in the same was as for ‘y’; that is, “yy” specifies use of the two low-order year digits, while any other field length specifies a minimum number of digits to display.
