### ISSUE TITLE
Filter times only for dates in a given range?

### ISSUE THREAD

**Issue by JashG** [Hacker0x01/react-datepicker#2662]
I am using the latest version (3.4.1). Is there a way to filter the selectable times only for certain dates? For example, I have an object as such:

```
const filterDates = {
  startDate: '2021-01-29T08:00:00',
  endDate: '2021-02-04T08:00:00',
}
```

For any date that occurs on the same day as the start or end date, I want to limit the times the user can choose. For example, if the day is `2021-01-29`, the user should be able to choose times before 8AM. Likewise, if the day is `2021-02-04`, the user should be able to choose times after 8AM. I am already able to filter out any dates between those two with the `filterDate` prop. I tried to pass a function to the `filterTime` prop to accomplish the same thing for times - however, everytime that function was invoked, the param passed was always the same date and wasn't the date I clicked on. I'm not sure what the intended behavior is.

I can't figure out whether or not `filterTime` is the prop that I should be using. Any help would be appreciated!

**Comment by gowthamrajbm** [comment]
You can use something like below:

`<DatePicker
              selected={ this.state.startDate }
              onChange={ this.handleChange }
              minDate={new Date()}
              maxDate={addDays(new Date(), 30)}
          />`
