### ISSUE TITLE
'startOpen" property not work

### ISSUE THREAD

**Issue by alan-anchen** [Hacker0x01/react-datepicker#2666]
**Describe the bug**
Date picker popper is default open after page loaded.

**To Reproduce**
Code like:
<DatePicker
          className={touched[name] && errors[name] ? 'is-invalid' : ''}
          id={id}
          autoComplete="off"
          autoFocus={true}
          startOpen={false}
          name={name}
          selected={value ? new Date(value) : null}
          title={name}
          aria-label={name}
          aria-required={isRequired}
          aria-invalid={touched[name] && errors[name] ? 'true' : 'false'}
          onChange={(val: any) => {
            setFieldValue(name, val);
          }}
          aria-describedby={
            touched[name] && errors[name] ? `${name}-error` : ''
          }
          customInput={
            <button
              className="border-0 bg-transparent"
              <i className="fa fa-calendar-alt" aria-hidden="true" />
            </button>
          }
        />

**Expected behavior**
Date picker popper is default closed after page loaded.

**Comment by vatsalyaagarwal** [comment]
Just the thought, try removing that property all together.

**Comment by alan-anchen** [comment]
Yes, I found this according to the source code.

**Comment by mrozema** [comment]
I'm using version 6.9.0 and am running into this issue. No matter what I try, the calendar always defaults to open. I've tried `startOpen={false}` and `autoFocus={false}` but it seems like the input is always getting focused when it the component mounts. I have 2 datepicker instances on the same page and the first one always gets focus right away and shows the calendar. I need to be able to keep the calendar hidden until the user selects the input for the first time.

My code is very basic:
```
<DatePicker
    id={props.id}
    selected={props.value}
    onChange={props.onChange}
    minDate={props.minDate}
    maxDate={props.maxDate}
    startOpen={false}
    autoFocus={false}
    />
```

This is how it looks when the component is mounted: 
![image](https://github.com/Hacker0x01/react-datepicker/assets/10343509/1b4ae34e-a777-412e-8051-80c80166a3fb)

But I want it to start like this: 
![image](https://github.com/Hacker0x01/react-datepicker/assets/10343509/27fc1fea-13ec-4494-ba38-4498ac90ab7e)

Any ideas?
