### ISSUE TITLE
Date Range doesn't work in Demo

### ISSUE THREAD

**Issue by wzup** [Hacker0x01/react-datepicker#267]
I want to select a date range, from ... to .... Like in hotel/tickets booking sites: 

![687474703a2f2f692e696d6775722e636f6d2f4c62414d6633442e706e67](https://cloud.githubusercontent.com/assets/3880497/11864163/327db192-a4d5-11e5-9536-1a5ca4c19e52.png)

I check Demo http://hacker0x01.github.io/react-datepicker/#example-8 but it seems it doesn't work, does it? I'd like to see the mechanic. Or it only doesn't work in Demo?

**Comment by rafeememon** [comment]
Hey @wzup, thanks for reporting this.  It appears to be an issue with the date `inRange` calculation.  Making a fix now.

**Comment by rafeememon** [comment]
Also working on an improvement to the example
