### ISSUE TITLE
is there a way to use filter time on future dates?

### ISSUE THREAD

**Issue by yanivkalfa** [Hacker0x01/react-datepicker#2673]
**Describe the bug**
So say that you want to filter time that it will filter any time that is smaller then current user time.
 basically `time >= currentTime`. 

`filterTime` time function only get a 24h window of the current user day - so no matter if you change to a different month or day you'll keep getting the exact same 24h datetimes objects.. which is extremely confusing and flawed.

with the same 24h range you cannot change future days or dates at all.

**Comment by JashG** [comment]
I was confused by this behavior as well. The workaround I went with was to use the `minTime` and `maxTime` prop. When the user selects a date, I wrote a function that will return the valid time range for the selected date, and then I just pass those values to the `minTime` and `maxTime` props.

**Comment by spostad7** [comment]
@JashG 
Could you please share your code how to manage minTime and maxTime?
I want to disable future time as well
