### ISSUE TITLE
Bug: Calendar auto re-opens when wrapped in a html label

### ISSUE THREAD

**Issue by codingyourlife** [Hacker0x01/react-datepicker#2676]
**Describe the bug**
The calendar popup with time does not auto-close after selecting a time

**To Reproduce**
When using the default example called "Custom time class name" from [https://reactdatepicker.com](https://reactdatepicker.com) and the `<DatePicker />` is wrapped in a label so:
`<label><DatePicker /></label>`
-> it behaves differently. concretely it does not close anymore after selecting a time.

**Expected behavior**
The `<DatePicker />` should behave identical if you wrap it in a label like `<label><DatePicker /></label>`

**Screenshots**
<img width="678" alt="grafik" src="https://user-images.githubusercontent.com/10122382/105077717-328e3080-5a8d-11eb-8df7-fedf4c793e56.png">

Problem in Chrome/Firefox and on Mobile so I guess everywhere.

**Additional context**
I guess the easiest would be to throw a custom error message if the component is wrapped in a label.

**Comment by Vovan-VE** [comment]
For better user experience we using portals ([example](https://reactdatepicker.com/#example-portal-by-id)). This also does solve the issue too.
