### ISSUE TITLE
Unable to install react-datepicker with React 17.0.1 and NPM version 7.4.0

### ISSUE THREAD

**Issue by james-work-account** [Hacker0x01/react-datepicker#2677]
**Describe the bug**
react-datepicker doesn't install when trying to install into a React 17 project. You get the following error:

```
$ npm install react-datepicker

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myapp@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0" from react-datepicker@3.4.1
npm ERR! node_modules/react-datepicker
npm ERR!   react-datepicker@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**To Reproduce**

1. `npx create-react-app myapp --use-npm`
2. `cd myapp`
3. `npm install react-datepicker`

**Expected behavior**
react-datepicker should install without any dependency tree errors

**Screenshots**
N/A (see terminal output above)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: N/A
- Version: latest (currently latest version of react-datepicker is 3.4.1)

**Comment by james-work-account** [comment]
Installing with `npm install react-datepicker --legacy-peer-deps` seems to be a workaround for now but ideally, react-datepicker would support the latest version of React out of the box. As the error from my original post says, "retry this command with --force, or --legacy-peer-deps to accept **an incorrect (and potentially broken) dependency resolution**" - it shouldn't be the default way of doing things.

**Comment by juliuscecilia33** [comment]
> Installing with `npm install react-datepicker --legacy-peer-deps` seems to be a workaround for now but ideally, react-datepicker would support the latest version of React out of the box. As the error from my original post says, "retry this command with --force, or --legacy-peer-deps to accept **an incorrect (and potentially broken) dependency resolution**" - it shouldn't be the default way of doing things.

This worked for me! Thank you so much :D

**Comment by IT-Magic-TS** [comment]
Installing with npm install react-datepicker --legacy-peer-deps seems to be a workaround for now but ideally, react-datepicker would support the latest version of React out of the box. As the error from my original post says, "retry this command with --force, or --legacy-peer-deps to accept an incorrect (and potentially broken) dependency resolution" - it shouldn't be the default way of doing things.

This worked for me..thanks

**Comment by Develliot** [comment]
This still seems to be an issue even though the latest major version 3.5.0 accepts React ^17 as a peer dependency

**Comment by h3rmanj** [comment]
Seems like even though support for react v17 was added in `react-popper@1.3.8`, it still depends on `create-react-context` which don't.

I opened an MR to fix it in react-popper, if it's merged the problem should go away.
https://github.com/popperjs/react-popper/pull/406

**Comment by rotabush** [comment]
> Seems like even though support for react v17 was added in `react-popper@1.3.8`, it still depends on `create-react-context` which don't.
> 
> I opened an MR to fix it in react-popper, if it's merged and released the problem should go away. [floating-ui/react-popper#406](https://github.com/floating-ui/react-popper/pull/406)
> 
> Edit: it't live now. This shouldn't be an issue anymore 🙂

I had this error pop up with react 18.0.0.
_C:\Users\...\OneDrive\Documents\Lyfe\web\lyfe_react> npm i --save react-datepicker
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: lyfe_react@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0 || ^17" from react-datepicker@4.7.0
npm ERR! node_modules/react-datepicker
npm ERR!   react-datepicker@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.__

**Comment by Nivethan-Ar** [comment]
> > Seems like even though support for react v17 was added in `react-popper@1.3.8`, it still depends on `create-react-context` which don't.
> > I opened an MR to fix it in react-popper, if it's merged and released the problem should go away. [floating-ui/react-popper#406](https://github.com/floating-ui/react-popper/pull/406)
> > Edit: it't live now. This shouldn't be an issue anymore slightly_smiling_face
> 
> I had this error pop up with react 18.0.0. _C:\Users...\OneDrive\Documents\Lyfe\web\lyfe_react> npm i --save react-datepicker npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! npm ERR! While resolving: lyfe_react@0.1.0 npm ERR! Found: react@18.0.0 npm ERR! node_modules/react npm ERR! react@"^18.0.0" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer react@"^16.9.0 || ^17" from react-datepicker@4.7.0 npm ERR! node_modules/react-datepicker npm ERR! react-datepicker@"*" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution.__

i'm also getting this error on React 18

**Comment by martinraabe** [comment]
Hi, same for me with react 18.0.0:

raabem@CPX-5HOJYVZV5WK:~/workspace/ta$ npm install react-datepicker
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ta@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0 || ^17" from react-datepicker@4.7.0
npm ERR! node_modules/react-datepicker
npm ERR!   react-datepicker@"^4.7.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/raabem/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/raabem/.npm/_logs/2022-04-29T23_04_25_912Z-debug-0.log

I can install it with
` npm install react-datepicker --legacy-peer-deps`

When I start my app I get the issue: 
Server Error
TypeError: Cannot read properties of null (reading 'useState')

**Comment by romanoducic** [comment]
The same error occurs on react 19
