### ISSUE TITLE
Demos on the site with dropdown are broken

### ISSUE THREAD

**Issue by Ugoku** [Hacker0x01/react-datepicker#2688]
**Describe the bug**
Several examples on reactdatepicker.com are broken, I've listed them below/

**To Reproduce**

1. Go to https://reactdatepicker.com
2. Scroll down to 'Month dropdown'
3. Click the input so the calendar pops up
4. Click on the month dropdown
4. See error: `Error: Minified React error #188`

This also goes for 'Month dropdown short month', 'MonthYear dropdown', 'Multiple months with year dropdown', 'Year dropdown'. 'Year select dropdown' is not affected.

**Expected behavior**
The dropdown should open

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Ubuntu 20.10
- Browser: Vivaldi 3.5

**Smartphone (please complete the following information):**

- Device: Xiaomi Mi A1
- OS: Android 9
- Browser: Chrome 87

**Additional context**
Greetings from Eelde to the people in Groningen ;)

**Comment by dschenck** [comment]
On Mac OS
Browser Chrome Version 87.0.4280.141 (Official Build) (x86_64)

![Screen Shot 2021-02-28 at 12 53 51](https://user-images.githubusercontent.com/6804043/109419219-48640f00-79c4-11eb-8cd1-fd8602fe91b3.png)

**Comment by Ugoku** [comment]
This appears to have been fixed now.
