### ISSUE TITLE
Time input field cuts AM/PM text due to short width

### ISSUE THREAD

**Issue by alejo4373** [Hacker0x01/react-datepicker#2697]
The default width for the time input field when `showTimeInput=true` is currently set to `85px` [in the src seen here](https://github.com/Hacker0x01/react-datepicker/blame/1605d79c175d5448d2e1ce63e71fc1202bc50a04/src/stylesheets/datepicker.scss#L257) which cuts the AM/PM text as seen in the screenshots below.

**Screenshots**

### Firefox: 81.0.2 (64-bit)
![Screen Shot 2021-01-23 at 8 23 08 PM](https://user-images.githubusercontent.com/18352555/105618930-148d3c80-5dbb-11eb-8655-fe7527aaf690.png)

### Chrome: Version 88.0.4324.96 (Official Build) (x86_64)
![Screen Shot 2021-01-23 at 8 22 45 PM](https://user-images.githubusercontent.com/18352555/105618935-18b95a00-5dbb-11eb-8ea1-bb982edb55c4.png)

**To Reproduce**
1. Go to https://reactdatepicker.com/#example-input-time
2. Click on the Date Picker
3. Inspect the time input and compare to the screenshots above

**Expected behavior**
Input field displays all its content without cutting out any of its text.

I would suggest removing the `85px` and let the browser decide the width necessary. This is what I'm doing in my override of the CSS using inline styles with
```jsx
<style>{`
  .react-datepicker__input-time-container 
  .react-datepicker-time__input-container 
  .react-datepicker-time__input input {                    
     width: unset
  }
`}</style>
```
I am wondering if anyone else is experiencing this issue.

**Desktop**
- OS: macOS Catalina, Version 10.15.7
- Browsers
  - Chrome  Version 88.0.4324.96 (Official Build) (x86_64)
  - Firefox 81.0.2 (64-bit)

**Additional context**
* This seems to affect Firefox and Chrome. Safari V.14.0.1 shows a 24 hour clock so the AM/PM text is never there.
* On mobile(iPhone SE) Chrome and Safari display the native time picker and 85px is more than enough to show all text content + it seems the iPhone has a smaller font-size for inputs.
* This feature/variant was introduced in [PR #1591](https://github.com/Hacker0x01/react-datepicker/pull/1591) by @gautam-pahuja

**Comment by chopify** [comment]
Thank you for the temporary fix.  I'm am seeing the same issue after PR #1591
