### ISSUE TITLE
Date Range Presets

### ISSUE THREAD

**Issue by yofret** [Hacker0x01/react-datepicker#2704]
Hey Thanks for this Awesome plugin for React, it is Really outstanding! I wasn't sure how to file this since it is not a request or an issue, I just wanted to know if what I'm trying to accomplish is really posible with the current state of the calendar

**Is your feature request related to a problem? Please describe.**
I'm trying to create Range presets for the Date Range, and see the preset reflected on the calendar, these presets would be applied via buttons, I've tried to set `startDate` and `endDate` state but this doesn't seem trigger the range color highlight, this highlight is only applied when interacting via clicks

**Describe the solution you'd like**
No real preference, I'm want to know if it is possible, or no

**Additional context**
Here is a picture of what I'm trying to achieve
<img width="732" alt="Screen Shot 2021-01-29 at 5 09 03 PM" src="https://user-images.githubusercontent.com/11755802/106332386-b649d900-6254-11eb-8158-62d619ca6a00.png">

This is an sketch rather than a design, the buttons bellow the calendar would select presets, and would be based on current date.

Thanks!, Any insight would be much appreciated!

**Comment by singleseeker** [comment]
any update?
