### ISSUE TITLE
Time selection doesn't work from keyboard

### ISSUE THREAD

**Issue by vatsalyaagarwal** [Hacker0x01/react-datepicker#2706]
**Describe the bug**
Time selection doesn't work on pressing enter

**To Reproduce**
1. run the date picker with witch "showTimeSelect" 
2. tab to the time selection list
3. try to press enter on the time 
 
**Expected behaviour**
Time should get selected on pressing enter

**Comment by martijnrusschen** [comment]
Fixed in #3005
