### ISSUE TITLE
Blur timeout bug

### ISSUE THREAD

**Issue by PeyveAndrew** [Hacker0x01/react-datepicker#271]
Hi!

if parent component get destroyed, after datepicker lost focus, there is bug with timeouts (Warning: setState(...): Can only update a mounted or mounting component).

You need to clear timeouts in datepicker.jsx

**Comment by RSO** [comment]
Thanks! Sounds reasonable and easy to fix.

**Comment by martijnrusschen** [comment]
@rafeememon Do you think this is fixed by #319?

**Comment by rafeememon** [comment]
Yup it is!
