### ISSUE TITLE
Some Classes not coming in Month and Quarter Range Pickers

### ISSUE THREAD

**Issue by teja-centime** [Hacker0x01/react-datepicker#2718]
**Describe the bug**

The following classes are not coming for the start date when the user is selecting "start" month or quarter in both the month and quarter **range** picker in a single calendar layout - that means when using the prop **selectsRange** as true :-

1. react-datepicker__month--in-range 
2. react-datepicker__month--range-start
3. react-datepicker__quarter--range-start
4. react-datepicker__quarter--range-start

**To Reproduce**
1. Props:- Use DatePicker with selectsRange as true and showMonthPicker as true and disabledKeyboardNavigation as true 2. Click on any start date - it will not be highlighted since no classes are added to this. See inspect element
3. If you hover on some months after this start month, the classes like `.react-datepicker__day--in-selecting-range` are also not getting added if you compare the same behavior with date range picker. 
4. But if user selects an end date, both start date and end date are highlighted then.

**Expected behavior**
Whenever user clicks on a start month or quarter, that should have some classes added to it to identify it.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] : MAC OS
- Browser [e.g. chrome, safari]: Firefox & Chrome
- Version [e.g. 22] : Above 60

**Comment by teja-centime** [comment]
@gautam-pahuja  Any thoughts on this ?

**Comment by teja-centime** [comment]
Anybody please check if it is in the pipeline or already solved ? Because, I'm not able to see the changes in latest version

**Comment by Ross-Gargett** [comment]
I am seeing this same issue.
