### ISSUE TITLE
Year Range Picker

### ISSUE THREAD

**Issue by teja-centime** [Hacker0x01/react-datepicker#2719]
**Describe the solution you'd like**

Its an excellent plugin with lot of options and customizations especially month and quarter range pickers. In addition to that,it would be great if we have the year range picker also.

**Describe alternatives you've considered**
This is the best solution I've found with simple yet with lot of customizable options for range pickers. I've tried airbnb, material ui range pickers, bootstrap range picker, advanced react range picker plugins etc.

**Comment by Antoshkiv** [comment]
Need this feature too!
