### ISSUE TITLE
How can I change the css in my browser?

### ISSUE THREAD

**Issue by Xurma2** [Hacker0x01/react-datepicker#275]
As soon as I translate the focus to the console. The window disappears.

**Comment by martijnrusschen** [comment]
You can try setting focus on true for the time being. This should set the calendar open when loading the page. See https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L44

**Comment by Xurma2** [comment]
Its not worked

**Comment by martijnrusschen** [comment]
What about a custom trigger that triggers it `$('.datepicker__input').click()`

**Comment by RSO** [comment]
I can see how this could be problematic. For now the easiest way I can see is to edit the CSS and then re-focus the input. That should work, right?

distant-future-thinking: It would be awesome to have some sort of stylesheet-playground, allowing for easy composition of your own stylesheets in the docs.

**Comment by stephenpascoe** [comment]
For reference @martijnrusschen's solution works: `$('.datepicker__input').click()`
