### ISSUE TITLE
Using monthsShown and minDate together is not working as expected

### ISSUE THREAD

**Issue by nayrl** [Hacker0x01/react-datepicker#2753]
**Describe the bug**

When monthsShown is set, the navigation arrows are enabled and the user can view 1 month in the past depending on whats set in minDate e.g if my minDate is set to today (18-02-21) and the user selects a date in march the prev navigation arrow is enabled and the user can navigate to January.

**To Reproduce**

1. Given the following implementation 
```javascript
const [startDate, setStartDate] = useState(new Date());
  const today = new Date();
  return (
    <DatePicker
      inline
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      monthsShown={2}
      minDate={today}
    />
  );
```
2. Previous arrow is not enabled, Next arrow is enabled
3. Click any date in March
4. Previous arrow is now enabled and the user can navigate back to January

**Expected behavior**
If the minDate is set to `new Date("2021", "01", "18")` then the user should not be able to view months previous to February.

**Code example**
https://codesandbox.io/s/react-datepicker-multi-months-uhktw

**Comment by dffUqp** [comment]
There is the same problem.

I know it's been a long time, but if you found a solution, could you please share it?😀
