### ISSUE TITLE
need to stop autocorrect function when the date is invalid

### ISSUE THREAD

**Issue by alan-anchen** [Hacker0x01/react-datepicker#2756]
**Is your feature request related to a problem? Please describe.**
We need input date manually and allow the invalid date displaying(we will give validation message but not autocorrect)

**Describe the solution you'd like**
Provide a property to control autocorrect function.

**Describe alternatives you've considered**

**Additional context**

**Comment by NikolaStanisavljevic** [comment]
+ 1 on this. So far soulution is to disable it with 
`onChangeRaw={e => e.preventDefault()}`
But then you cant insert your own custom validation if that event is disabled

**Comment by alan-anchen** [comment]
> * 1 on this. So far soulution is to disable it with
>   `onChangeRaw={e => e.preventDefault()}`
>   But then you can't insert your own custom validation for invalid input if that event is disabled

Yes, the trouble is that we need to input manually.

**Comment by NikolaStanisavljevic** [comment]
Workaround that could help is to do custom validation onChangeRaw, and add another check for invalid date onBlur, and if so it will reset field and show error. Pseudo code: 

`   <DatePicker
                onChange={onChange}
                onBlur={(event) => customBlur(event, onChange)}
                onChangeRaw={(event) => {
                  customValidation(event);
                }}
                dateFormat={format}
                placeholderText={placeholder}
                className="form-control"
              />`

**Comment by alan-anchen** [comment]
> Workaround that could help is to do custom validation onChangeRaw, and add another check for invalid date onBlur, and if so it will reset field and show error. Pseudo code:
> 
> ` <DatePicker onChange={onChange} onBlur={(event) => customBlur(event, onChange)} onChangeRaw={(event) => { customValidation(event); }} dateFormat={format} placeholderText={placeholder} className="form-control" />`

But we should stop the autocorrect function, because the autocorrent date is not the one that the user wanted.

**Comment by NikolaStanisavljevic** [comment]
Yes, but there is no way to stop it. Instead i let it happen
and immediately after reset field to empty and show error that invalid date
is entered.

**Comment by alan-anchen** [comment]
This just is the trouble.

**Comment by replaystudiosgames** [comment]
Hi,
I solved this problem using customInput property.
I created my own custom component as a Datepicker wrapper. In it I used a simple button as customInput. Doing so, I could open calendar just clicking on that button (in my case i used a button styled with a font awesome calendar icon).
Furthermore i created an input type="text" to manage date text.
You only have to manage "selected" and "onChange" properties.
Set as "selected" the date you saved in your internal state and set as "onChange" a function that changes that state based on what date you selected in your calendar.

This will allow you to manage data selection and to set text into a input type="text".

Almost done! To let user type in the input type="text" and to let datepicker know you changed the date, you need to manage the onChange event of the input type="text".
In this function, you need to check text validity (if it's a valid date or not) and then set your date as internal state (the same state set as "selected" property).


Pseudo code to help you understand better:
`
const DatepickerWrapper = () => {
   // save date state
   const [date, setDate] = useState();

const renderInputText = () => {
   // render your input type text
   return <input type="text" onChange="(text) => onChangeText(text)" />
}
function onChangeText(text) {
   // check if text set in input type text is a valid date
   if(isValidDate) {
      setDate(new Date(text));
   }
}

const renderCustomInput= (props, ref) => (
   // render button with calendar icon
   // do not forget this ref or calendar won't open. Check customInput section in documentation
   <div ref={ref}>
   // render button with icon
   </div>
}
// do not forget this forwardRef or calendar won't open. Check customInput section in documentation
const DatepickerCalendarButton = forwardRef(renderCustomInput);

const onDatepickerChange = (value) => {
  // check if text set in input type text is a valid date
   if(isValidDate) {
      setDate(new Date(text));
   }
}
return (
   <DatePicker
      selected={date}
      onChange={value => onDatepickerChange(value)}
      customInput={<DatepickerCalendarButton />}
   />
   );
}`

Further suggestion: i also checked text in input type="text" length and property "strictParsing" to reach the behave you are asking for.

Hope this could help.

**Comment by replaystudiosgames** [comment]
> **Is your feature request related to a problem? Please describe.**
> We need input date manually and allow the invalid date displaying(we will give validation message but not autocorrect)
> 
> **Describe the solution you'd like**
> Provide a property to control autocorrect function.
> 
> **Describe alternatives you've considered**
> 
> **Additional context**

Hi,
I solved this problem using customInput property.
I created my own custom component as a Datepicker wrapper. In it I used a simple button as customInput. Doing so, I could open calendar just clicking on that button (in my case i used a button styled with a font awesome calendar icon).
Furthermore i created an input type="text" to manage date text.
You only have to manage "selected" and "onChange" properties.
Set as "selected" the date you saved in your internal state and set as "onChange" a function that changes that state based on what date you selected in your calendar.

This will allow you to manage data selection and to set text into a input type="text".

Almost done! To let user type in the input type="text" and to let datepicker know you changed the date, you need to manage the onChange event of the input type="text".
In this function, you need to check text validity (if it's a valid date or not) and then set your date as internal state (the same state set as "selected" property).

Pseudo code to help you understand better:
`
const DatepickerWrapper = () => {
// save date state
const [date, setDate] = useState();

const renderInputText = () => {
// render your input type text
return
}
function onChangeText(text) {
// check if text set in input type text is a valid date
if(isValidDate) {
setDate(new Date(text));
}
}

const renderCustomInput= (props, ref) => (
// render button with calendar icon
// do not forget this ref or calendar won't open. Check customInput section in documentation

// render button with icon
} // do not forget this forwardRef or calendar won't open. Check customInput section in documentation const DatepickerCalendarButton = forwardRef(renderCustomInput);
const onDatepickerChange = (value) => {
// check if text set in input type text is a valid date
if(isValidDate) {
setDate(new Date(text));
}
}
return (
<DatePicker
selected={date}
onChange={value => onDatepickerChange(value)}
customInput={}
/>
);
}`

Further suggestion: i also checked text in input type="text" length and property "strictParsing" to reach the behave you are asking for.

Hope this could help.

**Comment by alan-anchen** [comment]
> if(isValidDate) {
> setDate(new Date(text));
> }

Thanks for your help! Actually, I had implemented it as the same way you provided before, but encountered another problem. Anyway, this is a good solution. Thanks again!
