### ISSUE TITLE
Support use custom header with datepicker and time select

### ISSUE THREAD

**Issue by zongwei007** [Hacker0x01/react-datepicker#2765]
I use `renderCustomHeader` property to add button which use to switch year. It worker well before version 3.5.0, but after commit 349cc994ba1748352a3194c35745a8c2a5ac8910, this feature is disable when use with `showTimeSelect` property.

What is the reason to disable renderCustomHeader feature and it will be re-enable?

That is the example that I use customer header for:
![image](https://user-images.githubusercontent.com/1511004/108993764-f5454000-76d5-11eb-9fd9-494cee572497.png)

**Comment by winlx** [comment]
Problem is here https://github.com/Hacker0x01/react-datepicker/commit/349cc994ba1748352a3194c35745a8c2a5ac8910

**Comment by winlx** [comment]
I think this is a bug. It is breaking change.

**Comment by redoy11** [comment]
Feels like a bug. I have not able to use the `renderCustomHeader` property as well.

**Comment by andrujoh** [comment]
I have this issue as well. `renderCustomHeader` does not show when using `showTimeSelect`.
It is working in version 3.4.1 but not in 3.5.0 and 3.6.0.

**Comment by enflaer** [comment]
@zongwei007 Issue can be closed.

**Comment by zongwei007** [comment]
> @zongwei007 Issue can be closed.

OK, THX.
