### ISSUE TITLE
withPortal doesn't work properly with iPhone 6/7/8 Plus. (Tested on Device Emulator on Chrome)

### ISSUE THREAD

**Issue by Yusuf023** [Hacker0x01/react-datepicker#2766]
Using time selector with the "withPortal" prop pushes the time selector down from the date selector.

**Steps to reproduce:**
On the demo page, https://reactdatepicker.com/. In the first example, add the properties, **withPortal** and **showTimeSelect**. 
Go to the device emulator on chrome, select iPhone 6/7/8 Plus and try to open the date picker.

**Comment by mayowaadegbola** [comment]
Noticed the same also.  Were you able to fix?
<img width="313" alt="Screenshot 2021-03-09 at 07 53 21" src="https://user-images.githubusercontent.com/17248258/110430401-9eb00c80-80ac-11eb-9f44-262ee0b016e3.png">
