### ISSUE TITLE
Import from react-datepicker duplicates date-fns modules

### ISSUE THREAD

**Issue by alexandrchebotar** [Hacker0x01/react-datepicker#2769]
**Describe the bug**
Because of direct import from `date-fns/[module]` when you import `react-datepicker` with es6 import you add that modules to bundle.
Same time if you import something from `date-fns` or other library that uses `date-fns`, for example `date-fns-tz`, you add to bundle modules from `date-fns/esm`. As a result you duplicate some `date-fns` modules.

**To Reproduce**

1. Import `react-datepicker`:
 ```
import DatePicker from "react-datepicker";
```
2. Import something from `date-fns`:
```
import { parseISO } from "date-fns";
import { format, utcToZonedTime } from 'date-fns-tz';
```
3. Make build.
4. See duplicated modules in bundle.

**Expected behavior**
`import DatePicker from "react-datepicker"` should add modules from `date-fns/esm/`

**Screenshots**
![image](https://user-images.githubusercontent.com/44335524/109433014-bd603480-7a16-11eb-8b91-ac4d8e1786f3.png)

**Additional context**
React Date Picker version - 3.6.0.

**Comment by tu4mo** [comment]
This is a bug in [date-fns](https://github.com/date-fns/date-fns/issues/2207).

**Comment by AlexandrChebotar** [comment]
@tu4mo these are different issues.

**Comment by tu4mo** [comment]
@AlexandrChebotar Oh, sorry. Was looking at the wrong thing.

**Comment by himynameistimli** [comment]
@AlexandrChebotar have you found a temporary workaround to force the use of a common date-fns module?

**Comment by magiskboy** [comment]
I hope that this issue will be resolved in near future

**Comment by magiskboy** [comment]
I think rc-picker uses star import for all locales of date-fns 
https://github.com/react-component/picker/blob/master/src/generate/dateFns.ts#L26

**Comment by gabycperezdias** [comment]
Any updates on this?
