### ISSUE TITLE
customTimeInput does not render

### ISSUE THREAD

**Issue by karltaylor** [Hacker0x01/react-datepicker#2775]
I'm trying to implement `react-datepicker` with a `customTimeInput` but using the example in a Next.js app it does not render.

Annoyingly this works on a simple [codesandbox](https://codesandbox.io/s/nervous-violet-bmjbm?file=/src/App.js)

```tsx
import { useState } from "react";
import "react-datepicker/dist/react-datepicker.css";
import ReactDatePicker from "react-datepicker";

const Test = () => {
  const [startDate, setStartDate] = useState<Date>(new Date());

  const ExampleCustomTimeInput = ({ date, value, onChange }) => {
    console.log("here?"); // does not fire
    return (
      <input
        value={value}
        onChange={(e) => onChange(e.target.value)}
        style={{ border: "solid 1px pink" }}
      />
    );
  };

  return (
    <div>
      <ReactDatePicker
        showTimeSelect
        selected={startDate}
        onChange={(date) => setStartDate(date)}
        customTimeInput={ExampleCustomTimeInput}
      />
    </div>
  );
};

export default Test;
```

![Screenshot 2021-03-02 at 12 14 51](https://user-images.githubusercontent.com/6763109/109647178-ebe22a80-7b50-11eb-829a-491e8fbd5208.png)

**Comment by kaeland** [comment]
@karltaylor I'm having the same issue. Did you find a fix for this?

**Comment by darfilp** [comment]
Did you find a fix for this?

**Comment by darfilp** [comment]
@karltaylor Hi Did you find a fix for this?

**Comment by darfilp** [comment]
@karltaylor or @kaeland Hi!
Have you found a solution??
