### ISSUE TITLE
[Feature Request] Different export options for bundle size

### ISSUE THREAD

**Issue by madeleineostoja** [Hacker0x01/react-datepicker#2776]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/Hacker0x01/react-datepicker/issues/2652 it would be great if `react-datepicker` offered different exports that supported subsets of features. For example I only use the `inline` calendar mode, so bundling Popper and all the associated form etc logic is unnecessary bloat making `react-datepicker` almost as bad as `react-dates`.

**Describe the solution you'd like**
Either different exports that have the same interface as now, or (for example), an `InlineDatePicker` component export rather than an `inline` prop on the full datepicker.

**Describe alternatives you've considered**
None avaiable

**Additional context**
`react-datepicker` is currently the single biggest dependency in our entire application, even with the move to `date-fns`, and the entire point of moving to it from `react-dates` was to get away from the weight of moment.js

**Comment by jvanderen1** [comment]
Still interested in this issue. Doesn't the `sideEffects` property in the `package.json` automatically remove some of these dependencies at bundle time?

**Comment by RobSchilderr** [comment]
Has anyone found a way to reduce the bundle size?

**Comment by CalvinD3v** [comment]
any feedback on this would be greatly appreciated.

**Comment by zjye-idealhub** [comment]
i migrated from react-dates to react-datepicker, but at the end the size very similar

**Comment by lucajung** [comment]
+1

**Comment by nicolasconnault** [comment]
Yeah it's a bit on the fat size :)

![Screenshot 2023-10-30 at 9 53 57 am](https://github.com/Hacker0x01/react-datepicker/assets/79558/5ce97440-a98f-4974-9423-d940971037dd)
