### ISSUE TITLE
Adding classes to the tether overlay

### ISSUE THREAD

**Issue by kumarharsh** [Hacker0x01/react-datepicker#280]
I'm using Radium and trying to add custom styles to the datepicker. Thankfully I'm using webpack so bundling the css files within the code is a breeze. To add custom styles, I am using the `<Style>` [component](https://github.com/FormidableLabs/radium/tree/master/docs/api#style-component) of Radium, which injects a Style node within the component's DOM.

I am facing a problem regarding the targeting of styles to the **tether overlay** which opens up on clicking the input. The `<Style>` component has a `scopeSelector` to add custom class to target the styles, but the DatePicker unfortunately does not accept a `className` for the overlay like it does for the input.

Can you add a prop called `overlayClassName` or something like that, which adds a class to the overlay too?

**Edit**: Nevermind, it slipped my mind that I don't even need to specify the scopeSelector :stuck_out_tongue_closed_eyes:  since I want to style ALL the Datepickers anyways.
But maybe it'd be a useful feature to have to scope styles properly?

**Comment by martijnrusschen** [comment]
Hi @kumarharsh, 

I had a hard time understanding what you wanted to achieve, but looks like you found it out. All styles are prefixed with `datepicker__ to scope it correctly according to BEM. (See https://github.com/Hacker0x01/react-datepicker/blob/master/src/stylesheets/datepicker.scss). Does this work for you?

**Comment by kumarharsh** [comment]
Ah, sorry for not being clear.

Basically what I am suggesting is that: would it be viable to add another propType to the datepicker which can add some user-defined class to the `datepicker` overlay?

**Comment by martijnrusschen** [comment]
What's the class you want to style. Can you provide the current class the overlay has, and is there a reason we should allow custom classes for that overlay?

**Comment by kumarharsh** [comment]
Right now, there are the classes applied on the Datepicker overlay:

`datepicker__container tether-element tether-enabled tether-abutted tether-abutted-left tether-element-attached-top tether-element-attached-left tether-target-attached-bottom tether-target-attached-left`

All of them are the ones supplied by `tether`, except for the `datepicker__container` which is specific to the picker.

I'm suggesting that you allow a user to *also* specify a class which can be added to this list, say something like: `holiday_picker`, `workday_picker`, etc, so that they can style two pickers differently *in the same app*. Right now users can have only ONE style for the datepicker overlay per app.

Again, it's just a suggestion, and I don't require it myself anymore because I will not have two different styled overlays in my app.

**Comment by martijnrusschen** [comment]
Right, I get it. So the goal you want to achieve here is to style 2 datepickers differently. IMO, a really specific use case but I'll see if I can work out something.

**Comment by rafeememon** [comment]
Let's handle this in #377
