### ISSUE TITLE
showFourColumnMonthYearPicker does not work

### ISSUE THREAD

**Issue by empav** [Hacker0x01/react-datepicker#2818]
**Describe the bug**
Can't make **showFourColumnMonthYearPicker** option work.

**To Reproduce**
I'm using this config for the date picker:
`
<DatePicker
    open={open}
    portalId={isMobile ? START_DATE_PORTAL : undefined}
    showMonthYearPicker
    showFourColumnMonthYearPicker
    selected={selectedDate}
    onChange={handleDateChange}
    dateFormat="MM/yyyy"
    minDate={minDate}
    maxDate={maxDate}
    placeholderText={getTranslationByKeyAndLocale(
      'DatePicker_Label1',
      language
    )}
  />
`

**Expected behavior**
I'd have expected to have the months on a 4-column layout but I get this instead:
![Capture](https://user-images.githubusercontent.com/15023919/111615147-b0965b80-87e0-11eb-90ad-d4be8b0dbe2d.PNG)
What am I missing?

**Comment by berzavlu** [comment]
I had the same problem, but it solved upgreating the version. i had instaled versión 3.0.0 but in the 3.5.0 recently was added 4 columns for month picker. Now i am using the last version 3.7.0 👍
