### ISSUE TITLE
DatePicker requires date selection to be done twice to select

### ISSUE THREAD

**Issue by MorenoMdz** [Hacker0x01/react-datepicker#2828]
**Describe the bug**
When you select a date, the whole calendar container moves to the side a few pixels and you need to reselect the date. Only then the wanted date is actually selected.

**Expected behavior**
A single click to select the correct date.

**Additional context**
The behavior of moving a few pixels is happening in all 4 date pickers. These are distributed in a flex column container, being each picker input inside a flex row with its label.

The component is set as:
```javascript
    <DatePicker
      selected={dueDate}
      onChange={setDueDate}
      dateFormat="MMM dd, yyyy"
      placeholderText="Select the End Date"
      minDate={new Date(startDate) || new Date()}
    />
```

https://user-images.githubusercontent.com/29472480/112237405-5f8fc880-8c21-11eb-9bfa-b9cc589695cb.mov

What could be causing the container to dance around and the date to not be registered? The click event is happening.

Update: it looks like I was able to solve it, I had a different input style affecting this one, in my case removing the padding on focus fixed it. The padding-left was causing the issue as the calendar container is positioned related to the text alignment in the input.

```css
  input {
    width: 240px;
    text-align: center;
    text-transform: none;
    &:focus {
      padding-left: 0;
    }
  }
```

**Comment by moombaPEX** [comment]
I had a similar issue when the datepicker appears above the input element. I was able to fix by passing `fixedHeight` as a **prop** to the datepicker.
