### ISSUE TITLE
open calander via external component?

### ISSUE THREAD

**Issue by aaronmgdr** [Hacker0x01/react-datepicker#283]
Id like to have a little calendar icon next to the select box. When it is clicked id like the calender selection to open. If this was a custom component id just included the icon in it and add an onclick, or take an optional prop / children. 

Is there a good way to do this with react-datepicker non hackily?

**Comment by martijnrusschen** [comment]
Nice suggestion, I don't think we have any non-hacky ways to do this at this moment. How would you like to implement this. Any suggestions?

**Comment by rafeememon** [comment]
I've been thinking about how this could work by having open/closed state managed by a prop rather than state.  Then the consumer has complete control over when it is open.  I'll experiment around with this.

**Comment by fremn** [comment]
two ways I think could work are using optional children prop
```
<DatePicker  selected={this.props.startDate} onChange={this.onChangeStart} >
<i className="cal-icon"/>
</DatePicker>
```

or using an optional Icon prop

```
<DatePicker  selected={this.props.startDate} onChange={this.onChangeStart} icon={<i className="cal-icon"/>} >
```

internally something like 
```
icon() {
   if (this.props.icon) {
      <span onClick={this.onInputClick}> {this.props.icon} </span>
   }
}
render() {
   return (
      <div className="datepicker__input-container">
        <DateInput
          ref="input"
          id={this.props.id}
          name={this.props.name}
          date={this.state.selected}
          dateFormat={this.props.dateFormat}
          focus={this.state.focus}
          onFocus={this.handleFocus}
          onBlur={this.handleBlur}
          handleClick={this.onInputClick}
          handleEnter={this.hideCalendar}
          setSelected={this.setSelected}
          invalidateSelected={this.invalidateSelected}
          placeholderText={this.props.placeholderText}
          disabled={this.props.disabled}
          className={this.props.className}
          title={this.props.title}
          readOnly={this.props.readOnly}
          required={this.props.required}
          tabIndex={this.props.tabIndex} />
        {clearButton}
        {this.props.disabled ? null : this.calendar()}
        {this.icon()} 
      </div>
    );
}
```

**Comment by martijnrusschen** [comment]
Yeah, opening/close via prop sounds a good idea.

**Comment by fremn** [comment]
yep props sounds great to me.

**Comment by gaastonsr** [comment]
Why not add an open method to the component?

Also, is somebody working on this? I can make a PR.

**Comment by martijnrusschen** [comment]
Would be great if you could kick this off!

**Comment by RSO** [comment]
I like the idea of having an optional icon in the input to open the calendar, I've seen this before in other places and it feels like good UX to have.

> Why not add an open method to the component?
How do you see this work?

**Comment by benwill** [comment]
Is there any progress with this?

**Comment by fremn** [comment]
@benwill not sure. i switched to `react-date-picker` so stopped paying attention

**Comment by matias91** [comment]
I'm trying to do something like this, with no success.
Any news?

**Comment by GrizliK1988** [comment]
Hi @fremn, @matias91.

You can do what you need by assigning **ref** property to datepicker component and after that calling **this.refs.nameOfRef.setOpen(true)**.

Than's it.

**Comment by M3lkior** [comment]
Or with the [React ref-callback attribute](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute) : 

```
<DatePicker {...this.props} className="form-control " ref={(c) => this._calendar = c}/>
<InputGroup.Addon><i className="fa fa-calendar" onClick={() => this._calendar.setOpen(true)}/></InputGroup.Addon>
```

@RSO @martijnrusschen , the Datapicker API is describred somewhere ?

**Comment by martijnrusschen** [comment]
@M3lkior The datepicker API is described in https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md

**Comment by M3lkior** [comment]
Not the setOpen function for example.
This doc only list availables props, without descriptions or uses examples. Is it possible to improve this doc ?

Thanks in advance.

**Comment by gaastonsr** [comment]
Because it's not an official API. You just wen into the inners of the component to open it.

Ideally you shouldn't have to do that but until something official comes up I think it's ok.

**Comment by schickling** [comment]
This should fix the problem: https://github.com/Hacker0x01/react-datepicker/pull/531

**Comment by waynebrantley** [comment]
Initially, would be nice to just specify if it is open via props.

**Comment by rafeememon** [comment]
Agreed that an `open` prop is the way to go.  See my comment on https://github.com/Hacker0x01/react-datepicker/pull/531#issuecomment-234735758 for potential complications with the implementation

**Comment by waynebrantley** [comment]
" this only covers the initial open state" - I think that would at least be a good start.  Then do another feature to honor it in more places.  I tried to do an 'in place' edit with your control.  Everything works great, but it requires an extra click.  

What people are after for the open is a 'control' that opens the datepicker other than picking.  Like the React-Date-Picker component has a built in little icon that you click to open the date picker.  You do not have to open it...you can just edit the date.  That would be a better 'larger' feature (which is easier to enable with this open prop).

Nice component.

**Comment by splendidtrade** [comment]
@M3lkior : tried using 'refs' for opening the calender from external component - but onBlur is not firing on close of the calender - any ideas?

**Comment by wwwebman** [comment]
So, there is no any progress with adding `isOpen` prop or something?

**Comment by rafeememon** [comment]
@wwwebman, contributions to implement this are welcome

**Comment by aaronmgdr** [comment]
based on @schickling comment gonna close this
