### ISSUE TITLE
Cannot read property 'componentNode' of undefined 

### ISSUE THREAD

**Issue by charlies96** [Hacker0x01/react-datepicker#2832]
**Describe the bug**
 When DatePicker component is set to open={false} and down/up keyboard keys are pressed in the input field the following error is thrown:
 `Uncaught TypeError: Cannot read property 'componentNode' of undefined`
 
 **To Reproduce**
 
 1. Go here: https://codesandbox.io/s/distracted-montalcini-0tzfh
 2. Click on the date input
 3. Press up/down arrows
 
 **Expected behavior**
 No error thrown
 
 **Screenshots**
 
 **Desktop (please complete the following information):**
 
 * OS: macOS
 * Browser chrome
 * Version 80

**Comment by mztnnrt** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/2082#issuecomment-1539352872
