### ISSUE TITLE
Date delimeters/input mask when typing manually

### ISSUE THREAD

**Issue by WojtechK** [Hacker0x01/react-datepicker#2840]
**Current solution:** 
I have datepicker with possibility to manually type date in the input. To handle this and prevent errors, currently I'm getting input value, onChange handler is validating if format is **MM/DD/YYYY** or **YYYY/MM/DD**, and only then setting new date value. 

**Problem**
I'm validating ONLY for slash sign ` / ` as a delimeter between day, month and year, user has to type ` / `  it manually.

**Would like to have:**
To ensure better UX and prevent from errors I'd like to have kind of "placeholder" or autocomplete for delimiter like ` - ` or ` / `. So when typing eg. 2021 input would automatically concatenate delimeter sign  `2021-` and I can type further.

Is somehow possible to do such trick with current options/props or new feature is required? Thanks in advance for any tips!

**Comment by WojtechK** [comment]
I found solution myself, maybe will help someone. Keyword to search for is _input mask_. There're libraries for that, for my case I added **react-maskedinput** and DatePicker got customInput prop for personalization.
` import MaskedInput from 'react-maskedinput';
<DatePicker 
   customInput={<MaskedInput mask="11/11/1111" placeholder="MM/DD/YYYY" />}
//otherProps
`

**Comment by catamphetamine** [comment]
My variant:

```js

import InputMask from 'react-input-mask';

    <DatePicker
      ...
      placeholderText="MM/DD/YY"
      dateFormat="MM/dd/yy"
      customInputRef="inputRef"
      customInput={<InputMask mask="99/99/99" />}
    />

**Comment by konerunaveena** [comment]
HI i need masked input only for time in 12 hour format with AM and PM.
i tried mask with [' ',
          /\d/,
          /\d/,
          `${timeDelim}`,
          /\d/,
          /\d/,
          ' ',
          /[AaPp]/i,
          /[Mm]/i,]

but i could get the proper mask for time.
any suggestion please .

**Comment by omegastripes** [comment]
Using `PatternFormat` from [react-number-format](https://www.npmjs.com/package/react-number-format) package

```jsx
import {useState} from 'react';
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import {registerLocale} from "react-datepicker";
import {ru} from 'date-fns/locale/ru';
import {PatternFormat} from 'react-number-format';

registerLocale('ru', ru);

const Example = () => {
  const [startDate, setStartDate] = useState(new Date());
  const [endDate, setEndDate] = useState(new Date());

  return (
    <>
      <DatePicker
        locale="ru"
        dateFormat="dd.MM.yyyy"
        customInputRef="getInputRef"
        customInput={<PatternFormat
          format="##.##.####"
          allowEmptyFormatting={false}
          mask="_"
        />}
        placeholderText='ДД.ММ.ГГГГ'
        selected={startDate}
        selectsStart
        startDate={startDate}
        endDate={endDate}
        onChange={(date) => setStartDate(date)}
      />
      <DatePicker
        locale="ru"
        dateFormat="dd.MM.yyyy"
        customInputRef="getInputRef"
        customInput={<PatternFormat
          format="##.##.####"
          allowEmptyFormatting={false}
          mask="_"
        />}
        placeholderText='ДД.ММ.ГГГГ'
        selected={endDate}
        selectsEnd
        startDate={startDate}
        endDate={endDate}
        onChange={(date) => setEndDate(date)}
      />
    </>
  );
};
```
package.json
```json
{
  "name": "test-react-datepicker",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-datepicker": "^7.5.0",
    "react-dom": "^18.3.1",
    "react-number-format": "^5.4.2"
  },
  "devDependencies": {
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.1",
    "eslint": "^8.57.0",
    "eslint-plugin-react": "^7.34.3",
    "eslint-plugin-react-hooks": "^4.6.2",
    "eslint-plugin-react-refresh": "^0.4.7",
    "vite": "^5.3.4"
  }
}
```
