### ISSUE TITLE
renderCustomHeader is not working with showTimeSelect on.

### ISSUE THREAD

**Issue by enflaer** [Hacker0x01/react-datepicker#2846]
**Describe the bug**
If we pass `renderCustomHeader` and `showTimeSelect` props, `renderCustomHeader` is not working.
It starts with 3.5.0 version.
Problem is here -> https://github.com/Hacker0x01/react-datepicker/blob/master/src/calendar.jsx#L676
`this.state.monthContainer` is `undefined` or `null` every time but not with `showTimeSelect` prop.

**To Reproduce**

1. Set `renderCustomHeader` and `showTimeSelect` props
2. Click on DatePicker
3. No custom header.

**Expected behavior**
Custom header rendering with `showTimeSelect` prop.

**Desktop (please complete the following information):**
- OS: Manjaro Linux x86_64 
- Kernel: 5.9.16-1-MANJARO 
- Browser ms edge
- Version 91.0.831.1

**Comment by ponas-andrius** [comment]
Encountered the same issue after upgrading to newer version. Would be nice to see this fixed in future versions.
