### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by gaastonsr** [Hacker0x01/react-datepicker#287]
There are some good fixes on master. Would it be possible to make a release?

**Comment by martijnrusschen** [comment]
Sure, I'll do a release tomorrow. Can you run on the master branch in the mean time?

**Comment by gaastonsr** [comment]
I can :), thanks.

**Comment by martijnrusschen** [comment]
Here you go https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.18.0

**Comment by gaastonsr** [comment]
Thank you!
