### ISSUE TITLE
minDate and maxDate cause the highlighted date to stick when clicking through months.

### ISSUE THREAD

**Issue by conoroc** [Hacker0x01/react-datepicker#2872]
**Describe the bug**
The highlighted date follows for each month when clicking through months. This happens in any case except when minDate is passed as null.

**To Reproduce**

1. Create a Datepicker with a minDate and maxDate set (even if they are last year and next year etc)
2. Open up the calendar
3. Click the right arrow to scroll through months
4. The current date of month will stay highlighted on each month (eg if today is the 8th, the 8 will be highlighted for all months)

**Expected behavior**
With minDate passed as null, the behavior is as expected.
In this case the highlighted date does not follow when clicking through months.

**Screenshots**
![screenshot-portal lvh me_3000-2021 04 08-17_52_13](https://user-images.githubusercontent.com/2374601/114066154-4fb7eb80-9893-11eb-8e2c-2511da790aeb.png)
![screenshot-portal lvh me_3000-2021 04 08-17_51_48](https://user-images.githubusercontent.com/2374601/114066159-50508200-9893-11eb-898a-90c07f58fffb.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser chrome
- Version 89

**Comment by NOIPA171** [comment]
I had this issue too, but luckily the class for this is `.react-datepicker__day--keyboard-selected`, while the one being actually selected is `.react-datepicker__day--selected`, so I got around this by setting different css styles
