### ISSUE TITLE
Better ref support

### ISSUE THREAD

**Issue by davidroeca** [Hacker0x01/react-datepicker#2873]
**Is your feature request related to a problem? Please describe.**

There is not an easy way for to provide separate ref to the input component. The root of the issue boils down to [this code](https://github.com/Hacker0x01/react-datepicker/blob/daebfffb1f6d9d598421b91febb087c849e33fbc/src/index.jsx#L927-L929).

Related issues:
- https://github.com/Hacker0x01/react-datepicker/issues/2397
- https://github.com/Hacker0x01/react-datepicker/issues/2165
- https://github.com/Hacker0x01/react-datepicker/issues/862
- https://github.com/Hacker0x01/react-datepicker/issues/1468

**Describe the solution you'd like**

Allow the user to provide an input `ref` to react-datepicker (and if `customInputRef` is provided, then the ref will be assigned to the customInput's `customInputRef` prop). We would need to handle the following cases:
- If no ref is provided, then define the callback ref as is already the case
- If a callback ref is provided, then decorate the callback with another callback that assigns `this.input = input`
- If a ref object is provided, then consider doing one of the following (not sure which is better):
  - Define a callback like this:
  ```ts
  const ref = (input) => {
    this.props.ref.current = input // just a thought -- may require tweaks
    this.input = input
  }
  ````
  - Or set `this.input = this.props.ref.current` somewhere, maybe a lifecycle method

**Describe alternatives you've considered**

It seems like the `customInputRef` prop provides a way to basically prevent this ref from being created (or to leverage this callback ref in a custom way), though I'd expect its main use would be for component libraries that define a separate name for the input ref such as `inputRef`. As a current work-around, I can create a `customInput` that takes a `throwawayRef` prop (and does nothing with it), then define `customInputRef="throwawayRef"`. I don't believe this is an anticipated use case but it works for me.

**Additional context**

I'm using [react-hook-form](https://react-hook-form.com/), and it leverages refs to allow the library to focus on elements that have errors in form submission. This ref is useful for the library to `focus()`. There are definitely work-arounds, but I think better ref support is the cleaner solution and would probably benefit other use cases as well.

**Comment by neilchaudhuri** [comment]
@davidroeca I am having an issue where my custom input won't fire any `onChangeRaw` events, and I have a feeling it is a similar `ref` situation.

(I also happen to be using React Hook Form)

Can you provide more details as to the ref forwarding between `react-datepicker` and your custom input? I have tried a lot of things and just can't get that event to fire.

**Comment by davidroeca** [comment]
:thinking: I haven't directly relied on `onChangeRaw` in my implementation, but my having read through the source code, it looks like that fires during `onChange` and `onSelect`. Are you passing `onChange` to your custom input? You'll need to follow the approach [here](https://github.com/Hacker0x01/react-datepicker/issues/2397#issuecomment-707048538), but I would also recommend passing all of the props that you can down to the input component:

```tsx
const CustomInput = forwardRef(({
  value,
  onClick,
  // Or whatever you call your custom throwaway ref
  throwAwayRef: _,
  onChange,
  ...props
}) => (
  <MySpecialInputComponent
    value={value}
    onClick={onClick}
    onChange={onChange}
    // You may need to hand-pick more of these rather than doing a full spread 
    {...props}
  />
))

**Comment by neilchaudhuri** [comment]
@davidroeca Thanks for this help. I deleted my comment because it turns out the issue had nothing to do with my `ref` handling but a third-party library I was using for input masking, and I had no idea you would be so prompt. Regardless, thanks for taking the time to provide this as I and I'm sure many others will benefit from your findings

**Comment by davidroeca** [comment]
No worries at all! Glad you were able to find the root of the problem

**Comment by vimkin** [comment]
I'm here because of the same reason as @davidroeca. Thank you for the issue! Actually, refs should be specified for all the input fields inside a form, in the opposite case react-hook-form validation stops working properly with `mode: onChange`. 
The following code works:
```javascript
const ParentComponent = forwardRef((props, ref) => {
  ...
  <Datepicker
    ref={ref}
    ...otherProps
  />
});
```
thought, for the most part, thanks to a `value` property on the `Datepicker` class (feels like a well-worked accident rather than intention), because `ref` is a legacy class component. It would be great if we could get input ref directly.

**Comment by knilink** [comment]
for object ref, can simply pass it to input then directly access it
```js
<input ref={this.props.ref} />
...
this.props.ref.current.focus();
```

`this.props.ref.current = input` may not be ideal as `current` is marked as readonly in typescript.
