### ISSUE TITLE
When invalid date, onBlur called with "wrong" value

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [Hacker0x01/react-datepicker#2888]
**Describe the bug**
When user type an invalid date then click outside of the input, input content is cleared (as date is invalid).
This is fine. However, the onBlur event received do not contain blank string but the invalid value.
Thus, it is impossible for a container to detect when the input was cleared by "react-datepicker".

**To Reproduce**

1. Go to 'https://codesandbox.io/s/goofy-frost-ryqeq?file=/src/App.js'
2. Click on the input
3. Type '4'
4. Click outside of the input
5. Look at the console

**Expected behavior**
We should have the result : 
- this is the value : ''

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : Firefox
- Version : 87.0

Yours faithfully,
LCDP

**Comment by lennerd** [comment]
@LeComptoirDesPharmacies any progress?

**Comment by LeComptoirDesPharmacies** [comment]
@lennerd problem is still there in last version (4.7.0) of react-datepicker.
