### ISSUE TITLE
Allow a predicate to determine the disabled state of any given day

### ISSUE THREAD

**Issue by smelnikov** [Hacker0x01/react-datepicker#289]
Hello,

I have a requirement to only allow a user to pick certain days of the month (in my case just the first day of the month), I could use `includeDates` but that would require me to generate an array from the beginning of time to the end of time, so not exactly feasible (unless I wish to cap the date at some arbitrary range). Is there a way to do this which I have missed?

If not, I propose an additional property `disabledDates` that takes in a function that accepts a date and returns a boolean. 

If this sounds like a good idea I'd be willing to put together the initial PR as it seems like it could be easily added to `calendar.jsx` `renderDay` method.

**Comment by martijnrusschen** [comment]
This should be fixed by #307

**Comment by rafeememon** [comment]
Hey @smelnikov, we added a `filterDate` property to the date picker to handle this use case.  Let us know if that works for you.

**Comment by smelnikov** [comment]
This is perfect! Thanks @rafeememon , @martijnrusschen
