### ISSUE TITLE
ExcludeDates is not excluding

### ISSUE THREAD

**Issue by loujonker** [Hacker0x01/react-datepicker#2891]
Hi,

Is the excludeDates option still supported?

`
	const holidays = [
		new Date(2021, 4, 1),
		new Date(2021, 4, 14)
	];
` in combination with `excludeDates={holidays}` doesn't exclude the dates anymore. 

Thanks!

**Comment by tu4mo** [comment]
Seems to be working fine. Remember that month is 0-indexed.

**Comment by Mads84** [comment]
I'm also not able to exclude dates when running my site with datepicker on MacOS (safari) or iOS (Safari or Chrome).
When rendering the same page on windows machine the dates are excluded correctly.

**Comment by aygul-h** [comment]
I have the same problem. Neither including nor excluding is not working
