### ISSUE TITLE
Calendar open and close immediately on iphone safari browser

### ISSUE THREAD

**Issue by vivek-appinventiv** [Hacker0x01/react-datepicker#2896]
Hello, 

I'm using react datepicker with 3.4.1 version

Datepicker is opening fine on all system except iphone safari of mobile.

**Issue: Once you click on the input of datepicker it will open calendar and then will close immediately, and will not open calendar again.**

Please check the code I'm using:

**My common component** 
![image](https://user-images.githubusercontent.com/82655436/115023007-d09e6500-9edb-11eb-9569-50773896a11a.png)

and reusing it like:
![image](https://user-images.githubusercontent.com/82655436/115023191-10fde300-9edc-11eb-8858-ea0a017ee790.png)

Let me know any solution.

Thanks in advance.

**Comment by thanhbk55** [comment]
You can try to delete `closeOnScroll` option to reslove this issue
