### ISSUE TITLE
Remove DateUtil abstraction

### ISSUE THREAD

**Issue by RSO** [Hacker0x01/react-datepicker#290]
When we initially introduced the `DateUtil` we only used `moment` for a couple of minor tasks (looping over all days in the week for example). At that point I decided that the abstraction would help us get rid of `moment` as a dependency in the future.

Looking at the codebase now it is save to say that we have grown more dependent on moment than was initially expected, and therefor it is also time to remove the `DateUtil` abstraction.

Ref #282 (sparked the initial discussion).

**Comment by RSO** [comment]
(@rafeememon I'm assigning you since you mentioned you had a branch ready for this. Let me know if you can't work on this and I will happily take over)

**Comment by rafeememon** [comment]
@RSO, please take a look when you get a chance, thanks!
