### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by RSO** [Hacker0x01/react-datepicker#291]
Our current documentation is basically a bunch of examples. Even though examples are great, I think that it would also be awesome to have some kind of API documentation (preferably generated).

Another thing I would love to try out would be to have some kind of playground (https://github.com/FormidableLabs/component-playground) where people who are interested can play around with the datepicker themselves (I tried replacing all examples with a playground, but that didn't work out quite as well as I expected. I'm open to suggestions here).

**Comment by martijnrusschen** [comment]
Something like this could work https://github.com/jsdoc3/jsdoc

**Comment by martijnrusschen** [comment]
Some more information http://blog.fusioncharts.com/2013/12/jsdoc-vs-yuidoc-vs-doxx-vs-docco-choosing-a-javascript-documentation-generator/

**Comment by martijnrusschen** [comment]
Got a first version running in a way that generates markdown files for each component file. (https://github.com/Hacker0x01/react-datepicker/pull/348) This is almost ready to go and could be nice first version to start with. Ideally, I'd add a new page to the GH pages website where we publish these docs in a nice way.

**Comment by martijnrusschen** [comment]
Closing this out since we have generate API documentation now. We'll add more docs over time once the internal API becomes more stable. Having a playground is a nice to have for me, but not a blocker for v1.0. Also, improving the generate documentation by copying it to the GH pages site is still on my list.
