### ISSUE TITLE
Month and year view not working properly with minDate

### ISSUE THREAD

**Issue by toomski** [Hacker0x01/react-datepicker#2912]
**Describe the bug**
As a user, I want to set minDate to now with a new Date().

I think is related to [https://github.com/Hacker0x01/react-datepicker/pull/2186](https://github.com/Hacker0x01/react-datepicker/pull/2186)

Below is the minimum code to reproduce the problem:

[https://codesandbox.io/s/mitorski-forked-5ccrm ](https://codesandbox.io/s/mitorski-forked-5ccrm )

**Result**
From the day view picker, all is fine.
From the month view picker, I can't select the current month (April)
From year view picker I can't select the current year (2021)

**To Reproduce**

1. Select month from select on left and try to select current month (April)
2. Select year from select on left and try to select the current year (2021)

**Expected behavior**
I want to select the current month (April) and year (2021)

**Desktop (please complete the following information):**

- OS: any
- Browser: any
- Version: any
- Version of react-datepicker - 3.8.0

**Comment by AlexYanichev** [comment]
same here
![image](https://user-images.githubusercontent.com/40503291/157933478-860d20ed-d471-4682-a6d5-d7c2de34532a.png)

**Comment by limes** [comment]
Why was the wontfix label added? The above described problem still occurs

**Comment by shu1007** [comment]
I too faced this problem.
In fixing this, I think we first need to consider whether these are breaking the minDate convention by returning the first day of the month or the first day of the year.
(e.g. minDate is 2022/12/30 and selecting 2022 returns 2022/1/1 and selecting 2022/12 returns 2022/12/1 )

**Comment by shu1007** [comment]
Another issue similar to minDate is the issue of excluded dates. Opinions differ as to how the exclusion dates should be treated when they are included.
