### ISSUE TITLE
back traversal(Shift + tab) is just going into the loop between date, prev and next it is not taking the control to previous form control.

### ISSUE THREAD

**Issue by sunaligoyal** [Hacker0x01/react-datepicker#2913]
**Describe the bug**
back traversal(Shift + tab) is just going into the loop between date, prev and next it is not taking the control to previous form control on shift+tab by closing the Calender. It has complicated the accessibility as user get stuck within the date picker itself on the back traversal

**To Reproduce**
In any window with react-datepicker try to traverse the window backwards with shift+tab 

**Expected behaviour**
on shift+tab it should open the calendar again on shift_tab it should close the calendar and move to the previous element in the document.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Abdubek** [comment]
I have the same problem, have you found a solution or a reason?
