### ISSUE TITLE
types are based on 1.x popper.js

### ISSUE THREAD

**Issue by dmwyatt** [Hacker0x01/react-datepicker#2935]
I'm not sure if someone here is maintaining `@types/react-datepicker`.  Maybe this is better filed at DefinitelyTyped?

**Describe the bug**
I was trying to use `popperModifiers` and I was getting:

```Type '{ name: string; options: { rootBoundary: string; tether: false; altAxis: true; }; }[]' is not assignable to type 'Modifiers'.
  Types of property 'shift' are incompatible.
    Type '() => { name: string; options: { rootBoundary: string; tether: false; altAxis: true; }; } | undefined' has no properties in common with type 'BaseModifier'.  TS2322
```

I thought this was odd because ['shift' is no longer used in Popper 2.x](https://popper.js.org/docs/v2/migration-guide/#11-inner-keeptogether-shift-modifiers-are-gone).

I think this is because `@types/react-datepicker` is pulling in dependencies from Popper 1.x:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c0214a16f47fd26fee174ba828d113e02ba345c7/types/react-datepicker/index.d.ts#L22

That's not how you [import from Popper in 2.x](https://popper.js.org/docs/v2/migration-guide/#2-change-the-import)

**To Reproduce**
Reproduction here: https://codesandbox.io/s/cool-sun-92mjc?file=/src/App.tsx

**Comment by martijnrusschen** [comment]
Hi! Popper v2 was just merged into master yesterday and hasn't been released yet. However, I'm not actively updating types, I don't think anyone is actively doing that so I wouldn't be surprised if things are outdated.

**Comment by martijnrusschen** [comment]
What would you suggest? Can these be automatically updated? Or should we remove it completely?

**Comment by dmwyatt** [comment]
Someone or the other I misled myself to think that Popper v2 was already being used.  What a dummy I am.

So, actually I don't think anything is broken and I'm just making noise, sorry!

Whenever Popper v2 is rolled out into a release, *then* the current types will be broken.  I don't think it's a terribly huge undertaking to update them as it's a pretty simple interface.  Depending on how busy I am, I might be able to update the types at that time if someone thinks to ping me.

**Comment by martijnrusschen** [comment]
No problem! I'll keep you posted on the release.

**Comment by fdcds** [comment]
I believe that react-datepicker v4.1.1 now uses Popper v2.

**Comment by fdcds** [comment]
This appears to have been fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/commit/296d2df84bb6a161976613c5560cd0f5595ecff9, which appears to be part of @types/react-datepicker v4.1.4 (there is no changelog, release notes or even VCS tags as far as I can see, but that version no longer shows the problematic behaviour of earlier versions).
