### ISSUE TITLE
Make Calendar component externally consumable

### ISSUE THREAD

**Issue by rafeememon** [Hacker0x01/react-datepicker#294]
The `Calendar` component is useful on its own if a consumer simply wants to display a calendar with selectable dates on a page.  I think it would be great if it was easy to import and consume only this component outside of the dropdown menu.  This can already be done to an extent, but to get to the ideal state I think a couple things need to happen:

1) _API_: The required `Calendar` props should be stripped down to only what is necessary.  It should have roughly the same required props as `DatePicker` (mainly the props that specify which dates can be selected), but I think it would be a huge help if we have a solid answer for #277 to make this as good as possible.

2) _Styles_: The standalone component should look good outside of the dropdown menu.  This may already be the case but it should be addressed.

**Comment by uniphil** [comment]
ooh this would be awesome!

**Comment by mike-engel** [comment]
@rafeememon This would be great! I'm currently working on a project that needs *just* this. Right now, however, I have to download a zip of the project and reference the calendar object locally. Would you consider adding the `src` folder to the `package.json` files key? That way I could just install this package and get at the singular calendar component (and its required files). Thanks!

**Comment by rafeememon** [comment]
Hey @mike-engel, glad you would find this useful.  I think the way this would work is we would publish a `lib` directory which is `src` cross-compiled with babel.  I'd like to get the API in a slightly more usable state before we do this though.

**Comment by mike-engel** [comment]
Thanks @rafeememon. Is there anything I can help with?

**Comment by rafeememon** [comment]
Now publishing compiled class files with #404, but not sure the API is in its final state where we can declare this finished yet.
