### ISSUE TITLE
Make it possible to support multiple themes

### ISSUE THREAD

**Issue by martijnrusschen** [Hacker0x01/react-datepicker#295]
One thing I would like to add is the support of themes. I'm not sure how we should integrate this, but it would be awesome if the user of the datepicker could choose between multiple themes/styles. Similar to https://github.com/zippyui/react-date-picker#theming

**Comment by martijnrusschen** [comment]
We could debate if this should be part of an v1.0 or not.

**Comment by rafeememon** [comment]
(trying to close out as many tickets as possible)

@martijnrusschen, I think it's best if we concentrate on making our one theme look as best as possible rather than supporting multiple styles.  Consumers are free to add to our CSS as they see fit.  I'll close this out unless you disagree.

**Comment by martijnrusschen** [comment]
sgtm
