### ISSUE TITLE
Date Range using input with clear button Not Working

### ISSUE THREAD

**Issue by UnikoveNeeraj** [Hacker0x01/react-datepicker#2959]
const [dateRange, setDateRange] = React.useState([null, null]);
    const [startDate, endDate] = dateRange;

function updateExecutionList(date): void { 
        setDateRange(date);
      //  props.updateExeList(date);
    }
            <DatePicker
                selectsRange={true}
           
                ref={datepicker}
                startDate={startDate}
                endDate={endDate}
                isClearable={true}
                className="inputField expstart"
                placeholderText="Date"
                dateFormat="d MMM, yyyy"
                highlightDates={highlightWithRanges}
                onChange={(update): void => { 
                  
                    updateExecutionList(update)
                  }}
              
               // customInput={<ExampleCustomInput />}
            >

When first date select calender get closed and also slected value is not showing.
any one help if i am doing somthing wrong

**Comment by sevgeek** [comment]
I have the same problem as @UnikoveNeeraj 
I'm using the sample code from the official site where it works.

![9](https://user-images.githubusercontent.com/60958933/118177163-fc5d2e00-b43a-11eb-95c0-a3e2ffee3906.gif)

But in my component code, displaying the selected range doesn't work. There is also no clear values button. As you can see from the logs, the selected values are perfectly passed through the callback function in the array format.

![8](https://user-images.githubusercontent.com/60958933/118177329-3a5a5200-b43b-11eb-9086-1ad10634bcf1.gif)

I use "react-datepicker": "3.8.0" and "react": "16.8.4". 

Me component code:

```
import React from "react";
import PropTypes from "prop-types";
import DatePicker from "react-datepicker";

function DateRangePicker(props) {
	const [dateRange, setDateRange] = React.useState([null, null]);
	const [startDate, endDate] = dateRange;

	/* Logging values */
	React.useEffect(() => props.onChange(dateRange), [dateRange]);

	return (
		<DatePicker
			selectsRange
			endDate={endDate}
			isClearable={true}
			startDate={startDate}
			onChange={(dates) => setDateRange(dates)}
			shouldCloseOnSelect={false}
		/>
	);
}

DateRangePicker.propTypes = {
	onChange: PropTypes.func.isRequired,
};

DateRangePicker.defaultProps = {

};

export default DateRangePicker;
```

**Comment by dharmverma** [comment]
I am also facing the same issue, on selecting date range its not displaying selected date in Input field. here is the code, we are using

https://codesandbox.io/s/blissful-blackwell-bk56e?file=/src/App.js

**Comment by sharanya5** [comment]
I am also facing the same issue (Dates and clear button isn't displayed after selection). Used the same example from the docs. https://reactdatepicker.com/#example-date-range-using-input-with-clear-button

**Comment by maoft** [comment]
I am experiencing the same issue and had to implement the workaround from @sharanya5 (Thanks!).

However I am also experiencing issues with the popper closing when selecting "startDate", and as such I have to open the popper again to select "endDate". I have to set "shouldCloseOnSelect" to false to keep the popper open, but then I have to manually close the popper when selecting "endDate". I expect "shouldCloseOnSelect" should be true and the popper should close only when both "startDate" and "endDate" has been filled?

**Comment by genovese** [comment]
I am having exactly this issue.  When I select the first date, the calendar closes. It then re-opens to select the second date. The date range does *not* display in the input field, however. And no clear button shows up.  My code is essentially the same as the demo code, except for where I store and retrieve the dates.  I'm happy to give details as needed, but the examples above pretty much capture it.

**Comment by ItayTur** [comment]
same issue with the start selection closes the popper.

**Comment by sevgeek** [comment]
On version `4.1.1` the date range selection functionality works correctly!
Thanks! 

```javascript
function DateRangePicker() {
	const [startDate, setStartDate] = React.useState(null);
	const [endDate, setEndDate] = React.useState(null);
	const onChange = (dates) => {
		const [start, end] = dates;
		setStartDate(start);
		setEndDate(end);
	};

	return (
		<DatePicker
			selected={startDate}
			onChange={onChange}
			startDate={startDate}
			endDate={endDate}
			selectsRange
			isClearable
		/>
	);
}
```
