### ISSUE TITLE
Add CSS class for days not in current month

### ISSUE THREAD

**Issue by rafeememon** [Hacker0x01/react-datepicker#296]
The calendar shows days adjacent to the current month (end of previous month, beginning of next month), but they look the same as days in the current month.  We should add a class to days not in the current month (maybe `datepicker__day--outside-month`) and style them slightly differently so that they can be distinguished.

**Comment by tomazzaman** [comment]
Agreed, it will definitely be a UX improvement to show these differently.

**Comment by RSO** [comment]
Yeah, we had this before, but I think some of this got lost in one of @lbekkema's styling refactors.

**Comment by rafeememon** [comment]
Aha, found the thread: #78  It looks like the main concern was that dates not in the current month looked non-selectable because they had the same styling as disabled dates.  I'm not sure what the proper styling should be but a good first step is implementing the `--outside-month` class.

**Comment by martijnrusschen** [comment]
Yes, great first step. Would be cool to discuss some possible options here for styling. Suggestions?

**Comment by martijnrusschen** [comment]
With #308 merged, we now have the ability to style `datepicker__day--outside-month`.

**Comment by martijnrusschen** [comment]
We'll be adding a default styling for this as soon as we have a idea on how to style this.

**Comment by martijnrusschen** [comment]
@tomazzaman Do you have suggestions on how this should look like?
