### ISSUE TITLE
Code coverage change on PR

### ISSUE THREAD

**Issue by martijnrusschen** [Hacker0x01/react-datepicker#297]
Now we have code coverage tool in our webpack output, it would be awesome if we could print the coverage change in the output of a PR. This could help people writing tests to cover their new/changed code.

**Comment by martijnrusschen** [comment]
Looks like https://codecov.io/ can help us here. Will see if I can set this up!

**Comment by rafeememon** [comment]
We can probably use something like Coveralls here.  Possibly relevant docs:

* https://coveralls.zendesk.com/hc/en-us/articles/201769715-Javascript-Node
* http://mluby.azurewebsites.net/coveralls-io-w-node-travis-ci/

**Comment by martijnrusschen** [comment]
Yeah both options are similar to each other I guess. One think I like about Codecov is that it's more in your face since it outputs the difference in the PR. I think that will help people more than having the output in the CI (Travis).
