### ISSUE TITLE
Inconsistency on onChange and onChangeRaw

### ISSUE THREAD

**Issue by pedro-pinho** [Hacker0x01/react-datepicker#2970]
**Describe the bug**
Datepicker not firing onChange event after multiple renders. It does fire the onChangeRaw event, but with no value on it's target parameter. What I can retrieve is the e.target.ariaLabel using ref and onChangeRaw, but that would involve parsing a text and honestly I expected the component to do that

**To Reproduce**

With the code bellow, at first it loads just fine, but if you keep changing the conditionX, after 2 loads it stops firing the onChange event for both.
I tried to render both of them and hide one using the Style={display:'none'} but the behavior is the same

```
{
      conditionX && <div className="input">
          <DatePicker
              selectsRange
              inline
              ref={rangeRef}
              onChange={value => handleChangeRange(value)}
              startDate={startDate}
              endDate={endDate}
              minDate={minDate}
              maxDate={maxDate}
              excludeDates={[...disableWildCard(), ...weekends]}
              onChangeRaw={(e) => { 
                      console.log('range raw', e.target, e.target.value, e.target.text)
              }}
          />
      </div>
  }
  {
      !conditionX && <div className="input">
          <DatePicker
              inline
              ref={normalRef}
              onChange={value => handleChange(value)}
              minDate={minDate}
              maxDate={maxDate}
              excludeDates={[...disableNonWildCard(), ...weekends]}
              onChangeRaw={(e) => { 
                    console.log('raw', e.target, e.target.value, e.target.text)
               }}
          />
      </div>
  }
```

**Expected behavior**
onChange event always firing regardless of how many times I change the conditions

**Screenshots**
As bellow, first time changing it works fine, but if I change it back to the range filter, it doesn't fire the event, also it doesn't paint the whole row as per my code says and as it works on the first time
![Screen Shot 2021-05-14 at 11 19 08](https://user-images.githubusercontent.com/32839552/118283956-4d563c00-b4a6-11eb-8c8e-7fdaa70371fd.png)

**Desktop (please complete the following information):**

- OS: macOs BigSur
- Browser Chrome 
- Version 90.0.4430.212 (Official Build) (arm64)

**Comment by Kucerenko171** [comment]
Try to add `e.preventDefault()`

e.g.
`onChangeRaw={(e) => {
e.preventDefault()
//other code...
}`
