### ISSUE TITLE
error TS2345: Argument of type 'Date | [Date, Date]' is not assignable to parameter of type 'SetStateAction< Date>'.

### ISSUE THREAD

**Issue by Ofer-Gal** [Hacker0x01/react-datepicker#2971]
**Describe the bug**
tslint error when using the same syntax as your sample

**To Reproduce**
 ```
const [startDate, setStartDate] = React.useState(new Date());
 const [endDate, setEndDate] = React.useState(new Date());
```
Then in the render

` <DatePicker selected={startDate}
                            onChange={date => setStartDate(date)} // the (date) is the error
                            selectsStart
                            startDate={startDate}
                            endDate={endDate}
                        />
                        <DatePicker
                            selected={endDate}
                            onChange={date => setEndDate(date)} // the (date) is the error
                            selectsEnd
                            startDate={startDate}
                            endDate={endDate}
                            minDate={startDate}
                        />`

**Expected behavior**
No error it is a date

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [Edge]
**Additional context**

"react-datepicker": "^3.8.0",
 "@types/react-datepicker": "^3.1.8",

**Comment by queden** [comment]
+1

**Comment by icyJoseph** [comment]
I think this problem comes from the types https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-datepicker/index.d.ts -

I guess there should be a union for each with `selectRange:true` and its proper `onChange` type handler instead of having all cases into one key.

**Comment by jan-miksik** [comment]
small workaround when is not necessary to use range `onChange={(date: Date) => setSelectedDate(date)}`

**Comment by bfpnascimento** [comment]
for range cases, we can use this:
```
const [dateRange, setDateRange] = useState([new Date(), new Date()]);
const [startDate, endDate] = dateRange;

<DatePicker
  selectsRange={true}
  startDate={startDate}
  endDate={endDate}
  onChange={(update: [Date, Date]) => {
    setDateRange(update);
  }}
/>
```
