### ISSUE TITLE
When using monthsShown allow startDate to be in the firstMonth

### ISSUE THREAD

**Issue by ledahu05** [Hacker0x01/react-datepicker#2975]
**Describe the bug**
I'm using the range date picker with two months displayed. The startDate of the range always appears in the second month. Therefore it's not possible to see directly a range between one and two months.

**To Reproduce**

const [defaultStartDate, setStartDate] = React.useState<Date>(new Date());
const [defaultEndDate, setEndDate] = React.useState<Date>(new Date());

const handleOnChange = (e: Date | [Date, Date] | null) => {
        if (Array.isArray(e)) {
            const [start, end] = e;
            setStartDate(start);
            setEndDate(end);
        }
    };
      <DatePicker
                selectsRange
                selected={defaultStartDate}
                startDate={defaultStartDate}
                endDate={defaultEndDate}
                onChange={(e) => handleOnChange(e)}
                inline={true}
                locale={translator.getLocale()}
                monthsShown={2}
                onClickOutside={() => setShowDatePicker(false)}

**Expected behavior**
The first month should be as such the startDate of the selected range is displayed in it.

**Screenshots**
![monthShown_startDate](https://user-images.githubusercontent.com/35862820/118635124-8575bb80-b7d3-11eb-8403-b3da165bb59c.png)
First month should by may and second month should be june

**Comment by BeKnowDo** [comment]
I'm dealing with this EXACT issue.

When I open the date picker for the first time, it starts in the current month.
I select the start date, it starts in the current month.
I select the end date, it starts in the current month.

I reopen the picker once both start/end dates have been selected, it shows last month as the start date.

AAAAAAAAHHH.

I've tried using the openToDate prop but that doesn't help the situation

**Comment by Zuru1** [comment]
Try adding focusSelectedMonth={true} to your DatePicker

**Comment by Kyzyl-ool** [comment]
Also you can manually render per month using monthsShown={1}

**Comment by mauriciomutte** [comment]
> Try adding focusSelectedMonth={true} to your DatePicker

Adding `focusSelectedMonth` worked to me

Thanks!

**Comment by ledahu05** [comment]
Its worked for me too! Many thanks!
