### ISSUE TITLE
Copyright header

### ISSUE THREAD

**Issue by rpowers119** [Hacker0x01/react-datepicker#2980]
Would it be possible to include a copyright header that indicates the code is available under an MIT license so that when the code is used on a website or in a hosted service, users will know what the license is?  Would you prefer if I submit a pull request with the suggested change?

**Comment by martijnrusschen** [comment]
Licence can be found in https://github.com/Hacker0x01/react-datepicker/blob/master/LICENSE, https://github.com/Hacker0x01/react-datepicker/blob/master/package.json#L6 and https://github.com/Hacker0x01/react-datepicker/blob/master/README.md#license. Where else would you expect to see it show up?

**Comment by rpowers119** [comment]
The MIT license requires that, at a minimum, a copyright and a reference to the license is included in the minified javascript.  

E.g., the React minified source has the following header:
/** @license React v16.13.1
 * react.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
For React, this header is injected during the build and the logic is defined in the following custom rollup build step: https://github.com/facebook/react/blob/master/scripts/rollup/wrappers.js 

So, I am looking for something similar to this that would include or inject a similar copyright that references your license in the minified code.  Let me know if I missing something that would add the reference to the minified code.

Thanks for the quick response.
