### ISSUE TITLE
Display expected input format as a placeholder

### ISSUE THREAD

**Issue by kidroca** [Hacker0x01/react-datepicker#2995]
**Is your feature request related to a problem? Please describe.**
I want to let the datepicker use a user locale (that I don't know ahead of time) and display some hint of what input is allowed

**Describe the solution you'd like**
I want to be able to display the expected format in which the user should input a date in the text field as a placeholder
E.g. USA users would see "MM/DD/YYYY" European users would see "DD/MM/YYYY"

**Describe alternatives you've considered**
- Use a fixed custom format like MM/DD/YYYY and force everybody to adhere to it when they want to input a date manually
- Or display a date parsed to local string as the placeholder `placeholder={(new Date()).toLocaleDateString()}`

**Comment by kidroca** [comment]
This is related: https://github.com/Hacker0x01/react-datepicker/issues/1580#issuecomment-525458332

**Comment by ShaneHudson** [comment]
I came here with the same question. It looks like `placeholderText` will work.
