### ISSUE TITLE
Cannot use version 3.6+ on react 16.13.1

### ISSUE THREAD

**Issue by Mehdi-HAFID** [Hacker0x01/react-datepicker#3000]
**Describe the bug**
date picker 3.5 is the last version that support react 16. making the version of DP to 3.6.0 and executing npm install shows the error below
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-onclickoutside@6.11.1
npm ERR! node_modules/react-datepicker/node_modules/react-onclickoutside
npm ERR!   react-onclickoutside@"^6.10.0" from react-datepicker@3.6.0
npm ERR!   node_modules/react-datepicker
npm ERR!     react-datepicker@"3.6.0" from the root project

**To Reproduce**
"react-datepicker": "3.6.0",
"react": "16.13.1",
![image](https://user-images.githubusercontent.com/25527904/119852395-ca4dd080-befe-11eb-9ae7-6df95d55a9c3.png)

**Comment by mgummelt** [comment]
It goes back further than version 3.5.  I'm getting failures with 3.3 as well.

This is the source of the issue - https://github.com/Pomax/react-onclickoutside/issues/357
