### ISSUE TITLE
Locale does not change calendar start day

### ISSUE THREAD

**Issue by MattCrouch** [Hacker0x01/react-datepicker#3015]
**Describe the bug**

When applying a locale to a datepicker, the `weekStartsOn` value seems to no longer have an effect.

Our datepickers that use the `en-GB` locale for example would have Monday as the first day of the week as of `3.8.0`.

Since upgrading to `4.1.0` the weeks now start on Sunday. (This also happens in `4.0.0`)

The value can be updated manually using the new `calendarStartDay` prop, but I'm assuming it's supposed to still be picked up from the locale provided.

**To Reproduce**

1. Apply a locale with a `weekStartsOn` value that is not `0`.
2. Render datepicker.
3. See week starts on Sunday.

This looks to also be happening in the [locale example in the documentation](https://reactdatepicker.com/#example-locale).

**Expected behavior**

The week starts on the day specified by the locale.

**Screenshots**

`3.8.0`
<img width="266" alt="Datepicker in 3-8-0" src="https://user-images.githubusercontent.com/1612120/120355638-5a26bc80-c2fb-11eb-9189-9e7afdc426b0.png">

`4.1.0`
<img width="266" alt="Datepicker in 4-1-0" src="https://user-images.githubusercontent.com/1612120/120355911-a7a32980-c2fb-11eb-831d-13f3cddde89b.png">

**Desktop**

- OS: MacOS 11.4
- Browser: Chrome
- Version: 91.0.4472.77

Although this happens on all browsers checked (Firefox, Safari, Edge)

**Comment by brtdv** [comment]
+1

**Comment by javierm83** [comment]
+1

**Comment by timmipetit** [comment]
Since this issue has been fixed now, is there a chance we can get a new release?
