### ISSUE TITLE
The second datepicker doesn't close

### ISSUE THREAD

**Issue by boyarskiy** [Hacker0x01/react-datepicker#302]
When open the first datepicker, change the month, then open the second one, and the first doesn't close.

Screenshot:
http://dl3.joxi.net/drive/0004/1007/275439/160113/5826535989.jpg

**Comment by rafeememon** [comment]
Thanks for the report.  Looks like this applies to any two pickers on the example page.

**Comment by rafeememon** [comment]
This is a limitation of `react-onclickoutside`, namely the `ignore-react-onclickoutside` class.  When clicking on another picker, the click doesn't trigger the first picker to close because of the class.

**Comment by rafeememon** [comment]
Should be fixed by #319
