### ISSUE TITLE
Navigation Arrows not showing up on Safari

### ISSUE THREAD

**Issue by leonardof26** [Hacker0x01/react-datepicker#3028]
The 'Previous' and 'After' arrows are not showing up on Safari on version 4.1.1.

* To Reproduce
1. Go to https://reactdatepicker.com on Safari
2. Click on any calendar.
<img width="1183" alt="Screen Shot 2021-06-04 at 11 15 51" src="https://user-images.githubusercontent.com/20707082/120815531-4a3ef080-c526-11eb-8259-e0df68c64b1d.png">

* System Info:
- MacOS 11.3.1
- Safari 14.1
- React-datepicker 4.1.1

* Additional context:
When accessing with Chrome the calendar works normally, the problem seems to only occur on Safari.

**Comment by dansackett** [comment]
It is also happening in IE11. Based on what I can see it seems that it was introduced in this PR: https://github.com/Hacker0x01/react-datepicker/pull/2724/files

**Comment by gkekesi** [comment]
Having the same issue!

**Comment by Erfolg1982** [comment]
Having the same issue but on Safari (iOS and macOS)
[I solved this problem by including the styles of the previous version](https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/3.8.0/react-datepicker.min.css) 
in later versions of navigation is no longer visible

**Comment by Ugoku** [comment]
I can confirm that using the stylesheet from 3.8 fixes the problem

**Comment by fedeant** [comment]
In my case using the styles from 3.8 caused a warning in the console when the field is selected.
I solved it keeping the latest css and just adding from 3.8 the styles for .react-datepicker__navigation:

`.react-datepicker__navigation {
	background: none;
	line-height: 1.7rem;
	text-align: center;
	cursor: pointer;
	position: absolute;
	top: 10px;
	width: 0;
	padding: 0;
	border: .45rem solid transparent;
	z-index: 1;
	height: 10px;
	width: 10px;
	text-indent: -999em;
	overflow: hidden
}

.react-datepicker__navigation--previous {
	left: 10px;
	border-right-color: #ccc
}

.react-datepicker__navigation--previous:hover {
	border-right-color: #b3b3b3
}

.react-datepicker__navigation--previous--disabled,
.react-datepicker__navigation--previous--disabled:hover {
	border-right-color: #e6e6e6;
	cursor: default
}

.react-datepicker__navigation--next {
	right: 10px;
	border-left-color: #ccc
}

.react-datepicker__navigation--next--with-time:not(.react-datepicker__navigation--next--with-today-button) {
	right: 95px
}

.react-datepicker__navigation--next:hover {
	border-left-color: #b3b3b3
}

.react-datepicker__navigation--next--disabled,
.react-datepicker__navigation--next--disabled:hover {
	border-left-color: #e6e6e6;
	cursor: default
}

.react-datepicker__navigation--years {
	position: relative;
	top: 0;
	display: block;
	margin-left: auto;
	margin-right: auto
}

.react-datepicker__navigation--years-previous {
	top: 4px;
	border-top-color: #ccc
}

.react-datepicker__navigation--years-previous:hover {
	border-top-color: #b3b3b3
}

.react-datepicker__navigation--years-upcoming {
	top: -4px;
	border-bottom-color: #ccc
}

.react-datepicker__navigation--years-upcoming:hover {
	border-bottom-color: #b3b3b3
}

.react-datepicker__year-option:hover .react-datepicker__navigation--years-upcoming,
.react-datepicker__month-option:hover .react-datepicker__navigation--years-upcoming,
.react-datepicker__month-year-option:hover .react-datepicker__navigation--years-upcoming {
	border-bottom-color: #b3b3b3
}

.react-datepicker__year-option:hover .react-datepicker__navigation--years-previous,
.react-datepicker__month-option:hover .react-datepicker__navigation--years-previous,
.react-datepicker__month-year-option:hover .react-datepicker__navigation--years-previous {
	border-top-color: #b3b3b3
}

.react-datepicker__portal .react-datepicker__navigation {
	border: .81rem solid transparent
}

.react-datepicker__portal .react-datepicker__navigation--previous {
	border-right-color: #ccc
}

.react-datepicker__portal .react-datepicker__navigation--previous:hover {
	border-right-color: #b3b3b3
}

.react-datepicker__portal .react-datepicker__navigation--previous--disabled,
.react-datepicker__portal .react-datepicker__navigation--previous--disabled:hover {
	border-right-color: #e6e6e6;
	cursor: default
}

.react-datepicker__portal .react-datepicker__navigation--next {
	border-left-color: #ccc
}

.react-datepicker__portal .react-datepicker__navigation--next:hover {
	border-left-color: #b3b3b3
}

.react-datepicker__portal .react-datepicker__navigation--next--disabled,
.react-datepicker__portal .react-datepicker__navigation--next--disabled:hover {
	border-left-color: #e6e6e6;
	cursor: default
}
`

**Comment by pastak** [comment]
https://github.com/Hacker0x01/react-datepicker/pull/3093 looks to solve this issue 👀

**Comment by eyesfocus** [comment]
I think the problem here is that the `<button>` class `.react-datepicker__navigation` uses `display: flex;`. 
It seems that defining a `<button>` as flex container doesn't work in IE11.

**Comment by tahsandewan** [comment]
> .react-datepicker__navigation { overflow: inherit; }
> 
> .react-datepicker__navigation-icon { width: 100%; }
> 
> .react-datepicker__navigation-icon--previous::before { left: 10px; }
> 
> .react-datepicker__navigation-icon--next::before { right: 10px; left: auto; }

Next icon doesn't show
