### ISSUE TITLE
Multiple date selection (not a range selector)

### ISSUE THREAD

**Issue by sovanjana** [Hacker0x01/react-datepicker#3049]
**Is your feature request related to a problem? Please describe.**

currently react-datepicker does not support multiple date selection on an inline calender. 
- is there a way to make it a multiple date selector ? 

**Describe alternatives you've considered**

1. https://react-day-picker.js.org/examples/selected-multiple
2. https://shahabyazdi.github.io/react-multi-date-picker/

**Comment by mpiorowski** [comment]
I was able to do it using highlightDates option. On onChange concat or filter array of dates, set selectedDate to null, and style everything so that selected dates wont be visible. Now your highlightDates is the new value of datepicker.
