### ISSUE TITLE
Bug report : Input return wrong date when type only numbers

### ISSUE THREAD

**Issue by levi-sr93** [Hacker0x01/react-datepicker#3058]
**Typing only numbers in the input return wrong date**

The input does not perform the styling from mask prop which can result in a wrong date. 
e.g: 

I did set up the mask as this example:
```
<ReactDatePicker                    
    ...
           dateFormat="dd/MM/yyyy"
           onChange={date => handleChange(date)}

    ...

   ...
    const handleChange = value => {
        setDate(value);
    };
  ...

```

While typing the date without providing the / the separate each part of the date in the input the onChange function try to guess and return the wrong date.

**To Reproduce**
1. Type any date directly without given the / to separate day to month and year 
2. See that no mask is shown to the user while its typing
3. The result is a wrong date.
4. website has the same behavior

Typing only numbers
![Typing only numbers](https://user-images.githubusercontent.com/49613573/122623204-984d0b80-d071-11eb-8592-b1ce16b7689d.png)

after pressing enter
![After pressing Enter](https://user-images.githubusercontent.com/49613573/122623210-9e42ec80-d071-11eb-8f21-d5121bd8d338.png)

**The expected behavior was to show the mask directly while typing and return the right date**
When typing only numbers that represents the date in the input should give the mask to better visualization and return the right date and not to try to guess.

Any idea of implementation to solve this would be nice.

**Environment :**

- OS: [Linux]
- Browser [chrome, firefox]

**Comment by rcelis** [comment]
This also happens with time, if you just type 150220210000 (Feb 15, 2021 midnight) it shows a date as 12/31/1501 19:03, for what I was able to debug, the reason for this is that is taking the 1502 (that I entered first) as the year and triggers the onChange event, but after I have finished entering the rest of the date field, it doesn't trigger the change event anymore.

Hope this helps to determine what the issue is.

**Comment by ShaneHudson** [comment]
Worth noting that this is still a bug. To replicate it just type a date without delineator.
