### ISSUE TITLE
Types at DefinitelyTyped needs to be updated after new major version (or preferably, moved here)

### ISSUE THREAD

**Issue by Svish** [Hacker0x01/react-datepicker#3065]
**Describe the bug**

The current types at DefinitelyTyped are for `react-datepicker` version 3, with e.g. `popper.js` version 1. This means, for example, that the `popperModifiers` type claimed by Typescript doesn't match up at all with what's shown in the examples (https://reactdatepicker.com/#example-configure-popper-properties).

**To Reproduce**

Use Typescript, install `react-datepicker@4`, and try to use e.g. the `popperModifiers` prop.

**Expected behavior**

Generally I expect packages to come with their own up-to-date types these days, but if not, then I expect to find types at DefinitelyTyped and that they least are _somewhat_ correct.

I looked into creating a PR myself, but decided to create an issue here instead. I'm not familiar enough with `react-datepicker` internals nor how package definitions in DefinitelyTyped actually works to mess with it. And, regardless, the PR process seem to involve the ones originally adding the types anyways, so I can't do it fully on my own anyways. For something as popular as `react-datepicker`, I feel it's best this is fixed by someone who knows what they're doing. 😬

**Comment by JanStevens** [comment]
I've update DefinitelyTyped so it uses popper v2 typings, the PR is here for reference https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54037

**Comment by Svish** [comment]
Types over at DefinitelyTyped have now been updated, merged, and released. Just tested it locally, and seems I can remove my `// @ts-ignore` lines now.

Thank you! 🙏
