### ISSUE TITLE
The calender Drop Down is not aligned in web view

### ISSUE THREAD

**Issue by prodiptahalder** [Hacker0x01/react-datepicker#3070]
The calender drop down does not appear just below the calender icon, instead its shifted on the right  hannd side, but it is working fine in mobile UI.

**Comment by Jorah-M** [comment]
> The calender drop down does not appear just below the calender icon, instead its shifted on the right hannd side, but it is working fine in mobile UI.

Have you found a way to change it's position?

**Comment by CodeguruEdison** [comment]
Any solution?
