### ISSUE TITLE
calendarStartDay not defined in ReactDatePickerProps

### ISSUE THREAD

**Issue by krusk8** [Hacker0x01/react-datepicker#3072]
**Describe the bug**
in the file:
@types/react-datepicker/inex.d.ts

is missing the definition of the input: calendarStartDay
inside the declaration of ReactDatePickerProps interface:

export interface ReactDatePickerProps {
...
    calendarStartDay: number;
...
}

**To Reproduce**

1. install the version 4.1.1
2. try to define calendarStartDay inside DatePicker using react typescript
3. you received the error: 
"Property 'calendarStartDay' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactDatePicker> & Readonly<ReactDatePickerProps> & Readonly<...>' "

**Expected behavior**
 The possibility to use this functionality 

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser :Chrome
- Version : 4.1.1

**Comment by JanStevens** [comment]
I made a PR on DefinitelyTyped to get this fixed: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54037

**Comment by sanmiawi** [comment]
Thanks guys for providing this datepicker! It would be nice to see this fixed because it is confusing to see it in action [here](https://reactdatepicker.com/#example-calendar-start-day) but not have access to use it when implementing it in a project.

**Comment by sanmiawi** [comment]
> Thanks guys for providing this datepicker! It would be nice to see this fixed because it is confusing to see it in action [here](https://reactdatepicker.com/#example-calendar-start-day) but not have access to use it when implementing it in a project.

Hi, figured out that my type definition for the datepicker was wrong. Change the type definition form 3.1.8 to 4.1.1 and the calendarStartDay prop works as expected.
