### ISSUE TITLE
Feature Request: nowButton like todayButton (Set time to other than 12:00 AM)

### ISSUE THREAD

**Issue by SonicMagna** [Hacker0x01/react-datepicker#3075]
I'm using calendar with time, like:
https://reactdatepicker.com/#example-select-time
And todayButton like:
https://reactdatepicker.com/#example-today-button
I'm also using: 
https://reactdatepicker.com/#example-filter-times
to limit the times choices to 'future'. 
All of this works, but the todayButton selects date, and sets the time to 12:00 AM.
I have not figured out how to get the todayButton to respect the filterTime values.
I would like a simple button implemention like the todayButton, that either sets date and time to now(), and/or allowed us to set the time like we can with filterTime.
Thanks for all the work!

**Comment by neutraali** [comment]
Would also be nice to have an example of `showTimeSelect` + `showTimeSelectOnly` with a **Now** -button.
