### ISSUE TITLE
Month Navigation Arrows do not show on Safari

### ISSUE THREAD

**Issue by GilliganL** [Hacker0x01/react-datepicker#3082]
**Describe the bug**
The month navigation arrows are not present on Safari.

**To Reproduce**
Open the datepicker popper in Safari and look for the arrows that are used to change months.

**Expected behavior**
The arrows should be displayed the same as Chrome.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Macbook Big sur 11.4
- Browser [e.g. chrome, safari] Safari
- Version [e.g. 22] 14.1.1

**Smartphone (please complete the following information):**

**Additional context**
Changing the styling of the span that has the pseudo element resolves the issue. (I add height and width 100% to the span and then changed the size and positioning of the :before element)

**Comment by HintDevelopment** [comment]
Also came across this issue today. Simply going to the demo site is enough to reproduce the issue: https://reactdatepicker.com

**Comment by Ugoku** [comment]
Duplicate of #3028
