### ISSUE TITLE
Custom navigation (previous, next) buttons

### ISSUE THREAD

**Issue by communityFabian** [Hacker0x01/react-datepicker#3085]
Is there a way to replace those previous / next month button icons with custom icons (React.ReactNode) ?

**Comment by samueldjones24** [comment]
Hi @communityFabian , you should be able to achieve this by using a custom header:

https://reactdatepicker.com/#example-custom-header

**Comment by KristenWilde** [comment]
Alternatively, you can also add custom content to the buttons using the props `previousMonthButtonLabel` and `nextMonthButtonLabel`. You'll also need to adjust the css for those buttons because the default "icons" are really just borders. (So add width and height and remove border.)

**Comment by Sahil-177** [comment]
I'm trying to customize the color of the navigation icons (previous and next arrows) in the ReactDatePicker component. However, despite applying various CSS styles and Tailwind CSS utility classes, the color changes are not being reflected.

If anyone can help with this issue or provide guidance on how to correctly apply these styles, it would be greatly appreciated.

**Comment by Sahil-177** [comment]
Hi, @samueldjones24 
I'm also trying to change the color of the navigation icons (previous and next arrows) in ReactDatePicker, but the styles aren't reflecting, even when using Tailwind CSS or regular CSS. Any advice on how to apply these changes would be appreciated.

Thanks!

**Comment by samueldjones24** [comment]
hi @Sahil-177, do you have an example of how you're applying the styles? As mentioned at top of post, it might be worth double checking the Custom Header example in the docs here: 

https://reactdatepicker.com/#example-custom-header:~:text=10/02/2024-,Custom%20header,-()%20%3D%3E
