### ISSUE TITLE
Datepicker flashes between open and closed when input is clicked in IE

### ISSUE THREAD

**Issue by rcoy-v** [Hacker0x01/react-datepicker#309]
Version 0.18 introduced a bug in Internet Explorer. When the datepicker is opened and the input is clicked, the calendar quickly flashes between opened and closed. Rolling back to version 0.17, this issue does not exist.

**Comment by rafeememon** [comment]
Possibly related to #273

**Comment by brettjanssen** [comment]
It has the same problem in Chrome using a Windows Precision Touchpad (and in fact when you select the date it doesn't populate the field).  It works fine with a mouse though!  Weird.

**Comment by raptoria** [comment]
+1   I have the same problem with IE10, my error message is:
Line: 110121
Error: Object doesn't support property or method 'setState'

**Comment by xabikos** [comment]
I have the same behavior with IE11. Currently I am using version 0.17 but this has some performance issues as on onBlur is called multiple times something that makes the component slow.

**Comment by rafeememon** [comment]
Should be fixed by #319
