### ISSUE TITLE
Selected day of the month remains visibly selected when navigating through months

### ISSUE THREAD

**Issue by samueldjones24** [Hacker0x01/react-datepicker#3095]
**Describe the bug**
Selected day of the month remains visibly selected when navigating through months

**To Reproduce**

1. Go to [https://reactdatepicker.com/#example-default](https://reactdatepicker.com/#example-default)
2. Select a date from the Default date picker
3. Navigate to different month
4. Day of the month remains selected, but input value does not update

**Expected behavior**
If I select September 15th 2021, then navigate to November - I would expect no date to be visibly selected. 

**Screenshots**
![datepicker](https://user-images.githubusercontent.com/46869759/125274833-3e550400-e306-11eb-9fe1-6b621dd3fd84.png)

**Comment by SapuSeven** [comment]
I also just came across this issue.
That's not the actual selected but the keyboard-selected day.
You can customize the styling by using the CSS class `react-datepicker__day--keyboard-selected` (as opposed to `react-datepicker__day--selected` for the actual selected day).

**Comment by samueldjones24** [comment]
Hi @SapuSeven , thanks for the tip - this fixed it!

```
.react-datepicker__day--keyboard-selected {
        background-color: transparent !important;

        &:hover {
            background-color:  // same as react-datepicker__day 
        }
    }
```
