### ISSUE TITLE
Datepicker style is broken when showTimeSelect is on

### ISSUE THREAD

**Issue by angelzbg** [Hacker0x01/react-datepicker#3096]
When I use showTimeSelect the whole style is broken.

```
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';

<DatePicker
  selected={+state.searchStr}
  dateFormat="yyyy-MM-dd HH:mm"
  onChange={(date) => {
    setState({ searchStr: new Date(date).getTime() + '' });
  }}
  className="mr-1"
  showTimeSelect
/>
```

The picker is in a `<div className="d-flex align-items-center mb-1">`

[Screenshot](https://i.ibb.co/PgLcrtX/react-datepicker-style-broken.png)
<img>https://i.ibb.co/PgLcrtX/react-datepicker-style-broken.png</img>

**Comment by quanscheng** [comment]
when I used in Shopify-Polaris,  the same problem , Datepicker style is broken ,
![image](https://user-images.githubusercontent.com/68772719/140717565-b0397dfa-2115-454d-b2db-10498e53abcb.png)

**Comment by elyeshkiri** [comment]
Same issue
