### ISSUE TITLE
Rendering issue on reactdatepicker.com

### ISSUE THREAD

**Issue by patsplat** [Hacker0x01/react-datepicker#3110]
**Describe the bug**
Rendering appears broken on reactdatepicker.com

**To Reproduce**

1. Go to https://reactdatepicker.com/

**Expected behavior**
Expect to see react-datepicker functioning normall

**Screenshots**
<img width="854" alt="Screen Shot 2021-07-22 at 10 58 05 AM" src="https://user-images.githubusercontent.com/178626/126661348-506796cd-d0e5-4903-8c5b-564082871e03.png">

**Desktop (please complete the following information):**

- OS: Mac OS X Big Sur 11.4
- Browser: Chrome
- Version: Version 91.0.4472.164 (Official Build) (x86_64)

**Comment by ArnieGA** [comment]
I'm also experiencing this, in Win10:
 - Firefox 90.0.2 x64
 - Chrome 92.0.4515.107 (Official Build) (64-bit)

**Comment by AirZT11** [comment]
I am also seeing this in Chrome Version 92.0.4515.107 (Official Build) (x86_64). Not sure if this has to do with this specific issue but i'm also getting the Popper: CSS 'margin' error that was previously issued and closed. Made sure to import 'react-datepicker/dist/react-datepicker.css' but still getting the warning.

**Comment by peabnuts123** [comment]
+1 absolutely embarrassing to see your component outright not work for weeks if not months
