### ISSUE TITLE
onCalendarClose the focus goes to body element

### ISSUE THREAD

**Issue by mmarshad** [Hacker0x01/react-datepicker#3121]
**Describe the bug**
After closing the calendar dialog (by selecting a date or Esc key) the focus does not return to the input field or the custom Icon , instead it either goes to the body element or some random element on the page.
** Please note that I'm using <CustomInput> for rendering
**To Reproduce**

1. Go to  input field
2. Open the calendar dialog either by clicking on field or the calendar icon
3. Select the date and dialog gets closed automatically
4. check with Chrome developer tools, (type document.activeElement on console ) the body element gets highlighted

**Expected behavior**
A the focus should go back to either input field or the calendar Icon so that the screen readers can read properly and keyboard navigation works correctly.

- OS: Windows 10
- Browser chrome

**Comment by Herm9111** [comment]
Using Edge here replicating partially.

When calendar is closed using ESC the focus just disappears (goes to body). When the user tabs, focus goes into next focusable element as expected.

Repro Steps:

Go to input field
Open the calendar dialog either by clicking on field or the calendar icon
DON'T Tab into the calendar, instead just hit ESC
check with Chrome developer tools, (type document.activeElement on console ) the body element gets highlighted


NOTE: If the user tabs into the calendar, then on ESC the focus returns to element as expected.
