### ISSUE TITLE
Changing names of months

### ISSUE THREAD

**Issue by janwolfram** [Hacker0x01/react-datepicker#3128]
Hey,
is there a feature to easily change the names of the months to use this amazing tools with in a other language.

Thx :)

**Comment by rafaelperrechil** [comment]
I have the same problem!

**Comment by OmarOmeiri** [comment]
> Hey, is there a feature to easily change the names of the months to use this amazing tools with in a other language.
> 
> Thx :)

You can change the locale for the language, like this:

```
import React, { useState } from 'react';
import DtPicker from 'react-datepicker';
import pt from 'date-fns/locale/pt-BR';

const DatePicker = () => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      locale={pt}
     />
  );
};
```
![Screenshot 2021-09-29 123207](https://user-images.githubusercontent.com/46783176/135301108-a30d3c28-2f28-447f-8d0d-26eaf69d7327.jpg)


But for me, I'd like to capitalize the month names, usually in portuguese we write alone month names capitalized, it bugs me a little bit.
