### ISSUE TITLE
Accessibility: keyboard navigation for the Today button

### ISSUE THREAD

**Issue by lrkissling** [Hacker0x01/react-datepicker#3136]
**Is your feature request related to a problem? Please describe.**
Users who are using the datepicker with just a keyboard are unable to navigate to or select the Today button.

**Describe the solution you'd like**
Users with the datepicker expanded should be able to tab to the Today button

**Additional context**
Inability to navigate to or select the Today button via keyboard can be verified on react-datepicker site example: https://reactdatepicker.com/#example-today-button

**Comment by karolis-cekaitis** [comment]
I would also say that it would be good to have possibility to pass your own button element that would be added to the div

**Comment by lrkissling** [comment]
This issue still exists and I believe should still be addressed.

**Comment by JanderSilv** [comment]
This issue still exists.
