### ISSUE TITLE
TypeError: Cannot read property 'onSetProperty' of undefined

### ISSUE THREAD

**Issue by ihsansatriawan** [Hacker0x01/react-datepicker#314]
I want parsing value from Datepicker into smart component

in my dump component :
```
handleChangeDate(date) {
    let newDate = date.format('DD/MM/YYYY')
    console.log(newDate)
    this.props.onSetProperty('startDate', newDate)
  }


<DatePicker
              dateFormat="YYYY/MM/DD"
              selected={data.get('startDate')}
              onChange={this.handleChangeDate} 
              placeholderText="First Date"/>
```

in my smart component, i have property `onSetProperty`, but console show error : `TypeError: Cannot read property 'onSetProperty' of undefined`

what i miss something to config ?

thx

**Comment by rafeememon** [comment]
You'll need to bind the context of your component to the function passed to the `onChange` prop.  Try:

```
<DatePicker
  dateFormat="YYYY/MM/DD"
  selected={data.get('startDate')}
  onChange={this.handleChangeDate.bind(this)}
  placeholderText="First Date"/>
```

**Comment by ihsansatriawan** [comment]
thx @rafeememon ! i prefer use arrow function `onChange={(date) => this.handleChangeDate(date)}`

thx for your suggest
