### ISSUE TITLE
SelectsRange bug?

### ISSUE THREAD

**Issue by Wpfal** [Hacker0x01/react-datepicker#3141]
**Describe the bug** (DatePicker 4.2.0)
I am unable to use `selectsRange` system as shown in the examples. Hovering doesn't show the preselect like it does in the examples either. Clicking on a date doesn't cause onChange to print two dates, it prints `[clickedDate, null]`. What could be the cause/solution to this?

**To Reproduce**
I am not really sure however, i am using this code:
```jsx
<DatePicker
    onChange={(dates) => {
        console.log(dates);
        let [start, end] = dates;
        this.setState({
            fromDate: start, // always ends up as date clicked.
            toDate: end      // always ends up as null
        });
    }}
    startDate={fromDate}
    endDate={toDate}
    selectsRange
    inline/>
```
The problem with this is toDate is always null so the end date never changes.

**Expected behavior**
The datepicker should show the preselect while hovering over the dates. `OnChange` should return both start and end dates.

**Screenshots**
https://gyazo.com/9cb6a07f904ade7b88daa3122a4e0b2c

produced: 
```log
[Mon Aug 02 2021 00:00:00 GMT+1000 (Australian Eastern Standard Time), null]
[Mon Aug 02 2021 00:00:00 GMT+1000 (Australian Eastern Standard Time), null]
[Thu Aug 19 2021 00:00:00 GMT+1000 (Australian Eastern Standard Time), null]
[Mon Aug 09 2021 00:00:00 GMT+1000 (Australian Eastern Standard Time), null]
[Wed Aug 18 2021 00:00:00 GMT+1000 (Australian Eastern Standard Time), null]
[Fri Aug 27 2021 00:00:00 GMT+1000 (Australian Eastern Standard Time), null]
[Mon Aug 16 2021 00:00:00 GMT+1000 (Australian Eastern Standard Time), null]
```
**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 92.0.4515.131

**Edit:** I tested with `selected` prop aswell and had the same result.

**Comment by Wpfal** [comment]
Disregard. For anyone having this issue, make sure you don't have anything constantly updating the dates 😂

**Comment by Gencko94** [comment]
I also have the exact same issue, any suggested workaround for this ?

**Comment by Gencko94** [comment]
Okay , obviously I was using ```date-fns``` ```parse``` method to pass the date to the picker. I used regular ```Date``` object from ```new Date()``` and worked like a charm.
