### ISSUE TITLE
4.2.0 broke libsass builds (math.div)

### ISSUE THREAD

**Issue by hoxu** [Hacker0x01/react-datepicker#3144]
We are using libsass via [jsass](https://gitlab.com/jsass/jsass) via [sass4clj](https://github.com/Deraen/sass4clj/). After upgrading react-datepicker from 4.1.1 to 4.2.0 our sass compilation broke with:

```
Execution error (ExceptionInfo) at sass4clj.core/sass-compile (core.clj:176).
Error: Invalid CSS after "...rgin-left: math": expected expression (e.g. 1px, bold), was ".div(-$datepicker__"
        on line 22:20 of node_modules/react-datepicker/src/stylesheets/mixins.scss
        from line 2:9 of node_modules/react-datepicker/src/stylesheets/datepicker.scss
        from line 2:9 of resources/private/sass/screen.scss
>>   margin-left: math.div(-$datepicker__triangle-size, 2);

   -------------------^
```

I'm aware of the [libsass deprecation](https://sass-lang.com/blog/libsass-is-deprecated).

**Describe the bug**

Commit 8d6b90686ad0b184f56b50b5f579f46fd5553cf1 broke libsass builds.

**To Reproduce**

1. Compile `react-datepicker/src/stylesheets/datepicker.scss` with libsass.

**Expected behavior**

No compile errors.

It would be nice if react-datepicker continued libsass support for now. And if not, more prominent notices in release notes & README would be warranted.

**Comment by hoxu** [comment]
Reproduction on OSX:

```
$ brew install sassc
...
$ sassc node_modules/react-datepicker/src/stylesheets/datepicker.scss
Error: Invalid CSS after "...rgin-left: math": expected expression (e.g. 1px, bold), was ".div(-$datepicker__"
        on line 22:20 of node_modules/react-datepicker/src/stylesheets/mixins.scss
        from line 2:1 of node_modules/react-datepicker/src/stylesheets/datepicker.scss
>>   margin-left: math.div(-$datepicker__triangle-size, 2);

   -------------------^
```

**Comment by hoxu** [comment]
Cc: @mortezakarimi

**Comment by martijnrusschen** [comment]
I pushed a fix to https://github.com/Hacker0x01/react-datepicker/releases/tag/v4.2.1

**Comment by hoxu** [comment]
That was quick, awesome, thanks!
