### ISSUE TITLE
Select multiple dates

### ISSUE THREAD

**Issue by pooyarm** [Hacker0x01/react-datepicker#3157]
**Is your feature request related to a problem? Please describe.**
It's not a problem, it's a use-case. In our platform our users should be able to select multiple dates (not a range, but an array of dates).

**Describe the solution you'd like**
To have an option to select multiple dates.

**Describe alternatives you've considered**
Of course there are other packages we can use but we were thinking about using this package since it looks modern and allows us to get rid of moment.

**Comment by mpiorowski** [comment]
I was able to do it using highlightDates option. On onChange concat or filter array of dates, set selectedDate to null, and style everything so that selected dates wont be visible. Now your highlightDates is the new value of datepicker.

**Comment by pooyarm** [comment]
Yes, that was an idea I also thought about, but it's kinda a hacky trick and that feature is not supposed to be used like that. So at the end I'm not sure if it's the best way to do it.

**Comment by sergio-cravas** [comment]
Hi! I would like to open again this discussion becouse I'm in the same use-case of @pooyarm. I need to select multiple dates, but not a range!

Is there any updates on that?
