### ISSUE TITLE
onMonthChange not triggering on day click

### ISSUE THREAD

**Issue by yimejky** [Hacker0x01/react-datepicker#3161]
**Describe the bug**

Function onMonthChange is not triggered when month is changed by click on next/previous overflowing month days.

**To Reproduce**

Click on days from next/previous month. 

In attached image you can click on October 1 or 2, which will change calendar month, but function is not triggered.

![image](https://user-images.githubusercontent.com/22467644/131329310-0a4cc786-be9e-45db-94ed-12b3fd1e6103.png)

**Expected behavior**
onMonthChange is triggered every time calendar month is changed. Even when month is change by clicks on next month days.

**Additional context**
I am trying to fetch data based on actually shown calendar.  Therefore I need to know calendar  state/month.

**Comment by h4i4nhnc** [comment]
@yimejky 
why don't you handle onChange(date) and compare with old state to trigger fetch new data?
I think `onMonthChange` is for user click to > and < or select Month from Dropdown. It's not auto trigger by select Date

**Comment by jees47** [comment]
having same issue, is there any other solution than moving logic into onchange?, this has to be handled by package
