### ISSUE TITLE
export all date_utils functions please

### ISSUE THREAD

**Issue by yumindev** [Hacker0x01/react-datepicker#3164]
**Is your feature request related to a problem? Please describe.**

 - **We need some of the functions in date_utils to customize the format**

**Describe the solution you'd like**

 - **export  all the date_utils funcions in index.ts**

**Describe alternatives you've considered**

**Additional context**

**Comment by Neirda24** [comment]
Indeed that would be very useful. I'm trying to wrap the components to customise the rendering of all parts to apply tailwind look and feel. Although it is a bit hard to extend some parts. So either making it more extendable (might be very tricky) or export the date utils so we can reuse them if needed. WDYT ?
