### ISSUE TITLE
Today button and time

### ISSUE THREAD

**Issue by rcelis** [Hacker0x01/react-datepicker#3173]
**Describe the bug**
When the Today button is set, it only changes the date but it doesn't change the time to the current time.

**To Reproduce**

1. Go to https://reactdatepicker.com/#example-input-time
2. Add todayButton="Today"
3. Change the date and time to a different value than the current one
4. Click the Today button
5. See that date is set to current date but the time doesn't change to the current time.

**Expected behavior**
When today is click, the Date and time should be changed to the current Date/Time

**Screenshots**

**Desktop (please complete the following information):**

- OS: Wndows, Linux
- Browser: chrome, edge, firefox
- Version current

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aftab-rfg** [comment]
I am having the same exact issue, it changes the date but won't change the time.
