### ISSUE TITLE
Datepicker & Typescript: how to set popperModifiers?

### ISSUE THREAD

**Issue by gitohyeah** [Hacker0x01/react-datepicker#3180]
(react-datepicker 3.8.0) 
We're just trying to use this api: https://reactdatepicker.com/#example-configure-popper-properties, but it seems not to work as it is in the example. Typescript absolutely hates it, and even if do // @ts-ignore, there are runtime errors: 

![image](https://user-images.githubusercontent.com/52310595/132706789-e586ac24-c6d4-4deb-be55-09396eb3421e.png)

Anyone has experience with setting popperModifiers attribute? Or knows how to declare & write the modifiers obj?

EDIT: Just to be clear, we are using literally the same code in popperModifiers as in the example.

**Comment by BakanovKirill** [comment]
Same here. Installed prop-types. Still the same issue

**Comment by gitohyeah** [comment]
> Same here. Installed prop-types. Still the same issue

Thanks for the reply. We solved the runtime errors by updating react-datepicker to the latest version, now the modifiers do work. But we have to keep the '// @ts-ignore' for typescript to compile it, which is silly.
