### ISSUE TITLE
Selected date keep showing in all months 

### ISSUE THREAD

**Issue by Amadouuu** [Hacker0x01/react-datepicker#3193]
**Describe the bug**
I choose a day 2021/09/29, then all months have highlighted the day 29
<img width="493" alt="Capture d’écran 2021-09-16 à 15 20 02" src="https://user-images.githubusercontent.com/51505362/133619561-0170f749-acdc-4251-b576-39351a50a290.png">

**Expected behavior**
I think the problem is because in the new version 4.2.1 the css class .react-datepicker__day--selected was removed and replaced with .react-datepicker__day--keyboard-selected

**Desktop (please complete the following information):**
- OS: [iOS]
- Browser [chrome]

**Comment by h4i4nhnc** [comment]
@Amadouuu 
please clear your expected behavior and the propose solution. did you mean:
expected: only date 2021/09/29 is highlight?
