### ISSUE TITLE
Strange display issue

### ISSUE THREAD

**Issue by ghost** [Hacker0x01/react-datepicker#3205]
After installing react-datepicker, the datepicker is displaying like this.

I am using React 16.13.1 in Chrome. 

This is my code. 

<DatePicker selected={this.state.object["StartDate"].value} dateFormat="MMMM d, yyyy" />

![2021-09-21_17-18-04](https://user-images.githubusercontent.com/46723140/134264248-89673c2f-bf27-4a72-b130-b889f5a76b9f.jpg)

**Comment by victormimo** [comment]
Don't forget to add  --> import "react-datepicker/dist/react-datepicker.css";
right under --> import ReactPicker..

Hope it helps!
