### ISSUE TITLE
Close portal from within portal

### ISSUE THREAD

**Issue by robsco** [Hacker0x01/react-datepicker#3207]
I've added an extra "reset" button to the portal, which works fine with my app, but I also need it to close the portal.

Is there a way of doing this?

This is my implementation:

(this.clearDate acts similar to this.handleChangeDate).

                <DatePicker
                    selected={ dateFromIso( this.props.list.date, false ) || new Date() }
                    onChange={ this.handleChangeDate }
                    withPortal
                    customInput={ div }
                >
                    <p onClick={ this.clearDate }>Clear</p>
                </DatePicker>

**Comment by rago4** [comment]
Check out this sandbox 👇 
https://codesandbox.io/s/react-datepicker-close-from-container-v3x18
