### ISSUE TITLE
Git tags off by one, compared to "gitHead" on npmjs.org

### ISSUE THREAD

**Issue by fviernau** [Hacker0x01/react-datepicker#3220]
Assumption: the Git tag should always correspond to the published revision.

Looking at the "gitHead" property in [1] it seems that the Git tags are off by one or vice versa.

[1] https://registry.npmjs.org/react-datepicker

**Comment by sschuberth** [comment]
Looks like that's because publishing itself creates an automated commit, like https://github.com/Hacker0x01/react-datepicker/commit/92a2cc32b72b6c2cd4aeea78ffdc792297ba8f1b which says "Publish new API docs (automated commit)".

**Comment by sschuberth** [comment]
So ideally, the Git tagging should happen after this line:

https://github.com/Hacker0x01/react-datepicker/blob/fe2b4384a69a7ab407b0e5cc15c08e0484fc70ec/scripts/release.sh#L16

**Comment by martijnrusschen** [comment]
Never realised this, but feel free to put up a PR to fix the tagging
