### ISSUE TITLE
Picking a date is not added to the input box

### ISSUE THREAD

**Issue by DavidTheSimon** [Hacker0x01/react-datepicker#324]
I tried you code and I just cannot make it work. Something I'm missing probably.

I use: ` "react": "^0.14.6",`

Whatever I do, the date in the input doesn't change. I console logged it and the onChange event doesn't pick the chosen date. Always shows the exact time and date of the moment I clicked, but still the input is not changed.

Could give me any idea why this is happening?

**Comment by martijnrusschen** [comment]
Can you post an example of how you're using the component?

**Comment by osala-netquest** [comment]
+1.
Tricky solution: assing formatted date to text input in onChange function -> YourDatePickerRef.refs.input.refs.input.value = date.format('YourFormat');

**Comment by rafeememon** [comment]
@DavidTheSimon, @osala-netquest, can you post your code that shows this problem?  Unfortunately we can't help you otherwise.

**Comment by mbektimirov** [comment]
I can confirm the issue.  The code is simple, nothing special:
```js
<DatePicker
  className='filter-input'
  onChange={onDateFilterChange}
  isClearable={true}
  showYearDropdown={true} />
```
```
"react": "^0.14.6",
"react-dom": "^0.14.7",
"react-datepicker": "^0.20.0",
```

**Comment by mbektimirov** [comment]
The workaround for this problem is to provide selected date via `selected` prop with current state:
```js
onDateFilterChange(momentDate) {
    const date = momentDate ? momentDate.format('YYYY-MM-DD') : undefined;
    this.setState({ date });
  }

// then in render
<DatePicker
  onChange={onDateFilterChange}
  selected={this.state.date} />
```

**Comment by rafeememon** [comment]
I think this is the intended use and in fact not a workaround.  We made a change recently where we no longer store the selected date as internal state, and instead leave it up to the user to store the selected date as the "single source of truth."  Storing the date twice could lead to inconsistencies between what is shown and what the wrapper components think is shown, so we now defer this entirely to the user.

**Comment by mbektimirov** [comment]
@rafeememon I like this solution, but you need to clarify this approach in documentation and describe all `DatePicker` props.

**Comment by rafeememon** [comment]
The docs could definitely be better re: props, but I should point out that every example shows the datepicker used this way, e.g. https://github.com/Hacker0x01/react-datepicker/blob/master/docs/src/examples/clear_input.jsx

**Comment by HoiDam** [comment]
no sol
