### ISSUE TITLE
prop to not show weekends in the calendar?

### ISSUE THREAD

**Issue by raptoria** [Hacker0x01/react-datepicker#325]
Right now I'm using CSS to hide the weekends from the calendar completely.. would it be possible to have a prop that does this or should I stick to CSS? 

Thanks!

**Comment by martijnrusschen** [comment]
You can probably use the filterDate option for this.

**Comment by martijnrusschen** [comment]
Example: http://hacker0x01.github.io/react-datepicker/#example-8

**Comment by martijnrusschen** [comment]
Oh I just noticed that the filterDate option isn't released yet. I'll go ahead and release a new version so you can start using this.

**Comment by martijnrusschen** [comment]
Latest release is now available on NPM. Release notes: https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.19.0

**Comment by raptoria** [comment]
thank you!!!
