### ISSUE TITLE
Date range - selecting a date before the start date to switch start and end date

### ISSUE THREAD

**Issue by gsouf** [Hacker0x01/react-datepicker#3265]
**Is your feature request related to a problem? Please describe.**
When  I open a date range picker, I select a first date. Then when I select a second date, if the second date is before the first date then it replace the start date.

![daterange](https://user-images.githubusercontent.com/3215399/137263894-e0fff235-691c-4cf7-9b4a-214defd91ef5.gif)

**Describe the solution you'd like**
I would like to have a range selection where the second date selected can be either before or after the first one selected, and either cases it will create a range instead of just setting the start date.

Example with react-date-range:

![daterange2](https://user-images.githubusercontent.com/3215399/137262716-f9c44f9d-e6c9-46ed-b65e-26aabc5ca40e.gif)

**Describe alternatives you've considered**
None

**Additional context**
None

---

Is there any reasons this is not implemented? I'm happy to work on a PR. Waiting for other contirbutors' word on this

**Comment by gsouf** [comment]
Slate bot you're a bad bot

**Comment by JayBox325** [comment]
Still keen to get this added. This should be reopened.
