### ISSUE TITLE
Thai Year: how to comply with the Buddhist calendar year 

### ISSUE THREAD

**Issue by fishNimo** [Hacker0x01/react-datepicker#3266]
There was an issue about th year, but it was closed since no further activity occurs. It's really a valid issue. Could you please take a look at it?

![image](https://user-images.githubusercontent.com/62533432/137269733-7a2542dd-0fcd-4ce7-a146-a07345d5c30b.png)

![image](https://user-images.githubusercontent.com/62533432/137269795-dbdf33b3-5103-4869-ba31-4521894e26f8.png)

**Comment by fishNimo** [comment]
Any updates on this issue?

**Comment by carryall** [comment]
I think it's because this date picker relies on [date-fns internationalization](https://date-fns.org/v2.0.0-alpha.18/docs/I18n) for localization and `date-fns`'s [Thai locale](https://github.com/date-fns/date-fns/tree/master/src/locale/th) only support BC year 😢
