### ISSUE TITLE
Custom Input toggle issue

### ISSUE THREAD

**Issue by theabdulmateen** [Hacker0x01/react-datepicker#3267]
Custom input toggle does not work because `onClickOutside` gets triggered every time the custom input is clicked it fires the `onClickOutside` and then the `onClick` of custom input.

**Comment by roivasxxx** [comment]
Same issue happening to me **when using device toggle**. When not using it it behaves somewhat as expected, where **clicking the custom input opens the calendar and clicking it again closes it** (it is actually closed by onClickOutside event but whatever, it works), however with the device toggle on clicking it again (when calendar is open)  fires the onClickOutside and then fires the input's onClick right away, which just reopens it. Running the sandbox works as expected, however running the code locally with device toggle on results in this issue.
![device toggle that I am referring to](https://user-images.githubusercontent.com/72450652/192551614-dd7fcb12-46cd-4029-a092-ddaae0a8834b.png)

Will the same behaviour happen on mobile devices, if yes, is there a simple way of fixing it (without manually handling this behaviour in something like the onClick event).
Thx


 [sandbox](https://codesandbox.io/s/react-datepicker-custom-input-onclickoutside-uxjxgi?file=/src/App.js)

**Comment by senabo** [comment]
Found a solution: https://github.com/Hacker0x01/react-datepicker/issues/3778#issuecomment-1272560156
