### ISSUE TITLE
navigation button displays "Previous month" and "next month" in a buggy way, not able to remove it

### ISSUE THREAD

**Issue by ggustav1** [Hacker0x01/react-datepicker#3285]
**Describe the bug**
Buttons "react-datepicker__navigation--previous" and "react-datepicker__navigation--next" with the span "react-datepicker__navigation-icon react-datepicker__navigation-icon--previous" has a text inside with respectively "Previous month" and "Next month". 

The text are displayed at the top of the date picker in a buggy way where you can only see part of the span text. There is no way for me to hide this text, since it is inside the arrow icon and thus I would have to hide the icon as well, which wouldn't be a good thing. 

![image](https://user-images.githubusercontent.com/44088380/138888253-0ed7d45e-ad8c-4ccd-8c18-df4fceb6f8ea.png)

![image](https://user-images.githubusercontent.com/44088380/138888384-355d1372-f338-4dff-b5d4-d14d757d34f8.png)

![image](https://user-images.githubusercontent.com/44088380/138888480-4d03cdde-31af-444a-ac13-04468ddea57f.png)

- OS: Windows
- Browser chrome
- Version: 94.0.4606.81

**Comment by jerlam06** [comment]
I am having the exact same issue.
