### ISSUE TITLE
Re-rendering datepicker causes setState error 

### ISSUE THREAD

**Issue by raptoria** [Hacker0x01/react-datepicker#329]
I have a page that re-mounts the same component when a new date is selected (with a new key, so the old DOM is tossed out).  The problem I have is 
the hideCalendar function gets called after the old datepicker component has already been removed.

the error:
setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the DatePicker component.

the source:
setTimeout(function(){e.setState({focus:!1})},0)}

Are there any plans to check if the component is mounted first before calling setState inside this function? Or is there a better way to solve this problem?

Thanks!

**Comment by rafeememon** [comment]
This was fixed with #319 (all async operations where this can happen have been removed), but I don't think it's been released yet.  @martijnrusschen should we cut a release?

**Comment by martijnrusschen** [comment]
Yep sounds good. I'll try to get a release out today.

**Comment by raptoria** [comment]
awesome. can't wait!

**Comment by martijnrusschen** [comment]
Just ran a release and updating the component to 0.20.0 should solve the problem. Can you confirm this works?

**Comment by raptoria** [comment]
getting this error upgrading to the latest:

clacey@clacey-VirtualBox:~/react-flask$ npm install react-datepicker --save
npm WARN package.json react-flask@0.0.0 No repository field.
npm WARN peerDependencies The peer dependency react@^0.14.7 included from react-addons-shallow-compare will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
react-datepicker@0.20.0 node_modules/react-datepicker
├── react-onclickoutside@4.5.0
├── classnames@2.2.3
└── react-tether@0.1.2 (tether@1.1.1, react@0.14.7, react-addons-shallow-compare@0.14.7)
clacey@clacey-Virtu

running the code:

ERROR in ./~/react-datepicker/dist/react-datepicker.min.js
Module not found: Error: Cannot resolve module 'tether' in /home/clacey/react-flask/node_modules/react-datepicker/dist
 @ ./~/react-datepicker/dist/react-datepicker.min.js 1:170-187
webpack: bundle is now VALID.

**Comment by martijnrusschen** [comment]
I guess the error might be in this file https://github.com/Hacker0x01/react-datepicker/blob/57d422bbb4d516f969f3fe2336bc1609510cdf33/webpack.config.js#L56. We moved from plain tether.js to a React package that creates wrapper around tether. Can you confirm this @rafeememon?

**Comment by rafeememon** [comment]
Ah, darn.  Looks like the tether declaration needs to be removed (rather than replaced with react-tether as it looks like react-tether doesn't export a global).  I think this is safe because classnames appears to work without an issue.

**Comment by rafeememon** [comment]
Per #335, this should address all of the issues here.
