### ISSUE TITLE
Show 2 time inputs with monthsShown={2}

### ISSUE THREAD

**Issue by DenysPavlenko** [Hacker0x01/react-datepicker#3290]
**Describe the bug**
I am trying to use date range with time. I need to have 2 time inputs for each displayed calendar
**To Reproduce**
Add monthsShown={2} and showTimeInput={true} to see what I mean.
**Expected behavior**
Should display 2 time inputs for each month calendar

**Screenshots**
![image](https://user-images.githubusercontent.com/37882647/139279377-c0faf672-f157-4d2c-bc72-96244641a365.png)

**Comment by BegovicPetar** [comment]
@DenysPavlenko have you solved this?

**Comment by orelHAnyvision** [comment]
same issue here. any suggestions?

**Comment by standbyoneself** [comment]
Same. Is the project alive?
