### ISSUE TITLE
Time Input keeps slowly scrolling up/down after the user stops doing so.

### ISSUE THREAD

**Issue by bmcn99** [Hacker0x01/react-datepicker#3296]
**Describe the bug**
When using the time input selector and scrolling to select your value the column will keep slowly scrolling after the user has stopped doing so, even once they leave the column. It doesn't seem to start this behavior right off the bat but rather after scrolling up and down a little bit first? I made a clip of it here: https://gfycat.com/plainwildargentineruddyduck

**To Reproduce**

1. Fresh 'npm i' with the latest version (currently "react-datepicker": "^4.3.0",)
2. 
<DatePicker 
    showTimeInput
    //Other stuff removed so we can prevent the cause being something else
/>
3. My video showing this behavior had the other fields included because they were going to be part of the design, but I stripped out everything except showTimeInput being passed in, tested it, and the behavior still remained.

**Expected behavior**
Scrolling should stop when the user stops.

**Screenshots**
Needs a video: https://gfycat.com/plainwildargentineruddyduck

**Desktop (please complete the following information):**

- OS: macOS Big Sur version 11.0.1
- Browser Chrome Version 95.0.4638.54 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

N/A

**Additional context**
The minute column is the one mostly affected by this. The hour column is also affected by this behavior but much less so, usually only scrolling one or two more ticks.

**Comment by SuraniKaushika** [comment]
I also experienced this same issue. Can anyone attend to this?

**Comment by asergb-churon** [comment]
I also have the same issue. I'll post if i find a workaround

**Comment by asergb-churon** [comment]
i found a naughty workaround:
just use a different package lmao

```javascript
import DatePicker from 'react-native-date-picker'
import { ScrollView, Text } from 'react-native';

export default function EntryPoint() {
  const [date, setDate] = useState(new Date())
  const [open, setOpen] = useState(false)

  return (
    <ScrollView scrollEnabled={!open}>
      <Button title="Open" onPress={() => setOpen(true)} />
      <DatePicker
        modal
        open={open}
        date={date}
        onConfirm={(date) => {
          setOpen(false)
          setDate(date)
        }}
        onCancel={() => {
          setOpen(false)
        }}
      />
    </ScrollView>
  )
}
```
