### ISSUE TITLE
Datepicker 0.20 doesn't work in react-bootstrap's modal

### ISSUE THREAD

**Issue by vojty** [Hacker0x01/react-datepicker#332]
0.19 was fine
There is no error in console...

**Comment by rafeememon** [comment]
Probably a z-index issue; try finding the `datepicker__tether-element` at the end of the DOM when you click the picker, and increasing its z-index until it's visible.

**Comment by vojty** [comment]
yeah that's, thank you!

**Comment by rafeememon** [comment]
Woot!
