### ISSUE TITLE
Two dates selected at once

### ISSUE THREAD

**Issue by john-fk** [Hacker0x01/react-datepicker#3321]
**Describe the bug**
A selected date is also selected in previous month

**To Reproduce**

1. Go to any  datepicker
2. Click on the date that will show you the following month (e.g. dates after 30/31 of the current month)
3. When month is moved forward, move back one month
4. Now the date selected is both selected on the currently selected month and also the next month

**Expected behavior**
When returning / moving to another month, 1 date (the current month) should be selected

**Screenshots**
![image](https://user-images.githubusercontent.com/83055097/143587271-f61b949a-62a8-4d4f-a8a9-a43c9f86b0b5.png)

**Desktop (please complete the following information):**

- OS: Windows 11 - Latest release
- Browser Edge
- Version Latest

**Comment by eamiralian** [comment]
Duplicate of 2565
