### ISSUE TITLE
Karma is not running all the tests

### ISSUE THREAD

**Issue by zzwt** [Hacker0x01/react-datepicker#3325]
**Describe the bug**
It seems like karma is not running all tests in test folder, or did i miss something?

**To Reproduce**
1. Get a clean clone of the project.
2. yarn install package and then run "yarn test"
3. Test will pass but only 471 tests were run. If you run "yarn test" multiple times, the tests number ran will be different each time as shown in the first two screenshots.

**Expected behavior**
All tests should be ran. Total test number should be 632 (I disabled the 2 problematic cases as in the screenshot 3).

**Screenshots**
![image](https://user-images.githubusercontent.com/12154828/143992327-6d38c92a-ec2f-4a5d-9e83-e692de5e16ee.png)
![image](https://user-images.githubusercontent.com/12154828/143992343-667562a5-8a62-42d4-a42d-9b5ff0f5f068.png)
![image](https://user-images.githubusercontent.com/12154828/143992502-756c40e3-995f-4e44-a909-3e88253c9fc0.png)

**Desktop (please complete the following information):**
node: 14.18.1
os: windows 10

**Additional context**
Investigation so far:
In day_test.js file, the "last two" test cases about "focus" using defer callback seems to be causing the issue. If i comment those 2 test cases out, it will behave as expected. The testing code seems to be fine to me as defer is being used in other places.

**Comment by martijnrusschen** [comment]
Interesting, we should go ahead and disable those 2 tests for now in favor of running the whole suite. Let's look into the failing test after that.
