### ISSUE TITLE
ES6 imports importing dependencies with Webpack

### ISSUE THREAD

**Issue by te-chris** [Hacker0x01/react-datepicker#333]
I've just added react-datepicker to my project and imported it like so:

`import DatePicker from 'react-datepicker'`

This seems to import all of react-datepickers dependencies, leading to moment and react being loaded twice.  I think this is due to bower requiring its dependencies as well as webpack loading the npm dependencies.  Is there a way around this?

Thank you

**Comment by rafeememon** [comment]
Hey @te-chris, a couple questions:

* Are you installing the datepicker via npm or bower?
* What does your dependency tree under `react-datepicker` look like, i.e. are `moment` and `react` included in `node_modules` **under react-datepicker**?  Or are they only in your topmost `node_modules`?

**Comment by te-chris** [comment]
hey @rafeememon thanks for getting back to me.  installed via NPM, moment and react are both already in the project.

**Comment by rafeememon** [comment]
@te-chris, right, but are they also present in `node_modules` under `react-datepicker`?  If they are, they'll be loaded separately because of how node resolves dependencies.  Deleting them from there should do the trick.

**Comment by rafeememon** [comment]
Oh, also, what versions of moment and react are you using in your project?  If they're different versions than what satisfy the datepicker's dependencies (currently react is ^0.14.0, moment is ^2.10) then the datepicker will install and load them as additional dependencies.

**Comment by te-chris** [comment]
Here's my package.json 

```
{
  "private": true,
  "version": "0.0.1",
  "description": "YOUR DESCRIPTION - Generated by generator-react-webpack",
  "main": "",
  "scripts": {
    "clean": "rimraf dist/*",
    "copy": "copyfiles -f ./src/index.html ./src/favicon.ico ./dist",
    "dist": "npm run copy & webpack --env=dist",
    "lint": "eslint ./src",
    "posttest": "npm run lint",
    "release:major": "npm version major && npm publish && git push --follow-tags",
    "release:minor": "npm version minor && npm publish && git push --follow-tags",
    "release:patch": "npm version patch && npm publish && git push --follow-tags",
    "serve": "node server.js --env=dev",
    "serve:dist": "node server.js --env=dist",
    "start": "node server.js --env=dev",
    "test": "karma start",
    "test:watch": "karma start --autoWatch=true --singleRun=false"
  },
  "repository": "",
  "keywords": [],
  "author": "Your name here",
  "devDependencies": {
    "accounting": "^0.4.1",
    "babel-core": "^6.0.0",
    "babel-eslint": "^5.0.0-beta4",
    "babel-loader": "^6.0.0",
    "babel-preset-es2015": "^6.0.15",
    "babel-preset-react": "^6.0.15",
    "bower-webpack-plugin": "^0.1.9",
    "chai": "^3.2.0",
    "copyfiles": "^0.2.1",
    "css-loader": "^0.23.0",
    "eslint": "^1.2.1",
    "eslint-loader": "^1.0.0",
    "eslint-plugin-react": "^3.3.0",
    "file-loader": "^0.8.4",
    "glob": "^6.0.0",
    "isparta-instrumenter-loader": "^1.0.0",
    "karma": "^0.13.9",
    "karma-chai": "^0.1.0",
    "karma-coverage": "^0.5.3",
    "karma-mocha": "^0.2.0",
    "karma-mocha-reporter": "^1.1.1",
    "karma-phantomjs-launcher": "^0.2.1",
    "karma-phantomjs-shim": "^1.1.1",
    "karma-sourcemap-loader": "^0.3.5",
    "karma-webpack": "^1.7.0",
    "lodash": "^3.10.1",
    "minimist": "^1.2.0",
    "mocha": "^2.2.5",
    "moment": "^2.11.1",
    "node-sass": "^3.4.2",
    "null-loader": "^0.1.1",
    "open": "0.0.5",
    "phantomjs": "^1.9.18",
    "postcss": "^5.0.11",
    "postcss-loader": "^0.8.0",
    "postcss-svg": "^1.0.4",
    "react-addons-test-utils": "^0.14.0",
    "react-hot-loader": "^1.2.9",
    "react-modal": "^0.6.1",
    "rimraf": "^2.4.3",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.6",
    "webpack": "^1.12.0",
    "webpack-dev-server": "^1.12.0"
  },
  "dependencies": {
    "alt": "^0.18.1",
    "alt-utils": "^1.0.0",
    "calc-polyfill": "^0.1.0",
    "core-js": "^2.0.0",
    "formsy-react": "^0.17.0",
    "history": "^1.17.0",
    "immutable": "^3.7.6",
    "jquery": "^1.11.3",
    "lockr": "^0.8.4",
    "lost": "^6.6.3",
    "lt-ie-9": "^0.1.0",
    "normalize.css": "^3.0.3",
    "react": "^0.14.0",
    "react-date-picker": "^4.0.6",
    "react-datepicker": "^0.20.0",
    "react-dom": "^0.14.0",
    "react-input-range": "^0.6.1",
    "react-router": "^1.0.3",
    "react-slick": "^0.9.3"
  }
}
```

**Comment by rafeememon** [comment]
@te-chris, again, please look in `node_modules/react-datepicker/node_modules` and tell me what's there =)

**Comment by te-chris** [comment]
Sorry, there's no `node_modules` dir in there.  there is a `bower_components` dir

**Comment by rafeememon** [comment]
Ah, I think npmv3 changed how dependencies are resolved.  What version of node and npm are you using?

What are you observing that is telling you that react and moment are being loaded twice?

**Comment by rafeememon** [comment]
Just looked into `bower-webpack-plugin`, and it looks like it's making webpack look in `bower_components` for dependencies.  I'd recommended using either npm or bower for dependencies, but not both; sometimes they can interact in strange ways.  If you don't explicitly need `bower-webpack-plugin` I'd get rid of it.

We officially removed bower support in #330, so we should probably stop publishing the bower_components directory anyway.

**Comment by te-chris** [comment]
Using node 5.4 and latest npm.  Oh of course! Sorry didn't even notice that - a hangover from the generator.  Will remove as we're not using bower at all

**Comment by te-chris** [comment]
Removed the bower loader and still getting this
![screen shot 2016-02-04 at 13 30 44](https://cloud.githubusercontent.com/assets/392904/12816308/90d94c76-cb43-11e5-9661-1d4249c8befc.png)

**Comment by rafeememon** [comment]
Hmm, are you sure you removed all references to bower in your config?  Looks like there are ways to load from bower in addition to the webpack plugin, e.g. https://webpack.github.io/docs/usage-with-bower.html

**Comment by te-chris** [comment]
Thanks for persisting, that was the issue.  Appreciate your patience! :)

**Comment by rafeememon** [comment]
Awesome, glad you got it working!

Also, completely out of curiosity, I see you also have `react-date-picker` in your package.json -- are there any features in that picker that you'd like to see here?

**Comment by te-chris** [comment]
Tbh I just needed one that worked as one a deadline so that was the next choice ;)
