### ISSUE TITLE
Error : Module build failed:

### ISSUE THREAD

**Issue by nsisodiya** [Hacker0x01/react-datepicker#337]
ERROR in ./~/react-datepicker/dist/react-datepicker.min.js
Module build failed: ReferenceError: [BABEL] /Users/narendrasisodiya/projects/hotelsoft/rzr-ui/node_modules/react-datepicker/dist/react-datepicker.min.js: Unknown option: /Users/narendrasisodiya/projects/hotelsoft/rzr-ui/node_modules/react-datepicker/.babelrc.presets

any idea ?

**Comment by nsisodiya** [comment]
@rafeememon When I remove .bablerc file, everythings works fine.
I am using old 5.xxx version for my project which i cannot migrate. Any idea, how to correct this error !

**Comment by martijnrusschen** [comment]
Have you tried this with the latest version? We changed some things in how we serve files to the package. This might work for you too.

**Comment by nsisodiya** [comment]
I am using `"react-datepicker": "0.20.0",`

**Comment by martijnrusschen** [comment]
Please try 0.21.0

**Comment by nsisodiya** [comment]
Problem solved..
