### ISSUE TITLE
with the official demo, why 2022 January create the last line ? it`s a bug , right>?

### ISSUE THREAD

**Issue by singleseeker** [Hacker0x01/react-datepicker#3371]
![image](https://user-images.githubusercontent.com/520698/145337605-b7dbe90c-1004-408a-9e20-e01c115d078b.png)

**Comment by zzwt** [comment]
The demo is setting peekNextMonth, which is the expected behavior.

**Comment by singleseeker** [comment]
Yes, you are right.
Thank you.
