### ISSUE TITLE
Date input doesn't format according to locale

### ISSUE THREAD

**Issue by ephill** [Hacker0x01/react-datepicker#3375]
**Describe the bug**
I registered the relevant locales for my application which changed the text within the date picker but the input field for the picker still uses the default locale's date format. If I force the input's value to the right value for, as an example, the ru-RU locale react-datepicker produces an "Invalid Date" message when I try to edit the input. How can I make the date format in the input adapt to the locale?

**To Reproduce**

1. Register locales:
```
import { cs, de, enAU, enCA, enGB, enUS, pl, pt, ru } from 'date-fns/locale';
registerLocale('en-US', enUS);
registerLocale('en-GB', enGB);
registerLocale('de', de);
registerLocale('de-DE', de);
registerLocale('en-CA', enCA);
registerLocale('pl', pl);
registerLocale('pl-PL', pl);
registerLocale('cs', cs);
registerLocale('cs-CZ', cs);
registerLocale('en-AU', enAU);
registerLocale('pt', pt);
registerLocale('pt-PT', pt);
registerLocale('ru', ru);
registerLocale('ru-RU', ru);
```

2. Render date picker with locale:
```
    <ReactDatePicker
      locale={locale}
      onChange={handleOnChange}
      selected={selectedJsDate}
    />
```

3. Set your locale to something other than the global default
4. Open the date picker

**Expected behavior**
Date format in the input would be correct for the chosen locale.

**Screenshots**
![image](https://user-images.githubusercontent.com/7432775/145781759-8ba4c3c7-a9f8-42ed-b099-70a40f5d06e8.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Chrome
- Version: 96.0.4664.93

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**

**Comment by jgradzki** [comment]
You need to pass ` dateFormat="Pp"` for example. 
Default value is: https://github.com/Hacker0x01/react-datepicker/blob/50488b4f54656aefc272fbf61ba26d9d67f1e9d5/src/index.jsx#L71

Check bottom of this table: https://date-fns.org/v2.28.0/docs/format
(Long localized date, Long localized time, Combination of date and time)
