### ISSUE TITLE
How do I change text to my native language?

### ISSUE THREAD

**Issue by stevenKirill** [Hacker0x01/react-datepicker#3376]
Hello, I would like to ask a question, how I can change time label to my native language , thanks very much for help in advance
<img width="312" alt="date" src="https://user-images.githubusercontent.com/47239173/145821821-a21bd484-b412-4948-bd17-a0e729fc19e2.png">

**Comment by SveinJarleReiakvam** [comment]
Have you tested the prop locale?
https://reactdatepicker.com/#example-locale-with-time

**Comment by PCPbiscuit** [comment]
hey
Use prop locale="ru"

**Comment by alexHlebnikov** [comment]
NWM, you just need to use timeCaption prop.
