### ISSUE TITLE
Not working with React 16

### ISSUE THREAD

**Issue by jespadas** [Hacker0x01/react-datepicker#3409]
Before you start - checklist
 I followed instructions in documentation written for my React-Date-Picker version
 I have checked if this bug is not already reported
Description
I'm having an issue with the version 4.5.0. I can't work with library it crash everytime I try.

Steps to reproduce
I just installed the newest version using :
"react": "16.0.0",
"react-datepicker": "^4.5.0",
"react-dom": "16.0.1",
"react-pie-progressbar": "^0.6.8",
"react-redux": "^5.0.6",
"react-router-dom": "^4.3.1"

I just followed the Install steps...

Expected behavior
The expected behavior is the library working !

Actual behavior
Instead I have this error :
webpackerror
![webpackerror](https://user-images.githubusercontent.com/35740179/147681193-6ef0d94f-0a7e-42cb-8363-f5a244efca97.png)

Additional information
I tried with other versions and nothing.

Environment
"react": "16.0.0",
"react-datepicker": "^4.5.0",
"react-dom": "16.0.1",
"react-pie-progressbar": "^0.6.8",
"react-redux": "^5.0.6",
"react-router-dom": "^4.3.1",

**Comment by jespadas** [comment]
Anyone ?

**Comment by tu4mo** [comment]
The documentation is wrong. You need at least React 16.3 to enable `createContext`.

**Comment by jespadas** [comment]
> The documentation is wrong. You need at least React 16.3 to enable `createContext`.

But I tried even with React 16.4.1 and nothing. Now is working but with React 16.9.x and I'm making tests with all the libraries that were installed before.
