### ISSUE TITLE
Change logs are missing in the last few releases

### ISSUE THREAD

**Issue by ljmerza** [Hacker0x01/react-datepicker#3426]
**Describe the bug**
change logs are missing after v4.2.1 release. We use these to verify any changes before updating libraries. Please update the change logs for newer releases.

**To Reproduce**
go to releases section and see there are no logs for the last few releases

**Expected behavior**
a bullet point of chagnes in the release

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Miladiir** [comment]
4.7.0 does not have release notes or a changelog and not even a version on Github, only a tagged commit in git.
