### ISSUE TITLE
Unable to manually input dates in input box when selectsRange is true

### ISSUE THREAD

**Issue by fgblomqvist** [Hacker0x01/react-datepicker#3429]
**Describe the bug**
It is currently impossible to manually enter dates in the textbox when the datepicker is configured to select a range.

**To Reproduce**

1. Go to https://reactdatepicker.com/#example-date-range-using-input-with-clear-button.
2. Select a range.
3. Try to modify the text in the input, e.g. decrementing the left year by one.
4. Press enter.
5. Watch how the text resets back to what it was before.

**Expected behavior**
It should work to manually input text, similar to how it works with single date selects.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox
- Version: 95

**Comment by FromLightbeam** [comment]
```js      
<DatePicker
  onChange={handleDateChange}
  onChangeRaw={e => {
    if (e.target.value) {
      const dates = e.target.value.split(' - ').map(date => {
        const d = new Date(date);
        return isValidDate(d) ? d : null;
      });
      handleDateChange(dates);
    }
  }}
  selectsRange
  startDate={startDate}
  endDate={endDate}
/>
```

I found a workaround for this issue by overriding `onChangeRaw`

**Comment by karolis-cekaitis** [comment]
having same issue

**Comment by ChinmoyRaj123** [comment]
I am facing the same issue. Please fix the bug asap.

**Comment by mjsawyers** [comment]
Any update on this issue? I assume that using the selectsRange within one datepicker is a common use case, and I'd love to see manual input work in that scenario.
