### ISSUE TITLE
how to stop auto date complete while typing with keyboard

### ISSUE THREAD

**Issue by mmarshad** [Hacker0x01/react-datepicker#3440]
my application needs to support accessibility for end users where some special user needs to type date manually using keyboard instead of selecting from calendar  e.g blind people etc
The issue is that soon you type first digit like 01/ , the control automatically completes it with 01/01/2000 etc and not allowing the user to type the date themselves. it also takes the focus out from the field too so user do not know what happens and they keep typing thinking its typing in the field.

How can I stop this autocomplete feature.

**Comment by evolve2k** [comment]
Ammusingly, I'm old an old version and am wanting to turn this feature on.
Can you also let us know which release/commit this feature was added in?

**Comment by mmarshad** [comment]
we are using 4.1.1 version

**Comment by CharlesCoqueret** [comment]
@mmarshad looks like setting: autoComplete="off" does the job.

**Comment by betatester07** [comment]
> @mmarshad looks like setting: autoComplete="off" does the job.

works for me too!

**Comment by yuki0410-dev** [comment]
This issue seems to have already been resolved.
If it seems to be OK, I would appreciate it if you could CLOSE it.
( cc. @martijnrusschen  )
