### ISSUE TITLE
Browser translator messing with days-of-the-week names

### ISSUE THREAD

**Issue by ffranco-a** [Hacker0x01/react-datepicker#3442]
**Describe the bug**
Days names ("Su Mo Tu We Th Fr Do") are incorrectly translated when a browser built-in translator is on.

**To Reproduce**
1. Render component
2. Activate browser built in translator
3. Check days-of-the-week names

**Expected behavior**
A correct translation, or no translation at all (translate="no")

**Screenshots**
![reporte 1 - ingles orig](https://user-images.githubusercontent.com/84511984/150337182-182f8b29-bd89-4a67-87c9-6ac15147beed.png)
![reporte 2 - ingles trad](https://user-images.githubusercontent.com/84511984/150335692-641a4ac4-5a74-4f1b-aa12-a6edaac7dbd6.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Edge
- Version: you mean browser version?? 97.0.1072.62

**Comment by gabrielareia** [comment]
This is happening to me as well, and I don't even have the translator on, I think it is just the locale. 

It is converting the day of the week in portuguese: **seg, ter, qua, qui, sex** to ordinal numbers in portuguese. ("seg" stands for "segunda" which is "second" as in the second day of the week, "ter" for "terça", which translates to third, the third day of the week, and so on...)

It wasn't happening in version 2.15.0, I just updated to 4.5.0 and it started to happen.

![image](https://user-images.githubusercontent.com/68579209/150604416-87479bb2-f653-4083-8199-5548bc5b6ce9.png)
