### ISSUE TITLE
dateFormat does not reflect the chosen locale

### ISSUE THREAD

**Issue by alex-piccione** [Hacker0x01/react-datepicker#3447]
**Describe the bug**
When a _locale_ is passed the _dateFormat_ should reflect that locale and not using the default MM/dd/yyyy.

**To Reproduce**
1. Use the provided example for setting the locale: 
```javascript
import { registerLocale, setDefaultLocale } from  "react-datepicker";
import es from 'date-fns/locale/es';
registerLocale('es', es)

<DatePicker
  locale="es"
/>
```

2. Look at the date in the textfield, it is in the format **MM/dd/yyyy**

**Expected behavior**
The date in the textbox should be in the format **dd/MM/yyyy**

**Screenshots**

![image](https://user-images.githubusercontent.com/876490/150633593-63aa20c4-6071-428a-ad7f-10b7d958f18a.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version latest

**Smartphone (please complete the following information):**

Not tested on smartphone.

**Additional context**
Sandbox: https://codesandbox.io/s/es-locale-forked-0d4ck

**Comment by mkaivanto** [comment]
#3375

Use `dateFormat` prop with eg.
`'P'` for Long localized date
`'p'` for Long localized time
`'Pp'` for Combination of date and time
