### ISSUE TITLE
showYearDropdown is not working with monthYearPicker 

### ISSUE THREAD

**Issue by Donorlin** [Hacker0x01/react-datepicker#3448]
**Describe the bug**
Property `showYearDropdown` is not working when datepicker is in the `monthYearPicker` mode

**To Reproduce**
```
() => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      showMonthYearPicker
      showYearDropdown
    />
  );
};
```

**Expected behavior**
I would expect a year dropdown in month year picker header as in [https://reactdatepicker.com/#example-year-dropdown](https://reactdatepicker.com/#example-year-dropdown)

**Versions:**
react-datepicker 4.6.0
react: 16.14.0
react-dom: 16.14.0

**Comment by sathishkumarssk** [comment]
i am also expecting this feature. let's see..

**Comment by kamnakis** [comment]
`monthYearPicker` also does not work with `customHeader` ☹️

**Comment by Dahmon** [comment]
Yep same problem here.
