### ISSUE TITLE
If not selected date and  is Clearable = true and set endDate then clear icon show

### ISSUE THREAD

**Issue by sergeushenecz** [Hacker0x01/react-datepicker#3453]
**Describe the bug**
If not selected date and  is Clearable = true and set endDate then clear icon show

**Expected behavior**
clear icon to need show only if we select date. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7217517/151660489-874708c6-65c4-4df8-be29-0cf07dbde790.png)

**Comment by lu-ne-va** [comment]
I faced the same issue. Is there any update?

**Comment by 0x54321** [comment]
A workaround is to make `isClearable` dependent on the selection value – i.e., `isClearable={!!startDate}` or `isClearable={!!endDate}`.

**Comment by smenshikov** [comment]
Same issue!

**Comment by smenshikov** [comment]
> A workaround is to make `isClearable` dependent on the selection value – i.e., `isClearable={!!startDate}` or `isClearable={!!endDate}`.

It works! Thanks
