### ISSUE TITLE
Past days are not disabled when using a date range

### ISSUE THREAD

**Issue by MichaelLiss** [Hacker0x01/react-datepicker#3466]
**Describe the bug**
I set the data picker to disable the days "in the past" (showDisabledMonthNavigation) but days in the past can still be selected

**To Reproduce**
run the code and select a date in the past
```
() => {
  const [dateRange, setDateRange] = useState([new Date(), new Date()]);
  const [startDate, endDate] = dateRange;
  return (
    <DatePicker
      selectsRange={true}
      startDate={startDate}
      endDate={endDate}
      onChange={(update) => {
        setDateRange(update);
      }}
      isClearable={true}
      showDisabledMonthNavigation
    />
  );
};
```

**Expected behavior**
User cannot select dates in the past

**Desktop (please complete the following information):**

- OS: [e.g. iOS] windows 11
- Browser [e.g. chrome, safari]  Chrome
- Version [e.g. 22] latest

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] - n/a
- OS: [e.g. iOS8.1] - n/a
- Browser [e.g. stock browser, safari] - n/a
- Version [e.g. 22] - n/a

**Additional context**
nothing more to add

**Comment by alialtun01** [comment]
Any Solution ?

**Comment by etienne-bondot** [comment]
I think you can try to filter available dates with the `filterDate` property.
