### ISSUE TITLE
onChange is not working if onChangeRaw is provided

### ISSUE THREAD

**Issue by lifeisegg123** [Hacker0x01/react-datepicker#3482]
**Describe the bug**
onChange is not working if onChangeRaw is provided. I expect when both provided, on input, onChangeRaw is triggered, on select, onChange is triggered

**To Reproduce**
1. set both onChange and onChangeRaw
2. select any date from calendar
3. it fires onChangeRaw event not onChange

**Expected behavior**
 onChange is triggered when select date, onChangeRaw is triggered when type on input

**Desktop (please complete the following information):**

- OS: [Mac OS Monteray]
- Browser [chrome]
- Version [92]

**Comment by Kucerenko171** [comment]
@lifeisegg123 Try to add `e.preventDefault()`

e.g.
`onChangeRaw={(e) => {
e.preventDefault()
//other code...
}`
