### ISSUE TITLE
How to center inline datepicker?

### ISSUE THREAD

**Issue by kuriel-trivu** [Hacker0x01/react-datepicker#3484]
![image](https://user-images.githubusercontent.com/46456105/155266740-c65630db-2a62-4383-b148-47f63d2893bd.png)

**Comment by kuriel-trivu** [comment]
can the aditional div created by the component, have a css class? to set a container styles.

**Comment by gabrielleford** [comment]
I'm not sure if you ever figured this out, and I know it's a few months old, but I came here looking for a similar answer and finally figured out a way to do it. First, I created a wrapper around the inline `<Datepicker />`
```
<div classname='calendarWrapper'>
  <Datepicker 
    selected={startDate} 
    minDate={new Date()} 
    maxDate={new Date(year, month + 6, day)} 
    onChange={dateRange} 
    startDate={startDate} 
    endDate={endDate} 
    showDisabledMonthNavigation 
    selectsRange 
    inline
  />
<div>
```
Then I applied this for the CSS
```
.calendarWrapper {
  display: flex;
  justify-items: center;
  margin: 0 auto 0 auto;
  width: fit-content;
}
```
