### ISSUE TITLE
Today button action

### ISSUE THREAD

**Issue by rafeememon** [Hacker0x01/react-datepicker#351]
The today button sets the selected date to the current date, which also closes the calendar.  This was a little bit jarring to me the first time I tried it, but I'll admit that I might be crazy, haha.  An alternative action would be to set the calendar to the current month but don't change the selected date, which is how other datepickers that I've used work.  The user would still be required to click the (bolded) current day, and I think it may be less jarring.  Not sure what the best thing to do here is.

Thoughts?

**Comment by martijnrusschen** [comment]
Hmm didn't have the same feeling. To me the today button feels more like a special button that behaves like the other date inputs. Do we have other examples of these buttons that are behaving different?

**Comment by rafeememon** [comment]
Looks like bootstrap-datepicker provides a switch called `linked` for this: https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#todaybtn

I don't feel strongly about it either way.  We can leave this open for now and see what other people think.

**Comment by rafeememon** [comment]
Let's stick with the current behavior
