### ISSUE TITLE
Triangle/arrow tries to get centered on the input, making it look weird for big ones

### ISSUE THREAD

**Issue by acelaya** [Hacker0x01/react-datepicker#3514]
**Describe the bug**

I was investigating why the triangle/arrow on the datepicker was being rendered completely to the right of the popover, when I noticed it had a `left` property set on it.

After some try and error I have noticed it takes the size of the input and calculates the `left` css property of the triangle based on that, so that it appears centered on the input.

However, for big inputs, that looks weird.

**To Reproduce**

It can be easily reproduced directly in https://reactdatepicker.com/

1. Go to https://reactdatepicker.com/
2. Open the browser's developer tools
3. Edit the CSS of the first input, setting `width: 500px;`
4. Scroll up/down to force the datepicker to re-render

**Expected behavior**

I would expect the triangle position to be calculated based on the popover size, not the input size.

**Screenshots**

![image](https://user-images.githubusercontent.com/2719332/157902506-0a947eee-cc00-480d-8943-37207bb97193.png)

**Desktop (please complete the following information):**

- OS: [Ubuntu]
- Browser [chrome]
- Version [e.g. 99]

**Comment by TobbeLundberg** [comment]
You can also see this in the official documentation 
![image](https://user-images.githubusercontent.com/87008627/159477326-dd32bf99-be7f-4191-a97d-7e6740aa6721.png)

**Comment by TobbeLundberg** [comment]
Two related issues: https://github.com/Hacker0x01/react-datepicker/issues/3254
https://github.com/Hacker0x01/react-datepicker/issues/3176

**Comment by singleseeker** [comment]
@TobbeLundberg Find its parent element and give some width to it.

**Comment by kingston** [comment]
I found a solution for this issue using the `popperModifiers` property that I added as a comment here: https://github.com/Hacker0x01/react-datepicker/issues/3176#issuecomment-1262100937
