### ISSUE TITLE
Datepicker wrap in bootstrap group input has wrong offset

### ISSUE THREAD

**Issue by james4388** [Hacker0x01/react-datepicker#353]
I want to add input group with calendar icon for datepicker, this is what I've done:

```
<div className="input-group">
          <span className="input-group-addon" id="basic-addon1"><i className="glyphicon glyphicon-calendar"></i></span>
          <DatePicker className="form-control"
              selected={this.state.selectedDate}
              onChange={this.handleDateChange.bind(this)}
              {...field}
         />
</div>
```

It's worked, amazing

<img width="521" alt="screen shot 2016-02-12 at 1 46 19 pm" src="https://cloud.githubusercontent.com/assets/174132/13021262/167302e0-d18f-11e5-805f-9f0a3fc59950.png">

But when click on it, the calendar got wrong offset coordinate and z-index do not ritght.

<img width="269" alt="screen shot 2016-02-12 at 1 47 55 pm" src="https://cloud.githubusercontent.com/assets/174132/13021288/40e59e20-d18f-11e5-80b5-619678e27b4e.png">

What should I do to improve

**Comment by rafeememon** [comment]
You can adjust the dropdown placement with the `popoverTargetOffset` prop, described here: https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md

**Comment by james4388** [comment]
Oh nice, thanks

**Comment by HadiAkmal** [comment]
@rafeememon 

There's no `popoverTargetOffset` prop in the link you provided. I'm having this problem:

![image](https://user-images.githubusercontent.com/14165645/28086445-9949068e-66b1-11e7-9d9c-b73d81a238c4.png)

Top calendar is having overlay problem with bottom date input field. How do I get the calendar to the front of the input field?

**Comment by artemv** [comment]
For those who came here to fix the input group addon layout issues with DatePicker - there's a relevant https://github.com/Hacker0x01/react-datepicker/issues/484 issue, and solution based on https://github.com/Hacker0x01/react-datepicker/issues/484#issuecomment-264408923 worked for me to solve this issue as well.
