### ISSUE TITLE
installation error in react 18.1.0

### ISSUE THREAD

**Issue by MrMyatNoe** [Hacker0x01/react-datepicker#3584]
**Can't install on react 18.1.0**
I have been working on next.js project with react 18.1.0. After installing, it shows me **peer react@"16.9.0 || 17" from react-datepicker@4.7.0**

- OS: [Ubuntu 20.04]
- Browser [chromium]
- Version [101.0.4951.54 (Official Build) snap (64-bit)]

![Screenshot from 2022-05-08 00-31-47](https://user-images.githubusercontent.com/33978217/167266395-81cbb4ec-db73-401b-adb5-b6c5446cd094.png)

**Comment by rizchaerul** [comment]
Do you find any workaround/solution?

**Comment by maxdbarton97** [comment]
> Do you find any workaround/solution?

Would simply be to run --legacy-peer-deps or downgrade react. No other option sadly.

**Comment by martijnrusschen** [comment]
The latest version added support for React 18
