### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by stevenKirill** [Hacker0x01/react-datepicker#3642]
How can I style  these things react-datepicker__month-container, react-datepicker__header, react-datepicker__month-select, react-datepicker__year-select ? Please help me

**Comment by un1tT** [comment]
@stevenKirill If you are using css/sass/scss:
```
[class*="react-datepicker__month-container"] {
  ...your styles
}
```

Pay attention, that selector `*=` will affect all of the elements that have `"react-datepicker__month-container"` **as part of a class name**, eg `<div class="react-datepicker__month-container myClass myClass2">block</div>`

**Comment by ShaneHudson** [comment]
Given you are just wanting to style elements based on specific classes, you don't even need to use the wildcard selector. You can (and should) do: 

```
. react-datepicker__month-container {
   ... your styles
}
```

**Comment by stevenKirill** [comment]
Greate Shane! Thanks!
