### ISSUE TITLE
Switch to ESlint (What kind of tooling should we use for linters)

### ISSUE THREAD

**Issue by martijnrusschen** [Hacker0x01/react-datepicker#367]
I wanted to start a discussion about what tooling we should use for this component. I'm a fan of ESlint (because they have so much options), but we should evaluate other tooling too. Right now we're using JSCS, which does its job, but I'd like to know what the common toolset is nowadays.

Questions:
- Does it make sense to use both JSCS and ESlint together?
- Are there any other tools we should evaluate?
- What's the standard in other OSS projects?

**Comment by rafeememon** [comment]
Nowadays in my new projects I use [standard](http://standardjs.com/), which is powered by ESLint but has an opinionated set of options.  It's definitely cool that ESLint has so many options, but so much optionality often leads to insignificant debates about style, and you end up with an extremely custom setup.  This makes the project harder to maintain and hinders approachability.  With standard we wouldn't need to make any decisions and instead can use a configuration used by a large portion of the JS community.

I'm not sure that JSCS gives us anything more than standard/ESLint, but in the interest of simplifying the build I'd be in favor of removing it.

**Comment by martijnrusschen** [comment]
We switched to ESLint with standard.js config and specific React rules.
