### ISSUE TITLE
Problem with React Types 18

### ISSUE THREAD

**Issue by tyddynonn** [Hacker0x01/react-datepicker#3708]
After migrating to React 18, I'm getting Typescript compilation error:

TS2786: 'DatePicker' cannot be used as a JSX component.
  Its instance type 'ReactDatePicker<never, undefined>' is not a valid JSX element.

**To Reproduce**
Create an instance of DatePicker:

```
export default function Test() {

    return (
        <>
            <DatePicker
                portalId='portalroot'

                dateFormat="d-MMMM-yyyy"
                onChange={(date: Date) => {
                    Log(`new Date ${date}`)
                }}
            />
        </>
    );
}
```

with the following line in the devDependencies in package.json

`    "@types/react": "^18.0.15",`

**Expected behavior**
successful compilation

**Desktop 

- OS: Win 11
- Browser Chrome

**Additional context**

Reverting the React types to 17.0.47 removes the problem (even whilst using React 18.2.0)

**Comment by ItaloMedici** [comment]
I'm using React Type 17.0.33 and getting the same error here

**Comment by dykarohora** [comment]
This is probably due to the React 17 type definition file being mixed in with your project.

In react-datepicker type definition package, the dependecy of the React type definition looks like this.

```
    "dependencies": {
        "@popperjs/core": "^2.9.2",
        "@types/react": "*",
        "date-fns": "^2.0.1",
        "react-popper": "^2.2.5"
    },
```

Check how your `yarn.lock` (or `package-lock.json`) resolves `@types/react@*`. 
If it references version 17 as shown below, it should be modified to refer to version 18.

```
"@types/react@*":
  version "17.0.38"
```

**Comment by vini-zapid** [comment]
I got the same problem but I just fixed adding the **resolutions** prop into my **package.json** and run **yarn** 

 ```
 "resolutions": {
    "@types/react": "18.0.8",
    "@types/react-dom": "18.0.3"
  },
```

I'm still not quite sure why it works but I'm keen to hear any thoughts 

I noticed that after running yarn, it made this change on **yarn.lock**

<img width="1702" alt="image" src="https://user-images.githubusercontent.com/83197817/188802962-9d4a3091-110f-4091-89e9-21da55113927.png">

**Comment by tyddynonn** [comment]
Fixed it for me too, thanks!
