### ISSUE TITLE
ESC key not doing anything

### ISSUE THREAD

**Issue by fmadden** [Hacker0x01/react-datepicker#372]
So I needed a click handler for this component which provided access to the javascript event and target.  Since I didn't get this from the datepicker's onclick handler, (only provides access to moment) I decided to hide the datepicker input and provide a div.  Onclick of the div, I'm then internally processing and then forwarding a click event on to the datepicker, which pops open the calendar.  In the onchange event handler I'm then updating the div contents.

It works GREAT!!! with the exception that now the datepicker doesn't seem to respond to the ESCape key.

So now in order to process an ESC, which will close the calendar, I'd like to provide an onKeyDown event handler. 

However it looks like the datepicker doesn't provide onKeyDown, onKeyUp, or onKeyPress.  

Additionally, I'm using version 0.13.0 because it has to work with React 0.13.2.

Suggestions and/or thoughts?

**Comment by rafeememon** [comment]
Hey @fmadden, how are you hiding the datepicker input?  Depending on how you're doing that, the browser may not actually be giving focus to the input because it's not in view, and there won't be any keypress events to listen to.  What is the reason for needing access to the click event?  There may be another way to approach the problem.

**Comment by fmadden** [comment]
Hi @rafeememon 
Thank you for your response.

I am hiding the element using visibility: hidden so that it still takes up the physical space it would on the screen and the calendar popup is where I would expect it to be.

The reason I need access to the actual click event, is that we are using this component in an application that needs to send some information to the server as soon as the input element is clicked on, and then once again when the calendar popup is closed.  Because the onChange event does not provide an actual javascript event and target element, I can not obtain the needed information when onchange is fired.  I need much more than simply a date from the onChange event.  I need to know which element on the screen received the date change.  This is because we have several date pickers on the screen, each with unique information assigned to them by the server.

I hope that makes sense.

**Comment by rafeememon** [comment]
> I am hiding the element using visibility: hidden

I'm not positive, but I think browsers don't actually give focus to elements that have `visibility: hidden`, which is probably why the escape key isn't doing anything.

> we are using this component in an application that needs to send some information to the server as soon as the input element is clicked on, and then once again when the calendar popup is closed

Can you use the `onFocus` and `onBlur` props for this instead?

> I need to know which element on the screen received the date change. This is because we have several date pickers on the screen, each with unique information assigned to them by the server.

Without knowing much about your setup it sounds like this can be worked around by having different callbacks for each datepicker.

**Comment by fmadden** [comment]
The funny thing about using onBlur, is that if I assign an onBlur event, even if the function does nothing at all, it causes the calendar popup to close when clicking on the arrows to move forward or back a month.  The month advance buttons in the calendar close the calendar when I have an onBlur event, whether it's empty or not.

**Comment by rafeememon** [comment]
Ah yeah, I think there were issues with the onFocus/onBlur callbacks many versions ago; the code surrounding those props has since been completely refactored.  I would highly recommend upgrading if possible because there have been numerous other bug fixes as well, and unfortunately we can't support old versions.  If you're stuck with React 0.13, maybe you can work something out with a combination of `onFocus` and `onChange`?
