### ISSUE TITLE
change input's date format

### ISSUE THREAD

**Issue by gasipari** [Hacker0x01/react-datepicker#373]
Hello. It looks like refs.input.props.dateFormat is readonly. How can I change the default "YYYY-MM-DD" format to something different ?

**Comment by rafeememon** [comment]
Hey @gasipari, you can use the `dateFormat` prop for this.  Unfortunately it looks like that prop is missing from the docs.

**Comment by gasipari** [comment]
Thanks @rafeememon. It works!
