### ISSUE TITLE
onChange is passed the initial date instead of the selected date

### ISSUE THREAD

**Issue by pirate** [Hacker0x01/react-datepicker#374]
For some reason I'm unable to get `<DatePicker/>` to work, even in the simplest possible page with no bells and whistles.  Any time I select a date, the `onChange` function is passed the initial `selected` date instead of the date I pick on the calendar.   Also for some reason the Today button is not shown, event though I'm setting the `showTodayButton` property.

```javascript
import {default as DatePicker} from 'react-datepicker'
import {default as moment} from 'moment'

const from_date = moment('2015-03-01')
const to_date = moment('2015-03-15')

ReactDOM.render(
        <DatePicker selected={from_date} startDate={from_date} endDate={to_date} onChange={(date) => console.log('SET TO', date._i)} isClearable={true} placeholderText="From date" showTodayButton showYearDropdown/>,
        document.getElementsByTagName('body')[0],
    )

```

Console output when I click `2015-03-03` in the date picker:
```javascript
SET TO 2015-03-01
```

<img width="312" alt="screen shot 2016-02-25 at 1 47 00 pm" src="https://cloud.githubusercontent.com/assets/511499/13335550/816e5fea-dbc6-11e5-82a1-cb1c49d14f3c.PNG">

When I check the state of the `<DatePicker/>` component using the React devtools, I notice it has no `maybeDate` set, could that be an indiction of some deeper problem?

**Comment by rafeememon** [comment]
What version of the datepicker are you using?

**Comment by pirate** [comment]
0.23.2, also tried 0.23.1 with no luck

**Comment by rafeememon** [comment]
Just tried this out -- `_i` is an internal field of moment objects that you shouldn't be using here (probably i for initial or internal); logging `.toISOString()` gives the correct result.
