### ISSUE TITLE
2 Dates selected when selecting a day and changing months

### ISSUE THREAD

**Issue by Jonohas** [Hacker0x01/react-datepicker#3743]
**Describe the bug**
When you select a date that is available in the next or previous month you will get 2 selected dates when changing months.

**To Reproduce**
1. Go to September 2022
2. Select third of September
3. Navigate to the august month
4. See that 2 dates are highlighted

**Expected behavior**
The highlighted date should only be that specific day

**Screenshots**
![image](https://user-images.githubusercontent.com/72028327/187384856-51f9f355-d044-4a96-893d-dc1fe459dc20.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Brave
- Version 1.42.97

**Additional context**
It only seems to be a visual bug.

**Comment by tarang7299** [comment]
I'm also facing the same. Can anyone help??

**Comment by tarang7299** [comment]
add this CSS to your project, it worked for me

.react-datepicker__day--keyboard-selected {
  background-color: inherit !important;
  color: #000 !important;
}

**Comment by Muhiq146** [comment]
.react-datepicker__day--keyboard-selected {
background-color: inherit !important;
color: #000 !important;
}

This CSS works but it also removes the highlight from every month.

**Comment by luddens** [comment]
Yeah, it's just a CSS issue where the color of keyboard-selected was too close to normal selected. I made a CSS change that makes it lighter for keyboard selected, so this issue could be closed.

**Comment by Muhiq146** [comment]
In the previous solution, the highlight doesn't work on today's date.

A new solution to fix this issue also.

```
.react-datepicker__day--keyboard-selected {
  background-color: inherit !important;
  color: #000 !important;
}

.react-datepicker__day--keyboard-selected.react-datepicker__day--today {
  background-color: #216ba5 !important;
  color: #fff !important
}
```
