### ISSUE TITLE
How to properly visualize hours on input field

### ISSUE THREAD

**Issue by justoverclockl** [Hacker0x01/react-datepicker#3752]
![Immagine 2022-09-09 125103](https://user-images.githubusercontent.com/79002016/189334316-cff52a0f-5307-43f2-b22d-f193f1380059.png)

i have this issue, the time is properly formatted but the value showed is not in 24h format...

how can i solve this?

**Comment by shreekeshmurkar** [comment]
Try providing `dateFormat` attribute with value as "MM/dd/yyyy HH:mm a" to `DatePicker`

**Comment by justoverclockl** [comment]
@shreekeshmurkar this add PM but is not 24h (it would be better to see  e.g. 14:45

**Comment by shreekeshmurkar** [comment]
@justoverclockl I have tried providing value to `dateFormat` along with `timeFormat` and Got following `DatePicker`.

![image](https://user-images.githubusercontent.com/36602524/190862962-99e04742-507b-48e5-b737-9cb5937f3f5c.png)

Is this you want ?

**Comment by justoverclockl** [comment]
damn, is HH not hh.....thanks! i figured it out now :D
