### ISSUE TITLE
Not working “select time only” picker

### ISSUE THREAD

**Issue by ktpi2000** [Hacker0x01/react-datepicker#3759]
**Describe the bug**
When entering any time in the input field, “RangeError: Invalid time value” is displayed and the field disappears.

**To Reproduce**

https://reactdatepicker.com/#example-select-time-only

The following video explains how to reproduce the procedure

https://user-images.githubusercontent.com/30472855/190152164-9662e3be-417d-4e90-877e-e518750f94d7.mov

**Expected behavior**

- The field should be visible for any input.
- no error displayed

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome 105

**Comment by luddens** [comment]
I replicated this on Windows 10(x64) and Firefox 105.01 (x64) by removing the value manually with backspace, like you did. I got the same error and the page crashed.

**Comment by luddens** [comment]
Error only happens when you have the showTimeSelectOnly applied. It won't happen on the Select Time example above.

**Comment by luddens** [comment]
How do I set up debugging for this project?

The error is happening after format is called from here: 

https://ibb.co/80h9qFb
https://ibb.co/5BJXGKK
https://ibb.co/jTHrqBV

time.jsx tries to interpolate the time intervals into the drop down list and when you input an invalid date it gets passed down to the format function in the first pic where an error is thrown.

**Comment by luddens** [comment]
If you input letters in Select Time it doesn't cause the error like it does with Select Time Only. Weird.

**Comment by luddens** [comment]
Okay. At the end of handlechange in index.jsx if you insert `    if (
      this.props.showTimeSelectOnly &&
      !isSameDay(date, this.props.selected)
    ) {
      if(date == null){
        date = set(this.props.selected, {
          hours: getHours(this.props.selected),
          minutes: getMinutes(this.props.selected),
          seconds: getSeconds(this.props.selected),
        });
      } else {
        date = set(this.props.selected, {
          hours: getHours(date),
          minutes: getMinutes(date),
          seconds: getSeconds(date),
        });
      }`

It should fix the issue.
