### ISSUE TITLE
Screen reader is staying silent on activating 'Next month' & 'previous month' buttons.

### ISSUE THREAD

**Issue by msftedad** [Hacker0x01/react-datepicker#3766]
**Describe the bug**
Screen reader is not announcing any information on activating 'Next month' & 'previous month' buttons of 'Date picker' dialog of 'Birthday', 'enroll date' & graduate date' edit fields.

**To Reproduce**
1. Open the above mentioned 'URL' in 'Microsoft Edge' & login with valid credentials.
2. 'Intern support' Home page will get open.
3. Navigate to 'Candidate' link via tab key & activate it using enter.
4. 'Candidates' detail page will get open.
5. navigate to 'New candidate' link via tab key & activate it using enter.
6. A page with 'Form' fields to create a candidate will get open.
7. Turn on the narrator using 'Ctrl+Windows+Enter' keys.
8. Navigate to the 'Next' & 'Previous' buttons present in 'Date picker' dialog of 'Birthday', 'enroll date' & graduate date' edit fields via tab key & activate it.
9. Observe the issue.

**Actual behavior**
Screen reader is not narrating anything on activating the 'next month' & 'Previous' month buttons.

**Expected behavior**
Screen reader should narrate name of the respective month, which appears upon activating 'next month' & 'Previous' month buttons.

**Screenshots**

**Desktop (please complete the following information):**
OS: Windows 11 Version: 21H2 (OS Build 22000.856)
Browser: Microsoft Edge Version 105.0.1343.42 (Official build) (64-bit)
URL: [https://internsupport.microsoft.com/](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2finternsupport.microsoft.com%2f&data=05%7c01%7cv-knarang%40microsoft.com%7cf76091e47ae04f67a01208da90094e27%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637980666901980033%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=R1BmtgD%2f2S7RZRcKY6DbVJrEnckvGhdnsVy5XuBrbTQ%3D&reserved=0)
Screen Reader: Narrator

**Smartphone (please complete the following information):**

**Additional context**
Similar issue repro, as screen reader is only narrating 'page title' information on selecting any date.

**Comment by martijnrusschen** [comment]
Fixed by https://github.com/Hacker0x01/react-datepicker/pull/3817
