### ISSUE TITLE
openToDate causes month shifting

### ISSUE THREAD

**Issue by Vitallek** [Hacker0x01/react-datepicker#3779]
If you have provided DatePicker (it should display 3 month, current month at the last place)
```javaScript
<ReactDatePicker
  focusSelectedMonth={false}
  selectsRange
  inline
  monthsShown={3}
  showYearDropdown
  locale={ru}
  disabledKeyboardNavigation
  dateFormat={"dd/MM/yyyy"}
  onChange={(dates) => handleChangeDate(dates, setDateRange)}
  className={"datepicker-here form-control"}
  maxDate={today}
  openToDate={today - MONTH_UNIX * 2}
  startDate={dateRange.startDate}
  endDate={dateRange.endDate}
/>
```
And you try to click on selected day (if only one is selected) or the first of selected days (if many selected), all blocks would be shifted (in my case - 2 shifts)

**Expected behavior**
I expected return of date of clicked day

**Screenshots**
Before click:
![before_datepicker](https://user-images.githubusercontent.com/63740234/192596522-9c39fc92-7b0d-403f-b779-dfde5e89d45d.png)
After click:
![after datepicker](https://user-images.githubusercontent.com/63740234/192596516-0d280c4d-d2ad-48d0-a813-9869005a66ae.png)

**System**
- OS: [Win 10]
- Browser [Edge]
- Version [105.0.1343.50]

**Comment by yuki0410-dev** [comment]
I am also having the same problem.
I attach the minimal code that reproduces.
https://codesandbox.io/s/loving-goldwasser-qbb4z0?file=/src/App.tsx
