### ISSUE TITLE
Typed or pasted invalid dates are not reset to previous value on blur

### ISSUE THREAD

**Issue by pledominykas** [Hacker0x01/react-datepicker#3792]
Date picker allows to type in any string into the input and does not reset the input value after blur.

1. Select a date in the date picker
2. Click on the input component
3. Delete the date with keyboard
4. Type in any string
5. Focus on any other element in the page

**Expected behavior**
The input value gets reset to the previously selected date

**Screenshots**
![image](https://user-images.githubusercontent.com/67858373/195082786-98589cef-d179-4f94-8216-981c016ff619.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 105.0.5195.127

**Comment by jpierson-at-riis** [comment]
Seems to contradict the suggested and reported behavior described in https://github.com/Hacker0x01/react-datepicker/issues/3789.

**Comment by pledominykas** [comment]
Thanks, will close this
