### ISSUE TITLE
yearsShown prop needed

### ISSUE THREAD

**Issue by nandita1** [Hacker0x01/react-datepicker#3827]
I was working on a month range picker and I wanted to show two years side by side. We have a `monthsShown` prop for date range picker but I wanted a similar prop for a month range picker too.

**Comment by Hvesyr** [comment]
Bump

**Comment by Dahmon** [comment]
I'd love this also!

**Comment by yuki0410-dev** [comment]
In v6.4.0 and later, it works by setting `monthsShown={2}`.
https://github.com/Hacker0x01/react-datepicker/pull/4603

( cc. @martijnrusschen )
