### ISSUE TITLE
Migration to FloatingUI

### ISSUE THREAD

**Issue by jakubpodolski** [Hacker0x01/react-datepicker#3842]
According to this discussion, [`popperjs/core` has been rebranded as FlotingUI](https://github.com/floating-ui/floating-ui/discussions/1425). The previous version will be kept in a low maintenance mode, as the new library `@floating-ui/popper` takes its place. 

Are there any plans to migrate internal mechanisms so that they utilize this new library?

**Comment by Xiphe** [comment]
Agree that it would be awesome if `react-datepicker` would migrate to floating-ui. 

In our design system we're already using floating-ui for a lot of other tasks and it would be awesome if we wouldn't load multiple positioning libraries at the same time.

I can start working on a PR for this given there's interest from the maintainers.
