### ISSUE TITLE
Custom format of startDate date. 

### ISSUE THREAD

**Issue by Yawan-1** [Hacker0x01/react-datepicker#3873]
**Is your feature request related to a problem? Please describe.**
Custom date format to console.log is not available.
When I `console.log(startDate)` then it is printing 

> Wed Feb 19 2020 00:00:00 GMT+0530

But How can I get it like `02/19/2020` ?

I didn't find this in readme.

And It doesn't work with `dateFormat` prop in **DatePicker**.

`format(startDate, "dd-MM-yyyy")` also only works in `inline JSX`

Then I thought of trimming the other parts of the string and convert it in numerics, But that would be much more filtering.

**Comment by coucoseth** [comment]
what is the solution?
