### ISSUE TITLE
month picker keyboard selected class names issue and update solution

### ISSUE THREAD

**Issue by sanghogu** [Hacker0x01/react-datepicker#3876]
**Describe the bug**
disabledKeyboardNavigation props in month picker doesn't work

**Expected behavior**
css and side event issues with classname

**Additional context**
Solution Modify 
line 321 of src/month.jsx as follows: !this.props.disabledKeyboardNavigation && utils.getMonth(preSelection) === m,

**Comment by Hvesyr** [comment]
Having the same issue. 
Anyone working on this project still?

**Comment by sanghogu** [comment]
Perfect

**Comment by yuki0410-dev** [comment]
Is there still a problem with this issue?
The fix appears to be complete.
(cc. @martijnrusschen )
