### ISSUE TITLE
Add prop to disable autocomplete

### ISSUE THREAD

**Issue by dtrodger** [Hacker0x01/react-datepicker#3899]
The form input saves a history of previous selections which overlays the calendar. It would be helpful is there was a prop that set autocomplete="off" on the input.
<img width="301" alt="Screen Shot 2023-01-16 at 4 51 34 PM" src="https://user-images.githubusercontent.com/16841791/212776871-3053dea0-c749-401b-beb6-ffba860f6a1a.png">

**Comment by itsaalexk** [comment]
This seems an easy fix! can you assign this to me so I can start working on it?

**Comment by betatester07** [comment]
looks like it is already implemented. See [source code](https://github.com/Hacker0x01/react-datepicker/blob/e8ec42f58ebf3b4e0be5c5f66ab6e56ca3a0ee43/src/index.jsx#L140).

Also see issue #3440.

**Comment by yuki0410-dev** [comment]
This issue seems to have already been resolved.
If it seems to be OK, I would appreciate it if you could CLOSE it.
( cc. @martijnrusschen  )
