### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by jcubic** [Hacker0x01/react-datepicker#3907]
I would like to fix error: #1565 but is this project even maintained? Will PR be merged if I fix this annoying error that is in the library for 4 years?

**Comment by SeanDonnellanJH** [comment]
seriously +1
How do I close the datepicker popper when using the Tab key? I tab to the next element (or prev) on the page and I just want the popper to close when focus shifts out of the popper but I can't find a solution. I believe the onBlur function just doesn't work. No matter what I try on the page, `onBlur={() => console.log('hello')} ` does nothing

**Comment by jcubic** [comment]
If no one cares about the project anymore, maybe someone should create a fork. Unfortunately, I don't have the capacity to do this myself. I wanted to create React Open Source project, but this one has way too many users for me alone to handle everything. But maybe if more people will join we will be able to create a better react date picker.

If anyone is interested in forking and maintaining, reading issues, fixing bugs, and doing code reviews and other things, then leave a comment below, so we can find out.

I can do the fork and create an organization, maybe just a generic `@react-forks` or something, just to not exclude other similar projects that may be needed to fork in the future. But not that I will not do everything myself, it's way too much work for one person, and I'm already maintainer of few projects.

**Comment by jcubic** [comment]
damn `react-forks` is taken.

**Comment by martijnrusschen** [comment]
Hi all - This repo is still maintained, but I've been a bit busy recently to keep this running on my own. I could use some help, but happy to keep this alive and spend some extra time on it. There's a lot of activity happening here, which is great but running this next to a full-time day job is challenging.

**Comment by jcubic** [comment]
You should seek more maintainers there are way too many issues open and PR hanging.
I'm afraid that will also not be able to help. Also, it's that interesting to me to spend my free time on it. I have other projects and need this one only for the job where I will only be til the end of February.

Maybe you should update the README with info that you seek maintainers. I'm not that good at creating communities myself. I mostly do solo Open Source projects.

But I'm part of one project where the original author left, his project is a great example because he automated a lot of things. Automatic build, tests, and releases. There are issues with this setup, but I think that automating as much as possible is a way to go.

**Comment by martijnrusschen** [comment]
Released new versions today. Enjoy!
