### ISSUE TITLE
formatWeekDay is returning a function instead of a string after 4.9.0

### ISSUE THREAD

**Issue by rodrigoeidelvein** [Hacker0x01/react-datepicker#3918]
**Describe the bug**
After `4.9.0`, the prop `formatWeekDay` is always returning a function instead of a string due to the changes of #3582 

Even on `@types/react-datepicker` it indicates that the prop will return a string, but the logic of the changes makes it impossible to reach the old code, it always returns a function, or is there a scenario where you can pass something other than a function to `formatWeekDay`?

**To Reproduce**

1. Use the prop `formatWeekDay` in a `DatePicker` instance:
```
() => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker 
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      formatWeekDay={date => date.substring(0, 3)}
    />
  );
};
```

**Expected behavior**
It should return a string from `formatWeekDay`

**Screenshots**
<img width="570" alt="image" src="https://user-images.githubusercontent.com/12849476/216443554-c273cb79-0594-471b-8907-bb00314fb215.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version 109

**Comment by salguerooo** [comment]
I'm also seeing the same behavior, current fix for now was to revert the version back to 4.8.0

**Comment by martijnrusschen** [comment]
Thanks for reporting. That's not intentional. @YuCJ Any thoughts on how to avoid making a breaking change? If we can't avoid that, we'll need to revert this change to avoid making breaking changes without a major version upgrade.

**Comment by YuCJ** [comment]
> Thanks for reporting. That's not intentional. @YuCJ Any thoughts on how to avoid making a breaking change? If we can't avoid that, we'll need to revert this change to avoid making breaking changes without a major version upgrade.

I agree that we need to revert the change for v4.9, too. If we want to change the value of the first parameter which is given to `formatWeekDay` (the reason is in the description of #3582), it will need a major version bump.

**Comment by davebrewer** [comment]
Experiencing same issue. Reverted using formatWeekDay prop and waiting on a fix until reintroducing.

**Comment by SamuelTorga** [comment]
Experiencing the same issue.  Used the param as string as a work around.

**Comment by maycon8609** [comment]
@types/react-datepicker from version 4.10.0 (I believe) already fixed this problem.

- "react-datepicker": "^4.9.0"
- "@types/react-datepicker": "^4.10.0"

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64392
https://www.npmjs.com/package/@types/react-datepicker

**Comment by maranomynet** [comment]
@robbchar the bomb went off for me last week.

It's just amazing how this remains unfixed for almost 7 weeks now.

**Comment by martijnrusschen** [comment]
Released a new version to revert the breaking changes

**Comment by targumon** [comment]
> `@types/react-datepicker` still has previous type of formatWeekDay :(

@ykostiuk-GD it's a separate repo. You can either force that package to version 4.8.0 (which is before both the breaking change and the "rollback"), or better yet - make a PR there. I think this is the change that needs to be reverted: DefinitelyTyped/DefinitelyTyped/pull/64392
