### ISSUE TITLE
Typing date in a different format like `Feb 28, 2023` doesn't work anymore

### ISSUE THREAD

**Issue by darryltec** [Hacker0x01/react-datepicker#3921]
**Describe the bug**
On versions 4.8 and below, you used to be able to type a date in words (for example: `Feb 28, 2023`) on the input and it'll automatically select the date on the picker and format the date on the input. The latest version doesn't allow that anymore.

**To Reproduce**

1. Go to https://reactdatepicker.com/
2. Type a new date on the input in a different format like `Feb 28, 2023` or `2023-02-28`
  - The reason why this is important, especially the month being `MMM` is users would type what's easiest for them and since it's easier to remember Aug than 08, people would type Aug or August.

**Expected behavior**
- It should select Feb 28, 2023 on the date picker

**Screenshots**

Note: This is a stylized version of your component.

v4.10.0 - Broken

![Feb-03-2023 07-45-50](https://user-images.githubusercontent.com/15986172/216632450-441bf629-1a60-4576-b88e-df42198be21c.gif)

v4.8.0 - Working
![Feb-03-2023 07-45-03](https://user-images.githubusercontent.com/15986172/216632292-ce3a7c2f-74f0-4519-8e05-8f3f212239c1.gif)

**Desktop (please complete the following information):**

- OS: Mac OS Ventura
- Browser: Chrome
- Version: Version 109.0.5414.119 (Official Build) (x86_64)

**Additional context**

**Comment by darryltec** [comment]
From what we can tell, this might've been removed by this change? https://github.com/Hacker0x01/react-datepicker/pull/3903

**Comment by sallesma** [comment]
I have the same issue with a datepicker configured for time only.

Some users are used to typing a number and let the picker extrapolate the full time. Eg. typing '7' to get '07:00'.

(Maybe it was not an intended feature of the datepicker though)

**Comment by Ugoku** [comment]
We experienced this problem in our test suite, which tests the date input by entering an ISO 8601 date (YYYY-MM-DD). We use DD-MM-YYYY for our calendar, so we "fixed" it by changing the way our test suite enters the date. I would still expect an ISO 8601 date to work though

**Comment by Hans-ABC** [comment]
> From what we can tell, this might've been removed by this change? #3903

Unclear if this is the exact issue, but definitely the change occurs in 4.9.0. The issue mentioned is included in that release.

My issue is that typing "30 June 2019" no longer works. Now need exact "30 Jun 2019" (no "e" for June) despite user using full name of the month. Arguably "user needs to type less", but user might copy paste value which a flexible parsing would be much better.

**Comment by darryltec** [comment]
After deciphering what happened on that PR. We found a workaround (or probably the intended use now?). Basically, pass in the format you want it to support. Still wont be as flexible as before but it'll do.

```jsx
<ReactDatePicker
  ...
  dateFormat={["P", "PP", "PPP", "MMM dd yyyy", "MMMM dd yyyy"]}
/>
```

**Comment by Hans-ABC** [comment]
So `dateFormat` is used for both presentation and parsing, but for presentation it only uses the first element of the array (at least from experimenting). That implicit "presentation uses first element of the array" sounds tricky.

**Comment by ckarras11** [comment]
This does not seem like it was something that should have been included in a minor version bump.  This functionally changes the way the input works and now only parses one date format by default and anyone using `dateFormat` currently  to have a user friendly display, keyboard users are no longer able to type in shorter dates that don't match the format exactly.  This appears to have been merged without review by someone making their first PR to this package.  This is a terrible user experience and if this is the intended new path forward it should instead be a **major** version bump with a breaking change section in the CHANGELOG.

**Comment by ckarras11** [comment]
Well done thanks!

**Comment by MirKml** [comment]
But problem with time only formats is back https://github.com/Hacker0x01/react-datepicker/issues/3933
I was little bit better with new 'fixed' date time parsing.
Now when I type '2' for eg. 2:00 time, it crashes as earlier.
