### ISSUE TITLE
[Accessibility] Focus position in Month Picker

### ISSUE THREAD

**Issue by GalGrigoryeva** [Hacker0x01/react-datepicker#3927]
**Describe the bug**
When you try to select a month with keyboard in month picker with two or four columns, focus seems to go to the place like it is still three columns.

**To Reproduce**

1. Go to https://reactdatepicker.com/#example-month-picker-four-columns-layout
2. Open month picker
3. Press Tab
4. Press Arrow Down

**Expected behavior**
When I click Arrow Down focus goes to month which is right below.

**Screenshots**
![focus-position](https://user-images.githubusercontent.com/19471924/217922572-58cc0f12-711a-4701-a40e-9e84a7121dc6.gif)

**Comment by KevinFabre-ods** [comment]
Happens also with the `monthsTwoColumns` prop
