### ISSUE TITLE
showIcon documented, but not present in props

### ISSUE THREAD

**Issue by Aziaev** [Hacker0x01/react-datepicker#3928]
**Describe the bug**
I found that showIcon prop is not working in version 4.10.0. I see this prop on [main website](https://hacker0x01.github.io/react-datepicker), I see it on [Github](https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md), but I can't use it.
Also showIcon prop is not presented in @types/react-datepicker

**To Reproduce**
1. install react-datepicker
2. Use it with prop showIcon

**Demo**
https://codepen.io/aziaev/pen/vYaoKpv

**Expected behavior**
Icon is presented on screen and svg dom element is inside of input container. Works on main website:
![image](https://user-images.githubusercontent.com/19153508/218188784-4a8584b3-7f2d-4043-8ada-7cc58f4f5249.png)

**Screenshots**
Prop does not exists, and it's not presented in dom
![image](https://user-images.githubusercontent.com/19153508/218188906-4c442f91-b367-4205-adf0-d55e9dd4f00b.png)
![image](https://user-images.githubusercontent.com/19153508/218188943-8df1ed1c-8106-4c52-a991-3b9a9bc4c9cb.png)

- OS: Windows 10
- Chrome 

**Additional context**

**Comment by Aziaev** [comment]
Looks like that showIcon prop removed and related classname doesn't added

**Comment by Entropiks** [comment]
experiencing same thing

**Comment by aaron-thompson** [comment]
I am seeing the same

**Comment by mattbeaudry** [comment]
I noticed that providing `type` prop of 'date' 'datetime' or 'time' will display the proper icon

**Comment by x7Michi10x** [comment]
> I noticed that providing `type` prop of 'date' 'datetime' or 'time' will display the proper icon
It is due to yersterdays update but still buggy. Only visible for me with the following css:
`.react-datepicker__input-container .react-datepicker__calendar-icon {
    padding: unset !important;
    top: 10px;
    left: 7px;
}
`

**Comment by flaviobvds** [comment]
I have the same problem

**Comment by epiera** [comment]
Same here.

**Comment by TobiasKC** [comment]
> datepicker__calendar

Worked for me, need to set showIcon = true and add this to your CSS. Appeared with some padding issues on mine, so set the padding left to 30px with: .react-datepicker__view-calendar-icon input

**Comment by yuki0410-dev** [comment]
Since showIcon now resides in @types/react-datepicker, the problem appears to be resolved.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6918081f66a51df9eab940d9b690d627467c4401/types/react-datepicker/index.d.ts#L181

( cc. @martijnrusschen )
