### ISSUE TITLE
onMonthChange doesn't fire when selecting month in MonthYearPicker

### ISSUE THREAD

**Issue by symphony** [Hacker0x01/react-datepicker#3934]
`onMonthChange` is fired when I navigate via the prev/next buttons in the header in Date view (using `decreaseMonth` and `increaseMonth` methods, however the event isn't detected when manually selecting a month in the `MonthYearPicker` calendar. 

It is also not detected when clicking on an `outside-month` in the normal date view.

_[MonthYearPicker]_
![image](https://user-images.githubusercontent.com/24639525/218572015-46d8c2be-f46d-4777-b904-1daa9c46ee2a.png)

_[Outside-Month dates]_
![image](https://user-images.githubusercontent.com/24639525/218577172-eac43c39-0016-4c23-878e-48c6b5e40ce2.png)

How I'm handling the view logic 

```jsx
// state
    const [viewType, setViewType] = useState<DatePickerViewType>("date");
    const [selectedDate, setSelectedDate] = useState<Date>(new Date());
```

```jsx
// navigation handler
      setViewType((prev) => prev === "year" ? "month" : "date");
```

```jsx
// onChange handler
     if (viewType === "date") {
       setSelectedDate(clickedDate)
     }
```

```jsx
// component
<ReactDatePicker
  showYearPicker={viewType === "year"}
  showMonthYearPicker={viewType === "month"}
  onCalendarClose={() => { setViewType("date"); }}
  selectedDate={selectedDate}
  onChange={onChange}
  // ...
/>
```

**Comment by symphony** [comment]
@jees47 Yes. I'm storing the selected date as state, and manually keeping track of the highlighted date as a ref, and then comparing it when I click a new one and updating accordingly.

```tsx
const [selectedDate, setSelectedDate] = useState<Date>((value && new Date(value)) || null);
const dateInView = useRef<Date>(selectedDate ?? new Date());

...
 
const onChangeHandler = (date: Date, event: FormEvent<HTMLInputElement>) => {
  if (dateInView.current.getMonth() !== date.getMonth()) {
    dateInView.current = date;
    return;
  }

  dateInView.current = date;
  setSelectedDate(date);
});

...

return (
  <Styled.Container tabIndex={-1} ref={forwardedRef}>
    <ReactDatePickerCompat
      selected={selectedDate}
      onChange={onChangeHandler}
      onMonthChange={(date: Date) => { dateInView.current = date }}
      {...someOtherProps}
    >
    </ReactDatePickerCompat>
  </Styled.Container>
);
```

**Comment by gentrit-humolli** [comment]
I see that this issue is marked as completed. However, I'm experiencing the issue when clicking on the "outside-month-date" is not firing the onMonthChange callback. 

Does the MUI team actually have a plan on fixing this, as because this 'hacky' workaround is not something I'm very fond of?
