### ISSUE TITLE
onChange(Raw) gets onClick event?

### ISSUE THREAD

**Issue by sKopheK** [Hacker0x01/react-datepicker#3949]
**Describe the bug**
instead of expected change event at input field passed to onChangeRaw callback, I'm receiving some weird onClick syntetic thingy

**To Reproduce**
```
<ReactDatePicker
    onChangeRaw={props.onChange}
    onChange={() => { }}
/>
```

**Expected behavior**
get original event what as you'd subscribe to change of input field itself

**Screenshots**
![imagen](https://user-images.githubusercontent.com/5802917/221614136-9f4e3f84-2f76-4551-a0c7-81e0a107e457.png)

**Desktop (please complete the following information):**

- OS: Win11
- Browser chrome
- Version latest

**Comment by sKopheK** [comment]
also, not part of this repo, but @types/react-datepicker - still worth notificing:  `onChangeRaw?(event: React.FocusEvent<HTMLInputElement>): void;`

**Comment by sKopheK** [comment]
actually same weird event is given on `onChange={(date, event) => ...}`

**Comment by yuki0410-dev** [comment]
@sKopheK
onChangeRaw is called in two places in index.jsx.

https://github.com/Hacker0x01/react-datepicker/blob/5261cbd15d8eff849cf76d4865126ce2b4ccb973/src/index.jsx#L542
https://github.com/Hacker0x01/react-datepicker/blob/5261cbd15d8eff849cf76d4865126ce2b4ccb973/src/index.jsx#L586

From the capture, it is assumed that it is called via handleSelect. (Judging from target and type).

There didn't seem to be anything odd about it as a reactEvent.
If you need nativeEvent, go to e.nativeEvent.
https://stackoverflow.com/a/70426848

**Comment by yuki0410-dev** [comment]
( cc: @martijnrusschen )
