### ISSUE TITLE
Support for time as well as date

### ISSUE THREAD

**Issue by piotrblasiak** [Hacker0x01/react-datepicker#395]
I can not see that there is any support for time picking, shouldn´t that be part of this component as well?

**Comment by cubbuk** [comment]
+1

**Comment by hedigerf** [comment]
I would appreciate that feature too :)

**Comment by arahansen** [comment]
Hey, this is something I would actually like to tackle. As far as design is concerned, what would everyone find more useful?

A timepicker that's available as a separate input element from the existing datepicker?

Or somehow integrate the timepicker into the datepicker popup?

**Comment by piotrblasiak** [comment]
Great to hear arahansen!

I think it makes more sense to have it in the same component and make it possible to specify the precision. If you then wanted to make one component for just the date and one for just the time you could do that, but also one for both if you wanted that.

**Comment by dmnd** [comment]
@arahansen did you make any progress on this?

**Comment by zsherman** [comment]
@arahansen https://projects.skratchdot.com/react-bootstrap-daterangepicker/ does a nice job with that imo.

**Comment by ktalebian** [comment]
What's the status of this?

**Comment by stevenleeg** [comment]
I'd love to see this as well. Is this a feature that's being worked on?

**Comment by adamraudonis** [comment]
I would also love to see this feature

**Comment by paerhaty** [comment]
+1

**Comment by jbbr** [comment]
I'm still interested

**Comment by jbbr** [comment]
Looks like this package does support time picking now (e.g https://reactdatepicker.com/#example-select-time )
