### ISSUE TITLE
Internet Explorer 9 support

### ISSUE THREAD

**Issue by vguzev** [Hacker0x01/react-datepicker#398]
Hi!

We're currently looking for replacement for our DatePicker component and your project looks great! 
Unfortunately we still have requirement of supporting Internet Explorer 9, because a lot of customers are still using it in banking sphere. Do you support IE9? 
Demo page https://hacker0x01.github.io/react-datepicker/ is not working in IE9. It gives error:
SCRIPT1028: Expected identifier, string or number 
bundle.js, line 91 character 80

P.S. You can get Virtual Machine with IE9 for free from Microsoft's site: https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/

**Comment by rafeememon** [comment]
After some googling it looks like that error is from how we compile the demo site (appears to be the same  issue described [here](http://jamesknelson.com/using-es6-in-the-browser-with-babel-6-and-webpack/#comment-4187)).  Re: IE9; the best way to find out is to give it a try, and we'd be happy to accept any PRs to make it compatible.

**Comment by Pizdetss** [comment]
Just FYI

The datepicker also has a dependency called 'react-onclickoutside' which doesn't support IE9 and never will. So unless they change this dependency your datepicker will not function correclty in IE9.

**Comment by rafeememon** [comment]
Thanks for digging into that @Pizdetss.  The reasoning for this is detailed on [this issue](https://github.com/Pomax/react-onclickoutside/issues/60) (perfectly valid IMO).  In another issue, [this comment](https://github.com/Pomax/react-onclickoutside/pull/14#issuecomment-103211295) describes a possible workaround, but I haven't tried it out.

**Comment by vguzev** [comment]
@Pizdetss @rafeememon We've already created a clone of react-onclickoutside with IE9 support: https://www.npmjs.com/package/react-onclickoutside-ie9

**Comment by vguzev** [comment]
Please, see PR for this issue: https://github.com/Hacker0x01/react-datepicker/pull/406

**Comment by rafeememon** [comment]
@vguzev, unfortunately I'm skeptical of including dependencies on forks of repositories because of the risk of the forks being abandoned, and I'd like to try to stay with the main plugin.  I'm also now skeptical of supporting IE9 for the reasons mentioned in the main plugin.  Can you try the workaround I mentioned in https://github.com/Hacker0x01/react-datepicker/issues/398#issuecomment-196706326 ?

**Comment by rafeememon** [comment]
Also, from the `react-onclickoutside` readme:

```
Note that this mixin relies on the .classList property, which is supported by all modern browsers, but not by no longer supported browsers like IE9 or even older. For setups that need to support deprecated browsers, using a classlist-polyfill will be necessary.
```

Please try adding `classlist-polyfill` to your setup to get IE9 working.

**Comment by vguzev** [comment]
OK. Then I suppose you should add info about this `classlist-polyfill` to your Readme page (+ some polyfill for console.* support). And add these polyfills to your demo page as well...

P.S. @Pomax should add `classlist-polyfill` as dependency in `react-onclickoutside`, but for some reasons declines to do that... So, all depending components have to warn their users about this issue... not really productive!

**Comment by rafeememon** [comment]
Added a note about IE9 compatibility in #408

**Comment by Pomax** [comment]
That's because IE9 has not been officially supported by Microsoft for over two months now. Make the web a better place, support supported browsers, not abandoned ones.

**Comment by fritz-c** [comment]
@Pomax I'm no fan of IE9, but I want to note that it is actually still supported... barely. Hence, any business with an internal system that only runs on IE9 is probably on the edge of its seat.

According to the [press release](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support), the IE support is for

> the most current version of Internet Explorer available for a supported operating system

And as Vista extended support lasts until April 11, 2017, and the latest IE on Vista is IE9... we're stuck with it for another year.

**Comment by Pomax** [comment]
Right but *only* Vista SP2, and only *on* Vista SP2. IE9 is *not* supported on any other version of Windows anymore. (They were smart enough to add that stipulation)
