### ISSUE TITLE
Style missing

### ISSUE THREAD

**Issue by alex3o0** [Hacker0x01/react-datepicker#3985]
**The react-datepicker component is rendered without its styles**
I inspect the page, and the css for the datepicker classes is not there

**To Reproduce**
1.- In node 18, I create a new project with create-react-app
2.- I installed the component whit `npm install react-datepicker --save`
3.- I implement it as follows in the App.js:

```
import DatePicker from 'react-datepicker'
import { useState } from 'react'

function App() {
  const [startDate, setStartDate] = useState(new Date())

  return (
    <div className="App">
      <DatePicker selected={startDate} onChange={ date => setStartDate(date) } />
    </div>
  );
}

export default App;
```
4.- I run the project with npm start
5.- The project starts and renders everything but the react-datepicker.css

The app is served from a linux.

The behavior is present in firefox, chrome and edge for linux, mac and windows.

**Comment by jeeveshlodhi** [comment]
`import { useState } from 'react'
import './App.css'
import "react-datepicker/dist/react-datepicker.css";
import DatePicker from 'react-datepicker'

function App() {
 const [startDate, setStartDate] = useState(new Date())

  return (
    <div className="App">
      <DatePicker selected={startDate} onChange={ date => setStartDate(date) } />
    </div>
  );
}

export default App
`

I think you have not included `import "react-datepicker/dist/react-datepicker.css";`

**Comment by jeeveshlodhi** [comment]
Add the CSS file of the library that is, import "react-datepicker/dist/react-datepicker.css"; in your code and it will work. 
I tried it in my project following your rules and included this CSS file, it worked.

**Comment by aziyatali** [comment]
@alex3o0  Close the issue if you problem resolved!

**Comment by donavan-tangible** [comment]
When I try to build production package I got this error: 

TypeError: Cannot read properties of undefined (reading 'e')

**Comment by Kay2dan** [comment]
> Add the CSS file of the library that is, import "react-datepicker/dist/react-datepicker.css"; in your code and it will work. I tried it in my project following your rules and included this CSS file, it worked.

Thank you, this solved it for me. I think its worth mentioning this in the docs as I was confused why the styling is not there.

**Comment by yuki0410-dev** [comment]
The problem appears to have already been resolved.
If there are no other problems, please close the issue.
( cc: @martijnrusschen )
