### ISSUE TITLE
showYearPicker disabled years

### ISSUE THREAD

**Issue by ekiankim92** [Hacker0x01/react-datepicker#3987]
Is there a way I could remove all the disabled years when using showYearPicker? Or just adjust them with the yearItemNumber?

<DatePicker
   minDate={new Date()}
   maxDate={new Date(new Date().getFullYear() + 40, 0)}
   showYearPicke              
   dateFormat={"yyyy"}
/>
I have 2017-2022 years in disabled along with 2064, but I want to remove these disabled years.

**Comment by aziyatali** [comment]
@ekiankim92 
Remove maxDate property from DatePicker and you can select any date.

```
<DatePicker
minDate={new Date()}
showYearPicke
dateFormat={"yyyy"}
/>
```

If you want to remove minDate disabled as well then you can remove that as well.

```
<DatePicker
showYearPicke
dateFormat={"yyyy"}
/>
```

**Comment by ekiankim92** [comment]
@aziyatali 
What if I was to set a specific year range? I wanted to show the year range from this year all the way through 2035. I have set to show the years with the yearItemNumber={6} but when I hit the last year to see the 2035, this will show the disabled 2036 through 2040.

`
<DatePicker
minDate={new Date()}
maxDate={new Date(new Date().getFullYear() + 12, 0)}
showYearPicker
yearItemNumber={6}
dateFormat={"yyyy"}
/>
`

**Comment by aziyatali** [comment]
@ekiankim92  
That's because you choose  yearItemNumber as 6, which means it will show you 6 years per tab.
You can't hide 2036-2040 for above reason. 
What you can do is, either set yearItemNumber to 1, or below code:
```

() => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker
    minDate={new Date()}
    maxDate={new Date(new Date().getFullYear() + 17, 0)}
    showYearPicker
    yearItemNumber={Math.max(6,1)}
    dateFormat={"yyyy"} />
  );
};
```

Please close your issue if resolved.

**Comment by ekiankim92** [comment]
thank you for your assitance!

**Comment by aziyatali** [comment]
@ekiankim92  If one of the above answer your question, please mark as an answered. So, next time someone stuck they can see what to do.

Please refer to this: https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/participating-in-a-discussion
