### ISSUE TITLE
DateInput does not re-render on format change

### ISSUE THREAD

**Issue by gnawjaren** [Hacker0x01/react-datepicker#399]
Hello.
when the locale changes (either moment.js global or via props) or the format props change, the component should re-render with the new format ?

currently that is not the case, the new format only gets picked up after a date change.
the problem is - the state of DateInput keeps the formatted date,
and the format gets only respected on change (not on re-render with same date, but different format).

one solution would be to store the moment in `this.state.maybeDate` and call `this.safeDateFormat(this.state.maybeDate)` in render.

i would be happy to submit a pull request if desired.

**Comment by rafeememon** [comment]
Hey @gnawjaren, good find.  I don't think that can be a solution because `maybeDate` stores the text of the input regardless of whether it's a valid date, and it would wipe out the user's intermediate text.  I'm sure there's another way to do this though.

**Comment by gnawjaren** [comment]
I see, so maybe `componentWillReceiveProps` and setting `maybeDate` there may be an option?

**Comment by rafeememon** [comment]
Fixed by #400
