### ISSUE TITLE
How to change focused inputs border color?

### ISSUE THREAD

**Issue by NurulWahedQalqul** [Hacker0x01/react-datepicker#3990]
This is the datepicker input when not focused:
![image](https://user-images.githubusercontent.com/127097111/230897984-715f9c75-2054-47a4-b956-a898e731d215.png)

And, this is how it looks when it's focused:

![image](https://user-images.githubusercontent.com/127097111/230898144-ae835352-31b7-4922-8038-bc78a7e052ca.png)

How can I change the focused inputs border color?

**Comment by rachit298** [comment]
@NurulWahedQalqul Apply below css property on your input field :-

input:focus {
  border: 2px solid green; //apply color as you wish
  border-radius: 2px;  //this won't affect the border color, you can remove it if your want to.    
  outline:none;  //this will remove border when focused 
}

**Comment by yuki0410-dev** [comment]
The problem appears to have already been resolved.
If there are no other problems, please close the issue.
( cc: @martijnrusschen )
