### ISSUE TITLE
Error with react-dom after build source.

### ISSUE THREAD

**Issue by Nelie-Taylor** [Hacker0x01/react-datepicker#3994]
Hi.
I use 
`"react-datepicker": "^4.11.0",`

 `"react-dom": "^18.2.0",`
 
When i builed. I cannot start with problem: `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object`
and i log it: 
`
{
  CalendarContainer: [Function: Qr],
  default: [Function: r],
  getDefaultLocale: [Function: tr],
  registerLocale: [Function (anonymous)],
  setDefaultLocale: [Function (anonymous)]
}
`
Please help me.
Thank you.

**Comment by Nelie-Taylor** [comment]
![image](https://user-images.githubusercontent.com/12018657/231521350-390df1c2-0550-410d-8173-58ed8ad811e2.png)

**Comment by aziyatali** [comment]
Remove your node-modules and try to install them again.

In app, 

`rm -rf node_modules.
`yarn install or npm install`

**Comment by Nelie-Taylor** [comment]
@aziyatali thank you for replay, it not work for me.

**Comment by kristico12** [comment]
@Nelie-Taylor 
I asked chapgpt and he answered this: 

"The error message “Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object” usually occurs when you are trying to import a component that is not exported correctly. This can happen when you forget to export the component from the file it’s defined in or when you mix up default and named imports12.

You can try to check if the component is exported correctly. If it is, then you can try to import it correctly. If you are using TypeScript with react-datepicker, you can try to use the following import statement:

import DatePicker from 'react-datepicker/dist/react-datepicker';"

and it worked for me

**Comment by mc13an** [comment]
I'm using Remix 2.1.0 and ran across this error as well. What got it working for me was something like this: 

```js
import ReactDatePicker, { type ReactDatePickerProps } from "react-datepicker";

// @ts-ignore
const Picker = ReactDatePicker.default;

export const DatePicker = ({ className, onChange, onBlur, selected }: ReactDatePickerProps) => (
  <Picker
    maxDate={new Date()}
    className={className}
    onChange={onChange}
    onBlur={onBlur}
    selected={selected}
  />
);

```

**Comment by BetoOrozco95** [comment]
> @Nelie-Taylor after a series of trial and error for both running locally and running compiled, this is what worked for me.
> 
> `import ReactDatePicker from "react-datepicker";
> 
> const DatePicker = (ReactDatePicker as unknown as { default: typeof ReactDatePicker }).default ?? ReactDatePicker;`

I had the same problem, with this I was able to solve it, thank you very much!

**Comment by Nelie-Taylor** [comment]
> @Nelie-Taylor after a series of trial and error for both running locally and running compiled, this is what worked for me.
> 
> `import ReactDatePicker from "react-datepicker";
> 
> const DatePicker = (ReactDatePicker as unknown as { default: typeof ReactDatePicker }).default ?? ReactDatePicker;`

thank you so muc.
