### ISSUE TITLE
Input type to DateInput

### ISSUE THREAD

**Issue by edygar** [Hacker0x01/react-datepicker#402]
It would be nice if it was possible to inject type of the `DateInput`, it uses 'text' but type 'date' provides a better experience in smartphone,

**Comment by martijnrusschen** [comment]
Probably best to make `date` the default.

**Comment by rafeememon** [comment]
How does an input or type `date` behave when the browser doesn't support it?  I know the date type is a relatively new thing.

**Comment by edygar** [comment]
it falls back to text type in all browsers.

Em seg, 14 de mar de 2016 às 12:19, Rafee Memon <notifications@github.com>
escreveu:

**Comment by rafeememon** [comment]
@edygar, could you elaborate on how it's a "better experience" for the date type? (sorry, edited after I posted and it's not in the notification email)

**Comment by rafeememon** [comment]
Briefly tried this out, and it looks like it currently won't work.  The native Chrome date picker and handling of the text in the input field conflicts with the DatePicker component's handlers.

**Comment by edygar** [comment]
@rafeememon, so, we can [hide the built in controls with CSS](http://stackoverflow.com/a/12267927) and the value should comply with  [RFC 3339](https://www.w3.org/TR/html-markup/input.date.html#input.date.attrs.value).

But as I was looking deeper into this idea, I found hard to change the format it presents the input to the user, simply there isn't a way to specify the format, so it is up to the browser, which in the fallback versions, presents the wire format (YYYY-MM-DD).

I think we will have to drop this idea.

On my iPhone, the input with type `date` shows the input like this:
[![iPhone](http://i.imgur.com/ungtcEj.png)](http://imgur.com/ungtcEj)

**Comment by rafeememon** [comment]
Sorry that we can't get this fix in for you @edygar.  Maybe we should revisit this when browsers have fully fleshed out the features we'd need to use.

I'm also wondering what that would imply for the future of this component if all browsers give a native picker for `date` types.  Something to keep an eye on

**Comment by edygar** [comment]
For me there's a simple solution, i just need to switch inputs accordingly with the resolution. It is just a shame that HTML5 date input comes so limited.

Anyway, thank you by the support. Good job in this component!

**Comment by rafeememon** [comment]
Hey @edygar -- I think we'll be exposing the `type` of the input as a prop rather than making `date` the default as we discussed here.
