### ISSUE TITLE
showPreviousMonths={true} is not working properly

### ISSUE THREAD

**Issue by gianpierobenvenuto** [Hacker0x01/react-datepicker#4023]
You can see this issue in action on the "Show previous month" example found on the demo website [https://reactdatepicker.com/](https://reactdatepicker.com/)

What happens?

If you have showPreviousMonths={true} and you click any day it will jump to the previous month instead. This also applies to different cases such as implementations with selectsRange={true} and monthsShown={2}.

**Comment by Kenan-Kuzgun** [comment]
Same issue !

**Comment by Kenan-Kuzgun** [comment]
![daterangepicker-issue](https://github.com/Hacker0x01/react-datepicker/assets/116794145/239fd89a-3587-41cb-8d0d-ff9cc9441138)


<DatePicker
        ref={datepickerRef}
        locale="tr"
        dateFormat="dd MMMM yyyy"
        selectsRange={true}
        showPreviousMonths={true}
        monthsShown={2}
        onChange={(update) => {
          setDateRange(update);
        }}
        customInput={<ExampleCustomInput />}
        startDate={startDate}
        endDate={endDate}
        maxDate={maxDate} 
        minDate={minDate} 
        onApply={(start, end) => {
          setStartDate(start);
          setEndDate(end);
        }}
      ></DatePicker>
      
      
     Same issue !

**Comment by Burak-Ozlece** [comment]
same issue too

**Comment by comountainclimber** [comment]
Any update on this? Its super broken

**Comment by Kenan-Kuzgun** [comment]
No, we couldn't fix it.

**Comment by comountainclimber** [comment]
Ok I actually was able to hack my way around this issue with something like the following:

```
const START_OF_LAST_MONTH = startOfMonth(subMonths(new Date(), 1));
const [startDate, setStartDate] = useState(START_OF_LAST_MONTH);
useEffect(
  function clearPreviousMonthStartDate() {
    if (!initialized) {
      setStartDate(null);
      setInitialized(true);
    }
  },
  [startDate, initialized]
);

return (
  <DatePicker
    fixedHeight
    open
    onChange={([start, end]) => {
      setStartDate(start);
      setEndDate(end);
    }}
    monthsShown={2}
    inline
    selectsRange
    startDate={startDate}
    endDate={endDate}
    maxDate={maximumDate}
    minDate={minimumDate}
    renderDayContents={renderCustomDayContents}
    disabledKeyboardNavigation
  />
);

```
This will render the picker with the visual appearance of what `showPreviousMonths` prop provides
