### ISSUE TITLE
Remove tap delay of 300ms for month navigation

### ISSUE THREAD

**Issue by thomasduenser** [Hacker0x01/react-datepicker#403]
It's easy to remove the tap delay for Android devices but it's not possible with CSS for every iOS Version yet.

Is there a way to remove the tap delay? Maybe this plugin would be the solution https://github.com/zilverline/react-tap-event-plugin.

It's not possible to navigate fastly through the month on iOS devices. Any idea is helpful! :)

Thanks for the great work btw!

**Comment by rafeememon** [comment]
It looks like that plugin would do the trick, and judging from the readme it looks like it's possible to use it independently of the datepicker component by calling `injectTapEventPlugin()` in your project code.  Let us know if that doesn't work.

**Comment by thomasduenser** [comment]
Thank you very much for the fast answer!

I think that's not enough, on the month navigation (prev + next) next to the `onClick`, there must be `onTouchTap` like in the Example of the `tap-event-plugin`.

**Comment by thomasduenser** [comment]
I ended up using [fastclick](https://github.com/ftlabs/fastclick) with the help of [this stackoverflow question](http://stackoverflow.com/questions/24335821/can-i-fastclick-reactjs-running-in-cordova). Seems to work fine.

Can be closed, but maybe a solution inside the plugin code would be awesome one day. Keep up the great work!

**Comment by rafeememon** [comment]
Hey @thomasduenser, glad you got it working.  Not sure a solution should be included natively in this plugin as it's a very platform-specific thing for a marginal UI improvement, and there are workarounds like the one you found.  However this could be included in a mobile-specific build, which is something I've been thinking about lately.
