### ISSUE TITLE
Publish lib instead of dist build

### ISSUE THREAD

**Issue by rafeememon** [Hacker0x01/react-datepicker#405]
As pointed out in #404, the dist build isn't the friendliest to those who are using module bundlers (i.e. probably everyone at this point).  Since we officially stopped supporting bower and RoR, we can optimize the build by publishing the `src` cross-compiled into `lib` and **stop publishing a heavy `dist` build**.  Unfortunately this is an API break, but filing this so that we don't forget to make the change before we release v1.0.

**Comment by jochenberger** [comment]
Is there any reason why the dist build cannot stay in place in addition to the separate libs? I use react-datepicker in an AMD environment and therefore use the dist build.
