### ISSUE TITLE
Warnings @emotion/react

### ISSUE THREAD

**Issue by AHorak** [Hacker0x01/react-datepicker#4067]
I get warnings when calling yarn install.
when using  "react-datepicker": "^4.13.0",

```
warning "react-select > @emotion/react > @emotion/babel-plugin@11.10.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "react-select > @emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
```
any solution for this

**Comment by yuki0410-dev** [comment]
At least in the latest version, react-datepicker does not depend on react-select, so that warning does not occur.
We believe the solution is to use the latest version of react-datepicker.
( cc. martijnrusschen )

**Comment by yuki0410-dev** [comment]
( cc. @martijnrusschen )
