### ISSUE TITLE
Is it possible to show 6 rows always? 

### ISSUE THREAD

**Issue by rakeshnayak360** [Hacker0x01/react-datepicker#4069]
Is it possible to show 6 rows always? 
Currently the height of the calendar is changing based on the number of days. Instead can we have fixed height or fixed rows in a month so that height changing issue gets resolved.

**Comment by 3CordGuy** [comment]
@rakeshnayak360 Check out the `fixedHeight` prop. I think that is what you want.

**Comment by borshhevskijj** [comment]
Is it possible to show 5 rows always?
