### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by Stan-Stani** [Hacker0x01/react-datepicker#4081]
**Is your feature request related to a problem? Please describe.**
Unable to find documentation.

**Describe the solution you'd like**
A link to a working docs site, or at least a reference to the documentation in the docs-site directory would be useful in the README. We want to know about all the available props, etc. without digging through the source if possible.

**Describe alternatives you've considered**
I've tried running everything locally, including `docs-site`, but I get a `Package subpath './lib/tokenize' is not defined by "exports" in ...` error.

**Additional context**
Maybe I just can't find the docs site? I know https://reactdatepicker.com/ works, but it doesn't document all the props and I specifically needed to know about the `open` prop to be able to manually open and close the component. I only found it thanks to ChatGPT4 somehow knowing about it.

**Comment by sinklair** [comment]
@Stan-Stani is this what you're looking for: https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md?

It is mentioned in the Configuration section.

**Comment by Stan-Stani** [comment]
> @Stan-Stani is this what you're looking for: https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md?
> 
> It is mentioned in the Configuration section.

Ah, my bad. I guess there comes a time when skimming readmes is not enough.

**Comment by sinklair** [comment]
Took me a while to find it too 😄
