### ISSUE TITLE
Select Time example on website shows CSS bugs

### ISSUE THREAD

**Issue by tannermann** [Hacker0x01/react-datepicker#4082]
https://reactdatepicker.com/#example-select-time

![Screenshot 2023-06-15 at 3 12 51 PM](https://github.com/Hacker0x01/react-datepicker/assets/17735264/8f9a6e93-784e-46a0-bbe9-4b68e5bd6ee5)

**Comment by saltire** [comment]
Seems to have been caused by this change: https://github.com/Hacker0x01/react-datepicker/issues/4028

**Comment by hzyhbk** [comment]
I meet the same problem too when I use monthsShown=2

**Comment by tannermann** [comment]
Update for folks reading this, this has been fixed today in 4.14.1.
