### ISSUE TITLE
Difficult to differentiate selectable days in range

### ISSUE THREAD

**Issue by strawbrary** [Hacker0x01/react-datepicker#410]
When there are unselectable days within a date range, it's a little difficult to differentiate between which days are selectable and which ones aren't. What do you think of increasing the contrast between the two for range selections?

![screen shot 2016-03-16 at 3 26 23 pm](https://cloud.githubusercontent.com/assets/2499332/13830685/7e5825aa-eb8b-11e5-8f5e-4e4cf6d372a9.png)

**Comment by rafeememon** [comment]
Hey @strawbrary, good find.  I think this actually brings up the bigger question of what disabled selected dates should look like in general.  My first instinct is to get rid of the blue background altogether for those dates, but I'm not sure.  What do you think?

**Comment by strawbrary** [comment]
Hi @rafeememon, here's a little about my use case and why I'm combining range + filter. I'm creating a UI for querying a slightly offbeat analytics API. When requesting weekly data, the API strictly defines a week as starting on Monday and ending on Sunday, and the API can only return a full week's data, no partials. If you asked for data from Monday to the following Monday (8 days), you'd actually get 14 days of data because the end date includes the start of the next week. Since this would be confusing to the user, I'm restricting which dates can be selected. So in my case I want the unselectable days highlighted because they are part of the range of data returned, but perhaps there are use cases where that wouldn't necessarily be true?

**Comment by rafeememon** [comment]
Ah cool, that makes sense.  I'm not sure what the right style adjustment to make is, but you can try adding CSS for `.react-datepicker__day--disabled.react-datepicker__day--in-range` to get something that works for you.  Let us know if you find something that looks good!

**Comment by strawbrary** [comment]
I'm no designer, so I just went for a darker gray and that seems okay-ish.

![screen shot 2016-03-17 at 11 57 03 am](https://cloud.githubusercontent.com/assets/2499332/13857505/71d05b3e-ec37-11e5-99db-8ad511b29c3b.png)

**Comment by rafeememon** [comment]
Glad you found something that worked for you.  I'm not sure what the right style to use is, and since I think it's going to be a fairly rare case that disabled dates are selected, I'm going to close this out, but feel free to re-open if you want to discuss further.
