### ISSUE TITLE
Migrate test framework away from Karma

### ISSUE THREAD

**Issue by Zarthus** [Hacker0x01/react-datepicker#4107]
**Is your feature request related to a problem? Please describe.**

Karma does not support Node JS 18+ (unless you run `export NODE_OPTIONS=--openssl-legacy-provider` [NOT RECOMMENDED]). GitHub Actions actively prohibits toggling this option on.

NodeJS 16 will EOL in 2 months time: https://endoflife.date/nodejs

It is unclear for how long GitHub Actions will keep supporting Node 16, but we should assume the EOL date.

**Describe the solution you'd like**
We need to migrate away from Karma to another testing framework, e.g. Jest

This may be partially automatable with something like https://jestjs.io/docs/migration-guide#jest-codemods

**Describe alternatives you've considered**

1. Run Github Actions on Node 18 with `--openssl-legacy-provider` (not possible)
2. Keep running the CI on node 16 but target development on 18 (not feasible long-term)
3. Use a different CI infrastructure than GitHub actions to run our testsuite (not feasible long-term)

**Additional context**

More context: https://github.com/Hacker0x01/react-datepicker/pull/4100

https://github.com/karma-runner/karma/commit/450fdfdac5b999967daec1020f1ac69cf9b854ab

**Comment by martijnrusschen** [comment]
This is an important initiative. Any help we can get to migrate to Jest would be welcome. Using code mods may be give us a good start on getting the migration done.
