### ISSUE TITLE
Expose input type

### ISSUE THREAD

**Issue by Pizdetss** [Hacker0x01/react-datepicker#411]
Hi,

Is it possible to expose the input type so we can target mobile devices keyboard to show numbers instead of the whole keyboard.

Cheers,

**Comment by rafeememon** [comment]
Hey @Pizdetss, this is something we could do, but I'm interested in your use case.  I think having only numbers available on the keyboard wouldn't allow someone to type in a full formatted date, and I'm not sure how a browser will react if a formatted date is put into a number field (probably should treat as undefined behavior).  Am I missing something?

(want to make sure that if we add this to the API it will be for the right reason)

**Comment by Pizdetss** [comment]
Hey @rafeememon, thanks for quick response.

Basically we can utilize html5 input type 'date' to keep the correct format.
You are correct that 'numbers' will not format the date correctly as I believe that type doesn't allow character '/'. However we could also use type 'tel'. 

There is some more info here: https://miketaylr.com/pres/html5/forms2.html (be warned the date input on here has some funky font size issue but works well on mobile). 

Our use case is building our forms as mobile priority first and desktop second.  

By utilizing the inputs in correct type will force Android and OSX devices to show date/telephone pad when the focus is on the input. It is more of a usability case so that users don't need to have an extra step to enable numbers on their device. This is off course if they prefer to type it in instead of using the datepicker UI to select the date. 

Perhaps maybe you could just have a default of type 'text' and just let the developer decide on which type they want to implement.

**Comment by rafeememon** [comment]
We had some interesting discussion re: using the `date` type on #402.  The tl;dr was that browser handling for types other than `text` conflict with the way this component handles the input field.  Specifically for  `type='date'`, focusing opens a native datepicker, imposes a date format that can't be changed, and generally did weird things when I briefly tried it out =P  Not sure if you've considered this, but you can try it out by running the example page and changing the type to `date`.  I suppose `type='tel'` could work if your date format only includes number and dashes, even though it seems like a slight abuse of that `type`.

Anyway, I think this will be trivial to support as we refactor components in preparation for v1.0.  I'll make sure it gets in

**Comment by rafeememon** [comment]
Oops, that commit did the opposite of what I wanted -- reverted it

**Comment by Pizdetss** [comment]
@rafeememon thanks!

**Comment by martijnrusschen** [comment]
@rafeememon What do you suggest here? Make the type configurable as a prop?

**Comment by aij** [comment]
@martijnrusschen  Isn't that already configurable via `customInput`?

Eg: `<DatePicker customInput={<input type="date"/>}/>`

**Comment by martijnrusschen** [comment]
A bit custom, but that should work indeed.
