### ISSUE TITLE
Module not found: Can't resolve 'react-onclickoutside'

### ISSUE THREAD

**Issue by Satish789748** [Hacker0x01/react-datepicker#4122]
"react-datepicker": "4.13.0",
    In this version getting this issue.
    error - ../../node_modules/react-datepicker/dist/react-datepicker.min.js:1:15
Module not found: Can't resolve 'react-onclickoutside'

**Comment by Zarthus** [comment]
I was unable to reproduce, can you give more insights?

The dep is also visible in the 4.13 tag

**Comment by yuki0410-dev** [comment]
The PR for this issue has already been merged and appears to be resolved.

( cc. @martijnrusschen )
