### ISSUE TITLE
Locale inconsistency when typing date

### ISSUE THREAD

**Issue by adambowles** [Hacker0x01/react-datepicker#414]
Typing a date string into the text box in amiguous format (e.g. `02/01/2016`) datepicker will assume American date format, i.e. typing `02/01/2016` -> `01/02/2016` gets rendered, and vice versa.

Occurs in [this demo](https://hacker0x01.github.io/react-datepicker/#example-6)

**Comment by rafeememon** [comment]
Fixed by #400, will be available in the next release
