### ISSUE TITLE
Disabled Quarters Not Visible in UI (excludeDates)

### ISSUE THREAD

**Issue by Maddy-O** [Hacker0x01/react-datepicker#4219]
**Issue Description:**
The react-datepicker component is not displaying disabled quarters properly in the UI, even though the disable functionality is functioning correctly. While the disable feature (excludeDates) works as expected for months and years, it seems to be encountering a CSS issue specifically when dealing with quarters. This results in disabled quarters not being clearly distinguishable from the enabled ones.

**Expected Behavior:**
When quarters are disabled using the excludeDates, they should have a visually distinct appearance from the enabled quarters. This is consistent with the behavior for months and years, where disabled units are clearly discernible through CSS styling.

**Screenshots:**
Attached screenshots clearly demonstrate the issue:

- Screenshot 1: Correct behavior for disabled months and years.

![raise-git-issue-01](https://github.com/Hacker0x01/react-datepicker/assets/95930594/7d4a8c6c-ce02-4b14-a407-c77b38392396)
![raise-git-issue-02](https://github.com/Hacker0x01/react-datepicker/assets/95930594/34dfb75e-b09b-42c9-abac-4676335722ea)

- Screenshot 2: Incorrect behavior for disabled quarters, lacking proper visual styling.

![raise-git-issue-03](https://github.com/Hacker0x01/react-datepicker/assets/95930594/06603025-bafe-4c53-8a32-60c90597285c)

**Comment by Maddy-O** [comment]
Any update ?

**Comment by asada-no4** [comment]
Hi [@martijnrusschen](https://github.com/martijnrusschen),

Please assign this issue to me. I'll try to work on this.

**Comment by asada-no4** [comment]
Sorry...
I accidentally created a PR before I was assigned.
https://github.com/Hacker0x01/react-datepicker/pull/4948
