### ISSUE TITLE
Please release 0.25.0

### ISSUE THREAD

**Issue by dmnd** [Hacker0x01/react-datepicker#424]
There's [lots of unreleased commits in master](https://github.com/Hacker0x01/react-datepicker/compare/v0.24.0...master). Could you please publish a new release? :smile: 

I ask because I want the changes from #404 but due to [npm limiltations](npm/npm#3055) it's annoying to depend on a git repository for modules that have a build step. Currently I'm using [`npm-git-install`](https://github.com/lzrski/npm-git-install) as a workaround but it makes my deploy super slow. :turtle:

Thanks! :heart:

**Comment by martijnrusschen** [comment]
Done: https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.25.0
