### ISSUE TITLE
Importing styles for POSTCSS

### ISSUE THREAD

**Issue by abilashs90** [Hacker0x01/react-datepicker#425]
Hi, I've been facing a issue with styling the date picker with `POSTCSS`. As most of you would know, styles in `POSTCSS` would be imported as JavaScript object and would be used. 

If I just import the styles as depicted in the examples, the date picker wouldn't work. How do I acheive this for `POSTCSS` is my question.

**Comment by abilashs90** [comment]
@rafeememon the styles, while using `POSTCSS` are imported as `JavaScript` objects and the class names are in react components are added something like `className={styles['class-name']}`. I noticed that the styles in date picker is used like `className="class-name"`. 

Any help would be appreciated.

**Comment by rafeememon** [comment]
I don't think it's possible to do what you're trying to do -- our styles are shipped with a CSS file referencing class names that appear in react components
