### ISSUE TITLE
Please add 'keep calendar open' property

### ISSUE THREAD

**Issue by VirgilioShadow** [Hacker0x01/react-datepicker#4255]
**Is your feature request related to a problem? Please describe.**
I would like to keep the calendar open at all times and with no popper arrow. I'm using the datepicker elsewhere in the application, and default behavior is fine, so a global change would be undesirable. I created a customized datepicker (see below), but the positioning changes when the dev console is open.  

**Describe the solution you'd like**
Please add a prop that prevents the calendar from closing when datepicker loses focus.

**Describe alternatives you've considered**
I created custom css for the popper which works intermittently: 

.custom-datepicker-popper {
  margin-left: -225px;
}

I'm also using state to keep the datepicker open on a zero length timer.

**Additional context**
Here is my customized datepicker:

import DatePicker from 'react-datepicker';

const CustomizedDatePicker = () => {
  const dispatch = useDispatch();
  const [isOpen, setIsOpen] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsOpen(true);
    }, 0);
    return () => clearTimeout(timer);
  }, [isOpen]);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    // fetch code
  };

  const handleDateChange = (date) => {
   // date change code
  };

  return (
    <DatePicker
      selected={selectedDate ? new Date(selectedDate) : new Date()}
      showPopperArrow={false}
      popperClassName='custom-datepicker-popper'
      onChange={handleDateChange}
      onCalendarClose={() => setIsOpen(false)}
      open={isOpen}
      todayButton='Today'
    />
  );
};

**Comment by bharath090909** [comment]
@VirgilioShadow , I would like to address this. Can I take it on?

**Comment by VirgilioShadow** [comment]
showPopperArrow={false} was causing my issue,  Playing around in the API fixed it, thanks!
