### ISSUE TITLE
onChange event not firing when typing

### ISSUE THREAD

**Issue by andynoelker** [Hacker0x01/react-datepicker#426]
The `onChange` event only seems to fire when selecting a date from the picker but not when the user types into the input field. This makes it impossible to do any sort of validation on user input.

Current workaround is to set `readOnly` to `true` so that it forces users to only use the picker, but it would be ideal to also let them type into the box and be able to run my own validation regex in a change handler before updating the input value. Am I missing something here or is this not supported? It seems like you would either need to expose the input field's actual `onChange` property or tie it into the parent component's property (I would have assumed it already was).

React-datepicker v0.25.0
React v0.14.7

**Comment by rafeememon** [comment]
Yep, currently `onChange` only reflects the selected date, not the user's input.  We're working on refactors for v1.0 that expose components/events in more native ways; I think the current `onChange` may end up being renamed to `onChangeDate`.

**Comment by andynoelker** [comment]
Okay, thanks for the info! Yes, factoring into 2 change events might be the best way to pull that off. I look forward to seeing this addressed in v1.0. I guess I'll leave this open until then, although if you'd prefer it didn't fill up the issues list then please close it.

**Comment by rafeememon** [comment]
I'll leave this open to make sure we don't forget =)

**Comment by Erzei** [comment]
Is there a workaround to get the native event?

I have a onChange handler where I receive the event and expect to get the input name from the event.target object, but instead I get a moment object, which breaks my state validation process.

**Comment by manishstrivepool** [comment]
I am facing the same problem. I am new to react so I don't have any sort of idea for solving this. can anybody please help me out of it.

**Comment by LeoAref** [comment]
@manishstrivepool @Erzei 
I'm solving the problem of native events by using `ref` and fire `ref.change()` manually!
Waiting for a proper solution as well

**Comment by alex-shamshurin** [comment]
I noticed that `onChange` event never happens if using custom input component with null value. When we select date through DatePicker the input field first get `onBlur` event and then if it's value is `null` and `onBlur` handler of input element is defined then `onChange` of DatePicker is not fired.

**Comment by FredyC** [comment]
Um, so is this ever going to happen since it was removed from milestone? It would be super useful for writing E2E tests so I can enter a specific value rather than by selecting a value from a combo.

**Comment by rafeememon** [comment]
@FredyC contributions to fix this issue are welcome

**Comment by YuriAntishev** [comment]
I have the same issues and I solve them by this approach:

`const [startDate, setStartDate] = useState(new Date());
        const ExampleCustomInput = ({ value, onClick, onChange }: any) => (
            <S.StyledFloatingLabel controlId="floatingInput" label={placeholder} className="mb-3"
            >
                <Form.Control
                    placeholder={placeholder}
                    onChange={onChange}
                    onClick={onClick}
                    value={value}
                    autoComplete="off"
                />
            </S.StyledFloatingLabel>
        );

return (
                <>
                    <DatePicker
                        className="form-control"
                        dateFormat="dd/MM/yyyy"
                        selected={startDate}
                        onChange={(date: any) => setStartDate(date)}
                        customInput={<ExampleCustomInput />}
                    />

                </>
            );
`

**Comment by YuriAntishev** [comment]
I met the same issues in my practice so I resolve problem with this approach - just pass all props(value, onClick, onChange) in the custom input(child) component:

```
const [startDate, setStartDate] = useState(new Date());
        const ExampleCustomInput = ({ value, onClick, onChange }: any) => (
            <S.StyledFloatingLabel controlId="floatingInput" label={placeholder} className="mb-3"
            >
                <Form.Control
                    placeholder={placeholder}
                    onChange={onChange}
                    onClick={onClick}
                    value={value}
                    autoComplete="off"
                />
            </S.StyledFloatingLabel>
        );
return (
                <>
                    <DatePicker
                        className="form-control"
                        dateFormat="dd/MM/yyyy"
                        selected={startDate}
                        onChange={(date: any) => setStartDate(date)}
                        customInput={<ExampleCustomInput />}
                    />
                </>
            );

```
