### ISSUE TITLE
Event bubbling problem

### ISSUE THREAD

**Issue by LopatkinEvgeniy** [Hacker0x01/react-datepicker#427]
I am set this datepicker inside a tooltip. Tooltip listens body's onClick event and hide if event targen is not inside.  If i pick some date in datepicker, tooltip is closed. I think that 'stopImmediatePropagation' property of datepicker component would be a good solution.

**Comment by rafeememon** [comment]
What about using the `renderCalendarTo` prop to make the calendar render in the tooltip's DOM tree?

**Comment by LopatkinEvgeniy** [comment]
thanks. That is what i need.

**Comment by rafeememon** [comment]
Great!
