### ISSUE TITLE
No scroll to selected item when using portalId for showTimeSelectOnly in scrollable div

### ISSUE THREAD

**Issue by 1Jesper1** [Hacker0x01/react-datepicker#4289]
**Describe the bug**
No scroll to selected item when using portalId for showTimeSelectOnly in scrollable div

**Test code:
```
() => {
  const [startDate, setStartDate] = useState(new Date('02-02=2023 06:00'));
  return (
  <div>
  <div id='test'></div>
    <DatePicker
      portalId={'test'}
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      showTimeSelectOnly
      showTimeSelect
    />
     </div>
  );
};
```

**Possible fix: 	
```
onCalendarOpen={() => {
 const itemSelected = document.querySelector( '#datepicker-wrapper .react-datepicker__time-list-item--selected' );
 const offSetTop = itemSelected?.offsetTop;
 const clientHeight = itemSelected?.clientHeight;
 const parentElement = itemSelected?.parentElement;
 if (parentElement) {
    parentElement.scrollTop = offSetTop - ((parentElement.clientHeight / 2) - (clientHeight / 2));
 }
}};
```

**Expected behavior**
Should scroll to item.

**Screenshot
![image](https://github.com/Hacker0x01/react-datepicker/assets/4539406/d8112e4c-e89d-4f38-9a6d-6ae2f3820cfb)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version react-datepicker 4.10.0

**Comment by balajis-qb** [comment]
Hi,

I fixed the issue in my PR https://github.com/Hacker0x01/react-datepicker/pull/4296 . This PR also fixes the other scroll related issue https://github.com/Hacker0x01/react-datepicker/issues/4290. Kindly review my fix and let me know your review comments.

**Comment by 1Jesper1** [comment]
@martijnrusschen Nice to see a fix so soon available! This issue can be closed I think?

**Comment by martijnrusschen** [comment]
You can close this issue if you're not experiencing issues anymore since the recent release

**Comment by 1Jesper1** [comment]
@martijnrusschen I will test soon.

**Comment by 1Jesper1** [comment]
Works!
