### ISSUE TITLE
How to make Calendar icon show in React Date Picker?

### ISSUE THREAD

**Issue by AtGbemiga** [Hacker0x01/react-datepicker#4291]
**Describe the bug**
I'm using React Date Picker, which I installed via npm i react-datepicker. Everything works except the calendar icon which doesn't display. The docs says to add showIcon to the JSX element to display the calendar icon, this does not show the icon, it only makes the JSX element bigger.

**To Reproduce**
```tsx
"use client";

import { useState } from "react";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";


export default function Form() {
  const [dateRange, setDateRange] = useState<[Date | null, Date | null]>([
    null,
    null,
  ]);
  const [startDate, endDate] = dateRange;

  return (
    <form>
      <DatePicker
        showIcon
        selectsRange={true}
        startDate={startDate}
        endDate={endDate}
        onChange={(update) => {
          console.log("Selected Date Range:", update);
          setDateRange(update);
        }}
        minDate={new Date()}
        withPortal
      />
    </form>
  );
}
```

**Expected behavior**
A calendar icon should be displayed.

**Screenshots**
[No icon](https://github.com/AtGbemiga/car-rental-frontend/blob/main/No%20icon.PNG)

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome
- Version "^4.16.0"

**Comment by frankops11** [comment]
@AtGbemiga show https://github.com/Hacker0x01/react-datepicker/pull/4295

**Comment by AtGbemiga** [comment]
> @AtGbemiga show #4295

I don't understand what your response is stating.

**Comment by frankops11** [comment]
Try the last versión and if problem persist please added a Sanbox or Stackblitz :)

**Comment by AtGbemiga** [comment]
> Try the last versión and if problem persist please added a Sanbox or Stackblitz :)

Alright, I will as quickly as possible :)

**Comment by frankops11** [comment]
Hey bro, you know, check it out and see if it's true. But the problem is more than anything because of a style:

After
![image](https://github.com/Hacker0x01/react-datepicker/assets/50973629/f6f01020-8507-4152-87cd-09e2b4a3b39c)

Before
![image](https://github.com/Hacker0x01/react-datepicker/assets/50973629/26365c83-26d8-4cc4-ae28-652fbbf4f836)

I'm going to review and look for the cause, because analyzing X's comment, this came from the last version. The funniest thing is that he never replied to me

**Comment by skoldborg** [comment]
@frankops11 Overriding `box-sizing: border-box;` does indeed solve the issue, but I'm not sure that's a viable solution? Icon should be still be visible when `box-sizing: border-box;` is set, no?

**Comment by frankops11** [comment]
That's right, I should be indifferent, I already have a solution and I'm raising the PR

**Comment by frankops11** [comment]
Hello Everyone! 🚀

Thrilled to announce that the solution to the calendar icon issue has been merged into the main branch! 🎉 Therefore, we can confidently state that issue [#4291](link_to_issue) is officially resolved.

The update will be available to all in the next release! We greatly appreciate your patience and constructive contributions throughout this resolution process. Your feedback and collaboration have been instrumental in reaching this juncture, and we’re excited to bring this enhancement to you all.

Special shoutouts to:
[Tag/Cite involved contributors here]

Should you encounter any further issues or have more feedback down the line, please do not hesitate to share. We’re here to build the best possible tool with and for you.

Once again, thank you, and we hope you enjoy the improvement! 

Warm regards,
Warm regards,
Francisco @Hacker0x01

**Comment by AtGbemiga** [comment]
I can confirm that the issue is fixed. 
version: "^4.20.0"

**Comment by Darko-Martinovic** [comment]
Is there a way to color the calendar icon? By default, it is black.

**Comment by my-kol** [comment]
@Darko-Martinovic, 
```
<DatePicker
  // all your needed props
  calendarIconClassName={"your-classname"}
  showIcon
/>
```

and .css

```
.your-classname{
    fill: lightgray;
}
```

![Image](https://github.com/user-attachments/assets/0d5d35be-56dc-4e67-83eb-0893b4a22e78)
