### ISSUE TITLE
Webpack needs appropriate loader: `Unexpected token .`

### ISSUE THREAD

**Issue by diffractometer** [Hacker0x01/react-datepicker#430]
Hi, using ES6 + Webpack I get the following error when I add `require('react-datepicker/dist/react-datepicker.css');`

```
ERROR in ./~/react-datepicker/dist/react-datepicker.css
Module parse failed: /Users/.../node_modules/react-datepicker/dist/react-datepicker.css Line 1: Unexpected token .
You may need an appropriate loader to handle this file type.
| .react-datepicker__tether-element-attached-top .react-datepicker__triangle, .react-datepicker__tether-element-attached-bottom .react-datepicker__triangle, .react-datepicker__year-read-view--down-arrow {
|   margin-left: -8px;
|   position: absolute;
```

Has anyone seen this error or know what loader I'm missing?

    "webpack": "1.12.11"
    "react": "^0.14.7"

**Comment by martijnrusschen** [comment]
I think you need this loader: https://github.com/webpack/css-loader

**Comment by diffractometer** [comment]
@martijnrusschen Wow that was quick! But I'm already using this loader. 

```
    {
      test: /(\.css|\.scss)$/,
      include: path.join(__dirname, 'src'),
      loaders: ['style', 'css?sourceMap', 'sass?sourcMap']
    },
```

**Comment by martijnrusschen** [comment]
Check out this config. We're using the datepicker internally to load the examples: https://github.com/Hacker0x01/react-datepicker/blob/master/webpack.docs.config.js

**Comment by diffractometer** [comment]
Thanks. Does using ExtractTextPlugin force No Hot Module Replacement?

**Comment by rafeememon** [comment]
@diffractometer, I think the issue is that your config is set up to read css files from your `src` directory and not `node_modules` where the datepicker stylesheet will live.

**Comment by diffractometer** [comment]
@rafeememon Yes! That was it. Thanks a ton!

**Comment by rafeememon** [comment]
No prob! :+1:

**Comment by brendonco** [comment]
how did you manage to load the react-datepicker.min.css?

I'm using webpack.config.js loader but doesnt work:

```
{
        test: /\.(scss|css)$/,
        include: [path.resolve(__dirname, "src/scss/"), path.resolve(__dirname, "node_modules/react-datepicker/dist/")],
        loaders: ["style", "css?sourceMap", "sass?sourceMap"],
      },
```
