### ISSUE TITLE
Cannot read property 'outsideClickIgnoreClass' of undefined

### ISSUE THREAD

**Issue by tjcampbell** [Hacker0x01/react-datepicker#433]
Hi guys,

Firstly, thanks for a great date picker!

Everything has been working for a while, but after updating to meteor's latest stable version (1.3) I can't get it working again. I realise this could be a meteor issue so feel free to send me in that direction if it's clearly not a problem here.

**The Problem**
The component mounts fine and opens correctly on focusing the input, but when clicking outside the calendar to close it, I get the error "Cannot read property 'outsideClickIgnoreClass' of undefined". After looking into what's going on, it looks like the react-onclickoutside mixin is getting the wrong context somewhere along the line
```javascript
var fn = this.__outsideClickHandler = (function(localNode, eventHandler) { 
  return function(evt) {
    evt.stopPropagation();
    var source = evt.target;
    var found = false;
    // this.props is undefined here, and 'this' is the document for some reason
    var ignoreClass = this.props.outsideClickIgnoreClass || IGNORE_CLASS;
```
Has anyone experienced this? Or is this possibly a meteor build issue?

**Comment by janroesner** [comment]
Same issue here

**Comment by andynoelker** [comment]
Just did an update and started getting this as well

**Comment by rafeememon** [comment]
Making a fix in react-onclickoutside now, please hold

**Comment by tjcampbell** [comment]
@rafeememon I can create a PR if it saves you some time?

**Comment by rafeememon** [comment]
Fix submitted at Pomax/react-onclickoutside#73.  Once it merges and a new version is released this should be fixed.

**Comment by tjcampbell** [comment]
Thanks @rafeememon

**Comment by rafeememon** [comment]
@tjcampbell, @janroesner, @andynoelker, the fix is merged, let us know if that fixes the issue for you

**Comment by janroesner** [comment]
Works for me. Thank you!

**Comment by rafeememon** [comment]
Awesome! Sorry for the trouble.

**Comment by tjcampbell** [comment]
@rafeememon are you guys going to do a release with the fix?

**Comment by rafeememon** [comment]
The new release of react-onclickoutside will be pulled in automatically if you reinstall
