### ISSUE TITLE
Enhancement: Improve Test cases Maintainability and Remove Magic Numbers on test/exclude_times_test.test.js, test/filter_times_test.test.js and test/include_times_test.test.js

### ISSUE THREAD

**Issue by balajis-qb** [Hacker0x01/react-datepicker#4334]
**Description**
This issue is to propose an enhancement to the project by improving the maintainability of certain test cases and removing magic numbers from the test cases which will be helpful for the developers to easily understand the codebase.

**Motivation and Benefits**

- Enhancing test case maintainability will lead to more readable and understandable code.
- Removing magic numbers will make the code more robust and easier to maintain

**Related Files/Code**

- test/exclude_times_test.test.js
- test/filter_times_test.test.js
- test/include_times_test.test.js

![image](https://github.com/Hacker0x01/react-datepicker/assets/145029139/ba046d87-eafc-45f1-9948-dc2e13afb2fa)

![image](https://github.com/Hacker0x01/react-datepicker/assets/145029139/8896b4bb-cda5-463b-80df-cd64dad35498)

**Comment by martijnrusschen** [comment]
Sounds good

**Comment by balajis-qb** [comment]
Hi @martijnrusschen , 

I created this issue based on the review comments I got on one of my previous PRs (https://github.com/Hacker0x01/react-datepicker/pull/4319#discussion_r1359640157).  Can you assign this issue to me? I'll update the test cases for the mentioned files

**Comment by balajis-qb** [comment]
@martijnrusschen, Thank you for assigning this refactor ticket to me.  I created a PR for this - https://github.com/Hacker0x01/react-datepicker/pull/4335.  Kindly review it and let me know if any changes required.
