### ISSUE TITLE
supported version for react@18.2.0

### ISSUE THREAD

**Issue by HarshitSrivastava007** [Hacker0x01/react-datepicker#4344]
Hi, 

currently i'm migrating my project to react 18.2.0 and facing issues with  react-datepicker@2.16.0

can please suggest me a solution

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0" from react-datepicker@2.16.0
npm ERR! node_modules/react-datepicker
npm ERR!   react-datepicker@"^2.9.4" from the root project

**Comment by martijnrusschen** [comment]
You're using a very old version of the package. Try using the latest version.
