### ISSUE TITLE
'Local Development' part of the README file needs to be modified.

### ISSUE THREAD

**Issue by DigitalBard** [Hacker0x01/react-datepicker#4362]
**Describe the bug**
When I followed the steps of the "Local Development" part of README file, I got an error like below:
![error](https://github.com/Hacker0x01/react-datepicker/assets/103251717/f94e44d4-af08-44cd-9d12-3c4531591de8)

That's because when I did `yarn build-dev`, the `dist` directory was incomplete.
![dist](https://github.com/Hacker0x01/react-datepicker/assets/103251717/2836928d-1fe4-4ff9-8cf2-0e8158289d89)

And there was another warning like this:
![1](https://github.com/Hacker0x01/react-datepicker/assets/103251717/109c4aa3-9557-442b-9243-5928838d97c6)

But when I followed the 'Getting set up' part of 'CONTRIBUTING.md' file, everything was okay.
![distrig](https://github.com/Hacker0x01/react-datepicker/assets/103251717/e2fa8af8-1707-4ad7-8e1f-efa16a784502)

**To Reproduce**

1. Clone the project by "git clone".
2. `yarn install`
3. `yarn build-dev`
4. `yarn start`

**Expected behavior**
So, I recommend to modify the 'Local Development' part of the 'README file' like 'Getting set up' part of 'CONTRIBUTING.md' file,
or rewrite simply like "Please refer to 'CONTRIBUTING.md' file."

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Comment by yuki0410-dev** [comment]
@DigitalBard (cc. @martijnrusschen )
It looks like the PRs have already been merged, are there any other issues?
