### ISSUE TITLE
Prevent browser autocomplete

### ISSUE THREAD

**Issue by evoluteur** [Hacker0x01/react-datepicker#4368]
**Is your feature request related to a problem? Please describe.**
Chrome is offering autocomplete on focus when thee input field is empty.  It is not needed in most contexts. It would be nice to have a new prop in the component to enable/disable it.

**Describe the solution you'd like**
Add autocomplete="off" attribute to the input field.

**Describe alternatives you've considered**
N/A

**Additional context**
I believe it's only happening w/ Chrome and noot w/ other browsers.

**Comment by Orhan92** [comment]
You can just pass the autocomplete prop to the DatePicker component and it will work.
<DatePicker autoComplete="off" />

**Comment by evoluteur** [comment]
Excellent. Thanks. 
I guess I can close the issue.
