### ISSUE TITLE
Build break re: parsing dates with a locale

### ISSUE THREAD

**Issue by rafeememon** [Hacker0x01/react-datepicker#438]
A unit test is failing because a formatted date cannot be parsed when a locale is specified: https://github.com/Hacker0x01/react-datepicker/blob/v0.25.0/test/date_input_test.js#L125

I think it's a bug in moment; tracking the issue here: https://github.com/moment/moment/issues/3088

**Comment by maggiepint** [comment]
Track this by moment pull request moment/moment#3078

**Comment by rafeememon** [comment]
Unbroke the build with 8a0d1829828121b0be44975d4fc6c94f3c1bc1b7; revert when fixed
