### ISSUE TITLE
Add CSS class for days name

### ISSUE THREAD

**Issue by montogeek** [Hacker0x01/react-datepicker#440]
Hi!

Thanks for this component :)

It would be nice to add a class for the day names: Su Mo Tu We Th Fr Sa.
Something like `__days`, I am happy submitting a PR for this, let me know if it works for you.

I am suggesting it because I need to style them :)

**Comment by rafeememon** [comment]
Yeah, I don't think it makes sense for the day names to have the same class as the dates (`react-datepicker__day`).  I think the day names should probably be separated into a separate class, probably `react-datepicker__day-name`.

**Comment by montogeek** [comment]
Hi @rafeememon I said `__days` but `__day-name` is good.
I will create a PR later today!

Thank you :)

**Comment by rafeememon** [comment]
Yeah please call it `react-datepicker__day-name`, I think it's much more descriptive of what's going on here

**Comment by montogeek** [comment]
I will! :D
