### ISSUE TITLE
Datepicker offset by one day?

### ISSUE THREAD

**Issue by mmahalwy** [Hacker0x01/react-datepicker#442]
Today's date is Thursday April 7, 2016. The datepicker is showing it's Friday 7th.

![image](https://cloud.githubusercontent.com/assets/3749095/14369862/7e9aa976-fcdd-11e5-9f6e-11c1664e0c58.png)

Code:
```
<DatePicker
            minDate={moment()}
            selected={startDate}
            startDate={startDate}
            endDate={endDate}
            onChange={this.handleChangeStart}
            placeholderText="From date"
            dateFormat="MM/DD/YYYY"
            className="form-control margin-md-left"
            isClearable />
```
I should also mention this is coming from server-side rendering

**Comment by mmahalwy** [comment]
Seems like the problem was around `selected` props, so I replaced `startDate` with `moment()`. In some cases it works and others it does not (where I have the weird offset of dates)

**Comment by mmahalwy** [comment]
Also throws this error when i open the datepicker:
```
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale
```

**Comment by rafeememon** [comment]
What version of the date picker are you using?

This is possibly the same issue as #203, which we have had a lot of trouble tracking down.

**Comment by mmahalwy** [comment]
`"react-datepicker": "^0.21.0",`

**Comment by rafeememon** [comment]
What version is actually installed? Look at the package.json pulled into node_modules/react-datepicker

**Comment by mmahalwy** [comment]
@rafeememon  ` "version": "0.21.0"`

**Comment by rafeememon** [comment]
Yep, try with the latest version, v0.25

**Comment by mmahalwy** [comment]
yep, fixed it!

**Comment by olanMbakop** [comment]
I'm having the issue until now... ^1.6.0

**Comment by JivkoJelev91** [comment]
moment(myDate).toISOString(true) Only this works for me :(
