### ISSUE TITLE
calendarStartDay and showWeekPicker, selected week is not active

### ISSUE THREAD

**Issue by vellov** [Hacker0x01/react-datepicker#4455]
**Describe the bug**
When showWeekPicker is set true and calendarStartDay is set to 1, then only the first day of the week gets active state.
If calendarStartDay prop is removed it works as intended. 

**To Reproduce**
1. Create datepicker as following:
2.  `<DatePicker selected={date} startDate={x} onChange={setDate} showWeekPicker={true} />`
3.  Check that after selecing week and reopening calendar it is in selected state
4. add calendarStartDay prop:  `<DatePicker calendarStartDay={1} selected={x} startDate={x} onChange={setX} showWeekPicker={true} />`
5. select week
6. selected week is not in active state

**Expected behavior**
selected week should be in active state 

**Screenshots**
<img width="232" alt="Screenshot 2024-01-14 at 23 53 56" src="https://github.com/Hacker0x01/react-datepicker/assets/5435960/40cbe8f7-a30a-4b74-8c69-32506bc20480">
<img width="232" alt="Screenshot 2024-01-14 at 23 54 21" src="https://github.com/Hacker0x01/react-datepicker/assets/5435960/eaa784b5-a78d-4551-a0f9-bbb1a79ef13b">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by paulmahardika** [comment]
I have same issue about this
