### ISSUE TITLE
context-menu opens on mobile-view

### ISSUE THREAD

**Issue by baeroe** [Hacker0x01/react-datepicker#4458]
**Describe the bug**
When I use the chrome developer console and select the mobile view, the context menu opens when I pres on the day, month or year.

**Demo**
https://codesandbox.io/p/sandbox/react-date-picker-problem-r93pxd?file=%2Fsrc%2FApp.js%3A7%2C20
https://r93pxd.csb.app/

**Expected behavior**
The context menu should not open.

**Screenshots**

https://github.com/Hacker0x01/react-datepicker/assets/35110665/eda6b376-4b68-4a3d-8640-de7de9565c91

**Desktop (please complete the following information):**

- OS: macOS 14.2.1 (23C71)
- Browser: chrome
- Version: 120.0.6099.216

**Comment by yuki0410-dev** [comment]
According to the sample code you provided, you seem to be using "react-date-picker". Since this is the Repository for "react-datepicker", you have created an issue in a different repository from the package you are using.
(@martijnrusschen)

**Comment by martijnrusschen** [comment]
Closing this since it's not related to this package.
