### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by l9777** [Hacker0x01/react-datepicker#4477]

**Comment by 39015745** [comment]
I've updated from last version and get the same warning

**Comment by timtucker-dte** [comment]
Seeing the same issue here as well.

**Comment by pfischer1290** [comment]
same here

**Comment by yusufneeson** [comment]
same

**Comment by jgoodall** [comment]
I have the same issue with 5.0.0, although 4.25.0 seems fine.

**Comment by Darlley** [comment]
Same

![Capturar](https://github.com/Hacker0x01/react-datepicker/assets/37590954/1b1c04a7-df51-4206-8497-ead27b0ca895)
![error](https://github.com/Hacker0x01/react-datepicker/assets/37590954/d6cd31d9-6086-48f0-b352-55be5b738a8b)

**Comment by martijnrusschen** [comment]
If there's anyone who wants to submit a PR for this, feel free to do so.
