### ISSUE TITLE
Week number is highlighted when selecting the first day of the week

### ISSUE THREAD

**Issue by MaertHaekkinen** [Hacker0x01/react-datepicker#4489]
**Describe the bug**
Week number gets highlighted when selecting the first day of the week, but not when selecting any other day of the week.

**To Reproduce**
1) Click on the first day of the week.
![image](https://github.com/Hacker0x01/react-datepicker/assets/9450980/e830771b-0234-4b55-b18f-89702cd8b20f)

2) Click on any other day of the week (same or other)
![image](https://github.com/Hacker0x01/react-datepicker/assets/9450980/a41ce8fe-e25a-49f7-8f57-332776a09333)

**Expected behavior**
Week number gets highlighted for both cases or only when a range is selected - I am not 100% sure on what is the agreed behaviour, but current one seemed very odd to me.

Desktop

- OS: Windows 10
- Browser: Chrome
- Version: 121.0.6167.139 (Official Build) (64-bit)

**Where to test?**

Codepen:
https://codepen.io/MaertHaekkinen/pen/ExMQrMq

OR

https://reactdatepicker.com/ - "Display Week Numbers"

**Comment by Vedant767** [comment]
Hi, I will take this issue.
