### ISSUE TITLE
Time input field loses focus after one character input

### ISSUE THREAD

**Issue by bayadsi** [Hacker0x01/react-datepicker#4514]
**Describe the bug**
In [this example](https://reactdatepicker.com/#example-input-time) in the docs the time input field loses focus after the user enters one numerical character. 

**To Reproduce**

1. Go to https://reactdatepicker.com/#example-input-time
2. Click on date input field
3. Click on time input field
4. Insert one character
5. Wait 1 second
6. Insert another charector
=> time input field loses focus to date field and the second character is inserted in the date field instead of the time field.

**Expected behavior**
Time input field should not lose focus and should allow users to insert multiple characters without them having to click (manually focus) the time input field again.

**Desktop:**

- OS: macOS Ventura, 13.6.1
- Browser: chrome, safari
- Version: chrome version - 121.0.6167.139, safari version - 17.3 (18617.2.4.11.9, 18617) 

**Additional context**
In react-datepicker version 4.15.0 this is not the case. The time field allows the user to enter multiple numbers without the focus of the input being removed.

**Comment by balajis-qb** [comment]
Hi @martijnrusschen , I tracked the issue related to this ticket.  Can you please assign this ticket to me?
