### ISSUE TITLE
Preact: DatePicker just opens one time and then not on subsequent clicks.

### ISSUE THREAD

**Issue by puredazzle** [Hacker0x01/react-datepicker#4538]
**Describe the bug**
When using react-datepicker@6.1.0 with Preact@10.19.6 it is not possible to open the datepicker again after the user has clicked outside the field.

**To Reproduce**

1. Go to https://codesandbox.io/p/sandbox/awesome-golick-3799w8
2. Click on the field
3. Click outside the field
4. Click on the field again

**Expected behavior**
The date picker should be visible each and every time a user click the field.

**Screenshots**
![image](https://media.cleanshot.cloud/media/30927/hu0aH6maOCWIEGYdCF4fsGzt4XUD5AwKU8ve3lKp.gif?Expires=1709065941&Signature=D~nj0ptlaXZIh3N8XfkM3IvLjU1MnRnZ~HCUHQ0byPmQb59QBwX0-Ek2Kucslc00ERAUnZcen6wrlK49AdvCtm51-qNIvC67PReunHP0fRzqQqL1bxIYb1WesWh57aAHxPH4IHSBm0l~OiI7aSptUFnjrTSI4I8xpm0aIijS1PwX3WcvHHVOV5aTFwqamOzsHxc~FSPh4ZbCKR0XA4b4zwQAkL09CVp2LGnRqbWxZlkeZDRpkPt6EsZBMLiC5UdUJSeKGa0aF099UiqmyKivuqlAUV3fRHCrK2qL6cYxkZZARm07~BPRDCS41ObpRDYXasOYHwN31nyQTHSdpfMc6g__&Key-Pair-Id=K269JMAT9ZF4GZ)

**Desktop (please complete the following information):**

- OS: Mac
- Browser chrome
- Version 121.0.6167.184 (Official Build) (x86_64)

**Comment by yuki0410-dev** [comment]
It seemed to work fine in the sandbox you presented.
In the sandbox, preact is set to latest. Is it possible that the preact version upgrade may have improved this?

**Comment by yuki0410-dev** [comment]
( cc: @martijnrusschen )

**Comment by puredazzle** [comment]
@yuki0410-dev right! It appears to have been resolved in the most recent version of Preact. Thanks!
