### ISSUE TITLE
extend onChange arguments

### ISSUE THREAD

**Issue by bratva** [Hacker0x01/react-datepicker#458]
Hello!
`onChange` is called with one argument - `date`.
Сan you add second argument to this function, e.g. `formattedDate`? 
```
setSelected (date) {
    if (!isSameDay(this.props.selected, date)) {
      this.props.onChange(date, .date.clone().locale(props.locale || moment.locale()).format(props.dateFormat))
    }
  }
```

**Comment by rafeememon** [comment]
Unfortunately I don't think we should support this -- since `dateFormat` and `locale` are taken in as props, the consumer can format the date themselves using that information.  Calling `onChange` with the moment object is enough information and this becomes API bloat.

**Comment by abdulloooh** [comment]
I think you should support it now.
I am using it as a reusable component thus I need to pass in an extra parameter to differentiate what component called it but I can't do that. Further, I tried to wrap it in a parent component and get it as ```(date,extraArg)=>{this.handleChange(date,extraArg)}```
But at the end, I would only still get the date and extra parameter will read undefined.

Can you please reopen this
