### ISSUE TITLE
Week Picker Skips Months When Decreasing Month from 1st day falling after Fridays

### ISSUE THREAD

**Issue by heyitsashleyhere** [Hacker0x01/react-datepicker#4581]
**Describe the bug**
When decreasing the month using the 'showWeekPicker' prop, it unexpectedly skips February when the current date is set to March 1st, 2024.

**To Reproduce**
1. Visit the [React Datepicker documentation](https://reactdatepicker.com/#example-week-picker) where the WeekPicker demo is featured.
3. Change the date from "2021/02/22" to "2024/03/01"
4. Click on input to open the calendar
5. Click on the '<' (left arrow) to decrease the month

**Expected behavior**
The calendar should display the month of February.

**Desktop (please complete the following information):**
- OS: [iOS]
- Browser [chrome]
- Version [latest]

**Additional context**
This issue occurs in any month where the 1st day falls after Fridays (Fri-Sun)

**Comment by yuki0410-dev** [comment]
I reproduced the same event on my end.

At the stage you selected 2024/03/01,
The `selected` is 2024/02/26, which is the beginning of the week 2024/03/01. The reason for this is that when you open the calendar in step 3, you will see `February 2024`.
If you execute step4 from that state, you will see `January`, one month back from February.
This seems to me to be a fine behavior.

**Comment by heyitsashleyhere** [comment]
Thank you for the clarification. 
I should specify my issue as I understand the behavior you described is when the startDate or selected date is pre-filled. However in scenarios where no date is pre-filled, and the calendar defaults behavior is to show the current date. In such instances, upon attempting to decrease the month, I wouldn't expect it to skip a month directly.

**Comment by yuki0410-dev** [comment]
Thank you for your comment.
I agree that it is a non-intuitive behavior, as I did not understand what happened when I first verified it.

How about the following policy for revision?
- before
    - `selected` (startDate) : Keeps the first date of the week for the selected date.
- after
    - `selected` (startDate) : Keeps the selected date

(@martijnrusschen)
