### ISSUE TITLE
Local build issue

### ISSUE THREAD

**Issue by bekerov** [Hacker0x01/react-datepicker#460]
I'm trying modify my fork, but when build have this error on SPA.
```
es6.promise.js:119 
Unhandled promise rejection Error: 
locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. 
You should disable react-transform-hmr in production by using `env` section in Babel configuration. 
See the example in README: https://github.com/gaearon/react-transform-hmr(…)
```

**Comment by rafeememon** [comment]
Are you able to build the master branch from this repository, not your fork?

**Comment by bekerov** [comment]
yep, im trying build this repo, and have similar issue. 
I think problem with `"transform": "react-transform-hmr",` in `.babelrc`

**Comment by bekerov** [comment]
I found problem in`set NODE_ENV=production`

**Comment by R0nd** [comment]
Experiencing the same issue in production on versions 0.60.0 and up.
