### ISSUE TITLE
Replace onClickOutside with @floating-ui/react

### ISSUE THREAD

**Issue by yuki0410-dev** [Hacker0x01/react-datepicker#4605]
**Is your feature request related to a problem? Please describe.**
@floating-ui/react provides the necessary functions.
https://floating-ui.com/docs/useDismiss

**Describe the solution you'd like**
Replace onClickOutside with @floating-ui/react

**Describe alternatives you've considered**
x

**Additional context**
Unless there is a special reason to do so, it is easier to maintain the library by using the features of the library that have already been installed.

**Comment by martijnrusschen** [comment]
makes sense

**Comment by yuki0410-dev** [comment]
refs #4801
