### ISSUE TITLE
react-frame iframe redering issues

### ISSUE THREAD

**Issue by adamellsworth** [Hacker0x01/react-datepicker#463]
https://github.com/pqx/react-frame

I'm using something like:

```javascript
// react-frame
<Frame styleSheets={['/dist/app-listing.css']}>
    <Listing options={options}/>
</Frame>
```

And within the `<Listing/>` component, I'm using react-datepicker. Note too that app-listing.css has the datepicker styles wrapped into it.

The issue is that it looks like the react-tether attaches itself to the main document's body instead of the iframe's body, and because the css is applied to only the children of the iframe the datepicker is lacking applied styles/positioning.

**Comment by adamellsworth** [comment]
Here's a general idea of what's happening:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        
        <div id="app-mount-node">
            <iframe>
                <!DOCTYPE html>
                <html>
                    <head>
                        <meta charset="utf-8">
                        <title></title>
                        <link src="..." /> <!-- app styles, react-datepicker wrapped into them -->
                    </head>
                    <body> <!-- where react-frame mounts -->
                        <div id="app">
                            <!-- where react-datepicker is used -->
                        </div>

                        <!-- where I'd expect react-datepicker to mount -->
                    </body>
                </html>
            </iframe>
        </div>

        <div class="datepicker__tether-element datepicker__tether-element-attached-left datepicker__tether-target-attached-left datepicker__tether-abutted datepicker__tether-abutted-left datepicker__tether-element-attached-bottom datepicker__tether-target-attached-top datepicker__tether-enabled" style="top: 0px; left: 0px; position: absolute; transform: translateX(424px) translateY(43px) translateZ(0px);"><div class="datepicker" data-reactid=".1">
            <!-- where react-datepicker mounts the DOM -->
        </div>
    </body>
</html>
```

**Comment by rafeememon** [comment]
Can you use the [`renderCalendarTo` prop](https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md)?  The prop takes in a DOM element that the calendar will be attached to, which is `document.body` by default.

**Comment by adamellsworth** [comment]
Ah that did it, thank you. I made the wrapping component  `<div className="row" ref="filter-control">` and set `renderCalendarTo={this.refs['filter-control']}`. Is that a bad way to approach the issue or should I look for the closest `document.body` instead?

**Comment by rafeememon** [comment]
Seems fine to me; personally I'd prefer to give a concrete DOM element rather than making an educated guess by walking up the tree and looking for a `document.body`.
