### ISSUE TITLE
Binding to empty field results to warning

### ISSUE THREAD

**Issue by daletune** [Hacker0x01/react-datepicker#464]
That actually more like a question.
How to bind to field that not set with default value?

When I replace default value (undefined) with empty string it results:
* Warning: Failed propType: Invalid prop `selected` of type `string` supplied to `DatePicker`, expected `object`. Check the render method of `Calendar`.
* Warning: Failed propType: Invalid prop `date` of type `string` supplied to `DateInput`, expected `object`. Check the render method of `DatePicker`.

And for null:
* Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

For undefined:
* DateInput is changing a uncontrolled input of type text to be controlled.

Example is simplified. But when state is taken from e.g. redux and passed throught props the result is the same.
```jsx
var Example = React.createClass({
  displayName: 'Example',

  getInitialState: function() {
    return {
      startDate: undefined
    };
  },

  handleChange: function(date) {
    this.setState({
      startDate: date
    });
  },

  render: function() {
    return <DatePicker
        selected={this.state.startDate}
        onChange={this.handleChange} />;
  }
});
```

**Comment by rafeememon** [comment]
The API that you should use for the default unselected date is `null`.  There are issues with how this is propagated down to the input -- I think react may have gotten pickier about what is passed to an input's value.  [The diff in this open PR](https://github.com/Hacker0x01/react-datepicker/pull/451/files#diff-f65f9484bd16b3defff3087eca6a222f) should fix this going forward by converting null/undefined to the empty string.

**Comment by daletune** [comment]
Thank you @rafeememon, i'll try it.
