### ISSUE TITLE
how to set the datapicker input tag autocomplete off

### ISSUE THREAD

**Issue by gentlythink** [Hacker0x01/react-datepicker#465]
how to set the datapicker input tag  autocomplete attribute  "off"?
It happens when i use the component on ie11 browser. could you help me to solve this problem
![image](https://cloud.githubusercontent.com/assets/2908871/14882932/dd98e604-0d6d-11e6-90aa-2555d62ee815.png)

**Comment by gentlythink** [comment]
![image](https://cloud.githubusercontent.com/assets/2908871/14882895/b298b826-0d6d-11e6-98d6-3b2da3013bbb.png)

**Comment by rafeememon** [comment]
We don't currently support the `autocomplete` attribute but a PR is welcome.

**Comment by rafeememon** [comment]
Added in #489
