### ISSUE TITLE
Input value not set

### ISSUE THREAD

**Issue by preacher2041** [Hacker0x01/react-datepicker#466]
Trying out the basic functionality of the plugin and following the instructions however the input field seems to be blank for me and click on a date of any kind doesn't update it.

Looking in the using devtools it seems that no value attribute is set on the input field.

**Comment by rafeememon** [comment]
Code?  Are you setting the `selected` prop in the DatePicker?

**Comment by preacher2041** [comment]
Yep, I copied and pasted the code from the github example, I'm relatively new to React and to plugins but this particular one will solve the exact problem I have so keen to use it.

**Comment by rafeememon** [comment]
Right, can you paste your app code here?  Hard to debug without full context on what's going on =P

**Comment by preacher2041** [comment]
`var React = require('react');
var DatePicker = require('react-datepicker');
var moment = require('moment');

var Application = React.createClass({
    displayName: 'Example',

    getInitialState: function() {
        return {
            startDate: moment()
        };
    },

    handleChange: function(date) {
        this.setState({
            startDate: date
        });
    },

    render: function() {
        return <DatePicker
            selected={this.state.startDate}
            onChange={this.handleChange} />;
    }
});

module.export = Application;`

moment and react have both been installed via NPM as well as the date-picker itself

**Comment by preacher2041** [comment]
Not sure what I've done but It seems to be working fine now. Thanks for your quick replies, it's a great plugin.

**Comment by rafeememon** [comment]
Cool, glad you were able to get it working!
