### ISSUE TITLE
How to close datepicker when click outside?

### ISSUE THREAD

**Issue by ilya4544** [Hacker0x01/react-datepicker#468]
How to close datepicker when click outside?
I want a standart behaviour.

Thank you.

**Comment by rafeememon** [comment]
This is already the standard behavior of the datepicker

**Comment by ilya4544** [comment]
Unfortunatelly, in my case the datepicker closes only if I press Esc. Can you tell me in which cases it's possible?

**Comment by rafeememon** [comment]
It's hard to say without seeing your code -- it's possible that another plugin is removing/disabling the click handler on the document, which this component relies on to close the picker.

**Comment by njj** [comment]
@ilya4544 Did you ever figure this out?
