### ISSUE TITLE
Unable to run with npm/browserify

### ISSUE THREAD

**Issue by meg2208** [Hacker0x01/react-datepicker#47]
Out of the box this is not working if I just import the package using requireJS/browserify. The external dependencies (React, moment, Tether) are assumed to be globals in the source. @RSO are you aware of this issue? I notice there is another issue https://github.com/Hacker0x01/react-datepicker/issues/42 but not sure how thoroughly tested that was.

**Comment by mattdell** [comment]
I'm aslo having this issue. Would be great to be able to use it this way.

**Comment by MandarinConLaBarba** [comment]
I've submitted a PR for this: https://github.com/Hacker0x01/react-datepicker/pull/81

**Comment by RSO** [comment]
Now that #81 has been landed, I think that this ticket can be closed. Can you confirm?
