### ISSUE TITLE
Is there any way to fix the date-picker to always open below the input element? 

### ISSUE THREAD

**Issue by preacher2041** [Hacker0x01/react-datepicker#470]

**Comment by rafeememon** [comment]
Clobber the `tetherConstraints` prop with `[]` to wipe out the default constraint; relevant pages:
* https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md
* http://github.hubspot.com/tether/

**Comment by gavinpatkinson** [comment]
This is still a problem and tetherConstraints no longer works.

**Comment by Rambobafet** [comment]
Anyone with a solution? Can we reopen this ticket? :)

**Comment by Naggertooth** [comment]
https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#modifiers..flip

Here I found a solution

@rafeememon if you r still working on this - please take a look

**Comment by Gayatri31** [comment]
@Naggertooth The link is not working, provide some text

**Comment by Naggertooth** [comment]
@Gayatri31 guess you need old docs https://github.com/popperjs/popper-core/blob/v1.3.2/docs/_includes/popper-documentation.md#modifiers..flip (first tap, don't know exact ver)
But anyway, solution already might/must be different
I am not the contributor :) so...)

**Comment by maheshsamudra** [comment]
Not sure if it's too late but I was able to fix it by using:

`popperPlacement="bottom"
      popperModifiers={[
        {
          name: "flip",
          options: {
            fallbackPlacements: ["bottom"],
            allowedAutoPlacements: ["bottom"],
          },
        },
      ]}`
