### ISSUE TITLE
Accessibility: Headings

### ISSUE THREAD

**Issue by Ibabalola** [Hacker0x01/react-datepicker#4703]
**Describe the bug**
A heading has been designed as such visually however it is not a heading programmatically.
This instance can be found with the react date modal.
The heading ‘March 2024’ has been written as a div, when it acts as a heading
that introduces related dates that the user can interact with. This means that screen reader
users are not afforded the information and structure that is relayed to users visually.

<img width="470" alt="Screenshot 2024-04-17 at 18 56 19" src="https://github.com/Hacker0x01/react-datepicker/assets/11960286/dd87bfa7-b5e4-4747-8e04-d374dd90c5ef">

**To Reproduce**
1. Open the react date picker via modal or custominput `<button />`

**For example**
```html
#customDiv > div.react-datepicker__portal > div > div > div.react-
datepicker__month-container > div.react-datepicker__header > div.react-
datepicker__current-month
<div class="react-datepicker__current-month">March 2024</div>
```

**Expected behavior**
Ensure that all text which introduces information is marked up as headings and presented in
a logical and hierarchical order. This enables screen reader users to determine the layout of
the page, relationships between content and skip to different sections of the page.
Use the current month and year as a level 2 heading.

```html
#customDiv > div.react-datepicker__portal > div > div > div.react-
datepicker__month-container > div.react-datepicker__header > div.react-
datepicker__current-month
<h2 class="react-datepicker__current-month">March 2024</h2>
```

**Desktop (please complete the following information):**

- OS: iOS Andriod
- Browser chrome, safari
- Version latest

**Smartphone (please complete the following information):**

- Device: all
- OS: latest
- Browser stock browser, safari
- Version latest

**Additional context**
```json
{
"_comment": "package.json"
 "dependancies": {
  "react-datepicker": "6.8.0",
 }
}
```

**Comment by balajis-qb** [comment]
Hi @martijnrusschen , Please assign this issue to me.  I'll work on this.
