### ISSUE TITLE
Extract value prop for use with .serialize()

### ISSUE THREAD

**Issue by preacher2041** [Hacker0x01/react-datepicker#477]
HI,

I'm trying to send the value of the datepicker (along with other form data) to an API using .serilaize() .

When inspecting the input element of the datepicker with standard dev tools I can see the input doesn't have an input field, due to this no data from the date picker is being sent to the API

When inspecting the input element with React tools I can see the input element has a prop of value that contains the date data.

How would / could I extract this value so I can send it to my API?

Many thanks

Lee

**Comment by rafeememon** [comment]
The datepicker displays whatever date you pass into the `selected` prop, so you should already have in hand the value that you'd want to pass to an API.
