### ISSUE TITLE
Support for leap-years

### ISSUE THREAD

**Issue by tysoncadenhead** [Hacker0x01/react-datepicker#478]
The calendar is currently a day off for 2016. It thinks that today (May 6) is a Saturday, but it is actually a Friday.

**Comment by rafeememon** [comment]
From the demo site:

<img width="280" alt="screen shot 2016-05-06 at 7 55 27 pm" src="https://cloud.githubusercontent.com/assets/1829450/15083340/91ed38f6-13c4-11e6-98e6-7bf2294f09bc.png">

Can you give a repro?

**Comment by rafeememon** [comment]
Don't think this is an issue; this was fixed by the moment refactors

**Comment by tysoncadenhead** [comment]
Yep, I was apparently stuck on an old version. It's not an issue in the current version. Thanks!
