### ISSUE TITLE
Input blur after date select

### ISSUE THREAD

**Issue by MardanovaA** [Hacker0x01/react-datepicker#4844]
Date picker does not blur input after date select. 

**Steps to reproduce the behavior:**

1. Go to https://reactdatepicker.com//#example-default
2. Click on date input field
3. Select any date
4. Calendar closes, but input stay focused.

**Expected behavior**
Calendar closes, input blurs.

**Even worse:**
5. Go to another browser tab
6. Return to date picker tab
7. Calendar is open.
**Expected behavior**
Calendar is closed

I set handleBlur function for onBlur, onSelect and onCalendarClose events. I think, that input loses focus for a split second, after executing itCalendarCloses, but then comes into focus again

```
const handleBlur = () => {
   pickerRef.current?.input?.blur(); // it doesn't work
  
  setTimeout(() => {
        pickerRef.current?.input?.blur(); // it is works
  }, 1000);
};
```

Any help how can I control input focus, please?

**Comment by balajis-qb** [comment]
I'll look into this issue
