### ISSUE TITLE
how far is this from fullcalendar

### ISSUE THREAD

**Issue by brw31415** [Hacker0x01/react-datepicker#485]
hi,

i would like to use this , but the features currently in fullcalendar jquery plugin, like the week and day views, how far is this from that? i'm just learning react. thanks

**Comment by rafeememon** [comment]
I'm not familiar with the jquery plugin, but you can check out the demo site to see if this meets your needs: https://hacker0x01.github.io/react-datepicker

**Comment by brw31415** [comment]
if you are intereted:
http://fullcalendar.io/

it is very popular
