### ISSUE TITLE
Option "required" should be typed as a boolean, not as a string

### ISSUE THREAD

**Issue by alexey-m-ukolov** [Hacker0x01/react-datepicker#4899]
**Describe the bug**
Commit [#6fe84be](https://github.com/Hacker0x01/react-datepicker/commit/6fe84be16bb9bafc6ccf498249b0b5abb44f93ea#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R186) introduced `DatePickerProps` type in which the `required` property is typed as a string.

**Expected behavior**
This option should be typed as a boolean as it stated in [the docs](https://github.com/Hacker0x01/react-datepicker/blob/main/docs/datepicker.md).

**Comment by tomekpiwowar** [comment]
I agree with @alexey-m-ukolov.
Even though the DatePicker component itself is not a form element, the required attribute is typically used in the context of form validation and its expected type in HTML is boolean.
