### ISSUE TITLE
Datepicker overflows out of viewport

### ISSUE THREAD

**Issue by rubenswieringa** [Hacker0x01/react-datepicker#4900]
_(lmk if this is intended behavior; I couldn’t find this in breaking changes)_

**Describe the bug**
Datepicker doesn’t automatically get contained within the viewport anymore.

**To Reproduce**

1. Add a datepicker with no properties on the left- or rightmost side of the viewport:
    ```
    <Datepicker />
    ```
3. Ensure input-field is less wide than datepicker, for example:
    ```
    .react-datepicker-wrapper input {
      width: 20px
    }
    ```
4. Click input-field to open datepicker

**Expected behavior**
In older* versions, the datepicker would automatically stay within the bounds of the viewport.

\* Admittedly I was on a very old (v4) version before updating to v7 just now. I’m not sure what the default behavior was in v5 or 6.

**Screenshots**

<img width="220" alt="Screenshot 2024-06-14 at 11 50 09" src="https://github.com/Hacker0x01/react-datepicker/assets/1004287/78c2a877-157b-413d-bfce-cf4eaa80d867">

**Workaround**
Give a value to the `popperPlacement` property:
```
<Datepicker popperPlacement="bottom-end" />
```

Note that only `"popperPlacement="bottom"` won’t keep the datepicker from overflowing horizontally.

**Versions**
- react-datepicker 7.0.0
- MacOS 14.5
- Firefox 126 & Chrome 124

**Additional comments**

Great work on the new major release guys, I’m sorry to be the first to open a ticket (and so soon).

**Comment by yuki0410-dev** [comment]
@rubenswieringa 
react-datepicker was changed in some version of v4-v6 to rely on floating-ui instead of popper.
Because the detailed behavior can be controlled by the popperModifiers props,
Why not use shift?
https://floating-ui.com/docs/shift

If it doesn't work, please provide some sample code and I may be able to advise otherwise.

**Comment by rubenswieringa** [comment]
@yuki0410-dev That did the trick – thanks for the quick reply (and sorry for my late one). Will close this issue now.

**Comment by CoreyCole** [comment]
> @yuki0410-dev That did the trick – thanks for the quick reply (and sorry for my late one). Will close this issue now.

can you share the code you got this to work? this does not fix it for me:
```typescript
import { shift, flip } from '@floating-ui/dom';
import { shift, flip } from '@floating-ui/dom';

// ...
popperModifiers={[shift(), flip({ padding: 5 })]}

```
<img width="341" alt="image" src="https://github.com/Hacker0x01/react-datepicker/assets/4467106/7929a84b-b5a9-48c1-9bb7-2546fa7d920e">

am I using incorrectly?

**Comment by rubenswieringa** [comment]
In the end I just used `popperPlacement="bottom-end"` because my anchoring element was always at the right-most side of the screen, but my offset modifier might help you figure the syntax out:

```
<DatePicker
  popperPlacement="bottom-end"
  popperModifiers={[{ name: 'offset', fn: ({ y }) => ({ y: y + 5 }) }]}
/>
```

Also, have a look at the code sample for configuring the Popper/FloatingUI bits in the API docs:

https://reactdatepicker.com/#example-configure-floating-ui-properties

**Comment by Jollus174** [comment]
In case anybody else runs into a similar problem and needs to modify popper modifiers, I ran into a similar issue where I wanted the popper to not flip when it reaches the bounds of the screen. This is what I used:
```
<DatePicker
  popperPlacement="bottom-start"
  popperModifiers={[
    {
      name: 'remove-flip',
      fn: () => ({ reset: { placement: 'bottom-start', rects: true } })
    }
  ]}
/>
```

**Comment by nickredmark** [comment]
In case anyone else lands here who would appreciate more examples of how to use floating ui with this component, here is one:

<DatePicker
  popperModifiers={[offset({ mainAxis: 5 )}]}
/>
