### ISSUE TITLE
onChangeRaw differently typed in v7.0.0

### ISSUE THREAD

**Issue by sm3sher** [Hacker0x01/react-datepicker#4901]
**Describe the bug**
After updating to the newest types included version (`7.0.0`) `onChangeRaw` seems to be typed differently than before.

In `@types/react-datepicker` it was typed like this:
```
onChangeRaw: (event: React.FocusEvent<HTMLInputElement>) => void;
```
But in the latest version this has changed:
```
onChangeRaw: (event?: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>) => void;
```

The problem here is that neither `React.MouseEvent` nor `React.KeyboardEvent` provide the `target` as `HTMLInputElement` even though the target seems to be of type `HTMLInputElement`. This leads to `event.target.value` being invalid typescript.

My current workaround is to access the value via `(event.target as HTMLInputElement).value` but I would hope for a better solution.

**To Reproduce**
1. Install the latest version 7.0.0
2. Make use of onChangeRaw in a TS environment
3. Try accessing `event.target.value`
4. See TS error

**Expected behavior**
`onChangeRaw` should provide the correct types or at least none that are in conflict with `@types/react-datepicker`.

**Desktop (please complete the following information):**

- OS: macOS 14.5
- Browser: Chrome
- Version: 125

**Comment by balajis-qb** [comment]
I'll look into this issue

**Comment by sm3sher** [comment]
You are indeed correct.

So far I've been filtering out the Day Component selection and click events by checking if `(e.target.value !== undefined)` to ensure I am working with an `HTMLInputElement`.

I will give it a try with `instanceof` check.

**Comment by yuki0410-dev** [comment]
@sm3sher ( cc. @martijnrusschen  )
Are there any outstanding issues regarding this issue?

**Comment by sm3sher** [comment]
None that I know of. I am closing this issue.
