### ISSUE TITLE
Uncaught TypeError: t.date.clone is not a function ReactClass.js:659 

### ISSUE THREAD

**Issue by abhaytalreja** [Hacker0x01/react-datepicker#491]
Whenever i add a `selectedDate` value i am getting this error in the browser console.

Please note, if i remove the selectedDate the date picker works, but when i do a selection no date shows up!

Steps: 

1) `npm install react-datepicker --save`
2) `var DatePicker = require('react-datepicker');`
3) 
```
<DatePicker
			    selected={this.state.startDate}
			    onChange={this.handleChange.bind(this)} 
			    showYearDropdown 
			    dateFormatCalendar="MMMM" />
```

**Comment by abhaytalreja** [comment]
I figured the problem was that i was using 
```
this.state = {
  startDate: new Date(),
}
```
I think we need to use
```
this.state = {
  startDate: moment(),
}
```

**Comment by rafeememon** [comment]
The `selected` property takes in [moment.js](http://momentjs.com/) date objects, so passing in an object instead should solve the problem

**Comment by SalTor** [comment]
Why does selected take moment.js date objects if moment usage in react-datepicker was meant to be phased out?

**Comment by rafeememon** [comment]
This issue is nearly three years old =( The `selected` prop [now takes a `Date`](https://github.com/Hacker0x01/react-datepicker/blob/164d10d81e215f745650f128a0ca756de7d80f3c/src/index.jsx#L134) as of v2.
