### ISSUE TITLE
excludScrollbar an optional property

### ISSUE THREAD

**Issue by lordenas** [Hacker0x01/react-datepicker#4922]
**Describe the bug**
excludeScrollbar - should be an optional property in DatePickerProps

**To Reproduce**
https://codesandbox.io/p/sandbox/datepickerprops-92df8r?file=%2Fsrc%2FApp.tsx

I want to make a wrapper for a component. To pass all its properties I use DatePickerProps from the react-datepicker import. 
But the excludeScrollbar property should be an optional property

**Expected behavior**
excludeScrollbar - should be an optional property in DatePickerProps

**Comment by yuki0410-dev** [comment]
@lordenas
Would this page be helpful? (It seems to be a glitch in ts.)
https://stackoverflow.com/questions/78641187/why-is-excludscrollbar-property-required-for-react-datepicker

When reproducing it at hand, I forked codesandbox, but the type error is not occurring for some reason.
https://codesandbox.io/p/sandbox/datepickerprops-forked-vzwr86

Would bringing ts up to date improve this?

**Comment by lordenas** [comment]
> @lordenas Would this page be helpful? (It seems to be a glitch in ts.) https://stackoverflow.com/questions/78641187/why-is-excludscrollbar-property-required-for-react-datepicker
> 
> When reproducing it at hand, I forked codesandbox, but the type error is not occurring for some reason. https://codesandbox.io/p/sandbox/datepickerprops-forked-vzwr86
> 
> Would bringing ts up to date improve this?

It's strange, but I still see the error in CodeSandox
<img width="774" alt="image" src="https://github.com/Hacker0x01/react-datepicker/assets/15974195/0ea130b6-ad3b-4038-a8b1-02da5b830b26">
