### ISSUE TITLE
CSS not applied onto TetherComponent

### ISSUE THREAD

**Issue by itphixl** [Hacker0x01/react-datepicker#493]
Hi !
I'm currently using the 0.27.0 and I've a weird problem. 
I've no css class applied to the TetherComponentt and I don't understand why. 
I can see the class 'react-datepicker__input-container' but not the others who I think, if I believe the demo, should be applied.

Can you help us ?

Thanks a lot, 
PhiXL team.

**Comment by itphixl** [comment]
Oh okay after some research I've found why. My bad, sorry for disturbing you :)

PhiXL team.

**Comment by evilemon** [comment]
encounter the same problem

the css is not applied
