### ISSUE TITLE
  Type '{ label: string; elected: Date; onChange: (date: Date) => void; }' is missing the following properties ts(2322) in version 7.2

### ISSUE THREAD

**Issue by Ofer-Gal** [Hacker0x01/react-datepicker#4945]
**Describe the bug**
TypeScript complains about optional properties in VSCode.

**To Reproduce**
`<DatePicker label="Select Start Date/Time (Optional) " elected={startDate} onChange={handleChange}  />`
Causes TS error:
`Type '{ label: string; elected: Date; onChange: (date: Date) => void; }' is not assignable to type 'IntrinsicAttributes & (IntrinsicClassAttributes<DatePicker> & (Readonly<DatePickerProps> & Readonly<...>))'.
  Type '{ label: string; elected: Date; onChange: (date: Date) => void; }' is missing the following properties from type 'Readonly<Omit<React.ComponentPropsWithoutRef<typeof Calendar>, "setOpen" | "dateFormat" | "preSelection" | "onSelect" | "onClickOutside" | "highlightDates" | "holidays" | "shouldFocusDayInline" | "outsideClickIgnoreClass" | ... 11 more ... | "dropdownMode"> & ... 5 more ... & { ...; }>': excludeScrollbar, icon, onSelect, selectsMultiple ts(2322)
`
**Expected behavior**
When I use older version, it does not complain.
Where the error in new version reaten in TS 

**Screenshots**

![image](https://github.com/Hacker0x01/react-datepicker/assets/5054931/d94132e7-27f2-46ac-9b0a-42c585238c01)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome, Edge]
- Version [7.2]

Is there esLint override I can use?

Thank you

**Comment by yuki0410-dev** [comment]
@Ofer-Gal 
I was able to reproduce it with codesandbox.
https://codesandbox.io/p/sandbox/react-datepicker-4945-zkv4ns?file=%2Fsrc%2FApp.tsx%3A14%2C54

Since there are no label props in DatePicker, please remove them or use the appropriate props.
https://github.com/Hacker0x01/react-datepicker/blob/main/docs/datepicker.md

**Comment by Ofer-Gal** [comment]
Thanks
