### ISSUE TITLE
Datepicker jumps unexpectedly on small screens

### ISSUE THREAD

**Issue by griffinmyers** [Hacker0x01/react-datepicker#496]
Greetings!  Thank you kindly for putting together the nice datepicker.  An issue I've noticed: 

the datepicker modal bounces around vertically in unexpected ways when the height of the screen is small.  I've attached some pictures to document the weirdness.  Would be happy to pitch in on a fix and am curious what your thoughts are!  

Thank you!

![screen shot 2016-05-27 at 12 27 10 pm](https://cloud.githubusercontent.com/assets/1980044/15614430/bb2e0f9a-2406-11e6-80b3-424fd068b735.png)
![screen shot 2016-05-27 at 12 27 20 pm](https://cloud.githubusercontent.com/assets/1980044/15614431/bb332cb4-2406-11e6-86b8-7367546257a2.png)
![screen shot 2016-05-27 at 12 27 14 pm](https://cloud.githubusercontent.com/assets/1980044/15614429/bb2d93e4-2406-11e6-9d15-bf707c73a69f.png)

**Comment by rafeememon** [comment]
Hey @griffinmyers, I think this is because of the way the tether library is configured to try to keep the datepicker on the screen as the user scrolls.  Maybe you can work around this by trying the solution here: https://github.com/Hacker0x01/react-datepicker/issues/470

**Comment by griffinmyers** [comment]
thanks @rafeememon!  Sorry I couldn't get my search query quite right to find this on my own.
