### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by flyalex** [Hacker0x01/react-datepicker#500]
Hi!

I am passing moment object from my component state to data picker, and I have set dateFormat="DD/MM/YYYY", however data picker "selected" recognizes my date as MM/DD/YYYY. For example when my state has 06/05/2016 (06 May 2016)
data picker shows 05/06/2016 (05 Jun 2016) instead.

Seems like this string dateFormat="DD/MM/YYYY" doesn't affects on date format of picker.

How can I fix it?

Thank you!

**Comment by rafeememon** [comment]
Are you able to paste your code or create an example page that shows the problem?  The [demo site](http://hacker0x01.github.io/react-datepicker/) gives an example of this that maybe you can model your code after.

**Comment by gor181** [comment]
I have just tried on 0.28.0 and it works without issues.
@rafeememon keep in mind that date format should be uppercase for moment to parse it as 'DD/MM/YYYY' or similar. Check moment docs for format options it accepts.

**Comment by rafeememon** [comment]
@gor181 yep, this is what the demo site shows and what @flyalex described.

Closing for lack of additional info

**Comment by syam1123** [comment]
Nowhere in the demo it's showing the format of 'DD/MM/YYYY'
For me also when I'm giving format 'DD/MM/YYYY', it's automatically changing to 'MM/DD/YYYY' and suppose if I'm selected '23/05/2016', it's changing to '05/23/2016' and suddenly to 'Invalid date'.
here is the code:

`<DatePicker {...input} placeholderText="YYYY-MM-DD" dateFormat="DD/MM/YYYY" className="form-control"
              fixedHeight
              selected={selectedDate}
              isClearable={true}
              showYearDropdown />`
