### ISSUE TITLE
The date-fns locale object is not aligned with what registerLocale expects for LocaleObj.

### ISSUE THREAD

**Issue by l5ss5l** [Hacker0x01/react-datepicker#5000]
**Describe the bug**
Argument of type 'typeof import("web/node_modules/date-fns/locale/nl")' is not assignable to parameter of type 'LocaleObj'.
  Type 'typeof import("/web/node_modules/date-fns/locale/nl")' is missing the following properties from type 'Pick<Locale, "options" | "formatLong" | "localize" | "match">': formatLong, localize, match

**To Reproduce**
`import nl from 'date-fns/locale/nl'`;
`import { registerLocale } from 'react-datepicker'`;
`registerLocale('nl', nl);`

**Screenshots**
![Screenshot 2024-07-22 at 15 55 54](https://github.com/user-attachments/assets/b3f77b4e-37e2-4ecb-8f49-3418af2c5f1a)

 "dependencies": {
   "react-datepicker": "^7.3.0",
    "date-fns": "^3.6.0",
}

**Comment by adik7960** [comment]
How you solved this problem?
