### ISSUE TITLE
Lib added to a CDN

### ISSUE THREAD

**Issue by ehkasper** [Hacker0x01/react-datepicker#501]
Hey, I do not know if this is the best way to do it, but I just wanted to let you know that this lib has been added to CDNJS. Please see: https://cdnjs.com/libraries/react-datepicker

I thought of creating a PR altering the README file to include this information, but it is totally up to maintainers to decide whether its worth or not.

Thanks for your work!

**Comment by martijnrusschen** [comment]
Hi @ehkasper, thanks for letting us know! We would welcome a PR if you have time to add it.

**Comment by ehkasper** [comment]
Sure. It is there.

**Comment by rafeememon** [comment]
@ehkasper, @martijnrusschen, my concern is that if we advertise the CDN links they should always be the up-to-date version, and currently releasing to the CDN is not in the release process.  I'm also not sure if this is long-term supportable as I think the vast majority of consumers use module bundlers, where reading from a CDN doesn't make much sense.  What do you think?

**Comment by martijnrusschen** [comment]
Agreed. Thinking about this, it might be nice to show display this somewhere in the readme, but it sounds to complicated to incorporate this into the release process.

**Comment by ehkasper** [comment]
@rafeememon I understand you concern. CDNJS has [enabled autoupdate](https://cdnjs.com/libraries/react-datepicker) (Check the badge at the top). The only thing to change as a new tag comes in is this README with the version (currently is the 0.27 one).

**Comment by martijnrusschen** [comment]
Sorry, so I need to change the badge every time I roll out a new release?

**Comment by ehkasper** [comment]
No need. The only info to be changed in every release is the version on README. For instance, the URL is `https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/0.27.0/react-datepicker.css`. When updating to 0.28 you should also update the URL in the README to `https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/0.28.0/react-datepicker.css`.

**Comment by damlu** [comment]
Hmm, maybe instead of having the resource URLs in the README which need to be updated every version, you could just link to the CDNJS library page, which looks to have auto-updated resource URLs: [https://cdnjs.com/libraries/react-datepicker](https://cdnjs.com/libraries/react-datepicker)

That way people can access the up-to-date resource URLs without any additional work required by Martjin et al.

**Comment by ehkasper** [comment]
sounds good. What about this message:
```
### CDN
The folks at [CDNJS](https://cdnjs.com/) graciously provide CDN support for React Datepicker's CSS and JavaScript: [https://cdnjs.com/libraries/react-datepicker](https://cdnjs.com/libraries/react-datepicker)
```

**Comment by ankibalyan** [comment]
After including the lib from CDN, `ReferenceError: DatePicker is not defined` in plunker.
How to define that?

**Comment by ehkasper** [comment]
@ankibalyan did you include `https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/0.41.1/react-datepicker.min.js` or any other versions?

**Comment by sfentress** [comment]
@ehkasper Is there an example of this working from the CDN build?

I tried to make a simple example here: https://jsfiddle.net/6bhhqrwd/, (forked from a working React example https://jsfiddle.net/reactjs/69z2wepo/), which includes react, moment, and the react-datepicker css and js files, and I get the error

        Uncaught TypeError: (0 , _reactOnclickoutside2.default) is not a function
            at Object.module.exports (react-datepicker.js:1003)
            at __webpack_require__ (react-datepicker.js:30)
            at Object.module.exports (react-datepicker.js:573)
            at __webpack_require__ (react-datepicker.js:30)
            at Object.defineProperty.value (react-datepicker.js:65)
            at __webpack_require__ (react-datepicker.js:30)
            at Object.defineProperty.value (react-datepicker.js:50)
            at react-datepicker.js:53
            at webpackUniversalModuleDefinition (react-datepicker.js:9)
            at react-datepicker.js:10
        fiddle.jshell.net/:4 Uncaught ReferenceError: DatePicker is not defined
            at eval (eval at transform.run (browser.js:5811), <anonymous>:4:37)
            at Function.transform.run (browser.js:5811)
            at exec (browser.js:5866)
            at runScripts (browser.js:5903)

**Comment by ehkasper** [comment]
@sfentress I suppose your jsfiddle isnt handling requirejs properly. Have a look here: https://codesandbox.io/s/k5Onp9xjN. You can see the CDN dependency in the left.

**Comment by justinbc820** [comment]
@ehkasper Looking at the webpack.config.js for your project, you have react-onclickoutside listed as an external dependency, so it's not being built into your final webpack bundle. Is that expected behavior?

You specify that react and moment are not built into the project, but don't mention anything about react-onclickoutside.

Thanks

**Comment by ehkasper** [comment]
@justinbc820 I suppose these dependencies should be handled individually in each project. The CDN only includes the react-datepicker bundle.
