### ISSUE TITLE
React-datepicker,Trying to implement start date and end date but  date picker initializes twice

### ISSUE THREAD

**Issue by ranjan653** [Hacker0x01/react-datepicker#502]
DatePicker id="effDate"    id={id} dateFormat = "YYYY-MM-DD"    selected={moment(new Date(caseData.EFF_DT))}  maxDate = {moment(new Date(caseData.DIS_DT))} onChange={this.changeEffDt}  onClick={this.handleBodyClick} ref="effInput"   autoFocus={focus}  

DatePicker2 id="disDate"   dateFormat = "YYYY-MM-DD"    selected={moment(new Date(caseData.DIS_DT))} onChange={this.changeDisDt}  minDate = {moment(new Date(caseData.EFF_DT))} onClick={this.handleBodyClick} ref="disInput"

**Comment by ranjan653** [comment]
Please help me

**Comment by rafeememon** [comment]
I'm not sure what you mean by initializes twice -- what is the problem you are seeing?

**Comment by ranjan653** [comment]
If i click on the first text box date picker comes, and if click on the second text box the first date picker does not hide

**Comment by rafeememon** [comment]
Are you seeing the same problem on the demo site?

**Comment by ranjan653** [comment]
onClickOutside: this.handleCalendarClickOutside, 
this method invokes but unable to close the date picker 
handleCalendarClickOutside: function handleCalendarClickOutside(event) {
	    this.setOpen(false);
	  },
it always returns true. Please help me how to close the date picker on click outside

**Comment by ranjan653** [comment]
hi @rafeememon  could you plz help me out

**Comment by ranjan653** [comment]
hi @dmnd @natlownes @brendannee @dcousineau  is there any one who can help me out

**Comment by ranjan653** [comment]
hi each time this method call s

 handleBlur: function handleBlur(event) {
	    if (this.state.open) {
	      this.refs.input.focus();
	    } else {
	      this.props.onBlur(event);
	    }
	  },


on click datepicker and outside datepicker

**Comment by chadwilken** [comment]
Im also getting this, if you select a value, then reselect the same box but now attempt to click into another input field. It will change the focus back to the date selector and open the calendar.

**Comment by mrchief** [comment]
@ranjan653 Please take a moment to format your messages. Its hard to read through code and messages all mixed up.
