### ISSUE TITLE
feature request: option to set timezone

### ISSUE THREAD

**Issue by katiepeters** [Hacker0x01/react-datepicker#507]
Please correct me if I missed something, but it looks like you can't currently make the DatePicker component use a different timezone than the one local to the user. Maybe switch to using moment-timezone and provide an optional prop that lets us set a timezone?

I'm working on an app where the calendar needs to be viewed in time local to a geographic location that might be different than the user's location. But the component doesn't take this into account.

So for example, the geographic location is New York, but the user is in China. 'Today' in the calendar will be one day ahead of what it should be since China is so far ahead time-wise.

**Comment by rafeememon** [comment]
Think this is a similar request to #498

**Comment by martijnrusschen** [comment]
This should be possible now.

**Comment by vazbloke** [comment]
Since the move from `moment` to `date-fns`, how can this be done now?

**Comment by QinBa** [comment]
> Since the move from `moment` to `date-fns`, how can this be done now?

I believe you can use `utcToZonedTime` from `date-fns-tz` to specify a user defined timezone
```
import { utcToZonedTime } from 'date-fns-tz'

   <DatePicker
      selected={utcToZonedTime(date, 'America/Los_Angeles') }
  />
```
