### ISSUE TITLE
When i close react-datepicker inside a modal its close the modal

### ISSUE THREAD

**Issue by CusProjects** [Hacker0x01/react-datepicker#509]
`
import React from 'react';
import Rebase from 're-base';
import Select from 'react-select';
import {ModalContainer, ModalDialog} from 'react-modal-dialog';
import DatePicker from 'react-datepicker';

import Util from '../services/Util.js';

const base = Rebase.createClass('https://aiolostest.firebaseio.com')
class RateQuotations extends React.Component{

	constructor(props){
		super(props);
		this.componentWillMount = this.componentWillMount.bind(this);
		this.componentDidMount = this.componentDidMount.bind(this);
		this.handleClickModal = this.handleClickModal.bind(this);
		this.handleCloseModal = this.handleCloseModal.bind(this);
		this.handleHarborsOrigin = this.handleHarborsOrigin.bind(this);
		this.handleHarborsDestination = this.handleHarborsDestination.bind(this);
 		
	}

	componentWillMount(){

		base.fetch('harbors', {
		    context: this,
		    asArray: true,
		    then(data){
		      this.setState({harbors: Util.castToSelect(data)});
		    }
		});
	}

	componentDidMount(){
		this.setState({isShowingModal: false});
	}

	handleClickModal(){
		this.setState({isShowingModal: true});
	}
	
	handleCloseModal(){
		console.log("HELLO ITS COLSE");
		this.setState({isShowingModal: false});
	}

	handleHarborsOrigin(val){
		this.setState({'selectedHarborOrigin': val});
	}
	handleHarborsDestination(val){
		this.setState({'selectedHarborDestination' : val});
	}
	handleDate(val){
		console.log(val);
	}

	render() {

		if(this.state){

			
			let harbordSelectOrigin = (
				<Select 
					ref="stateSelect" autofocus name="selected-state"
	      			options={this.state.harbors} simpleValue  
	      			value={this.state.selectedHarborOrigin} 
	      			onChange={this.handleHarborsOrigin} 
	      			searchable={true} 
	      			placeholder={"Harbor"}
	      		/>
			);

			let harbordSelectDestination = (
				<Select 
					ref="stateSelect" autofocus name="selected-state"
	      			options={this.state.harbors} simpleValue  
	      			value={this.state.selectedHarborDestination} 
	      			onChange={this.handleHarborsDestination} 
	      			searchable={true} 
	      			placeholder={"Harbor"}
	      		/>
			);

			return <a onClick={this.handleClickModal}>RATE QUOTATIONS
			  {
			    this.state.isShowingModal &&
			    <ModalContainer onClose={this.handleCloseModal}>
			      <ModalDialog onClose={this.handleCloseModal}>
			    	
			       
			    	<form  className="form login-form" role="form">

			    		<h1> Rate Quotations</h1>
			    		<div className="col-md-12 no-padding">

				    		<h3>Origin</h3>
				    		<div className="col-md-3 no-padding">
					      		<select  className="form-control custom-select" placeholder="Door">
					      			<option>Door</option>
					      			<option value={'port'}>Port</option>
					      		</select>
					      	</div>
					      	<div className="col-md-3 no-padding">
					      		{harbordSelectOrigin}
					      	</div>
					      	<div className="col-md-6 no-padding">
					      		<textarea className="form-control custom-input" placeholder="Address" />
					      	</div>

					      	<h3>Destination</h3>
				    		<div className="col-md-3 no-padding">
					      		<select  className="form-control custom-select" placeholder="Door">
					      			<option>Door</option>
					      			<option value={'port'}>Port</option>
					      		</select>
					      	</div>
					      	<div className="col-md-3 no-padding">
					      		{harbordSelectDestination}
					      	</div>
					      	<div className="col-md-6 no-padding">
					      		<textarea className="form-control custom-input" placeholder="Address" />
					      	</div>
				 
				      		<h3>Commodity</h3>
					      	<textarea className="form-control custom-textarea" placeholder="What are you shipping?" ></textarea>

					      	<h3>Hazardouz?</h3>
					      	<input type="checkbox" className="form-control"/> 

					      	<h3>Incoterm</h3>
					      	<select className="form-control custom-select" placeholder="Iconterm">
					      		<option>EXW - Ex Works (named place of delivery) </option>
					      		<option>FCA - Free Carrier (named place of delivery)</option>
					      	</select>

					      	<h3>Equipment</h3>
					      	<select className="form-control custom-select" placeholder="Iconterm">
					      		<option>Dry Cargo Container </option>
					      		<option>Special</option>
					      	</select>

					      	<select className="form-control custom-select" placeholder="Iconterm">
					      		<option>Select your especial Equipoment </option>
					      		<option>20' Full Height Open Top Container</option>
					      	</select>

					      	<h3>Frecuency</h3>

					      	<div className="col-md-3 ">
					      		<div className="radio">
							  		<label><input type="radio" name="equipment" />{' '} One Time</label>
								</div>
					      	</div>
					      	
							<div className="col-md-2 no-padding">
							 	<div className="radio">
							  		<label><input type="radio" name="equipment" />{' '} Weekly</label>
								</div>
							</div>

							<div className="col-md-2 no-padding">
							 	<div className="radio">
							  		<label><input type="radio" name="equipment" />{' '} Monthly</label>
								</div>
							</div>

							<div className="col-md-2 no-padding">
							 	<div className="radio">
							  		<label><input type="radio" name="equipment" />{' '} Yearly</label>
								</div>
							</div>
							
							<div className="col-md-3 no-padding">
							 	
								<DatePicker
								  
								    onChange={this.handleDate} />	

							</div>
						
				      	</div>

				      	<select className="form-control custom-select" placeholder="Account type"> 
				      		<option>Please select</option>
				      		<option value={'Cliente (Shipper - Consignee)'}>Cliente (Shipper - Consignee)</option>
				      		<option value={'Foright Forwarder'}>Foright Forwarder</option>
				      	</select>

				      	<input  className="form-control custom-input" placeholder="E-mail"/>

				      	
				      	<textarea className="form-control custom-textarea" placeholder="banking information" ></textarea>

						<input ref="inputLogo" className="form-control custom-input" type="file" id="exampleInputFile" onChange={this.handleUploadImage} accept=".png, .jpg, .jpeg"/>

						<textarea className="form-control custom-textarea" placeholder="Consigment Instructions" ></textarea>

				      	<input className="form-control custom-input last-input " placeholder="Password"/>

				       

						<br/>
				      	<button type="submit" className="btn btn-info btn-accent btn-block">Save</button>
			      	</form>

			      </ModalDialog>
			    </ModalContainer>
			  }
			</a>;
		}else{
			return(
				<p> Loading... </p>
			)
		}
 	}

}

export default RateQuotations;
`

**Comment by mayrsascha** [comment]
Probably related to #488

**Comment by rafeememon** [comment]
Yeah looks to be the same, closing as a duplicate
