### ISSUE TITLE
Your webpage https://reactdatepicker.com/ is down - it is totally blank

### ISSUE THREAD

**Issue by roseKQ** [Hacker0x01/react-datepicker#5126]
Your web page with your documentation is down / blank

 - Go to https://reactdatepicker.com/
 - See blank webpage

![Screenshot 2024-09-25 at 10 03 21](https://github.com/user-attachments/assets/ee6e8c3d-eda1-4d2f-97fe-1248b8945a69)
 Tested on

 - latest chrome 
 - Latest chrome incognito
 - Firefox
 - Safari

**Comment by BreakBB** [comment]
Duplicate of #5108

**Comment by martijnrusschen** [comment]
duplicate of https://github.com/Hacker0x01/react-datepicker/issues/5108
