### ISSUE TITLE
portal.d.ts is missing from package on npm with v7.4.0

### ISSUE THREAD

**Issue by johansigfrids** [Hacker0x01/react-datepicker#5129]
The dist/portal.d.ts file with the type definitions for the portal.tsx file is missing from the package on npm.

I upgraded to v7.4.0 and ran tsc --noEmit to type check my project that uses react-datepicker. This gives the following type errors:

```
> tsc --noEmit

node_modules/react-datepicker/dist/index.d.ts:6:20 - error TS2307: Cannot find module './portal' or its corresponding type declarations.

6 import Portal from "./portal";
                     ~~~~~~~~~~

node_modules/react-datepicker/dist/popper_component.d.ts:2:20 - error TS2307: Cannot find module './portal' or its corresponding type declarations.

2 import Portal from "./portal";
```

Checking the `node_modules/react-datepicker/dist/` folder I can confirm that the portal.d.ts file is not included.

Looking at my package-lock.json file the specific version I am using is:

```
    "node_modules/react-datepicker": {
      "version": "7.4.0",
      "resolved": "https://registry.npmjs.org/react-datepicker/-/react-datepicker-7.4.0.tgz",
      "integrity": "sha512-vSSok4DTZ9/Os8O4HjZLxh4SZVFU6dQvoCX6mfbNdBqMsBBdzftrvMz0Nb4UUVVbgj9o8PfX84K3/31oPrTqmg==",
      "dependencies": {
        "@floating-ui/react": "^0.26.23",
        "clsx": "^2.1.1",
        "date-fns": "^3.6.0",
        "prop-types": "^15.8.1"
      },
      "peerDependencies": {
        "react": "^16.9.0 || ^17 || ^18",
        "react-dom": "^16.9.0 || ^17 || ^18"
      }
    },
```

I manually downloaded the `https://registry.npmjs.org/react-datepicker/-/react-datepicker-7.4.0.tgz` and poked around inside to verify the file is indeed missing.

**Comment by vladyslavgeyna** [comment]
@martijnrusschen I've faced with the same issue. The portal is missed in the node_modules and it causes too many types issues.
