### ISSUE TITLE
filterDate not working.

### ISSUE THREAD

**Issue by diffractometer** [Hacker0x01/react-datepicker#513]
Hi,

`filterDate={this.isWeekday}` is not working for me. Is anyone else having the same issue? I'm on 0.27.0. No errors in the console.

Thanks!

**Comment by rafeememon** [comment]
Can you elaborate on what you mean by "not working?"  Throw in some `console.log`s to see what's going on, and possibly paste your code so we can see what you're doing.

**Comment by rafeememon** [comment]
Closing for lack of info/activity
