### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dkan** [Hacker0x01/react-datepicker#516]
Hey,

Im trying to use the inline feature that was merged into master. It looks like the npm package has not been updated. Can you guys update the latest release on npm to include the latest changes on master.

Thanks!

**Comment by martijnrusschen** [comment]
Give me a sec

**Comment by martijnrusschen** [comment]
Here you go https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.28.0
