### ISSUE TITLE
Potential Suggestion - Give us the component thats not mounted when we try and call setState

### ISSUE THREAD

**Issue by AdamKyle** [Hacker0x01/react-datepicker#518]
So have you ever come across the whole "we cannot set state because component is unmounted?"

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

Is it possible, and I haven't dug too deep into the source code, to say: "Yo! This component: `SomeComponent` is trying to call setState, and isn't mounted."

When you have 6 or seven components all being put together to form the page or the app or what ever and one of them is causing this issue (programmer error), its pretty hard to figure out which one it is.

**Is this possible?**

**Comment by avk** [comment]
@AdamKyle this is a standard React error. The stack trace in console should help you see which component the `setState` call is coming from.

**Comment by rafeememon** [comment]
Agreed with @avk -- this is a React-wide problem, and fixing it for this specific component seems silly; the dev tools should be able to give you what you need.
