### ISSUE TITLE
Months with 6 lines cause the calendar to shift if more than 2 months shown

### ISSUE THREAD

**Issue by incognos** [Hacker0x01/react-datepicker#5204]
**Describe the bug**
Months with 6 lines cause the calendar to shift if more than 2 months shown

**To Reproduce**

over the summer of 2024, june starts on a saturday and ends on a sunday. This causes the month to have 6 lines.

    <DatePicker
      swapRange
      selected={fieldStartDate.value}
      onChange={(dates: [Date | null, Date | null]) => {
        const [startDate, endDate] = dates
        setFieldValue('reportStartDate', startDate)
        setFieldTouched('reportStartDate', true)
        setFieldValue('reportEndDate', endDate)
        setFieldTouched('reportEndDate', true)
      }}
      maxDate={new Date()}
      startDate={fieldStartDate.value}
      endDate={fieldEndDate.value}
      monthsShown={4}
      selectsRange
      inline
      showDisabledMonthNavigation
    />

**Expected behavior**
I don;t expect september to be completely out of alignment with the other months

**Screenshots**
![CleanShot 2024-11-01 at 17 33 12@2x](https://github.com/user-attachments/assets/3004a825-b9ca-45dd-97d7-b61507b53dcd)

**Desktop (please complete the following information):**

- OS: MAc OS 14.6.1
- Browser Brave
- Version  [Version 1.70.126 Chromium: 129.0.6668.100 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by pmacmillan** [comment]
not sure if this is a good way to address this, but here is a workaround:

```css
.react-datepicker {
  display: flex;
  flex-wrap: wrap;
}
```

or combine with `calendarClassName` if you're wary of overriding the main class.

i.e.
```js
   <DatePicker ... calendarClassName="react-date-picker-flexible" ... />
```
```css
.react-datepicker-flexible {
  display: flex;
  flex-wrap: wrap;
}
```

![image](https://github.com/user-attachments/assets/c388a6a0-25d3-4e8b-b89b-a62488a2a0b3)

**Comment by incognos** [comment]
Did not fix it but appreciate the response. Limited to 2 months for now.
