### ISSUE TITLE
Calendar shows out of the browser window (partially)

### ISSUE THREAD

**Issue by af7** [Hacker0x01/react-datepicker#523]
Can the calendar shift to the left automatically so it does not go out of the browser window?

![image](https://cloud.githubusercontent.com/assets/7850073/16708233/fd0ae9a6-45f3-11e6-9f02-8cb4116fc85c.png)

**Comment by af7** [comment]
Is there  a way to do so? Thanks!

**Comment by rafeememon** [comment]
This doesn't look to be our component; are you sure you're filing this in the right place?

**Comment by af7** [comment]
You are right! It was meant for a different repo ('react-date-picker), I apologize.
