### ISSUE TITLE
openToDate doesn't work when minDate and maxDate are set

### ISSUE THREAD

**Issue by tylergould** [Hacker0x01/react-datepicker#525]
I'm trying to use react-datepicker with an openToDate on a project and I'm having trouble getting it to work when I have a minDate and maxDate set.

The calendar opens to the beginning of my min/max date range, when I would expect it to open to the openToDate.

I made this barebones project to reproduce the issue.
https://github.com/tylergould/reproduce-opentodate-issue

Thank you.

**Comment by rafeememon** [comment]
Thanks for the bug report; resolved with #526

**Comment by thangaduraicse** [comment]
@rafeememon - Kindly Let us know whether above issue is resolved in current release or if this issue is resolved only in next release then please let us know date for next release?

**Comment by vetri50ster** [comment]
@rafeememon - we are using the same plugin in our project. we are also facing same defect.Please let us know solution for this defect.

**Comment by martijnrusschen** [comment]
This should be fixed with the next release (should happen this week)

**Comment by thangaduraicse** [comment]
@martijnrusschen: Client ask is to update that fix immediately. If you release the next version, this 'll be helpful for us.

**Comment by rafeememon** [comment]
@thangaduraicse, you can easily build your own dist of the component in lieu of a release.

**Comment by martijnrusschen** [comment]
Planning to do a release today. Stay tuned :)

**Comment by martijnrusschen** [comment]
@thangaduraicse Here you go https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.28.2

**Comment by thangaduraicse** [comment]
@martijnrusschen @raffeememon Thank you.. :)

**Comment by tsteele2013** [comment]
I'm having this issue also. Using v0.41.1

The following code still opens to today's date. Any ideas?

````
<DatePicker
  selected={moment(Application.ExpectedRetDate).isValid() ? moment(Application.ExpectedRetDate) : null}
  onChange={value => {
    this.setState({ touched: Object.assign(touched, { ExpectedRetDate: true })});
    Application.ExpectedRetDate = value ? value._d : null;
  }}
  openToDate={moment('1993-09-28')}
  onBlur={value => this.setState({ touched: Object.assign(touched, { ExpectedRetDate: true })})}
  minDate={Authentication.user.eligible_date}
  maxDate={moment().add(5, "years")}
  disabled={disabled}
  fixedHeight
  name="ExpectedRetDate"
  id="FormDatePicker"
  placeholderText="Select Date"
  className='form-control'
/>
````

**Comment by superfunkminister** [comment]
+1
