### ISSUE TITLE
How can I initialize it with an empty value?

### ISSUE THREAD

**Issue by illing2005** [Hacker0x01/react-datepicker#53]
Hi, 
I like your component, but I am not able to initialize it with an empty value.
How can that be done?
Thanks!

**Comment by RSO** [comment]
Hey @illing2005 !

Thanks, how would you like this to work? At this point it is not possible indeed, mostly because I'm not quite sure how the component should behave.

What do you expect to see when you open the date-picker when it's empty? I'm thinking the current month?
