### ISSUE TITLE
the year should not disappear when showYearDropdown is false.

### ISSUE THREAD

**Issue by solsos** [Hacker0x01/react-datepicker#533]
When I set the showYearDropdown is false. 
We don't want the user select the year. 

But base on current function. 
1. the first show is right, we the month and year in title.
![before click the year](https://cloud.githubusercontent.com/assets/17923026/17262450/6493056c-55a9-11e6-8b1c-deb2f62992a7.png)
2. after click, the year is disappear and the year drop down list is in display none. 
![after click the year](https://cloud.githubusercontent.com/assets/17923026/17262449/6491eec0-55a9-11e6-9348-f8e717d35c9b.png)
So, that not a good user experience..

**Comment by jochenberger** [comment]
I cannot reproduce this with 0.34.0: https://codepen.io/jochenberger/pen/xRpQOK
