### ISSUE TITLE
onChange event returns moment object instead of native

### ISSUE THREAD

**Issue by Erzei** [Hacker0x01/react-datepicker#535]
I have implemented the DatePicker component to be able to polyfill the input[type=date] on browsers which are not Chrome. 

My problem is that when an onChange event os fired on the component, instead of a native event object, it's returning a moment object, which is breaking my form & state validations. 

Is there a way to receive the native event object?

Here is my onChange handler:

```
onChange (event) {
    console.warn(event)
    const form = _.cloneDeep(this.state.form)
    let {name, value} = event.target

    if (name.match(/\[(.*?)\]/) !== null) {
      name = name.split('[')[0] + '.' + name.match(/\[(.*?)\]/)[1]
    }

    _.set(form, name, value)
    this.setState({form: form})
  }
```

As you can see, I'm expecting to have a target attribute to do my system validations, where all the other standard inputs are behaving as expected.

**Comment by averted** [comment]
Related to #488

**Comment by martijnrusschen** [comment]
Moment.js was removed in #1527, starting v2.0.0, this package doesn't use Moment anymore.
