### ISSUE TITLE
onBlur not working for server side rendering - requirejs, browserify

### ISSUE THREAD

**Issue by njj** [Hacker0x01/react-datepicker#544]
Hi all,

I have a date picker that will only close when a date is selected.  I have added the `onBlur` property, and it will only fire after the date picker is closed, and if I click around the date picker.   Below is a screenshot of after I clicked a date, it shows the date picker as still being selected (focused).  Once I click outside that area it will fire the onBlur event.

Any ideas? I'm using the most recent version of the library.

<img width="305" alt="screen shot 2016-08-15 at 9 53 19 am" src="https://cloud.githubusercontent.com/assets/1734769/17666439/20ef3d44-62ce-11e6-8ac2-bdea96c8a74b.png">

Edit: Also when I have multiple date pickers, it won't close other ones before opening another so I end up having a bunch of them overlapping.

After some more digging into this issue I believe its related to requirejs and browserify, but can't figure out exactly why yet.

**Comment by njj** [comment]
Solved my issue, by including `react-datepicker` as an external with browserify and then manually loading it via requirejs (with its dependencies as well).

Any maintainers know why this is happening?

**Comment by joeJazdzewski** [comment]
I have had the same issue, it might be that you were missing the "react-onclickoutside" package.

**Comment by njj** [comment]
@joeJazdzewski I ended up using requirejs to pull in moment and react-onclickoutside before requiring in this library.

Did you have a different way you included the react-onclickoutside library?  I tried just importing it before this library, but no luck on fixing the issue.

I think a PR to move react-onclickoutside to a HoC versus a mixin would be a good help too.  Maybe I'll do that.

**Comment by joeJazdzewski** [comment]
I installed both packages into my project and that seemed to fix it for me. I believe that version 5.0.0 (and above) of react-onclickoutside is a HoC instead of a mixin.

**Comment by njj** [comment]
@joeJazdzewski cool I'll give that a shot, so just installed the at the same version as they are in this library?  Do you import the dependencies in the same file you import this library also?
