### ISSUE TITLE
allow datepicker to be a controlled component

### ISSUE THREAD

**Issue by bbmreed** [Hacker0x01/react-datepicker#547]
date_input.jsx does not always call `props.onChange`, eg if the date is in valid or not within a valid range.

This means that a parent component using date_picker as a controlled component will not always be aware of the user's input, which has the following pitfalls:
- the user's invalid data can not be stored and re-displayed (aka it disappears on any re-render)
- the user's input can not be inspected to provide warnings (aka "out of range" / "invalid") 

This is especially jarring when typing in a syntactically valid date that is not within range - the typed in value disappears, and we can't give a warning as to why.

example: https://gyazo.com/c3404b9dcfdc8497a92466bd4dc77717.gif

I believe this was the original commit:

https://github.com/Hacker0x01/react-datepicker/pull/346/commits/b8fc931399f50eecf27203cb7d976483b7f18c54

More on what I mean by a controlled component: https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by aij** [comment]
Does the new `onChangeRaw` solve this?
