### ISSUE TITLE
Manual input date is getting reset to blank on IE11

### ISSUE THREAD

**Issue by rahulvjti** [Hacker0x01/react-datepicker#548]
I am using react datePicker for one of the Project. When I am entering the date manually in textbox its getting reset to blank. In second scenario when I select date from calendar its not getting reset but again if i am entering manually it is getting reset to calendar selected date. Please help with this issue asap

**Comment by charlotteisabella** [comment]
Hey, is it resetting to nothing or is it resetting to 'Invalid Date'? I am having a similar issue in IE11 and firefox where when a user enters anything in the textbox it returns 'Invalid date'.

**Comment by rahulvjti** [comment]
I have analyzed this issue and for IE 11 when user select date from calendar first then its valid but when manually edit the date then its coming as invalid date so it resetting it to earlier date(Selected from calendar). At the start when i enter the date manually ,its coming invalid date so resetting it to blank.

**Comment by rahulvjti** [comment]
Someone please provide the solution as its getting frustrated really.
