### ISSUE TITLE
Disable inline datepicker does not work

### ISSUE THREAD

**Issue by mathan78** [Hacker0x01/react-datepicker#550]
The disabled attribute does not seem to work for inline DatePickers. Works fine without the inline. 

Is this by design or a bug? It would be nice to be able to disable inline as well.

// does not work
<DatePicker
  disabled={true}
  inline
  ...
/>

// works
<DatePicker
  disabled={true}
  ...
/>

**Comment by jochenberger** [comment]
What do you mean by "does not seem to work"? You can specify `inline` and `disabled`: http://codepen.io/jochenberger/pen/YpvxgV

**Comment by slavikdenis** [comment]
I have no idea why, but It seems to not work for me either. Maybe the issue can be that I have the inline date picker in bootstrap modal somehow?

**Comment by jakezatecky** [comment]
If you take the same example and modify it to include `selected` and `onChange`, it behaves as if nothing is actually disabled.

http://codepen.io/anon/pen/aJQryY

The developer can get around some of this by setting `minDate` and `maxDate` to the `selected` value and omitting the `onChange` handler, but the calendar should at least have some visual indicators that it is disabled.

I created an example based on @jochenberger's example that effectively created the appearance of a disabled inline date:

http://codepen.io/anon/pen/XMywPE

**Comment by Florensvb** [comment]
It has been a while my friends! Unfortunately the issue still persists.
Workaround of setting the `minDate` and `maxDate` works, however it would be nice if this could get fixed soon.

**Comment by demkovych** [comment]
+1

**Comment by artardupilot** [comment]
+1
