### ISSUE TITLE
Warning with React version 15.3.1

### ISSUE THREAD

**Issue by jetpack3331** [Hacker0x01/react-datepicker#553]
Hi,
when i use DatePicker 0.29.0 version with React version 15.3.1 i get maaaany warnings in console. All is like this:

Warning: You are manually calling a React.PropTypes validation function for the `autoComplete` prop on `DatePicker`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

And all files show that, so about 35 warnings on startup.

**Comment by martijnrusschen** [comment]
Thanks, if someone could dig into this to find out what's going wrong that would be really appreciated.

**Comment by jochenberger** [comment]
I don't get any warnings in 0.34.0, React 15.3.2.

**Comment by martijnrusschen** [comment]
Yeah I think this was fixed in one of the recent releases. Closing this out.
