### ISSUE TITLE
Datepicker inside a dialog html tag does not work properly

### ISSUE THREAD

**Issue by mstn** [Hacker0x01/react-datepicker#555]
Within a [dialog tag](http://www.w3schools.com/tags/tag_dialog.asp) the datepicker does not work properly. In particular:
1. It is displayed under the dialog and dialog::backdrop; changing z-index does not work.
2. OnChange events are not detected even when the calendar is moved inside the dialog tag. In this case days are clickable again, but change event is not triggered and the calendar is closed.

EDIT
It could be related to https://github.com/Hacker0x01/react-datepicker/issues/488, but the behavior described there is slightly different. In my case I use the relatively new dialog tag.

**Comment by rafeememon** [comment]
Dialog tags function much differently than modals, so I think they're unrelated.  This seems like the same issue described [here](https://github.com/zeroclipboard/zeroclipboard/issues/542), but judging from the responses it looks like the only solution would be to move the datepicker container to inside the `<dialog>`.
