### ISSUE TITLE
Uncaught Error: Cannot find module "react-datepicker" on webpack rebuild

### ISSUE THREAD

**Issue by npverni** [Hacker0x01/react-datepicker#562]
I'm getting the following error when webpack rebuilds changes:

`Cannot find module "react-datepicker"`

If I restart webpack, it works fine. 

I know this is probably unrelated to this library, but I have not experienced this with any other dependencies.

My import statements are as follows:

```javascript
import React, { PureComponent, PropTypes } from 'react';
import { Map } from 'immutable';
import moment from 'moment';
import DatePicker from 'react-datepicker';
```

Any help/ideas would be appreciated. If unrelated, feel free to close.

Thanks,
Nathan

**Comment by rafeememon** [comment]
Seems like a webpack problem to me; try wiping out `node_modules` and `npm install`ing again?

**Comment by rafeememon** [comment]
Closing for lack of anything else to go on
