### ISSUE TITLE
how to assign empty date 

### ISSUE THREAD

**Issue by RatanPaul** [Hacker0x01/react-datepicker#565]
I am trying to leave the date field empty at initial load. is it possible ? 

```
this.state = {
                     startDate: moment(),
		    endDate: moment()
		}
```

this will give current date but i leave it blank 

```
this.state = {
                     startDate: "",
		    endDate: ""
		}
```

this is giving me error 

any solution?

**Comment by rafeememon** [comment]
Use `null` instead of the empty string

**Comment by RatanPaul** [comment]
ahh Thanks!

**Comment by Kelvne** [comment]
Actually `null` is not working for me.

It throws on the console:
`Uncaught TypeError: t.date.clone is not a function`

Version 0.40.0
