### ISSUE TITLE
Display multiple months vertically

### ISSUE THREAD

**Issue by inyigo** [Hacker0x01/react-datepicker#566]
Sorry for not digging deeper but I skimmed through demos/docs and issues but couldn't find anything that relates to what I need. 

Is it currently possible to display multiple months and display them vertically?

eg

![kayak calendar](https://cloud.githubusercontent.com/assets/405883/18675514/2cacf3e6-7f85-11e6-9625-7c18fb502f18.png)

![kayak calendar 2](https://cloud.githubusercontent.com/assets/405883/18675523/31cfd47e-7f85-11e6-85a2-7e6a55fb755b.png)

**Comment by rafeememon** [comment]
Nope, not currently possible.  PRs implementing this are welcome!

**Comment by inyigo** [comment]
@rafeememon thanks for the info. I will give it a shot.

**Comment by jkyro** [comment]
Hi, I opened a PR #596 about multiple month support. However the layout of the months is horizontal since it fits my use case but should not be too difficult to make an option for vertical layout.

**Comment by inyigo** [comment]
https://github.com/Hacker0x01/react-datepicker/pull/596

**Comment by gius** [comment]
@inyigo 
Try this CSS override:
```css
.react-datepicker__month-container {
    float: none;
}
```
