### ISSUE TITLE
Mask typed input

### ISSUE THREAD

**Issue by felipe-gdr** [Hacker0x01/react-datepicker#567]
Mask user input on keyUp event. Ex.: --/--/----

**Comment by ReactGirl** [comment]
Any solution for this one?

**Comment by truefunrun** [comment]
@ReactGirl I'm not found solution, using that component, I use air-datepicker for that feature

**Comment by alyahmedaly** [comment]
any update on tha

**Comment by js2me** [comment]
@alyahmedaly I heard so that component have possible to connect with react-inputmask

**Comment by alyahmedaly** [comment]
yes it's very easy 
`          <DatePicker {...DatePickerProps}
            customInput={<MaskedInput mask={['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/]} calendar={this._calendar} />}
          />`

**Comment by js2me** [comment]
I think that issue need to close

**Comment by rafeememon** [comment]
Agreed, I don't think this is something that we could easily support natively given the flexibility of the date formats.

**Comment by vctormb** [comment]
@alyahmedaly Where can I find the 'DatePickerProps'? I'm trying to use the 'MaskedInput' lib, but the value doesn't change when I select a new date.

**Comment by alyahmedaly** [comment]
@vctormb not sure what's your issue but any way this my props 
` const DatePickerProps = {
      onBlur: input.onBlur,
      onFocus: input.onFocus,
      dateFormat: dateFormat,
      selected: selectedValue,
      onChange: this.handleChange,
      className: "form-control",
      fixedHeight: true,
      showMonthDropdown: true,
      showYearDropdown: true,
      placeholderText: custom.placeholder,
      disabled: custom.disabled,
      minDate: custom.min,
      maxDate: custom.max,
      customInput: <DatePickerMaskedInput />,
      customInputRef: 'inputRef'
    };`

**Comment by vctormb** [comment]
@alyahmedaly When I select a new date on the Calendar it does not change the MaskedInput value. Do you know how to solve it?

**Comment by arielff3** [comment]
New soluction ?

**Comment by mabitten** [comment]
hi, how can i put mask when the users are typing?
