### ISSUE TITLE
Uses american date format when locale is set to en-gb

### ISSUE THREAD

**Issue by saborrie** [Hacker0x01/react-datepicker#568]

**Comment by rafeememon** [comment]
Can you provide more detail here; specifically, can you give us code that reproduces this?

**Comment by karldanninger** [comment]
experiencing the same problem

**Comment by rafeememon** [comment]
@karldanninger, again, it's difficult to provide any help without code that shows this problem =)

**Comment by karldanninger** [comment]
yeah, sorry @rafeememon totally understandable, I'm just using the same as the example on the demo page

```
    <DatePicker
      selected={selected}
      onChange={onChange}
      locale='en-gb'
    />
```

I'm also on `"react-datepicker": "^0.29.0"`

❤️

**Comment by lfender6445** [comment]
this is simple, just change the date format prop

          dateFormat="MM/DD/YYYY"
          locale="en-gb"

**Comment by karldanninger** [comment]
what I actually need is the side effect of having the week rows start with Mon-Sun

**Comment by iknowcss** [comment]
@saborrie and @karldanninger have you added the `'en-gb'` locale to moment.js? I believe most locales are not included by default.

http://momentjs.com/docs/#/i18n/loading-into-browser/ 

I am on mobile now so it is difficult to test. I will have a second look a bit later.

**Comment by iknowcss** [comment]
If this solves the problem maybe the README needs to be updated

**Comment by rafeememon** [comment]
@karldanninger, as noted in the readme you can change the week start by configuring the `week.dow` option in moment.  However, if you're really working with the `en-gb` locale you should probably set the locale to be more semantically correct; be sure to load it as @iknowcss mentioned.

**Comment by karldanninger** [comment]
👍

**Comment by lfender6445** [comment]
@saborrie also just wanted to note, the american date format does start with sunday and not monday

> According to international standard ISO 8601, Monday is the first day of the week. It is followed by Tuesday, Wednesday, Thursday, Friday, and Saturday. Sunday is the 7th and final day.
> Although this is the international standard, several countries, including the United States and Canada, consider Sunday as the start of the week.

https://www.timeanddate.com/calendar/days/
