### ISSUE TITLE
Feature request: allow custom handling of Enter key

### ISSUE THREAD

**Issue by marina-marina** [Hacker0x01/react-datepicker#580]
When I press the enter key the calendar is getting closed now. It would be really nice to allow custom handling of the enter key. This is very useful if we want to search our form on pressing enter. 

The datepicker could have something like `onEnter={callback()}` and `closeOnEnter={bool}` or just let it be closed on enter (like now) + custom callback.

Thank you!

**Comment by jbrey** [comment]
+1

**Comment by arnabk** [comment]
+1

**Comment by mihailmetro** [comment]
+ 1

**Comment by pbsmultimedia** [comment]
+1

**Comment by harshalpandey** [comment]
+1
