### ISSUE TITLE
Close calendar from customInput

### ISSUE THREAD

**Issue by xrado** [Hacker0x01/react-datepicker#581]
I'm using custom input to enable form submit on enter, but input calendar stays open.
Is there a way to close it?

**Comment by alex-shamshurin** [comment]
+1
This is another reason why we need isOpen property

**Comment by rafeememon** [comment]
More discussion about an `isOpen` prop on #283 and #531

**Comment by danilvalov** [comment]
I use the following solution:
```
closeDatePicker() {
  const {datepicker} = this.refs;

  datepicker.setOpen(false);
}

render() {
   return (
      <div>
        <DateInput
          ref="datepicker"
          {...options}
        />
      </div>
    );
}
```

**Comment by Tautorn** [comment]
I'm use a footer button to close my calendar, like this:

```
const [myRef, setMyRef] = useState(false)

const closeCalendar = () => {
  myRef.setOpen(false)
}

return (
  <DatePicker
      ref={(r) => {
        setMyRef(r)
      }} 
     {...props}
  >
    <button onClick={closeCalendar}>Close</button>
  </DatePicker>
)
```

**Comment by matviishyn** [comment]
Solution with hooks

`let datepickerRef = useRef(null);

  const openDatepicker = () => {
    datepickerRef.setOpen(true);
  };

 <DatePicker
        ref={(r) => datepickerRef = r}
        {...props}
/>
`
