### ISSUE TITLE
This component doesn't define main assets in bower.json

### ISSUE THREAD

**Issue by marekdano** [Hacker0x01/react-datepicker#583]
I've added the rails-assets-react-date-picker gem to my Gemfile and got following response after running bundle install:

marekdano$ bundle install
Fetching gem metadata from https://rails-assets.org/....
Fetching version metadata from https://rails-assets.org/..
Fetching gem metadata from https://rails-assets.org/....
Fetching gem metadata from https://rubygems.org/Retrying fetcher due to error (2/4): Bundler::HTTPError The checksum of /info/debugger-linecache does not match the checksum provided by the server! Something is wrong (local checksum is "\"a0cb7fcb8f8e31c264a79d00457ebac1\"", was expecting "W/\"a0cb7fcb8f8e31c264a79d00457ebac1\"").
..........
Fetching version metadata from https://rails-assets.org/..
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rails-assets.org/..
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.2.2
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.1
Using addressable 2.4.0
Using animate-css-rails 3.5.2
Using babel-source 5.8.35
Using execjs 2.7.0
Using bcrypt 3.1.11
Using method_source 0.8.2
Using thor 0.19.1
Using bundler 1.12.5
Using byebug 9.0.5
Using cancancan 1.15.0
Using json 2.0.2
Using mimemagic 0.3.1
Using chartkick 2.1.1
Using ffi 1.9.14
Using coffee-script-source 1.10.0
Using connection_pool 2.2.0
Using database_cleaner 1.5.3
Using debug_inspector 0.0.2
Using orm_adapter 0.5.0
Using diff-lcs 1.2.5
Using multipart-post 2.0.0
Using hashie 3.4.4
Using multi_json 1.12.1
Using jwt 1.5.4
Using rb-fsevent 0.9.7
Using mini_magick 4.5.1
Using multi_xml 0.5.5
Using pg 0.18.4
Using puma 3.6.0
Installing rails-assets-moment 2.15.1
Installing rails-assets-react-date-picker 0.30.0
Using rails_serve_static_assets 0.0.5
Using rails_stdout_logging 0.0.5
Using tilt 2.0.5
Using rolify 5.1.0
Using rspec-support 3.5.0
Using rubyzip 1.2.0
Using sass 3.4.22
Using websocket 1.2.3
Using spring 1.7.2
Using sqlite3 1.3.11
Using turbolinks-source 5.0.0
Using wicked_pdf 1.1.0
Using wkhtmltopdf-binary 0.12.3
Using faker 1.6.6
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using warden 1.2.6
Using rack_session_access 0.1.1
Using sprockets 3.7.0
Using websocket-driver 0.6.4
Using mime-types 3.1
Using babel-transpiler 0.7.0
Using uglifier 3.0.2
Using childprocess 0.5.9
Using rb-inotify 0.9.7
Using coffee-script 2.4.1
Using faraday 0.9.2
Using omniauth 1.3.1
Using rails_12factor 0.0.3
Using rspec-core 3.5.0
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using turbolinks 5.0.1
Using activesupport 5.0.0.1
Using loofah 2.0.3
Using xpath 2.0.0
Using mail 2.6.4
Using selenium-webdriver 2.53.4
Using listen 3.0.8
Using oauth2 1.2.0
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0.1
Using factory_girl 4.7.0
Using groupdate 3.0.2
Using jbuilder 2.6.0
Using rails-html-sanitizer 1.0.3
Using capybara 2.7.1
Using spring-watcher-listen 2.0.0
Using omniauth-oauth2 1.4.0
Using activejob 5.0.0.1
Using activerecord 5.0.0.1
Using carrierwave 0.11.2
Using actionview 5.0.0.1
Using omniauth-facebook 3.0.0
Using active_median 0.1.3
Using actionpack 5.0.0.1
Using actioncable 5.0.0.1
Using actionmailer 5.0.0.1
Using railties 5.0.0.1
Using sprockets-rails 3.2.0
Using rails-controller-testing 0.1.1
Using bootstrap-datepicker-rails 1.6.4.1
Using coffee-rails 4.2.1
Using responders 2.2.0
Using factory_girl_rails 4.7.0
Using font-awesome-rails 4.6.3.1
Using jquery-rails 4.2.1
Using react-rails 1.9.0
Using rspec-rails 3.5.0
Using web-console 3.3.1
Using rails 5.0.0.1
Using sass-rails 5.0.6
Using devise 4.2.0
Bundle complete! 42 Gemfile dependencies, 120 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from rails-assets-react-date-picker:
This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/Hacker0x01/react-datepicker

**Comment by rafeememon** [comment]
Unfortunately we no longer support bower; see https://github.com/Hacker0x01/react-datepicker/issues/303
