### ISSUE TITLE
Date Range with single DatePicker

### ISSUE THREAD

**Issue by hoodsy** [Hacker0x01/react-datepicker#584]
Is this at all possible? The example for date range is exactly the functionality I would want, but it would be best if the user is selecting the range on a single calendar, not through 2 separate inputs.

**Comment by rafeememon** [comment]
Yep, it's possible -- you'll need to define your own way of setting `startDate` and `endDate` based on `onChange` events.

**Comment by hoodsy** [comment]
@rafeememon sweet! thanks for the quick response. How about the hover styling, to show the range. It seems like that is controlled by ```selectsStart``` and ```selectsEnd```

**Comment by rafeememon** [comment]
Check out the example on the [demo page](https://hacker0x01.github.io/react-datepicker/#example-6)

**Comment by rafeememon** [comment]
Actually, I don't think we currently support having `selectsStart` and `selectsEnd` on the same picker.  Not sure how the semantics of this would work, but PRs to support this are welcome.

**Comment by sahanarula** [comment]
Looking forward for the best solution.

**Comment by TrejGun** [comment]
would love to see this feature too

**Comment by martijnrusschen** [comment]
I agree, would love to see if someone could diff up a PR.

**Comment by TrejGun** [comment]
probably its better to use https://github.com/airbnb/react-dates :)

**Comment by Charlie91** [comment]
Ok, it's possible through the setting startDate and endDate, but how can I display two dates at one input field? It seems that I can only display one date at one time

**Comment by marinarjumina** [comment]
May be it helps someone in the future:

### Get `weekStartDay` and `weekEndDay`:

const weekStartDay = startOfWeek(currentDate, { weekStartsOn: 1 })
const weekEndDay = endOfWeek(currentDate, { weekStartsOn: 1 })

### Prepare `inputValue` range dates output:

const inputValue = format(weekStartDay, "dd/MM/yyyy") + ' - ' + format(weekEndDay, "dd/MM/yyyy")_

### Pass formatted `inputValue` to Datepicker's `value`:

<DatePicker selected={weekStartDay} highlightDates={highlightDates} onChange={setCurrentDate} locale="enGB" **value={inputValue}** />

For me it works.

**Comment by vedadeepta** [comment]
Recently came across this use-case. This can be implemented as follows:

```

  handleChange = date => {
    const { format } = this.props
    if (date) {
      if (!this.state.date) {
        return this.setState({ date })
      }
      this.setState({
        endDate: date,
        rangeDate: `${this.state.date.format(format)} -> ${date.format(format)}`
      })
      return this.props.onDateChange(
        this.state.date.format(format),
        date.format(format)
      )
    }
    this.props.onDateChange(null)
  }

  render () {
        <RDatePicker
          selected={date}
          dateFormat={format}
          onChange={this.handleChange}
          selectsEnd: Boolean(rangePicker && date),
          minDate: date,
          startDate: date,
          endDate: endDate,
          shouldCloseOnSelect: Boolean(rangePicker && date),
          customInput: <div>{this.state.rangeDate || 'Select Date Range'}</div>
        />
  }
```

**Comment by DeanHand** [comment]
Thanks @vedadeepta for the starting point. This method works perfectly for what I need. Hopefully will help anyone else looking for this. 

```
  const [startDate, setStartDate] = useState(undefined);
  const [endDate, setEndDate] = useState(undefined);
  const [selectionComplete, toggleSelectionComplete] = useState(false);

  const handleDateChange = date => {
    if (!selectionComplete && !startDate) {
      //on first date selection, set the start date

      setStartDate(date);
      return;
    }

    if (!selectionComplete && startDate && !endDate) {
      //on second date selection, set the end date

      setEndDate(date);
      toggleSelectionComplete(true);

      //do stuff with date range

      return;
    }

    if (selectionComplete && startDate && endDate) {
      //on third date selection, begin selection of a new date range
      //reset the start date and clear the end date.

      setStartDate(date);
      setEndDate(undefined);
      toggleSelectionComplete(false);
      return;
    }
  };

  return (
    <DatePicker 
      selected={startDate} 
      onChange={handleDateChange} 
      selectsEnd={Boolean(startDate)} 
      startDate={startDate} 
      endDate={endDate} 
      inline
    />
  );
```

**Comment by rs-8** [comment]
Seems like need pull request to enable this feature (selectRange props maybe)

**Comment by tdiluzio** [comment]
Thanks @DeanHand for your demo 👍  Here's my two cents: a simple range demo, I've pasted only useful stuffs. Hope it'll help someone out there:

```jsx
export function DemoDatePicker() {
  // range demo
  const [startDate, setStartDate] = useState(null);
  const [endDate, setEndDate] = useState(null);

  function handleDateChange(date) {
    // initial change start by setting the startDate
    if (!startDate && !endDate) {
      setStartDate(date);
      // startDate has been set, set the end date
    } else if (startDate && !endDate) {
      setEndDate(date);
    }

    // user is choosing another range => set the start date
    // and set the endDate back to null
    if (startDate && endDate) {
      setStartDate(date);
      setEndDate(null);
    }
  }

  return (
    <div>
      <DatePicker
        onChange={(date) => handleDateChange(date)}
        selectsStart={true}
        selected={startDate}
        startDate={startDate}
        endDate={endDate}
        inline={true}
      />
    </div>
  );
}
```

**Comment by lomberas** [comment]
I wanted to show 2 month calendar on `openToDate` to select two dates with date range functionality and show the dates selected on the input field.

Here is what I did with 2 months shown for Date Range: has the `openToDate` attribute, has `placeholderText` ("Select custom date"), moment to format, and I set the value with the custom `inputValue` that holds `startDate` and `endDate`: 

`const [startDate, setStartDate] = useState(new Date());
  const [endDate, setEndDate] = useState(null);
  const onChange = (dates) => {
    const [start, end] = dates;
    setStartDate(start);
    setEndDate(end);
  };
  const inputValue =
    moment(`${startDate}`).format('MM/DD/YYYY') +
    ' - ' +
    moment(`${endDate}`).format('MM/DD/YYYY');

  return (
    <DatePicker
      selected={null}
      onChange={onChange}
      placeholderText="Select Custom date"
      startDate={startDate}
      endDate={endDate}
      selectsRange
      monthsShown={2}
      openToDate={new Date()}
      value={!endDate ? new Date() : inputValue}
    />
  );`

This worked for what I wanted to accomplish. I hope it helps.

**Comment by bipindubey-technoark** [comment]
I am getting an issue while implementing this
16171819202122
![Screenshot from 2020-09-04 15-15-36](https://user-images.githubusercontent.com/59605232/92225937-8c68d200-eec1-11ea-9ba0-5767370599f7.png)

**Comment by bipindubey-technoark** [comment]
Following is my code
`
    const [startDate, setStartDate] = useState(subDays(new Date(), 10));
    const [endDate, setEndDate] = useState(new Date());
    const onDateChange = (dates) => {
        const [start, end] = dates;
        setStartDate(start);
        setEndDate(end);
    };

<DatePicker
                            selected={startDate}
                            startDate={startDate}
                            endDate={endDate}
                            onChange={onDateChange}
                            className={classes.datePicker}
                            todayButton="Today"
                            inline
                            selectsRange
                            selectsEnd={true}
                            selectsStart={true}
                            openToDate={new Date()}
                            maxDate={new Date()}
                            monthsShown={2}
                        />
`

**Comment by dextermb** [comment]
The issue I am having with the `selectsRange` prop without `inline` is that the calendar closes after selecting the start date, meaning users have to reopen the calendar to select the end date.

What's the best method for keeping the calendar open until an end date is selected? Is it even possible?

**Comment by josias-r** [comment]
Yup, came across the same problem as @dextermb. It took me a while until I noticed that `inline` is the culprit. They also have it in [the docs](https://reactdatepicker.com/#example-date-range-for-one-datepicker).

This is a bug, right? Otherwise, it should be mentioned in the docs that `inline` is required for some reason to work with `selectsDate`

**Comment by kellydena-TTMSTech** [comment]
suggest using shouldCloseOnSelect to solve this problem @josias-r

**Comment by khuongphp** [comment]
> 

Thank you. That should be the right answer. But seem complex :D :D
There are some difference with the document
[https://reactdatepicker.com/#example-date-range-using-input-with-clear-button](https://reactdatepicker.com/#example-date-range-using-input-with-clear-button)

**Comment by khuongphp** [comment]
update to verson `"react-datepicker": "^4.6.0"` resolved my issue
