### ISSUE TITLE
setting new date values from extern are not respected by the input

### ISSUE THREAD

**Issue by Siern** [Hacker0x01/react-datepicker#588]
When sending new selected date in the props to the datepicker, only the calendar respects this change.
The reason is the input uses state.value to feed the input.  However, on the componentWillReceiveProps you check the new props.date against the old prop.date.  This does not make sense to me.
It should be a check from newProps.date and state.value.  FYI, the "old props" actually have the new desired date already in it, which is why the compare fails to see the difference.  This is a result of the main datepicker render forwarding the props to the input render.

The result now, is to have the input update, the calendar selection must be opened and closed.  Without even selecting a date.  This is likely caused by the blur event setting the date without a difference check!

**Comment by rafeememon** [comment]
The reasoning for the same day check [here](https://github.com/Hacker0x01/react-datepicker/blob/v0.30.0/src/date_input.jsx#L40) is that the input should only be changed if the new date is different, so as not to clobber a user's intermediate input; `state.value` will not always be a valid date.  Can you provide a sample app that shows the problem you're describing?

**Comment by Siern** [comment]
The source of the error may actually be a false assumption that moment.add was immutable, due to inexperience with this container.
I now believe this is modifying your old date object.

the onChange's handler had an add x days then conversion to Date, then on the render a conversion back to moment.  This I believe now resulted in original moment being modified.  This can be seen in the fact that their _i and _d values are not matching in the old props when the compare is made.

I will test and confirm this tomorrow.

**Comment by rafeememon** [comment]
Yep, unfortunately this is a pretty common gotcha with the moment library.  Please re-open if you still run into an issue
