### ISSUE TITLE
"a.default.utc is not a function" when importing DatePicker

### ISSUE THREAD

**Issue by tpinne** [Hacker0x01/react-datepicker#589]
Hi,

I just tried to use your component but got stuck right away. After 
```
import {DatePicker} from 'react-datepicker';
```
I get the following error in my browser console
```
Dynamic page loading failed TypeError: a.default.utc is not a function
```
I'm using [reactboilerplate@3.2.0](https://github.com/mxstbr/react-boilerplate) and freaking out not getting around this problem.

Any help is really appreciated.

Thanks, Tobi.

**Comment by rafeememon** [comment]
Can you provide a full sample app that shows this?

**Comment by tpinne** [comment]
I put something together really quick, but the problem is reproduced here.

```
git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
npm run setup
npm run clean
npm install react-datepicker --save
```

---------------------
**Optional** 
(to get rid of a webpack warning later):
```
npm install --save-dev empty-module
```

in 'webpack/webpack.base.babel.js' add after line 72 
```
new webpack.ContextReplacementPlugin(/\.\/locale$/, 'empty-module', false, /js$/)
```
---------------------

then
```
npm run start
```

Open 'http://localhost:3000'

and add
```
import DatePicker from 'react-datepicker';
```

to `app/containers/HomePage/index.js` @ line 15 (eg.)

let webpack recompile and then reload your browser and look at console output.

Hope this helps.

Thx for having a look into it anyway.

**Comment by rafeememon** [comment]
Based on the error message you posted, this might be an issue with how ES6 modules are compiled/consumed, specifically when importing the default export.  Unfortunately I don't have time to look into this, but maybe you can use that as a starting point.

**Comment by akiokio** [comment]
Same here pretty sure is because how the react boilerplate loads the libraries.

Did you find a solution @tpinne ?

**Comment by tpinne** [comment]
Haven't had the time to look into it. Maybe on Friday or sometime next week.

**Comment by ej23lee** [comment]
I had the same issue. Check if [this fixes your issue](https://github.com/mxstbr/react-boilerplate/issues/1152).

**Comment by rafeememon** [comment]
Good find @ej23lee -- closing this out since this is react-boilerplate-side
