### ISSUE TITLE
Duplicating week line in Safari

### ISSUE THREAD

**Issue by joaoeffting** [Hacker0x01/react-datepicker#592]
Chrome is ok, but when i open in safari, my actual week is duplicating

![captura de tela 2016-10-14 as 19 51 13](https://cloud.githubusercontent.com/assets/7833788/19404849/b0637c9e-9247-11e6-944a-d67863e1594a.png)
![captura de tela 2016-10-14 as 19 51 41](https://cloud.githubusercontent.com/assets/7833788/19404848/b06162ba-9247-11e6-9ccc-b8bfdc454c8d.png)

**Comment by joaoeffting** [comment]
yep, it does

![captura de tela 2016-10-14 as 19 54 07](https://cloud.githubusercontent.com/assets/7833788/19404874/041994b8-9248-11e6-83c7-aba4ccb08e55.png)

**Comment by rafeememon** [comment]
Thanks. Any help digging into this would be much appreciated.

**Comment by joaoeffting** [comment]
No problem. I'll try hehe

**Comment by joaoeffting** [comment]
I'm trying to resolt it. I saw the problem occurs only in october because daylight saving :)

**Comment by nildowjunior** [comment]
Same problem here.
I've tested at two devices, both using the demo page:

- iPad running iOS 9.3.5 - The problem doesn't exist
- iPhone 7 running iOS 12.1 - The problem exist 


The problem occurs in some specific months. For example 11/2018, 11/2019, 10/2020, 11/2020

Anyone has ideas how to solve it?

**Comment by fnfilho** [comment]
Having the same problem here, anyone has any idea on how to solve this?
