### ISSUE TITLE
Selected dates highlight on multiple inline DatePickers

### ISSUE THREAD

**Issue by mlzsolti** [Hacker0x01/react-datepicker#594]
Hi!

When I have two inline datepickers, one next to the other, if I change the date on one, the CSS highlight disappears on the other. I'd like to keep the highlight and the "selected" class active on both datepickers.

Is this normal behaviour, and is there any way to keep the "selected" class on both datepickers separately?

**Comment by rafeememon** [comment]
The highlight will always appear on the selected date passed into the picker.  Are you sure you're passing in the correct dates?
