### ISSUE TITLE
Warning in React 15.x when value is empty

### ISSUE THREAD

**Issue by ido-ofir** [Hacker0x01/react-datepicker#602]
Hi. I am using react 15.0.3 and I get a warning when there is an empty value as the selected date:

Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

my selected date is set to an empty string but it looks like the DatePicker is trying to render `null` to the input. this also happens when I use an initial value with the `clearable` option and then clear the date using the clear button.

**Comment by alex-shamshurin** [comment]
+1

Yes, during server rendering "selected" prop may be null and the field initially may be empty without warnings.

**Comment by rafeememon** [comment]
What version of the datepicker are you using?  [This line](https://github.com/Hacker0x01/react-datepicker/blob/v0.33.0/src/date_input.jsx#L73) should be creating an empty string when the date is `null`.

Not sure if you literally meant it, but you shouldn't be passing an empty string to the `selected` property to have no date selected; pass in `null` instead.

**Comment by alex-shamshurin** [comment]
0.32 it doesn't work, but on 0.33 it's ok.

**Comment by ido-ofir** [comment]
Apparently I was using an older version. on 0.33 it's fine. 
Thank you.
