### ISSUE TITLE
With custom input datepicker opens and closes on each click on input

### ISSUE THREAD

**Issue by alex-shamshurin** [Hacker0x01/react-datepicker#604]
But with builtin input it never happens.

**Comment by jochenberger** [comment]
Confirmed, see http://codepen.io/jochenberger/pen/ENRNZN

**Comment by jochenberger** [comment]
Make sure that your input has the `react-datepicker-ignore-onclickoutside` CSS class, it should work then.

**Comment by jochenberger** [comment]
@martijnrusschen, this should probably be mentioned in the docs and fixed in https://hacker0x01.github.io/react-datepicker/#example-24.

**Comment by alex-shamshurin** [comment]
I did't know about that

**Comment by martijnrusschen** [comment]
Can someone fix the example, to make sure this won't happen to other people as well?

**Comment by jochenberger** [comment]
Fixing the example won't prevent this from happening again. The docs definitely need some love too.

**Comment by alex-shamshurin** [comment]
Is the project not maintained anymore?

**Comment by martijnrusschen** [comment]
@jochenberger Agree. Would love to have that updated before we starting releasing a V1 version. Something I'm planning to do in the next few weeks. Do you have suggestion on things we need to update in the docs? (we should probably move this to a different issue.)

**Comment by martijnrusschen** [comment]
@alex-shamshurin The project is still maintained and active. However, maintaining doesn't mean you should fix all issues yourself.

**Comment by jochenberger** [comment]
@martijnrusschen At least all the props and their effects should be documented. 
For the custom input, I'm not even sure how it's supposed to work. Probably, you should just pass down all props to your custom component, as in `props={...this.props}`.
