### ISSUE TITLE
How to allow multiple input formats?

### ISSUE THREAD

**Issue by homerlex** [Hacker0x01/react-datepicker#605]
With the locale set to us-en the user has to enter the date formatted like 01/01/2016 (MM/DD/YYYY) if they type it in manually (otherwise the date is not considered valid).

Is there a way to allow the user to also type in the date without having to pad the the month and day with zeros and not have to put in the full year (like 1/1/16)?

Of course we'd like to have this same sort of behavior (not forcing the padded numbers but allowing it) with date formats for all locales.

**Comment by rafeememon** [comment]
The `dateFormat` prop can [accept an array of formats](https://github.com/Hacker0x01/react-datepicker/blob/v0.33.0/docs/datepicker.md#dateformat) where they will all be used for reading but the first one is used for displaying.

**Comment by homerlex** [comment]
The problem with using the `dateFormat` prop is that it overrides the format based on locale.  So if I set `dateFormat={['MM/DD/YYYY', 'M/D/YY', ...]}` it would be fine for en-US but wrong for en-GB since it uses the first format in the `dateFormat` array to display the date.

**Comment by salkiducky** [comment]
I'm searching for this answer as well!

**Comment by pawlowskim** [comment]
I have the same issue today. And I wonder, theoretically. If we pass a function as first date format that will change it depends on locales could it display date in local format? I know this doable in some languages (a property, not a function that is dynamically calculated when needed)

**Comment by dmasley-hyfen** [comment]
This issue was fixed for me with this. I just added different formats for slashes and dashes

`dateFormat={["dd/MM/yyyy", "dd-MM-yyyy"]}`

> The `dateFormat` prop can [accept an array of formats](https://github.com/Hacker0x01/react-datepicker/blob/v0.33.0/docs/datepicker.md#dateformat) where they will all be used for reading but the first one is used for displaying.
