### ISSUE TITLE
Keyboard access with empty date shows NaN's

### ISSUE THREAD

**Issue by markbrown4** [Hacker0x01/react-datepicker#607]
- Go to https://hacker0x01.github.io/react-datepicker/
- Clear input
- press the down arrow

> Invalid date
> NaN NaN NaN NaN NaN NaN NaN

**Comment by dktan** [comment]
any one working on this?

**Comment by quangas** [comment]
I have the same issue

- select the date
- clear the input (with backspace)

then it breaks and shows invalid date, NaN, NaN

**Comment by abury** [comment]
Same issue. Really need to be able to allow user input but can't really let them while this is a problem :(
