### ISSUE TITLE
"TypeError: s.default.locale is not a function(…)" when running in production mode

### ISSUE THREAD

**Issue by ej23lee** [Hacker0x01/react-datepicker#609]
Hi,

I'm using react-boilerplate and I get this issue when I'm using the DatePicker in production mode. When I run the env in development mode, there are no issues and it works fine. 

![screen shot 2016-10-27 at 2 51 08 pm](https://cloud.githubusercontent.com/assets/7704225/19780912/0d69d2c8-9c55-11e6-868a-dde4f0e6b26d.png)

I set the DatePicker's locale props and this issue goes away but I get another error.

![screen shot 2016-10-27 at 2 56 02 pm](https://cloud.githubusercontent.com/assets/7704225/19781049/93972bd4-9c55-11e6-933b-9d2e777df594.png)

Any ideas or suggestions?

Thanks.

**Comment by rafeememon** [comment]
Probably the same issue as #589

**Comment by ej23lee** [comment]
I'm closing the issue since [this is the fix](https://github.com/mxstbr/react-boilerplate/issues/1152).
