### ISSUE TITLE
todayButton styles are overriding the rest

### ISSUE THREAD

**Issue by xuerion** [Hacker0x01/react-datepicker#611]
When the Today button is set, the entire calendar turns gray (#f0f0f0? the same color as the Today button). This started happening after upgrading from 0.29.0 to 0.33.0. It is occurring on the example page as well for the Today button example: https://hacker0x01.github.io/react-datepicker/#example-3 

![screenshot from 2016-11-17 13 44 55](https://cloud.githubusercontent.com/assets/6878165/20404797/0b808470-accc-11e6-8e25-b500b3253525.png)

**Comment by jochenberger** [comment]
The button takes the complete height of the calendar. Shouldn't `.react-datepicker__today-button` have `clear:left`?

**Comment by jochenberger** [comment]
This issue was caused in 6ec4cb9ad2ef0393a9d66519b4bf51e896104bda, specifically in https://github.com/Hacker0x01/react-datepicker/commit/6ec4cb9ad2ef0393a9d66519b4bf51e896104bda#diff-9da5657b359639ae904fe748a1fb2b4cR119.
