### ISSUE TITLE
The date picker acts strange in IE11

### ISSUE THREAD

**Issue by lorenzosjb** [Hacker0x01/react-datepicker#615]
I found out that this is an issue with Internet Explorer 11 (11.0.9600.18499).  The problem can be reproduced in https://hacker0x01.github.io/react-datepicker/ on the date range option:

1. Click any date field
2. Click outside the IE browser on any other application´s windows or desktop area
3. Click the other date field

I added an image. When you reproduce the problem, you will see the cursor blinking like crazy. With lesser versions (0.29.0), the browser goes irresponsive. 

![error](https://cloud.githubusercontent.com/assets/7716358/19939685/a3a9c77c-a0ef-11e6-98e2-00567b0fdd20.jpg)

**Comment by jochenberger** [comment]
Confirmed, I can reproduce this issue in IE11 and a similar one in Edge.

**Comment by torkjels** [comment]
I am also encountering this issue in IE11 specifically.
