### ISSUE TITLE
Can't install repo from GitHub URL

### ISSUE THREAD

**Issue by leebradley** [Hacker0x01/react-datepicker#616]
Installing this package via NPM from the GitHub URL doesn't currently work. It probably just needs a few minor adjustments. Right now react-datepicker uses `prepublish` to create the dist folders, but this doesn't run when packages are installed via npm.

**Comment by rafeememon** [comment]
Yep, this is somewhat intentional as we don't commit the built source to the repo.  This is the convention that most npm packages follow.
