### ISSUE TITLE
Include SCSS files in NPM release

### ISSUE THREAD

**Issue by 321ckatz123** [Hacker0x01/react-datepicker#619]
Can you please include the SCSS files in the output when this is required from NPM? I understand the potential ramifications of this decision as far as potential bugs (I changed the default font-size and now it doesn't work... help), but it is somewhat annoying to have to copy the CSS file into a custom CSS file and either convert it THERE to be SCSS or create overrides for the CSS and override the old school way.

**Comment by jeremija** [comment]
You can import the `.css` file by omitting the extension. I have this in my `.scss` file:

```css
@import "../node_modules/alertifyjs/build/css/alertify";
```

**Comment by dherran** [comment]
They should be included imo, for people who want to customise them. It's very annoying having to come back to the Github repo to manually pull the SCSS files everytime they change.

**Comment by lorinkoz** [comment]
Agreed, I also need this, plz.

**Comment by floriangosse** [comment]
It would be nice to have the scss files included. I have currently the problem that I can't increase the size of the component easily because everything depends on the body.
