### ISSUE TITLE
Some issue when the number of rows exceeds 5 in a month.

### ISSUE THREAD

**Issue by vk92kokil** [Hacker0x01/react-datepicker#620]
I have attached a gif, i was facing the same issue in my code. When you go to some months like October 2016 or April 2017, the calendar hangs up when you press right or left arrow. [It happens only when the calendar opens up on the top].

![calendar](https://cloud.githubusercontent.com/assets/5166213/20130669/735893c0-a67e-11e6-80f0-5380623f910b.gif)

**Comment by rafeememon** [comment]
#361
