### ISSUE TITLE
Paste from clipboard

### ISSUE THREAD

**Issue by dmr** [Hacker0x01/react-datepicker#621]
I was trying to paste a date from clipboard into the input but the demo code didn't accept my input.
Is it possible to include that feature?

**Comment by jochenberger** [comment]
What demo code do you mean? I can paste a date into the "Default" example on https://hacker0x01.github.io/react-datepicker/.

**Comment by MikaelCarpenter** [comment]
I have this issue if I paste a date that has extra whitespace: `03/15/2017 `

**Comment by dmr** [comment]
About 80% of our users paste things with whitespace from my experience ^^

**Comment by MikaelCarpenter** [comment]
Yea i actually just submitted a PR to fix the issue.

**Comment by MikaelCarpenter** [comment]
https://github.com/Hacker0x01/react-datepicker/pull/717
