### ISSUE TITLE
 onChange event not working when input is provided in text field

### ISSUE THREAD

**Issue by manishstrivepool** [Hacker0x01/react-datepicker#622]
The onChange event only works only when date is selected  from the datepicker.
As soon as the data is entered in the very next "text"  field or "textarea"  the selected date get disappeared and when clicked on submit it don't pass any value in date field. It  passes an empty value for that specific field.

**Comment by syabro** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/426
