### ISSUE TITLE
Calendar pop-up window does not close if using Macbook touchpad

### ISSUE THREAD

**Issue by ignatif** [Hacker0x01/react-datepicker#628]
Yes, it sounds strange but this is how it is.
I have Macbook Pro 2011, and when i click on some date(day number), window doesn't close(it closes for a millisecond, then it appears again).

I recorded a video.
https://monosnap.com/file/iC6HuXQjChtF0QVNGaFAQH5Xfz7bxv

It only happened when i touched the touchpad. If i 'clicked' it or used a mouse everything was fine.
I wonder that there were not such issue. I tested it on my friend's Macbook Pro 2014 and there was the same issue.

I figured out that it happened because onFocus event ran after onSelect. I fixed it by prohibiting onFocus event for 40 milliseconds after onSelect event. It fixed this problem, and i don't think it caused anything else to break.

**Comment by Kadrian** [comment]
I would highly appreciate this, I'm having the same issue
