### ISSUE TITLE
react 15.4:  attempting to use a component class or function as a mixin

### ISSUE THREAD

**Issue by aferrandi** [Hacker0x01/react-datepicker#630]
It looks like the code:

mixins: [require('react-onclickoutside')],

found for example in **year_dropdown_options.jsx**, causes the error:

ReactClass: You're attempting to use a component class or function as a mixin. Instead, just use a regular object.(…)

when used with react 15.4. 
Am I using the component in the wrong way?

**Comment by plentz** [comment]
duplicates #536

**Comment by jochenberger** [comment]
Should be fixed with #651.

**Comment by martijnrusschen** [comment]
Fix has been merged. Will be released soon.
