### ISSUE TITLE
Position of the month container

### ISSUE THREAD

**Issue by epsyan** [Hacker0x01/react-datepicker#635]
What should I do if I place date picker at the top-right corner of the page ? Month container becomes half-hidden to the right border of the browser window. Is there any solution? 
[bug_demo](https://dl.dropboxusercontent.com/u/97915091/ShareX/2016/11/webstorm64_2016-11-23_17-04-33.png)

P.S. I've tried to use popoverAttachment="top right". But it looks like it works incorrect
[bug_demo_2](https://dl.dropboxusercontent.com/u/97915091/ShareX/2016/11/webstorm64_2016-11-23_17-08-19.png)

**Comment by ian-moore** [comment]
Also seeing this behavior, the docs are not clear on what the options for the position props actually impact

**Comment by subuta** [comment]
Latest example contains `popperPlacement` example. It might work for you guys!

https://hacker0x01.github.io/react-datepicker/

```jsx
<DatePicker
    selected={this.state.startDate}
    onChange={this.handleChange}
    popperPlacement="top-end"
    popperModifiers={{
      offset: {
        enabled: true,
        offset: '5px, 10px'
      },
      preventOverflow: {
        enabled: true,
        escapeWithReference: false, // force popper to stay in viewport (even when input is scrolled out of view)
        boundariesElement: 'viewport'
      }
    }}
/>
```

These values are valid for `popperPlacement` :)

```
export const popperPlacementPositions = [
  'auto',
  'auto-left',
  'auto-right',
  'bottom',
  'bottom-end',
  'bottom-start',
  'left',
  'left-end',
  'left-start',
  'right',
  'right-end',
  'right-start',
  'top',
  'top-end',
  'top-start'
]
```

https://github.com/Hacker0x01/react-datepicker/blob/c179eecbe80885e410e4d8e2a7d776c0e7f644ef/src/popper_component.jsx#L5

**Comment by iisa** [comment]
hi, wanted to check in. Really love this datepicker, though it seems that the popperPlacement is not working. Not even in the demo. if you scroll the popperPlacement example a lil higher than the midline of the window, it will drop below the input

**Comment by caitlin** [comment]
The popper position seems to work fine for me, but the triangle isn't scooting over to the other side (for `bottom-end`). It looks like the CSS in react-datepicker.css is missing special styles for "end".

**Comment by carmouche** [comment]
I was experiencing the same thing as @iisa.
After a ton of searching, it seems that you need to set the flip modifier to `enabled: false` to prevent it from flipping when it reaches the boundaries of the page. 
https://popper.js.org/popper-documentation.html#modifiers..flip

I updated my props to:

`
<DatePicker
  popperPlacement="botom-start"
  popperModifiers={{
    flip: {
      enabled: false
    },
    preventOverflow: {
      enabled: true,
      escapeWithReference: false
    }
  }}
/>
`

**Comment by evepen1** [comment]
Facing the same issue with react-datepicker placed on top-right corner of the screen.

The below code worked for me check it out: 

.react-datepicker-popper[data-placement^=bottom] .react-datepicker__triangle {
    margin-left: 8em; 
}

**Comment by canhoviet** [comment]
Basically, @carmouche 's solution works. However, when it comes into `time picker`, it doesn't work correctly: the time picker is still hidden (see red rectangle on the top right)

<img width="234" alt="screen shot 2018-08-01 at 5 40 08 pm" src="https://user-images.githubusercontent.com/7037154/43517302-694cc61a-95b2-11e8-8f42-4eea58c696a4.png">

This is b/c the time container element is positioned as `absolute` and thus taken out of the normal flow. Therefore, the `popper` only takes `date` (in red)
![screen shot 2018-08-01 at 5 47 44 pm](https://user-images.githubusercontent.com/7037154/43517570-6821d0f4-95b3-11e8-9903-736cb4849ecf.png)
 container's width into account.

Modifying the CSS may solve the issue but it has the risks of introducing other regression issues if not careful.

**Comment by JulsRicketti** [comment]
Coming in late for the party, so perhaps things have changed since this thread was last updated.

I am having the issues of the DatePicker's popper being rendered off screen when I open it. The `popperPlacement` and `popperModifiers` props do nothing for me.

This is roughly what my code looks like:

```
 <DatePicker
            popperPlacement='top'
            showTime={true}
            value={date}
            onChange={date => setDate(date)}
          />
```

This is how it looks when being rendered:

![Screen Shot 2019-10-23 at 4 30 32 PM](https://user-images.githubusercontent.com/886808/67432228-eadfd700-f5b3-11e9-93f5-eaa2fc60a5d1.png)


Not sure where to take it from here.

**Comment by maedi** [comment]
@JulsRicketti Is there enough room beneath the calendar popup? If you scroll down the screen does it switch from being on top to below? That's the problem I had, with the developer console open there was just never enough room.

From what I can tell the library still uses the `popperPlacement` variable and defaults to 'bottom-start' placement:
https://github.com/Hacker0x01/react-datepicker/blob/master/src/popper_component.jsx#L22

**Comment by yosagar** [comment]
use **popperPlacement='top-start'** to open it on the top side.

![image](https://user-images.githubusercontent.com/25338187/93302905-49d7bb80-f818-11ea-8f13-7e04fbf92034.png)
