### ISSUE TITLE
Failure to call .focus() on custom input after selecting a date

### ISSUE THREAD

**Issue by avindra** [Hacker0x01/react-datepicker#636]
With a `customInput` set, where `customInput` has the `<input>` element deeply nested, `react-datepicker` will throw:

```
Uncaught TypeError: this.refs.input.focus is not a function(…)
```

after a date is selected.

A simple way to fix this behavior is to skip the `.focus()` step if `customInput` was passed.

Not sure what a clean solution would be to better support `customInput`.

**Comment by jochenberger** [comment]
Can't use SFCs as custom inputs either because they cannot have refs.

**Comment by jochenberger** [comment]
I ended up implementing a `focus` function in my custom component that focuses the input: http://codepen.io/jochenberger/pen/qqKrPd
That's pretty advanced stuff though, I with it was easier. This should probably go into the documentation.
cc @martijnrusschen

**Comment by dvdgarcia** [comment]
Same error here. I think we should be able to overwrite the onFocus like with onBlur or onChange.
I noticed that if I call the e.preventDefault in my own onBlur, i have not this error, but I lose the dateValidation.
So I think that if we use a customInput, we should have the focus event inside our component and we decide if we focus or not, for example in my case I have to change the focus to other element once I selected a date.

**Comment by seafarring13** [comment]
We are looking for this update as well. We had to use a custom input for layout/styling requirements and also see this error being thrown.

**Comment by crabicode** [comment]
No updates?

**Comment by stamkov-sc** [comment]
You can fix error if overwrite onBlur event in custom input  like `<input type="text" onBlur={()=>{}}/>`

**Comment by gigaga** [comment]
@stamkov-sc Does not work for me... :(

**Comment by aij** [comment]
@seafarring13 Does your custom input have a `focus()` method?

**Comment by ernani** [comment]
This is not working for me, I have a functional component, won't work with `this`

**Comment by janhartmann** [comment]
Verified custom text input does throw this error
