### ISSUE TITLE
Layout is broken for showYearDropdown=false showMonthDropdown=true

### ISSUE THREAD

**Issue by jochenberger** [Hacker0x01/react-datepicker#646]
`.react-datepicker__header__dropdown react-datepicker__header__dropdown--select` has a margin of `-16px` (https://github.com/Hacker0x01/react-datepicker/commit/95a870ac91b3cc76c3f9f3fca32975c2a2825e22#diff-9da5657b359639ae904fe748a1fb2b4cR43). This was probably added to "remove" the additional margin that is added when using a year dropdown (https://github.com/Hacker0x01/react-datepicker/blame/95a870ac91b3cc76c3f9f3fca32975c2a2825e22/src/stylesheets/datepicker.scss#L59). But if the date picker does not have a year dropdown, there is no additional margin to remove and the month picker ends up 16px too high.

**Comment by jochenberger** [comment]
See https://codepen.io/anon/pen/GNyJPN

**Comment by jochenberger** [comment]
It also breaks if you only specify `dropdownMode="select"`: https://codepen.io/jochenberger/pen/jVYbwX

**Comment by martijnrusschen** [comment]
Interesting, would you be able to fix this and create a PR?

**Comment by jochenberger** [comment]
Actually, I'm not sure how. It looks pretty complicated to me the way it is. Absolute positioning combined with magic-number margins. I think we should get rid of those altogether but since there are so many possible combinations of the dropdown options, I'm not sure how to fix it without breaking something else.
