### ISSUE TITLE
Bugs in latest version

### ISSUE THREAD

**Issue by gazpachu** [Hacker0x01/react-datepicker#650]
.react-datepicker__navigation is missing z-index: 1

**Comment by martijnrusschen** [comment]
Any chance you can add it in?

**Comment by gazpachu** [comment]
@martijnrusschen I've forked the repo and when I was going to add it, it was already there O_O. I'm not sure why is not appearing in my app.
<img width="389" alt="screen shot 2016-12-02 at 11 45 24" src="https://cloud.githubusercontent.com/assets/1721288/20831268/81169d96-b884-11e6-8214-9fae0c5362b4.png">


<img width="408" alt="screen shot 2016-12-02 at 11 43 59" src="https://cloud.githubusercontent.com/assets/1721288/20831249/6972296c-b884-11e6-899b-720d1822fac9.png">

**Comment by gazpachu** [comment]
I've also noticed that, when creating two datepickers and set as a range (like in [example 12](https://hacker0x01.github.io/react-datepicker/#example-12), after the range is set, if I alter the end date to an earlier date than the start date, then the start date doesn't update itself automatically like in the example.

**Comment by mnbucher** [comment]
Also had this issue... adding  `.react-datepicker__navigation { 
z-index: 1 
}`  solved the problem for me.
