### ISSUE TITLE
Issues with Datepicker and Bootstrap Modal

### ISSUE THREAD

**Issue by jochenberger** [Hacker0x01/react-datepicker#652]
See http://codepen.io/jochenberger/pen/rWpQZN
In Firefox 50 on Debian Linux, the select field does not open (or it looks as if the options are hidden). Firefox 45.5.1 on Windows does not work either. Chrome works fine. I have no idea what's happening. :-(

**Comment by jochenberger** [comment]
It also works fine in Edge and works... sometimes... in IE11. I wonder if it's a rendering or a JavaScript issue...

**Comment by jochenberger** [comment]
Never mind, it's caused by react-bootstrap. The `Modal` tries to keep focus and that trips Firefox. You can set `enforceFocus` to `false` on the `Modal`. See http://react-bootstrap.github.io/components.html#modals-props-modal

**Comment by innopal** [comment]
Not sure why this is closed!
The suggested answer by @jochenberger compromises the accessibility of the bootstrap modal.
Is there any other solution other than turning off enforceFocus?

Cheers
