### ISSUE TITLE
Pick day by arrows is possible, when maxDate prop is defined

### ISSUE THREAD

**Issue by epsyan** [Hacker0x01/react-datepicker#659]
I've set up maxDate as today. 
I Can't pick a date later than today by the mouse. But can pick it by keyboard arrows.
[Screenshot_from_dec_2nd](https://dl.dropboxusercontent.com/u/97915091/ShareX/2016/12/chrome_2016-12-02_17-24-39.png)

**Comment by SanyasiraoM** [comment]
Duplicate of https://github.com/Hacker0x01/react-datepicker/issues/720
