### ISSUE TITLE
Date picker does not close after selecting/changing a date only on IPhone IOS

### ISSUE THREAD

**Issue by monkeyjs978** [Hacker0x01/react-datepicker#661]
I am seeing this issue only on iPhone/safari - works fine on desktop, did any one else face this issue? Also when I inspect in mobile view on chrome the problem is there, works totally fine on desktop. Tried adding a ref and doing this.refs[calender].setOpen(false) - getting setOPen of undefined error here..

**Comment by splendidtrade** [comment]
Issue is gone if I use the CustomInput.

**Comment by jochenberger** [comment]
Does this still happen with 0.37.0?

**Comment by jochenberger** [comment]
Could this be related to #597?
