### ISSUE TITLE
Should not select disabled date when use arrow keys

### ISSUE THREAD

**Issue by twoeo** [Hacker0x01/react-datepicker#662]
See official example [Filter dates](https://hacker0x01.github.io/react-datepicker/#example-11)

When use arrow key to change date,

disabled date would still be selected. (Saturday & Sunday)

![](http://i1.piimg.com/567571/06faa02e946362f8.png)

**Comment by lbelinsk** [comment]
I have encountered this issue also in my end...

**Comment by josiahgallen** [comment]
I am also seeing the same issue, @lbelinsk how did you work around it?

**Comment by benbcai** [comment]
This issue should be resolved in the latest version. You can still use the arrows keys on the keyboard to navigate to the disabled dates but you can not select them.

**Comment by josiahgallen** [comment]
Thanks @benbcai! I realized this after I posted the question.

**Comment by lbelinsk** [comment]
@benbcai I guess this isn't relevant anymore :)

**Comment by benbcai** [comment]
@martijnrusschen @rafeememon I believe this was resolved by https://github.com/Hacker0x01/react-datepicker/pull/673 in version 0.41.0. Can this issue be closed?
