### ISSUE TITLE
onChange event

### ISSUE THREAD

**Issue by TrejGun** [Hacker0x01/react-datepicker#664]
Hi there!
Thanks for awesome datepicker
I wander is it possible to have `input` as event.target in onChange event rather than table cell

```js
<DatePicker
	onChange={(moment, event) => {
		// event.target points to table cell (div)
	}}
/>
```

**Comment by Vellames** [comment]
Someone can help me to? I have the same problem

**Comment by VadimGorbenko** [comment]
Any update?
I wanna get event.target.name in onChange event object but event.target linked on div..
