### ISSUE TITLE
Showing error message under date-input

### ISSUE THREAD

**Issue by vinayshetty88** [Hacker0x01/react-datepicker#665]
Scenario : 
1.) Enter Invalid date inside date-input
2.) Validate Date entered inside date-input on certain criteria 

If either of these above scenarios fail , I would like to show an error message such as a label as below 

![image](https://cloud.githubusercontent.com/assets/21378724/20968499/cfe7a8e6-bcaa-11e6-8b2d-5158c707ecbc.png)

Any current way to do this ?

**Comment by amityb** [comment]
You can do this externally to the react-datepicker component source code.  

Place your validation inside a function that is called in your render() function.  It can return the error message and validation state (invalid or valid).  Then you can conditionally render the error message in your render function.
