### ISSUE TITLE
Internal representation of time in UTC is wrong

### ISSUE THREAD

**Issue by alex-shamshurin** [Hacker0x01/react-datepicker#679]
When user pickups some date he intended to select exactly that date which has been choosen, it must be not calculated or transformed somehow.  But I think in datePicker the date is stored in UTC.

Well, my issue is about `minDate` and `maxDate`. I live in GMT +3, so at 01.00 AM local time is already 'tommorow', whereas UTC time is still 'yesterday'. So it leads to incorrect `minDate` date. User can chose previous date which totally breaks down a business logic.  To workaround I have to add time offset to moment constructor.

**Comment by TrejGun** [comment]
It should store date in UTC for simpler calculation

for example you are in GMT+3 and I'm in GMT+8
so at the same time you select 10am and me - 3pm
`new Date().toISOString() // 2016-12-24T07:00:00.000Z`
you store both in UTC in DB and then show it like
`new Date("2016-12-24T07:00:00.000Z").toString() // Sat Dec 24 2016 15:00:00 GMT+0800 (WITA)`

meanwhile if you store relative time you have to store your and mine UTC offset
`const date = new Date()`
`const x = {date: date, offset: date.getTimezoneOffset()}`
then
`const d = new Date(x.date); d.setMinutes(x.offset); d.toString()`
so you have more data in db, more calculation to show date, and extremely hard calculations to get time difference and range difference

**Comment by alex-shamshurin** [comment]
I agree, in DB time values must be stored in UTC, it's doubtless. But in my case it's just a train ticket date which user selects from the form. User cannot choose "yesterday" date, it's a relative value. It must be taken from user's browser and it's local time. It applies to the user only, it doesn't matter what is the time of other users. I need simply "today" and all following dates. So the internal date representation in Datepicker must be in local time. If I need to extract UTC time to store it in DB, it's a programmer's responsibility to do it.

**Comment by alex-shamshurin** [comment]
+1

**Comment by martijnrusschen** [comment]
This should be fixed now. Please let me know if this isn't the case.
