### ISSUE TITLE
Can't resolve file or directory ./styles in react-datepicker/dist

### ISSUE THREAD

**Issue by alex-cory** [Hacker0x01/react-datepicker#681]
I think this might be a variable name collision, but I'm not 100% sure.  We use the `Webpack.DefinePlugin` to allow us to use the `s` variable in our components.  Is this what could be causing the issue?  I tried excluding `node_modules` using thing `webpack-node-externals` package, but still no luck.  Any ideas?

Console:
![image](https://cloud.githubusercontent.com/assets/5455859/21510370/5a9bd376-cc47-11e6-8ea7-96621f9b1628.png)

Browser Console:
![image](https://cloud.githubusercontent.com/assets/5455859/21510401/af711852-cc47-11e6-85a5-2ea5fec7cfd2.png)

**Comment by alex-cory** [comment]
Ohhh.... You don't support css modules.. ok

**Comment by rafeememon** [comment]
@alex-cory, feel free to help out to get CSS modules working
