### ISSUE TITLE
Should not automatically select the date while navigating with the keyboard

### ISSUE THREAD

**Issue by lbelinsk** [Hacker0x01/react-datepicker#682]
I would expect that while navigating with the keyboard, the value of the date (in the Input) won't get set until the user presses Enter key.

It isn't an expected behaviour when the user presses 'Escape' key, that the value will indeed get selected. that means that Enter and Escape have the same roll which is solely to close the Calendar..

**Comment by mgrdevport** [comment]
Resolved by #673 ?
