### ISSUE TITLE
Date range with multiple months

### ISSUE THREAD

**Issue by mir3z** [Hacker0x01/react-datepicker#684]
I use DatePicker to select date range as stated in https://hacker0x01.github.io/react-datepicker/#example-12 and I've set multiple months visible to 2. The problem is that selected date is always shown within first month, whereas I would like it show start date as first month and end date as second month. Is it possible?

**Comment by The-Code-Monkey** [comment]
this is something im looking into too and it would be so much smoother to be able to do that rather than 2 boxes

**Comment by mudassirmmt** [comment]
I need to pre-populate multiple date range in range picker. How i need to implement

**Comment by JoyLubega** [comment]
@mudassirmmt this could help 
`<DatePicker
  inline
  selected={this.state.startDate}
  startDate={this.state.startDate}
  endDate={this.state.endDate}
  onChange={this.handleDateSelect}
  monthsShown={2}
  shouldCloseOnSelect={false}
/>`

**Comment by mudassirmmt** [comment]
> @mudassirmmt this could help
> 
> ```
> <DatePicker
>   inline
>   selected={this.state.startDate}
>   startDate={this.state.startDate}
>   endDate={this.state.endDate}
>   onChange={this.handleDateSelect}
>   monthsShown={2}
>   shouldCloseOnSelect={false}
> />
> ```
Thanks. 
But i need to display multiple date range at once in the date range picker. 
My requirement is to select date range at once at a time but need to pre populate(dispaly) all date ranges at once in the calender.

**Comment by sanjar-162** [comment]
Any updates on this?
