### ISSUE TITLE
Add custom css class to calendar itself, not to input

### ISSUE THREAD

**Issue by mir3z** [Hacker0x01/react-datepicker#686]
Feature request

**Comment by cnolimit** [comment]
Had to update the `react-datepicker/dist/react-datepicker.css` file to achieve the behaviour that i wanted. would be good to be able to target the parent and apply styles.

**Comment by Aarbel** [comment]
any news about it ?

**Comment by 12tp12** [comment]
any update on this?

**Comment by Aarbel** [comment]
@martijnrusschen @RSO @rafeememon when could we include this simple feature ?

**Comment by aij** [comment]
@Aarbel Have you submitted a PR?

**Comment by Aarbel** [comment]
i think it will take a long time for me to make a clean PR, so better to fix by main contributors :+1:

**Comment by rafeememon** [comment]
@Aarbel, given that this feature request has been open for over a year, it will be included much more quickly with the help of outside contributions.

**Comment by CaitlinWeb** [comment]
@Aarbel You can use the prop `calendarClassName`, eg:
```jsx
<DatePicker calendarClassName="custom-class-name" />
```

Looks like it has been supported for some time as of #715.

**Comment by Aarbel** [comment]
i'm not working on it right now, not the time those days
