### ISSUE TITLE
Is it possible to manually set the position of the calendar ?

### ISSUE THREAD

**Issue by cnolimit** [Hacker0x01/react-datepicker#687]
is it possible to manually set wether the calendar displays from the top or the bottom of the input?

[![Screen Shot 2017-01-05 at 10.25.15.png](https://s27.postimg.org/e0wwzvfwj/Screen_Shot_2017_01_05_at_10_25_15.png)](https://postimg.org/image/v1ft8jsxr/)

[![Screen Shot 2017-01-05 at 10.25.26.png](https://s29.postimg.org/s1f884mpj/Screen_Shot_2017_01_05_at_10_25_26.png)](https://postimg.org/image/pwuv71l2r/)

**Comment by mir3z** [comment]
See https://hacker0x01.github.io/react-datepicker/#example-16

Datepicker uses [tether.io](http://tether.io/) to position popover. You are looking for `popoverAttachment`, `popoverTargetAttachment`, `popoverTargetOffset` props.

**Comment by cnolimit** [comment]
thanks thats exactly what i was looking for, i must of scrolled past it when i checked the examples 🙈

**Comment by martijnrusschen** [comment]
Awesome, closing this now :)
