### ISSUE TITLE
Calendar jumps around when changing months

### ISSUE THREAD

**Issue by MikaelCarpenter** [Hacker0x01/react-datepicker#688]
So I have an issue where my calendar is set to use
```
popoverAttachment: 'top left'
popoverTargetAttachment: 'bottom left'
popoverTargetOffset: '10px 0px'
```

This works fine, however if the datepicker happens to be at the bottom of the browser window, the calendar shows above the datepicker. That's fine except that as you cycle through the months, when you got to a month that has a different number of rows, the calendar is no longer aligned and will start jumping around to try to fix alignment. Once the calendar is misaligned you can click the month name and it will try to align or you can click the arrow and it tries to align but it's not working properly.

Example:
![datepicker](https://cloud.githubusercontent.com/assets/8742292/21694191/d6532404-d338-11e6-9c95-13f67ff7dda5.gif)

**Comment by rafeememon** [comment]
This is one of our favorite issues  #361
