### ISSUE TITLE
Add ability to disable days in the future or past 

### ISSUE THREAD

**Issue by lbekkema** [Hacker0x01/react-datepicker#69]
The datepicker ables users to select dates in the future or past, but for some cases these dates are not applicable. For example if you'd have a dashboard, you want to force users to only select dates in the past. Or if you'd have an appointment scheduler you want to force users to select dates in the future.

**Comment by hahahana** [comment]
I took a stab at this [in my repo](https://github.com/hahahana/react-datepicker/pull/3/files). It depends on my other PR [(#72)](https://github.com/Hacker0x01/react-datepicker/pull/72), so I haven't submitted it here yet.

**Comment by azizijunaid** [comment]
for past date disbable

const today = new Date();
<DayPicker disabledDays={{ before: today }} />,

**Comment by sabinbogati1** [comment]
Did anyone solved it??

**Comment by yashmiRajamanthrie** [comment]
import moment from 'moment';
 
minDate={moment().toDate()}

try this ,

**Comment by annadayadev11** [comment]
> import moment from 'moment';
> 
> minDate={moment().toDate()}
> 
> try this

Hi, it's working, how can I also disable future date? Thank you.

**Comment by satish769843** [comment]
> > import moment from 'moment';
> > minDate={moment().toDate()}
> > try this
> 
> Hi, it's working, how can I also disable future date? Thank you.

use maxDate
