### ISSUE TITLE
Datepicker to receive views as props

### ISSUE THREAD

**Issue by frontsideair** [Hacker0x01/react-datepicker#692]
First of all, thanks for the excellent datepicker. I want to use this on our project but I want to adapt it to our look&feel. I'd like to develop this feature so I can provide `Day` and `Month` components to `Datepicker` as props. I'll send a PR as soon as I'm done. (I'll probably componentize other parts of view as well.)

**Comment by frontsideair** [comment]
It's been a year and my suggestion has emerged as a pattern called "render props". But this requires a lot of effort to refactor, which I can't do right now. Feel free to close or promote to a feature request with a help wanted tag.

**Comment by brennowilliam** [comment]
Hi guys, I've been wanting to contribute to this project. Can I try to tackle this feature?
If so, could you provide me some guidance?
