### ISSUE TITLE
Datepicker on mobile device - Suggest using a portal/overlay

### ISSUE THREAD

**Issue by ro-savage** [Hacker0x01/react-datepicker#695]
I have been testing out the datepicker for a project I am working on, but have found the user experience on mobile not to be very good.

<img src="https://cloud.githubusercontent.com/assets/9244507/21877229/8065dcd8-d8ee-11e6-8cb5-26feda0ff77f.png" width="400" />

I took a look at how [airbnb's react-dates](https://github.com/airbnb/react-dates) handle mobile and found they use a portal/overlay.

<img src="https://cloud.githubusercontent.com/assets/9244507/21877296/df81d492-d8ee-11e6-8abc-cbf325067654.png" width="400" />

**I suggest making a similar overlay for react-datepicker.**

**Comment by ro-savage** [comment]
I have created PR #696  the adds the the prop `withPortal` which creates the calendar in a portal/overlay.

Here it is running on my project.

<img src="https://cloud.githubusercontent.com/assets/9244507/21877642/48b82ad6-d8f1-11e6-86b6-9ca0e8a45563.png" width="400" />

Happy to hear any feedback.

**Comment by martijnrusschen** [comment]
Pushed 0.40.0 with this included.

**Comment by leomyth330** [comment]
`withPortal` works great on desktop browser.
When I test on mobile, it doesn't prevent outside touch events and if I click button behind overlay, it's click event works.
And browser console says 

> Unable to preventDefault inside passive event listener invocation
