### ISSUE TITLE
scary error if Date object is used instead of moment

### ISSUE THREAD

**Issue by mvolkmann** [Hacker0x01/react-datepicker#700]
The start and end date values must be moment objects, not Date objects.
If you forget about this, you'll get this rather scary error message:

warning.js:36 Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().
Invariant Violation: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().

Maybe this component could check for that and give a more reasonable error message.

**Comment by martijnrusschen** [comment]
Moment.js was removed in #1527, starting v2.0.0, this package doesn't use Moment anymore.
