### ISSUE TITLE
FilterDate: Only current month shown on the Calendar

### ISSUE THREAD

**Issue by komlanvi** [Hacker0x01/react-datepicker#701]
Hi,

I wanted to make the user able to only pick a date in the current month shown on the Calendar. I have been able to do this by defining the function passed to `filterDate` as this:

![fiilterdate](https://cloud.githubusercontent.com/assets/8933992/21937944/71e235f0-d9b9-11e6-8f66-d6b16c2fbecf.png)

Is there another way to get the current month shown on the Calendar than this `this.refs.datePicker.refs.calendar.refs.instance.state.date` ?

**Comment by rafeememon** [comment]
Why not pass in `minDate` and `maxDate` to be the beginning and the end of the month in question?

**Comment by komlanvi** [comment]
Your suggestion work when the user can't change the month like in the example on the main website.

![jan](https://cloud.githubusercontent.com/assets/8933992/21938597/4a0a2b48-d9bc-11e6-9dbb-ad781804398c.png)

But in my case the user must also be able to change the month. Maybe I misunderstood some point ??

**Comment by rafeememon** [comment]
What is the use case for restricting the selected day to the current month, yet also allowing changing months?  Isn't this equivalent to allowing the user to select a day with no restrictions?

**Comment by rafeememon** [comment]
If you're talking about the days from the previous and next month in the monthly view, you can style the `react-datepicker__day--outside-month` CSS class to suit your needs, possibly with `pointer-events`.

**Comment by komlanvi** [comment]
Yes that's partially what I tried to explain but I did not explain myself well. The goal is to disable (not only style) the next and prev month days from the monthly view.

**Comment by amajor** [comment]
I've been able to detect which month the user is viewing by passing a function in to the _[onMonthChange](https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md#onmonthchange)_ prop for the date picker.

I initialize a state, _monthBeingViewed_, as 'current', then in _handleMonthChange()_ I check to see which month is being viewed and compare it with the current month to tell where I am in the calendar, setting my state to reflect what I need to know.

So something like this:

```javascript
handleMonthChange(monthBeingViewed) {
    const currentMonth = moment();
    if (monthBeingViewed.isSame(currentMonth, 'month')) {
        this.setState({ monthRelation: 'current' });
    } else if (monthBeingViewed.isAfter(currentMonth, 'month')) {
        this.setState({ monthRelation: 'future' });
    } else {
        this.setState({ monthRelation: 'past' });
    }
}
```

You can compare it to the current month using [isBefore()](https://momentjs.com/docs/#/query/is-before/), [isSame()](https://momentjs.com/docs/#/query/is-same/), etc.

And then in the date picker that you're rendering...

```javascript
render() {
    return (
        <DatePicker
            onMonthChange={this.handleMonthChange}
        />
    );
}
```

**Comment by mtrabelsi** [comment]
So sad that is not included in the doc, I will have time to make a lot of contribution for this..

**Comment by martijnrusschen** [comment]
Hi @mtrabelsi, feel free to improve our documentation/readme/examples. I'd love to get some extra thoughts on this how to improve and make this developer friendly. Feel free to open a PR with updated and changes.

**Comment by mtrabelsi** [comment]
I'm able to solve this using : 

```
       .react-datepicker__day--outside-month {
                color: transparent;
                pointer-events: none;
              }
```

here the result : 
![screen shot 2017-09-11 at 12 40 36](https://user-images.githubusercontent.com/7538862/30272587-71e24712-96f5-11e7-939e-8ef7cfc60ec3.png)

**Comment by jasonellington** [comment]
@mtrabelsi where does this CSS go in relation to your datepicker component?

**Comment by mtrabelsi** [comment]
@jasonellington I use both, to style a single day based on some specific test then I use classname, but when I want to style the default layout for the Date picker ( as you can see in my screenshot ) I hook with the style names and override them with my style - pretty handy and quick to understand. But expect to do some CSS debugging to know which is the best class to Hook. ;)

**Comment by jasonellington** [comment]
@mtrabelsi Interesting, I am using your suggestion and the dates are still visible, only the pointer-events: none; is working :/

**Comment by jasonellington** [comment]
@mtrabelsi how did you edit other css properties? It seems from your attached image that were able to change colors, font, selected date icon, etc... I didn't see any directions for this on the docs

**Comment by waheedsid** [comment]
@jasonellington I think he would dig in the classes from the debugger and appy styles to it, I was able to get his solution working and did not need visibility:hidden, but I still could not take out the space being taken by that transparent dates, there is lot of space at the bottom of the month. any ideas?

**Comment by mtrabelsi** [comment]
Hey guys, I have no more access to code, but I can help if you put your code here :).
I'll try to find time this weekend to make a PR.
Cheers

**Comment by dmitrystril** [comment]
> I'm able to solve this using :
> 
> ```
>        .react-datepicker__day--outside-month {
>                 color: transparent;
>                 pointer-events: none;
>               }
> ```
> Don't use _display: none_, it will break the layout ;)
> 
> here the result :
> ![screen shot 2017-09-11 at 12 40 36](https://user-images.githubusercontent.com/7538862/30272587-71e24712-96f5-11e7-939e-8ef7cfc60ec3.png)

Or just set `visibility: hidden;`

**Comment by YASHWANTH272000** [comment]
![calendar](https://github.com/Hacker0x01/react-datepicker/assets/61707045/7e190599-e546-4f03-9712-d2be2fb0f158)

I can solve this by using this code : 
.react-datepicker__day--outside-month {
  color:rgb(203,203,203);
  pointer-events: none;
}
