### ISSUE TITLE
Using a forked version of the repo

### ISSUE THREAD

**Issue by MikaelCarpenter** [Hacker0x01/react-datepicker#714]
Anyone know how to get a forked version working in a project? My `package.json` has:
```
"react-datepicker": "git+https://github.com/MikaelCarpenter/react-datepicker.git"
```
However it doesn't install the files properly. I imagine this is because the files need to be built and compiled which doesn't happen when its taken from git? I need to test out some changes before I make a PR on this repo.

**Comment by rafeememon** [comment]
Probably the quickest way to get this working is to run the build script and commit the built files to your forked repo.  Then they'll be available to your project when you install the dependency.

**Comment by MikaelCarpenter** [comment]
so oddly enough, when I install from git it only pulls down
```
LICENSE		README.md	node_modules	package.json
```
So i ended up cloning my forked version locally and running `npm install` also built the `dist` and `lib` folders. So i manually injected that into my projects `node_modules/react-datepicker` and it worked
