### ISSUE TITLE
Keyboard Navigation ignores min/max dates

### ISSUE THREAD

**Issue by MikaelCarpenter** [Hacker0x01/react-datepicker#720]
If you set a min and max date, the datepicker tries to prevent you from selecting dates outside of that range. However, the new keyboard navigation feature is able to ignore the min and max dates.

In the gif, I have min date set to `1/24/2017` and then proceed to use my arrow keys to select a date before the min date.
![keyboard-min-date](https://cloud.githubusercontent.com/assets/8742292/22272736/dce1dc58-e250-11e6-817e-47cfa89d59a1.gif)

**Comment by krismeister** [comment]
This commit, allows disabling Keyboard navigation:
https://github.com/Hacker0x01/react-datepicker/commit/1877e697221c9e3f4ed63fc5dd503ff2fdcf0aa4

pass `disabledKeyboardNavigation={true}` property.

**Comment by MikaelCarpenter** [comment]
Yup, I'm doing that for now until this issue gets fixed.

**Comment by shubhanus** [comment]
HI i am still facing this issue.

**Comment by JankoSalkovicKS** [comment]
Also, there is an issue that you can do a raw input that is outside the given range (minDate and maxDate).
