### ISSUE TITLE
not working locale

### ISSUE THREAD

**Issue by vampics** [Hacker0x01/react-datepicker#723]
Hello guys,

im a little bit confused. 

`                                <DatePicker
                                    dateFormat="DD.MM.YYYY"
                                    locale="de"
                                    selected={this.state.timeStartDate}
                                    onChange={this.timeChange}
                                />
`

In my project only the locale attribute doesnt work. 
It make no sense (e.g. en-gb) which locale i choose. Nothing changes.
Any Idea whats going on?

**Comment by vampics** [comment]
Here some more Informations:

"react": "15.4.2",
"react-dom": "15.4.2",
"react-datepicker": "0.40.0",
"moment": "^2.17.1"

**Comment by vampics** [comment]
Ah, found my mistake. Wrong path to locale. 
Sorry Guys!

**Comment by andreas-koch** [comment]
Where did you set the path to locale?

**Comment by Matus-Stastny** [comment]
You need to load locales to the browser, you should check this:
[](http://momentjs.com/docs/#/i18n/loading-into-browser/)
