### ISSUE TITLE
Add custom CSS classes to the calendar dates

### ISSUE THREAD

**Issue by gomo** [Hacker0x01/react-datepicker#726]
I request a feature add custom CSS classes to the calendar dates.

For example, it is like this.

```Jsx
<DatePicker
  inline
  highlightDates=[this.props.currentMoment]
  customCSSClassesDates={
    mySelected: [moment('2017-01-03'), moment('2017-01-04')]
  }
/>
```

In my application, there is an interface to select multiple dates from the calendar. This application switches pages by each day.

I would like to inform the user of the two states on the calendar,  "selected dates" and  "editing page date".

I used `highlightDates` to "selected dates" because there are multiple selected, but if I use 'editing page date' as` selected`, I can not select that day because `onChange` does not occur.

**Comment by Aarbel** [comment]
hi gomo, did you found a way to do it ?
