### ISSUE TITLE
The moment package should be moved to devDepencencies

### ISSUE THREAD

**Issue by DimitryKislichenko** [Hacker0x01/react-datepicker#739]
Why Moment.js is in **dependencies** section, should it be moved to **devDependencies**?

**Comment by rafeememon** [comment]
The datepicker depends on moment to run, so it cannot be moved to devDependencies.

**Comment by DimitryKislichenko** [comment]
@rafeememon then the README should be updated:

> You’ll need to install React and **Moment.js** separately since those dependencies aren’t included in the package.

**Comment by rafeememon** [comment]
I think that bit of text is a bit of a conversational piece, not direct instructions on how to use the component, but PRs to clarify the text are welcome.
