### ISSUE TITLE
Yearless datepicker

### ISSUE THREAD

**Issue by unwill** [Hacker0x01/react-datepicker#741]
How do you use the datepicker without years?

I am only interested to pick two dates without year from a calendar. Where 1st of each month is always top left, and not showing the day of week.

**Comment by rafeememon** [comment]
I don't think we can or should handle this case.  The component returns moment objects, which are always attached to a year.  Furthermore, you need to know the year in addition to the month to know how many days are in the month (February).  I think your options are

* Manually set the min/max dates to a month that looks the way you want, and override the weekday and month/year formatting
* Roll your own solution with a plain table (recommended)
