### ISSUE TITLE
Date selection for inline is broken in version 0.41.0

### ISSUE THREAD

**Issue by benbcai** [Hacker0x01/react-datepicker#745]
In version 0.40.0, when selecting a new date in the inline picker the highlight on the previously selected date is removed.

In version 0.41.0, the previously selected date remains highlighted. 

See the inline example in https://hacker0x01.github.io/react-datepicker/

**Comment by martijnrusschen** [comment]
Hmm, it seems 0.41 introduced some regressions that weren't in 0.40. Hopefully someone is able to find the root cause, so this can be fixed.

**Comment by gavacho** [comment]
git bisected to identify when the regression was introduced: https://github.com/Hacker0x01/react-datepicker/pull/715

**Comment by gavacho** [comment]
I was incorrect about the source

**Comment by gavacho** [comment]
Okay, looks like the culprit was https://github.com/Hacker0x01/react-datepicker/pull/673.
