### ISSUE TITLE
MinDate set to Today not Hiding Month Back Button

### ISSUE THREAD

**Issue by pdfabbro** [Hacker0x01/react-datepicker#753]
Hi,

I am setting the min date of the date picker to today.  It correctly disables all days before today, but it doesn't disable the back button at the top left of the calendar which takes you to a previous month.  In this demo under "specific date range" it does hide the previous month button:

https://hacker0x01.github.io/react-datepicker/

**Comment by pdfabbro** [comment]
Disregard, I just realized it's because today is the 28th of February and therefore going back to February is correct... duh

**Comment by pdfabbro** [comment]
I checked this morning and the same issue is still occurring actually.  It defaults to March 1st but the previous month button is there for all months.  How do I make it disappear?

**Comment by pdfabbro** [comment]
Any update on this?

**Comment by rafeememon** [comment]
Nope, PRs to fix the problem are welcome =)

**Comment by pdfabbro** [comment]
I'm new to Git.  What's a PR?

**Comment by pdfabbro** [comment]
It doesn't appear to have ever been fixed, but I'm no longer using react and haven't looked at this in a couple years so feel free to close
