### ISSUE TITLE
Support providing "onClear" event handler

### ISSUE THREAD

**Issue by LeoAref** [Hacker0x01/react-datepicker#762]
I see that sometimes we will need to react on the clear event, not just call `onChange` with null value

```js
<DatePicker
  selectsStart
  className="form-control"
  selected={this.props.start_date}
  minDate={moment()}
  placeholderText="Start date"
  isClearable={true}
  onChange={this.handleChange}
  // ---- onClear ---- //
  onClear={this.handleClear}
  // ---- onClear ---- //
/>
```

I can submit PR if if we agreed about that

**Comment by rafeememon** [comment]
How would this differ from the cases of `onChange` being fired with null?

**Comment by LeoAref** [comment]
@rafeememon 

Yes, it almost the same, but I see these points are valuable

1. It's declarative
2. The user won't have to check `if (date === null)`

**Comment by rafeememon** [comment]
An `onClear` handler would more declarative, but a null check isn't a huge deal IMO.  I think it would be very error-prone to have two ways of detecting the same event.  I don't think this warrants an API change since the functionality is already supported.

**Comment by LeoAref** [comment]
@rafeememon I think implementing `onClear` will lead to not firing the `onChange` event in case of clearing (to not fire it twice), and that will introduce a *breaking change*

So do you see it worth it? (honestly not)

**Comment by Jucesr** [comment]
Clicking the 'x' button when prop **isClearable** also triggers **onBlur** event which is causing me to unmount my **Datepicker component** so is not able to handle the **onChange** event. 
```js
const [isEditing, setIsEditing] = useState(true)

return <>
 {
 isEditing && 
  <DatePicker
    ....
    isClearable={true}
    onBlur={() => {
      setEditing(false)
    }}
    onChange={(date) => {
       setEditing(false);
     if (date) {
       setValue(moment(date).format("MM-DD-YYYY"))
     }else{
       setValue(undefined)
     }
     }}
  />
}
</>
```

**Comment by matiasf9** [comment]
> Clicking the 'x' button when prop **isClearable** also triggers **onBlur** event which is causing me to unmount my **Datepicker component** so is not able to handle the **onChange** event.
> 
> ```js
> const [isEditing, setIsEditing] = useState(true)
> 
> return <>
>  {
>  isEditing && 
>   <DatePicker
>     ....
>     isClearable={true}
>     onBlur={() => {
>       setIsEditing(false)
>     }}
>     onChange={(date) => {
>        setIsEditing(false);
>      if (date) {
>        setValue(moment(date).format("MM-DD-YYYY"))
>      }else{
>        setValue(undefined)
>      }
>      }}
>   />
> }
> </>
> ```

+1. Where you able to solve it @Jucesr ?

**Comment by shamseer-ahammed** [comment]
+1

**Comment by Raphaww** [comment]
Also in a Range select (2 dates) it triggers onChange twice
