### ISSUE TITLE
Date selection with key "Enter" cause an error if minDate and maxDate props are defined

### ISSUE THREAD

**Issue by guillaumesayegh** [Hacker0x01/react-datepicker#764]
Hi everyone,

I ran into an issue that is not a duplicate of #192 nor #187.
Suppose you have minDate and maxDate props defined, when you use keyboard navigation and press "Enter", I get this error:
- Uncaught TypeError: Cannot read property 'clone' of undefined

If I remove maxDate props, this error does not trigger anymore.

I use last version 0.41.1.

Any advice or help would be welcome :)
Thanks

**Comment by benbcai** [comment]
Looks like this was introduced by https://github.com/Hacker0x01/react-datepicker/pull/721/ in version 0.41.0. 

This line https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L275 still gets executed for 'Enter', 'Tab', or 'Escape' when it shouldn't and newSelection is never set to a valid date.
Maybe this entire if block (https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L239-L276) should be an elseif block.

**Comment by mvs202** [comment]
Reverting to version 0.40.0 avoids the problem.

**Comment by guillaumesayegh** [comment]
Well thank you.
I did revert to version 0.40.0 for now.

**Comment by martijnrusschen** [comment]
Have you tried upgrading to 0.42? That should solve the problem as well.

**Comment by mvs202** [comment]
yup; current version (0.44.0) fixes the problem.
