### ISSUE TITLE
Using date-picker causes error . Uncaught TypeError: Cannot read property 'startDate' of null

### ISSUE THREAD

**Issue by RajPratim21** [Hacker0x01/react-datepicker#767]
`import React from 'react'
import { connect } from 'react-redux'

import * as actions from '../actions'
import { ourState } from '../selectors'
import ResultList from './ResultList'
import styles from './Overview.css'
import { Calendar } from  'react-date-range'
//import DatePicker from './Date-picker';
//import DatePicker from 'react-datepicker'
var moment = require('moment');
import DatePicker from 'react-datepicker'
const optionsStyle = {
  maxWidth: 255,
  marginRight: 'auto',
};
 

   class Overview extends React.Component {

 mapStateToProps(state) {
  return {
    date: state.date
  };
}

   getInitialState() {
    return {
      //startDate:null
      startDate: moment()
    };
  }
 
  handleChange(date) {
    console.log(date) 
    this.setState({
      startDate: date,
       
    });
   
  }
    
   
   componentDidUpdate(){
    // Access ISO String and formatted values from the DOM.
    var hiddenInputElement = document.getElementById("example-datepicker");
    
  }
 `    
    render() {
           const { date, onChange } = this.props;
        return (
      <div>
        
               <input
                      className={styles.query}
                        onChange={e=>this.props.onInputChanged(e.target.value)}
                        placeholder="Search your memory"
                        value={this.props.query}
                        ref='inputQuery'
                        >
              </input>
              <div>
                <DatePicker>
                  selected={this.state.startDate}
                 onChange={this.handleChange}
                </DatePicker>
                
                <DatePicker>
                   selected={this.state.startDate}
                 onChange={this.handleChange}
                </DatePicker>
                
                 </div>

                          <ResultList searchResult={this.props.searchResult} />
              
      </div>
    );
                                    
            
    }

     componentDidMount() {
        if (this.props.grabFocusOnMount) {
            this.refs['inputQuery'].focus()
        }
    }
   
}

const mapStateToProps = (state) => ({
    query: ourState(state).query,
    searchResult: ourState(state).searchResult,
})

const mapDispatchToProps = (dispatch) => ({
    onInputChanged: input => {
        dispatch(actions.setQuery({query: input}))
    },
})

export default connect(mapStateToProps, mapDispatchToProps)(Overview)`

**Comment by Anaskhalifa** [comment]
This was in 11 Mar 2017 so did you resolve the problem ?

**Comment by emiliosanches** [comment]
Same here...
Already updated packages and still having this issue
