### ISSUE TITLE
Accessibility issue:  Invalid date string gets overwritten when leaving input field

### ISSUE THREAD

**Issue by greg-a-smith** [Hacker0x01/react-datepicker#768]
When the input field loses focus and the field contains an invalid date string, it is clearing the field and restoring the previously-selected date (or blank if none was previously selected).  This is an accessibility issue because when the field is overwritten back to the previous date, there is nothing that would notify a screen reader that it occurred.

We would like to propose a propType to disable the auto-correction of invalid dates.  Our consumers of this DatePicker would handle their own date validation and could mark the field as "invalid" which would alert a screen reader of the state change.

**NOTE:  We have a proposed solution in PR #769 .**

**Comment by aij** [comment]
I think any fix for #547 will be also fix this issue in a more general way. Would you mind giving #773 a spin?

IMHO, it would also be nicer to have the less annoying behavior by default rather than having to explicitly enable it via a prop. Is it even worth making the current behavior of losing user input an option?

**Comment by greg-a-smith** [comment]
@aij I checked out your pull request #773 and this seems to be a good solution for this issue.  My current pull request #769 could be closed if your pull request got approved and merged.

As for whether it is default behavior or enabled via a prop -- default is always nice, but it doesn't matter to me either way.  We use a component in our library that wraps the react-datepicker component so it would be invisible to our consumers.

**Comment by aij** [comment]
Fixed in #773
