### ISSUE TITLE
I can't find a way to intercept the onChange trigger?

### ISSUE THREAD

**Issue by tusharchhibber** [Hacker0x01/react-datepicker#770]
First of all, sorry if my formatting of my question is wrong. It is my 1st time. 

Currently I am using DatePicker sending the dateFormat as 'DD-MMM-YY'. The problem is as soon as I start typing eg. 13-MAR-2017... as I reach 13-MAR-20 , onChange gets triggered sending me the date as 13th March 2020. I have some validations on the onChange function but How do I validate a wrong input by user if the user starts typing 13-MAR-2017, he will end up saving 13-MAR-20.

**Comment by YarnChen** [comment]
HI ,I think your DateFormats is wrong ,since you send your dataFormats as DD-MMM-YY,the year with 2 digit ,which results in 13-MAR-20, you only need to change it as DD-MMM-YYYY ,it will accept 4 digit~
