### ISSUE TITLE
Datepicker should offset for bottom of component

### ISSUE THREAD

**Issue by al3x-huang** [Hacker0x01/react-datepicker#778]
### Issue
If a margin (specifically margin-bottom) is put on the input for Datepicker, the calendar renders below the margin. 

<img width="255" alt="screen shot 2017-03-18 at 8 17 44 pm" src="https://cloud.githubusercontent.com/assets/20210402/24071941/695070b4-0c18-11e7-9f6f-b80468261e64.png">

### Expected behavior 
Datepicker should ignore margin-bottom or at least provide a means to ignore it. This margin should be offset whenever the position is calculated for the calendar.

**Comment by aij** [comment]
Have you tried adding the margin to the `div.react-datepicker__input-container` instead of the input itself? I think that does what you want.
