### ISSUE TITLE
DatePicker won't close for Inline portal version

### ISSUE THREAD

**Issue by ibekavac** [Hacker0x01/react-datepicker#785]
Not sure if this is a bug or a feature, but date-picker for Inline portal version can not be closed without selecting the date. I assume its bug cause in other examples it can be closed outside calendar.

### Issue:
- You can not click outside of calendar or leave selected (today) to close it. One must click any date but today to close it.

- To reproduce it go to examples page and scroll to [Inline portal version](https://hacker0x01.github.io/react-datepicker/) and try to close date-picker by clicking on today or by clicking outside of calendar.

**Comment by alex-shamshurin** [comment]
I made a PR https://github.com/Hacker0x01/react-datepicker/pull/784 with onSelect callback for this purpose.

**Comment by ibekavac** [comment]
@alex-shamshurin Ok, that's cool. Let me know when it gets merged!

Any update on clicking outside of calendar? Is that a bug?

**Comment by alex-shamshurin** [comment]
When you click outside the event `handleCalendarClickOutside` is fired (I checked that) and open state sets to false : `this.setOpen(false)` but it does no close... Hmm.

**Comment by alex-shamshurin** [comment]
Oh, I know why, because it inlined and cannot be closed, probably

**Comment by alex-shamshurin** [comment]
This is a PR https://github.com/Hacker0x01/react-datepicker/pull/788 with 'onClickOutside' callback. You can use it to rerender outer component, like `this.setState({showDatePicker: false})`. I hope it will be merged into next release.

**Comment by martijnrusschen** [comment]
PR has been merged and released. Closing this out.

**Comment by ibekavac** [comment]
@martijnrusschen thank you!
