### ISSUE TITLE
Broken Demo for "Multiple months with year dropdown"

### ISSUE THREAD

**Issue by lintiwen** [Hacker0x01/react-datepicker#790]
I'm using Chrome 56.0.2924.87 (64-bit), and this doesn't look right:
<img width="887" alt="demo" src="https://cloud.githubusercontent.com/assets/3269632/24309328/ad98e142-1088-11e7-9a20-a390ecdf04ab.png">

Notice that there's misalignment, is this intended?

**Comment by atarazavi** [comment]
I have same problem! It has the problem in the official document too!
