### ISSUE TITLE
onClickOutside

### ISSUE THREAD

**Issue by vmikOtr** [Hacker0x01/react-datepicker#792]
Im trying to use datepicker with button , and Im experiencing two problems 
- Im not able to select the same date( with input it ok it just closes the calendar)
- I click outside calendar it doesnt close, I tried to implement onClickOutside but this function is not called,
could you please help?
My code :
`	<div>
		<button
			onClick={this.toggleCalendar}>
			{this.state.departureDate.format("DD-MM-YYYY")}
		</button>
	{
		this.state.isOpen && (
		<DatePicker
			selected={this.state.departureDate}
			onChange={this.handleDepartureDateChangeBtn} //only when value has changed
         		onSelect={this.handleDepartureDateChangeBtn} //when day is clicked
			onClickOutside={this.handleDepartureDateChangeBtn}
			minDate={moment()}
			monthsShown={2}
	        	dateFormat="DD-MM-YYYY"
		       inline />
		)
		}		</div>`

**Comment by pravinborade** [comment]
use onBlur={(event)=>{}}

**Comment by pravinborade** [comment]
use onBlur={()=>{this.handleDepartureDateChangeBtn}} instead of  onClickOutside{this.handleDepartureDateChangeBtn}

**Comment by purohitMinesh** [comment]
I'm using reactJs and managing like this 

```
shouldCloseOnSelect={false}
onBlur={() => setopenCalendar(false)}
```
