### ISSUE TITLE
t.isSame is not a function

### ISSUE THREAD

**Issue by tamitutor** [Hacker0x01/react-datepicker#795]
I'm trying to use react-datepicker with react@15.4.2.  When clicking on a day in the calendar, react-datepicker is croaking with what you see in the following screen shot...

<img width="817" alt="screen shot 2017-03-28 at 7 54 01 pm" src="https://cloud.githubusercontent.com/assets/54854/24436454/6b471eba-13f0-11e7-9164-9b3f943cbe6b.png">

Any ideas?

**Comment by tamitutor** [comment]
Ahhh, I think I may have found a clue: https://github.com/Hacker0x01/react-datepicker/issues/167

The "selected" property must be a Moment.js object--not a regular Javascript date object...

I fixed this myself by setting my "selected" property to a moment() object.

**Comment by tamitutor** [comment]
+1 for docs reflecting the need to use a moment() object for the "selected" property.

**Comment by AwyerSoft** [comment]
@tamitutor your solution made my day 
tnx alot
