### ISSUE TITLE
Rendering incorrectly using the datepicker in React 15.4.2

### ISSUE THREAD

**Issue by stephanieatrtr** [Hacker0x01/react-datepicker#797]
For some reason the calendar isn't rendering correctly and the only recent change we have made is upgrade to react 
```
<DatePicker
                  label="Rent Begin"
                  placeholderText="Pick rent begin date"
                  minDate={moment()} // Today is minimum date
                  weekStart='0' // start on sunday
                  selected={this.state.rentBeginMoment ? moment(this.state.rentBeginMoment) : null}
                  onChange={this.handleChangeRentStartDate.bind(this)} />
```
![screen shot 2017-03-29 at 2 11 54 pm](https://cloud.githubusercontent.com/assets/25012532/24469476/9bd8b414-1489-11e7-8019-a51abe39ca6b.png)

**Comment by agrcrobles** [comment]
I am getting the same

**Comment by Yamini-Govardhani** [comment]
I guess u people are forget to import the css file

i.e.., import 'react-datepicker/dist/react-datepicker.css';

**Comment by dereksweet** [comment]
Importing the CSS file working for me. Thanks @Yamini-Govardhani

**Comment by tharakabimal** [comment]
It still didn't work for me :-(
