### ISSUE TITLE
react-datepicker prevents default form behaviour of submission on Enter

### ISSUE THREAD

**Issue by matt-easyagile** [Hacker0x01/react-datepicker#802]
When I use the react-datepicker in a form it prevents the default behaviour of submitting the form by pressing ENTER (while focused on a text field). It affects the whole form, not just text fields rendered by the react-datepicker. If I remove the react-datepicker component from my form, the normal behaviour of submitting the form on ENTER works as expected.

**Comment by cattermo** [comment]
I think this commit https://github.com/Hacker0x01/react-datepicker/commit/82a48b0bf4653da69d4297bdbe2c090ad6c6f5d4 fixes this problem. Not yet released though. When can we expect a release @philiptzou ?

**Comment by philiptzou** [comment]
I don't know... Since I am not the owner of this project:)

**Comment by martijnrusschen** [comment]
Sorry for the delay here. I’m currently on vacation but I’ll do a release
as soon as I get back home.

**Comment by reactionic127** [comment]
@martijnrusschen 
I am getting same issue. did you released the updated version

**Comment by reactionic127** [comment]
@martijnrusschen 
I fixed it by myself.
In my case, custom input of react date picture was a button.
so if date picture clicked, form is submitted
