### ISSUE TITLE
Making a responsive inline calendar

### ISSUE THREAD

**Issue by andyrichardson** [Hacker0x01/react-datepicker#806]
Thanks for the great component. 

I've been looking to make the inline calendar responsive so it will take the width of the parent container and scale vertically appropriately. Ideal for working with bootstrap columns.

Is there a reason this hasn't been done already or am I possibly approaching responsive components in the wrong way? 

The fork implementing this functionality can be found [here](https://github.com/andyrichardson/react-datepicker). I'd be happy to create a pull request if this is considered useful.

**Containing div original width**
![screenshot from 2017-04-05 19-47-55](https://cloud.githubusercontent.com/assets/10779424/24721662/e50a7fc8-1a38-11e7-90e6-c199ad20c3c9.png)

**Containing div reduced width**
![screenshot from 2017-04-05 19-48-33](https://cloud.githubusercontent.com/assets/10779424/24721674/ec717212-1a38-11e7-8ed9-b0ac3e88649f.png)

**Comment by Nishanth11** [comment]
is der an example for this responsive inline datepicker ?

**Comment by jees47** [comment]
any updates on this
