### ISSUE TITLE
Can someone explain to me what the filterDate prop needs to filter the weekends?

### ISSUE THREAD

**Issue by RyanBreece** [Hacker0x01/react-datepicker#807]
I have looked at the example in the docs. It shows filterDate={this.isWeekday}.
What is this.isWeekday ?
What am i putting in this variable?

Or would someone show me an example of using the filterDate prop?

This is my first time using this datepicker. Any help is much appreciated.

**Comment by aij** [comment]
It's a function that takes a moment object and returns whether or not it is a weekday.

You can see it in the example code at https://github.com/Hacker0x01/react-datepicker/blob/efa7edc043f04db8ed0a29365e0300c797be06e9/docs-site/src/examples/filter_dates.jsx#L19

I suppose it would be good if that were included in the example code on the page as well.

**Comment by RyanBreece** [comment]
Thank you. This is exactly what I need.
