### ISSUE TITLE
Deprecation warning with React 15.5

### ISSUE THREAD

**Issue by obartra** [Hacker0x01/react-datepicker#813]
React is showing the following deprecation warning when using the latest published version of react-datepicker (0.44.0):

>  DateInput: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

There's information about the deprecations [here](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

**Comment by rafeememon** [comment]
cc @Pomax re: https://github.com/Pomax/react-onclickoutside/commit/5b023e90b09ea148285296c31041e35d7aa5b8dd

**Comment by obartra** [comment]
Hey there @rafeememon happy to contribute, what should be the approach here, do you want to use `create-react-class`, ES6 classes or something else?

If using ES6 classes, I see you have stage-0 plugins added on babelrc, have you considered using [transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/)? It could make migration a bit simpler/cleaner

**Comment by martijnrusschen** [comment]
@obartra ES6 classes seem to be the new standard. Welcoming help to get the codebase migrated!

**Comment by liady** [comment]
@rafeememon any news on this PR?

**Comment by ltfschoen** [comment]
Yes, I simply had to change this:
```
import React from 'react';

const Hello = React.createClass({
    render() {
        return <h1>Hello, world</h1>;
    }
});

export default Hello;
```

to either:
```
import React from 'react';

export default class Hello extends React.Component{
    render() {
        return <h1>Hello, world</h1>;
    }
}
```

or:
```
import React from 'react';

const Hello = () => {
    return <h1>Hello, world</h1>;
};

export default Hello;
```
