### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by wzup** [Hacker0x01/react-datepicker#814]
Calendar doesn't appear on click. Styles are not applied. No errors throw though

![search form - google chrome 2017-04-11 00 27 48](https://cloud.githubusercontent.com/assets/3880497/24871907/e2ec46c2-1e4d-11e7-8c5e-ef8e363b9a9c.png)

```
const DatePicker = require('react-datepicker');
const moment = require('moment');
require('react-datepicker/dist/react-datepicker.css');


class DP extends React.Component {
    render() {

        return (
            <div className={this.props.className}>
                <DatePicker
                    selected={this.state.startDate}
                    onChange={this.handleChange}
                    selectsStart
                    startDate={this.state.startDate}
                    endDate={this.state.endDate}
                />

            </div>
        );
    }

    handleChange (date) {
        this.setState({
            startDate: date,
        });
    }

    constructor(props) {
        super(props);
        this.state = {
            startDate: moment(),
            endDate: moment()
        };
    }
```

**Comment by SimonaJ** [comment]
I have the same problem.
Although I see datepicker rendered in html but its' transform properties are calculated all wrong so datepicker is outside of the page. 
Maybe something's wrong with tether.js?

**Comment by alex-shamshurin** [comment]
Styles works)) And I'm not sure about it
 ` this.state = {
            startDate: moment(),
            endDate: moment()
        };`

**Comment by martijnrusschen** [comment]
Closing due inactivity.
