### ISSUE TITLE
Twitter Bootstrap 3 makes size small

### ISSUE THREAD

**Issue by olefrank** [Hacker0x01/react-datepicker#826]
When using this with BS3 the month popup size is computed smaller than when not. 

<img width="152" alt="skaermbillede 2017-04-17 kl 11 58 34" src="https://cloud.githubusercontent.com/assets/3809708/25085977/4030cf62-2365-11e7-90df-058e25d9b26f.png">

**Comment by janka** [comment]
That is because rem units are used, so the date picker is sized relative to the root font size. Deafult for browsers are typically 16px, bootstrap uses 10px. So adding this

`html {font-size: 16px;}`

fixes it. May fuck up other things on your site though...

**Comment by janka** [comment]
See also #624

**Comment by olefrank** [comment]
Thanks, it worked! I looked everywhere for the place in the code where the size is computed. But I didn't find it yet. Where is it?

**Comment by janka** [comment]
It is not computed, just set with rem units in the style sheet. Not ideal, as pr discussion in #624
