### ISSUE TITLE
DateField crash on IE10

### ISSUE THREAD

**Issue by pek7** [Hacker0x01/react-datepicker#829]
Having this datefield on IE10
              <DateField
                dateFormat="DD.MM.YYYY"
              />

.. when clicking the input area nothing is shown. Console shows error: 
'Unable to get property 'props' on undefined or null reference'

from bundle.js

```
	var DateField = function (_Component) {
            // ...
	    key: 'onCalendarIconMouseDown',
	    value: function onCalendarIconMouseDown(event) {
	      if (this.props.disabled) {  // failure here
	        return;
	      }
	      event.preventDefault();
```

package.json:

`    "react-date-picker": "^5.3.28",`

**Comment by martijnrusschen** [comment]
That's a different datepicker. You can install this datepicker here: https://www.npmjs.com/package/react-datepicker.

**Comment by pek7** [comment]
Oops, that's a blunder. Seems react-datepicker is good to go with IE10, good work!
