### ISSUE TITLE
In the demo, calendar goes beyond the screen

### ISSUE THREAD

**Issue by binarykitchen** [Hacker0x01/react-datepicker#83]
It overlaps the upper and left window borders ...

**Comment by martijnrusschen** [comment]
Is this still an issue? If so, can you post a screenshot?

**Comment by binarykitchen** [comment]
i cannot remember nor reproduce. because your comment comes in five months late after reported.

**Comment by martijnrusschen** [comment]
Sorry, my bad. We're working on improved examples, those improvements will avoid issues like these.

**Comment by martijnrusschen** [comment]
A new demo has been deployed: https://hacker0x01.github.io/react-datepicker
