### ISSUE TITLE
Date picker does not reopen after closing on Safari iOS

### ISSUE THREAD

**Issue by skywickenden** [Hacker0x01/react-datepicker#830]
If the date picker is opened and a date selected, then the picker closes. However if the date field is clicked on again it does not reopen.

It happens because the text input does not loose focus when the picker closes (even if readOnly is set)

Tested on an iPad and iPhone using Safari

Tested on the demo page.

Probably related to https://github.com/Hacker0x01/react-datepicker/issues/597

**Comment by dan-diaz** [comment]
Just ran into this today. Are there any work-arounds?

**Comment by dan-diaz** [comment]
@skywickenden 

This seems to have fixed the issue:
```
class CustomInput extends Component {
  handleTouchStart = () => {
    this.props.onClick();
  }

  render() {
    return (<input onTouchStart={this.handleTouchStart} />);
  }
}
```

iOS will prevent additional click events to an input that is already in focus.
But it does accept touch events.

**Comment by martijnrusschen** [comment]
Nice, is this something that could be implemented in the component itself?
