### ISSUE TITLE
It is not possible to close `inline withPortal` picker without changing date

### ISSUE THREAD

**Issue by martinek** [Hacker0x01/react-datepicker#834]
I have case similar to the case 'Inline portal version' from samples. I use button to show modal picker.

    <DatePicker
        selected={this.state.date}
        onChange={this.handleDateChange}
        withPortal
        inline
    />

When picker is shown, there is no way to close picker without selecting different date. I'm not sure why, because the case with only `withPortal` (ie. without `inline`) works as expected (you can click background to close the modal). This can also be seen in demo `Portal version`.

**Comment by leopoldw** [comment]
Strictly speaking, I don't think this is a bug; it's up to the dev to handle opening and closing the inline window. However, there's no easy way I can see to bind the dev's `close` function to a background click. Passing a function which is run when the user clicks this background, something like `inline={ close }` or `inlineClose={ close }`, would help.

**Comment by alex-shamshurin** [comment]
You can use `onSelect` callback, it's already impemented and merged by PR https://github.com/Hacker0x01/react-datepicker/pull/788

**Comment by martinek** [comment]
`onSelect` partially solves my problem by enabling clicking on the already picked date. It does not however solve problem with not being able to click on backdrop to close.

**Comment by alex-shamshurin** [comment]
That's why there is another callbac - `onClickOutside` to solve your problem.

**Comment by martinek** [comment]
That solves my problem, thanks.
