### ISSUE TITLE
Components "displayName" are gone.

### ISSUE THREAD

**Issue by toomuchdesign** [Hacker0x01/react-datepicker#836]
Since [v0.46.0](https://github.com/Hacker0x01/react-datepicker/tree/v0.46.0) has switched to `React.component`, `react-datepicker`'s components don't declare their `displayName` property any more.

I'm opening this issue since I can't find any reference about this in the Changelog (might it be considered a breaking change?).

If a design decision, please feel free to close the issue right away.

Else, there are at least a couple of options:
- Restore `displayName` as static properties
- Try to add `displayName` props at JSX compile time (maybe [this babel plugin](https://www.npmjs.com/package/babel-plugin-add-react-displayname) might work)

I'm available to PR a fix, but I'd like to know which options do you prefer as mantainers of this repo.

Thank you for the great work here, Cheers!

**Comment by martijnrusschen** [comment]
This is definitely not by design. I think we missed this one during the refactor, and I'm supportive to get it back in. My guess is that adding it back as a static property would be fine?

**Comment by toomuchdesign** [comment]
Yep, I think so! Static props is the way I personally declare `displayName` on `React.component` instances.
