### ISSUE TITLE
Enable adding classes to days with callback

### ISSUE THREAD

**Issue by martinek** [Hacker0x01/react-datepicker#841]
This feature allows highlighting of any dates without the need of knowing upfront which days will be rendered by calendar. It also allows adding more, completely custom classes.

Callback function is passed the `date` being rendered and can return any value that can be processed by `classnames` module. That include `undefined` if no additional class should be inserted.

I have submitted PR #835 with this feature.

**Comment by utsavdevsharma** [comment]
This is exactly what we need in advanced usage. I would like to request, it would be really helpful if we can merge #835 soon.

**Comment by martijnrusschen** [comment]
Should be possible now.
