### ISSUE TITLE
Filter dates

### ISSUE THREAD

**Issue by vmiimu** [Hacker0x01/react-datepicker#842]
Following example code for [Filter dates](https://hacker0x01.github.io/react-datepicker/#example-12) to only display weekdays produces different results than example page.
```
<DatePicker
  selected={ this.state.startDate }
  onChange={ this.handleChange }
  filterDate={this.isWeekday}
  placeholderText="Select a weekday"
/>
```
Desired behavior:
![screenshot3](https://cloud.githubusercontent.com/assets/1923495/25426627/9eb79122-2a24-11e7-8ceb-0d3f6e8cd029.png)

Current behavior:
![screenshot2](https://cloud.githubusercontent.com/assets/1923495/25426646/ade50ed6-2a24-11e7-8a25-74c4c9506bc5.png)

**Comment by mgrdevport** [comment]
@vmiimu Did you provide the isWeekday function in your component?
```js
isWeekday = (date) => {
    const day = date.day()
    return day !== 0 && day !== 6
  }
```

**Comment by martijnrusschen** [comment]
Closing due inactivity.

**Comment by jamparke** [comment]
It would be great if these were in the docs. It just asks for a function without any info on the function.

**Comment by rafeememon** [comment]
@jamparke, contributions to improve the docs are welcome

**Comment by jamieallen59** [comment]
If others end up here, this is now:
```javascript
const isWeekday = (date) => {
    const day = date.getDay()
    return day !== 0 && day !== 6
}

**Comment by AcidRaZor** [comment]
> @vmiimu Did you provide the isWeekday function in your component?
> 
> ```js
> isWeekday = (date) => {
>     const day = date.day()
>     return day !== 0 && day !== 6
>   }
> ```

Documentation seems very weak with this library compared to other popular packages....

**Comment by yong-zong-dev** [comment]
> @vmiimu Did you provide the isWeekday function in your component?
> 
> ```js
> isWeekday = (date) => {
>     const day = date.day()
>     return day !== 0 && day !== 6
>   }
> ```

Hi Mgrdevport
date.day() is working in your side?

**Comment by kevbarns** [comment]
Hello 

the following implementation is working : 

```
isWeekday = date =>{
const day = getDay(date)
return day !== 0 && day !== 6
}
```

> > @vmiimu Did you provide the isWeekday function in your component?
> > ```js
> > isWeekday = (date) => {
> >     const day = date.day()
> >     return day !== 0 && day !== 6
> >   }
> > ```
> 
> Hi Mgrdevport
> date.day() is working in your side?

try this 

`
isWeekday = date =>{
const day = getDay(date)
return day !== 0 && day !== 6
}
`
