### ISSUE TITLE
onChange event is not firing for a specific case

### ISSUE THREAD

**Issue by sweetLew2** [Hacker0x01/react-datepicker#847]
The datepicker interface will override a date that was typed in, if it is invalid, without triggering the "onChange" event.. 

I'm not sure how to implement date validation if I can't always check what is being displayed to the user..

Imagine the picker with a pre-selected (valid) date.  If you click into the text box (which opens the datepicker interface), type "asdf" on the end of the date, and then hit enter you will see that the the onChange event did not fire - but the input has actuallly changed..

I think there should be either a "onKeyDown" event or "onEnter" event or maybe the datepicker interface should trigger onChange in this case.. I'm pretty sure validation should be handled by whoever is implementing it..  and I really want to use this tool.. everything else seems fantastic.

**Comment by aij** [comment]
Have you tried upgrading to 0.46.0? Pretty sure this is fixed.

`onChange` still won't fire, because existing code expects a valid moment object, but you can use `onChangeRaw` and `onBlur`.

**Comment by sweetLew2** [comment]
Hey, thanks for the fast response - I am on that version actually.  Also, the onChangeRaw isn't fired when the user hits enter.

I think the main issue is that the datepicker overrides the input (which seems reasonable) but it does so without triggering any events... so I can't revalidate the new date.

**Comment by mrchief** [comment]
`onChangeRaw` doesn't fire even in v1.1.0.

**Comment by adrianblynch** [comment]
As @mrchief says, `onChangeRaw` doesn't fire for me and I'm using v2.3.0.

```
<DatePicker
  selected={new Date()}
  onChange={(date) => { console.log("date:", date) }}
  onChangeRaw={(e) => { console.log("e:", e) }}
/>
```

The above results in the date being logged to the console. I'm about to dig a little deeper.
