### ISSUE TITLE
Date Picker jumps around when clicking on month title box/changing months

### ISSUE THREAD

**Issue by bethcodes** [Hacker0x01/react-datepicker#850]
When it's on July, you can see it sort of walk up the page with each click.

![out](https://cloud.githubusercontent.com/assets/4296381/25726584/ba2bf2c0-30d9-11e7-8ede-73ab20e16e8f.gif)

**Comment by rafeememon** [comment]
Probably the same issue as https://github.com/Hacker0x01/react-datepicker/issues/361
