### ISSUE TITLE
There are few semantics issues

### ISSUE THREAD

**Issue by unlabeled** [Hacker0x01/react-datepicker#852]
react-datepicker__month-container class should be either react-datepicker__content or react-datepicker__container
react-datepicker__current-month class  should be react-datepicker__header-text

**Comment by rafeememon** [comment]
Agreed that the class names are less than ideal, but unfortunately fixing them would be a breaking change, which I'm extremely hesitant about.

**Comment by unlabeled** [comment]
Will close this issue. But I hope in major release you'll try to solve it.
