### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by tomitrescak** [Hacker0x01/react-datepicker#861]
Hi, there is a deprecation warning due to use of creacteclass in react 15.5

**Comment by ZachGawlik** [comment]
I just ran into those warnings myself, but it turns out the fix is already in [v0.46.0](https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.46.0)! Upgrade your version of react-datepicker to stop seeing the warnings.
