### ISSUE TITLE
Time change is not registered

### ISSUE THREAD

**Issue by PovilasID** [Hacker0x01/react-datepicker#870]
Instead of time set in the field I get current time

```
  handleDateTimeChange(date) {
    this.setState({
      startDate: date
    });
  }
```
The state receives the date correctly but time if in a form I change the time to 5 pm it still returns 6 if it's now 6. Here is component
```
          <DatePicker
              dateFormat="YYYY-MM-DD HH:mm"
              selected={this.state.startDate}
              todayButton="Today"
              onChange={this.handleDateTimeChange}
          />
```

**Comment by VrajSolanki** [comment]
is there any support to change the date as well as time from the date picker itself??

**Comment by alex-shamshurin** [comment]
`this.state.startDate` is a `moment` object. You can always rewrite it in `onChange` or you can use `onSelect` callback if you need to catch each `select`. DatePicker is not TimePicker, it just cares about dates, but you can track current time in `onSelect` callback.

**Comment by martijnrusschen** [comment]
Closing due inactivity.
