### ISSUE TITLE
DatePicker does not display internationalized dates. 

### ISSUE THREAD

**Issue by karthiklsarma** [Hacker0x01/react-datepicker#871]
I am getting an internationalized date using this code:
myDate = moment(str).locale(localeString).format(ISO_FORMAT);
I get myDate value as ༢༠༡༧-༠༥-༡༡

I am passing this date to the react-datepicker shown as below:
        <DatePicker
          className={className}
          dateFormat={this.props.format}
          locale={localeString}
          placeholderText={this.props.format}
          selected={moment(myDate) && moment(myDate).isValid() ? momentValue : null}
          />
The above code gives me an error because moment(myDate) is NaN and does not display anything.
I get this warning in my console:

moment.js:291 Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

**Comment by rafeememon** [comment]
Try passing the moment object itself (not the formatted string) into the datepicker, and you'll probably also need to set the `locale` prop to `localeString`

**Comment by karthiklsarma** [comment]
Thank you. It helped. Closing the issue.
