### ISSUE TITLE
Adjust datepicker size?

### ISSUE THREAD

**Issue by naheller** [Hacker0x01/react-datepicker#872]
Apologies -- I don't know where else to ask this, but how does one adjust the overall size of the datepicker pop-over window? Is there a general width and height value (CSS, props, etc)?

Thanks

**Comment by oldo** [comment]
@naheller see https://github.com/Hacker0x01/react-datepicker/issues/624#issuecomment-261696513

**Comment by naheller** [comment]
Thank you!
