### ISSUE TITLE
unable to get property 'stetPosition' of undefined null reference

### ISSUE THREAD

**Issue by benjh729** [Hacker0x01/react-datepicker#873]
<script type="text/javascript"
  src="http://maps.googleapis.com/maps/api/js?v=3.18&sensor=false">
</script> 

<script type="text/javascript">
    var map;
	var path;
	var vehicle;
	var showVehicle = 1;
	var waypoints = [];

    google.maps.event.addDomListener(window, 'load', initialize);
	function initialize() {
		busy();
        var latlng = new google.maps.LatLng(40.0, 12.0);
        var myOptions = {
            zoom: 2,
            center: latlng,
            disableDefaultUI: false,
            mapTypeId: google.maps.MapTypeId.HYBRID
        };
        map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
		
		 var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 2,
    center: myLatlng
  });

  var marker = new google.maps.Marker({
    position: myLatlng,
    map: map,
    title: 'Click to zoom'
  });
path.setMap(map);
		
		vehicle = new google.maps.Marker({ 
			map: map, 
			draggable: true,
			animation: google.maps.Animation.DROP, 
			position: latlng,
			visible: false			
		});
  map.addListener('center_changed', function() {
    // 3 seconds after the center of the map has changed, pan back to the
    // marker.
    window.setTimeout(function() {
      map.panTo(marker.getPosition());
    }, 3000);
  });

		path.setMap(map);
		
		vehicle = new google.maps.Marker({ 
			map: map, 
			draggable: true,
			animation: google.maps.Animation.DROP, 
			position: latlng,
			visible: false			
		});
 
        google.maps.event.addListener(map, 'click', function (event) {
            setWaypoint(event.latLng);
        });

**Comment by benjh729** [comment]
can get map and move but can't set position from gps

**Comment by rafeememon** [comment]
Wrong project?
