### ISSUE TITLE
Merging PR

### ISSUE THREAD

**Issue by alex-shamshurin** [Hacker0x01/react-datepicker#874]
Hi guys, I wonder when you will merge pull requests? I do not see any feedbacks for my PR https://github.com/Hacker0x01/react-datepicker/pull/860 and https://github.com/Hacker0x01/react-datepicker/pull/859. Other PRs also need to be merged as well.

**Comment by alex-shamshurin** [comment]
Up! Please merge https://github.com/Hacker0x01/react-datepicker/pull/860

**Comment by martijnrusschen** [comment]
Merged.

**Comment by alex-shamshurin** [comment]
Thanks

**Comment by aij** [comment]
@martijnrusschen As long as we're already making API breaking changes, would it make sense to get #740 merged too?
