### ISSUE TITLE
position popup to sides of input element, not .react-datepicker__input-container

### ISSUE THREAD

**Issue by jedwards1211** [Hacker0x01/react-datepicker#875]
When I put a `DatePicker` inside of a Bootstrap `.input-group` (inside `.row > .form-group`) at least, the height of the `.react-datepicker__input-container` becomes 0 because the `.input-group` gets `display: table`.  Because the height is 0, the popup displays in the wrong position:

![image](https://user-images.githubusercontent.com/1448194/26901261-c3ee7860-4b9a-11e7-802f-e4b9c37b5dbd.png)

Even if I add `overflow: hidden` to the `.react-datepicker__input-container` to establish a new block formatting context, its height ends up including the `margin-bottom` of the `<input>` element and the popup position is still wrong:

![image](https://user-images.githubusercontent.com/1448194/26901285-dc14de70-4b9a-11e7-9bc6-a5b5ed2a22da.png)

But obviously the bottom of the `<input>` element is in correct position, so if you position the popup to the sides of the `<input>` element instead of the `.react-datepicker__input-container`, no one will have this problem.

**Comment by kunal886496** [comment]
can someone solve this?
