### ISSUE TITLE
Previous Month on Date Select

### ISSUE THREAD

**Issue by zsteiner** [Hacker0x01/react-datepicker#877]
On inline calendar, if I follow the following steps: 
1. Advance to the next month (July) and select a date (Jul 15)
2. Advance to next month (August) and select a new date (Aug 15)

I expect to have Aug 15 highlighted, but the calendar navigates to the previous month (July). Aug 15 is selected in data and is highlight if I navigate back to August. The datepicker erroneously navigates to the previous month. Appears to be a propagation or click handling issue, but I haven't narrowed down where it is happening.

**Comment by enectronic** [comment]
+1 I'm also having this problem.

**Comment by tylerreinhart** [comment]
+1

**Comment by martijnrusschen** [comment]
Should be fixed now.
