### ISSUE TITLE
Adjust margin, padding, size of modal

### ISSUE THREAD

**Issue by naheller** [Hacker0x01/react-datepicker#878]
![screen shot 2017-06-08 at 11 32 21 am](https://user-images.githubusercontent.com/18204925/26945198-daa62d46-4c3f-11e7-8d38-472bdd8ebc82.png)

How do I shrink the padding around this modal to get rid of the empty white space around the edges? Thank you

**Comment by ghfkui** [comment]
The same question

**Comment by PaulRBerg** [comment]
I couldn't find anything in the official documentation, so I ended up looking up the class names and overriding them in my CSS.

Example for how to override the time container:

```
.react-datepicker__time-container {
    width: auto;
    padding-bottom: 12px;
  }
```

Other elements have intuitive class names such as `.react-datepicker__day`, `.react-datepicker__time-box` etc.
