### ISSUE TITLE
Datepicker style not working, any dependencies I need?

### ISSUE THREAD

**Issue by johhansantana** [Hacker0x01/react-datepicker#879]
When I click it does this instead:
<img width="191" alt="screen shot 2017-06-09 at 11 10 50 am" src="https://user-images.githubusercontent.com/9933887/26981839-58f0a6ee-4d04-11e7-80c0-9bb5bd796453.png">

is there a way to add the css manually?

when I check the dev tools there is no css being load up
<img width="1280" alt="screen shot 2017-06-09 at 3 43 55 pm" src="https://user-images.githubusercontent.com/9933887/26991965-8226653c-4d2a-11e7-9d9b-a3506778d5f6.png">

**Comment by johhansantana** [comment]
well I was having trouble importing `react-datepicker/dist/react-datepicker.css'` I'm not a webpack savvy so I just added it as a static file and now it works.

**Comment by sislam6** [comment]
Just use a tilde in front of the the path. Just like you import bootstrap from the node dependencies.  
Add this in your scss file import "~react-datepicker/dist/react-datepicker.css". This should work.

**Comment by AKArunkumar** [comment]
@johhansantana if you solved this issue please let me know how,
I tried, importing using **require, importing using ~, made css file in same directory** tried to import but nothing worked for me.

**Comment by AliAlperSakar** [comment]
You should import css of react-datepicker=> ~~import "react-datepicker/dist/react-datepicker.css"~~ in index.js/index.ts file which includes getElementById('root').

**Comment by DomantasP** [comment]
Adding 'import 'react-datepicker/dist/react-datepicker-cssmodules.min.css' to my index.jsx solved the problem for me.

**Comment by Boucherie** [comment]
We tried adding both

 import "react-datepicker/dist/react-datepicker.css" 
import  'react-datepicker/dist/react-datepicker-cssmodules.min.css'

and neither threw an error, but no styles. changing the file to something like

 'react-datepicker/dist/react-datepicker-cssmodules.min.css1' throws an error, so they are being found and imported, but the chrome inspetor shows no styles :(

**Comment by Nadya1993** [comment]
> We tried adding both
> 
> import "react-datepicker/dist/react-datepicker.css"
> import 'react-datepicker/dist/react-datepicker-cssmodules.min.css'
> 
> and neither threw an error, but no styles. changing the file to something like
> 
> 'react-datepicker/dist/react-datepicker-cssmodules.min.css1' throws an error, so they are being found and imported, but the chrome inspetor shows no styles :(

@Boucherie  you can just import css from cdnjs: @import url('https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/2.8.0/react-datepicker.min.css'); 

It was the only way that worked for me

**Comment by larsblumberg** [comment]
Also for me, non of the mentioned imports do apply any styling. What's the issue?

**Comment by VinixGonzalez** [comment]
try to import the css inside index.js
`import "react-datepicker/dist/react-datepicker.css";`
this worked for me !

**Comment by SidOfc** [comment]
Before anything else, thank you for providing this component 💟 

I think quite some folks end up here after checking this page: https://reactdatepicker.com/ which actually lacks a critical `import` line for the stylesheet. This `import` is included in the GH README.md, however:

![image](https://user-images.githubusercontent.com/3225058/66467244-6c981680-ea84-11e9-82cb-6f5d7cc1127f.png)

Perhaps it would be a good idea to update the website to include this `import` there as well?

Cheers and keep up the good work 👍

**Comment by topovik** [comment]
`import DatePicker from "react-datepicker"
require('react-datepicker/dist/react-datepicker.css')`
it should work

**Comment by SidOfc** [comment]
While it should work, that doesn't mean it is obvious that you'd do so from the actual website. It's not too bad since GH docs mention it but just adding the import line I think will prevent folks from having to search for it or figure out by themselves that it's "not on the website, but only on GH".

Also, if you can `import DatePicker`, can't you use ES6 modules to `import 'react-datepicker/dist/react-datepicker.css'` in your setup? :)

**Comment by ffpetrovic** [comment]
Yes, if you can import the component using ES6 `import` then it should work for `.css` files as well. And this section should be added to the website. Since the `npm install` part is there, the following steps necessary for the library to work/look properly should be listed as well.

**Comment by michael-harley** [comment]
> This is how the component looks to me:
> 
> <img alt="Screenshot 2019-08-16 at 15 16 23" width="166" src="https://user-images.githubusercontent.com/5980316/63170096-d1149780-c038-11e9-9258-b1afc0664dc7.png">
> 
> The mentioned imports are accepted (no compile error) but styling is not properly applied.

![image](https://user-images.githubusercontent.com/29723619/79755212-f33a8400-8342-11ea-898d-b6056c042590.png)

This is how it looked to me as well, and the styling is not properly applied.
Anyone know how to fix this styling?
I thought it should looked like this: https://reactdatepicker.com/

**Comment by clinton-slice** [comment]
Add the line below to the top of your file where you are using the DatePicker 
`import 'react-datepicker/dist/react-datepicker.css';`

**Comment by franlol** [comment]
In my case, under a nextjs project with babel7 and webpack4, the only way that I can fix the css is

`
import DatePicker from "react-datepicker"
import "react-datepicker/src/stylesheets/datepicker.scss";
`

Hope it can help someone

**Comment by Eezi** [comment]
In my case the import of the css file didn't work at all, but I fixed it by replacing line in the css file:
 ** content: "\00d7"; with this --> content: &times;**

import "react-datepicker/dist/react-datepicker.css";

**Comment by michelmany** [comment]
@franlol your solution worked for me. Thanks!

**Comment by ThusharaSampath** [comment]
> import "react-datepicker/dist/react-datepicker.css

Try this one ! works for me

**Comment by nielsuit227** [comment]
This becomes especially annoying on a dev-server. I had to copy the CSS and manually move it.

**Comment by nevingrowingstars** [comment]
> 
> 
> In my case, under a nextjs project with babel7 and webpack4, the only way that I can fix the css is
> 
> ```js
> import DatePicker from "react-datepicker"
> import "react-datepicker/src/stylesheets/datepicker.scss";
> ```
> 
> Hope it can help someone

This is the one fix which is working....

**Comment by ndnenkov** [comment]
I was having an issue with webpacker where it worked in dev, but not in other environments. I had to add
```
@import 'react-datepicker/dist/react-datepicker';
```

To `application.scss` rather the inline import.

**Comment by kbiswas100** [comment]
if nothing works then you can add this class to your css file , 
`.react-datepicker__time-list-item {
    width: 70px;
    margin-left: -40px;
    padding-left: 18px !important;
}`

**Comment by codeybench** [comment]
In addition to all the above, it is very important to write the file name extension. Import without `.css` ruins absolutely everything

**Comment by GodAlmighty990** [comment]
I had to add import 'react-datetime/css/react-datetime.css'; to my App.js.


Here is my App.js file

This could also be your index.js file


import React from 'react';
import { BrowserRouter as Router } from 'react-router-dom';
import Layout from './layouts/Layout';
import 'react-toastify/dist/ReactToastify.min.css';
import 'react-datepicker/dist/react-datepicker.css';
import 'react-image-lightbox/style.css';





const App = () => {
  
  
  
  return (
    
      <Router basename={process.env.PUBLIC_URL}>
      
        <Layout />
        
      </Router>
  
  );
};

export default App;

**Comment by pedro-pinho** [comment]
In my case it was because I had the postcss-purgecss plugin installed, and it was purging some of the css
To fix it, I had to update my postcss.config.js file to this:

`module.exports = {
  plugins: [
    'postcss-flexbugs-fixes',
    [
      'postcss-preset-env',
      {
        autoprefixer: {
          flexbox: 'no-2009',
        },
        stage: 3,
        features: {
          'custom-properties': false,
        },
      },
    ],
    [
      '@fullhuman/postcss-purgecss',
      {
        content: ['./pages/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}', './styles/*.{scss}'],
        defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
        safelist: ['html', 'body', 'react-datepicker'],
      },
    ],
  ],
}
`

**Comment by DevOzair** [comment]
I ended up copying everything in the react-datepicker.css  into my main index CSS, added it in a section below. 
Nothing above was working.

**Comment by themegabyte** [comment]
FYI for `"next": "12.3.1"`

Add your import to the `_app.js` file:

Like so: 

```js
import "../styles/globals.css";
import "react-datepicker/dist/react-datepicker.css"; # 👈

import { SWRConfig } from "swr";
import axios from "axios";
...

```

Documentation here: https://nextjs.org/docs/basic-features/built-in-css-support#import-styles-from-node_modules

**Comment by ashwindevx** [comment]
> I ended up copying everything in the react-datepicker.css into my main index CSS, and added it in a section below. Nothing above was working.
> 
> (new to all this, 3rd day at React so my solution is 100% not the best :D )

Can you share the style you copied and pasted to your index CSS file? Thanks!

**Comment by amanattryb** [comment]
I am stack with this issue as I am trying to run yarn run build

Error: 'Calendar' is not exported by node_modules/react-date-range/dist/index.js, imported by src/composite-component/date-picker/date-picker.tsx

**Comment by martijnrusschen** [comment]
@amanattryb Based on the error it seems you may be using a different component.
