### ISSUE TITLE
npm package has jsx files in src with js extension

### ISSUE THREAD

**Issue by mikha** [Hacker0x01/react-datepicker#88]
hi,

while trying to use react-datepicker:0.5.1 I'm getting following:

```
ERROR in ./~/react-datepicker/src/datepicker.js
Module parse failed: ...\node_modules\react-datepicker\src\datepicker.js Line 50: Unexpected token <
You may need an appropriate loader to handle this file type.
|     if (this.state.focus) {
|       return (
|         <Popover>
|           <Calendar
|             selected={this.props.selected}
 @ .../some_file.cjsx 13:13-40
```

this is produced by webpack. naturally my webpack config only applies jsx-loader to files with appropriate extension (*.jsx). can you please keep extension at .jsx for files in /src when you dist the npm package?

**Comment by RSO** [comment]
Hmm, I'm not quite sure what I should change here. The git repo has those files in a `.jsx` extension. Do you have any suggestions as to what I should fix?

**Comment by iam4x** [comment]
@RSO You should publish a builded file without JSX synthax in it and minified for NPM packages. This will allow webpack/browserify users work with react-datepicker.

I'll open a PR.

**Comment by jaseemabid** [comment]
The version installed with npm in unusable at the moment due to this issue

**Comment by iam4x** [comment]
@mikha @jaseemabid 

Try `npm install --save react-datepicker@iam4x/react-datepicker#fix-npm-use-webpack` and use it this way:

```
var DatePicker = require('react-datepicker);
// or ES6 style
import DatePicker from 'react-datepicker'
```

Can I have feedback? This shouldn't run server side yet, because of `Tether` dep.

**Comment by oliveiraethales** [comment]
Also having this issue, trying @iam4x solution now (:

**Comment by oliveiraethales** [comment]
Some progress :D Thanks @iam4x! But the positioning is still bad \: And there's a JS error when I click on any calendar day. Also, is it 'normal' to require the datepicker css through something like 
`require('../../../node_modules/react-datepicker/dist/react-datepicker.css')` for it to work correctly? Or I should mess with something in webpack config?

![ss](https://cloud.githubusercontent.com/assets/208830/6556579/352551c8-c64d-11e4-83a2-70caca91f22b.png)

Cheers!

**Comment by iam4x** [comment]
@oliveiraethales You should have https://github.com/webpack/style-loader with webpack to require css files, or just do it as normal in the html:

```
<link rel='stylesheets' href='dist/react-datepicker.css' />
```

**Comment by FoxxMD** [comment]
Thank you @iam4x ! Your solution worked for me.

**Comment by iam4x** [comment]
When the PR #89 is merged, everything should be fine with `$ npm install react-datepicker`

**Comment by RSO** [comment]
Could you verify if v0.6.0 fixed this issue?
