### ISSUE TITLE
scrollableYearDropdown is limit to down 2008?

### ISSUE THREAD

**Issue by critdhenz** [Hacker0x01/react-datepicker#886]
Hi, Why the year dropdown is limit to down 2008 and you still have to click arrow down to show more years? Do we have minDate and maxDate for years? Thank you

![image](https://user-images.githubusercontent.com/11516898/27070101-1259a430-504a-11e7-84d7-b884a26525ad.png)

**Comment by riccoski** [comment]
From reading it looks like it shows the previous 10 years and the next 10 years... 
yearDropdownItemNumber={1}
This will change the amount of years it-/+

**Comment by mikeyc7m** [comment]
the yearDropdownItemNumber only sets the size of the picker window, it has no effect on the number of available years to pick from.
