### ISSUE TITLE
How can I wait before I close the datepicker?

### ISSUE THREAD

**Issue by thevangelist** [Hacker0x01/react-datepicker#887]
I'd like to display a custom message inside the calendar component, "Selected date is in past", can I somehow wait for say 5 seconds before closing the calendar?

**Comment by alex-shamshurin** [comment]
What do you mean? Do you need validate input string or date which is selected? If you want to handle when calendar is open or closed you can just use `inline` property and open and close it manually via reference.

```
saveRef = c => {
  this._reactDatePicker = c
}

<ReactDatePicker
  ref={this.saveRef}
  inline={true}
  ...>
```
and use it `this._reactdatePicker.seOpen(false)` or `this._reactdatePicker.seOpen(true)`

or use `setTimeout(() => this._reactdatePicker.seOpen(false), 100)`

**Comment by martijnrusschen** [comment]
Closing due inactivity.
