### ISSUE TITLE
Resetting state on parent component doesn't reset input

### ISSUE THREAD

**Issue by dsvictorh** [Hacker0x01/react-datepicker#888]
When inputting the date from the input typing rather than choosing with the datepicker controls if I reset the state of the parent component that passes the date value onto a child component that inside has the Datepicker which is turn uses the property of the middle component to set it's own value we can see the choice on the calendar resetting, but the input stays unchanged.

If for example I have a reset button in this scenario that resets to today's date after choosing the date 05/05/2017 15:00 and resetting the calendar and the input reset back to say 06/14/2017. If however I type 05/05/2017 15:00 entirely from the input or even choose the date and type in a small change, say the time itself, at the point where I reset you see the calendar choice back at 06/14/2017....yet the input is still set to what I previously typed disregarding the current value of the calendar.

![before-reset-choice](https://user-images.githubusercontent.com/4581131/27150683-65723af4-5105-11e7-9808-a8daf4eaba06.png)
![after-reset-choice](https://user-images.githubusercontent.com/4581131/27150682-6571ce84-5105-11e7-9220-8ceb0569e89e.png)
![before-reset-typed](https://user-images.githubusercontent.com/4581131/27150681-656eea20-5105-11e7-915f-05ba2a5a86dd.png)
![after-reset-typed](https://user-images.githubusercontent.com/4581131/27150684-6573f8ee-5105-11e7-8612-69b44a68384c.png)

**Comment by aij** [comment]
If you want to reset the value of the input string as the user is typing, I think you can still do that via the `value` prop.

The problem with resetting the input every time `selected` changes, is that it's common to update `selected` from the `onChange` function, which results in issues like #560, where the input was getting reset while the user is typing. (If they happened to type an intermediate value that was parseable as a date.)

**Comment by dsvictorh** [comment]
It was definitely a bit hectic but playing with a separate inner state just to define the value of the input I can force an empty string or today's date at reset! Thanks @aij !!!

**Comment by alex-shamshurin** [comment]
I think react-datepicker should get rid of internal state. It must be maintained somewhere else.

**Comment by martijnrusschen** [comment]
Anything actionable what we can do today? Removing internal state seems more like a long term solution.

**Comment by BillOTei** [comment]
related to #1025 any news?

**Comment by BillOTei** [comment]
issue seems to come from `_this.setSelected(date,` event, true);` keepInput boolean should be `false` when called in `_this.handleChange`

**Comment by aij** [comment]
@BillOTei No, that would result in resetting the input while the user is typing.

See my comment above. If you want to control the value of the input, you can do so via the `value` prop. If you choose not to control the value of the input, then the datepicker will do it via internal state.

We don't want to reset user input when the `selected` prop changes, because that usually happens in response to `onChange()`, which gets called while the user is typing.

Perhaps we could add a `.reset()` method, so the datepicker's internal state can be cleared without needing to fully control the component.
