### ISSUE TITLE
Can't set local to "de"

### ISSUE THREAD

**Issue by andreas-koch** [Hacker0x01/react-datepicker#890]
My Code is: 
```
<DatePicker
          locale="de"
          dateFormat="LLLL"
        selected={this.state.startDate}
        onChange={this.handleChange}
      />
```
But the date string shown displays "Wednesday, June 28, 201".

Elsewhere in the code I set 
```
var deLocale = require('moment/locale/de');
moment.locale('de', deLocale);
console.log("MMMMMM",moment.locale());
console.log("MMMMMM",moment());
```
There it worked.

Thanks!

**Comment by maxm450** [comment]
Got the same problem with french translations. I added the french translations into moment, and pass the proper locale to the DatePicker and still have the month in english. But when display moment inside a console 
```
moment().locale('fr-ca')
console.log(moment().fromNow());
```
it display the proper string.

**Comment by janhoeck** [comment]
Same problem here! Please fix it

**Comment by BernardTeske** [comment]
Did anyone solve this problem by himself?

**Comment by juliocarneiro** [comment]
same problem....
