### ISSUE TITLE
Split color on date

### ISSUE THREAD

**Issue by vebjorni** [Hacker0x01/react-datepicker#891]
Hi. 

What do I need to override to set a split color on a date like in the picture below. Can someone give exact code using custom calendar class?

![screen shot 2017-06-15 at 21 26 00](https://user-images.githubusercontent.com/9068991/27198136-48012446-5211-11e7-9413-2aad319b71c7.png)

Thanks in advance!

**Comment by alex-shamshurin** [comment]
You can use different highlighted ranges. One cell can be red, another can be green. If you need combine colours inside one cell you can do it with css. So it's possible.
