### ISSUE TITLE
Input event with value and name

### ISSUE THREAD

**Issue by BenBenz** [Hacker0x01/react-datepicker#892]
In react when an input change we can get the value and the name like this:

event.target.name
event.target.value 

With react-datepicker theses values are undefined, 

this is normal or not ?

**Comment by alex-shamshurin** [comment]
What you mean? Where undefined? These values exists only in native event handlers from elements like `input`, `div` and so on.

**Comment by martijnrusschen** [comment]
Closing due inactivity.
