### ISSUE TITLE
Selected date didn't appear in input field

### ISSUE THREAD

**Issue by HadiAkmal** [Hacker0x01/react-datepicker#894]
I use custom `customInput` so i can display button next to the input field. The problem is, when I select the date, the selected date did not appear in the input field. 

Example : https://codepen.io/jochenberger/pen/ENRNZN

What did I miss?

**Comment by alex-shamshurin** [comment]
Because you need to maintain somehow input field state. It's not bound to any value.

**Comment by alex-shamshurin** [comment]
Closing this, no feedback
