### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by martijnrusschen** [Hacker0x01/react-datepicker#895]
I'd like to have some help with maintaining the repo and moving to a stable release schedule by moving to a 1.0 version. @alex-shamshurin  @aij is this something you guys would be interested in helping? I can give you write access you so both would be able to merge a PR when you think it makes sense to merge it.

**Comment by alex-shamshurin** [comment]
ok, nice ))

**Comment by aij** [comment]
@martijnrusschen Sure. It looks like we're going to be using this datepicker for the foreseeable future.

**Comment by martijnrusschen** [comment]
Thanks, added @ajj and @alex-shamshurin ad maintainers.
