### ISSUE TITLE
Blurry text at certain browser window zoom levels

### ISSUE THREAD

**Issue by tohjustin** [Hacker0x01/react-datepicker#899]
## Description
The `Tether` module (used by the datepicker to position its popup calendar) uses CSS transforms to trigger GPU optimizations. Using these CSS transforms would result in blurry texts in certain zoom levels. (See **Optimization section** @ http://tether.io)

Here's a pair of screenshots showing the difference (viewing https://hacker0x01.github.io/react-datepicker/ on [13" MBP, macOS Sierra - Chrome version 58 **(Window @ 67% Zoom Level)**]:

<img width="1073" alt="macos - chrome version 58 0 3029 110 64-bit" src="https://user-images.githubusercontent.com/8844886/27368387-0f79168e-5607-11e7-8f18-ac3496c0486f.png">

## Proposed Solution
Thankfully, the guys at Hubspot implemented a prop for us to disable this. 

```
<TetherComponent
  classPrefix={'react-datepicker__tether'}
  attachment={this.props.popoverAttachment}
  targetAttachment={this.props.popoverTargetAttachment}
  targetOffset={this.props.popoverTargetOffset}
  renderElementTo={this.props.renderCalendarTo}
  constraints={this.props.tetherConstraints}

  // *** exposing Tether's `optimizations` prop to the datepicker ***
  optimizations={this.props.tetherOptimizations}
>
  ...
</TetherComponent>
```

**Disabling GPU optimization:**
```
<DatePicker
  selected={this.state.startDate}
  onChange={this.handleChange}
  tetherOptimizations={{ gpu: false }}/>
```

I've made a fix on my end, would love to create a pull request for it! Really liked this library, would be great to get this patched on NPM asap so that we can use it for production =)

**Comment by alex-shamshurin** [comment]
So is this a problem? may be a bit blurry is better than lack of GPU optimizations? With this optimization tethered component won't be repainted on scrolling.

**Comment by tohjustin** [comment]
Hmm true, this might not be a huge problem for everyone. =S

By exposing more props for the user to control, we can allow them to fine tune the component to their specific use case (might be the reason by this optimization can be disabled in the first place)

**Comment by grkacy** [comment]
This blur is annoying and is becoming a stopper for using this component in our system. +1

**Comment by rafeememon** [comment]
I'm very uneasy about adding a prop that is directly tied to the internal implementation of the component -- aside from increasing the API footprint, it hinders our ability to change the internals in the future.  Relatedly, tether's project status is [up in the air](https://github.com/HubSpot/tether#rotating_light-project-status-rotating_light), and they are encouraging people to use [popper.js](https://popper.js.org/) instead, which may be worth exploring.

**Comment by tohjustin** [comment]
@rafeememon I do understand your concerns, isn't `tetherConstraints` something similar that's already implemented?

**Comment by rafeememon** [comment]
@tohjustin, yep it is =)  But I don't think that's a reason to make the hole any deeper.

**Comment by tohjustin** [comment]
@rafeememon @alex-shamshurin I guess this fix isn't going through? =S

On a side note, any plans to migrate over [popper.js](https://popper.js.org/)? I can start working on it this weekend =)

**Comment by martijnrusschen** [comment]
If popper is proposed by tether itself, I'd be supportive in moving to
that.

**Comment by tohjustin** [comment]
@martijnrusschen Is this a green light for me to start working on it? =0

**Comment by martijnrusschen** [comment]
Yeah would love to see a PR 👍

**Comment by tohjustin** [comment]
Okay, will create an issue & start working on it this weekend =)

**Comment by rafeememon** [comment]
@tohjustin, I think it's worth keeping this open to track the blurriness issue; the switch may or may not solve it

**Comment by tohjustin** [comment]
@rafeememon  Thanks for the heads up! =)

I'm aware that this might not fix the issue but will still be glad to help out you guys to migrate over to [Popper.js](https://popper.js.org/)

**Comment by FezVrasta** [comment]
Popper.js roundes the offset values to avoid half pixels and prevent text blurring

**Comment by martijnrusschen** [comment]
I released the new popper implementation, this should be resolved. Let me know if this still happens.

**Comment by tohjustin** [comment]
@martijnrusschen Thanks for the heads up 👍 will let you know if the blurry text is still there!
