### ISSUE TITLE
Quickly navigate years

### ISSUE THREAD

**Issue by mschipperheyn** [Hacker0x01/react-datepicker#90]
It should be possible to click the year and quickly navigate to a different year.

**Comment by RSO** [comment]
Interesting! How would you imagine this to work?

**Comment by mschipperheyn** [comment]
Click on the year and get a pulldown that allows you to quickly change the year. In this case, it should also be visually clear the the year is clickable.

**Comment by RSO** [comment]
Interesting! /cc @lbekkema @jenskanis

**Comment by KeitIG** [comment]
Any news on this ? :)

**Comment by RSO** [comment]
@KeitIG what do you think about the proposed solution? Would that fit your need? Or do you think we should build this in a different way. As always, you're free to create a PR with the proposed changes.

**Comment by KeitIG** [comment]
Hi @RSO. Yes, the above solution is what we see in almost every calendar plugins. I currently have no time for this due to a lot of work, I'll see if I can work on it this week-end. The only thing really stopping me is "how to simulate an infinite years list ? Should a lazy loading be done ?

**Comment by KeitIG** [comment]
useful ref http://zippyui.com/react-date-picker/
