### ISSUE TITLE
Uncaught Error: Minified React error #119;

### ISSUE THREAD

**Issue by iBasit** [Hacker0x01/react-datepicker#903]
After adding the plugin I get the following error, but it shows datepicker fine.

Uncaught Error: Minified React error #119;

![image](https://user-images.githubusercontent.com/34341/27395368-76ea7f88-56a7-11e7-908b-862089a69fff.png)

**Comment by rafeememon** [comment]
From the [link in the error message](https://facebook.github.io/react/docs/error-decoder.html?invariant=119)

> addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

See https://github.com/Hacker0x01/react-datepicker/issues/459
