### ISSUE TITLE
Replace `tether` with `popper` package for calendar popups

### ISSUE THREAD

**Issue by tohjustin** [Hacker0x01/react-datepicker#905]
This is a follow up from the discussion at #899.

Since the project status for [Tether](https://github.com/HubSpot/tether/) is [up in the air](https://github.com/HubSpot/tether#rotating_light-project-status-rotating_light), [Popper.js](https://popper.js.org/) seems like a better alternative & even the maintainers of Tether recommended it.

**Comment by tohjustin** [comment]
@alex-shamshurin @martijnrusschen @rafeememon Would be great if you guy can assign this issue to me =)

**Comment by rafeememon** [comment]
I don't think we use assignments in this repo but you're free to start working on this!

**Comment by FezVrasta** [comment]
Take a look at react-popper for a battle tested React integration with Popper.js

**Comment by tohjustin** [comment]
@FezVrasta Thanks for the heads up, will look at it over the weekend!

**Comment by alex-shamshurin** [comment]
Waiting for PR to test it!

**Comment by tohjustin** [comment]
@alex-shamshurin @rafeememon Just a quick question, do you think we should use `popper.js` directly or just use `react-popper`? Cause I'm a bit skeptical about how 'battle tested' this wrapper module is when there's no form of testing implemented =/

Also, let's say we're using `react-popper` and there's some bug in `popper.js` or `react-popper` itself, won't we have to wait for the guys w/ the `react-popper` to fix the stuff before we can update our dependencies & ship the fix on our end?

**Comment by FezVrasta** [comment]
I use react-popper in production and it works wonderfully.

I know there's an issue open to add tests, rather than create a new project consider add tests to the existing one maybe?

**Comment by tohjustin** [comment]
@FezVrasta Thanks for the quick reply! Didn't realize that you're also the creator of `popper.js`, I guess I shouldn't be worried about this issue then xD

**Comment by tohjustin** [comment]
@alex-shamshurin @rafeememon `Popper.js` uses a different way of specifying the behavior of the popups & there's some differences in functionality...

Do you guys intend to maintain the same API & all tether related props? (`classPrefix`, `attachment`, `targetAttachment`, `targetOffset`, `renderElementTo`, `constraints`)
