### ISSUE TITLE
Need to update Readme with latest React compatibility information

### ISSUE THREAD

**Issue by GreenAsJade** [Hacker0x01/react-datepicker#906]
It's great that there is a section about what version to use with which React.

Unforunately, it's a bit too out of date to be really useful.

**Comment by martijnrusschen** [comment]
Can you explain what you're missing, or maybe just create a PR with new info?

**Comment by GreenAsJade** [comment]
Hi, sorry for not being clearer.

I have to run with React 15.4.1 because react-bootstrap wont work with anything later.

Therefore, I need to know what version of react-datepicker is most appropriate.

react-datepicker@0.48.0 requires react-onclickoutside@6.1.1 which requires react@15.5.x.

I found by trial and error that react-datepicker@0.40.0 calls for react-onclickoutside@4.9.0 which is happy with react@15.4.1

Cheers,

GaJ

**Comment by alex-shamshurin** [comment]
Hmm, please provide a PR.

**Comment by GreenAsJade** [comment]
I would have thought an authoritative update would have been better, but my suggestion is here:

https://github.com/Hacker0x01/react-datepicker/pull/907
