### ISSUE TITLE
How do I track time change in state?

### ISSUE THREAD

**Issue by cbll** [Hacker0x01/react-datepicker#908]
I'm attempting to use your component here -  It works as intended in terms of the date transformation to ISO-8601, but I can't get it compliant with the time. Simply put the date can change in state, but irregardless of what the use changes in the time input, it will default to the initial time state and it can't be changed? 

Here's my component:

Stated initially:

```
    this.state = {
                from: moment().subtract(7, "days"), // Default 1 week back
                to: moment(), // Current date
            };

```
The component itself:

```
    <DatePicker
        dateFormat="DD-MMM HH:mm"
        dropdownMode="select"
        selected={this.state.from}
        onChange={this.handleFromChange}
    />
```

```
And the onchange trigger:

    handleFromChange(date) {
        this.setState({
            from : date
        });
    }
```

I think my issue is the dateFormat; The DD-MMM are easily transformed to ISO-8601 by calling using the ECMAScript function `toISOString()` before posting it to some backend services. But how do I get the time to go with it?

The user(myself, testing) can chance the time on the datepicker itself, but it won't register in the state. Simply it will just pick the current time, or current time 1 week ago(as per the moment from/to initial states). The date, i can change also, but the time remains the same(current time).

How do I change the dateFormat so it takes the time input from the user? How do I make it ISO 8601 compliant per default in the `dateFormat` attribute? 

Edit: I just tested with setting "from" to subtract 5 minutes at such:

    this.state = {
                from: moment().subtract(5, "minutes"),
                to: moment(), // Current date
            };

And it formats it correctly when I post it. Seems strange. It must be related to the onChange function then?

**Comment by alex-shamshurin** [comment]
I really did not get what you meant. What do you mean by 'track time'? When you select date with react-datepicker it simple keeps time of initial state time passed as `selected` property.

**Comment by martijnrusschen** [comment]
Closing due inactivity.
