### ISSUE TITLE
Is there a way we can easily handle top and left absolutes positions ?

### ISSUE THREAD

**Issue by PqBenoit** [Hacker0x01/react-datepicker#909]
It seems that the style of the popup `react-datepicker__tether-element` is reset each time you make it appear. What is the best way to add custom top/left positioning, since for now it is always reset to `top: 0px; left: 0px` ?

**Comment by rafeememon** [comment]
You can style `.react-datepicker__tether-element` in your stylesheet with the `top` and `left` properties.
