### ISSUE TITLE
Date picker still appears and date can be selected/changed when readOnly is true.

### ISSUE THREAD

**Issue by tfuda** [Hacker0x01/react-datepicker#911]
If you render the DatePicker component with the readOnly property set to true, you cannot type a date into the input field, however, clicking in the input field opens the calendar widget, and if you select a date from the calendar, it will update the value in the input field. I guess my expectation is that in readOnly mode, the calendar would not appear and the date should not be changeable. Is this the intended/desired behavior?

**Comment by alex-shamshurin** [comment]
I think `readOnly` is only about the input field itself and it does not mean that value cannot be selected via widget. Moreover - `readOnly` status can be changed and usually used to hide phone's keyboard.

**Comment by rafeememon** [comment]
Agreed with @alex-shamshurin -- if you need a true read-only field, use a plain `<span>` or a `<div>`, etc.

**Comment by alex-shamshurin** [comment]
With a `onChange` callback and custom input you have full control over the your state. You can do that `onChange` does nothing

**Comment by tfuda** [comment]
Thanks for the clarification.
