### ISSUE TITLE
Defining week number as a function

### ISSUE THREAD

**Issue by duncanfwalker** [Hacker0x01/react-datepicker#912]
A lot of big enterprises have their own week numbering system. I would like to be able provide a function as prop for calculating the current week number following that company's business logic.

The week numbers used in react-datepicker come from moment. The way to change how they are calculated in moment is to define a custom locales. There are a couple of problems with this 1) its not really a /locale/ we're talking about here 2) Custom locales only allow you to define the first day of the year as a fixed integer, which isn't enough to represent the logic that I need for determining the week number.

Instead I would like to passing a function as prop to DatePicker that calculates the week number. I can understand that you may want avoid doing this to keep moment handling the date domain. At the same time I think this is probably a fairly common use case so it would be great to see it supported in react-datepicker. What do you think? If you're happy with the idea in principle I'm happy to work up a PR.

**Comment by alex-shamshurin** [comment]
Could your provide more info about your use case. The primary intention of this widget is a date selection. Why you need week numbers? You can calculate week number of selected date outside, I think.

**Comment by duncanfwalker** [comment]
We are trying to replace something that looks like this
![old date picker](https://user-images.githubusercontent.com/2590892/27692896-c356d7b6-5cdf-11e7-82df-78f0f507367e.jpg)

The week numbers help with finding the date the user wants. In the corporation I'm working for (and in other very large organisations). All of the weeks of the year have numbers that are used consistently across the organisation for scheduling. For example when ours user is talking about a specific date they may say 'the tuesday of week 10', rather than 'March 12th'. 

The week numbers are not necessarily the same as the ISO week numbers, the way of calculating week number may vary from one organisation to another.

**Comment by rafeememon** [comment]
Can you give a concrete use case for needing a function, as opposed to just specifying a new start-of-the-week day?  Any function that doesn't behave in that way would produce unpredictable layout behavior in the datepicker when showing the week number.

**Comment by duncanfwalker** [comment]
At the organisation I am working for the 
2017 week 1 is 31st Dec - 7th Jan
2016 week 1 is 2nd Jan - 9th Jan

How this is decided is based on complex logic that is roughly which week is the first to have more than 3 days in the new calendar year.

A rule I have seen at another organisations is week 1 starts the first Monday after Christmas

**Comment by duncanfwalker** [comment]
If this seems a reasonable parameter to extract I can make a PR?

**Comment by sentient06** [comment]
Some companies that deal with scheduling events do have unorthodox week numbering systems that can increase the number of weeks in an year or decrease, positioning the next year's week #1 before and ahead the ISO standard. Also, it could be useful for situations like fiscal year starting in April, for example.

**Comment by martijnrusschen** [comment]
Sure, if you suggest a PR with some possible solution than we can take a look to see if we think it's a worthy addition.

**Comment by sentient06** [comment]
Hello, please find the PR below. All the best.
https://github.com/Hacker0x01/react-datepicker/pull/934
