### ISSUE TITLE
Can't use the package

### ISSUE THREAD

**Issue by iphonic** [Hacker0x01/react-datepicker#914]
Hey there, the library looks awesome, downloaded the source code it works fine.. I want to integrate to my app, so I followed

> npm install --save react-datepicker moment

it doesn't seem to be working for me, is there any extra setting do I need to do apart from including the loaders for css? What are all dependencies do I need to install and configure..

Please Help!!
Thanks.

**Comment by rafeememon** [comment]
What is the error you're seeing?

**Comment by alex-shamshurin** [comment]
Please provide additional information.

**Comment by iphonic** [comment]
Below is my import 

```
import DatePicker from 'react-datepicker';
import moment from 'moment';

import 'react-datepicker/dist/react-datepicker.css';
```
I don't get any error, but it looks like this

![screen shot 2017-06-29 at 12 22 02 am](https://user-images.githubusercontent.com/5745637/27654987-5eb5be04-5c61-11e7-9df9-f6c0f1ca8ff1.png)

Thanks.

**Comment by alex-shamshurin** [comment]
Styles are not applied. Supply the whole file.

**Comment by shnako** [comment]
@iphonic Add this to your main.js:
require('react-datepicker/dist/react-datepicker.css');
