### ISSUE TITLE
maxDate used but year dropdown still showing  future years

### ISSUE THREAD

**Issue by Puneetbh** [Hacker0x01/react-datepicker#918]
i have used below configuration with maxdate value today, when calendar opens it is showing future years in dropdown i.e. 2011,2022, etc
![screen shot 2017-06-29 at 6 17 56 pm](https://user-images.githubusercontent.com/5443708/27688186-5ae0b658-5cf7-11e7-9bea-4961f663e6b7.png)

<DatePicker {...input} 
          showYearDropdown={true}
          showMonthDropdown={true}
          maxDate={new Date()}  //maxDate
          maxMonth={new Date()}  //maxDate
          inline dropdownMode="select"
      	/>

**Comment by acollier88** [comment]
maxDate={moment()} solves it
