### ISSUE TITLE
Dependency on React < 0.13

### ISSUE THREAD

**Issue by manuelmeurer** [Hacker0x01/react-datepicker#92]
Is it necessary to limit React to < 0.13 in bower.json?
If not, a new release with that limit removed would be much appreciated! :smile: 
(I can submit a PR with that change if needed)

**Comment by RSO** [comment]
I haven't tested it yet in 0.13, could you confirm if the datepicker works in 0.13?

**Comment by manuelmeurer** [comment]
Yep, it works fine, have been running it with 0.13 for a couple of days now.

**Comment by manuelmeurer** [comment]
:+1: cheers!
