### ISSUE TITLE
Is there any way to open the datepicker in a specific month?

### ISSUE THREAD

**Issue by renatho** [Hacker0x01/react-datepicker#922]
I want the datepicker to open in a specific month, starting the datepicker navigation based on a month previously selected in my application.

Eg.: Today is July, 3. But the user selected a February filter in my application and I want to show the Datepicker with this context, but allowing the user to navigate normally to other months.

Can I do it with some param?

**Comment by marius-vlas** [comment]
You can:
https://hacker0x01.github.io/react-datepicker/#example-27
