### ISSUE TITLE
isClearable doesn't work when the input lose focus

### ISSUE THREAD

**Issue by mrtrandinhvn** [Hacker0x01/react-datepicker#923]
[In this "Clear datepicker input" example](https://hacker0x01.github.io/react-datepicker/#example-17)
Reproduce steps:
1. Type a valid date.
2. Click outside to lose focus.
3. Click on clear date button
**Expectation**: The input value is cleared.
**Reality**: only selected prop is cleared.
![image](https://user-images.githubusercontent.com/11169633/27816125-c1983e38-60b3-11e7-9ae5-7d6db6e01da3.png)

**Comment by victorredondoGL** [comment]
Can we get this fix merge? Im running in the same issue and the fix seems to be pretty clear.
Thanks guys
