### ISSUE TITLE
Calendar in Popover component is blurry anyway on zoom, in Chrome browser (css3 transform transition)

### ISSUE THREAD

**Issue by kotoo** [Hacker0x01/react-datepicker#924]
![image](https://user-images.githubusercontent.com/23284240/27817904-10f884aa-609c-11e7-9675-f4cea8eb834b.png)
![image](https://user-images.githubusercontent.com/23284240/27818054-c2218f4c-609c-11e7-8f4f-c326bfa61032.png)

Can you make optional prop for choosing position method (by css3 "transform: transition" or "top, left, z-index")? In Chrome browsers text seems blurry on zoom or lower screen dimensions - transform: transition properties do it.

Maybe overload this in "style={ ... }" of calendar ref, as example?

**Comment by tohjustin** [comment]
This is probably related to #899

**Comment by martijnrusschen** [comment]
This should be fixed now.

**Comment by U-4-E-A** [comment]
I was having this issue in Chrome. I resolved it by adding this to the popperModifiers config: -

computeStyle: { gpuAcceleration: false }

Hope that helps someone.

**Comment by neminovno** [comment]
@U-4-E-A Yes it does. Thank you. For others here is how you add it:
```
<DatePicker
    selected={this.state.selectedDate}
    onChange={this.onDateChange}
    dateFormat="dd-MMM-yyyy"
    popperModifiers={{
        computeStyle: { gpuAcceleration: false }
    }}
/>
```
