### ISSUE TITLE
Datepicker don't switch to new range in inline mode

### ISSUE THREAD

**Issue by m1n0s** [Hacker0x01/react-datepicker#927]
Hi! I faced with a problem that I use DatePicker across the site and in one place I need it just for showing a quarter of year like the calendar.
Steps to reproduce:
1. Add inline datepicker
2. Change selected date (or min max dates like in my example)
3. Expect to switch calendar to the new range but it works just after click somewhere on the page.

I try to find own solution and I think it relates to #743 
But it strange that after click somewhere it works fine. Could I somehow forceUpdate datepicker to implicitly call `setOpen()` or whatever what makes it work :)

Here is the link to screencast of issue -> http://take.ms/oSAc8

I show the debugger statement that doesn't fire after the last click.

Thank you.

**Comment by m1n0s** [comment]
@martijnrusschen could you tell me when approximately will be a release with this fix? Thanks.

**Comment by martijnrusschen** [comment]
Consider it done!

**Comment by martijnrusschen** [comment]
0.50.0 is released.

**Comment by m1n0s** [comment]
@martijnrusschen, unfortunately, the bug is still present. Please reopen an issue, I'll try to fix it myself and make a PR after if success.
