### ISSUE TITLE
Allow hiding dates from the previous/next month

### ISSUE THREAD

**Issue by xzyfer** [Hacker0x01/react-datepicker#928]
Essentially allowing people to emulate the Google Analytics style of date picker. 

![image](https://user-images.githubusercontent.com/579928/27945384-0eeae41e-6330-11e7-8e14-45c2acae4a74.png)

This would also respect `monthsShown`.

![image](https://user-images.githubusercontent.com/579928/27945470-873493de-6330-11e7-892a-b337d1a1bf62.png)

Our users have mentioned it's difficult to select common dates of interested like 1st of the month quickly. We could highlight these dates but that feels like a work around. 

I'm happy to do implementation if you're interested in it.

**Comment by aij** [comment]
You can already customize the appearance of those days via the `react-datepicker__day--outside-month` CSS class.

**Comment by rafeememon** [comment]
You can probably style the outside-month class with `visibility: hidden` to get what you need.

**Comment by xzyfer** [comment]
Thanks!

**Comment by IgorZd** [comment]
@karlkras If you want to short name of week to one letter, you should do it: 
<DatePicker formatWeekDay={(nameOfDay) => nameOfDay.substr(0, 1)} />

**Comment by dygy** [comment]
for me solution were 
```
    :global(.react-datepicker__day--outside-month) {
      display: none;
    }
    :global(.react-datepicker__week) {
      text-align: left;
    }

```

**Comment by thusmiley** [comment]
This worked for me, I had to combine it with .react-datepicker to get it work:

.react-datepicker .react-datepicker__day--outside-month {
  @apply text-almostBlack/10 dark:text-white/10 font-medium cursor-none;
}

**Comment by musamaashraf** [comment]
`.react-datepicker__day--outside-month {
  visibility: hidden;
}`

This worked for me. `display: none` was making dates on saturdays and sundays go wrong.
