### ISSUE TITLE
Does this have an ExcludeDays Feature

### ISSUE THREAD

**Issue by tejasvimahesh** [Hacker0x01/react-datepicker#929]
Hi,

First of all i would like to thank you for providing a great tool in react for datepicker. However, i am stuck in one phase. You do excludeDates feature but i was unable to find excludeDays, which is, i can be able to exclude specific days across months in the calendar. like, i can add specific days like this 

excludeDays={[2,4,10,15,20]}

which will disable the above dates across months.

Any Help in regard to this would be deeply appreciated.
Thanks.

**Comment by rafeememon** [comment]
You can use the [`filterDate` prop](https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md) to specify a filter that can accomplish this.
