### ISSUE TITLE
Add additional classes to container div

### ISSUE THREAD

**Issue by rkosafo** [Hacker0x01/react-datepicker#932]
From the docs, there is the `className` prop for adding additional classes to the input element. Is there a way to do same for the container element?

I'm using the component with `Semantic-Ui` and for proper styling need to add `ui input` to the container div. At the moment, the temporary "work around" is to edit the output js and add the additional classes to `react-datepicker__input-container`. Is there a way to do this?

**Comment by sentient06** [comment]
I have the same problem, I've been forced to wrap the datepicker in a parent element with the class I require to include an icon in the input.

**Comment by aij** [comment]
#740 should fix this when it's merged.

**Comment by nbkhope** [comment]
Same problem here with Semantic UI !

**Comment by nbkhope** [comment]
@rkosafo could you elaborate how you got to apply `ui input` to the date picker input? My problem is I need the input to be fluid, so I need to apply the following class to a div containing the input: `ui fluid input`.

**Comment by rkosafo** [comment]
@nbkhope In my case, I just added the class directly to the source file. Only problem is that it is lost, after e.g. adding a new npm package, and must be done again.

@aij Is there anything we can do to get the PR merged?
