### ISSUE TITLE
Latest version does not open popup inside table

### ISSUE THREAD

**Issue by vitaliy-komenda** [Hacker0x01/react-datepicker#937]
It seems like migration to popper.js broke popup position.
I think it has something related to https://github.com/FezVrasta/popper.js/issues/276

**Comment by FezVrasta** [comment]
I'd love to get this fixed. It shouldn't be a complex bug. But for personal reasons I'm going to be away from PC for some time. If someone could come up with a PR it would be awesome.

**Comment by bradbirnbaum** [comment]
I am also having issue as a result of switching from `tether` to `popper`

**Comment by evolve2k** [comment]
To clarify for future reference, the version under discussion is 0.49 and this change:
- Migrate from tether.io to popper.js for handling calendar popups

Workaround: Revert back to 0.48 for the mean time.

**Comment by vitaliy-komenda** [comment]
@evolve2k I cannot because it fails in Jest test with: Invariant Violation: getNodeFromInstance: Invalid argument.

**Comment by FezVrasta** [comment]
the table bug should be fairly easy to fix if anyone wants to give it a shot in the Popper.js repo

**Comment by f2net** [comment]
This project is using "react-popper", not "popper.js" by FezVrasta (which should have solved this problem since 1.11.0).

**Comment by FezVrasta** [comment]
react-popper depends on popper.js@1.x so you are able to update the popper.js version independently

**Comment by pierre-H** [comment]
Does anyone have a concrete solution ?
I have the bug inside a table...

**Comment by rafeememon** [comment]
@pierre-H did you try bumping popper.js to 1.11.0?

**Comment by martijnrusschen** [comment]
Perhaps #1001 might help?

**Comment by rafeememon** [comment]
@martijnrusschen, with the caret dependencies, it can be bumped independently -- it only locks in the first non-zero number, and from what I can tell the recent react-popper dependencies are also carets.  Regardless, we should make that change =)

**Comment by martijnrusschen** [comment]
Ah yes, just upgrading it for my own sanity to get it removed from the `yarn outdated` list in that case :)
