### ISSUE TITLE
isClearable doesn't work if you paste the value into

### ISSUE THREAD

**Issue by mikkanika** [Hacker0x01/react-datepicker#938]
If you paste any value into this component clearable button doesn't work.
If you choose the value from the calendar it works smoothly.

In version **0.41.1** this functionality worked smoothly as well (with pasting value).
In version **0.48.0** - doesn't.

**Comment by poushy** [comment]
Facing same issue with typing in value as well.

**Comment by mikkanika** [comment]
Acctually "handleChange" does not work if you paste the value into.
