### ISSUE TITLE
Inline style of 'display: inline-block' applied to popper target container

### ISSUE THREAD

**Issue by kyleturman** [Hacker0x01/react-datepicker#943]
In the popper component, it adds a div with an inline style of `display: inline-block` [shown here](https://github.com/Hacker0x01/react-datepicker/blob/43816d69a450dcc11d3a03da973d92b4947c6651/src/popper_component.jsx#L58).

It'd be great if this was a class instead so better customizations could be made to the styling of the input, specifically in regards to width—right now you can't make the width of the input 100% due to this.

**Comment by siarheipashkevich** [comment]
@kyleturman I have the same issue.

Please add the ability to setup a class for this div element.

**Comment by sahaviev** [comment]
I have the same issue too.
Please fix this foolish programming choice...

**Comment by rafeememon** [comment]
@sahaviev @siarheipashkevich PRs to fix this are absolutely welcome

**Comment by sahaviev** [comment]
@rafeememon ok, I will try to fix and commit it now

**Comment by sahaviev** [comment]
ready..

**Comment by tohjustin** [comment]
My bad, should have notice this mistake earlier on =S 

Thanks @sahaviev for fixing it! #944

**Comment by kyleturman** [comment]
Thank you @sahaviev and @tohjustin!
