### ISSUE TITLE
Pressing enter with an invalid date cause the date picker to select today

### ISSUE THREAD

**Issue by dbertella** [Hacker0x01/react-datepicker#945]
Step to reproduce:
From any example in the date picker if you type anything in the input field that is not a valid date and press enter you will find today as selected date.

Is this a design choice or is it a bug? 
I'll be happy to add a PR about this, I'm just wondering what's the expected behaviour. 
I think the date picker should have an error state but I didn't see anything about errors in the library.

**Comment by mellis481** [comment]
This is still an issue for me.  In my situation, however, I can enter a valid date which it will correctly accept onBlur, but if I hit ENTER, it will ignore my valid date and pick today.  I even tried adding `disabledKeyboardNavigation`, but that did nothing.
