### ISSUE TITLE
Cannot read property 'classSet' of undefined

### ISSUE THREAD

**Issue by kylecesmat** [Hacker0x01/react-datepicker#95]
Might be worth noting somewhere that this package requires react with addons for the classSet utility to work correctly. And with that being depreciated soon, maybe looking at including another utility.

For the time being, I was able to get it working in my app with `var React  = require('react/addons');`

**Comment by RSO** [comment]
Good call, `classSet` is deprecated, I'll remove it!

**Comment by RSO** [comment]
This should be fixed in 0.6.2! Sorry for the inconvenience
