### ISSUE TITLE
Problems with DatePicker and moment (sorry for my lack of knowledge)

### ISSUE THREAD

**Issue by jcabrerazuniga** [Hacker0x01/react-datepicker#954]
I am using the next React component:

    <DatePicker
            selected = {this.state.startDate}
			onChange = {(d) => {console.log('date = ' + d); 
                        this.setState({startDate: d})}}
						dateFormat="MMMM, DD, YYYY"
	/>

it works fine if startDate is equal to moment() but I get error message if I execute

    this.setState({startDate: 	momdate});

where

    var momdate = moment('2017-10-22').valueOf() / 1000;

and this instruction is executed at the 

     componentDidMount()

react function. The error message is:

      Uncaught TypeError: e.clone is not a function

Any ideas, please?

**Comment by rafeememon** [comment]
You must pass a moment object into the `selected` prop; `moment('2017-10-22').valueOf() / 1000` evaluates to a number.
