### ISSUE TITLE
Increasing dimensions of datePicker

### ISSUE THREAD

**Issue by jcabrerazuniga** [Hacker0x01/react-datepicker#957]
Is there a way to increase the dimensions of the DatePicker?
I unsuccessfully tried something like:

      <DatePicker style={{height: '600px'}}

In my app. the DatePicker appears smaller than in your examples 

Thanks

**Comment by jcabrerazuniga** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/624

**Comment by shrutic** [comment]
The issue mentioned updates the sizes of the font inside the calender. However the question is about how to increase the length/height of the input box itself

**Comment by staho** [comment]
You want to do something like this in your css file
`
.react-datepicker__input-container {
  width: inherit;
}

.react-datepicker-wrapper {
  width: 100%;
}

`
