### ISSUE TITLE
problem with manual editing

### ISSUE THREAD

**Issue by sOstrovsky** [Hacker0x01/react-datepicker#958]
when property 'value' is set input becomes disabled for manual input and i can change date only by picking from calendar. Are there any solution to change date by manual editing and by picking from calendar?

`<DatePicker
                            locale="ru-ru"
                            onChange={e => {
                                this.setState({startDate: e._d})
                            }}
                            value={this.state.startDate}
                        />`

**Comment by tesarm** [comment]
use `selected=` instead of `value=` to set it
