### ISSUE TITLE
make disable or readonly input field

### ISSUE THREAD

**Issue by manishk-sdei** [Hacker0x01/react-datepicker#961]
i dont want my users to input in the datepicker field, there is no property that we can add and it become readonly or disabled for input from keyboard

**Comment by aij** [comment]
If I understand, you want to set extra props on the input element itself, without making the datepicker as a whole readonly or disabled? Have you tried `customInput`?

**Comment by Mukhammadali** [comment]
hi @manishk-sdei ! This can fix it. 
```
componentDidMount(){
    const datePicker=document.getElementsByClassName("react-datepicker__input-container")[0];
    datePicker.childNodes[0].setAttribute("readOnly",true);
  }
  
```

**Comment by bcullman** [comment]
If you want your users to *only* use the calendar control and not the input field, you need to use an alternate method for blocking text input - read-only has a defined meaning, per W3C - it specifies the value can not be edited by the user. see

https://www.w3.org/TR/html401/interact/forms.html#adef-readonly

**Comment by coderade** [comment]
@Mukhammadali solution for when you have more than one input (eg. date and timeOnly pickers)

     componentDidMount() {
        const datePickers = document.getElementsByClassName("react-datepicker__input-container");
        Array.from(datePickers).forEach((el => el.childNodes[0].setAttribute("readOnly", true)))
    };
