### ISSUE TITLE
Unable to set dateFormat="DD/MM/YYYY" or any other format and unable to close mobile keyboard

### ISSUE THREAD

**Issue by SyedSaifAli** [Hacker0x01/react-datepicker#964]
Hello,
The problem I am facing is I am unable to select dateFormat, everytime I am trying to select a dateFormat, it is not reflecting in the date field. Also I wanted that on click of the date field the keyboard of mobile should not pop up. How can I achieve that?

**Comment by joinsunil** [comment]
I am also facing the same issue. MM/DD/YYYY dateFormat does not work.
