### ISSUE TITLE
Invalid keyboard input ignored when datepicker returns back to focus.

### ISSUE THREAD

**Issue by buhuitou** [Hacker0x01/react-datepicker#966]
Hi there,
I notice the following behaviour:

1.  type an invalid date into datepicker and then press Tab to cause it lose focus.
2. press shift-TAB to make it get focus again and then press Enter.

Expected: the invalid input is not accepted.
Actually: today is selected.

**Comment by Aprillion** [comment]
sounds like https://github.com/Hacker0x01/react-datepicker/issues/945 which is already merged - regression or not relased yet plz?

**Comment by Aprillion** [comment]
#996 might help with the "press Enter" part when using `disabledKeyboardNavigation` ;)

**Comment by superyarik** [comment]
also there is case: with date+time, when we type date without time it also select today, but will be better select typed date + 00:00 time

**Comment by Gintez** [comment]
Did someone find a workaround for this?
