### ISSUE TITLE
Week always starts on Monday

### ISSUE THREAD

**Issue by heivo** [Hacker0x01/react-datepicker#970]
Hi,

changing the `locale` seems to have no effect, the week always starts on Monday.

Thanks for this great library!

**Comment by KevinTrinche** [comment]
Hi,

i have the same issue, if someone have the answer.
That's be pretty cool !

**Comment by KevinTrinche** [comment]
I found a solution.

You have to insert :  import 'moment/locale/en-gb';
and you can use locale="en-gb".

Now my week begin on Monday.

**Comment by rafeememon** [comment]
More generally, you can use any of moment's localization features: https://github.com/Hacker0x01/react-datepicker#localization

**Comment by Mekbib-awono** [comment]
I solved it this way..
`
import enGb from 'date-fns/locale/en-GB';
registerLocale('en-gb', enGb);

        <DatePicker
          locale="en-gb"
        />
`

**Comment by tonyrol** [comment]
How can I use react-datepicker with moment since it has more locales than date-fns ?

**Comment by FColacilli** [comment]
Also if your locale doesn't have the start date you wish, you can override the default values by doing this:
```
import DatePicker, { registerLocale } from "react-datepicker";
import es from "date-fns/locale/es";
registerLocale("es", { ...es, options: { ...es.options, weekStartsOn: 0 } });

const MyComponent = props => (
        <DatePicker
             locale="es"
        />
);
```
