### ISSUE TITLE
_reactOnclickoutside2.default is not a function

### ISSUE THREAD

**Issue by dhruvparmar372** [Hacker0x01/react-datepicker#975]
I'm using react-datepicker in the following way. 
```
import ReactDatePicker from 'react-datepicker/lib/datepicker';
```
I'm getting this error related to react-onclickoutside.

`VM17482:94 Dynamic page loading failed TypeError: (0 , _reactOnclickoutside2.default) is not a function`

Versions of packages I'm using
```
react: 15.6.1
react-datepicker: 0.52.0
webpack: 2.1.0-beta.15
```

**Comment by dhruvparmar372** [comment]
After digging around I figured this might be due to https://github.com/webpack/webpack/issues/706

**Comment by cinic** [comment]
I fixed it by changing react-datepicker to [airbnb/react-dates](https://github.com/airbnb/react-dates) :+1:

**Comment by NI-Hsu** [comment]
Facing the same problem
seen no one care
