### ISSUE TITLE
"Only a ReactOwner can have refs" error with react-datepicker and minified versions of react, react-dom

### ISSUE THREAD

**Issue by gregpasha** [Hacker0x01/react-datepicker#977]
When I include the react, and react-com minified versions for a production build, I get the below  error coming from react-datepicker (the error goes away if I remove react-datepicker). I am running react version 15.5.4, react-datepicker 0.52.0

**Error:**
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

**Pertinent WebpackConfig** 
webpackConfig.resolve.alias = {
  react$: path.join(basePath, 'node_modules', 'react', 'dist', 'react.min.js'),
  'react-dom$': path.join(
    basePath,
    'node_modules',
    'react-dom',
    'dist',
    'react-dom.min.js'
  ),
  redux$: path.join(basePath, 'node_modules', 'redux', 'dist', 'redux.min.js'),
  'react-redux$': path.join(
    basePath,
    'node_modules',
    'react-redux',
    'dist',
    'react-redux.min.js'
  )
};

**Comment by danoc** [comment]
![image](https://user-images.githubusercontent.com/916038/29442988-db5aa682-8389-11e7-8c2b-27a57daaad1c.png)

I'm getting this issue at well. Seems to be related to the `calendar` ref.

**Comment by rafeememon** [comment]
I think this comes up when the datepicker component is used inside of a stateless functional component.  Unfortunately refs don't work inside of SFCs.

**Comment by gregpasha** [comment]
I am not using inside a SFC, it's only happening when I use minified react.

**Comment by danoc** [comment]
@gregpasha – Is there any chance that you are running two copies of React on your page? 

It turns out we were. Spent many hours trying to remove the extra version and see if it fixes this issue but our build system is complicated so this is unfortunately not trivial.

Here's a blog post to help see if you have two versions of React running:
https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375

**Comment by danoc** [comment]
Just want to circle back and point out that the issue we were having was indeed related to loading two versions of React on our pages.
