### ISSUE TITLE
Date does not change (from default date)

### ISSUE THREAD

**Issue by Kotoriii** [Hacker0x01/react-datepicker#979]
Hi, I'm trying to set the state of a component with datepicker from a parent component. But the date or input never change from the default moment() date after clicking on another date on the picker, manual input with keyboard (it goes back to default onBlur), etc. The state does not change either according to React Console. Please note that the Placeholder Text is not showing either. Here is my code:

Parent Component:

```
constructor(props) {
    super(props);

    this.state = {
      wants_interview_date: moment(),
  }
}

handleDateChange(date) {
    return (evt) => this.setState({ wants_interview_date: date });
 }

return <ChildComponent
        wants_interview_date={this.state.wants_interview_date}
        onDateChange={this.handleDateChange} />;

```

Child Component:

```
<DatePicker
  selected={this.props.wants_interview_date}
  onChange={this.props.onDateChange}
  className="form-control"
  id="wants_interview_date"
  placeholderText="Choose a Date"
/>
```

I am using `Create-React-App` if that makes a difference. Any ideas or tips are welcome (ASAP!).

**Comment by andrewwong97** [comment]
See #324

**Comment by andrewwong97** [comment]
Essentially if you want to use the setState function, you need to bind it to the component. Alternatively, you can use the ES6 arrow function inline to avoid having to bind.

**Comment by andrewwong97** [comment]
```
return <ChildComponent
        wants_interview_date={this.state.wants_interview_date}
        onDateChange={(date) => this.setState({wants_interview_date: date})} />;
```

**Comment by rafeememon** [comment]
In addition to binding the callback to the component, in the provided code, `handleDateChange` is returning an anonymous function that is never invoked; `setState` should be the only thing in the callback.

**Comment by jandranrebbalangue** [comment]
@jaintarun268 did you fixed the issue?
