### ISSUE TITLE
Wrong position inside table

### ISSUE THREAD

**Issue by trungdq88** [Hacker0x01/react-datepicker#983]
![react-datepicker](https://user-images.githubusercontent.com/4214509/29068357-a5e4eb6e-7c60-11e7-96bf-bc1f4b91ed73.gif)

Live demo: https://codesandbox.io/s/GJoOm2y5

Seem to be related to https://github.com/FezVrasta/popper.js/issues/276

Is there any workaround for this?

**Comment by rafeememon** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/937
