### ISSUE TITLE
customInput doesn't respect className

### ISSUE THREAD

**Issue by heatherbooker** [Hacker0x01/react-datepicker#986]
When I pass a customInput with a div as the outermost wrapper, any classNames associated with that div are removed in rendering. For example,

```
<div className="potatoes">
  <input />
  <button>hi</button>
</div>
```

Is rendered as 

```
<div>
  <input />
  <button>hi</button>
</div>
```

I also notice that an `id` is stripped from the outermost component, and that changing the element type of the outermost component doesn't prevent this from happening. 

Is there a reason for this or it's just a quirk?
Thanks!

**Comment by serkolch** [comment]
Hey! I was trying this out earlier and noticed that too - if I passed an element in with className, the html would show a class attribute with nothing else there.

In my case, I was just passing in a render function into customInput such as

```
render () {
    return <DatePicker
        customInput={this.renderInput()}
    />
}

renderInput () {
    return <div className="test" />;
}
```

I was able to get the classes to work when I took the custom input out of the React class and into its own CustomInput component. Hope that helps!

**Comment by sonofjack** [comment]
The docs where not clear on this, I got the `className` to render on the `customInput` when providing it to the parent `<DatePicker />` component.

This will render the `custom-class` on the button component

```
<DatePicker
  className="custom-class" 
  customInput={<Button>{value}</Button>}
/>
```

**Comment by mdelrossi1** [comment]
I felt this was counterintuitive too.  Initially I
