### ISSUE TITLE
Change to mobile calendar?

### ISSUE THREAD

**Issue by serkolch** [Hacker0x01/react-datepicker#988]
Is there a way that the calendar appears like a mobile/native calendar (achieved with something simple like input type="date"?

This would make the mobile web experience much better

**Comment by rafeememon** [comment]
You probably just want to use a native `<input type="date">` for that

http://mobileinputtypes.com/

**Comment by Charlie91** [comment]
`<input type="date">` is too unflexible to be a normal datepicker. There is no any native decision to choose data with 'DD MMM' format, without year.
