### ISSUE TITLE
Allow to click on the calendar without closing it

### ISSUE THREAD

**Issue by lbelinsk** [Hacker0x01/react-datepicker#989]
I want to use the DatePicker with range (startDate and endDate)

![image](https://user-images.githubusercontent.com/18248989/29180689-388fb272-7e01-11e7-9513-14d951df515e.png)

The user will click twice to select the start and end date. the problem is that each click will close the datePicker.

I found an ugly hack by using ref:

```
<ReactDatepicker
          ref={reactDatePicker => this.reactDatePicker = reactDatePicker}
          onChange={val => //if firstClick the set startDate and don't close calendar, else set endDate and close calendar
          customInput={this.renderInput()}
          onSelect={() => setTimeout(() => this.r.reactDatePicker.setOpen(true), 0)}
          startDate={startDate}
          endDate={endDate}
          onSelect={() => setTimeout(() => this.reactDatePicker.setOpen(true), 0)} ///hack!!!!
/>
```

I can track the clicks and to know if this is first click or a second one, but I cant find a good way to leave the calendar open.
Even this hack is just opening the calendar just after it gets closed.

Can I create a pr to add a new dynamic prop like **shouldCloseOnSelect** ?
This will be a boolean, and I will set it to true when it is second clidk, and to false when this is going to be the first click.

This prop will be used here, in order to prevent the calendar to automatically close:
https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L225

**Comment by martijnrusschen** [comment]
Totally off topic, but huge props to the design! This looks terrific! Would love to have support for multiple designs so we can offer this by default as an option.

**Comment by lbelinsk** [comment]
Thanks :)
This is from wix-style-react: https://wix.github.io/wix-style-react/?selectedKind=Core&selectedStory=DatePicker&full=0&down=0&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by lbelinsk** [comment]
The design is not completely ready yet, it is a work in progress, but let me know how would you like us to contribute.

Returning to topic, we really need this feature so hopefully I will get an answer for that as well.
tnx

**Comment by martijnrusschen** [comment]
I think an additional prop could work here. I would assume that normal behaviour would close the datepicker after picker a date, but I'm fine with overriding this if you need different behaviour.

**Comment by lbelinsk** [comment]
I agree - 
defaultProps. shouldCloseOnSelect = true

Cool, I will  prepare a pr then..

**Comment by martijnrusschen** [comment]
Awesome, thanks!

**Comment by lbelinsk** [comment]
Pr is ready :)
#992

**Comment by martijnrusschen** [comment]
Just pushed: https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.53.0
