### ISSUE TITLE
If minDate and maxDate have values the selected date should be between them

### ISSUE THREAD

**Issue by robbinjanssen** [Hacker0x01/react-datepicker#99]
To create between and not between functionality the calendar should respect the following rules:

- If minDate < maxDate the selectedDate must be between minDate and maxDate.
- If maxDate < minDate (which sounds strange, but hear me out), the selectedDate must be **before** maxDate and **after** minDate. (e.g. not between maxDate and minDate).

**Comment by robbinjanssen** [comment]
I'm not able to create a branch/pull request, so here are the fixes I applied to achieve this.

In util/date.js add:
```
DateUtil.prototype.isBetween = function(begin, end) {
    return this._date.isBetween(begin._date, end._date, 'day');
};
```

in calendar.jsx at line 87 add:
```
    if (minDate._date !== null && maxDate._date !== null) {
      disabled = !(minDate.isBefore(maxDate) ? day.isBetween(minDate, maxDate) : !day.isBetween(maxDate, minDate));
    }
```

**Comment by RSO** [comment]
Interesting feature request. I think that I would be open to implementing something like this, but would like to add some tests before I add it to the codebase.

Small comment on the code change:

Wouldn't this work the same as the code you proposed?

```lang=javascript
var disabled = day.isBetween(maxDate, minDate);

if (minDate.isBefore(maxDate)) {
  disabled = ! disabled
}
```

I'll see if I can find some time this weekend to write some tests. Thanks for the suggestion!

**Comment by robbinjanssen** [comment]
I think it does. I can test it tonight in my own fork and let you know, but im quite sure it is the same.

Thanks for picking this up!

**Comment by rafeememon** [comment]
I'm not this should be implemented, in the interest of keeping a simple API.  This is possible with either `excludeDates` or `filterDate`.
