### ISSUE TITLE
The onChange callback also invokes the onSelect callback

### ISSUE THREAD

**Issue by benbcai** [Hacker0x01/react-datepicker#990]
I want to use the onSelect prop to only listen when selecting a date from the picker. However, when I manually enter a valid date, the onSelect callback is also invoke in addition to the onChange callback.

I would expect that selecting a date from the picker would invoke both onSelect and onChange and manually entering a date should only invoke onChange and not onSelect (since I did not select a date from the picker).

It looks like the [handleChange](https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L210) function simply calls setSelected, which will invoke both onChange and onSelect.

The workaround I'm using is when I'm handling the onSelect event, I check to see what the event type is. If the event type is `change` then it is invoked from onChange. If the event type is 'keydown' or 'click', then it is invoke from either clicking a date or hitting the Enter key from the picker.

**Comment by alex-shamshurin** [comment]
I think you are right. `onSelect` must be called when you `select`.
