### ISSUE TITLE
Testing component with Enzyme gives `<t />` name

### ISSUE THREAD

**Issue by nbkhope** [Hacker0x01/react-datepicker#993]
Hi guys, I have a component that includes the `<DatePicker />` component and am trying to test to make sure it is there. I am using Enzyme (with shallow wrapper) to test it. Usually I do the following to check the existence of a certain component:

```
expect(
  enzymeWrapper.find('DatePicker').length
).toBe(1)
```

My expectation is to find the `DatePicker` by its component name -- "DatePicker" -- however it is showing up with simply a "t" for its name, as demonstrated by console logging the node for the component (I did manual, exact search using `.children()` and `.at()`):

**.text()**:
```
<t />
```

**.name()**:
```
t
```

(1) Why isn't the component name just DatePicker?
(2) Is there a specific way to check for the existence of a DatePicker component inside mine using Enzyme and its find method?

(PS: my tests work properly if I search using `component.find('t')`, but why on earth would you have that single letter for a component name?)

**Comment by davidtheclark** [comment]
Looks to me like the cause of this is that the `package.json`'s `main` field is pointing to `dist/react-datepicker.min.js` — the minified file. Instead, I believe that *should* point to `dist/react-datepicker.js`, and leave it to the user to minify.

@nbkhope My workaround for now is to `require('react-datepicker/dist/react-datepicker')` directly.

**Comment by yeziTesting** [comment]
the react 16.0.0 has not this problem
