### ISSUE TITLE
raw change event bubbles up when value is invalid, even though react-datepicker doesn't call onChange

### ISSUE THREAD

**Issue by jedwards1211** [Hacker0x01/react-datepicker#995]
If you do the following:

```js
function handleChangeOnParent(e) {
  console.log('parent got:', e)
}

function handleChange(newValue) {
  console.log(newValue)
}

ReactDOM.render(
  <span onChange={handleChangeOnParent}>
    <DatePicker selected={...} onChange={handleChange} />
  </span>,
  document.getElementById('root')
)
```
Then you select all in the text box and type `8` in it, then you'll see that `handleChangeOnParent` gets called with the raw change event, but `handleChange` doesn't get called.  I think this is likely to confuse developers, and it would be better to `stopPropagation` on the raw event and call `onChange` with the raw text.

**Comment by rafeememon** [comment]
`onChange` is meant to fire with a moment object when a valid date is entered; to listen to changes in raw text, use `onChangeRaw`.  We can't change the API of `onChange`.
